from a_student_finance import T
SLUG='asylum-residence-hub'
SRC=[('IND · Nieuwe wetten en regels asiel en nareis','https://ind.nl/nl/asiel-en-nareis-het-migratiepact-en-andere-ontwikkelingen/nieuwe-wetten-en-regels-asiel-en-nareis'),
('Rijksoverheid · Waar vind ik gratis hulp of advies bij een juridisch probleem? (juni 2026)','https://www.rijksoverheid.nl/vraag-en-antwoord/bescherming-van-consumenten/waar-kan-ik-terecht-voor-hulp-bij-een-juridisch-probleem-of-conflict'),
('VluchtelingenWerk Nederland · Juridische begeleiding','https://www.vluchtelingenwerk.nl/wat-wij-doen/juridische-begeleiding'),
('Juridisch Loket · Contact (gratis bellen 0800-8020)','https://www.juridischloket.nl/contact/'),
('Sociaal Werk Nederland · Sociaal raadslieden (kaart)','https://www.sociaalwerknederland.nl/sociaal-raadslieden'),
('Nationale ombudsman · Waarmee kunnen wij u helpen','https://www.nationaleombudsman.nl/'),
('Nationale ombudsman · IND: asiel en nareis','https://www.nationaleombudsman.nl/ind/asiel-en-nareis'),
('IND · Asiel aangevraagd voor 12 juni 2026','https://ind.nl/nl/asiel-en-nareis-het-migratiepact-en-andere-ontwikkelingen/asiel-aangevraagd-voor-12-juni-2026')]
AR=dict(title='مركز أدلة اللجوء والإقامة في هولندا 2026: كل الأدلة في مكان واحد، ومن أين تحصل على مساعدة بشرية مجانية',
crumb='مركز أدلة اللجوء والإقامة',
desc='صفحة تجمع أدلة اللجوء والإقامة ولمّ الشمل والتسجيل والوثائق والاندماج والإقامة الدائمة والجنسية، مع جدول «وضعي ← أي دليل أقرأ»، وقسم «أين أجد مساعدة بشرية»: VluchtelingenWerk Nederland وJuridisch Loket والمستشارون الاجتماعيون (sociaal raadslieden) والمحقق الوطني (Nationale ombudsman) بروابطها الرسمية وأرقام الهاتف المؤكدة.',
summary='<ol><li>ابدأ من جدول «وضعي ← أي دليل»: كل دليل مرتبط بمرحلة (طلب اللجوء، بعد الإقامة، لمّ الشمل، الوثائق، الاندماج، الإقامة الدائمة).</li><li>القواعد تغيّرت منذ <strong>12 يونيو 2026</strong> (نظام الحالتين). اقرأ أولاً <a href="/articles/asylum-two-status-system-2026.html">دليل نظام الحالتين</a>.</li><li>المساعدة المجانية: <strong>VluchtelingenWerk</strong> (مرافقة قانونية في كل مراكز الاستقبال)، <strong>Juridisch Loket</strong> (الاتصال المجاني <strong>0800-8020</strong> لأصحاب الدخل المنخفض)، <strong>sociaal raadslieden</strong> في كثير من البلديات، و<strong>Nationale ombudsman</strong> للشكاوى ضد الجهات الحكومية.</li><li>هذه الأدلة للتوعية وليست استشارة قانونية. قرار حالتك بيد IND والجهة المختصة.</li></ol>',
body=(
'<h2 id="start">من أين أبدأ؟ وضعي ← الدليل المناسب</h2>'
+T([['أنتظر قرار اللجوء أو قدّمت قبل 12 يونيو 2026','<a href="/articles/asylum-two-status-system-2026.html">نظام الحالتين للجوء 2026</a> (قسم «طلبات قبل 12 يونيو»)'],['حصلت على إقامة لجوء وأريد معرفة حالتي ووثيقتي','<a href="/articles/asylum-two-status-system-2026.html">نظام الحالتين للجوء 2026</a>'],['أريد لمّ شمل زوجتي وأطفالي (بعد اللجوء)','<a href="/articles/asylum-family-reunification.html">لمّ شمل عائلة اللاجئ (Nareis)</a> ثم <a href="/articles/asylum-two-status-system-2026.html">نظام الحالتين</a>'],['فاتتني مهلة nareis أو لا تنطبق عليّ، أو أريد لمّ شمل شريك','<a href="/articles/family-reunification-mvv-ind.html">لمّ الشمل مع الشريك: MVV والإقامة العادية</a>'],['وثائقي سورية وأحتاج تصديقاً وترجمة','<a href="/articles/syrian-documents-legalisation-translation.html">الوثائق السورية: التصديق والترجمة</a>'],['وصلت وأريد التسجيل في البلدية والحصول على BSN','<a href="/articles/bsn-municipality-registration.html">التسجيل في البلدية وBSN</a>، ثم <a href="/articles/digid-registration-guide.html">DigiD</a>'],['غيّرت عنواني','<a href="/articles/change-address-netherlands.html">تغيير العنوان</a>'],['أريد تعلم اللغة والاندماج','<a href="/articles/inburgering-integration-law-2026.html">الاندماج (Inburgering) 2026</a> و<a href="/articles/nt2-b1-exam-guide.html">امتحان NT2 وB1</a>'],['أريد معادلة شهادتي','<a href="/articles/diploma-evaluation-sbb.html">تقييم الشهادات والمعادلة</a>'],['وصلتني رسالة قرار لا أوافق عليها','<a href="/articles/bezwaar-objection-letter.html">الاعتراض على قرار حكومي</a>'],['أحتاج محامياً أو مساعدة قانونية','<a href="/articles/legal-aid-lawyer-toevoeging.html">المحامي المجاني (toevoeging)</a>'],['مرّت 5 سنوات من الإقامة وأفكر بالإقامة الدائمة','<a href="/articles/eu-permanent-residence-netherlands.html">الإقامة الدائمة ومقيم طويل الأمد</a>'],['أفكر بالجنسية','<a href="/articles/dutch-naturalisation-guide.html">التجنّس في هولندا</a>'],['أخشى الاحتيال أو وسطاء يعدون بتسريع الطلب','<a href="/articles/scams-phishing-netherlands.html">الاحتيال في هولندا</a>']],['وضعي','الدليل'])
+'<p>الجدول مجرد دليل للتوجيه وليس تقييماً لحالتك.</p>'
'<h2 id="all">كل أدلة اللجوء والإقامة</h2><h3>اللجوء ولمّ الشمل</h3><ul><li><a href="/articles/asylum-two-status-system-2026.html">نظام الحالتين للجوء 2026</a></li><li><a href="/articles/asylum-family-reunification.html">لمّ شمل عائلة اللاجئ (Nareis)</a></li><li><a href="/articles/family-reunification-mvv-ind.html">لمّ الشمل مع الشريك: MVV والإقامة العادية</a></li></ul><h3>الوثائق والتسجيل</h3><ul><li><a href="/articles/syrian-documents-legalisation-translation.html">الوثائق السورية: التصديق والترجمة المحلفة</a></li><li><a href="/articles/bsn-municipality-registration.html">التسجيل في البلدية والحصول على BSN</a></li><li><a href="/articles/digid-registration-guide.html">DigiD</a></li><li><a href="/articles/change-address-netherlands.html">تغيير العنوان</a></li><li><a href="/articles/diploma-evaluation-sbb.html">تقييم الشهادات والمعادلة</a></li></ul><h3>الاندماج والإقامة الدائمة والجنسية</h3><ul><li><a href="/articles/inburgering-integration-law-2026.html">الاندماج (Inburgering) 2026</a></li><li><a href="/articles/nt2-b1-exam-guide.html">امتحان NT2 وB1</a></li><li><a href="/articles/eu-permanent-residence-netherlands.html">الإقامة الدائمة ووضع المقيم طويل الأمد</a></li><li><a href="/articles/dutch-naturalisation-guide.html">التجنّس في هولندا</a></li></ul><h3>الحقوق والمساعدة</h3><ul><li><a href="/articles/bezwaar-objection-letter.html">الاعتراض على قرار حكومي</a></li><li><a href="/articles/legal-aid-lawyer-toevoeging.html">المحامي المجاني (toevoeging)</a></li><li><a href="/articles/scams-phishing-netherlands.html">الاحتيال في هولندا</a></li></ul>'
'<h2 id="help">أين أجد مساعدة بشرية مجانية؟</h2><p>القواعد معقدة وتتغير، وحالتك قد تختلف عن الأمثلة العامة. هذه جهات رسمية أو مذكورة في صفحات حكومية. الأرقام والمواعيد من مواقعها بتاريخ 8 أكتوبر 2026؛ تحقق منها قبل الاتصال.</p>'
+T([['<strong>VluchtelingenWerk Nederland</strong><br><a href="https://www.vluchtelingenwerk.nl/" rel="noopener">vluchtelingenwerk.nl</a><br><a href="https://www.vluchtelingenwerk.nl/wat-wij-doen/juridische-begeleiding" rel="noopener">المرافقة القانونية</a>','منظمة غير حكومية. تقول إنها تقدم مرافقة قانونية للاجئين <strong>في كل مراحل إجراء اللجوء</strong> وفي إجراء لمّ الشمل، وتتواجد في <strong>كل مراكز الاستقبال</strong> بساعات استقبال. تشرح الإجراء وتساعد في طلب الوثائق وفهم رسائل IND أو المحامي. لا تُؤوي طالبي اللجوء (هذا عمل COA).'],['<strong>Juridisch Loket</strong><br><a href="https://www.juridischloket.nl/" rel="noopener">juridischloket.nl</a><br><a href="https://www.juridischloket.nl/contact/" rel="noopener">الاتصال والفروع</a>','معلومات ونماذج رسائل لكل شخص. النصيحة الشخصية المجانية لمن <strong>دخله منخفض ومدخراته قليلة</strong>. هاتف مجاني <strong>0800-8020</strong> من الإثنين إلى الجمعة 09:00–17:00. من خارج هولندا: +31 30 239 2030 (بتكلفة المكالمة العادية). لديه فروع بساعات استقبال دون موعد في مدن كثيرة، وقد يكون مزدحماً.'],['<strong>المستشارون الاجتماعيون (sociaal raadslieden)</strong><br><a href="https://www.sociaalwerknederland.nl/sociaal-raadslieden" rel="noopener">خريطة sociaal raadslieden</a>','يساعدون سكان البلدية مجاناً وبسرّية في مشكلات مالية أو قانونية: الضرائب، الإعانات والبدلات، السكن، المرافق المحلية، وبدء مساعدة الديون. <strong>ليست كل البلديات لديها هذه الخدمة</strong> وما يقدمونه يختلف من بلدية لأخرى: اسأل بلديتك.'],['<strong>Nationale ombudsman</strong><br><a href="https://www.nationaleombudsman.nl/" rel="noopener">nationaleombudsman.nl</a><br><a href="https://www.nationaleombudsman.nl/ind/asiel-en-nareis" rel="noopener">IND: اللجوء وnareis</a>','جهة مستقلة تساعد حين «يسوء الأمر بينك وبين الحكومة»، ولديها صفحات عن IND (اللجوء، nareis، التأشيرة، الإقامة) وعن البلدية وتسجيل BRP ونماذج رسائل. هاتف <strong>0800-33 55 555</strong> في أيام العمل 09:00–17:00. راجع على موقعها «هل يمكننا معالجة شكواك؟» قبل التقديم. ليست جهة قانونية تمثلك في القضايا.']],['الجهة','ماذا تقدم'])
+'<h3>جهات أخرى مفيدة</h3><ul><li><strong>Raad voor Rechtsbijstand:</strong> ترتب محامياً في إجراء اللجوء، وهو عادةً مجاني حسب IND. انظر <a href="/articles/legal-aid-lawyer-toevoeging.html">المحامي المجاني</a>.</li><li><strong>بلديتك:</strong> اسأل عن sociaal raadslieden وعن دعم الاندماج.</li><li><strong>IND:</strong> صفحات الحالة ومدد الانتظار تتحدث باستمرار على ind.nl.</li></ul>'
'<h2 id="tips">كيف تستعد للاتصال بجهة مساعدة؟</h2><ol><li>جهّز <strong>رقم V (V-nummer) ورقم BSN</strong> إن وُجدا، وقرار IND أو البطاقة وتاريخها.</li><li>اكتب <strong>الأسئلة والتواريخ</strong> بالترتيب: متى قدّمت؟ متى وصلت الرسالة؟ ما المهلة المذكورة؟</li><li>احتفظ بنسخ من كل الرسائل. لا ترسل بياناتك الحساسة عبر وسائل غير آمنة.</li><li>اطلب مترجماً إن احتجت، واسأل عن مواعيد الاستقبال دون موعد.</li><li>لا تدفع مالاً لأحد يعدك بتسريع قرار IND.</li></ol>'
'<h2 id="mistakes">أخطاء شائعة</h2><ol><li>الاعتماد على منشورات مواقع التواصل وأخبار قديمة بدل IND.</li><li>الانتظار حتى تقترب المهلة قبل طلب المساعدة.</li><li>الاتصال بالجهة الخطأ: المحقق الوطني لا يحل محل المحامي، وJuridisch Loket لا يستبدل VluchtelingenWerk في شؤون اللجوء وحدها. استخدم الجدول أعلاه.</li><li>تجاهل رسائل IND أو عدم تحديث العنوان.</li></ol>'
'<h2 id="related">أدلة مرتبطة</h2><ul><li><a href="/articles/asylum-two-status-system-2026.html">نظام الحالتين للجوء 2026</a></li><li><a href="/articles/syrian-documents-legalisation-translation.html">الوثائق السورية: التصديق والترجمة</a></li><li><a href="/articles/asylum-family-reunification.html">لمّ شمل عائلة اللاجئ</a></li><li><a href="/articles/legal-aid-lawyer-toevoeging.html">المحامي المجاني</a></li></ul>'),
faq=[('من أين أبدأ بعد حصولي على الإقامة؟','ابدأ بدليل نظام الحالتين لمعرفة حالتك ووثيقتك، ثم دليل التسجيل في البلدية وBSN، ثم الاندماج. الجدول في أعلى هذه الصفحة يرشدك.'),
('هل الاستشارة من VluchtelingenWerk مجانية؟','تقول المنظمة إن المرافقة القانونية متاحة للاجئين في كل مراحل الإجراء. اسأل عن مكتب منطقتك أو عن ساعات الاستقبال في مركزك.'),
('هل Juridisch Loket مجاني للجميع؟','المعلومات على الموقع للجميع. النصيحة الشخصية المجانية لمن دخله منخفض ومدخراته قليلة. رقم الاتصال المجاني 0800-8020.'),
('ما هم sociaal raadslieden؟','موظفون يقدمون مساعدة مجانية وسرية في مسائل مالية وقانونية (ضرائب، إعانات، سكن). متوفرون في كثير من البلديات لا كلها: اسأل بلديتك.'),
('متى أتصل بـNationale ombudsman؟','حين تكون لديك شكوى من تعامل جهة حكومية (مثل IND أو البلدية)، وبعد قراءة صفحة «هل يمكننا معالجة شكواك؟» على موقعها. هاتفها 0800-33 55 555.'),
('هل يمثلني المحقق الوطني أمام IND؟','لا؛ يعالج الشكاوى المتعلقة بسلوك الجهات الحكومية وليس قضيتك القانونية. للتمثيل راجع محامياً أو VluchtelingenWerk.'),
('هل المحامي في إجراء اللجوء مجاني؟','حسب IND، ترتب Raad voor Rechtsbijstand محامياً وهو عادةً مجاني.'),
('ماذا أفعل إن لم أفهم رسالة IND؟','اتصل بـVluchtelingenWerk أو Juridisch Loket أو sociaal raadslieden، وأحضر الرسالة وتاريخها.'),
('هل يمكنني دفع مال لتسريع القرار؟','لا. لا تدفع لوسطاء يعدون بذلك؛ هذا احتيال شائع.')],
src_note='راجعنا مواقع VluchtelingenWerk وJuridisch Loket وNationale ombudsman وصفحة Rijksoverheid عن المساعدة القانونية المجانية وصفحات IND في 8 أكتوبر 2026. لم نجد رقم هاتف معلناً لـVluchtelingenWerk على الصفحة التي راجعناها فلم نذكره. أرقام الهواتف وساعات العمل قد تتغير؛ تحقق منها. نذكر هذه الجهات للتعريف بها ولا نضمن نتيجة أي طلب.')
NL=dict(title='Hub asiel en verblijf 2026: alle gidsen op één plek en waar u gratis menselijke hulp vindt',
crumb='Hub asiel en verblijf',
desc='Overzicht van alle gidsen over asiel, verblijf, gezinshereniging, inschrijven, documenten, inburgering, permanent verblijf en naturalisatie, met een tabel “mijn situatie → welke gids”, en een onderdeel “waar vind ik menselijke hulp”: VluchtelingenWerk Nederland, het Juridisch Loket, sociaal raadslieden en de Nationale ombudsman, met officiële links en gecontroleerde telefoonnummers.',
summary='<ol><li>Begin bij de tabel “mijn situatie → welke gids”: elke gids hoort bij een fase (asielprocedure, na de vergunning, gezinshereniging, documenten, inburgering, permanent verblijf).</li><li>De regels zijn veranderd sinds <strong>12 juni 2026</strong> (tweestatusstelsel). Lees eerst de <a href="/nl/articles/asylum-two-status-system-2026.html">gids over het tweestatusstelsel</a>.</li><li>Gratis hulp: <strong>VluchtelingenWerk</strong> (juridische begeleiding in alle opvanglocaties), het <strong>Juridisch Loket</strong> (gratis bellen <strong>0800-8020</strong> bij laag inkomen), <strong>sociaal raadslieden</strong> in veel gemeenten en de <strong>Nationale ombudsman</strong> voor klachten over de overheid.</li><li>Deze gidsen zijn voorlichting, geen juridisch advies. De IND of de bevoegde instantie beslist over uw situatie.</li></ol>',
body=(
'<h2 id="start">Waar begin ik? Mijn situatie → de juiste gids</h2>'
+T([['Ik wacht op een asielbesluit of vroeg aan vóór 12 juni 2026','<a href="/nl/articles/asylum-two-status-system-2026.html">Tweestatusstelsel asiel 2026</a> (onderdeel “asiel aangevraagd vóór 12 juni”)'],['Ik heb een asielvergunning en wil mijn status en pasje begrijpen','<a href="/nl/articles/asylum-two-status-system-2026.html">Tweestatusstelsel asiel 2026</a>'],['Ik wil mijn partner en kinderen laten komen (na asiel)','<a href="/nl/articles/asylum-family-reunification.html">Gezinshereniging asiel (nareis)</a> en <a href="/nl/articles/asylum-two-status-system-2026.html">tweestatusstelsel</a>'],['Ik zit buiten de nareistermijn of wil een partner laten komen','<a href="/nl/articles/family-reunification-mvv-ind.html">Gezinshereniging met partner: mvv en regulier verblijf</a>'],['Mijn documenten zijn Syrisch en moeten gelegaliseerd en vertaald worden','<a href="/nl/articles/syrian-documents-legalisation-translation.html">Syrische documenten legaliseren en vertalen</a>'],['Ik ben aangekomen en moet me inschrijven bij de gemeente (BSN)','<a href="/nl/articles/bsn-municipality-registration.html">Inschrijven bij de gemeente en BSN</a>, daarna <a href="/nl/articles/digid-registration-guide.html">DigiD</a>'],['Ik ben verhuisd','<a href="/nl/articles/change-address-netherlands.html">Adres wijzigen</a>'],['Ik wil inburgeren en de taal leren','<a href="/nl/articles/inburgering-integration-law-2026.html">Inburgeren in 2026</a> en <a href="/nl/articles/nt2-b1-exam-guide.html">NT2- en B1-examen</a>'],['Ik wil mijn diploma laten waarderen','<a href="/nl/articles/diploma-evaluation-sbb.html">Diplomawaardering en gelijkwaardigheid</a>'],['Ik ben het niet eens met een besluit','<a href="/nl/articles/bezwaar-objection-letter.html">Bezwaar maken tegen een besluit</a>'],['Ik zoek een advocaat of juridische hulp','<a href="/nl/articles/legal-aid-lawyer-toevoeging.html">Gratis advocaat (toevoeging)</a>'],['Ik woon 5 jaar hier en denk aan permanent verblijf','<a href="/nl/articles/eu-permanent-residence-netherlands.html">Permanent verblijf en EU-langdurig ingezetene</a>'],['Ik denk aan het Nederlanderschap','<a href="/nl/articles/dutch-naturalisation-guide.html">Naturalisatie</a>'],['Ik vrees oplichting of tussenpersonen die snelheid beloven','<a href="/nl/articles/scams-phishing-netherlands.html">Oplichting in Nederland</a>']],['Mijn situatie','Gids'])
+'<p>De tabel is alleen een wegwijzer, geen beoordeling van uw situatie.</p>'
'<h2 id="all">Alle gidsen over asiel en verblijf</h2><h3>Asiel en gezinshereniging</h3><ul><li><a href="/nl/articles/asylum-two-status-system-2026.html">Tweestatusstelsel asiel 2026</a></li><li><a href="/nl/articles/asylum-family-reunification.html">Gezinshereniging asiel (nareis)</a></li><li><a href="/nl/articles/family-reunification-mvv-ind.html">Gezinshereniging met partner: mvv en regulier verblijf</a></li></ul><h3>Documenten en inschrijving</h3><ul><li><a href="/nl/articles/syrian-documents-legalisation-translation.html">Syrische documenten legaliseren en vertalen</a></li><li><a href="/nl/articles/bsn-municipality-registration.html">Inschrijven bij de gemeente en BSN</a></li><li><a href="/nl/articles/digid-registration-guide.html">DigiD</a></li><li><a href="/nl/articles/change-address-netherlands.html">Adres wijzigen</a></li><li><a href="/nl/articles/diploma-evaluation-sbb.html">Diplomawaardering en gelijkwaardigheid</a></li></ul><h3>Inburgering, permanent verblijf en naturalisatie</h3><ul><li><a href="/nl/articles/inburgering-integration-law-2026.html">Inburgeren in 2026</a></li><li><a href="/nl/articles/nt2-b1-exam-guide.html">NT2- en B1-examen</a></li><li><a href="/nl/articles/eu-permanent-residence-netherlands.html">Permanent verblijf en EU-langdurig ingezetene</a></li><li><a href="/nl/articles/dutch-naturalisation-guide.html">Naturalisatie</a></li></ul><h3>Rechten en hulp</h3><ul><li><a href="/nl/articles/bezwaar-objection-letter.html">Bezwaar maken tegen een besluit</a></li><li><a href="/nl/articles/legal-aid-lawyer-toevoeging.html">Gratis advocaat (toevoeging)</a></li><li><a href="/nl/articles/scams-phishing-netherlands.html">Oplichting in Nederland</a></li></ul>'
'<h2 id="help">Waar vind ik gratis menselijke hulp?</h2><p>De regels zijn ingewikkeld en veranderen, en uw situatie kan afwijken van de algemene voorbeelden. Hieronder staan organisaties met een eigen officiële website of vermelding op overheidspagina’s. Telefoonnummers en tijden komen van hun sites van 8 oktober 2026; controleer ze vóór u belt.</p>'
+T([['<strong>VluchtelingenWerk Nederland</strong><br><a href="https://www.vluchtelingenwerk.nl/" rel="noopener">vluchtelingenwerk.nl</a><br><a href="https://www.vluchtelingenwerk.nl/wat-wij-doen/juridische-begeleiding" rel="noopener">Juridische begeleiding</a>','Ngo. Volgens de organisatie kunnen vluchtelingen in <strong>alle stadia van de asielprocedure</strong> en de gezinsherenigingsprocedure rekenen op juridische begeleiding; medewerkers zijn in <strong>iedere opvanglocatie</strong> aanwezig met spreekuren. Ze geven voorlichting over de procedure, helpen bij het opvragen van documenten en leggen brieven van de IND of de advocaat uit. VluchtelingenWerk vangt zelf geen asielzoekers op (dat doet het COA).'],['<strong>Juridisch Loket</strong><br><a href="https://www.juridischloket.nl/" rel="noopener">juridischloket.nl</a><br><a href="https://www.juridischloket.nl/contact/" rel="noopener">Contact en vestigingen</a>','Informatie en voorbeeldbrieven voor iedereen. Persoonlijk advies is gratis bij een <strong>laag inkomen en weinig spaargeld</strong>. Gratis bellen <strong>0800-8020</strong>, ma–vr 09.00–17.00. Vanuit het buitenland: +31 30 239 2030 (normale belkosten). Vestigingen met inloopspreekuur zonder afspraak in veel steden; het kan druk zijn.'],['<strong>Sociaal raadslieden</strong><br><a href="https://www.sociaalwerknederland.nl/sociaal-raadslieden" rel="noopener">Kaart sociaal raadslieden</a>','Gratis, laagdrempelige en vertrouwelijke hulp voor inwoners van een gemeente bij financiële of juridische problemen: belastingen, uitkeringen en toeslagen, wonen, lokale voorzieningen, starten van schuldhulp. <strong>Niet elke gemeente heeft ze</strong> en wat ze doen verschilt per gemeente: vraag het uw gemeente.'],['<strong>Nationale ombudsman</strong><br><a href="https://www.nationaleombudsman.nl/" rel="noopener">nationaleombudsman.nl</a><br><a href="https://www.nationaleombudsman.nl/ind/asiel-en-nareis" rel="noopener">IND: asiel en nareis</a>','Onafhankelijk loket als het “misgaat tussen u en de overheid”. Heeft pagina’s over de IND (asiel en nareis, visum, verblijfsvergunning), over de gemeente en de BRP-inschrijving, en voorbeeldbrieven. Bellen kan op <strong>0800-33 55 555</strong>, op werkdagen 09.00–17.00. Lees op de site “Mogen wij uw klacht behandelen?” vóór u indient. Geen juridisch vertegenwoordiger in uw zaak.']],['Organisatie','Wat ze doen'])
+'<h3>Andere nuttige loketten</h3><ul><li><strong>Raad voor Rechtsbijstand:</strong> regelt een advocaat in de asielprocedure; dit is volgens de IND meestal gratis. Zie <a href="/nl/articles/legal-aid-lawyer-toevoeging.html">Gratis advocaat</a>.</li><li><strong>Uw gemeente:</strong> vraag naar sociaal raadslieden en ondersteuning bij inburgering.</li><li><strong>IND:</strong> actuele informatie en wachttijden staan op ind.nl.</li></ul>'
'<h2 id="tips">Zo bereidt u het contact voor</h2><ol><li>Houd uw <strong>V-nummer en BSN</strong> bij de hand (als u die hebt), plus het IND-besluit of pasje met data.</li><li>Schrijf <strong>vragen en data</strong> op: wanneer aangevraagd, wanneer de brief kwam, welke termijn staat erin?</li><li>Bewaar kopieën van alle brieven. Deel gevoelige gegevens niet via onveilige kanalen.</li><li>Vraag om een tolk als u die nodig hebt en vraag naar inloopspreekuren zonder afspraak.</li><li>Betaal nooit iemand die belooft dat de IND sneller beslist.</li></ol>'
'<h2 id="mistakes">Veelgemaakte fouten</h2><ol><li>Afgaan op social media of oud nieuws in plaats van de IND.</li><li>Te laat om hulp vragen, vlak voor een termijn.</li><li>Bij de verkeerde organisatie aankloppen: de Nationale ombudsman vervangt geen advocaat en het Juridisch Loket vervangt VluchtelingenWerk niet bij asielzaken. Gebruik de tabel hierboven.</li><li>Post van de IND negeren of een adreswijziging niet doorgeven.</li></ol>'
'<h2 id="related">Gerelateerde gidsen</h2><ul><li><a href="/nl/articles/asylum-two-status-system-2026.html">Tweestatusstelsel asiel 2026</a></li><li><a href="/nl/articles/syrian-documents-legalisation-translation.html">Syrische documenten legaliseren en vertalen</a></li><li><a href="/nl/articles/asylum-family-reunification.html">Gezinshereniging asiel (nareis)</a></li><li><a href="/nl/articles/legal-aid-lawyer-toevoeging.html">Gratis advocaat</a></li></ul>'),
faq=[('Waar begin ik na mijn verblijfsvergunning?','Begin met de gids over het tweestatusstelsel om uw status en pasje te begrijpen, daarna inschrijven bij de gemeente en BSN en inburgeren. De tabel bovenaan helpt u op weg.'),
('Is hulp van VluchtelingenWerk gratis?','Volgens de organisatie kunnen vluchtelingen rekenen op juridische begeleiding in alle stadia van de procedure. Vraag naar de vestiging in uw regio of het spreekuur op uw locatie.'),
('Is het Juridisch Loket voor iedereen gratis?','Informatie op de site is er voor iedereen. Persoonlijk advies is gratis bij laag inkomen en weinig spaargeld. Gratis bellen kan op 0800-8020.'),
('Wat zijn sociaal raadslieden?','Medewerkers die gratis en vertrouwelijk helpen bij financiële en juridische vragen (belasting, toeslagen, wonen). Er zijn ze in veel, niet in alle gemeenten: vraag het uw gemeente.'),
('Wanneer bel ik de Nationale ombudsman?','Bij een klacht over hoe een overheidsinstantie (zoals de IND of de gemeente) met u omgaat, na lezing van “Mogen wij uw klacht behandelen?”. Telefoon 0800-33 55 555.'),
('Vertegenwoordigt de Nationale ombudsman mij bij de IND?','Nee. De ombudsman behandelt klachten over het handelen van de overheid, niet uw juridische procedure. Voor vertegenwoordiging: advocaat of VluchtelingenWerk.'),
('Is een advocaat in de asielprocedure gratis?','Volgens de IND regelt de Raad voor Rechtsbijstand een advocaat voor u; dit is meestal gratis.'),
('Wat als ik een IND-brief niet begrijp?','Neem de brief met datum mee naar VluchtelingenWerk, het Juridisch Loket of de sociaal raadslieden.'),
('Kan ik betalen om het besluit sneller te krijgen?','Nee. Betaal niemand die dat belooft; dit is een bekende vorm van oplichting.')],
src_note='Gecontroleerd op de sites van VluchtelingenWerk, het Juridisch Loket, de Nationale ombudsman, Rijksoverheid en de IND op 8 oktober 2026. Voor VluchtelingenWerk stond op de bekeken pagina geen telefoonnummer, dus we noemen er geen. Telefoonnummers en openingstijden kunnen wijzigen: controleer ze. Deze organisaties worden genoemd ter informatie; wij kunnen geen uitkomst garanderen.')
AR['seo_title']='مركز أدلة اللجوء والإقامة في هولندا 2026'
AR['desc']='كل أدلة اللجوء والإقامة ولمّ الشمل والجنسية في مكان واحد، مع جدول «وضعي ← أي دليل أقرأ» وأين تجد مساعدة بشرية مجانية.'
NL['seo_title']='Hub asiel en verblijf 2026: alle gidsen'
NL['desc']='Alle gidsen over asiel, verblijf, gezinshereniging en naturalisatie op één plek, met “mijn situatie → welke gids” en waar u gratis hulp vindt.'
#xlink
AR['body']+='<p><strong>مصطلح غير مفهوم في رسالتك؟</strong> ابحث عنه في <a href="/articles/dutch-government-terms-glossary.html">قاموس المصطلحات الحكومية الهولندية</a> (141 مصطلحاً مع النطق والمعنى).</p><p><strong>جرّب الحاسبة:</strong> <a href="/calculators/zorgtoeslag.html">حاسبة zorgtoeslag 2026</a> تقدّر بدلك من دخلك وأصولك.</p><p><strong>جرّب الحاسبة:</strong> <a href="/calculators/kindgebonden-budget.html">حاسبة kindgebonden budget 2026</a> تقدّر المبلغ حسب الدخل وعدد الأطفال وأعمارهم.</p>'
NL['body']+='<p><strong>Een woord in uw brief niet begrepen?</strong> Zoek het op in <a href="/nl/articles/dutch-government-terms-glossary.html">Overheidstaal uitgelegd</a> (141 begrippen met het Arabische woord).</p><p><strong>Probeer de rekenhulp:</strong> <a href="/nl/calculators/zorgtoeslag.html">Zorgtoeslag berekenen 2026</a> geeft een schatting op basis van inkomen en vermogen.</p><p><strong>Probeer de rekenhulp:</strong> <a href="/nl/calculators/kindgebonden-budget.html">Kindgebonden budget berekenen 2026</a> geeft een schatting per jaar en maand.</p>'
