from a_student_finance import T
SLUG='bezwaar-objection-letter'
R='https://www.rijksoverheid.nl/'
SRC=[('Rijksoverheid · Hoe maak ik bezwaar tegen een beslissing van de overheid?',R+'vraag-en-antwoord/bezwaar-en-beroep/bezwaar-tegen-beslissing-overheid'),
('Rijksoverheid · Wat gebeurt er na een bezwaar?',R+'vraag-en-antwoord/bezwaar-en-beroep/na-een-bezwaar'),
('Rijksoverheid · Beslissing op aanvraag of bezwaar te laat (dwangsom)',R+'vraag-en-antwoord/bezwaar-en-beroep/beslissing-aanvraag-bezwaar-te-laat'),
('Wetten.nl · Algemene wet bestuursrecht (geldend 2026)','https://wetten.overheid.nl/BWBR0005537/2026-01-01'),
('Ondernemersplein (overheid.nl) · Bezwaar en beroep tegen beslissing van de overheid','https://ondernemersplein.overheid.nl/wetten-en-regels/bezwaar-en-beroep-tegen-beslissing-van-de-overheid/'),
('De Rechtspraak · Niet eens met beslissing overheidsorganisatie (beroepsprocedure)','https://www.rechtspraak.nl/organisatie-en-contact/rechtsgebieden/bestuursrecht/procedures/beroepsprocedure'),
('De Rechtspraak · Griffierecht in het bestuursrecht (tarieven 2026)','https://www.rechtspraak.nl/naar-de-rechter/kosten-rechtszaak/griffierecht/griffierecht-bestuursrecht'),
('Belastingdienst · Mijn toeslag klopt niet, moet ik bezwaar maken?','https://www.belastingdienst.nl/wps/wcm/connect/nl/toeslagen/content/mijn-toeslag-klopt-niet'),
('Belastingdienst · Bezwaar voor particulieren','https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/themaoverstijgend/programmas_en_formulieren/bezwaar-voor-particulieren'),
('UWV · Bezwaarprocedure','https://www.uwv.nl/nl/klacht-melding-bezwaar/bezwaar/bezwaarprocedure'),
('IND · Bezwaar maken of in beroep gaan','https://ind.nl/nl/na-uw-aanvraag/bezwaar-maken-of-in-beroep-gaan'),
('CJIB · Ik ben het niet eens met een verkeersboete','https://www.cjib.nl/ik-ben-het-niet-eens-met-een-verkeersboete'),
('Rijksoverheid · Klacht indienen bij de Nationale ombudsman',R+'vraag-en-antwoord/kwaliteit-en-integriteit-overheidsinstanties/hoe-kan-ik-een-klacht-indienen-bij-de-nationale-ombudsman'),
('Het Juridisch Loket · Contact','https://www.juridischloket.nl/contact/')]

PRE='<pre dir="ltr" lang="nl" style="white-space:pre-wrap;text-align:left;direction:ltr;background:#f5f5f7;color:#1d1d1f;border:1px solid #dce1e6;border-radius:12px;padding:1rem;font-size:.9rem;line-height:1.6;overflow-wrap:anywhere">'
LETTER=(PRE+
'[Voornaam en achternaam]\n'
'[Straat en huisnummer]\n'
'[Postcode en woonplaats]\n'
'[Telefoonnummer en e-mailadres]\n'
'[BSN of klantnummer, alleen als de organisatie daarom vraagt]\n\n'
'Aan: [naam van de organisatie], afdeling Bezwaar\n'
'[adres uit de beslissing]\n\n'
'[Woonplaats], [datum van vandaag]\n\n'
'Betreft: bezwaarschrift tegen uw besluit van [datum besluit], kenmerk [kenmerk of dossiernummer]\n\n'
'Geachte heer, mevrouw,\n\n'
'Hierbij maak ik bezwaar tegen uw besluit van [datum besluit] met kenmerk [kenmerk]. '
'In dit besluit heeft u [korte omschrijving, bijvoorbeeld: mijn aanvraag voor ... afgewezen / mijn ... herzien en een bedrag van € ... teruggevorderd]. '
'Een kopie van het besluit stuur ik mee.\n\n'
'Ik ben het niet eens met dit besluit, omdat:\n'
'1. [reden 1, bijvoorbeeld: u bent uitgegaan van een verkeerd inkomen; mijn werkelijke inkomen in ... was € ...]\n'
'2. [reden 2, bijvoorbeeld: u heeft geen rekening gehouden met mijn situatie ...]\n'
'3. [reden 3, met verwijzing naar de bijlagen]\n\n'
'Ik verzoek u daarom het besluit te herroepen en [wat u wilt, bijvoorbeeld: mijn aanvraag alsnog toe te kennen].\n\n'
'[Alleen bij een pro-forma bezwaar:] De gronden van mijn bezwaar stuur ik zo snel mogelijk na. Ik verzoek u mij daarvoor een redelijke termijn te geven.\n\n'
'Ik wil graag worden gehoord over mijn bezwaar.\n'
'[Optioneel:] Ik verzoek u om vergoeding van de kosten die ik in verband met dit bezwaar redelijkerwijs heb moeten maken.\n\n'
'Met vriendelijke groet,\n\n'
'[handtekening]\n'
'[voornaam en achternaam]\n\n'
'Bijlagen:\n'
'- kopie van het besluit van [datum]\n'
'- [bewijsstukken, bijvoorbeeld loonstroken, jaaropgaaf, huurcontract, medische verklaring]'
'</pre>')

AR=dict(title='الاعتراض على قرار حكومي في هولندا (bezwaar) 2026: مهلة 6 أسابيع، ما يجب أن تحتويه الرسالة، الغرامة اليومية حتى 1,442 يورو، والمحكمة برسوم 54 يورو — مع نموذج رسالة جاهز',
crumb='الاعتراض على قرار حكومي (bezwaar)',
seo_title='الاعتراض على قرار حكومي bezwaar 2026',
desc='الاعتراض (bezwaar) على قرار من Toeslagen أو UWV أو البلدية: مهلة 6 أسابيع، ما يجب أن تحتويه الرسالة، الغرامة اليومية حتى 1,442 يورو، مع نموذج رسالة جاهز.',
summary='<ol><li>عندك <strong>6 أسابيع</strong> للاعتراض، وتُحسب من <strong>تاريخ القرار</strong> المكتوب على الرسالة، لا من يوم قراءتها (المادة 6:7 Awb).</li><li>الرسالة يجب أن تحتوي: <strong>اسمك وعنوانك، التاريخ، وصف القرار، أسباب اعتراضك، وتوقيعك</strong> (المادة 6:5 Awb). الاعتراض <strong>مجاني</strong> ولا تحتاج محامياً.</li><li>لا تعرف الأسباب بعد؟ أرسل <strong>اعتراضاً مبدئياً (pro forma)</strong> قبل نهاية المهلة، وأكمل الأسباب لاحقاً.</li><li>الجهة تقرر عادة خلال <strong>6 أسابيع</strong> بعد نهاية مهلة الاعتراض، أو <strong>12 أسبوعاً</strong> إن كانت هناك لجنة استشارية، ويمكن التمديد <strong>6 أسابيع</strong> كحد أقصى.</li><li>تأخرت الجهة؟ أرسل <strong>إنذاراً (ingebrekestelling)</strong>؛ بعد <strong>أسبوعين</strong> تبدأ غرامة يومية تصل إلى <strong>1,442 يورو</strong> كحد أقصى.</li><li>رُفض اعتراضك؟ تستطيع الطعن (<strong>beroep</strong>) أمام المحكمة خلال <strong>6 أسابيع</strong>. رسوم المحكمة للأفراد في 2026: <strong>54 يورو</strong> (إعانات وبدلات) أو <strong>200 يورو</strong> (قضايا أخرى)، وتُعاد إليك إن ربحت.</li></ol>',
body=(
'<h2 id="what">ما هو الاعتراض (bezwaar) وعلى ماذا تعترض؟</h2>'
+'<p>الـ<strong>besluit</strong> هو قرار رسمي مكتوب من جهة حكومية يخصّك أنت: رفض أو تخفيض بدل (toeslag)، استرداد مبلغ، تقدير ضريبي نهائي، قرار من UWV بشأن WW أو WIA، قرار من SVB بشأن kinderbijslag أو AOW، قرار من البلدية بشأن bijstand أو Wmo، أو قرار من IND. إن كنت غير موافق، فالخطوة الأولى في الغالب هي <strong>bezwaar</strong>: تطلب من الجهة نفسها أن تعيد النظر في قرارها.</p>'
+'<ul><li><strong>الاعتراض مجاني</strong> ولا يلزمك محامٍ، لكن يحق لك أن تستعين بمحامٍ أو بشخص تثق به.</li><li>في آخر القرار توجد عادة فقرة <strong>«Bezwaar maken?»</strong> أو <strong>«Bent u het niet eens?»</strong> تشرح أين وكيف تعترض. اقرأها أولاً، فهي تتقدم على أي دليل عام.</li><li><strong>القرار يبقى سارياً</strong> أثناء الاعتراض. UWV يقول ذلك صراحة: ما دام لم يصدر قرار على اعتراضك، فالقرار الأصلي هو المعمول به. فإن كان عليك دفع مبلغ، اسأل الجهة عن تأجيل الدفع.</li><li>أحياناً يكون الطريق <strong>administratief beroep</strong> لدى جهة أخرى بدلاً من bezwaar. هذا أيضاً مكتوب في القرار.</li></ul>'
+'<h2 id="deadline">المهلة: 6 أسابيع، ومن أي يوم تبدأ؟</h2>'
+'<p>المادة <strong>6:7 Awb</strong>: مهلة تقديم الاعتراض <strong>ستة أسابيع</strong>. وتقول الحكومة إنها تُحسب من <strong>تاريخ القرار</strong> المكتوب على الرسالة. أي إن تأخّر البريد أو تأخرت أنت في فتح الرسالة، فالمهلة تجري رغم ذلك.</p>'
+'<ul><li><strong>Toeslagen</strong>: الاعتراض على الحساب النهائي (definitieve berekening) خلال 6 أسابيع من التاريخ المكتوب عليه.</li><li><strong>IND</strong>: إن حصلت على الإقامة لكنك غير موافق على جزء منها، فاعترض خلال <strong>4 أسابيع</strong> من تاريخ استلامك وثيقة الإقامة، حسب صفحة IND. في القضايا الأخرى المهلة مكتوبة في القرار.</li><li><strong>مخالفات المرور (CJIB)</strong> لها طريق آخر: الطعن لدى النيابة (officier van justitie) خلال 6 أسابيع. انظر <a href="/articles/traffic-fines-cjib.html">دليل المخالفات المرورية</a>.</li><li><strong>تأخرت؟</strong> يُرفض الاعتراض عادة شكلاً (niet-ontvankelijk). يُقبل فقط إن كان التأخير ليس بخطئك (verschoonbaar)، مثل أن القرار لم يصلك أصلاً. اكتب السبب مع الأدلة.</li><li>أرسل بالبريد المسجل (aangetekend) أو احفظ إثبات الإرسال الإلكتروني (لقطة شاشة أو رسالة تأكيد).</li></ul>'
+'<h2 id="content">ما الذي يجب أن تحتويه رسالة الاعتراض؟ (المادة 6:5 Awb)</h2>'
+T([['الاسم والعنوان','لتعرف الجهة من أنت وأين ترسل الرد','أضف رقم الهاتف والبريد الإلكتروني، والـBSN أو رقم الملف إن طلبته الجهة'],['التاريخ','لإثبات أنك أرسلت داخل المهلة','تاريخ يوم الإرسال'],['وصف القرار','لتعرف الجهة أي قرار تقصد','تاريخ القرار ورقمه المرجعي (kenmerk)، وأرفق نسخة منه'],['الأسباب (gronden)','لماذا تعتقد أن القرار خاطئ','اكتب نقاطاً واضحة وأرفق الأدلة؛ إن لم تكن جاهزاً فاعتراض مبدئي'],['التوقيع','الاعتراض الورقي بلا توقيع ناقص','في الأنظمة الإلكترونية يحل الدخول بـDigiD محل التوقيع عادة']],['العنصر','لماذا؟','نصيحة'])
+'<p>إن نقص عنصر، فالجهة عادةً لا ترفض فوراً، بل تطلب منك إكماله خلال مهلة تحددها في رسالتها (المادة 6:6 Awb). مثال: IND يطلب الوثائق الناقصة <strong>خلال أسبوعين</strong>. التزم بهذه المهلة، وإلا يُرفض اعتراضك شكلاً.</p>'
+'<h2 id="proforma">الاعتراض المبدئي (pro-forma bezwaar)</h2>'
+'<p>إذا اقتربت نهاية الأسابيع الستة وأنت ما زلت تجمع الأوراق أو تنتظر موعداً مع مستشار، أرسل رسالة قصيرة <strong>قبل نهاية المهلة</strong> تذكر فيها الاسم والعنوان والتاريخ والقرار والتوقيع، وتكتب أنك ستُرسل الأسباب لاحقاً. الجهة تعطيك بعدها مهلة لإكمال الأسباب. المهم أن <strong>الاعتراض المبدئي يحفظ حقك</strong> في المهلة، لكنه لا يكفي وحده: إن لم تُكمل الأسباب في الوقت المحدد، يُرفض.</p>'
+'<h2 id="where">أين وكيف تعترض؟ القرارات الشائعة</h2>'
+T([['Toeslagen (بدل الإيجار، الرعاية الصحية، رعاية الأطفال، kindgebonden budget)','Belastingdienst/Toeslagen','لسنة 2026: غالباً <strong>لا تحتاج اعتراضاً</strong>، صحّح بياناتك في Mijn toeslagen أو تطبيق Toeslagen. لسنة 2025 وما قبلها: اعترض على الحساب النهائي خلال 6 أسابيع.'],['ضريبة الدخل: التقدير النهائي (definitieve aanslag)','Belastingdienst','إلكترونياً بـDigiD، أو بنموذج ورقي موقّع إلى: Belastingdienst/Centrale administratieve processen, Postbus 2572, 6401 DB Heerlen. إفادة الاستلام خلال 3 أسابيع. هذا النموذج لا يصلح للتقدير المؤقت ولا للـtoeslagen.'],['WW، WIA، Ziektewet','UWV','حسب القرار؛ بعد تقديمه يتصل بك UWV عادة <strong>خلال 5 أيام عمل</strong>، ثم تصلك إفادة الاستلام خلال 5 أيام عمل بعد المكالمة. تتابع الملف في Mijn UWV تحت «Mijn Zaken».'],['AOW، kinderbijslag','SVB','الطريقة والعنوان مذكوران في قرار SVB.'],['Bijstand، bijzondere bijstand، Wmo، kwijtschelding','البلدية (college van B&amp;W)','عبر النموذج الإلكتروني للبلدية بـDigiD إن وُجد، أو برسالة. كثير من البلديات لديها لجنة اعتراضات، فقد تصبح مهلة القرار 12 أسبوعاً.'],['قرارات IND (إقامة، لمّ شمل…)','IND','رسالة بالبريد إلى العنوان المذكور في القرار، أو بريد إلكتروني آمن (حتى 20 MB لكل رسالة)، أو رفع الوثائق بـDigiD.'],['مخالفة مرورية (حرف M)','النيابة عبر CJIB','ليس bezwaar عادياً: طعن لدى officier van justitie خلال 6 أسابيع عبر Digitaal Loket Verkeer أو برسالة.']],['نوع القرار','الجهة','كيف؟'])
+'<p>القاعدة الذهبية: <strong>العنوان والطريقة في رسالة القرار نفسها هما المرجع</strong>. هذا الجدول للتوجيه فقط.</p>'
+'<h2 id="letter">نموذج رسالة اعتراض (بالهولندية) مع شرح كل سطر</h2>'
+'<p>اكتب الرسالة بالهولندية. لا تحتاج لغة قانونية؛ الجمل البسيطة الواضحة تكفي. انسخ النموذج وغيّر ما بين الأقواس [ ].</p>'
+LETTER
+T([['الأسطر الخمسة الأولى','بياناتك: الاسم، العنوان، الهاتف والبريد، وBSN أو رقم الملف إن طُلب. هذا الشرط الأول في المادة 6:5.'],['Aan: … afdeling Bezwaar','اسم الجهة وعنوانها كما في القرار تماماً.'],['[Woonplaats], [datum]','مدينتك وتاريخ اليوم؛ يُثبت أنك أرسلت داخل الأسابيع الستة.'],['Betreft: bezwaarschrift tegen uw besluit van …','الموضوع: «اعتراض على قراركم بتاريخ…» مع الرقم المرجعي (kenmerk). هذا «وصف القرار».'],['Hierbij maak ik bezwaar…','«أقدّم بهذا اعتراضاً على…»، ثم جملة تلخص ما قرروه (رفض، استرداد مبلغ…).'],['Ik ben het niet eens met dit besluit, omdat: 1. 2. 3.','«لا أوافق لأن…»: أهم جزء. كل سبب في نقطة، واذكر الدليل المرفق لكل نقطة.'],['Ik verzoek u daarom het besluit te herroepen…','«أطلب إلغاء القرار و…»: اكتب بالضبط ما تريده.'],['[Alleen bij een pro-forma bezwaar]','للاعتراض المبدئي فقط: «سأرسل الأسباب لاحقاً، أرجو إعطائي مهلة». احذف السطر إن كتبت الأسباب كاملة.'],['Ik wil graag worden gehoord…','«أريد أن يُستمع إليّ»: تطلب جلسة استماع (hoorzitting).'],['Ik verzoek u om vergoeding van de kosten…','اختياري: طلب تعويض التكاليف (مثلاً إن استعنت بمحامٍ). يجب طلبه <strong>قبل</strong> صدور القرار على اعتراضك.'],['Met vriendelijke groet + handtekening','«مع التحية» ثم <strong>توقيعك</strong> واسمك. بلا توقيع تكون الرسالة الورقية ناقصة.'],['Bijlagen','قائمة المرفقات: نسخة القرار والأدلة. لا ترسل الأصول، أرسل نسخاً.']],['السطر في الرسالة','الشرح بالعربية'])
+'<h2 id="after">ماذا يحدث بعد الاعتراض؟</h2>'
+'<ol><li><strong>إفادة استلام (ontvangstbevestiging)</strong>، وفيها غالباً المهلة التي يجب أن تقرر الجهة خلالها.</li><li><strong>جلسة استماع (hoorzitting)</strong>: تُدعى عادة لتشرح موقفك شفهياً، حضورياً أو بالهاتف أو بالفيديو. تستطيع الاطلاع على أوراق الملف قبل الجلسة بـ<strong>أسبوع على الأقل</strong>، وتصطحب فرداً من العائلة أو معارفك أو مستشاراً قانونياً، أو ترسل من يمثلك بتفويض مكتوب. UWV قد يقترح بدلاً منها وساطة (mediation).</li><li><strong>القرار على الاعتراض (beslissing op bezwaar)</strong> ضمن المهل التالية:</li></ol>'
+T([['القاعدة العامة','6 أسابيع بعد نهاية مهلة الاعتراض'],['إن كانت هناك لجنة استشارية للاعتراضات (adviescommissie)','12 أسبوعاً بعد نهاية مهلة الاعتراض'],['التمديد (verdagen)','حتى 6 أسابيع إضافية، تُبلَّغ به كتابياً'],['تمديد أطول','فقط بموافقتك، أو إن طلبت أنت ذلك']],['الحالة','مهلة القرار (beslistermijn)'])
+'<p>المهلة تبدأ من <strong>نهاية</strong> الأسابيع الستة المخصصة للاعتراض، لا من يوم إرسالك له.</p>'
+'<h2 id="late">الجهة لم تقرر في الوقت: الإنذار والغرامة اليومية (dwangsom)</h2>'
+'<ol><li>بعد انتهاء مهلة القرار، أرسل <strong>إنذاراً كتابياً (ingebrekestelling)</strong> تقول فيه إن المهلة انتهت. لدى الحكومة نموذج جاهز لذلك على صفحتها.</li><li>للجهة بعد ذلك <strong>أسبوعان</strong> لتقرر.</li><li>إن لم تقرر، تبدأ <strong>الغرامة اليومية تلقائياً</strong>، وتستطيع أيضاً رفع <strong>طعن مباشر لدى المحكمة</strong> بسبب عدم اتخاذ القرار في الوقت.</li></ol>'
+T([['أول أسبوعين','23 يورو في اليوم','14 × 23 = 322'],['الأسبوعان التاليان','35 يورو في اليوم','14 × 35 = 490'],['بقية الأيام','45 يورو في اليوم','14 × 45 = 630'],['المجموع الأقصى','حد أقصى 42 يوماً','<strong>1,442 يورو</strong>']],['الفترة','المبلغ','الحساب'])
+'<p><strong>استثناءات:</strong> لا غرامة يومية على طلبات الوصول إلى المعلومات (Woo-verzoek)، ولا على السلفة المؤقتة (voorschot) من Belastingdienst/Toeslagen.</p>'
+'<h2 id="beroep">رُفض اعتراضك: الطعن أمام المحكمة (beroep)</h2>'
+'<ul><li>المهلة: <strong>6 أسابيع</strong> بعد القرار على اعتراضك، لدى <strong>القسم الإداري في المحكمة (rechtbank)</strong>. المحكمة المختصة مكتوبة في القرار.</li><li>عريضة الطعن (beroepschrift) تحتوي: اسمك وعنوانك، القرار الذي تطعن فيه، لماذا لا توافق، وما الذي تراه صحيحاً، مع التاريخ والتوقيع.</li><li>لكثير من القضايا يمكن التقديم <strong>إلكترونياً</strong> عبر <strong>Mijn Rechtspraak</strong> بـDigiD.</li><li><strong>لا يلزمك محامٍ</strong> لبدء الطعن.</li><li>القاضي يصدر حكمه عادةً <strong>خلال 6 أسابيع بعد الجلسة</strong>.</li><li>بعدها يمكن الاستئناف (hoger beroep): لدى <strong>Centrale Raad van Beroep</strong> في الضمان الاجتماعي وتمويل الدراسة، أو <strong>Raad van State</strong>، أو <strong>CBb</strong> في القانون الإداري الاقتصادي. المهلة مكتوبة في الحكم.</li></ul>'
+T([['شخص طبيعي: قضايا مخفّضة (مثل الإعانات والبدلات)','54 يورو'],['شخص طبيعي: قضايا إدارية أخرى','200 يورو'],['شركة أو منظمة (rechtspersoon)','397 يورو']],['من يطعن؟','رسوم المحكمة (griffierecht) 2026'])
+'<p>تصلك فاتورة الرسوم (griffienota) من المحكمة، ومهلة الدفع مكتوبة فيها. <strong>إن ربحت كلياً أو جزئياً</strong>، يجب على الجهة الحكومية أن تعيد لك الرسوم. دخلك منخفض؟ اسأل Juridisch Loket عن المساعدة القانونية المدعومة.</p>'
+'<h2 id="vovo">الإجراء المستعجل (voorlopige voorziening)</h2>'
+'<p>الاعتراض لا يوقف القرار تلقائياً. إن كان القرار سيسبب ضرراً لا يمكن إصلاحه قبل أن ينتهي الاعتراض أو الطعن (مثلاً: قطع شجرة، إيقاف دخلك كاملاً، أو مغادرة البلد)، اطلب من قاضي الأمور المستعجلة (voorzieningenrechter) <strong>إجراءً مؤقتاً</strong>. يمكن طلبه أثناء الاعتراض بشرط أن تكون قد قدّمت الاعتراض فعلاً، أو أثناء الطعن. له رسوم محكمة أيضاً. في قضايا IND قد تكون المهلة قصيرة جداً (صفحة IND تذكر <strong>24 ساعة</strong> في حالات معينة)، فاتبع ما في رسالتك بدقة واتصل بمحامٍ فوراً.</p>'
+'<h2 id="klacht">الاعتراض أم الشكوى أم أمين المظالم؟</h2>'
+T([['bezwaar (اعتراض)','على <strong>محتوى قرار</strong> رسمي (رفض، مبلغ، سحب)','6 أسابيع','يمكن أن يتغير القرار'],['klacht (شكوى)','على <strong>تصرف</strong> الموظف أو الجهة: معاملة سيئة، عدم رد، تأخير، أخطاء في التواصل','لدى الجهة نفسها أولاً','اعتذار أو تحسين، لا يُلغى القرار'],['Nationale ombudsman','بعد أن تشتكي للجهة دون نتيجة','خلال <strong>سنة</strong> من معالجة الجهة لشكواك','تحقيق مستقل وتوصيات'],['beroep (طعن قضائي)','بعد القرار على الاعتراض','6 أسابيع','حكم ملزم']],['الطريق','على ماذا؟','المهلة','النتيجة'])
+'<p>أمين المظالم <strong>لا ينظر</strong> في الأمر إن كان الاعتراض أو الطعن ما يزال ممكناً، ولا في أحكام القضاء. تقدم له الشكوى عبر نموذج إلكتروني أو نموذج مطبوع أو رسالة. لبعض البلديات أمين مظالم محلي (gemeentelijke ombudsman).</p>'
+'<h2 id="examples">أمثلة محسوبة</h2>'
+T([['قرار Toeslagen بتاريخ 3 مارس 2026','آخر يوم للاعتراض: <strong>14 أبريل 2026</strong> (3 مارس + 42 يوماً)'],['نفس الاعتراض، بلا لجنة استشارية','مهلة القرار حتى <strong>26 مايو 2026</strong> (14 أبريل + 6 أسابيع)؛ مع تمديد حتى 7 يوليو'],['قرار بلدية فيه لجنة اعتراضات','مهلة القرار حتى <strong>7 يوليو 2026</strong> (14 أبريل + 12 أسبوعاً)'],['الجهة لم تقرر حتى 7 يوليو، وأرسلتَ إنذاراً','بعد أسبوعين تبدأ الغرامة: 322 + 490 + 630 = <strong>1,442 يورو</strong> كحد أقصى بعد 42 يوماً'],['طعن على قرار UWV رُفض اعتراضه','رسوم المحكمة: <strong>54 يورو</strong> (قضية إعانة)؛ تُعاد إن ربحت'],['جار يطعن في رخصة بناء','رسوم المحكمة: <strong>200 يورو</strong>']],['الحالة','الحساب'])
+'<p>أمثلة توضيحية وليست حالات أشخاص حقيقيين. في حالتك تحقق دائماً من التواريخ المكتوبة على رسالتك.</p>'
+'<h2 id="steps">خطوة بخطوة: من استلام القرار إلى إرسال الاعتراض</h2>'
+'<ol><li><strong>اكتب تاريخ القرار</strong> واحسب نهاية الأسابيع الستة فوراً، وضعها في هاتفك.</li><li>اقرأ فقرة «Bezwaar maken» في آخر القرار: لمن، وكيف، وأي عنوان.</li><li>اتصل بالجهة إن كان الخطأ بسيطاً (رقم دخل خاطئ مثلاً)؛ أحياناً يكفي تصحيح البيانات، لكن <strong>لا تترك المهلة تمر</strong> وأنت تنتظر.</li><li>اجمع الأدلة: قسائم الراتب، jaaropgaaf، عقد الإيجار، رسائل، تقارير طبية.</li><li>اكتب الرسالة بالنموذج أعلاه، أو قدّم الاعتراض إلكترونياً بـDigiD عند الجهة.</li><li>وقّع، واحتفظ بنسخة كاملة، وأرسل بالبريد المسجل أو احفظ تأكيد الإرسال.</li><li>انتظر إفادة الاستلام. لم تصل خلال بضعة أسابيع؟ اتصل.</li><li>استعد لجلسة الاستماع، واطلب الاطلاع على الملف قبلها.</li><li>بعد القرار: موافق؟ انتهى الأمر. غير موافق؟ طعن خلال 6 أسابيع. تأخرت الجهة؟ إنذار.</li></ol>'
+'<h2 id="mistakes">أخطاء شائعة</h2><ol><li><strong>حساب المهلة من يوم فتح الرسالة</strong> بدل تاريخ القرار.</li><li><strong>الاتصال الهاتفي بدل الاعتراض الكتابي</strong>: المكالمة ليست اعتراضاً.</li><li><strong>نسيان التوقيع</strong> أو نسخة القرار أو الرقم المرجعي.</li><li><strong>الاعتراض لدى الجهة الخطأ</strong>، مثل إرسال اعتراض Toeslagen إلى البلدية.</li><li><strong>التوقف عن الدفع</strong> لأنك اعترضت: القرار يبقى سارياً ما لم تحصل على تأجيل.</li><li><strong>إرسال اعتراض مبدئي ثم نسيان إكماله</strong> في المهلة التي تحددها الجهة.</li><li><strong>الخلط بين الشكوى والاعتراض</strong>: شكوى عن موظف لا تغيّر القرار.</li><li><strong>انتظار القرار بلا نهاية</strong>: بعد انتهاء مهلة القرار يحق لك إرسال إنذار.</li></ol>'
+'<h2 id="help">مساعدة مجانية</h2><ul><li><strong>Het Juridisch Loket</strong>: هاتف <strong>0800-8020</strong> مجاني، من الاثنين إلى الجمعة 9:00 – 17:00. نصيحة شخصية مجانية لمن دخله منخفض ومدخراته قليلة، ومكاتب فيها ساعات استقبال دون موعد.</li><li><strong>المستشار الاجتماعي (sociaal raadslid)</strong> في بلديتك أو لدى مؤسسة الرعاية الاجتماعية: يساعد غالباً في كتابة الاعتراض على toeslagen والإعانات مجاناً. اسأل بلديتك.</li><li><strong>محامٍ بمساعدة قانونية مدعومة (toevoeging)</strong> عبر Juridisch Loket إن كانت القضية معقدة، خاصة في قضايا IND.</li><li>إن كان الاعتراض عن ديون أو استرداد مبالغ، انظر أيضاً <a href="/articles/debt-help-schuldhulp.html">مساعدة الديون المجانية</a>.</li></ul>'
+'<h2 id="related">أدلة مرتبطة</h2><ul><li><a href="/articles/toeslagen-income-update.html">تحديث الدخل في Toeslagen</a></li><li><a href="/articles/zorgtoeslag-guide.html">بدل الرعاية الصحية</a></li><li><a href="/articles/unemployment-benefit-ww.html">إعانة البطالة WW</a></li><li><a href="/articles/social-assistance-bijstand.html">المساعدة الاجتماعية bijstand</a></li><li><a href="/articles/wmo-home-support.html">دعم Wmo</a></li><li><a href="/articles/traffic-fines-cjib.html">المخالفات المرورية وCJIB</a></li><li><a href="/articles/digid-registration-guide.html">DigiD</a></li></ul>'),
faq=[('كم مهلة الاعتراض على قرار حكومي؟','6 أسابيع من تاريخ القرار (المادة 6:7 Awb)، ما لم يذكر القرار مهلة أخرى، مثل 4 أسابيع لدى IND بعد استلام وثيقة الإقامة.'),
('ماذا يجب أن أكتب في رسالة الاعتراض؟','اسمك وعنوانك، التاريخ، وصف القرار (التاريخ والرقم المرجعي)، أسباب عدم موافقتك، وتوقيعك. أرفق نسخة من القرار والأدلة.'),
('هل يمكن أن أكتب الرسالة بالعربية؟','الأفضل بالهولندية. استخدم النموذج في هذا الدليل وغيّر ما بين الأقواس؛ لا تحتاج لغة قانونية.'),
('لا أملك كل الأسباب الآن، ماذا أفعل؟','أرسل اعتراضاً مبدئياً (pro forma) قبل نهاية الأسابيع الستة، واكتب أنك ستُرسل الأسباب لاحقاً، ثم أكملها في المهلة التي تحددها الجهة.'),
('هل الاعتراض يكلّف مالاً؟','لا، الاعتراض مجاني. الطعن أمام المحكمة له رسوم: 54 يورو للأفراد في قضايا الإعانات والبدلات و200 يورو في القضايا الأخرى (2026).'),
('هل أتوقف عن الدفع أثناء الاعتراض؟','لا تلقائياً. القرار يبقى سارياً أثناء الاعتراض. اطلب تأجيل الدفع من الجهة إن احتجت.'),
('كم تأخذ الجهة لتقرر؟','6 أسابيع بعد نهاية مهلة الاعتراض، أو 12 أسبوعاً مع لجنة استشارية، ويمكن التمديد 6 أسابيع.'),
('الجهة تأخرت، ماذا أفعل؟','أرسل إنذاراً (ingebrekestelling). بعد أسبوعين تبدأ غرامة يومية 23 ثم 35 ثم 45 يورو، بحد أقصى 1,442 يورو في 42 يوماً، ويمكنك الطعن مباشرة أمام المحكمة.'),
('ما الفرق بين الاعتراض والشكوى؟','الاعتراض على محتوى القرار ويمكن أن يغيّره. الشكوى على طريقة تعامل الجهة معك، ولا تلغي القرار. بعد الشكوى يمكنك التوجه إلى Nationale ombudsman خلال سنة.'),
('أين أجد مساعدة مجانية؟','Het Juridisch Loket على الرقم المجاني 0800-8020، والمستشار الاجتماعي (sociaal raadslid) في بلديتك.')],
src_note='راجعنا Rijksoverheid وقانون Awb على wetten.overheid.nl وDe Rechtspraak وBelastingdienst وUWV وIND وJuridisch Loket في 7 أكتوبر 2026. رسوم المحكمة هي تعرفة 2026، ولم نذكر رسوم الإجراء المستعجل ولا مهل الاستئناف لأنها تختلف حسب القضية وتُذكر في الحكم أو الفاتورة. تفاصيل SVB والبلديات تختلف، فاتبع ما في رسالة القرار. نموذج الرسالة للإرشاد وليس استشارة قانونية. الأمثلة توضيحية.')

NL=dict(title='Bezwaar maken tegen een besluit van de overheid in 2026: 6 weken termijn, wat in je bezwaarschrift moet, dwangsom tot € 1.442 en beroep voor € 54 — met voorbeeldbrief',
crumb='Bezwaar maken tegen een besluit',
seo_title='Bezwaar maken tegen een overheidsbesluit 2026',
desc='Bezwaar maken tegen een besluit van Toeslagen, UWV of gemeente: 6 weken termijn, inhoud van je bezwaarschrift, dwangsom tot € 1.442 en een voorbeeldbrief.',
summary='<ol><li>Je hebt <strong>6 weken</strong> om bezwaar te maken, gerekend vanaf de <strong>datum van het besluit</strong>, niet vanaf het moment dat je de brief leest (art. 6:7 Awb).</li><li>In je bezwaarschrift staan: <strong>naam en adres, datum, omschrijving van het besluit, de redenen en je handtekening</strong> (art. 6:5 Awb). Bezwaar maken is <strong>gratis</strong> en een advocaat is niet nodig.</li><li>Nog geen redenen? Stuur op tijd een <strong>pro-forma bezwaar</strong> en vul de gronden later aan.</li><li>De overheid beslist meestal binnen <strong>6 weken</strong> na afloop van de bezwaartermijn, <strong>12 weken</strong> bij een adviescommissie, en kan <strong>maximaal 6 weken</strong> verdagen.</li><li>Te laat? Stuur een <strong>ingebrekestelling</strong>; na <strong>2 weken</strong> loopt een dwangsom van maximaal <strong>€ 1.442</strong>.</li><li>Bezwaar afgewezen? <strong>Beroep</strong> bij de rechtbank binnen <strong>6 weken</strong>. Griffierecht 2026 voor particulieren: <strong>€ 54</strong> (o.a. uitkeringen en toeslagen) of <strong>€ 200</strong>; je krijgt het terug als je gelijk krijgt.</li></ol>',
body=(
'<h2 id="what">Wat is bezwaar en waartegen maak je het?</h2>'
+'<p>Een <strong>besluit</strong> is een schriftelijke beslissing van een overheidsorgaan over jou: een toeslag wordt afgewezen of verlaagd, je moet geld terugbetalen, je krijgt een definitieve aanslag, UWV beslist over je WW of WIA, de SVB over kinderbijslag of AOW, de gemeente over bijstand of Wmo, of de IND over je verblijf. Ben je het er niet mee eens, dan is de eerste stap meestal <strong>bezwaar</strong>: je vraagt dezelfde organisatie het besluit opnieuw te bekijken.</p>'
+'<ul><li><strong>Bezwaar maken kost niets</strong> en je hebt geen advocaat nodig. Je mag je wel laten bijstaan of vertegenwoordigen.</li><li>Onderaan het besluit staat meestal <strong>‘Bezwaar maken?’</strong> of <strong>‘Bent u het niet eens?’</strong>. Lees dat eerst: wat daar staat gaat voor op een algemene gids.</li><li><strong>Het besluit blijft gelden</strong> tijdens het bezwaar. UWV zegt het letterlijk: zolang er geen beslissing op bezwaar is, geldt de beslissing waartegen je bezwaar maakt. Moet je betalen, vraag dan om uitstel.</li><li>Soms is de weg <strong>administratief beroep</strong> bij een ander orgaan in plaats van bezwaar. Ook dat staat in het besluit.</li></ul>'
+'<h2 id="deadline">De termijn: 6 weken, maar vanaf wanneer?</h2>'
+'<p>Artikel <strong>6:7 Awb</strong>: de termijn voor een bezwaarschrift bedraagt <strong>zes weken</strong>. Volgens de overheid reken je vanaf de <strong>datum van de beslissing</strong>. Komt de post laat of maak je de brief pas later open, dan loopt de termijn toch door.</p>'
+'<ul><li><strong>Toeslagen</strong>: bezwaar tegen de definitieve berekening binnen 6 weken na de datum op die berekening.</li><li><strong>IND</strong>: heb je je verblijfsvergunning gekregen maar ben je het met een onderdeel niet eens, dan stuur je volgens de IND het bezwaar binnen <strong>4 weken</strong> na de datum waarop je het verblijfsdocument kreeg. In andere zaken staat de termijn in het besluit.</li><li><strong>Verkeersboetes (CJIB)</strong> hebben een eigen route: beroep bij de officier van justitie binnen 6 weken. Zie <a href="/nl/articles/traffic-fines-cjib.html">Verkeersboetes en het CJIB</a>.</li><li><strong>Te laat?</strong> Dan wordt het bezwaar meestal niet-ontvankelijk verklaard. Alleen als de overschrijding je niet te verwijten is (verschoonbaar), bijvoorbeeld omdat je het besluit nooit kreeg, kan het nog. Leg dat uit met bewijs.</li><li>Verstuur aangetekend of bewaar het verzendbewijs van je digitale bezwaar (bevestiging of schermafbeelding).</li></ul>'
+'<h2 id="content">Wat moet er in het bezwaarschrift? (art. 6:5 Awb)</h2>'
+T([['Naam en adres','Zodat de organisatie weet wie je bent en waar het antwoord heen moet','Zet er telefoon en e-mail bij, en je BSN of dossiernummer als daarom wordt gevraagd'],['Datum','Bewijs dat je binnen de termijn zat','De datum van verzending'],['Omschrijving van het besluit','Zodat duidelijk is welk besluit je bedoelt','Datum en kenmerk van het besluit, met een kopie als bijlage'],['Gronden (redenen)','Waarom het besluit volgens jou niet klopt','Duidelijke punten met bewijs; nog niet klaar, dan pro forma'],['Handtekening','Een papieren bezwaar zonder handtekening is onvolledig','Bij digitale loketten geldt inloggen met DigiD meestal als ondertekening']],['Onderdeel','Waarom?','Tip'])
+'<p>Ontbreekt er iets, dan wijst de organisatie het meestal niet direct af, maar geeft ze je een termijn om het verzuim te herstellen (art. 6:6 Awb). De IND vraagt ontbrekende documenten bijvoorbeeld <strong>binnen 2 weken</strong> op te sturen. Houd je aan die termijn, anders volgt alsnog niet-ontvankelijkheid.</p>'
+'<h2 id="proforma">Pro-forma bezwaar</h2>'
+'<p>Loopt de termijn bijna af en verzamel je nog papieren of wacht je op advies? Stuur dan <strong>vóór het einde van de termijn</strong> een korte brief met naam, adres, datum, het besluit en je handtekening, en schrijf dat je de gronden nastuurt. De organisatie geeft je daarna een termijn om de gronden aan te vullen. Een pro-forma bezwaar <strong>houdt de termijn veilig</strong>, maar is niet genoeg: vul je de gronden niet op tijd aan, dan wordt het bezwaar alsnog niet-ontvankelijk.</p>'
+'<h2 id="where">Waar en hoe maak je bezwaar? Veelvoorkomende besluiten</h2>'
+T([['Toeslagen (huurtoeslag, zorgtoeslag, kinderopvangtoeslag, kindgebonden budget)','Belastingdienst/Toeslagen','Voor 2026: meestal <strong>geen bezwaar nodig</strong>, geef een wijziging door in Mijn toeslagen of de app Toeslagen. Over 2025 en eerder: bezwaar tegen de definitieve berekening binnen 6 weken.'],['Inkomstenbelasting: definitieve aanslag','Belastingdienst','Online met DigiD, of het ondertekende formulier naar Belastingdienst/Centrale administratieve processen, Postbus 2572, 6401 DB Heerlen. Ontvangstbevestiging binnen 3 weken. Dit formulier is niet voor een voorlopige aanslag of een toeslag.'],['WW, WIA, Ziektewet','UWV','Volgens het besluit; UWV belt je meestal <strong>binnen 5 werkdagen</strong> na ontvangst en stuurt binnen 5 werkdagen na dat gesprek een ontvangstbevestiging. Volgen in Mijn UWV onder ‘Mijn Zaken’.'],['AOW, kinderbijslag','SVB','Hoe en waar staat in het besluit van de SVB.'],['Bijstand, bijzondere bijstand, Wmo, kwijtschelding','Gemeente (college van B&amp;W)','Via het digitale formulier van de gemeente met DigiD als dat er is, of per brief. Veel gemeenten hebben een bezwaarcommissie; de beslistermijn kan dan 12 weken zijn.'],['IND-besluiten (verblijf, gezinshereniging …)','IND','Per post naar het adres in het besluit, per beveiligde e-mail (maximaal 20 MB per mail) of documenten uploaden met DigiD.'],['Verkeersboete (letter M)','Officier van justitie via CJIB','Geen gewoon bezwaar: beroep binnen 6 weken via het Digitaal Loket Verkeer of per brief.']],['Soort besluit','Organisatie','Hoe?'])
+'<p>Gouden regel: <strong>het adres en de manier in het besluit zelf zijn leidend</strong>. Deze tabel is een wegwijzer.</p>'
+'<h2 id="letter">Voorbeeldbrief bezwaarschrift</h2>'
+'<p>Je hoeft geen juridische taal te gebruiken; eenvoudige, duidelijke zinnen zijn genoeg. Kopieer de brief en vul in wat tussen [ ] staat.</p>'
+LETTER
+T([['Eerste vijf regels','Je gegevens. Dit is het eerste vereiste van art. 6:5 Awb.'],['Aan: … afdeling Bezwaar','Naam en adres precies zoals in het besluit.'],['[Woonplaats], [datum]','Toont aan dat je binnen 6 weken verstuurde.'],['Betreft: …','Datum en kenmerk: de ‘omschrijving van het besluit’.'],['Hierbij maak ik bezwaar …','Vat in één zin samen wat er is besloten.'],['Ik ben het niet eens …, omdat: 1. 2. 3.','Het belangrijkste deel. Eén reden per punt, met verwijzing naar bewijs.'],['Ik verzoek u daarom …','Zeg precies wat je wilt dat er gebeurt.'],['Pro-forma regel','Alleen als je de gronden later stuurt; anders weglaten.'],['Ik wil graag worden gehoord','Je vraagt om een hoorzitting.'],['Vergoeding van de kosten','Optioneel, bijvoorbeeld bij een advocaat. Vraag dit <strong>vóór</strong> de beslissing op bezwaar.'],['Handtekening','Zonder handtekening is een papieren bezwaar onvolledig.'],['Bijlagen','Kopie van het besluit en bewijsstukken. Stuur kopieën, geen originelen.']],['Regel in de brief','Waarom'])
+'<h2 id="after">Wat gebeurt er na je bezwaar?</h2>'
+'<ol><li>Een <strong>ontvangstbevestiging</strong>, vaak met de beslistermijn.</li><li>Een <strong>hoorzitting</strong>: je wordt meestal uitgenodigd om je bezwaar mondeling toe te lichten, op locatie, telefonisch of via video. De stukken liggen <strong>minstens een week</strong> vooraf ter inzage. Je mag familie, kennissen of een juridisch adviseur meenemen, of je laten vertegenwoordigen met een schriftelijke machtiging. UWV kan ook mediation voorstellen.</li><li>De <strong>beslissing op bezwaar</strong>, binnen deze termijnen:</li></ol>'
+T([['Hoofdregel','6 weken na afloop van de bezwaartermijn'],['Met een adviescommissie voor bezwaarschriften','12 weken na afloop van de bezwaartermijn'],['Verdaging','Maximaal 6 weken, schriftelijk meegedeeld'],['Langer uitstel','Alleen met jouw instemming of op jouw verzoek']],['Situatie','Beslistermijn'])
+'<p>De beslistermijn start aan het <strong>einde</strong> van de bezwaartermijn van 6 weken, niet op de dag dat jij je bezwaar instuurde.</p>'
+'<h2 id="late">Te laat beslist: ingebrekestelling en dwangsom</h2>'
+'<ol><li>Is de beslistermijn verstreken, stuur dan een <strong>ingebrekestelling</strong>: een brief waarin je zegt dat de termijn voorbij is. De overheid heeft er een voorbeeldformulier voor.</li><li>De organisatie heeft daarna <strong>2 weken</strong> om alsnog te beslissen.</li><li>Gebeurt dat niet, dan gaat de <strong>dwangsom automatisch lopen</strong> en kun je <strong>direct beroep</strong> instellen bij de rechter wegens niet tijdig beslissen.</li></ol>'
+T([['Eerste 2 weken','€ 23 per dag','14 × € 23 = € 322'],['Volgende 2 weken','€ 35 per dag','14 × € 35 = € 490'],['Overige dagen','€ 45 per dag','14 × € 45 = € 630'],['Maximum','Uiterlijk 42 dagen','<strong>€ 1.442</strong>']],['Periode','Bedrag','Berekening'])
+'<p><strong>Uitzonderingen:</strong> geen dwangsom bij een Woo-verzoek en niet bij een voorschot van Belastingdienst/Toeslagen.</p>'
+'<h2 id="beroep">Bezwaar afgewezen: beroep bij de rechtbank</h2>'
+'<ul><li>Termijn: <strong>6 weken</strong> na de beslissing op bezwaar, bij de <strong>sector bestuursrecht van de rechtbank</strong>. Welke rechtbank staat in de beslissing.</li><li>In het beroepschrift: naam en adres, het besluit waartegen je in beroep gaat, waarom je het er niet mee eens bent en wat de beslissing volgens jou had moeten zijn, met datum en handtekening.</li><li>Voor veel zaken kun je <strong>digitaal</strong> beroep instellen via <strong>Mijn Rechtspraak</strong> met DigiD.</li><li>Voor het instellen van beroep is <strong>geen advocaat verplicht</strong>.</li><li>De rechter doet meestal <strong>binnen 6 weken na de zitting</strong> uitspraak.</li><li>Daarna is hoger beroep mogelijk: bij de <strong>Centrale Raad van Beroep</strong> (sociale zekerheid, studiefinanciering), de <strong>Raad van State</strong> of het <strong>CBb</strong> (economisch bestuursrecht). De termijn staat in de uitspraak.</li></ul>'
+T([['Natuurlijk persoon: verlaagd tarief (o.a. uitkeringen, toeslagen)','€ 54'],['Natuurlijk persoon: overige bestuurszaken','€ 200'],['Rechtspersoon (bedrijf, organisatie)','€ 397']],['Wie','Griffierecht rechtbank 2026'])
+'<p>Je krijgt een <strong>griffienota</strong> van de rechtbank met de betaaltermijn. Krijg je (gedeeltelijk) <strong>gelijk</strong>, dan moet de overheidsorganisatie het griffierecht vergoeden. Laag inkomen? Vraag het Juridisch Loket naar gesubsidieerde rechtsbijstand.</p>'
+'<h2 id="vovo">Voorlopige voorziening (spoed)</h2>'
+'<p>Bezwaar schort het besluit niet automatisch op. Dreigt er onomkeerbare schade voordat bezwaar of beroep is afgerond (een boom wordt gekapt, je inkomen stopt helemaal, je moet het land uit), vraag dan de voorzieningenrechter om een <strong>voorlopige voorziening</strong>. Dat kan tijdens bezwaar, mits je al bezwaar hebt gemaakt, of tijdens beroep. Ook hiervoor betaal je griffierecht. In IND-zaken kan de termijn heel kort zijn (de IND noemt in bepaalde gevallen <strong>24 uur</strong>): volg je brief nauwkeurig en schakel direct een advocaat in.</p>'
+'<h2 id="klacht">Bezwaar, klacht of Nationale ombudsman?</h2>'
+T([['Bezwaar','De <strong>inhoud van een besluit</strong> (afwijzing, bedrag, intrekking)','6 weken','Het besluit kan veranderen'],['Klacht','Het <strong>gedrag</strong> van een medewerker of organisatie: onheus, niet teruggebeld, te laat, slecht geïnformeerd','Eerst bij de organisatie zelf','Excuses of verbetering; het besluit blijft'],['Nationale ombudsman','Als je klacht bij de organisatie niets opleverde','Binnen <strong>1 jaar</strong> na afhandeling van je klacht','Onafhankelijk onderzoek en aanbevelingen'],['Beroep','Na de beslissing op bezwaar','6 weken','Bindende uitspraak']],['Route','Waarover?','Termijn','Resultaat'])
+'<p>De ombudsman behandelt je klacht <strong>niet</strong> als bezwaar of beroep nog mogelijk is, en niet over een uitspraak van de rechter. Klagen kan met het online formulier, een uitgeprint formulier of een brief. Sommige gemeenten hebben een eigen gemeentelijke ombudsman.</p>'
+'<h2 id="examples">Rekenvoorbeelden</h2>'
+T([['Besluit Toeslagen gedateerd 3 maart 2026','Laatste dag bezwaar: <strong>14 april 2026</strong> (3 maart + 42 dagen)'],['Zelfde bezwaar, geen adviescommissie','Beslistermijn tot <strong>26 mei 2026</strong> (14 april + 6 weken); met verdaging tot 7 juli'],['Gemeentebesluit met bezwaarcommissie','Beslistermijn tot <strong>7 juli 2026</strong> (14 april + 12 weken)'],['Geen beslissing op 7 juli, ingebrekestelling verstuurd','Na 2 weken loopt de dwangsom: € 322 + € 490 + € 630 = maximaal <strong>€ 1.442</strong> na 42 dagen'],['Beroep tegen afgewezen bezwaar bij UWV','Griffierecht <strong>€ 54</strong> (uitkeringszaak); terug als je gelijk krijgt'],['Buurman gaat in beroep tegen een bouwvergunning','Griffierecht <strong>€ 200</strong>']],['Situatie','Berekening'])
+'<p>Illustratief, geen echte personen. Controleer in je eigen zaak altijd de data in je brief.</p>'
+'<h2 id="steps">Stap voor stap: van besluit tot bezwaarschrift</h2>'
+'<ol><li><strong>Noteer de datum van het besluit</strong> en reken direct het einde van de 6 weken uit; zet het in je agenda.</li><li>Lees ‘Bezwaar maken’ onderaan het besluit: bij wie, hoe en welk adres.</li><li>Bel bij een simpele fout (verkeerd inkomen) gerust de organisatie; soms is een wijziging genoeg. Maar <strong>laat de termijn niet verlopen</strong> terwijl je wacht.</li><li>Verzamel bewijs: loonstroken, jaaropgaaf, huurcontract, brieven, medische stukken.</li><li>Schrijf de brief met het voorbeeld hierboven, of dien online in met DigiD.</li><li>Onderteken, bewaar een volledige kopie en verstuur aangetekend of bewaar de bevestiging.</li><li>Wacht op de ontvangstbevestiging. Na een paar weken niets? Bel.</li><li>Bereid de hoorzitting voor en vraag de stukken vooraf in te zien.</li><li>Na de beslissing: eens? Klaar. Niet eens? Beroep binnen 6 weken. Te laat? Ingebrekestelling.</li></ol>'
+'<h2 id="mistakes">Veelgemaakte fouten</h2><ol><li><strong>De termijn rekenen vanaf het openen van de brief</strong> in plaats van de datum van het besluit.</li><li><strong>Bellen in plaats van schriftelijk bezwaar</strong>: een telefoontje is geen bezwaar.</li><li><strong>Handtekening, kopie of kenmerk vergeten</strong>.</li><li><strong>Bezwaar bij de verkeerde organisatie</strong>, bijvoorbeeld een toeslagbezwaar naar de gemeente.</li><li><strong>Stoppen met betalen</strong> omdat je bezwaar maakte: het besluit blijft gelden zonder uitstel.</li><li><strong>Pro forma indienen en vergeten aan te vullen</strong> binnen de gegeven termijn.</li><li><strong>Klacht en bezwaar verwarren</strong>: een klacht over een medewerker verandert het besluit niet.</li><li><strong>Eindeloos wachten</strong>: na de beslistermijn mag je een ingebrekestelling sturen.</li></ol>'
+'<h2 id="help">Gratis hulp</h2><ul><li><strong>Het Juridisch Loket</strong>: <strong>0800-8020</strong> (gratis), maandag t/m vrijdag 09.00 – 17.00 uur. Gratis persoonlijk juridisch advies voor mensen met een laag inkomen en weinig spaargeld, en vestigingen met inloopspreekuur.</li><li><strong>Sociaal raadslid</strong> bij je gemeente of welzijnsorganisatie: helpt vaak gratis met bezwaren over toeslagen en uitkeringen. Vraag ernaar bij je gemeente.</li><li><strong>Advocaat met een toevoeging</strong> (gesubsidieerde rechtsbijstand) via het Juridisch Loket bij ingewikkelde zaken, zeker bij de IND.</li><li>Gaat het bezwaar over schulden of terugvorderingen, zie ook <a href="/nl/articles/debt-help-schuldhulp.html">Gratis schuldhulp</a>.</li></ul>'
+'<h2 id="related">Gerelateerde gidsen</h2><ul><li><a href="/nl/articles/toeslagen-income-update.html">Inkomen doorgeven bij Toeslagen</a></li><li><a href="/nl/articles/zorgtoeslag-guide.html">Zorgtoeslag</a></li><li><a href="/nl/articles/unemployment-benefit-ww.html">WW-uitkering</a></li><li><a href="/nl/articles/social-assistance-bijstand.html">Bijstand</a></li><li><a href="/nl/articles/wmo-home-support.html">Wmo-ondersteuning</a></li><li><a href="/nl/articles/traffic-fines-cjib.html">Verkeersboetes en CJIB</a></li><li><a href="/nl/articles/digid-registration-guide.html">DigiD aanvragen</a></li></ul>'),
faq=[('Hoe lang heb ik om bezwaar te maken?','6 weken vanaf de datum van het besluit (art. 6:7 Awb), tenzij het besluit een andere termijn noemt, zoals 4 weken bij de IND na ontvangst van het verblijfsdocument.'),
('Wat moet er in een bezwaarschrift staan?','Naam en adres, datum, omschrijving van het besluit (datum en kenmerk), de redenen waarom je het er niet mee eens bent en je handtekening. Voeg een kopie van het besluit en bewijs toe.'),
('Moet het bezwaar in het Nederlands?','Dat is het verstandigst. Gebruik de voorbeeldbrief en vul de onderdelen tussen haakjes in; juridische taal is niet nodig.'),
('Wat is een pro-forma bezwaar?','Een kort bezwaar binnen de termijn zonder (volledige) gronden. Je stuurt de redenen later na binnen de termijn die de organisatie je geeft.'),
('Kost bezwaar maken geld?','Nee, bezwaar is gratis. Beroep bij de rechtbank kost griffierecht: € 54 voor particulieren in o.a. uitkerings- en toeslagzaken en € 200 in andere zaken (2026).'),
('Hoef ik tijdens bezwaar niet te betalen?','Niet automatisch. Het besluit blijft gelden tijdens het bezwaar. Vraag uitstel van betaling aan als dat nodig is.'),
('Hoe lang duurt het voor er beslist wordt?','6 weken na afloop van de bezwaartermijn, 12 weken met een adviescommissie, plus eventueel 6 weken verdaging.'),
('De overheid beslist te laat. Wat nu?','Stuur een ingebrekestelling. Na 2 weken loopt een dwangsom van € 23, dan € 35 en dan € 45 per dag, maximaal € 1.442 in 42 dagen, en je kunt direct in beroep.'),
('Wat is het verschil tussen bezwaar en klacht?','Bezwaar gaat over de inhoud van een besluit en kan het veranderen. Een klacht gaat over hoe je bent behandeld en verandert het besluit niet. Daarna kun je binnen 1 jaar naar de Nationale ombudsman.'),
('Waar krijg ik gratis hulp?','Bij Het Juridisch Loket via 0800-8020 (gratis) en bij de sociaal raadslieden in je gemeente.')],
src_note='Gecontroleerd bij Rijksoverheid, de Awb op wetten.overheid.nl, De Rechtspraak, Belastingdienst, UWV, IND en Het Juridisch Loket op 7 oktober 2026. Griffierecht volgens de tarieven 2026; griffierecht voor een voorlopige voorziening en termijnen voor hoger beroep noemen we niet, omdat die per zaak verschillen en in de griffienota of uitspraak staan. Werkwijze van SVB en gemeenten verschilt: volg je besluit. De voorbeeldbrief is een hulpmiddel, geen juridisch advies. Voorbeelden illustratief.')
