from a_student_finance import T
SLUG='social-assistance-bijstand'
R='https://www.rijksoverheid.nl/'
SRC=[('Rijksoverheid · Wanneer heb ik recht op bijstand?',R+'vraag-en-antwoord/bijstand/wanneer-heb-ik-recht-op-bijstand'),
('Rijksoverheid · Hoe hoog is mijn bijstandsuitkering?',R+'vraag-en-antwoord/bijstand/hoe-hoog-is-mijn-bijstandsuitkering'),
('Rijksoverheid · Bijstand voor jongeren',R+'vraag-en-antwoord/bijstand/welke-regels-gelden-er-voor-de-bijstand-voor-jongeren'),
('Rijksoverheid · Rechten en plichten in de bijstand',R+'vraag-en-antwoord/bijstand/wat-zijn-mijn-rechten-en-plichten-in-de-bijstand'),
('Rijksoverheid · Taaleis in de bijstand',R+'vraag-en-antwoord/bijstand/wat-is-de-taaleis-in-de-bijstand'),
('Rijksoverheid · Nieuwe regels bijstand 2026 en 2027',R+'themas/belastingen-uitkeringen-en-toeslagen/bijstand/nieuwe-regels-bijstand-2026-en-2027'),
('Rijksoverheid · Regels voor bijstand',R+'onderwerpen/bijstand/regels-voor-bijstand'),
('Rijksoverheid · Uitkeringsbedragen per 1 juli 2026',R+'actueel/nieuws/2026/06/11/uitkeringsbedragen-per-1-juli-2026')]

AR=dict(title='المساعدة الاجتماعية (Bijstand) في هولندا 2026: من يستحقها، المبالغ من 1 يوليو، حد المدخرات، الالتزامات وشرط اللغة، والقواعد الجديدة لعامي 2026 و2027',
crumb='المساعدة الاجتماعية',
desc='دليل عميق للمساعدة الاجتماعية (Participatiewet): الشروط، المبالغ الشهرية من 1 يوليو 2026 (1,419.46 يورو للشخص الوحيد و2,027.79 للزوجين)، حد المدخرات 8,000 و16,000 يورو، قاعدة تقاسم السكن، الشباب وأسابيع البحث الأربعة، الالتزامات، شرط اللغة 1F، الهدايا حتى 1,200 يورو، وما يتغير في 2027.',
summary='<ol><li><strong>Bijstand</strong> هي شبكة الأمان الأخيرة: دخل حتى «الحد الاجتماعي الأدنى» لمن لا يملك دخلاً أو مالاً كافياً، من سن 18 وبإقامة قانونية.</li><li><strong>المبالغ الشهرية من 1 يوليو 2026</strong> (21 سنة حتى سن التقاعد، شاملة بدل العطلة): شخص وحيد <strong>1,419.46</strong> يورو، متزوجان أو ساكنان معاً <strong>2,027.79</strong> يورو.</li><li><strong>حد المدخرات 2026:</strong> 8,000 يورو للشخص الوحيد، و16,000 للأسرة أو الوالد الوحيد.</li><li><strong>الالتزامات:</strong> البحث عن عمل وقبوله، إبلاغ كل تغيير، و<strong>شرط لغة بمستوى 1F</strong> (بسيط جداً).</li><li><strong>جديد 2026:</strong> الهدايا حتى 1,200 يورو سنوياً لا تُبلَّغ، ورعاية قريب لا تخفض المساعدة. <strong>من 2027:</strong> هامش حتى 1,000 يورو سنوياً للدخل المتقلب.</li></ol>',
body=(
'<h2 id="who">من يستحق المساعدة الاجتماعية؟</h2><ul><li>عمرك 18 سنة فأكثر.</li><li>تسكن في هولندا بجنسية هولندية أو إقامة سارية.</li><li>دخلك ومالك أقل من الحد اللازم للعيش (تحت معيار المساعدة).</li><li>لا يحق لك دخل أو دعم آخر قبلها (مثل WW أو تمويل الدراسة) (<a href="/articles/unemployment-benefit-ww.html">إعانة البطالة WW</a>).</li><li>من بلغ سن التقاعد يطلب عبر SVB (<a href="/articles/aow-aio-pension.html">AOW وAIO</a>).</li></ul>'
'<h2 id="amounts">كم المبلغ؟ (1 يوليو 2026، شاملة بدل العطلة)</h2>'
+T([['شخص وحيد، 21 سنة حتى سن التقاعد','1,401.50','<strong>1,419.46</strong>'],['متزوجان أو ساكنان معاً، 21 حتى سن التقاعد','2,002.13','<strong>2,027.79</strong>'],['شخص وحيد بعد سن التقاعد','—','1,587.34'],['متزوجان بعد سن التقاعد','—','2,176.10']],['الحالة (يورو شهرياً)','1 يناير 2026','1 يوليو 2026'])
+'<ul><li><strong>قاعدة تقاسم التكاليف (kostendelersnorm):</strong> إن سكن معك بالغون عمرهم 27 سنة فأكثر (غير شريكك) ينخفض المبلغ؛ كلما زاد عددهم انخفض أكثر. الأبناء تحت 27 لا يُحسبون.</li><li><strong>18–20 سنة:</strong> معيار أقل للشباب، لأن على الأهل واجب النفقة.</li><li>تُرفع المبالغ مرتين سنوياً مع <a href="/articles/minimum-wage-netherlands.html">الحد الأدنى للأجر</a> (14.99 يورو للساعة من 1 يوليو 2026).</li></ul>'
'<h2 id="assets">حد المدخرات والممتلكات (2026)</h2>'
+T([['شخص وحيد','8,000 يورو'],['زوجان/ساكنان معاً','16,000 يورو'],['والد وحيد','16,000 يورو']],['الحالة','حد المدخرات'])
+'<p>يمكن خصم الديون المثبتة؛ لكن قرض الدراسة والديون للعائلة لا تُخصم. السيارة والبيت يُنظر فيهما حسب القواعد والبلدية.</p>'
'<h2 id="youth">الشباب تحت 27</h2><ul><li>تبحث أولاً <strong>4 أسابيع</strong> عن عمل أو دراسة، ثم تقدّم الطلب النهائي.</li><li>الشباب في وضع هش (بلا مأوى، مشكلة نفسية أو جسدية، مشاكل في البيت) يحصلون على المساعدة فوراً.</li><li>منذ 2026 يحتفظ الشباب (15–27) بـ15% من أجرهم إن عملوا بجانب المساعدة.</li></ul>'
'<h2 id="duties">الالتزامات</h2>'
+T([['العمل','قبول العمل المناسب والحفاظ عليه، والتعاون في برامج العودة للعمل'],['المقابل (tegenprestatie)','أنشطة مفيدة للمجتمع بلا أجر إن طلبتها البلدية'],['واجب الإبلاغ','كل تغيير: دخل، ميراث، انتقال، علاقة، هدايا فوق 1,200 يورو سنوياً'],['الهوية','هوية سارية؛ منذ 2026 تقبل رخصة القيادة السارية'],['الإجازة','حتى 28 يوماً سنوياً، بإذن مسبق'],['اللغة','شرط اللغة 1F (انظر أدناه)']],['الالتزام','التفاصيل'])
+'<p>عدم الالتزام قد يخفض المساعدة، ويجب على البلدية مراعاة ظروفك. عدم الإبلاغ يؤدي إلى استرداد المبلغ وقد تُضاف غرامة.</p>'
'<h2 id="language">شرط اللغة في المساعدة الاجتماعية</h2><ul><li>المستوى المطلوب <strong>1F</strong>: قراءة وكتابة نصوص قصيرة وبسيطة (ليس B1).</li><li>الإثبات: 8 سنوات تعليم بالهولندية، أو امتحان الاندماج، أو ما يعادله؛ وإلا تُجري اختبار لغة.</li><li>إن لم تستوفِ الشرط ولم تبذل جهداً: خصم <strong>20%</strong> في أول 6 أشهر، ثم <strong>40%</strong> في الأشهر الستة التالية، ثم حتى <strong>100%</strong>.</li><li>المشاركة في دروس الاندماج تُعد جهداً (<a href="/articles/inburgering-integration-law-2026.html">الاندماج</a>).</li></ul>'
'<h2 id="new">القواعد الجديدة 2026 و2027</h2>'
+T([['1 يناير 2026','يمكن للبلدية الصرف بأثر رجعي حتى 3 أشهر؛ الهدايا حتى 1,200 يورو سنوياً لا تُبلَّغ؛ إعادة الطلب خلال سنة دون كل الوثائق من جديد؛ رعاية قريب (mantelzorg) لا تخفض المساعدة؛ 15% من أجر الشباب يبقى لهم.'],['1 يناير 2027','هامش حتى <strong>1,000 يورو</strong> سنوياً لمن دخله متقلب (عمل جزئي)؛ اعتراف أوسع بالتطوع والدراسة والرعاية كمشاركة؛ دعم للوالد الوحيد.']],['التاريخ','التغيير'])
+'<h2 id="apply">كيف تطلب؟</h2><ol><li>اطلب عبر <strong>werk.nl</strong> أو مباشرة من البلدية.</li><li>جهّز: الهوية، الإقامة، عقد الإيجار، كشوف البنك لكل الحسابات، إثبات الدخل، والديون.</li><li>تطلب البلدية مقابلة وقد تزورك.</li><li>القرار عادة خلال 8 أسابيع؛ اسأل عن «سلفة» إن كنت بلا مال.</li><li>بعدها اطلب أيضاً: <a href="/articles/zorgtoeslag-guide.html">بدل الرعاية</a>، <a href="/articles/housing-rent-allowance-2026.html">بدل الإيجار</a>، و<a href="/articles/municipal-taxes-exemption-kwijtschelding.html">إعفاء ضرائب البلدية</a>.</li></ol>'
'<h2 id="work">العمل بجانب المساعدة</h2><p>العمل الجزئي يُخصم من المساعدة عادة، مع استثناءات (مثل نسبة الشباب 15%، وهامش 2027). أبلغ كل دخل فوراً. الهدف من المساعدة الانتقال للعمل؛ اسأل عن برامج البلدية والتدريب (<a href="/articles/trending-jobs-2026.html">المهن المطلوبة</a>).</p>'
'<h2 id="mistakes">أخطاء تكلّف غالياً</h2><ol><li>عدم إبلاغ ساكن جديد أو علاقة.</li><li>تحويلات مالية من العائلة دون إبلاغ (فوق 1,200 يورو).</li><li>السفر دون إذن أو أكثر من 28 يوماً.</li><li>إخفاء حساب بنكي في الخارج.</li><li>تجاهل رسائل البلدية.</li></ol>'),
faq=[('كم مبلغ المساعدة الاجتماعية في 2026؟','من 1 يوليو 2026: 1,419.46 يورو شهرياً للشخص الوحيد و2,027.79 للزوجين (21 سنة حتى سن التقاعد، شاملة بدل العطلة).'),
('كم يمكن أن أملك من مدخرات؟','8,000 يورو للشخص الوحيد، و16,000 للأسرة أو الوالد الوحيد في 2026.'),
('هل يجب أن أتكلم الهولندية؟','نعم بمستوى 1F البسيط. عدم بذل الجهد قد يخفض المساعدة 20% ثم 40% ثم أكثر.'),
('هل أبلغ عن مال تعطيني إياه عائلتي؟','الهدايا حتى 1,200 يورو سنوياً لا تُبلَّغ منذ 2026؛ ما فوقها يجب إبلاغه.'),
('ابني البالغ يسكن معي، هل تنخفض مساعدتي؟','فقط إن كان عمره 27 سنة فأكثر (قاعدة تقاسم التكاليف).'),
('أين أطلب؟','عبر werk.nl أو البلدية؛ ومن بلغ سن التقاعد عبر SVB.')],
src_note='راجعنا صفحات Rijksoverheid عن المساعدة الاجتماعية في 5 أكتوبر 2026. البلديات تنفذ القانون وتختلف في التفاصيل؛ اعتمد على رسائل بلديتك. لم نتمكن من تأكيد نسب قاعدة تقاسم التكاليف ومعيار 18–20 سنة بالأرقام.')

NL=dict(title='Bijstand in 2026: wie recht heeft, normen per 1 juli, vermogensgrens, plichten en taaleis, en de nieuwe regels voor 2026 en 2027',
crumb='Bijstand',
desc='Uitgebreide gids Participatiewet: voorwaarden, normen per 1 juli 2026 (€ 1.419,46 alleenstaand, € 2.027,79 gehuwd), vermogensgrens € 8.000/€ 16.000, kostendelersnorm, jongeren en 4 weken zoektijd, plichten, taaleis 1F, giften tot € 1.200 en wat er in 2027 verandert.',
summary='<ol><li><strong>Bijstand</strong> is het laatste vangnet: inkomen tot het sociaal minimum voor wie niet genoeg inkomen of vermogen heeft (18+, rechtmatig verblijf).</li><li><strong>Normen per 1 juli 2026</strong> (21 tot AOW, incl. vakantiegeld): alleenstaande <strong>€ 1.419,46</strong>, gehuwd/samenwonend <strong>€ 2.027,79</strong>.</li><li><strong>Vermogensgrens 2026:</strong> € 8.000 alleenstaand, € 16.000 gezin of alleenstaande ouder.</li><li><strong>Plichten:</strong> werk zoeken en aanvaarden, wijzigingen doorgeven en een <strong>taaleis op niveau 1F</strong>.</li><li><strong>Nieuw 2026:</strong> giften tot € 1.200 per jaar hoef je niet te melden; mantelzorg verlaagt de uitkering niet. <strong>2027:</strong> buffer tot € 1.000 bij wisselend inkomen.</li></ol>',
body=(
'<h2 id="who">Wie heeft recht?</h2><ul><li>18 jaar of ouder.</li><li>Wonen in Nederland met Nederlandse nationaliteit of geldige vergunning.</li><li>Te weinig inkomen en vermogen.</li><li>Geen recht op een voorliggende voorziening zoals WW of studiefinanciering (<a href="/nl/articles/unemployment-benefit-ww.html">WW</a>).</li><li>Vanaf AOW-leeftijd via de SVB (<a href="/nl/articles/aow-aio-pension.html">AOW en AIO</a>).</li></ul>'
'<h2 id="amounts">Bedragen (incl. vakantiegeld)</h2>'
+T([['Alleenstaande, 21 tot AOW','1.401,50','<strong>1.419,46</strong>'],['Gehuwd/samenwonend, 21 tot AOW','2.002,13','<strong>2.027,79</strong>'],['Alleenstaande vanaf AOW','—','1.587,34'],['Gehuwd vanaf AOW','—','2.176,10']],['Situatie (€ per maand)','1 januari 2026','1 juli 2026'])
+'<ul><li><strong>Kostendelersnorm:</strong> wonen er volwassenen van 27+ bij je (niet je partner), dan daalt je uitkering. Jongeren onder 27 tellen niet mee.</li><li><strong>18–20 jaar:</strong> lagere jongerennorm (onderhoudsplicht ouders).</li><li>Bedragen stijgen twee keer per jaar mee met het <a href="/nl/articles/minimum-wage-netherlands.html">minimumloon</a> (€ 14,99 per uur per 1 juli 2026).</li></ul>'
'<h2 id="assets">Vermogensgrens 2026</h2>'
+T([['Alleenstaande','€ 8.000'],['Gehuwd/samenwonend','€ 16.000'],['Alleenstaande ouder','€ 16.000']],['Situatie','Grens'])
+'<p>Aantoonbare schulden mogen eraf; studieschuld en schulden bij familie niet.</p>'
'<h2 id="youth">Jongeren onder 27</h2><ul><li>Eerst <strong>4 weken</strong> zoeken naar werk of opleiding, dan de definitieve aanvraag.</li><li>Kwetsbare jongeren krijgen direct bijstand.</li><li>Sinds 2026 houden jongeren (15–27) 15% van hun loon.</li></ul>'
'<h2 id="duties">Plichten</h2>'
+T([['Werk','Werk aanvaarden en behouden, meewerken aan re-integratie'],['Tegenprestatie','Onbetaalde nuttige activiteiten als de gemeente dat vraagt'],['Inlichtingenplicht','Inkomen, erfenis, verhuizing, relatie, giften boven € 1.200 per jaar'],['ID','Geldig ID; sinds 2026 ook een geldig rijbewijs'],['Vakantie','Max. 28 dagen per jaar, vooraf toestemming'],['Taal','Taaleis 1F']],['Plicht','Toelichting'])
+'<p>Niet nakomen kan tot verlaging leiden; de gemeente moet rekening houden met je situatie. Niet melden betekent terugvordering en mogelijk een boete.</p>'
'<h2 id="language">Taaleis</h2><ul><li>Niveau <strong>1F</strong>: korte, eenvoudige teksten lezen en schrijven (geen B1).</li><li>Bewijs: 8 jaar Nederlandstalig onderwijs, inburgeringsexamen of gelijkwaardig; anders een taaltoets.</li><li>Geen inspanning: <strong>20%</strong> verlaging de eerste 6 maanden, dan <strong>40%</strong>, daarna tot <strong>100%</strong>.</li><li>Deelname aan inburgeringslessen telt als inspanning (<a href="/nl/articles/inburgering-integration-law-2026.html">inburgeren</a>).</li></ul>'
'<h2 id="new">Nieuwe regels 2026 en 2027</h2>'
+T([['1 januari 2026','Tot 3 maanden terugwerkend uitkeren; giften tot € 1.200 per jaar niet melden; binnen een jaar opnieuw aanvragen zonder alle bewijsstukken; mantelzorg verlaagt de uitkering niet; jongeren houden 15% van hun loon.'],['1 januari 2027','Buffer tot <strong>€ 1.000</strong> per jaar bij schommelend inkomen; ruimere erkenning van vrijwilligerswerk, opleiding en mantelzorg; tegemoetkoming alleenstaande ouders.']],['Datum','Wijziging'])
+'<h2 id="apply">Aanvragen</h2><ol><li>Via <strong>werk.nl</strong> of de gemeente.</li><li>Neem mee: ID, verblijfsdocument, huurcontract, bankafschriften van alle rekeningen, inkomen en schulden.</li><li>Gesprek en soms huisbezoek.</li><li>Besluit meestal binnen 8 weken; vraag om een voorschot als je niets hebt.</li><li>Vraag ook <a href="/nl/articles/zorgtoeslag-guide.html">zorgtoeslag</a>, <a href="/nl/articles/housing-rent-allowance-2026.html">huurtoeslag</a> en <a href="/nl/articles/municipal-taxes-exemption-kwijtschelding.html">kwijtschelding</a>.</li></ol>'
'<h2 id="work">Werken naast bijstand</h2><p>Inkomsten worden meestal verrekend, met uitzonderingen (15% voor jongeren, buffer 2027). Geef alles direct door. Vraag naar werkprogramma’s van de gemeente (<a href="/nl/articles/trending-jobs-2026.html">kansrijke beroepen</a>).</p>'
'<h2 id="mistakes">Dure fouten</h2><ol><li>Een nieuwe huisgenoot of relatie niet melden.</li><li>Geld van familie boven € 1.200 niet melden.</li><li>Zonder toestemming of langer dan 28 dagen op reis.</li><li>Een buitenlandse rekening verzwijgen.</li><li>Brieven van de gemeente negeren.</li></ol>'),
faq=[('Hoe hoog is de bijstand in 2026?','Per 1 juli 2026: € 1.419,46 alleenstaand en € 2.027,79 gehuwd (21 tot AOW, incl. vakantiegeld).'),
('Hoeveel vermogen mag ik hebben?','€ 8.000 alleenstaand, € 16.000 gezin of alleenstaande ouder.'),
('Moet ik Nederlands spreken?','Ja, op niveau 1F; zonder inspanning volgt een verlaging van 20%, dan 40% en meer.'),
('Moet ik geld van familie melden?','Giften tot € 1.200 per jaar niet sinds 2026; daarboven wel.'),
('Mijn volwassen zoon woont bij mij. Daalt mijn bijstand?','Alleen als hij 27 of ouder is (kostendelersnorm).'),
('Waar vraag ik aan?','Via werk.nl of de gemeente; vanaf AOW-leeftijd bij de SVB.')],
src_note='Gecontroleerd op Rijksoverheid-pagina’s over bijstand op 5 oktober 2026. Gemeenten voeren uit en verschillen in details; ga uit van je gemeente. Percentages van de kostendelersnorm en de jongerennorm konden we niet officieel bevestigen.')
