from a_student_finance import T
SLUG='bol-bbl-comparison'
SRC=[('SBB · Verschil tussen bol en bbl','https://www.s-bb.nl/bedrijven/wat-is-een-leerbedrijf/verschil-bol-en-bbl'),
('Rijksoverheid · Hoogte lesgeld en cursusgeld mbo','https://www.rijksoverheid.nl/vraag-en-antwoord/middelbaar-beroepsonderwijs/hoogte-lesgeld-en-cursusgeld-mbo'),
('Rijksoverheid · Studiefinanciering mbo','https://www.rijksoverheid.nl/themas/onderwijs/studiefinanciering/studiefinanciering-mbo'),
('Rijksoverheid · Bedragen minimumloon bbl 2026','https://www.rijksoverheid.nl/themas/werk/minimumloon/bedragen-minimumloon-bbl-opleiding/bedragen-minimumloon-bbl-2026'),
('Rijksoverheid · Hoger minimumjeugdloon vanaf 2027','https://www.rijksoverheid.nl/actueel/nieuws/2026/04/17/hoger-minimumjeugdloon-vanaf-2027')]
AR=dict(title='BOL أم BBL؟ مقارنة الدراسة والتدريب والعمل: الوقت، الراتب، التكلفة، والتمويل',
crumb='BOL أم BBL',
desc='مقارنة بين BOL وBBL في MBO: أيام المدرسة، الراتب وعقد العمل، lesgeld وcursusgeld (2026/27)، الحد الأدنى لأجر BBL، التمويل، ومن يناسبه كل مسار.',
summary='<ol><li><strong>BOL:</strong> تدرس 4 إلى 5 أيام أسبوعياً وتتدرب عند شركة معتمدة (stage) في فترات، ولا راتب مضمون.</li><li><strong>BBL:</strong> تدرس يوماً أو يومين وتعمل 3 إلى 4 أيام على الأقل عند شركة معتمدة بعقد عمل وراتب.</li><li>تكلفة الدراسة: BOL 18+ يدفع <strong>lesgeld 1,511 يورو</strong> (2026/27)، وBBL يدفع <strong>cursusgeld 314 أو 762 يورو</strong>.</li><li>BOL يستحق <strong>studiefinanciering</strong>؛ BBL يتقاضى راتباً وله جدول حد أدنى للأجر خاص حتى نهاية 2026.</li><li>BBL يتطلب <strong>إيجاد شركة</strong> تقبل بك قبل أن تبدأ فعلياً.</li></ol>',
body=(
'<h2 id="table">مقارنة سريعة</h2>'
+T([['أيام المدرسة','4–5 أيام أسبوعياً','1–2 يوم أسبوعياً'],['العمل','تدريب (stage) في فترات من أسابيع إلى سنة دراسية','3–4 أيام أسبوعياً على الأقل عند شركة معتمدة (والحد الأدنى 16 ساعة أسبوعياً بحسب SBB)'],['العقد','اتفاقية تدريب (bpv) بين الطالب والمدرسة والشركة','عقد عمل (arbeidsovereenkomst) وفق قانون WEB'],['المال','لا راتب بالضرورة؛ studiefinanciering','راتب؛ وقد تُدفع أيام المدرسة إن نصّ CAO'],['رسوم الدراسة (18+)','lesgeld 1,511 يورو (2026/27)','cursusgeld 314 (مستوى 1–2) أو 762 (مستوى 3–4)'],['المدة','حسب الدراسة','عادةً من سنة إلى 4 سنوات'],['تجربة العمل','محدودة في فترات التدريب','واسعة: تعمل طوال الدراسة']],['','BOL','BBL'])
+'<p>المصدر: SBB (مؤسسة التعاون بين التعليم المهني وسوق العمل) والحكومة الهولندية.</p>'
'<h2 id="bol">BOL: متى يناسبك؟</h2><ul><li>تفضل تعلماً نظرياً قوياً وبنية مدرسية.</li><li>لا تملك شركة تعمل بها بعد، أو لغتك الهولندية ما زالت تتطور فتحتاج مدرسة أكثر.</li><li>يحق لك <strong>studiefinanciering</strong> (<a href="/articles/student-finance.html">تفاصيلها</a>).</li><li>الشركة قد تعرض عليك عملاً أو عقداً لكنك غير ملزم بقبوله.</li></ul>'
'<h2 id="bbl">BBL: متى يناسبك؟</h2><ul><li>تريد <strong>راتباً</strong> وخبرة عمل منذ اليوم الأول.</li><li>أنت بالغ أو تغيّر مهنتك (zij-instromer): نحو 29% من طلاب BBL بالغون ومتحولون مهنياً بحسب SBB.</li><li>تستطيع إيجاد شركة معتمدة تقبلك بعقد.</li><li>تتقبل أن عقد العمل قد يتضمن <strong>proeftijd</strong> وقد يشترط البقاء مدة بعد الدبلوم إن دفعت الشركة دورات إضافية.</li></ul>'
'<h2 id="pay">الراتب في BBL</h2><p>أنت موظف، فتستحق على الأقل الحد الأدنى الخاص بـBBL (إجمالي بالساعة، وفق الحكومة):</p>'
+T([['21+','14.71','14.99'],['20','9.05','9.22'],['19','7.72','7.87'],['18','6.69','6.82'],['17','5.81','5.92'],['16','5.07','5.17']],['العمر','من 1 يناير 2026','من 1 يوليو 2026'])
+'<p>وأعلنت الحكومة (17 أبريل 2026) أنها ستساوي حد BBL للشباب بالحد العام من <strong>1 يناير 2027</strong> (خطة معلنة، تحقق عند التنفيذ). التفاصيل في <a href="/articles/minimum-wage-netherlands.html">دليل الحد الأدنى للأجر</a>. كثير من CAO تدفع أعلى؛ اقرأ عقدك. وهل تُدفع أيام المدرسة؟ يتوقف على CAO أو على ما تقدمه الشركة طوعاً.</p>'
'<h2 id="cost">التكلفة والتمويل</h2>'
+T([['BOL (18+)','lesgeld 1,511','1,554'],['BBL مستوى 1–2','cursusgeld 314','323'],['BBL مستوى 3–4','cursusgeld 762','784']],['المسار','2026/2027 (يورو)','2027/2028 (يورو)'])
+'<ul><li><strong>BOL:</strong> basisbeurs وaanvullende beurs ومواصلات وقرض اختياري. المستوى 1–2 هبة؛ والمستوى 3–4 prestatiebeurs تتحول هبة بالدبلوم خلال 10 سنوات.</li><li><strong>BBL:</strong> الراتب هو مصدرك. وقد تستحق <a href="/articles/zorgtoeslag-guide.html">zorgtoeslag</a> بحسب دخلك.</li><li>تأمين صحي إلزامي في الحالين (<a href="/articles/health-insurance-newcomers.html">التأمين للقادمين</a>).</li></ul>'
'<h2 id="find">كيف أجد شركة لـBBL؟</h2><ol><li>اختر الدراسة والمعهد أولاً.</li><li>ابحث عن <strong>leerbedrijf معتمد</strong> عبر SBB (تتحقق من الاعتماد).</li><li>اعرض نفسك على الشركات مباشرة وعبر المعهد.</li><li>تأكد أن العقد يوافق قانون WEB وأنك تفهم بنود الإقامة بعد الدبلوم ومدة الاختبار.</li><li>اسأل المعهد قبل التوقيع: ماذا يحدث إن انتهى العقد في أثناء الدراسة؟</li></ol>'
'<h2 id="who">شروط القبول</h2><p>الشروط تُحدد بالمستوى والشهادة السابقة وليست بنوع BOL أو BBL (<a href="/articles/mbo-conditions.html">شروط MBO</a>). وفي BBL تحتاج بالإضافة عقداً مع شركة.</p>'
'<h2 id="mistakes">أخطاء شائعة</h2><ul><li><strong>اختيار BBL قبل وجود شركة.</strong></li><li><strong>نسيان cursusgeld.</strong></li><li><strong>الاعتقاد أن تدريب BOL مدفوع.</strong> ليس بالضرورة.</li><li><strong>عدم قراءة بند الاستمرار بعد الدبلوم.</strong></li><li><strong>عدم مقارنة راتب BBL بالحد الأدنى الصحيح لعمرك.</strong></li></ul>'
'<p>بعد MBO: <a href="/articles/mbo-hbo-wo-comparison.html">MBO وHBO وWO</a>. لقراءة عقدك: <a href="/articles/employment-contracts-labor-law-2026.html">عقود العمل</a>.</p>'),
faq=[('ما الفرق الأساسي بين BOL وBBL؟','BOL معظمه مدرسة مع تدريب؛ BBL عمل بعقد وراتب مع يوم أو يومين في المدرسة.'),
('هل BBL مدفوع؟','نعم، بعقد عمل وراتب لا يقل عن الحد الأدنى الخاص بـBBL.'),
('كم الرسوم في 2026/27؟','BOL 18+ يدفع 1,511 يورو؛ BBL يدفع 314 أو 762 يورو.'),
('هل يحق لطالب BBL studiefinanciering؟','تتحدث الحكومة عن الحق للطلاب في BOL؛ طالب BBL يتقاضى راتباً.'),
('هل أحتاج شركة؟','في BBL نعم: شركة معتمدة وعقد عمل.')],
src_note='الفروق من SBB، والرسوم والتمويل والحد الأدنى من Rijksoverheid، راجعناها في 4 أكتوبر 2026. جملة أن BBL لا studiefinanciering له استنتاج من أن الحكومة تذكر الحق لـBOL فقط؛ تحقق من DUO لحالتك.')
NL=dict(title='Bol of bbl? Leren, werken en verdienen vergeleken: tijd, loon, kosten en financiering',
crumb='Bol of bbl',
desc='Bol en bbl in het mbo vergeleken: schooldagen, loon en arbeidsovereenkomst, lesgeld en cursusgeld (2026-2027), minimumloon bbl, financiering en voor wie welke route past.',
summary='<ol><li><strong>Bol:</strong> 4 tot 5 dagen per week naar school en stage bij een erkend leerbedrijf in periodes; geen vast loon.</li><li><strong>Bbl:</strong> 1 tot 2 dagen naar school en minimaal 3 tot 4 dagen werken bij een erkend leerbedrijf met een arbeidsovereenkomst en loon.</li><li>Kosten: bol vanaf 18 betaalt <strong>lesgeld € 1.511</strong> (2026-2027); bbl betaalt <strong>cursusgeld € 314 of € 762</strong>.</li><li>Bol geeft recht op <strong>studiefinanciering</strong>; bbl-leerlingen verdienen loon met een eigen minimumloontabel tot eind 2026.</li><li>Voor bbl moet je eerst een <strong>leerbedrijf</strong> vinden.</li></ol>',
body=(
'<h2 id="table">Snel vergeleken</h2>'
+T([['Schooldagen','4–5 dagen per week','1–2 dagen per week'],['Werken','Stage in periodes van weken tot een schooljaar','Minimaal 3–4 dagen per week bij een erkend leerbedrijf (minimaal 16 uur per week volgens SBB)'],['Contract','Stageovereenkomst (bpv) tussen student, school en bedrijf','Arbeidsovereenkomst conform de WEB'],['Geld','Geen vast loon; studiefinanciering','Loon; schooldagen soms betaald via de cao'],['Kosten (18+)','Lesgeld € 1.511 (2026-2027)','Cursusgeld € 314 (niveau 1-2) of € 762 (niveau 3-4)'],['Duur','Afhankelijk van opleiding','Meestal 1 tot 4 jaar'],['Werkervaring','Beperkt tot stageperiodes','Veel: je werkt de hele opleiding']],['','Bol','Bbl'])
+'<p>Bron: SBB (Samenwerking Beroepsonderwijs Bedrijfsleven) en de Rijksoverheid.</p>'
'<h2 id="bol">Bol: wanneer past het?</h2><ul><li>Je wilt een stevige theoretische basis en schoolstructuur.</li><li>Je hebt nog geen werkgever, of je Nederlands is nog in ontwikkeling en je kunt meer schoolbegeleiding gebruiken.</li><li>Je hebt recht op <strong>studiefinanciering</strong> (<a href="/nl/articles/student-finance.html">meer</a>).</li><li>Een bedrijf kan je een bijbaan of contract aanbieden, maar je moet daar niet op ingaan.</li></ul>'
'<h2 id="bbl">Bbl: wanneer past het?</h2><ul><li>Je wilt <strong>loon</strong> en werkervaring vanaf dag 1.</li><li>Je bent volwassen of verandert van loopbaan (zij-instromer): ongeveer 29% van de bbl-studenten is volwassene of zij-instromer volgens SBB.</li><li>Je kunt een erkend leerbedrijf vinden dat je aanneemt.</li><li>Je accepteert dat je contract een <strong>proeftijd</strong> kan hebben en een bindingsperiode na het diploma kan bevatten als het bedrijf extra cursussen betaalde.</li></ul>'
'<h2 id="pay">Loon in de bbl</h2><p>Je bent werknemer en hebt minimaal recht op het bbl-minimumloon (bruto per uur, volgens de overheid):</p>'
+T([['21+','14,71','14,99'],['20','9,05','9,22'],['19','7,72','7,87'],['18','6,69','6,82'],['17','5,81','5,92'],['16','5,07','5,17']],['Leeftijd','Vanaf 1 januari 2026','Vanaf 1 juli 2026'])
+'<p>Het kabinet kondigde op 17 april 2026 aan het bbl-jeugdloon per <strong>1 januari 2027</strong> gelijk te trekken met het reguliere jeugdloon (aangekondigd plan; controleer bij invoering). Meer in de <a href="/nl/articles/minimum-wage-netherlands.html">gids minimumloon</a>. Veel cao-s betalen meer; lees je contract. Worden schooldagen betaald? Dat hangt af van de cao of van een vrijwillige vergoeding.</p>'
'<h2 id="cost">Kosten en financiering</h2>'
+T([['Bol (18+)','lesgeld 1.511','1.554'],['Bbl niveau 1-2','cursusgeld 314','323'],['Bbl niveau 3-4','cursusgeld 762','784']],['Route','2026-2027 (€)','2027-2028 (€)'])
+'<ul><li><strong>Bol:</strong> basisbeurs, aanvullende beurs, reisproduct en optionele lening. Niveau 1-2 gift; niveau 3-4 prestatiebeurs die een gift wordt bij een diploma binnen 10 jaar.</li><li><strong>Bbl:</strong> je loon is je inkomen. Afhankelijk van je inkomen kun je <a href="/nl/articles/zorgtoeslag-guide.html">zorgtoeslag</a> krijgen.</li><li>Zorgverzekering is in beide gevallen verplicht (<a href="/nl/articles/health-insurance-newcomers.html">voor nieuwkomers</a>).</li></ul>'
'<h2 id="find">Een leerbedrijf vinden voor de bbl</h2><ol><li>Kies eerst opleiding en school.</li><li>Zoek een <strong>erkend leerbedrijf</strong> via SBB (controleer de erkenning).</li><li>Solliciteer direct en via de school.</li><li>Controleer dat het contract aan de WEB voldoet en dat je bindingsperiode en proeftijd begrijpt.</li><li>Vraag de school vooraf: wat gebeurt er als je contract tijdens de opleiding eindigt?</li></ol>'
'<h2 id="who">Toelating</h2><p>De toelatingseisen hangen af van niveau en vooropleiding, niet van bol of bbl (<a href="/nl/articles/mbo-conditions.html">toelating mbo</a>). Voor de bbl heb je daarnaast een contract met een bedrijf nodig.</p>'
'<h2 id="mistakes">Veelgemaakte fouten</h2><ul><li><strong>Bbl kiezen zonder leerbedrijf.</strong></li><li><strong>Cursusgeld vergeten.</strong></li><li><strong>Denken dat een bol-stage betaald is.</strong> Niet per se.</li><li><strong>De bindingsclausule niet lezen.</strong></li><li><strong>Bbl-loon niet toetsen aan het juiste minimum voor je leeftijd.</strong></li></ul>'
'<p>Na het mbo: <a href="/nl/articles/mbo-hbo-wo-comparison.html">mbo, hbo en wo</a>. Je contract lezen: <a href="/nl/articles/employment-contracts-labor-law-2026.html">arbeidscontracten</a>.</p>'),
faq=[('Wat is het belangrijkste verschil tussen bol en bbl?','Bol is vooral school met stage; bbl is werken met een arbeidsovereenkomst en loon, met 1 of 2 schooldagen.'),
('Krijg ik loon in de bbl?','Ja, met een arbeidsovereenkomst en minimaal het bbl-minimumloon.'),
('Wat kost het in 2026-2027?','Bol 18+: € 1.511; bbl: € 314 of € 762.'),
('Heeft een bbl-student recht op studiefinanciering?','De overheid noemt dat recht voor bol-studenten; een bbl-student verdient loon.'),
('Heb ik een bedrijf nodig?','In de bbl wel: een erkend leerbedrijf en een arbeidsovereenkomst.')],
src_note='Verschillen komen van SBB; kosten, financiering en minimumloon van Rijksoverheid, gecontroleerd op 4 oktober 2026. Dat bbl geen studiefinanciering heeft is onze afleiding uit het feit dat de overheid dit recht voor bol noemt; controleer bij DUO voor jouw situatie.')
