from a_student_finance import T
SLUG='cbr-driving-license-netherlands'
SRC=[('CBR · Wat kost het halen van een autorijbewijs?','https://www.cbr.nl/nl/rijbewijs-halen/auto/wat-kost-het-halen-van-een-autorijbewijs'),
('CBR · Welk theorie-examen past bij jou?','https://www.cbr.nl/nl/rijbewijs-halen/auto/theorie-examen-auto/welk-theorie-examen-past-bij-jou'),
('CBR · Hoe lang is mijn theorie-examen geldig?','https://www.cbr.nl/nl/veelgestelde-vragen/hoe-lang-is-het-positieve-resultaat-van-mijn-theorie-examen-geldig'),
('CBR · Stappenplan rijden voor je 18e (2toDrive)','https://www.cbr.nl/nl/rijbewijs-halen/auto/je-autorijbewijs-halen/stappenplan-rijden-voor-je-18e'),
('RDW · Hoe werkt het halen van een rijbewijs?','https://www.rdw.nl/het-rijbewijs/rijbewijs-halen/hoe-werkt-het-halen-van-een-rijbewijs'),
('RDW · Buitenlands rijbewijs omwisselen','https://www.rdw.nl/het-rijbewijs/buitenlands-rijbewijs/buitenlands-rijbewijs-omwisselen'),
('RDW · Exchanging a foreign driving licence (landenlijst)','https://www.rdw.nl/en/driving-licence/foreign-driving-licence/exchanging-a-foreign-driving-licence'),
('RDW · Rijden met een buitenlands rijbewijs','https://www.rdw.nl/het-rijbewijs/buitenlands-rijbewijs/rijden-met-een-buitenlands-rijbewijs'),
('Rijksoverheid · Mag ik met mijn buitenlandse rijbewijs in Nederland rijden?','https://www.rijksoverheid.nl/vraag-en-antwoord/mag-ik-met-mijn-buitenlandse-rijbewijs-in-nederland-aan-het-verkeer-deelnemen'),
('Rijksoverheid · Bromfietsrijbewijs: wanneer rijles en examen?','https://www.rijksoverheid.nl/onderwerpen/rijbewijs/vraag-en-antwoord/wanneer-mag-ik-rijles-nemen-en-rijexamen-doen-voor-mijn-bromfietsrijbewijs')]

AR=dict(title='رخصة القيادة في هولندا 2026: امتحان CBR النظري والعملي، التكاليف، لغات الامتحان، وتبديل الرخصة الأجنبية (ومنها السورية)',
crumb='رخصة القيادة',
seo_title='رخصة القيادة rijbewijs وامتحان CBR 2026',
desc='رخصة القيادة في هولندا 2026: النظري لدى CBR بـ50.50 يورو والعملي 143.50، الامتحان بالإنجليزية أو مع مترجم، وقاعدة 185 يوماً للرخصة الأجنبية.',
summary='<ol><li><strong>الرخصة الأجنبية من خارج أوروبا</strong> تقود بها في هولندا <strong>185 يوماً فقط</strong> من تسجيلك في البلدية، ثم تحتاج رخصة هولندية.</li><li><strong>تبديل الرخصة</strong> ممكن لرخص الاتحاد الأوروبي ولقائمة دول محددة فقط. <strong>سوريا ليست في القائمة</strong>، ولا يوجد استثناء خاص للاجئين: يجب اجتياز الامتحانين.</li><li><strong>تكاليف CBR 2026:</strong> النظري 50.50 يورو (بالإنجليزية 57، مع مترجم 118.50)، والعملي 143.50 يورو، وإفادة الصحة 45.25 يورو. يُضاف إليها ثمن دروس المدرسة، وهو الجزء الأكبر.</li><li><strong>النظري صالح 18 شهراً.</strong> يمكنك تقديمه من سن 16، والعملي من 17 مع مرافق (2toDrive).</li><li><strong>لا يمكن طلب الرخصة</strong> بوثيقة لاجئ قيد الانتظار (VI): يلزم تصريح إقامة.</li></ol>',
body=(
'<h2 id="foreign">عندك رخصة من بلدك؟ ابدأ من هنا</h2>'
+T([['رخصة من الاتحاد الأوروبي أو EFTA','تقود بها، ويمكنك تبديلها دائماً (حتى لو انتهت). الفئة B صالحة حتى 15 سنة بعد إصدارها؛ وإن كان عمرها أكثر من 15 سنة فسنتان من بدء سكنك.'],
    ['رخصة من دولة في قائمة RDW','تُبدَّل دون امتحان: أندورا، ألبرتا وكيبيك (كندا)، جبل طارق، بريطانيا وإيرلندا الشمالية، غيرنزي، جزيرة مان، جيرسي، إسرائيل، اليابان، موناكو، سنغافورة، تايوان، كوريا الجنوبية، جزر الأنتيل الهولندية السابقة. شرط: أن تكون عشت 185 يوماً في ذلك البلد في سنة حصولك عليها.'],
    ['رخصة من دولة خارج القائمة (مثل سوريا، العراق، تركيا، المغرب، مصر…)','<strong>لا تبديل.</strong> تقود بها 185 يوماً بعد تسجيلك، ثم يجب اجتياز النظري والعملي لدى CBR.'],
    ['قاعدة الـ30% (الخبراء الوافدون للعمل)','من لديه قرار expatregeling من Belastingdienst يبدّل رخصة أي دولة. ليست قاعدة للاجئين.'],
    ['أوكرانيون (الحماية المؤقتة)','يقودون برخصتهم حتى المنتهية؛ التبديل فقط مع قاعدة الـ30%.']],
   ['حالتك','ما يحدث'])
+'<p><strong>مهم للاجئين:</strong> لا توجد في صفحات RDW أي قاعدة خاصة تسمح لحاملي الإقامة بتبديل رخصة من دولة خارج القائمة. إن سمعت عكس ذلك في المجموعات، فاطلب المصدر الرسمي. الخبر الجيد: خبرتك في القيادة تجعل الدروس أقل عادة.</p><p><strong>كيف تبدّل (إن كانت دولتك مسموحة):</strong> عند البلدية، مع صورة ملونة، والرخصة الأجنبية (مترجمة ترجمة محلَّفة إن لم تكن بأحرف لاتينية)، وإفادة صحة CBR لرخص خارج أوروبا. الرسوم حسب البلدية. خلال 15 يوم عمل تصلك رسالة، ثم تستلم بعد 5 أيام عمل. لا تُعاد إليك الرخصة الأجنبية. ابدأ قبل انتهاء صلاحيتها، فالرخصة المنتهية من خارج أوروبا لا تُبدَّل. الشروط والوثائق بالتفصيل في <a href="/articles/foreign-driving-license-exchange.html">دليل تبديل الرخصة الأجنبية</a>.</p>'
'<h2 id="conditions">شروط طلب رخصة هولندية</h2><ul><li>أن تكون مسجلاً في البلدية (BRP) وتسكن في هولندا <strong>185 يوماً على الأقل</strong> (<a href="/articles/bsn-municipality-registration.html">التسجيل في البلدية</a>).</li><li>جنسية أوروبية، أو <strong>تصريح إقامة</strong> (محدد أو دائم)، أو وضع تركي حسب اتفاقية 1/80، أو حماية مؤقتة.</li><li><strong>وثيقة VI لطالب اللجوء ليست تصريح إقامة</strong>، ومن ينتظر قراراً لا يستطيع الطلب بعد. لكن يمكنك البدء بدراسة النظري.</li></ul>'
'<h2 id="costs">التكاليف الرسمية 2026</h2>'
+T([['الامتحان النظري (بالهولندية)','50.50 يورو'],['النظري بالإنجليزية','57.00 يورو'],['النظري مع وقت إضافي (45 دقيقة بدل 30)','64.00 يورو؛ مع إفادة عسر قراءة تسترد الإضافة خلال 14 يوماً'],['النظري مع مترجم أو بمرافقة فردية','118.50 يورو + أجر المترجم'],['الامتحان العملي B','143.50 يورو (تدفعه المدرسة للـCBR، ولها تكاليفها)'],['الاختبار المرحلي (tussentijdse toets)','143.50 يورو'],['إفادة الصحة (Gezondheidsverklaring)','45.25 يورو'],['امتحان لذوي القلق من الامتحان','202.00 يورو'],['إصدار الرخصة في البلدية','حد أقصى 53.65 يورو؛ المستعجل +39.65 يورو']],['البند','السعر 2026'])
+'<p>كل محاولة جديدة تُدفع بنفس السعر. الجزء الأكبر من التكلفة هو <strong>دروس القيادة</strong> لدى المدرسة، وأسعارها حرة؛ قارن بين المدارس واسأل عن نسبة النجاح وما يشمله السعر.</p>'
'<h2 id="theory">الامتحان النظري: اللغة والتحضير</h2><ul><li><strong>اللغات:</strong> الهولندية أو الإنجليزية. لأي لغة أخرى (مثل العربية) تحضر <strong>مترجماً معتمداً</strong> بنفسك، وتحجز قبل 14 يوماً على الأقل، بسعر 118.50 يورو.</li><li><strong>المدة:</strong> 30 دقيقة، و45 مع الوقت الإضافي. يمكن الاستماع للأسئلة بصوت حاسوبي بسماعات من CBR.</li><li><strong>الصلاحية:</strong> النجاح صالح <strong>18 شهراً</strong>؛ إن لم تنجح في العملي خلالها تعيد النظري (ممكن من 3 أشهر قبل الانتهاء).</li><li><strong>نصيحة:</strong> إن كانت لغتك الإنجليزية جيدة فالامتحان بالإنجليزية أرخص وأسهل من مترجم. ومن يتعلم الهولندية يستفيد مرتين.</li></ul>'
'<h2 id="steps">الخطوات من الصفر حتى البطاقة</h2><ol><li><strong>إفادة الصحة</strong> عبر Mijn CBR (45.25 يورو)؛ قد تحتاج تقرير طبيب عيون أو غيره.</li><li><strong>اختر مدرسة قيادة</strong> وابدأ الدروس.</li><li><strong>الامتحان النظري</strong> (من سن 16).</li><li><strong>اختبار مرحلي</strong> اختياري لتعرف مستواك.</li><li><strong>الامتحان العملي</strong>: تحجزه المدرسة عادة (من سن 17).</li><li><strong>اطلب الرخصة من البلدية</strong> من اليوم التالي للنجاح، مع جواز أو هوية سارية وصورة ملونة حسب المعايير. الرخصة صالحة 10 سنوات.</li></ol>'
'<h2 id="young">الشباب: القيادة من 17 سنة (2toDrive)</h2><ul><li>النظري من 16، والدروس من 16.5، والعملي من 17.</li><li>تحت 18 تقود فقط مع <strong>مرافق</strong> عمره 27 سنة على الأقل ولديه رخصة هولندية منذ 5 سنوات على الأقل (1 إلى 5 مرافقين).</li><li>تطلب أولاً بطاقة المرافق من RDW، ثم الرخصة من البلدية. رخصة المبتدئ تسري 5 سنوات.</li></ul>'
'<h2 id="moped">الدراجة النارية الصغيرة (AM)</h2><p>النظري من 15.5 سنة (50.50 يورو)، والدروس والعملي من 16 سنة (149 يورو). من لديه رخصة سيارة لا يحتاج رخصة AM منفصلة.</p>'
'<h2 id="driving-period">أثناء انتظار الرخصة</h2><ul><li>بعد 185 يوماً من تسجيلك لا يجوز القيادة برخصة من خارج أوروبا، حتى لو كان طلب التبديل قيد المعالجة.</li><li>أثناء التبديل قد لا تملك رخصة تريها للشرطة؛ احمل دائماً هويتك. لا يُنصح بالسفر بالسيارة لدول أخرى أثناء الطلب.</li><li>غرامة القيادة بلا رخصة سارية يحددها جدول الغرامات الرسمي (OM)، وقد تؤثر على تأمين السيارة. عن دفع الغرامات ومواعيدها راجع <a href="/articles/traffic-fines-cjib.html">دليل غرامات المرور وCJIB</a>.</li></ul>'
'<h2 id="mistakes">أخطاء شائعة</h2><ol><li>الاستمرار بالقيادة برخصة سورية أو عراقية بعد مرور 185 يوماً.</li><li>انتظار انتهاء الرخصة الأجنبية القابلة للتبديل، ثم يتعذر تبديلها.</li><li>حجز امتحان مع مترجم دون حجز المترجم قبل 14 يوماً.</li><li>ترك النظري ينتهي بعد 18 شهراً قبل النجاح في العملي.</li><li>نسيان إفادة الصحة، فيتأخر حجز العملي.</li></ol>'
'<h2 id="work">الرخصة والعمل</h2><p>رخصة القيادة تفتح أبواباً كثيرة: سائق توصيل، وسائق شاحنة، ونقل عام من المهن المطلوبة في قائمة UWV (<a href="/articles/trending-jobs-2026.html">المهن المطلوبة</a>). رخص C وD لها مسار وامتحانات إضافية.</p>'),
faq=[('هل يمكنني تبديل رخصتي السورية؟','لا. سوريا ليست في قائمة الدول التي تُبدَّل رخصها، ولا يوجد استثناء للاجئين. يجب اجتياز النظري والعملي لدى CBR.'),
('كم يوماً أستطيع القيادة برخصتي الأجنبية؟','للرخص من خارج أوروبا: 185 يوماً من بدء سكنك المسجل في هولندا.'),
('هل يمكن تقديم الامتحان النظري بالعربية؟','ليس مباشرة. الامتحان بالهولندية أو الإنجليزية، أو مع مترجم معتمد تحضره بنفسك (118.50 يورو للامتحان).'),
('كم تكلف رخصة القيادة؟','رسوم CBR والبلدية نحو 290 يورو (نظري 50.50 + عملي 143.50 + صحة 45.25 + بطاقة حتى 53.65)، يضاف إليها ثمن الدروس وهو الأكبر.'),
('كم مدة صلاحية النظري؟','18 شهراً بعد النجاح.'),
('هل أستطيع الطلب وأنا في مركز اللجوء؟','لا يمكن طلب الرخصة بوثيقة VI. يلزم تصريح إقامة وتسجيل في البلدية لمدة 185 يوماً.')],
src_note='راجعنا الأسعار والقواعد في CBR وRDW وRijksoverheid في 4 أكتوبر 2026. سعر إفادة الصحة ظهر بقيمتين في صفحات CBR (45.25 و46.90 يورو)؛ تحقق منه في Mijn CBR.')

NL=dict(title='Rijbewijs in Nederland 2026: CBR-theorie- en praktijkexamen, kosten, examentalen en je buitenlandse rijbewijs omwisselen',
crumb='Rijbewijs',
seo_title='Rijbewijs halen in Nederland: CBR-examen 2026',
desc='Rijbewijs halen in 2026: CBR-theorie € 50,50 en praktijk € 143,50, examen in het Engels of met tolk, en de 185-dagenregel voor je buitenlandse rijbewijs.',
summary='<ol><li><strong>Rijbewijs van buiten de EU/EVA:</strong> je mag er <strong>185 dagen</strong> na inschrijving mee rijden, daarna heb je een Nederlands rijbewijs nodig.</li><li><strong>Omwisselen</strong> kan alleen voor EU/EVA en een beperkte landenlijst. <strong>Syrië staat er niet op</strong> en er is geen aparte regeling voor statushouders.</li><li><strong>CBR-tarieven 2026:</strong> theorie € 50,50 (Engels € 57, met tolk € 118,50), praktijk € 143,50, Gezondheidsverklaring € 45,25. Plus rijlessen.</li><li><strong>Theorie is 18 maanden geldig</strong>; theorie vanaf 16, praktijkexamen vanaf 17 met coach (2toDrive).</li><li><strong>Een VI-document is geen verblijfsvergunning</strong>: zonder vergunning geen rijbewijsaanvraag.</li></ol>',
body=(
'<h2 id="foreign">Heb je al een rijbewijs uit je land?</h2>'
+T([['EU/EVA-rijbewijs','Altijd om te wisselen (ook verlopen). Categorie B geldig tot 15 jaar na afgifte; ouder dan 15 jaar: nog 2 jaar na vestiging.'],['Land op de RDW-lijst','Omwisselen zonder examen: Andorra, Alberta en Québec, Gibraltar, Groot-Brittannië en Noord-Ierland, Guernsey, Isle of Man, Jersey, Israël, Japan, Monaco, Singapore, Taiwan, Zuid-Korea, voormalige Nederlandse Antillen. Voorwaarde: 185 dagen in dat land gewoond in het jaar van afgifte.'],['Land niet op de lijst (bijv. Syrië, Irak, Turkije, Marokko, Egypte)','<strong>Niet omwisselen.</strong> 185 dagen rijden na inschrijving, daarna theorie- en praktijkexamen bij het CBR.'],['30%-regeling','Met een beschikking expatregeling wissel je een rijbewijs van elk land om; geen vluchtelingenregeling.'],['Oekraïners (titel 46)','Rijden op eigen rijbewijs, ook verlopen; omwisselen alleen met 30%-regeling.']],['Situatie','Gevolg'])
+'<p><strong>Voor statushouders:</strong> op de RDW-pagina’s staat geen aparte regeling om een rijbewijs van een land buiten de lijst om te wisselen. <strong>Omwisselen:</strong> bij de gemeente, met pasfoto, het buitenlandse rijbewijs (beëdigd vertaald bij niet-Latijnse tekens) en een Gezondheidsverklaring bij een rijbewijs van buiten de EU/EVA. Kosten per gemeente. Binnen 15 werkdagen een brief, ophalen na 5 werkdagen. Je krijgt het buitenlandse rijbewijs niet terug; start vóór het verloopt. Zie onze <a href="/nl/articles/foreign-driving-license-exchange.html">gids over buitenlands rijbewijs omwisselen</a>.</p>'
'<h2 id="conditions">Voorwaarden voor een Nederlands rijbewijs</h2><ul><li>Ingeschreven in de BRP en minstens <strong>185 dagen</strong> in Nederland wonen (<a href="/nl/articles/bsn-municipality-registration.html">inschrijven bij de gemeente</a>).</li><li>EU/EVA-nationaliteit, een <strong>verblijfsvergunning</strong> (bepaalde of onbepaalde tijd), Associatiebesluit 1/80 of titel 46.</li><li>Een <strong>VI-document is geen verblijfsvergunning</strong>; wachten op een besluit betekent nog niet aanvragen. Theorie leren kan wel.</li></ul>'
'<h2 id="costs">Officiële kosten 2026</h2>'
+T([['Theorie-examen (Nederlands)','€ 50,50'],['Theorie Engels','€ 57,00'],['Theorie met verlengde tijd (45 min)','€ 64,00; toeslag terug met dyslexieverklaring binnen 14 dagen'],['Theorie met tolk of individueel begeleid','€ 118,50 + tolk'],['Praktijkexamen B','€ 143,50 (rijschool betaalt het CBR, plus eigen kosten)'],['Tussentijdse toets','€ 143,50'],['Gezondheidsverklaring','€ 45,25'],['Faalangstexamen','€ 202,00'],['Rijbewijs bij de gemeente','maximaal € 53,65; spoed + € 39,65']],['Onderdeel','Tarief 2026'])
+'<p>Elke nieuwe poging kost hetzelfde tarief. De grootste kostenpost zijn de <strong>rijlessen</strong>; vergelijk rijscholen.</p>'
'<h2 id="theory">Theorie-examen: taal en voorbereiding</h2><ul><li><strong>Talen:</strong> Nederlands of Engels. Voor andere talen regel je zelf een erkende <strong>tolk</strong>, minstens 14 dagen vooraf (€ 118,50).</li><li><strong>Duur:</strong> 30 minuten, 45 met verlengde tijd; voorlezen met computerstem mogelijk.</li><li><strong>Geldigheid:</strong> <strong>18 maanden</strong>; opnieuw doen kan vanaf 3 maanden voor het verlopen.</li></ul>'
'<h2 id="steps">Van nul tot pasje</h2><ol><li><strong>Gezondheidsverklaring</strong> via Mijn CBR.</li><li><strong>Rijschool</strong> kiezen en lessen.</li><li><strong>Theorie-examen</strong> (vanaf 16).</li><li>Eventueel <strong>tussentijdse toets</strong>.</li><li><strong>Praktijkexamen</strong>, meestal gereserveerd door de rijschool (vanaf 17).</li><li><strong>Rijbewijs aanvragen</strong> bij de gemeente, vanaf de dag na het examen, met geldig ID en kleurenpasfoto. Geldig 10 jaar.</li></ol>'
'<h2 id="young">Rijden vanaf 17 (2toDrive)</h2><ul><li>Theorie vanaf 16, lessen vanaf 16,5, praktijkexamen vanaf 17.</li><li>Onder 18 alleen met een <strong>coach</strong> van minimaal 27 jaar met minstens 5 jaar een Nederlands rijbewijs (1 tot 5 coaches).</li><li>Eerst begeleiderspas bij de RDW, dan rijbewijs bij de gemeente. Beginnersrijbewijs 5 jaar.</li></ul>'
'<h2 id="moped">Bromfiets (AM)</h2><p>Theorie vanaf 15,5 jaar (€ 50,50), lessen en praktijkexamen vanaf 16 jaar (€ 149). Met een autorijbewijs heb je geen apart bromfietsrijbewijs nodig.</p>'
'<h2 id="driving-period">Tijdens het wachten</h2><ul><li>Na 185 dagen mag je niet meer rijden met een rijbewijs van buiten de EU/EVA, ook niet als de omwisseling loopt.</li><li>Neem altijd je ID mee; rijd tijdens de aanvraag liever niet naar het buitenland.</li><li>De boete voor rijden zonder geldig rijbewijs staat in de Boetebase van het OM en kan gevolgen hebben voor je verzekering. Over betalen en termijnen: zie <a href="/nl/articles/traffic-fines-cjib.html">verkeersboetes en het CJIB</a>.</li></ul>'
'<h2 id="mistakes">Veelgemaakte fouten</h2><ol><li>Na 185 dagen doorrijden met een Syrisch of Iraaks rijbewijs.</li><li>Een omwisselbaar rijbewijs laten verlopen.</li><li>Examen met tolk boeken zonder de tolk op tijd te regelen.</li><li>Theorie laten verlopen vóór het praktijkexamen.</li><li>De Gezondheidsverklaring vergeten.</li></ol>'
'<h2 id="work">Rijbewijs en werk</h2><p>Bezorgers, vrachtwagen- en buschauffeurs staan op de UWV-lijst van kansrijke beroepen (<a href="/nl/articles/trending-jobs-2026.html">kansrijke beroepen</a>). Voor C en D gelden extra examens.</p>'),
faq=[('Kan ik mijn Syrische rijbewijs omwisselen?','Nee. Syrië staat niet op de lijst en er is geen aparte regeling voor statushouders; je doet theorie- en praktijkexamen.'),
('Hoe lang mag ik met mijn buitenlandse rijbewijs rijden?','Met een rijbewijs van buiten de EU/EVA: 185 dagen na vestiging.'),
('Kan ik het theorie-examen in het Arabisch doen?','Niet direct: Nederlands of Engels, of met een erkende tolk die je zelf regelt (€ 118,50).'),
('Wat kost een rijbewijs?','CBR en gemeente samen circa € 290 (theorie, praktijk, Gezondheidsverklaring, pasje), plus rijlessen.'),
('Hoe lang is mijn theorie geldig?','18 maanden.'),
('Kan ik aanvragen als ik in het azc woon?','Niet met een VI-document; je hebt een verblijfsvergunning en 185 dagen inschrijving nodig.')],
src_note='Tarieven en regels gecontroleerd bij CBR, RDW en Rijksoverheid op 4 oktober 2026. De prijs van de Gezondheidsverklaring staat op twee CBR-pagina’s verschillend (€ 45,25 en € 46,90); controleer in Mijn CBR.')
