from a_student_finance import T
SLUG='traffic-fines-cjib'
C='https://www.cjib.nl/'
SRC=[('CJIB · Verkeersboete: hoe werken wij (stappen, aanmaningen, dwangmiddelen)',C+'over-ons/hoe-werken-wij/verkeersboete'),
('CJIB · Wat zijn de regels voor betalen in termijnen?',C+'wat-zijn-de-regels-voor-betalen-termijnen'),
('CJIB · Betalingsregeling aanvragen',C+'betalen-in-delen-aanvragen'),
('CJIB · Ik ben het niet eens met een verkeersboete',C+'ik-ben-het-niet-eens-met-een-verkeersboete'),
('CJIB · Met een brief bezwaar maken tegen uw verkeersboete',C+'ik-wil-met-een-brief-bezwaar-maken-tegen-mijn-verkeersboete'),
('Openbaar Ministerie · Veelgestelde vragen verkeersboete','https://www.om.nl/onderwerpen/v/verkeersboete/veelgestelde-vragen-verkeersboete'),
('Openbaar Ministerie · Boetebase (bedragen vanaf 1-1-2026)','https://www2.om.nl/boetebase'),
('Rijksoverheid · Hoe hoog zijn de boetes in Nederland?','https://www.rijksoverheid.nl/vraag-en-antwoord/straffen-en-maatregelen/hoe-hoog-zijn-de-boetes-in-nederland'),
('Rijksoverheid · Boete voor een verkeersovertreding','https://www.rijksoverheid.nl/vraag-en-antwoord/straffen-en-maatregelen/werkwijze-boete-verkeersovertreding')]
AR=dict(title='المخالفات المرورية وCJIB في 2026: المهل، الزيادات ×1.5 و×3، الاعتراض خلال 6 أسابيع، والتقسيط حتى 36 شهراً — مع أمثلة',
crumb='المخالفات المرورية وCJIB',
desc='دليل عميق لرسالة المخالفة المرورية من CJIB: معنى الحرف M، مهلة الدفع 8 أسابيع وتذكير مجاني لأسبوعين، الإنذار الأول ×1.5 والثاني ×3، رسوم إدارية 9 يورو، الاعتراض لدى النيابة خلال 6 أسابيع عبر Digitaal Loket Verkeer، شروط التقسيط (75 يورو فأكثر، من 3 إلى 36 شهراً)، وما يحدث إن لم تدفع، مع أمثلة محسوبة وأسئلة شائعة.',
summary='<ol><li><strong>المهلة الأولى 8 أسابيع</strong> للدفع أو لطلب التقسيط. بعدها تذكير <strong>مجاني</strong> بمهلة <strong>أسبوعين</strong>.</li><li>إن لم تدفع: <strong>الإنذار الأول = 1.5 × الغرامة</strong>، و<strong>الإنذار الثاني = 3 × الغرامة</strong>. غرامة 50 يورو تصبح 150.</li><li>CJIB يضيف <strong>9 يورو رسوماً إدارية</strong>، ومبالغ Boetebase لا تشملها.</li><li><strong>لست موافقاً؟</strong> اعترض لدى النيابة (officier van justitie) خلال <strong>6 أسابيع</strong> من تاريخ الرسالة، عبر Digitaal Loket Verkeer بـDigiD أو برسالة. لا تدفع ولا تطلب تقسيطاً أثناء الاعتراض.</li><li><strong>التقسيط</strong> ممكن إن كان المجموع <strong>75 يورو فأكثر</strong>: من 3 أشهر (حتى 120 يورو) إلى 36 شهراً (4,000 فأكثر)، ويمكن طلب تقسيط حسب دخلك.</li></ol>',
body=(
'<h2 id="letter">افهم الرسالة: الحرف في أعلى اليمين</h2>'
+T([['M','مخالفة مرورية خفيفة (قانون Mulder/Wahv). إدارية: لا سجل جنائي.'],['O','Strafbeschikking من النيابة: مخالفات أثقل، مثل تجاوز السرعة بأكثر من 30 كم/س (40 على الطريق السريع) أو القيادة تحت تأثير الكحول. هذا قانون جنائي وطريق الاعتراض مختلف (verzet).'],['E','غرامة أوروبية (من دولة أوروبية أخرى).'],['Z','أقساط التأمين الصحي غير المدفوعة.'],['S','غرامة فرضها القاضي.']],['الحرف','المعنى'])
+'<p>هذا الدليل عن الحرف <strong>M</strong>. على الرسالة: وصف المخالفة، <strong>رمز المخالفة (feitcode)</strong>، المبلغ، ورقم CJIB. المبلغ مرتبط بالـfeitcode، وتجد قيمته في <strong>Boetebase</strong> لدى النيابة (المبالغ سارية من 1 يناير 2026، ولا تشمل 9 يورو رسوماً إدارية).</p>'
'<h2 id="who">لمن تُرسل الغرامة؟</h2><ul><li>للسائق إن أوقفته الشرطة وسلّمته المخالفة.</li><li>وإلا <strong>لمالك اللوحة (kentekenhouder)</strong>، حتى لو كان شخص آخر يقود. لا يمكن تحويل غرامة M إلى اسم السائق.</li><li>أو لمن استأجر السيارة.</li><li>تُرسل المخالفة الخفيفة عادة <strong>خلال 4 أشهر</strong>، و<strong>8 أشهر</strong> للسيارة المستأجرة، وأحياناً أطول (مثلاً عند تغيير العنوان).</li><li>تاريخ الرسالة قد يكون في المستقبل عمداً، ليبدأ حساب مهلة الاعتراض منه.</li></ul>'
'<h2 id="timeline">الجدول الزمني إن لم تدفع</h2>'
+T([['1. الغرامة','8 أسابيع للدفع، أو لطلب التقسيط، أو لإضافتها إلى تقسيط قائم','المبلغ الأصلي'],['2. تذكير الدفع (betalingsherinnering)','أسبوعان إضافيان دون تكاليف','المبلغ الأصلي'],['3. الإنذار الأول (eerste aanmaning)','يمكنك ما زلت طلب التقسيط','1.5 × الغرامة'],['4. الإنذار الثاني (tweede aanmaning)','آخر إنذار قبل الإجراءات','3 × الغرامة'],['5. فحص العنوان','CJIB يتحقق من عنوانك لدى البلدية؛ بلا عنوان ثابت: سجل البحث لدى الشرطة','—'],['6. إجراءات الإلزام','حسب الحالة (الجدول التالي)','تكاليف إضافية']],['المرحلة','المهلة/الخيار','المبلغ'])
+'<p>إن اعترضت ورُفض اعتراضك، تحصل مرة أخرى على <strong>8 أسابيع</strong> للدفع، ولا يُرسل تذكير.</p>'
'<h2 id="enforce">ماذا يحدث إن لم تدفع أبداً؟</h2>'
+T([['حجب اللوحات (kentekenblokkade)','عند 5 غرامات أو أكثر غير مدفوعة وصل لها الإنذار الثاني: لا تستطيع تسجيل لوحات جديدة باسمك.'],['السحب من حسابك البنكي','حتى 500 يورو في المرة، مع رسالة «kennisgeving van verhaal».'],['المحضر القضائي (deurwaarder)','المبلغ يزيد بتكاليفه.'],['سحب رخصة القيادة','تسلّم رخصتك 4 أسابيع ولا تقود سيارة أو دراجة نارية.'],['إيقاف المركبة','الشرطة قد توقف المركبة التي تستخدمها، حتى لو كانت لغيرك.'],['الحبس الإكراهي (gijzeling)','حتى 7 أيام بإذن قاضي المقاطعة، و<strong>لا يلغي الدَّين</strong>.']],['الإجراء','التفاصيل'])
+'<p>قبل كل إجراء يرسل CJIB رسالة تشرح كيف تدفع لتتفاداه. لا تتجاهل البريد، وأبلغ عن تغيير عنوانك.</p>'
'<h2 id="examples">أمثلة محسوبة (توضيحية)</h2>'
+T([['غرامة 50 يورو، دُفعت خلال المهلة أو بعد التذكير','<strong>50</strong> يورو (+ الرسوم الإدارية 9 يورو المذكورة في الرسالة)'],['نفس الغرامة بعد الإنذار الأول','50 × 1.5 = <strong>75</strong> يورو'],['نفس الغرامة بعد الإنذار الثاني','50 × 3 = <strong>150</strong> يورو'],['غرامة 110 يورو مع إنذار ثانٍ','110 × 3 = <strong>330</strong> يورو؛ الفرق 220 يورو كان يمكن تفاديه'],['مجموع ديون CJIB 280 يورو وطلب تقسيط','بين 120 و300: حتى <strong>6 أشهر</strong> ≈ 46.67 يورو شهرياً'],['مجموع 1,500 يورو','بين 1,250 و2,000: حتى <strong>18 شهراً</strong> ≈ 83.33 يورو شهرياً'],['مجموع 60 يورو','أقل من 75: <strong>لا تقسيط</strong>؛ ادفع مرة واحدة']],['الحالة','الحساب'])
+'<p>هذه أمثلة توضيحية وليست حالات أشخاص حقيقيين. مثال الـ50 يورو مأخوذ من صفحة CJIB. المبالغ الحقيقية لكل مخالفة في Boetebase.</p>'
'<h2 id="objection">الاعتراض (in beroep gaan) خطوة بخطوة</h2><ol><li><strong>تحقق أولاً</strong>: اطلب صورة الكاميرا (flitsfoto) أو تقرير المعايرة من CJIB إن كانت مخالفة سرعة أو إشارة حمراء.</li><li><strong>خلال 6 أسابيع</strong> من تاريخ إرسال الرسالة، اعترض لدى <strong>officier van justitie</strong>:<ul><li><strong>إلكترونياً</strong> عبر <strong>Digitaal Loket Verkeer</strong> لدى النيابة، بـDigiD (لكل غرامة على حدة).</li><li><strong>أو برسالة</strong> إلى: Parket CVOM, Afdeling Mulder, Postbus 50.000, 3500 MJ Utrecht. تكتب: الاسم والعنوان والهاتف، رقم CJIB، سبب الاعتراض، التاريخ، والتوقيع، مع نسخة من الغرامة. يمكن جمع عدة غرامات في رسالة واحدة مع كل أرقام CJIB. يُفضَّل البريد المسجل.</li></ul></li><li><strong>أرفق الأدلة</strong>: عقد إيجار السيارة (حتى 3 أشهر)، أو إثبات البيع (vrijwaringsbewijs)، أو محضر سرقة لدى الشرطة.</li><li><strong>لا تدفع ولا تطلب تقسيطاً</strong> أثناء الاعتراض. إن طلبت النيابة إكمال اعتراضك، عندك <strong>4 أسابيع</strong> ولا تمديد.</li><li>تصلك بالبريد <strong>إفادة استلام</strong> بعد بضعة أسابيع. إن وصلك إنذار رغم اعتراضك في الوقت، يسقط تلقائياً.</li><li><strong>إن رُفض</strong>: تستطيع الطعن لدى <strong>قاضي المقاطعة (kantonrechter)</strong>، لكن يجب أولاً <strong>دفع الغرامة</strong> كضمان (zekerheidstelling). المهلة والعنوان في قرار النيابة. بعدها يمكن الاستئناف لدى محكمة الاستئناف .</li><li><strong>إن ربحت</strong> يعيد CJIB المبلغ المدفوع (كلياً أو جزئياً).</li></ol>'
'<h2 id="plan">التقسيط (betalingsregeling)</h2><p><strong>الشروط:</strong> المجموع <strong>75 يورو أو أكثر</strong> (تُحسب الزيادات ولا تُحسب الرسوم الإدارية)، وأنك التزمت بأي تقسيط سابق خلال آخر 6 أشهر.</p>'
+T([['حتى 120 يورو','3'],['120 – 300','6'],['300 – 450','9'],['450 – 1,250','12'],['1,250 – 2,000','18'],['2,000 – 3,000','24'],['3,000 – 4,000','30'],['4,000 فأكثر','36']],['المبلغ المفتوح عند الطلب','عدد الأشهر الأقصى'])
+'<ul><li><strong>لا يُضاف للتقسيط</strong> ما هو بالفعل عند المحضر، أو يُقتطع من راتبك أو إعانتك، أو عليه إجراء إلزام، أو عليه اعتراض.</li><li><strong>القسط مرتفع؟</strong> اطلب <strong>تقسيطاً مخصصاً (maatwerk)</strong> مع إثباتات الدخل والمصاريف.</li><li><strong>تسجلت في مساعدة الديون</strong> لدى البلدية؟ اسأل CJIB عن <strong>تأجيل الدفع (Uitstel van Betaling)</strong>. انظر <a href="/articles/debt-help-schuldhulp.html">مساعدة الديون المجانية</a>.</li><li>أبلغ عن أي تغيير دائم في دخلك. يمكنك رؤية الاتفاق عبر DigiD في البوابة الرقمية لـCJIB.</li></ul>'
'<h2 id="steps">ماذا تفعل اليوم عندما تصلك رسالة CJIB</h2><ol><li>انظر إلى <strong>الحرف</strong> (M أو O أو غيره) و<strong>تاريخ الرسالة</strong>.</li><li>هل المخالفة صحيحة؟ إن كنت تشك، اطلب الصورة واعترض خلال 6 أسابيع.</li><li>صحيحة؟ <strong>ادفع خلال 8 أسابيع</strong> مع رقم الدفع الصحيح المذكور في الرسالة.</li><li>لا تستطيع؟ اطلب <strong>التقسيط فوراً</strong>، قبل الإنذار الأول إن أمكن.</li><li>احتفظ بنسخة وصور من كل شيء، وراقب بريدك.</li></ol>'
'<h2 id="mistakes">أخطاء شائعة</h2><ol><li><strong>ترك الرسالة دون فتح</strong> حتى تتضاعف ثلاث مرات.</li><li><strong>الاعتراض متأخراً</strong>: المهلة من تاريخ الرسالة، لا من يوم قراءتها.</li><li><strong>دفع الغرامة وطلب التقسيط مع الاعتراض</strong>؛ هذا يعقّد الأمر.</li><li><strong>إقراض السيارة</strong> دون أن تعرف أنك أنت مالك اللوحة المسؤول عن غرامات M.</li><li><strong>عدم تحديث العنوان</strong> بعد الانتقال؛ الغرامات تُرسل للعنوان القديم وتكبر.</li><li><strong>تصديق رسائل مزيفة</strong>: CJIB لا يطلب الدفع عبر رابط واتساب أو SMS. تحقق في الموقع الرسمي بالدخول بنفسك.</li></ol>'
'<h2 id="related">أدلة مرتبطة</h2><ul><li><a href="/articles/foreign-driving-license-exchange.html">تبديل رخصة القيادة الأجنبية</a></li><li><a href="/articles/cbr-driving-license-netherlands.html">رخصة القيادة وCBR</a></li><li><a href="/articles/debt-help-schuldhulp.html">مساعدة الديون المجانية من البلدية</a></li><li><a href="/articles/digid-registration-guide.html">DigiD</a></li><li><a href="/articles/change-address-netherlands.html">تغيير العنوان</a></li></ul>'),
faq=[('كم مهلة دفع المخالفة؟','8 أسابيع، ثم تذكير مجاني بأسبوعين إضافيين.'),
('كم تزيد الغرامة إن تأخرت؟','الإنذار الأول 1.5 مرة الغرامة، والثاني 3 مرات. 50 يورو تصبح 75 ثم 150.'),
('كيف أعترض على مخالفة؟','لدى النيابة خلال 6 أسابيع من تاريخ الرسالة، عبر Digitaal Loket Verkeer بـDigiD أو برسالة إلى Parket CVOM في أوترخت. لا تدفع أثناء الاعتراض.'),
('هل أستطيع التقسيط؟','نعم إن كان المجموع 75 يورو أو أكثر: من 3 أشهر حتى 36 شهراً حسب المبلغ، أو تقسيط حسب دخلك.'),
('صديقي كان يقود سيارتي، هل يمكن تحويل الغرامة لاسمه؟','لا، غرامة M تبقى على مالك اللوحة إن لم تُوقِف الشرطة السائق.'),
('هل تظهر المخالفة المرورية في سجلي الجنائي؟','مخالفات M الخفيفة لا تُسجَّل جنائياً. أما strafbeschikking (حرف O) فهي جنائية.')],
src_note='راجعنا CJIB والنيابة العامة (OM) وRijksoverheid في 7 أكتوبر 2026. لم نذكر مبالغ مخالفات بعينها (السرعة، الهاتف…) لأنها تختلف حسب feitcode؛ ابحث عنها في Boetebase. مهلة الطعن لدى قاضي المقاطعة مذكورة في قرار النيابة. الأمثلة توضيحية.')
NL=dict(title='Verkeersboetes en het CJIB in 2026: termijnen, verhogingen ×1,5 en ×3, beroep binnen 6 weken en betalen in termijnen tot 36 maanden — met voorbeelden',
crumb='Verkeersboetes en CJIB',
desc='Uitgebreide gids over de CJIB-verkeersboete: de letter M, 8 weken betaaltermijn en gratis herinnering van 2 weken, eerste aanmaning ×1,5 en tweede ×3, € 9 administratiekosten, beroep bij de officier van justitie binnen 6 weken via het Digitaal Loket Verkeer, betalingsregeling (vanaf € 75, 3 tot 36 maanden) en dwangmiddelen, met rekenvoorbeelden en FAQ.',
summary='<ol><li><strong>8 weken</strong> om te betalen of een regeling af te spreken; daarna een <strong>gratis</strong> herinnering met <strong>2 weken</strong> extra.</li><li>Niet betaald: <strong>eerste aanmaning = 1,5 × de boete</strong>, <strong>tweede = 3 ×</strong>. € 50 wordt € 150.</li><li>Het CJIB rekent <strong>€ 9 administratiekosten</strong>; Boetebase-bedragen zijn exclusief.</li><li><strong>Niet eens?</strong> Beroep bij de officier van justitie binnen <strong>6 weken</strong> na verzenddatum, via het Digitaal Loket Verkeer (DigiD) of per brief. Niet betalen en geen regeling aanvragen tijdens beroep.</li><li><strong>Betalingsregeling</strong> vanaf <strong>€ 75</strong>: 3 maanden (tot € 120) tot 36 maanden (€ 4.000+), of maatwerk.</li></ol>',
body=(
'<h2 id="letter">De letter rechtsboven</h2>'
+T([['M','Lichte verkeersovertreding (Wet Mulder/Wahv). Administratief: geen strafblad.'],['O','OM-strafbeschikking: zwaardere feiten, zoals meer dan 30 km/u te hard (40 op de snelweg) of rijden onder invloed. Strafrecht; bezwaar heet verzet.'],['E','Europese boete.'],['Z','Premies zorgverzekering.'],['S','Boete van de rechter.']],['Letter','Betekenis'])
+'<p>Deze gids gaat over <strong>M</strong>. Op de beschikking staan de overtreding, de <strong>feitcode</strong>, het bedrag en het CJIB-nummer. Bedragen per feitcode vind je in de <strong>Boetebase</strong> van het OM (geldend vanaf 1 januari 2026, exclusief € 9 administratiekosten).</p>'
'<h2 id="who">Wie krijgt de boete?</h2><ul><li>De bestuurder bij een staandehouding.</li><li>Anders de <strong>kentekenhouder</strong>, ook als iemand anders reed; een Mulderbeschikking kan niet op naam van een andere bestuurder.</li><li>Of de huurder van het voertuig.</li><li>Lichte overtredingen worden meestal <strong>binnen 4 maanden</strong> verstuurd, bij huurvoertuigen <strong>8 maanden</strong>; soms later (bijv. na verhuizing).</li><li>De dagtekening ligt soms in de toekomst, zodat je de volledige beroepstermijn hebt.</li></ul>'
'<h2 id="timeline">Tijdlijn bij niet betalen</h2>'
+T([['1. Verkeersboete','8 weken betalen, regeling afspreken of toevoegen','Boetebedrag'],['2. Betalingsherinnering','2 weken extra, zonder kosten','Boetebedrag'],['3. Eerste aanmaning','Regeling aanvragen kan nog','1,5 × boete'],['4. Tweede aanmaning','Laatste aanmaning','3 × boete'],['5. Adrescontrole','Check bij de gemeente; geen vast adres: opsporingsregister','—'],['6. Dwangmiddelen','Zie hieronder','Extra kosten']],['Stap','Termijn/optie','Bedrag'])
+'<p>Na een afgewezen beroep heb je opnieuw <strong>8 weken</strong> om te betalen; er komt dan geen herinnering.</p>'
'<h2 id="enforce">Dwangmiddelen</h2>'
+T([['Kentekenblokkade','Bij 5 of meer onbetaalde boetes met tweede aanmaning: geen nieuwe kentekens op je naam.'],['Verhaal op bankrekening','Maximaal € 500 per keer; brief ‘kennisgeving van verhaal’.'],['Deurwaarder','Bedrag stijgt met deurwaarderskosten.'],['Inneming rijbewijs','4 weken inleveren, niet rijden met auto of motor.'],['Buitengebruikstelling voertuig','Politie kan het voertuig dat je gebruikt stilzetten, ook van een ander.'],['Gijzeling','Maximaal 7 dagen met machtiging van de kantonrechter; de boete blijft verschuldigd.']],['Middel','Uitleg'])
+'<h2 id="examples">Rekenvoorbeelden (illustratief)</h2>'
+T([['Boete € 50, betaald binnen termijn of na herinnering','<strong>€ 50</strong> (+ € 9 administratiekosten zoals vermeld)'],['Na eerste aanmaning','€ 50 × 1,5 = <strong>€ 75</strong>'],['Na tweede aanmaning','€ 50 × 3 = <strong>€ 150</strong>'],['Boete € 110 met tweede aanmaning','€ 110 × 3 = <strong>€ 330</strong>; € 220 was te voorkomen'],['Totaal € 280 en regeling','€ 120–300: max. <strong>6 maanden</strong> ≈ € 46,67 p/m'],['Totaal € 1.500','€ 1.250–2.000: max. <strong>18 maanden</strong> ≈ € 83,33 p/m'],['Totaal € 60','Onder € 75: <strong>geen regeling</strong>']],['Situatie','Berekening'])
+'<p>Illustratieve voorbeelden, geen echte personen. Het € 50-voorbeeld komt van de CJIB-site.</p>'
'<h2 id="objection">In beroep gaan, stap voor stap</h2><ol><li><strong>Controleer</strong>: vraag de flitsfoto of het ijkrapport op bij het CJIB.</li><li><strong>Binnen 6 weken</strong> na verzenddatum beroep bij de <strong>officier van justitie</strong>:<ul><li>online via het <strong>Digitaal Loket Verkeer</strong> met DigiD (per beschikking);</li><li>of per brief aan Parket CVOM, Afdeling Mulder, Postbus 50.000, 3500 MJ Utrecht, met naam, adres, telefoon, CJIB-nummer, reden, datum, handtekening en kopie van de boete. Meerdere boetes in één brief mag, met alle CJIB-nummers. Liefst aangetekend.</li></ul></li><li><strong>Bewijs</strong>: huurovereenkomst (max. 3 maanden verhuurd), vrijwaringsbewijs bij verkoop, of aangifte bij diefstal.</li><li><strong>Niet betalen en geen regeling</strong> tijdens beroep. Vraagt de officier om aanvulling: <strong>4 weken</strong>, geen verlenging.</li><li>Ontvangstbevestiging per post na enkele weken. Een aanmaning na tijdig beroep vervalt vanzelf.</li><li><strong>Afgewezen?</strong> Beroep bij de <strong>kantonrechter</strong>; eerst <strong>zekerheid stellen</strong> door te betalen. Termijn en adres staan in de beslissing. Daarna eventueel het gerechtshof.</li><li><strong>Gelijk gekregen?</strong> Het CJIB betaalt (deels) terug.</li></ol>'
'<h2 id="plan">Betalingsregeling</h2><p><strong>Voorwaarden:</strong> in totaal <strong>€ 75 of meer</strong> (verhogingen tellen mee, administratiekosten niet), en een eerdere regeling in de afgelopen 6 maanden nagekomen.</p>'
+T([['tot € 120','3'],['€ 120 – € 300','6'],['€ 300 – € 450','9'],['€ 450 – € 1.250','12'],['€ 1.250 – € 2.000','18'],['€ 2.000 – € 3.000','24'],['€ 3.000 – € 4.000','30'],['€ 4.000 of hoger','36']],['Openstaand bedrag bij aanvraag','Max. maanden'])
+'<ul><li><strong>Niet in de regeling</strong>: bedragen bij de deurwaarder, met loon- of uitkeringsbeslag, met een lopend dwangmiddel, of in beroep/verzet.</li><li><strong>Maandbedrag te hoog?</strong> Vraag <strong>maatwerk</strong> aan met bewijsstukken.</li><li><strong>Bij schuldhulp aangemeld?</strong> Vraag naar <strong>Uitstel van Betaling</strong>. Zie <a href="/nl/articles/debt-help-schuldhulp.html">Gratis schuldhulp</a>.</li><li>Geef blijvende inkomenswijzigingen door. Bekijk je regeling met DigiD in het digitaal loket van het CJIB.</li></ul>'
'<h2 id="steps">Brief ontvangen? Zo pak je het aan</h2><ol><li>Kijk naar de <strong>letter</strong> en de <strong>datum</strong>.</li><li>Twijfel? Foto opvragen en binnen 6 weken beroep.</li><li>Klopt het? <strong>Betaal binnen 8 weken</strong> met het juiste betalingskenmerk.</li><li>Lukt dat niet? <strong>Direct een regeling</strong> aanvragen, liefst vóór de eerste aanmaning.</li><li>Bewaar kopieën en houd je post in de gaten.</li></ol>'
'<h2 id="mistakes">Veelgemaakte fouten</h2><ol><li>De brief laten liggen tot het bedrag verdrievoudigd is.</li><li>Te laat in beroep: de termijn loopt vanaf de verzenddatum.</li><li>Betalen of een regeling aanvragen terwijl je in beroep gaat.</li><li>Je auto uitlenen zonder te beseffen dat jij als kentekenhouder de M-boete krijgt.</li><li>Adreswijziging niet doorgeven.</li><li>Betalen via een link in WhatsApp of sms: ga altijd zelf naar de officiële CJIB-site.</li></ol>'
'<h2 id="related">Gerelateerde gidsen</h2><ul><li><a href="/nl/articles/foreign-driving-license-exchange.html">Buitenlands rijbewijs omwisselen</a></li><li><a href="/nl/articles/cbr-driving-license-netherlands.html">Rijbewijs halen bij het CBR</a></li><li><a href="/nl/articles/debt-help-schuldhulp.html">Gratis schuldhulp</a></li><li><a href="/nl/articles/digid-registration-guide.html">DigiD aanvragen</a></li><li><a href="/nl/articles/change-address-netherlands.html">Adres wijzigen</a></li></ul>'),
faq=[('Hoe lang heb ik om een verkeersboete te betalen?','8 weken, daarna een gratis herinnering met 2 weken extra.'),
('Hoeveel hoger wordt de boete bij te laat betalen?','Eerste aanmaning 1,5 keer, tweede aanmaning 3 keer de boete.'),
('Hoe ga ik in beroep?','Binnen 6 weken bij de officier van justitie via het Digitaal Loket Verkeer (DigiD) of per brief aan Parket CVOM. Tijdens beroep hoef je niet te betalen.'),
('Kan ik in termijnen betalen?','Ja, vanaf € 75 in totaal: 3 tot 36 maanden afhankelijk van het bedrag, of maatwerk.'),
('Iemand anders reed in mijn auto. Kan de boete op zijn naam?','Nee, een Mulderbeschikking blijft bij de kentekenhouder als de bestuurder niet is staande gehouden.'),
('Krijg ik een strafblad van een verkeersboete?','Niet van een lichte Mulderboete (M). Een strafbeschikking (O) is wel strafrecht.')],
src_note='Gecontroleerd bij het CJIB, het Openbaar Ministerie en Rijksoverheid op 7 oktober 2026. Geen bedragen per overtreding genoemd: die hangen af van de feitcode (zie Boetebase). De termijn voor de kantonrechter staat in de beslissing van de officier. Voorbeelden illustratief.')
