from a_student_finance import T
SLUG='employment-contracts-labor-law-2026'
SRC=[('Rijksoverheid · Hoelang duurt mijn proeftijd?','https://www.rijksoverheid.nl/vraag-en-antwoord/arbeidsovereenkomst-en-cao/hoelang-duurt-een-proeftijd'),
('Rijksoverheid · Wanneer gaat mijn tijdelijke contract over in een vast contract?','https://www.rijksoverheid.nl/vraag-en-antwoord/arbeidsovereenkomst-en-cao/wanneer-verandert-mijn-tijdelijke-arbeidscontract-in-een-vast-contract'),
('Rijksoverheid · Wat is een aanzegtermijn?','https://www.rijksoverheid.nl/vraag-en-antwoord/arbeidsovereenkomst-en-cao/wat-is-een-aanzegtermijn'),
('Rijksoverheid · Opzegtermijn werkgever','https://www.rijksoverheid.nl/vraag-en-antwoord/ontslag/ontslagen-worden-opzegtermijn-werkgever'),
('Rijksoverheid · Hoe hoog is de transitievergoeding?','https://www.rijksoverheid.nl/vraag-en-antwoord/ontslag/hoe-hoog-is-de-transitievergoeding-als-ik-word-ontslagen'),
('Rijksoverheid · Hoeveel loon krijg ik doorbetaald als ik ziek ben?','https://www.rijksoverheid.nl/vraag-en-antwoord/ziekteverzuim-van-het-werk/hoeveel-loon-krijg-ik-doorbetaald-als-ik-ziek-ben'),
('Rijksoverheid · Hoe lang krijg ik loon doorbetaald als ik ziek ben?','https://www.rijksoverheid.nl/vraag-en-antwoord/ziekteverzuim-van-het-werk/hoe-lang-krijg-ik-loon-doorbetaald-als-ik-ziek-ben'),
('Rijksoverheid · Hoe hoog is mijn vakantiegeld?','https://www.rijksoverheid.nl/vraag-en-antwoord/vakantiedagen-en-vakantiegeld/hoe-hoog-is-mijn-vakantiegeld'),
('Rijksoverheid · Meer zekerheid voor mensen met een flexcontract (7-7-2026)','https://www.rijksoverheid.nl/actueel/nieuws/2026/07/08/meer-zekerheid-voor-mensen-met-een-flexcontract')]

AR=dict(title='عقد العمل في هولندا 2026: فترة التجربة، العقد المؤقت والدائم، الإنذار، الفصل، والمرض — دليل شامل قبل التوقيع',
crumb='عقد العمل',
desc='دليل عميق لعقد العمل في هولندا: مدة فترة التجربة، متى يتحول العقد المؤقت إلى دائم، مهلة إبلاغك بعدم التجديد، مهل الإنهاء، تعويض الفصل (حتى 102,000 يورو في 2026)، الأجر أثناء المرض، الإجازات، وما يتغير في 2028.',
summary='<ol><li><strong>اقرأ نوع العقد أولاً:</strong> مؤقت (bepaalde tijd)، دائم (onbepaalde tijd)، استدعاء (oproep)، أو عبر وكالة توظيف. لكل نوع حقوق مختلفة.</li><li><strong>فترة التجربة</strong> لا تجوز في عقد 6 أشهر أو أقل، وحدها الأقصى شهر أو شهران حسب نوع العقد.</li><li><strong>العقد المؤقت يصبح دائماً</strong> بعد أكثر من 3 عقود مؤقتة، أو أكثر من 3 سنوات متتالية، إن لم يفصل بينها أكثر من 6 أشهر، ما لم ينص الـCAO على غير ذلك.</li><li><strong>عند انتهاء العقد أو الفصل</strong> تستحق غالباً <strong>transitievergoeding</strong>: ثلث راتب شهري عن كل سنة خدمة، من اليوم الأول.</li><li><strong>في المرض:</strong> يدفع صاحب العمل حتى سنتين، 70% على الأقل، ولا يقل في السنة الأولى عن الحد الأدنى للأجر.</li><li><strong>من 1 يناير 2028</strong> يدخل قانون جديد للعقود المرنة حيز التنفيذ (تفاصيل في القسم الأخير).</li></ol>',
body=(
'<h2 id="types">أنواع العقود: اعرف ما الذي توقّع عليه</h2>'
+T([['عقد مؤقت (bepaalde tijd)','له تاريخ انتهاء. ينتهي تلقائياً، لكن يلزم صاحب العمل إبلاغك مسبقاً بالتجديد أو عدمه (انظر «مهلة الإبلاغ»).'],
    ['عقد دائم (onbepaalde tijd)','بلا تاريخ انتهاء. لا ينتهي إلا بالاتفاق أو الاستقالة أو فصل بإجراء قانوني.'],
    ['عقد استدعاء (oproepcontract)','لا ساعات ثابتة: عقد إطاري، أو صفر ساعات، أو min-max. له قواعد خاصة (<a href="/articles/zero-hours-contract.html">دليل عقود الاستدعاء</a>).'],
    ['عبر وكالة توظيف (uitzend)','عقدك مع الوكالة، وعملك عند شركة أخرى (<a href="/articles/temporary-agency-work-rights.html">دليل العمل عبر Uitzendbureau</a>).'],
    ['عقد تدريب BBL','عقد عمل مرتبط بدراسة MBO، وله استثناءات (<a href="/articles/bol-bbl-comparison.html">BOL أم BBL</a>).']],
   ['النوع','ماذا يعني لك'])
+'<p><strong>الـCAO مهم جداً:</strong> كثير من القطاعات لها اتفاقية عمل جماعية (cao) قد تغيّر القواعد العامة في هذا الدليل (فترة التجربة، سلسلة العقود، الأيام غير المدفوعة في المرض…). اسأل دائماً: «أي cao ينطبق على عقدي؟» واطلب نسخة منه.</p>'
'<h2 id="proeftijd">فترة التجربة (proeftijd)</h2><p>خلالها يمكن لك ولصاحب العمل إنهاء العقد فوراً، دون مهلة إنذار، ودون أن يبحث صاحب العمل عن وظيفة بديلة لك داخل الشركة. لذلك يجب أن تعرف حدّها القانوني:</p>'
+T([['عقد مؤقت 6 أشهر أو أقل','<strong>ممنوع</strong> وضع فترة تجربة'],
    ['عقد مؤقت أكثر من 6 أشهر وأقل من سنتين','حد أقصى <strong>شهر واحد</strong>'],
    ['عقد مؤقت بلا تاريخ نهاية محدد','حد أقصى <strong>شهر واحد</strong>'],
    ['عقد مؤقت سنتان أو أكثر','حد أقصى <strong>شهران</strong>'],
    ['عقد دائم','حد أقصى <strong>شهران</strong>']],['العقد','فترة التجربة'])
+'<ul><li>يجب أن تكون فترة التجربة <strong>مكتوبة</strong>. قد يسمح الـCAO بقواعد مختلفة في العقود المؤقتة.</li><li>في العقد التالي مع نفس صاحب العمل لنفس العمل، لا يجوز عادةً وضع فترة تجربة جديدة، إلا في حالات تسمح بها القواعد (مثل عمل مختلف يحتاج مهارات أخرى).</li><li>مثال: عقد 6 أشهر فيه «proeftijd 1 maand» ← هذا البند <strong>باطل</strong> قانوناً.</li></ul>'
'<h2 id="chain">متى يصبح العقد المؤقت دائماً؟ (ketenbepaling)</h2><p>يتحول عقدك تلقائياً إلى دائم إذا:</p><ul><li>حصلت على <strong>أكثر من 3 عقود مؤقتة</strong> عند نفس صاحب العمل؛ أو</li><li>عملت <strong>أكثر من 3 سنوات</strong> متتالية بعقود مؤقتة عنده؛ أو</li><li>عند «أصحاب عمل متتابعين» لنفس العمل، مثل أن تعمل عبر وكالة توظيف ثم توظفك الشركة مباشرة.</li></ul><p><strong>الشرط:</strong> ألا يفصل بين العقود أكثر من <strong>6 أشهر</strong> (أو 3 أشهر للعمل الموسمي المتكرر حتى 9 أشهر في السنة إن نص الـCAO). وقواعد الـCAO تتقدّم على القاعدة العامة.</p>'
+T([['عقد 1 (12 شهراً) ← عقد 2 (12 شهراً) ← عقد 3 (12 شهراً)','3 عقود، 36 شهراً: ما زالت ضمن الحد. العقد الرابع، أو تجاوز 3 سنوات، يجعله دائماً.'],
    ['عقد 1 (6 أشهر) ← انقطاع 7 أشهر ← عقد جديد','الانقطاع أكثر من 6 أشهر يبدأ العد من جديد (حسب القاعدة الحالية).'],
    ['عبر وكالة سنة، ثم مباشرة عند الشركة نفسها لنفس العمل','قد يُحسب كسلسلة واحدة (opvolgend werkgeverschap). اسأل Juridisch Loket.']],['الحالة','النتيجة'])
+'<p><strong>استثناءات</strong> من هذه القاعدة: عقد BBL، من هم دون 18 ويعملون حتى 12 ساعة أسبوعياً في المتوسط، بعض المعلمين البدلاء، وقطاعات بعقود مؤقتة فقط (مثل الرياضة الاحترافية)، وما ينص عليه الـCAO.</p>'
'<h2 id="aanzeg">مهلة الإبلاغ بعدم التجديد (aanzegtermijn)</h2><p>في العقد المؤقت (عادةً لمدة 6 أشهر أو أكثر) يجب على صاحب العمل أن يخبرك <strong>كتابياً قبل شهر على الأقل</strong> من نهاية العقد: هل سيجدده أم لا، وبأي شروط إن جدّد.</p><ul><li>إن تأخر أو لم يخبرك: تستحق تعويضاً بقدر التأخير. مثال رسمي: تأخر أسبوع ← تعويض أسبوع من الراتب.</li><li>إن كُتب في العقد منذ البداية أنه لن يكون هناك عقد تالٍ، فهذا يتعامل مع المسألة بشكل مختلف؛ اقرأ البند.</li><li>نصيحة: احتفظ بالرسالة أو البريد الإلكتروني الذي يبلغك بالقرار، وبتاريخه.</li></ul>'
'<h2 id="opzeg">مهل الإنهاء (opzegtermijn)</h2><p><strong>أنت كعامل:</strong> القاعدة العامة شهر واحد (إن لم يُتفق على غير ذلك). وإن نص العقد على مهلة أطول لك، فيجب أن تكون مهلة صاحب العمل <strong>ضعفها</strong>.</p><p><strong>صاحب العمل في العقد الدائم</strong> (بعد إذن UWV أو المحكمة عادةً):</p>'
+T([['أقل من 5 سنوات','شهر واحد'],['5 إلى 10 سنوات','شهران'],['10 إلى 15 سنة','3 أشهر'],['15 سنة أو أكثر','4 أشهر']],['مدة الخدمة','مهلة صاحب العمل'])
+'<ul><li>في فترة التجربة: لا مهلة للطرفين.</li><li>الفصل الفوري (ontslag op staande voet) لسبب عاجل خطير: لا مهلة. إن حدث، اطلب السبب كتابياً واطلب استشارة قانونية فوراً، فالمهل للاعتراض قصيرة.</li><li>لا توقّع على «اتفاق إنهاء بالتراضي» (vaststellingsovereenkomst) قبل أن تفهم أثره على إعانة البطالة WW وعلى التعويض. خذ وقتك واستشر.</li></ul>'
'<h2 id="transitie">تعويض الفصل (transitievergoeding)</h2><p>إذا فصلك صاحب العمل، أو <strong>لم يجدد عقدك المؤقت بمبادرة منه</strong>، تستحق غالباً تعويضاً من <strong>اليوم الأول</strong> للخدمة:</p><ul><li><strong>ثلث راتب شهري إجمالي</strong> عن كل سنة خدمة كاملة؛</li><li>وجزء نسبي عن الباقي (حسب معادلة رسمية)؛</li><li>الحد الأقصى في 2026: <strong>102,000 يورو إجمالي</strong>، أو راتب سنة كاملة إن كان أعلى.</li></ul>'
+T([['3,000 × 3 سنوات','3 × (3,000 ÷ 3) = <strong>3,000 يورو</strong> + جزء الأشهر الإضافية'],
    ['2,400 × سنة واحدة','2,400 ÷ 3 = <strong>800 يورو</strong>'],
    ['مثال رسمي: 9 سنوات و5 أيام براتب 3,000','9 × 1,000 = 9,000 + 22.22 عن الأيام الخمسة = <strong>9,022.22 يورو</strong>']],['الراتب الشهري × المدة','التعويض التقريبي'])
+'<ul><li>يُدفع خلال شهر من انتهاء العقد، غالباً مع آخر راتب. إن لم يُدفع: يمكنك اللجوء للمحكمة خلال <strong>3 أشهر</strong> من انتهاء الخدمة، ويستحق عليه فائدة قانونية بعد شهر.</li><li>التعويض يخضع للضريبة، وقد يؤثر على البدلات (<a href="/articles/toeslagen-income-update.html">حدّث دخلك في Toeslagen</a>).</li></ul>'
'<h2 id="sick">المرض: كم تتقاضى ولمدة كم؟</h2><ul><li>يدفع صاحب العمل أجرك <strong>حتى سنتين (104 أسابيع)</strong>.</li><li><strong>السنة الأولى:</strong> 70% على الأقل من أجرك، ولا يقل عن <strong>الحد الأدنى للأجر</strong> الذي ينطبق عليك (<a href="/articles/minimum-wage-netherlands.html">الحد الأدنى</a>). كثير من الـCAO تدفع 100% في السنة الأولى.</li><li><strong>السنة الثانية:</strong> 70% على الأقل، بدون ضمان الحد الأدنى.</li><li><strong>أيام الانتظار:</strong> قد لا يُدفع اليوم الأول أو اليومان الأولان، فقط إن نص العقد أو الـCAO. إن مرضت مجدداً خلال 4 أسابيع فلا أيام انتظار، وتُحسب الفترتان فترة واحدة.</li><li>بعد سنتين: قد تستحق إعانة WIA عبر UWV.</li><li>إن انتهى عقدك المؤقت وأنت مريض: يبلغ صاحب العمل UWV، وقد تستحق إعانة Ziektewet.</li></ul>'
'<h2 id="leave">الإجازات وبدل العطلة</h2><ul><li><strong>الإجازة القانونية:</strong> 4 أضعاف ساعات عملك الأسبوعية سنوياً. مثال: 40 ساعة أسبوعياً ← 160 ساعة (20 يوماً).</li><li><strong>بدل العطلة (vakantiegeld):</strong> 8% على الأقل من الأجر الإجمالي السنوي. إن نص الـCAO على غير ذلك، فلا يقل عن 8% من الحد الأدنى للأجر.</li><li>في أيام الإجازة يُدفع لك 100% حتى لو كنت تتقاضى 70% بسبب المرض.</li></ul>'
'<h2 id="checklist">قائمة الأسئلة قبل التوقيع (اطبعها)</h2><ol><li>ما نوع العقد؟ ومتى ينتهي؟</li><li>هل فيه فترة تجربة؟ وهل مدتها قانونية حسب الجدول؟</li><li>كم ساعة أسبوعياً؟ وهل الساعات ثابتة أم «حسب الحاجة»؟</li><li>كم الأجر الإجمالي بالساعة أو بالشهر؟ وهل يتجاوز الحد الأدنى لعمري؟</li><li>أي CAO ينطبق؟</li><li>هل بدل العطلة 8% داخل الراتب أم يُدفع منفصلاً؟</li><li>هل هناك أيام انتظار في المرض؟</li><li>هل يوجد بند منع المنافسة (concurrentiebeding)؟ في العقد المؤقت يجب أن يكون معلَّلاً.</li><li>هل هناك تقاعد (pensioen) ويُخصم منه جزء؟</li><li>بدل السفر والعمل الإضافي والعطل الرسمية؟</li><li>كم مهلة الإنذار لي؟</li><li>أين يُكتب الجدول ومتى يصلني؟</li></ol>'
'<h2 id="mistakes">أخطاء شائعة</h2><ul><li><strong>التوقيع على نص لا تفهمه.</strong> لك الحق في أخذ العقد وقراءته أو ترجمته قبل التوقيع.</li><li><strong>قبول فترة تجربة في عقد 6 أشهر.</strong> البند باطل.</li><li><strong>عدم عدّ العقود المؤقتة.</strong> سجّل تواريخ كل عقد.</li><li><strong>الاستقالة شفهياً في نزاع</strong> قد يكلّفك WW والتعويض.</li><li><strong>الخلط بين الصافي والإجمالي</strong> عند مقارنة الراتب (<a href="/articles/dutch-payslip-explained.html">قسيمة الراتب</a>).</li></ul>'
'<h2 id="2028">ما الذي سيتغير؟ قانون «مزيد من الأمان للعاملين بعقود مرنة»</h2><p>وافق مجلس الشيوخ في <strong>7 يوليو 2026</strong> على قانون Wet meer zekerheid flexwerkers، ويبدأ تطبيقه <strong>1 يناير 2028</strong>. أهم ما أعلنته الحكومة:</p><ul><li><strong>بعد 3 عقود مؤقتة</strong> لا يجوز عقد مؤقت جديد بين نفس الطرفين لمدة <strong>3 سنوات</strong> (الآن 6 أشهر فقط). الهدف: إيقاف حيلة «الباب الدوار».</li><li><strong>عقود صفر ساعات</strong> تُستبدل بعقد «النطاق» (bandbreedtecontract).</li><li><strong>عمال الوكالات</strong> يحصلون على شروط عمل مساوية على الأقل لشروط الموظفين الدائمين، وتُقصَّر المراحل الأقل أماناً من سنة ونصف إلى سنة.</li></ul><p>حتى ذلك التاريخ تبقى القواعد الحالية في هذا الدليل سارية. سنحدّث الدليل عند صدور التفاصيل التطبيقية.</p>'),
faq=[('كم مدة فترة التجربة القصوى؟','شهر في العقد المؤقت الأطول من 6 أشهر والأقصر من سنتين، وشهران في العقد الدائم أو المؤقت لسنتين أو أكثر. ولا تجوز في عقد 6 أشهر أو أقل.'),
('متى يصبح عقدي المؤقت دائماً؟','بعد أكثر من 3 عقود مؤقتة أو أكثر من 3 سنوات متتالية عند نفس صاحب العمل، إن لم يفصل بينها أكثر من 6 أشهر، ما لم ينص الـCAO على غير ذلك.'),
('هل أستحق تعويضاً إن لم يُجدَّد عقدي المؤقت؟','نعم غالباً، إن كان عدم التجديد بمبادرة صاحب العمل: ثلث راتب شهري عن كل سنة، من اليوم الأول.'),
('كم يدفع صاحب العمل إن مرضت؟','حتى سنتين: 70% على الأقل، وفي السنة الأولى لا يقل عن الحد الأدنى للأجر.'),
('ما مهلة الإنذار إن أردت الاستقالة؟','شهر واحد عادةً، ما لم يُتفق كتابياً على غير ذلك.'),
('هل تغيّر قانون العقود المرنة؟','أُقرّ قانون جديد في 7 يوليو 2026 ويُطبق من 1 يناير 2028. حتى ذلك الحين تبقى القواعد الحالية.')],
src_note='راجعنا كل الأرقام والقواعد في صفحات Rijksoverheid في 4 أكتوبر 2026. القواعد العامة قد تختلف بحسب الـCAO الخاص بقطاعك. هذا دليل توعوي وليس استشارة قانونية؛ في النزاع اتصل بـJuridisch Loket.')

NL=dict(title='Arbeidscontract in Nederland 2026: proeftijd, tijdelijk en vast, aanzegtermijn, ontslag en ziekte — complete gids vóór je tekent',
crumb='Arbeidscontract',
desc='Uitgebreide gids over je arbeidscontract: maximale proeftijd, wanneer tijdelijk vast wordt, aanzegtermijn, opzegtermijnen, transitievergoeding (max € 102.000 in 2026), loon bij ziekte, vakantie en wat er in 2028 verandert.',
summary='<ol><li><strong>Check eerst het soort contract:</strong> bepaalde tijd, onbepaalde tijd, oproep of uitzend. Elk heeft eigen rechten.</li><li><strong>Proeftijd</strong> mag niet bij een contract van 6 maanden of korter, en is maximaal 1 of 2 maanden.</li><li><strong>Tijdelijk wordt vast</strong> na meer dan 3 tijdelijke contracten of meer dan 3 jaar, met tussenpozen van maximaal 6 maanden, tenzij de cao anders bepaalt.</li><li><strong>Bij ontslag of niet verlengen</strong> door de werkgever: meestal een <strong>transitievergoeding</strong> van 1/3 maandsalaris per dienstjaar, vanaf dag 1.</li><li><strong>Ziek:</strong> maximaal 2 jaar loondoorbetaling, minimaal 70%, in het 1e jaar minimaal het minimumloon.</li><li><strong>Per 1 januari 2028</strong> geldt de Wet meer zekerheid flexwerkers (zie het laatste deel).</li></ol>',
body=(
'<h2 id="types">Soorten contracten</h2>'
+T([['Bepaalde tijd','Heeft een einddatum; de werkgever moet wel tijdig laten weten of je verder kunt (aanzegtermijn).'],
    ['Onbepaalde tijd','Geen einddatum; eindigt alleen met wederzijds goedvinden, opzegging door jou of ontslag via de juiste procedure.'],
    ['Oproepcontract','Geen vaste uren: voorovereenkomst, nuluren of min-max (<a href="/nl/articles/zero-hours-contract.html">gids oproepcontracten</a>).'],
    ['Uitzendcontract','Contract met het uitzendbureau, werk bij een inlener (<a href="/nl/articles/temporary-agency-work-rights.html">gids uitzendwerk</a>).'],
    ['Bbl-leerwerkovereenkomst','Gekoppeld aan een mbo-opleiding, met uitzonderingen (<a href="/nl/articles/bol-bbl-comparison.html">bol of bbl</a>).']],['Soort','Wat het voor jou betekent'])
+'<p><strong>De cao is belangrijk:</strong> veel sectoren hebben een cao die de algemene regels in deze gids kan aanpassen. Vraag altijd welke cao op jouw contract van toepassing is.</p>'
'<h2 id="proeftijd">Proeftijd</h2><p>Tijdens de proeftijd kunnen jij en je werkgever direct opzeggen, zonder opzegtermijn en zonder herplaatsingsplicht.</p>'
+T([['Tijdelijk ≤ 6 maanden','<strong>Geen</strong> proeftijd toegestaan'],['Tijdelijk > 6 maanden en < 2 jaar','Maximaal <strong>1 maand</strong>'],['Tijdelijk zonder einddatum','Maximaal <strong>1 maand</strong>'],['Tijdelijk ≥ 2 jaar','Maximaal <strong>2 maanden</strong>'],['Vast','Maximaal <strong>2 maanden</strong>']],['Contract','Proeftijd'])
+'<ul><li>De proeftijd moet <strong>schriftelijk</strong> zijn vastgelegd. Een cao kan bij tijdelijke contracten andere regels hebben.</li><li>Voorbeeld: contract van 6 maanden met "proeftijd 1 maand" ← dat beding is <strong>nietig</strong>.</li></ul>'
'<h2 id="chain">Wanneer wordt tijdelijk vast? (ketenbepaling)</h2><ul><li>Meer dan <strong>3 tijdelijke contracten</strong> bij dezelfde werkgever; of</li><li>langer dan <strong>3 jaar</strong> achter elkaar tijdelijke contracten; of</li><li>bij opvolgende werkgevers voor hetzelfde werk, bijvoorbeeld eerst via een uitzendbureau en daarna direct bij het bedrijf.</li></ul><p>Voorwaarde: maximaal <strong>6 maanden</strong> tussen de contracten (bij seizoenswerk tot 9 maanden per jaar kan de cao 3 maanden bepalen). De cao gaat voor.</p>'
+T([['12 + 12 + 12 maanden','3 contracten, 36 maanden: nog binnen de grens. Een 4e contract of langer dan 3 jaar maakt het vast.'],['6 maanden, 7 maanden pauze, nieuw contract','De keten begint opnieuw (huidige regel).'],['1 jaar via uitzendbureau, daarna direct bij hetzelfde bedrijf','Kan als één keten tellen (opvolgend werkgeverschap). Vraag het Juridisch Loket.']],['Situatie','Gevolg'])
+'<p><strong>Uitzonderingen:</strong> bbl-leerwerkovereenkomst, jonger dan 18 met gemiddeld maximaal 12 uur per week, bepaalde invalleerkrachten, sectoren met alleen tijdelijke contracten, en afwijkende cao-afspraken.</p>'
'<h2 id="aanzeg">Aanzegtermijn</h2><p>Bij een tijdelijk contract (doorgaans van 6 maanden of langer) moet je werkgever je <strong>uiterlijk 1 maand vóór het einde schriftelijk</strong> laten weten of het contract wordt voortgezet en onder welke voorwaarden.</p><ul><li>Te laat of niet gemeld: je krijgt een vergoeding naar rato. Officieel voorbeeld: een week te laat ← een weeksalaris.</li><li>Bewaar de brief of e-mail met datum.</li></ul>'
'<h2 id="opzeg">Opzegtermijnen</h2><p><strong>Jij als werknemer:</strong> in principe 1 maand. Is voor jou een langere termijn afgesproken, dan moet die van de werkgever <strong>twee keer zo lang</strong> zijn.</p>'
+T([['Korter dan 5 jaar','1 maand'],['5 tot 10 jaar','2 maanden'],['10 tot 15 jaar','3 maanden'],['15 jaar of langer','4 maanden']],['In dienst','Opzegtermijn werkgever'])
+'<ul><li>In de proeftijd: geen opzegtermijn.</li><li>Ontslag op staande voet: geen opzegtermijn; vraag de reden schriftelijk en zoek direct juridisch advies.</li><li>Teken geen vaststellingsovereenkomst voordat je de gevolgen voor WW en vergoeding begrijpt.</li></ul>'
'<h2 id="transitie">Transitievergoeding</h2><p>Bij ontslag of als de werkgever je tijdelijke contract <strong>niet verlengt</strong>, heb je meestal recht op een vergoeding vanaf <strong>dag 1</strong>:</p><ul><li><strong>1/3 bruto maandsalaris</strong> per heel dienstjaar;</li><li>plus een deel over de resterende periode (officiële formule);</li><li>maximum 2026: <strong>€ 102.000 bruto</strong>, of één jaarsalaris als dat hoger is.</li></ul>'
+T([['€ 3.000 × 3 jaar','3 × € 1.000 = <strong>€ 3.000</strong> + deel over de resterende maanden'],['€ 2.400 × 1 jaar','<strong>€ 800</strong>'],['Officieel voorbeeld: 9 jaar en 5 dagen, € 3.000','€ 9.000 + € 22,22 = <strong>€ 9.022,22</strong>']],['Maandsalaris × duur','Vergoeding (indicatief)'])
+'<ul><li>Uitbetaling binnen 1 maand na het einde, vaak met het laatste salaris. Niet betaald? Binnen <strong>3 maanden</strong> naar de rechter; vanaf 1 maand is wettelijke rente verschuldigd.</li><li>De vergoeding is belast en kan je toeslagen beïnvloeden (<a href="/nl/articles/toeslagen-income-update.html">inkomen wijzigen</a>).</li></ul>'
'<h2 id="sick">Ziek: hoeveel en hoe lang?</h2><ul><li>Loondoorbetaling tot <strong>2 jaar (104 weken)</strong>.</li><li><strong>1e jaar:</strong> minimaal 70%, en minimaal het voor jou geldende <a href="/nl/articles/minimum-wage-netherlands.html">minimumloon</a>. Veel cao-s betalen 100%.</li><li><strong>2e jaar:</strong> minimaal 70%, zonder aanvulling tot minimumloon.</li><li><strong>Wachtdagen:</strong> 1 of 2 onbetaalde dagen alleen als dat in contract of cao staat; binnen 4 weken opnieuw ziek: geen wachtdagen en de periodes tellen samen.</li><li>Na 2 jaar: mogelijk WIA via UWV. Eindigt je tijdelijke contract tijdens ziekte: mogelijk Ziektewet.</li></ul>'
'<h2 id="leave">Vakantie en vakantiegeld</h2><ul><li><strong>Wettelijke vakantie:</strong> 4 keer je wekelijkse uren per jaar (40 uur ← 160 uur).</li><li><strong>Vakantiegeld:</strong> minimaal 8% van je brutojaarsalaris; als de cao anders bepaalt, minimaal 8% van het minimumloon.</li><li>Tijdens vakantiedagen krijg je 100%, ook als je wegens ziekte 70% krijgt.</li></ul>'
'<h2 id="checklist">Checklist vóór je tekent</h2><ol><li>Soort contract en einddatum?</li><li>Proeftijd en is die wettelijk toegestaan?</li><li>Aantal uren: vast of oproep?</li><li>Brutoloon per uur/maand, en boven het minimumloon voor je leeftijd?</li><li>Welke cao?</li><li>Vakantiegeld apart of in het loon?</li><li>Wachtdagen bij ziekte?</li><li>Concurrentiebeding (bij tijdelijk contract moet het gemotiveerd zijn)?</li><li>Pensioen en eigen bijdrage?</li><li>Reiskosten, overwerk, feestdagen?</li><li>Jouw opzegtermijn?</li><li>Hoe en wanneer krijg je je rooster?</li></ol>'
'<h2 id="mistakes">Veelgemaakte fouten</h2><ul><li>Tekenen zonder te begrijpen; je mag het contract eerst meenemen en laten vertalen.</li><li>Proeftijd accepteren bij een contract van 6 maanden: nietig.</li><li>Contracten niet tellen: noteer alle data.</li><li>Mondeling ontslag nemen tijdens een conflict.</li><li>Bruto en netto verwarren (<a href="/nl/articles/dutch-payslip-explained.html">loonstrook</a>).</li></ul>'
'<h2 id="2028">Wat verandert er? Wet meer zekerheid flexwerkers</h2><p>De Eerste Kamer stemde op <strong>7 juli 2026</strong> in; invoering per <strong>1 januari 2028</strong>. Volgens de overheid:</p><ul><li>Na <strong>3 tijdelijke contracten</strong> mag er <strong>3 jaar</strong> geen tijdelijk contract meer tussen dezelfde partijen komen (nu 6 maanden).</li><li><strong>Nulurencontracten</strong> worden vervangen door een <strong>bandbreedtecontract</strong>.</li><li><strong>Uitzendkrachten</strong> krijgen minimaal gelijkwaardige arbeidsvoorwaarden; de meest onzekere fases worden verkort van anderhalf jaar naar 1 jaar.</li></ul><p>Tot die datum gelden de huidige regels uit deze gids.</p>'),
faq=[('Hoe lang mag een proeftijd duren?','1 maand bij tijdelijk > 6 maanden en < 2 jaar; 2 maanden bij vast of tijdelijk ≥ 2 jaar; niet bij contracten van 6 maanden of korter.'),
('Wanneer wordt mijn tijdelijke contract vast?','Na meer dan 3 tijdelijke contracten of meer dan 3 jaar bij dezelfde werkgever, met tussenpozen van maximaal 6 maanden, tenzij de cao anders bepaalt.'),
('Krijg ik een vergoeding als mijn contract niet wordt verlengd?','Meestal wel, als de werkgever niet verlengt: 1/3 maandsalaris per dienstjaar, vanaf dag 1.'),
('Hoeveel loon krijg ik bij ziekte?','Tot 2 jaar minimaal 70%; in het 1e jaar minimaal het minimumloon.'),
('Wat is mijn opzegtermijn als ik zelf stop?','In principe 1 maand, tenzij schriftelijk anders afgesproken.'),
('Verandert de wet voor flexwerkers?','Ja, per 1 januari 2028. Tot dan gelden de huidige regels.')],
src_note='Alle regels en bedragen gecontroleerd op Rijksoverheid op 4 oktober 2026. Je cao kan afwijken. Dit is algemene informatie, geen juridisch advies; neem bij een conflict contact op met het Juridisch Loket.')
