from a_student_finance import T
SLUG='energy-contracts-saving-2026'
A='https://consument.acm.nl/elektriciteit-en-gas/'
R='https://www.rijksoverheid.nl/'
SRC=[('ACM ConsuWijzer · Tips bij het kiezen van een energieleverancier',A+'overstappen-vergelijken-en-verhuizen/tips-bij-het-kiezen-van-een-energieleverancier'),
('ACM ConsuWijzer · Energiecontract opzeggen: opzegvergoeding en opzegtermijn',A+'overstappen-vergelijken-en-verhuizen/energiecontract-opzeggen-alles-over-opzegvergoeding-en-opzegtermijn'),
('ACM ConsuWijzer · Energiecontract bij verhuizen',A+'overstappen-vergelijken-en-verhuizen/energiecontract-bij-verhuizen'),
('ACM ConsuWijzer · Termijnbedrag',A+'wat-betaal-ik-voor-mijn-energie/termijnbedrag'),
('ACM ConsuWijzer · Ik kan mijn energierekening niet betalen',A+'ik-heb-een-probleem/kan-energierekening-niet-betalen'),
('ACM ConsuWijzer · Teruglevering van elektriciteit',A+'duurzame-energie/teruglevering-van-elektriciteit'),
('Rijksoverheid · Opbouw energierekening',R+'vraag-en-antwoord/energie-thuis/opbouw-energierekening'),
('Rijksoverheid · Salderingsregeling',R+'themas/klimaat-milieu-en-natuur/energie-thuis/salderingsregeling'),
('Rijksoverheid · Noodfonds Energie gaat open (29-9-2026)',R+'actueel/nieuws/2026/09/29/noodfonds-energie-gaat-open'),
('Rijksoverheid · Ondersteuning bij een hoge energierekening',R+'vraag-en-antwoord/koopkracht/hoe-krijg-ik-ondersteuning-bij-een-hoge-energierekening'),
('Rijksoverheid · Kan mijn energieleverancier afsluiten als ik niet betaal?',R+'vraag-en-antwoord/energie-thuis/kan-mijn-energieleverancier-de-levering-van-energie-afsluiten-als-ik-niet-betaal'),
('Rijksoverheid · Servicekosten en gas, water en elektriciteit',R+'vraag-en-antwoord/woning-huren/waarom-betaal-ik-servicekosten-en-kosten-voor-gas-water-en-elektriciteit'),
('Milieu Centraal · Gas en stroom besparen voor huurders','https://www.milieucentraal.nl/energie-besparen/duurzaam-verwarmen-en-koelen/gas-en-stroom-besparen-voor-huurders/')]

AR=dict(title='عقد الكهرباء والغاز في هولندا 2026–2027: ثابت أم متغير أم ديناميكي، غرامة الإلغاء، ضريبة الطاقة، نهاية المقاصة، والمساعدة إن لم تستطع الدفع',
crumb='عقد الطاقة والتوفير',
seo_title='عقد الكهرباء والغاز energiecontract 2026',
desc='عقد الكهرباء والغاز في هولندا: ثابت أم متغير أم ديناميكي، غرامة الإلغاء قد تكون 0 يورو، نهاية المقاصة في 1 يناير 2027، وصندوق الطاقة حتى 1,800 يورو.',
summary='<ol><li><strong>ثلاثة أنواع عقود:</strong> ثابت (سعر ثابت لمدة محددة)، متغير (الشركة تغيّر السعر عادة في 1 يناير و1 يوليو)، ديناميكي (سعر يتغير كل ساعة أو يوم ويحتاج عداداً ذكياً).</li><li><strong>مهلة الإلغاء</strong> شهر واحد كحد أقصى لكل العقود. <strong>غرامة الإلغاء المبكر</strong> فقط في العقد الثابت قبل نهايته، وتساوي خسارة الشركة الفعلية؛ إن ارتفعت الأسعار أو بقيت كما هي فالغرامة <strong>0 يورو</strong>.</li><li><strong>الانتقال لمنزل جديد لا يلغي الغرامة</strong>؛ لكن يمكنك نقل العقد معك.</li><li><strong>من 1 يناير 2027 تنتهي المقاصة</strong> لأصحاب الألواح الشمسية: افحص عقدك.</li><li><strong>صندوق طوارئ الطاقة:</strong> الطلبات من <strong>4 يناير حتى 7 مايو 2027</strong>، والدعم من 120 حتى 1,800 يورو.</li><li><strong>لا تستطيع الدفع؟</strong> قبل أي قطع يجب 3 تذكيرات وعرض تقسيط وإبلاغ البلدية لمساعدة الديون.</li></ol>',
body=(
'<h2 id="types">أنواع العقود: أيها يناسبك؟</h2>'
+T([['ثابت (vast)','السعر ثابت طوال المدة (مثلاً سنة أو ثلاث).','تعرف فاتورتك مسبقاً.','غالباً أغلى؛ غرامة إن ألغيت مبكراً. بعد انتهاء المدة يتحول إلى سعر متغير.'],
    ['متغير (variabel)','الشركة تعدّل السعر، غالباً في 1 يناير و1 يوليو، وتبلغك قبل 30 يوماً على الأقل.','لا غرامة إلغاء؛ مرونة.','قد ترتفع الأسعار فجأة.'],
    ['ديناميكي (dynamisch)','سعر الكهرباء يتغير كل ربع ساعة أو ساعة أو يوم، والغاز يومياً. تعرف الأسعار قبل يوم.','رخيص إن نقلت الاستهلاك لأوقات السعر المنخفض.','يحتاج عداداً ذكياً ومتابعة؛ مخاطرة في أيام الذروة.']],
   ['النوع','كيف يعمل','الميزة','العيب'])
+'<p><strong>قاعدة عملية:</strong> إن كانت ميزانيتك ضيقة وتحتاج رقماً ثابتاً كل شهر فالثابت أريح نفسياً؛ إن أردت المرونة دون التزام فالمتغير؛ والديناميكي لمن يستطيع تشغيل الغسالة والشحن في الساعات الرخيصة.</p>'
'<h2 id="cancel">الإلغاء وغرامة الإلغاء المبكر (opzegvergoeding)</h2><ul><li><strong>مهلة الإلغاء:</strong> مكتوبة في العقد، وحدها الأقصى <strong>شهر واحد</strong> تبدأ من اليوم التالي للإلغاء، لكل أنواع العقود.</li><li><strong>متى تدفع غرامة؟</strong> فقط إن اجتمعت ثلاثة أمور: عقد لمدة محددة (ثابت)، لم تنته المدة بعد، والغرامة وطريقة حسابها مكتوبتان في العقد.</li><li><strong>كيف تُحسب؟</strong> (الاستهلاك المتبقي حتى نهاية العقد) × (سعرك الحالي − سعر الشركة الجديد لعقد بنفس المدة المتبقية). ليس لها حد أدنى أو أقصى ثابت، ولا تتجاوز خسارة الشركة. <strong>إن ارتفعت الأسعار أو بقيت كما هي فالغرامة 0.</strong></li><li>هذه القواعد للعقود الثابتة المبرمة من <strong>1 يونيو 2023</strong>؛ العقود الأقدم تبقى على القواعد القديمة.</li><li><strong>لا غرامة:</strong> بعد انتهاء المدة، في العقد المتغير أو الديناميكي، إن أنهت الشركة العقد، أو إن لم تُذكر طريقة الحساب في العقد.</li><li><strong>اسأل قبل أن تبدّل:</strong> يجب أن تخبرك الشركة الحالية بقيمة الغرامة خلال أيام، والحساب صالح شهرين.</li><li><strong>مكافأة الترحيب:</strong> يمكن مطالبتك بردها فقط إن ألغيت خلال 6 أشهر، وليس أكثر من قيمتها.</li></ul>'
'<h2 id="move">الانتقال لمنزل آخر</h2><p>حسب ACM: <strong>الانتقال، أو الهجرة، أو السكن مع شريك ليست استثناء</strong> من الغرامة. لكن يمكنك <strong>نقل العقد</strong> إلى عنوانك الجديد (وحتى على عنوانين مؤقتاً). أبلغ الشركة قبل الانتقال بأسبوعين على الأقل، وسجّل قراءات العداد يوم التسليم والاستلام بصورة.</p>'
'<h2 id="bill">من أين تتكوّن فاتورتك؟ ضريبة الطاقة 2026</h2>'
+T([['ضريبة الطاقة على الكهرباء','9.161 سنت/كيلوواط ساعة (نحو 11.1 سنت مع الضريبة) حتى 10,000 كيلوواط ساعة','8.80 سنت (مقترح)'],
    ['ضريبة الطاقة على الغاز','60.066 سنت/م³ (نحو 73 سنت مع الضريبة)','61.63 سنت (مقترح)'],
    ['خصم ضريبة الطاقة لكل اتصال سنوياً','519.80 يورو، أي <strong>629 يورو مع الضريبة</strong>','519.58 يورو (مقترح)']],
   ['البند','2026 (بدون ضريبة القيمة المضافة ما لم يُذكر)','2027'])
+'<ul><li>الفاتورة = سعر التوريد (من شركتك) + تكاليف الشبكة (من مدير الشبكة) + ضريبة الطاقة − الخصم السنوي + ضريبة القيمة المضافة 21%.</li><li>تقدّر الحكومة متوسط فاتورة الأسرة في 2026 بنحو <strong>2,089 يورو</strong> سنوياً (900 م³ غاز و1,870 كيلوواط ساعة).</li><li>أرقام 2027 مقترحة في خطة الضرائب، وتصبح نهائية بعد تصويت البرلمان (<a href="/articles/prinsjesdag-2026-changes.html">تغييرات 2027</a>). تكاليف الشبكة لـ2027 تحددها ACM في ديسمبر.</li></ul>'
'<h2 id="solar">الألواح الشمسية: نهاية المقاصة في 1 يناير 2027</h2><ul><li>القانون نافذ: حتى <strong>31 ديسمبر 2026</strong> تُخصم الكهرباء التي تردّها للشبكة من استهلاكك (salderen). من <strong>1 يناير 2027</strong> لا مقاصة.</li><li>بدلاً منها تحصل على <strong>تعويض عن الإرجاع</strong>، وحتى 2030 لا يقل عن <strong>50% من سعر التوريد الصافي</strong> (بدون ضرائب).</li><li><strong>تكاليف الإرجاع (terugleverkosten)</strong> مسموحة فقط بقدر تكاليف الشركة الفعلية، وACM تراقب ذلك.</li><li>الكهرباء التي تستهلكها مباشرة من ألواحك لا ضريبة عليها؛ فاستعمل الأجهزة في ساعات الشمس.</li><li>إن كان عقدك الثابت يمتد بعد 1 يناير 2027 فاقرأ ما يقوله عن المقاصة، وضعه على <a href="/articles/year-end-checklist-2026.html">قائمة نهاية السنة 2026</a>.</li></ul>'
'<h2 id="advance">الدفعة الشهرية (termijnbedrag) والفاتورة السنوية</h2><ul><li>الدفعة الشهرية <strong>تقدير</strong>: تكاليف السنة المتوقعة ÷ 12. يمكنك تعديلها بنفسك في التطبيق أو الموقع، لكن الدفعة المنخفضة جداً تعني فاتورة سنوية كبيرة.</li><li>تستطيع الشركة رفع الدفعة لسبب وجيه (أسعار أعلى في العقد المتغير أو استهلاك أكبر)، دون إشعار 30 يوماً (الإشعار مطلوب لتغيير السعر فقط).</li><li>الشكوى: يجب أن تقرر الشركة خلال <strong>8 أسابيع</strong>.</li><li>بعد التبديل تصل الفاتورة الختامية خلال <strong>6 أسابيع</strong>.</li><li>المطالبة المتأخرة يجب أن تصل خلال <strong>سنتين</strong>، وإلا تسقط.</li></ul>'
'<h2 id="switch">قائمة التبديل الآمن (حسب ACM)</h2><ol><li>خذ آخر فاتورة سنوية واعرف استهلاكك بالكيلوواط ساعة والمتر المكعب.</li><li>في العقد الثابت: اسأل شركتك الحالية عن غرامة الإلغاء أولاً.</li><li>قارن في أكثر من موقع مقارنة، وانظر للتكاليف الثابتة والخصومات وتكاليف الإرجاع، لا للسعر الأول فقط.</li><li><strong>لا توقّع عقداً أثناء مكالمة بيع هاتفية.</strong></li><li>سجّل فقط عند الشركة الجديدة، وهي تتولى التبديل.</li><li>لديك <strong>14 يوماً</strong> للتراجع عن أي عقد جديد.</li></ol>'
'<h2 id="cantpay">لا تستطيع دفع الفاتورة؟</h2><p><strong>قبل أي قطع</strong> يجب على الشركة: إرسال <strong>3 تذكيرات</strong> على الأقل بمهلة 14 يوماً لكل منها، وعرض <strong>خطة تقسيط</strong>، ثم مشاركة بياناتك مع البلدية لتعرض عليك مساعدة الديون.</p><p><strong>لا يجوز القطع</strong> إن: التزمت بخطة تقسيط، أو قدّمت شكوى مكتوبة عن الفاتورة، أو سجّلت في مساعدة الديون (حتى القرار)، أو كان القطع خطراً جدياً على الصحة (بإفادة طبيب غير طبيبك).</p><p><strong>البرد:</strong> لا يوجد «منع قطع شتوي» عام في القانون؛ مديرو الشبكات اتفقوا على عدم القطع بين 1 أكتوبر و1 أبريل عند الصقيع الشديد (يومان متتاليان بمتوسط تحت الصفر).</p>'
'<h2 id="noodfonds">صندوق طوارئ الطاقة 2026–2027</h2>'
+T([['التحضير والتواصل','من 1 ديسمبر 2026'],['الطلبات','من <strong>4 يناير حتى 7 مايو 2027</strong>'],['من يستحق','دخل إجمالي حتى 130% من الحد الاجتماعي وفاتورة طاقة ≥ 8% من الدخل، أو 130–200% وفاتورة ≥ 10%'],['ماذا يدفع','نصف التكاليف فوق تلك النسبة؛ من <strong>120 حتى 1,800 يورو</strong>، غالباً عبر شركتك على 12 شهراً'],['قواعد أخرى','لا «من يسبق يحصل»؛ يشمل التدفئة الجماعية والطلاب وشبكات الحرارة؛ طلب ورقي ممكن؛ أول دفعة بعد 4–6 أسابيع تقريباً']],['البند','التفاصيل'])
+'<p>لا يوجد «بدل طاقة» وطني بعد الآن، لكن البلديات حصلت على مال إضافي ويمكن أن تساعد محلياً (مساعدة خاصة أو بدل طاقة محلي)، ومستشار طاقة يقدم نصائح وأدوات عزل صغيرة مجاناً. ابحث في energiehulpvinden.nl. وللشروط وأمثلة الحساب راجع <a href="/articles/energy-emergency-fund-2027.html">دليل صندوق طوارئ الطاقة 2027</a>.</p>'
'<h2 id="renters">للمستأجرين</h2><ul><li>تدفع «تكاليف خدمات» للطاقة فقط إن كانت الطاقة عبر المالك. يجب أن يصلك كشف سنوي حتى <strong>1 يوليو</strong>؛ إن لم يصل أو كان خاطئاً فتوجه لنقطة البلاغ في البلدية أو Huurcommissie.</li><li>من <strong>1 يناير 2027</strong>: حد أقصى 8 أنواع من تكاليف الخدمات للعقود الجديدة.</li><li><strong>شهادة الطاقة (energielabel)</strong> تؤثر في نقاط المنزل وبالتالي في الحد الأقصى للإيجار؛ يمكنك طلب فحصها من Huurcommissie.</li><li>إن كان دخلك منخفضاً: <a href="/articles/housing-rent-allowance-2026.html">بدل الإيجار</a> و<a href="/articles/municipal-taxes-exemption-kwijtschelding.html">إعفاء ضرائب البلدية</a>.</li></ul>'
'<h2 id="tips">نصائح توفير بأرقام (Milieu Centraal)</h2><p>محسوبة بسعر 1.37 يورو/م³ غاز و0.21 يورو/كيلوواط ساعة؛ توفيرك الفعلي يختلف حسب منزلك وسعرك:</p>'
+T([['خفض التدفئة درجة واحدة','نحو 170 يورو/سنة'],['تدفئة منخفضة في الليل (15°) وأثناء الغياب','نحو 120 يورو/سنة'],['إغلاق الستائر مساءً','نحو 45 يورو/سنة'],['تجفيف الغسيل على حبل بدل المجفف','نحو 50 يورو/سنة'],['رقائق عاكسة خلف المشعاع','نحو 40 يورو/سنة'],['رأس دش موفر للماء','نحو 25 يورو/سنة'],['إلغاء ثلاجة ثانية','نحو 35 يورو/سنة'],['غسالة الصحون على وضع eco','نحو 15 يورو/سنة']],['الإجراء','التوفير التقريبي'])
+'<h2 id="mistakes">أخطاء شائعة</h2><ol><li>التوقيع أثناء مكالمة بيع أو على الباب دون مقارنة.</li><li>الظن أن الانتقال يلغي غرامة العقد الثابت.</li><li>خفض الدفعة الشهرية كثيراً ثم صدمة الفاتورة السنوية.</li><li>تجاهل التذكيرات بدل طلب التقسيط فوراً.</li><li>أصحاب الألواح: عدم فحص العقد قبل 1 يناير 2027.</li></ol>'),
faq=[('ما الفرق بين العقد الثابت والمتغير؟','في الثابت السعر لا يتغير طوال المدة لكن قد تدفع غرامة إن ألغيت مبكراً. في المتغير تعدّل الشركة السعر (غالباً مرتين سنوياً) ولا غرامة إلغاء.'),
('كم غرامة إلغاء العقد الثابت؟','تساوي خسارة الشركة الفعلية: الاستهلاك المتبقي × الفرق بين سعرك والسعر الجديد. إن لم تنخفض الأسعار فقد تكون 0 يورو.'),
('أنتقل لمنزل جديد، هل أدفع غرامة؟','الانتقال ليس استثناء، لكن يمكنك نقل عقدك إلى عنوانك الجديد. أبلغ قبل أسبوعين على الأقل.'),
('ماذا يتغير لأصحاب الألواح الشمسية؟','من 1 يناير 2027 تنتهي المقاصة؛ تحصل على تعويض عن الكهرباء المرتجعة لا يقل حتى 2030 عن 50% من سعر التوريد الصافي.'),
('متى أطلب دعم صندوق الطاقة؟','من 4 يناير حتى 7 مايو 2027، والتحضير من 1 ديسمبر 2026. الدعم بين 120 و1,800 يورو.'),
('هل يمكن قطع الكهرباء عني في الشتاء؟','لا يوجد منع عام، لكن قبل أي قطع يجب 3 تذكيرات وعرض تقسيط وإحالة لمساعدة الديون. ومديرو الشبكات لا يقطعون أثناء الصقيع الشديد.')],
src_note='راجعنا القواعد في ACM ConsuWijzer وRijksoverheid في 4 أكتوبر 2026، ونصائح التوفير من Milieu Centraal (مؤسسة معلومات مستقلة ممولة حكومياً). أرقام 2027 مقترحة حتى يقرها البرلمان.')

NL=dict(title='Energiecontract 2026–2027: vast, variabel of dynamisch, opzegvergoeding, energiebelasting, einde salderen en hulp als je niet kunt betalen',
crumb='Energiecontract en besparen',
seo_title='Energiecontract 2026–2027: vast of variabel',
desc='Energiecontract kiezen: vast, variabel of dynamisch. Opzegvergoeding vaak € 0, einde salderen op 1 januari 2027 en Noodfonds Energie tot € 1.800.',
summary='<ol><li><strong>Drie contracten:</strong> vast (vaste prijs voor een looptijd), variabel (leverancier past prijs aan, vaak 1 januari en 1 juli), dynamisch (prijs per uur of dag, slimme meter nodig).</li><li><strong>Opzegtermijn</strong> maximaal 1 maand. <strong>Opzegvergoeding</strong> alleen bij vast contract vóór het einde, gelijk aan het werkelijke verlies van de leverancier; stijgen of blijven prijzen gelijk, dan <strong>€ 0</strong>.</li><li><strong>Verhuizen is geen uitzondering</strong>, maar je kunt je contract meenemen.</li><li><strong>Salderen stopt op 1 januari 2027.</strong></li><li><strong>Noodfonds Energie:</strong> aanvragen van <strong>4 januari tot en met 7 mei 2027</strong>, € 120 tot € 1.800.</li><li><strong>Kun je niet betalen?</strong> Vóór afsluiting: 3 herinneringen, een betalingsregeling en melding bij de gemeente voor schuldhulp.</li></ol>',
body=(
'<h2 id="types">Soorten contracten</h2>'
+T([['Vast','Prijs vast voor de looptijd (bijv. 1 of 3 jaar).','Je weet wat je betaalt.','Vaak duurder; opzegvergoeding bij vroeg opzeggen. Na afloop variabel tarief.'],['Variabel','Leverancier past tarief aan, vaak 1 januari en 1 juli, minstens 30 dagen vooraf gemeld.','Geen opzegvergoeding.','Prijzen kunnen stijgen.'],['Dynamisch','Stroomprijs per kwartier, uur of dag; gas per dag; prijzen 1 dag vooraf bekend.','Goedkoop als je verbruik verschuift.','Slimme meter nodig; risico bij piekprijzen.']],['Type','Werking','Voordeel','Nadeel'])
+'<h2 id="cancel">Opzeggen en opzegvergoeding</h2><ul><li><strong>Opzegtermijn:</strong> staat in het contract, maximaal <strong>1 maand</strong>, vanaf de dag na opzegging. Geldt voor alle contracten.</li><li><strong>Wanneer een vergoeding?</strong> Alleen als alle drie kloppen: contract voor bepaalde tijd, looptijd nog niet voorbij, en beide staan in het contract.</li><li><strong>Berekening:</strong> (resterend verbruik tot einde contract) × (jouw tarief − nieuw tarief van dezelfde leverancier voor de resterende looptijd). Geen vast minimum of maximum, nooit meer dan het verlies van de leverancier. <strong>Stijgen of blijven prijzen gelijk, dan € 0.</strong></li><li>Geldt voor vaste contracten afgesloten vanaf <strong>1 juni 2023</strong>; oudere contracten vallen onder de oude regels.</li><li><strong>Geen vergoeding:</strong> na afloop van de looptijd, bij variabel of dynamisch, als de leverancier opzegt, of als de berekening niet in het contract staat.</li><li><strong>Vraag eerst:</strong> je oude leverancier moet de hoogte binnen enkele dagen melden; de berekening is 2 maanden geldig.</li><li><strong>Welkomstpremie:</strong> terugbetalen mag alleen bij opzeggen binnen 6 maanden en nooit meer dan de premie.</li></ul>'
'<h2 id="move">Verhuizen</h2><p>Volgens de ACM zijn <strong>verhuizen, emigreren en samenwonen geen uitzondering</strong> op de opzegvergoeding. Je kunt het contract wel <strong>meenemen</strong> naar je nieuwe adres (tijdelijk zelfs op 2 adressen). Meld de verhuizing uiterlijk 2 weken vooraf en maak foto’s van de meterstanden.</p>'
'<h2 id="bill">Opbouw van je rekening en energiebelasting</h2>'
+T([['Energiebelasting stroom','9,161 ct/kWh (ca. 11,1 ct incl. btw) tot 10.000 kWh','8,80 ct (voorstel)'],['Energiebelasting gas','60,066 ct/m³ (ca. 73 ct incl. btw)','61,63 ct (voorstel)'],['Vermindering energiebelasting per aansluiting','€ 519,80, <strong>€ 629 incl. btw</strong>','€ 519,58 (voorstel)']],['Onderdeel','2026 (excl. btw tenzij vermeld)','2027'])
+'<ul><li>Rekening = leveringskosten + netbeheerkosten + energiebelasting − vermindering + 21% btw.</li><li>Gemiddeld huishouden 2026 volgens de Rijksoverheid: circa <strong>€ 2.089 per jaar</strong> (900 m³ gas, 1.870 kWh).</li><li>Tarieven 2027 zijn voorstellen uit het Belastingplan (<a href="/nl/articles/prinsjesdag-2026-changes.html">Prinsjesdag 2026</a>); de nettarieven 2027 stelt de ACM in december vast.</li></ul>'
'<h2 id="solar">Zonnepanelen: einde salderen op 1 januari 2027</h2><ul><li>Wettelijk vastgelegd: tot en met <strong>31 december 2026</strong> kun je salderen, vanaf <strong>1 januari 2027</strong> niet meer.</li><li>Je krijgt een <strong>terugleververgoeding</strong>; tot 2030 minimaal <strong>50% van het kale leveringstarief</strong>.</li><li><strong>Terugleverkosten</strong> mogen alleen de werkelijke kosten van de leverancier zijn; de ACM houdt toezicht.</li><li>Direct zelf verbruikte stroom is onbelast: verschuif verbruik naar zonuren.</li><li>Loopt je vaste contract over de jaargrens? Lees wat er over salderen in staat en zet het op je <a href="/nl/articles/year-end-checklist-2026.html">checklist jaareinde 2026</a>.</li></ul>'
'<h2 id="advance">Termijnbedrag en jaarafrekening</h2><ul><li>Het termijnbedrag is een <strong>voorschot</strong> (verwachte jaarkosten ÷ 12). Je kunt het zelf aanpassen; te laag betekent een hoge bijbetaling.</li><li>De leverancier mag het verhogen bij een goede reden, zonder 30 dagen vooraf (dat geldt alleen voor tariefwijzigingen).</li><li>Klacht: beslissing binnen <strong>8 weken</strong>.</li><li>Eindafrekening na overstappen binnen <strong>6 weken</strong>.</li><li>Naheffing moet binnen <strong>2 jaar</strong>, anders verjaard.</li></ul>'
'<h2 id="switch">Veilig overstappen (ACM)</h2><ol><li>Pak je laatste jaarafrekening: verbruik en kosten.</li><li>Vast contract? Vraag eerst de opzegvergoeding.</li><li>Vergelijk bij meerdere vergelijkers, ook vaste kosten, kortingen en terugleverkosten.</li><li><strong>Sluit niets af tijdens een telefonisch verkoopgesprek.</strong></li><li>Meld je alleen aan bij de nieuwe leverancier; die regelt de overstap.</li><li>Gebruik de <strong>14 dagen bedenktijd</strong>.</li></ol>'
'<h2 id="cantpay">Kun je de rekening niet betalen?</h2><p>Vóór afsluiting moet de leverancier minstens <strong>3 herinneringen</strong> sturen met elk 14 dagen betaaltermijn, een <strong>betalingsregeling</strong> aanbieden en daarna je gegevens delen met de gemeente, die schuldhulp aanbiedt.</p><p><strong>Geen afsluiting</strong> als je een betalingsregeling nakomt, schriftelijk over de factuur hebt geklaagd, je hebt aangemeld voor schuldhulp (tot het besluit), of bij een ernstig gezondheidsrisico (verklaring van een andere arts dan je eigen arts).</p><p><strong>Winter:</strong> er is geen algemeen wettelijk afsluitverbod; netbeheerders sluiten van 1 oktober tot 1 april niet af bij strenge vorst (2 dagen achtereen gemiddeld onder 0 graden).</p>'
'<h2 id="noodfonds">Noodfonds Energie 2026–2027</h2>'
+T([['Voorbereiden','Vanaf 1 december 2026'],['Aanvragen','<strong>4 januari tot en met 7 mei 2027</strong>'],['Voorwaarden','Bruto-inkomen tot 130% van het sociaal minimum en energiequote ≥ 8%, of 130–200% en energiequote ≥ 10%'],['Steun','Helft van de kosten boven die grens; <strong>€ 120 tot € 1.800</strong>, meestal via je leverancier over 12 maanden'],['Verder','Geen «op is op»; ook blokverwarming, studenten, warmtenetten; papieren aanvraag mogelijk; eerste uitbetaling na circa 4–6 weken']],['Onderdeel','Details'])
+'<p>Een landelijke energietoeslag is er niet meer; gemeenten kregen extra geld en kunnen lokaal helpen. Een energiecoach geeft gratis advies en kleine maatregelen. Kijk op energiehulpvinden.nl. Voorwaarden en rekenvoorbeelden: zie onze <a href="/nl/articles/energy-emergency-fund-2027.html">gids Noodfonds Energie 2027</a>.</p>'
'<h2 id="renters">Huurders</h2><ul><li>Servicekosten voor energie betaal je alleen als je energie via de verhuurder krijgt; het jaaroverzicht moet uiterlijk <strong>1 juli</strong> binnen zijn. Klopt het niet: gemeentelijk meldpunt of Huurcommissie.</li><li>Vanaf <strong>1 januari 2027</strong> maximaal 8 soorten servicekosten bij nieuwe contracten.</li><li>Het <strong>energielabel</strong> telt mee in de huurpunten; de Huurcommissie kan het toetsen.</li><li>Laag inkomen: <a href="/nl/articles/housing-rent-allowance-2026.html">huurtoeslag</a> en <a href="/nl/articles/municipal-taxes-exemption-kwijtschelding.html">kwijtschelding</a>.</li></ul>'
'<h2 id="tips">Besparen in euro’s (Milieu Centraal)</h2><p>Berekend met € 1,37 per m³ gas en € 0,21 per kWh; jouw besparing hangt af van je woning en tarief:</p>'
+T([['Verwarming 1 graad lager','ca. € 170 per jaar'],['Verwarming laag ’s nachts (15°) en bij afwezigheid','ca. € 120 per jaar'],['Gordijnen ’s avonds dicht','ca. € 45 per jaar'],['Was aan het rek in plaats van droger','ca. € 50 per jaar'],['Radiatorfolie','ca. € 40 per jaar'],['Waterbesparende douchekop','ca. € 25 per jaar'],['Tweede koelkast weg','ca. € 35 per jaar'],['Vaatwasser op eco','ca. € 15 per jaar']],['Maatregel','Besparing'])
+'<h2 id="mistakes">Veelgemaakte fouten</h2><ol><li>Tekenen tijdens een verkoopgesprek zonder te vergelijken.</li><li>Denken dat verhuizen de opzegvergoeding schrapt.</li><li>Termijnbedrag te laag zetten.</li><li>Herinneringen negeren in plaats van direct een regeling vragen.</li><li>Met zonnepanelen het contract niet controleren vóór 1 januari 2027.</li></ol>'),
faq=[('Wat is het verschil tussen vast en variabel?','Vast: prijs gelijk tijdens de looptijd, maar mogelijk opzegvergoeding. Variabel: leverancier past prijs aan (vaak twee keer per jaar), geen opzegvergoeding.'),
('Hoe hoog is de opzegvergoeding?','Gelijk aan het werkelijke verlies van de leverancier: resterend verbruik × prijsverschil. Zijn prijzen niet gedaald, dan kan het € 0 zijn.'),
('Ik ga verhuizen. Moet ik een vergoeding betalen?','Verhuizen is geen uitzondering, maar je kunt je contract meenemen. Meld het minstens 2 weken vooraf.'),
('Wat verandert er voor zonnepanelen?','Salderen stopt op 1 januari 2027; je krijgt een terugleververgoeding van minimaal 50% van het kale leveringstarief tot 2030.'),
('Wanneer kan ik het Noodfonds aanvragen?','Van 4 januari tot en met 7 mei 2027; voorbereiden vanaf 1 december 2026. Steun € 120 tot € 1.800.'),
('Mag mijn energie in de winter worden afgesloten?','Er is geen algemeen verbod, maar eerst 3 herinneringen, een betalingsregeling en schuldhulp; netbeheerders sluiten niet af bij strenge vorst.')],
src_note='Regels gecontroleerd bij ACM ConsuWijzer en Rijksoverheid op 4 oktober 2026; besparingsbedragen van Milieu Centraal (onafhankelijke, door de overheid gefinancierde voorlichter). Bedragen voor 2027 zijn voorstellen tot het parlement beslist.')
