from a_student_finance import T
SLUG='dutch-government-terms-glossary'
B='https://www.belastingdienst.nl/wps/wcm/connect/nl/'
SRC=[('Rijksoverheid · Bezwaar maken tegen een beslissing van de overheid','https://www.rijksoverheid.nl/onderwerpen/bezwaar-en-beroep/vraag-en-antwoord/bezwaar-tegen-beslissing-overheid'),
('De Rechtspraak · Beroepsprocedure bestuursrecht (niet eens met beslissing overheidsorganisatie)','https://www.rechtspraak.nl/organisatie-en-contact/rechtsgebieden/bestuursrecht/procedures/beroepsprocedure'),
('Belastingdienst · Ik krijg een voorschotbeschikking van toeslagen - wat is dat?',B+'toeslagen/content/voorschotbeschikking-toeslagen'),
('Belastingdienst · Toeslag terugbetalen na de definitieve berekening',B+'toeslag-terugbetalen/content/toeslag-terugbetalen-na-definitieve-berekening'),
('Belastingdienst · Wat is een voorlopige aanslag?',B+'voorlopige-aanslag/content/wat-is-een-voorlopige-aanslag'),
('Rijksoverheid · Wanneer mag een schuldeiser een incassobureau inschakelen?','https://www.rijksoverheid.nl/vraag-en-antwoord/schulden/wanneer-incassobureau'),
('MijnOverheid · Berichtenbox: post van de overheid digitaal ontvangen','https://mijn.overheid.nl/'),
('DigiD · DigiD Machtigen','https://www.digid.nl/machtigen'),
('IND · Verblijfsvergunning aangevraagd: wat er nu gebeurt','https://ind.nl/nl/verblijfsvergunning-aangevraagd-wat-er-nu-gebeurt'),
('IND · Verblijfsvergunning regulier bepaalde tijd verlengen','https://ind.nl/nl/verlengen')]

# Each term: (Dutch term, pronunciation in Arabic letters, Arabic meaning, AR practical line, NL B1 explanation, guide slug or None)
THEMES=[
('letters','الرسائل والإجراءات الرسمية','Brieven en procedures',[
("beschikking","بِسخيكينخ","قرار إداري فردي","قرار مكتوب من جهة حكومية يخصّك أنت (مثلاً مبلغ إعانتك). يمكنك الاعتراض عليه.","Een schriftelijk besluit van de overheid over één persoon, bijvoorbeeld hoeveel toeslag iemand krijgt. Je kunt er bezwaar tegen maken.",None),
("besluit","بِسلاوت","قرار","الكلمة العامة لأي قرار من جهة حكومية. في الرسالة تجدها في جملة «Wij hebben besloten» (قررنا).","Algemeen woord voor een beslissing van de overheid. In de brief staat vaak: ‘Wij hebben besloten…’.",None),
("bezwaar","بيزوار","اعتراض","تطلب من نفس الجهة أن تعيد النظر في قرارها. المهلة عادة <strong>6 أسابيع</strong>، وهو مجاني ولا يحتاج محامياً.","Je vraagt dezelfde organisatie om haar besluit opnieuw te bekijken. Meestal binnen <strong>6 weken</strong>. Het is gratis en je hebt geen advocaat nodig.","bezwaar-objection-letter"),
("bezwaarschrift","بيزوارسخريفت","رسالة الاعتراض","تكتب فيها: اسمك وعنوانك، التاريخ، أي قرار تعترض عليه، لماذا، وتوقيعك.","De brief waarin je bezwaar maakt: naam en adres, datum, welk besluit, waarom je het er niet mee eens bent, en je handtekening.","bezwaar-objection-letter"),
("beslissing op bezwaar","بيسليسينخ أوب بيزوار","القرار بعد الاعتراض","رد الجهة على اعتراضك. إن بقيت غير موافق، الخطوة التالية هي الطعن (beroep).","Het antwoord van de organisatie op je bezwaar. Ben je het nog steeds niet eens? Dan kun je in beroep gaan.",None),
("hoorzitting","هورزيتينخ","جلسة استماع","موعد تشرح فيه اعتراضك شفهياً للجهة الحكومية، أحياناً عبر الهاتف أو الفيديو. يمكنك أن تحضر معك مساعداً.","Een gesprek waarin je je bezwaar mondeling uitlegt, soms via telefoon of video. Je mag iemand meenemen.",None),
("beroep","بيروب","طعن أمام المحكمة","بعد رفض اعتراضك تذهب إلى المحكمة الإدارية (rechtbank)، عادة خلال <strong>6 أسابيع</strong>. قد تدفع رسوم محكمة (griffierecht).","Na een afgewezen bezwaar ga je naar de rechtbank, meestal binnen <strong>6 weken</strong>. Je betaalt vaak griffierecht.",None),
("hoger beroep","هوخَر بيروب","استئناف","إن لم تقبل حكم المحكمة: مثلاً لدى Centrale Raad van Beroep في قضايا الإعانات، أو Raad van State، أو محكمة الاستئناف في الضرائب.","Niet eens met de rechtbank? Dan naar een hogere rechter, bijvoorbeeld de Centrale Raad van Beroep (uitkeringen), de Raad van State of het gerechtshof (belastingen).",None),
("voorlopige voorziening","فورلوبيخه فورزينينخ","إجراء مؤقت مستعجل","تطلب من القاضي حلاً مؤقتاً سريعاً حين لا يمكنك انتظار نتيجة الاعتراض أو الطعن (حالة عاجلة).","Je vraagt de rechter om snel een tijdelijke oplossing, als je niet kunt wachten op de uitkomst van bezwaar of beroep.",None),
("klacht","كلاخت","شكوى","عن <strong>تعامل</strong> الموظفين أو الجهة معك، لا عن القرار نفسه. للقرار تستخدم bezwaar.","Over hoe een organisatie of medewerker je heeft <strong>behandeld</strong>, niet over het besluit zelf. Tegen een besluit maak je bezwaar.",None),
("Nationale ombudsman","ناسيونالي أومبودسمان","أمين المظالم الوطني","جهة مستقلة تلجأ إليها بشكواك إن لم تحلّها الجهة الحكومية بنفسها أولاً.","Onafhankelijke instantie voor klachten over de overheid, als de organisatie zelf je klacht niet goed heeft opgelost.",None),
("aanmaning","آنمانينخ","إنذار بالدفع","تأتي بعد التذكير إن لم تدفع. قد تُضاف تكاليف، وبعدها قد تأتي إجراءات تحصيل أشد. لا تتجاهلها.","Een officiële betalingsaanmaning na de herinnering. Er kunnen kosten bij komen en daarna zwaardere invorderingsstappen. Niet laten liggen.","debt-help-schuldhulp"),
("herinnering","هيرينرينخ","تذكير","تذكير بأن الدفع أو المهمة لم تتم بعد. غالباً مرحلة قبل الإنذار.","Een brief die je eraan herinnert dat je nog iets moet betalen of doen. Meestal komt die vóór de aanmaning.",None),
("termijn","تيرمَين","مهلة / قسط","معنيان: <strong>المهلة</strong> (binnen 6 weken = خلال 6 أسابيع)، أو <strong>القسط</strong> (in termijnen betalen = الدفع بالتقسيط).","Twee betekenissen: een <strong>deadline</strong> (‘binnen 6 weken’) of een <strong>deelbetaling</strong> (‘in termijnen betalen’).",None),
("kenmerk","كينميرك","رقم المرجع","رقم ملفك في الرسالة (ons kenmerk). اذكره في كل اتصال أو رد. «uw kenmerk» هو رقمك أنت إن أرسلت لهم شيئاً.","Het nummer van je dossier in de brief (‘ons kenmerk’). Noem het altijd als je belt of schrijft. ‘Uw kenmerk’ is jouw eigen nummer.",None),
("betalingskenmerk","بيتالينخسكينميرك","رقم الدفع","رقم يجب نسخه <strong>بالضبط</strong> عند التحويل البنكي، وإلا قد لا يُربط دفعك بالدَّين.","Het nummer dat je <strong>precies</strong> overneemt bij het betalen, anders wordt je betaling misschien niet goed verwerkt.","traffic-fines-cjib"),
("dagtekening","داختيكنينخ","تاريخ الرسالة","التاريخ المطبوع على الرسالة. كثير من المهل تُحسب منه، لا من يوم قراءتك للرسالة.","De datum die op de brief staat. Veel termijnen tellen vanaf deze datum, niet vanaf de dag dat je de brief leest.",None),
("ontvangstbevestiging","أونتفانخستبيفيستيخينخ","إشعار استلام","رسالة تؤكد أنهم استلموا طلبك أو اعتراضك. احتفظ بها كدليل.","Een bevestiging dat je aanvraag of bezwaar is ontvangen. Goed bewaren als bewijs.",None),
("bijlage","بايلاخه","مرفق","مستند مرفق بالرسالة أو مطلوب منك إرفاقه (نسخة جواز، كشف راتب…).","Een document dat bij de brief zit of dat je zelf moet meesturen, zoals een kopie paspoort of loonstrook.",None),
("machtiging","ماختيخينخ","تفويض","إذن رسمي لشخص آخر ليقوم بأمورك الحكومية عنك، عبر <strong>DigiD Machtigen</strong>. لا تعطِ كلمة سر DigiD لأحد.","Toestemming aan iemand anders om zaken met de overheid voor je te regelen, via <strong>DigiD Machtigen</strong>. Nooit je DigiD-inloggegevens doorgeven.","digid-registration-guide"),
("DigiD","ديخي دي","الهوية الرقمية","اسم المستخدم وكلمة السر (أو التطبيق) للدخول إلى مواقع الحكومة والتأمين الصحي.","Je digitale identiteit om in te loggen bij de overheid en bijvoorbeeld je zorgverzekeraar.","digid-registration-guide"),
("MijnOverheid","ماين أوفرهايد","حكومتي (البوابة الشخصية)","موقع واحد ترى فيه بياناتك الشخصية وتستلم فيه البريد الحكومي رقمياً، تدخله بـDigiD.","Persoonlijke website van de overheid met je gegevens en digitale post. Inloggen met DigiD.",None),
("Berichtenbox","بيريختنبوكس","صندوق الرسائل الرقمي","صندوق بريدك الحكومي داخل MijnOverheid. إن فعّلته، قد تصل رسائل مهمة فيه بدلاً من الورق؛ فعّل التنبيه بالبريد الإلكتروني وافتحه بانتظام.","Je digitale brievenbus voor overheidspost in MijnOverheid. Belangrijke brieven kunnen hier komen in plaats van op papier. Zet e-mailmeldingen aan en kijk regelmatig.",None),
("wijziging doorgeven","فايزيخينخ دورخيفن","الإبلاغ عن تغيير","واجب إبلاغ الجهة بأي تغيير (دخل، عنوان، شريك، أولاد) بسرعة، وإلا قد تُطالَب بالإرجاع.","Een verandering (inkomen, adres, partner, kinderen) op tijd melden. Anders moet je later misschien geld terugbetalen.","toeslagen-income-update"),
]),
('toeslagen','الإعانات (toeslagen)','Toeslagen',[
("toeslag","توسلاخ","إعانة / مساهمة مالية","مساعدة من الدولة لتغطية جزء من تكاليف التأمين الصحي أو الإيجار أو الحضانة أو الأولاد، حسب دخلك.","Geld van de overheid als bijdrage in kosten van zorgverzekering, huur, kinderopvang of kinderen, afhankelijk van je inkomen.","toeslagen-income-update"),
("Dienst Toeslagen","دينست توسلاخن","مصلحة الإعانات","الجهة التي تحسب وتدفع toeslagen. تجد بياناتك في «Mijn toeslagen» بـDigiD.","De organisatie die toeslagen berekent en uitbetaalt. Je gegevens staan in ‘Mijn toeslagen’ (inloggen met DigiD).",None),
("zorgtoeslag","زورخ توسلاخ","إعانة التأمين الصحي","مساهمة في قسط التأمين الصحي الأساسي.","Bijdrage in de premie van de zorgverzekering.","zorgtoeslag-guide"),
("huurtoeslag","هور توسلاخ","إعانة الإيجار","مساهمة في الإيجار إن كان دخلك منخفضاً وإيجارك ضمن الحدود.","Bijdrage in de huur bij een laag inkomen en een huur binnen de grenzen.","housing-rent-allowance-2026"),
("kinderopvangtoeslag","كندرأوبفانخ توسلاخ","إعانة حضانة الأطفال","مساهمة في تكاليف الحضانة المسجلة، مرتبطة بساعات الحضانة وعملك.","Bijdrage in de kosten van geregistreerde kinderopvang, gekoppeld aan opvanguren en werk.","childcare-allowance-kinderopvangtoeslag"),
("kindgebonden budget","كينتخيبوندن بودجيت","ميزانية الأطفال","مبلغ إضافي لعائلات بدخل محدود لديها أطفال قاصرون.","Extra bijdrage voor gezinnen met minderjarige kinderen en een niet te hoog inkomen.","kindgebonden-budget-guide"),
("toeslagpartner","توسلاخ بارتنر","شريك الإعانة","الشريك الذي يُحسب دخله مع دخلك (زوج/زوجة أو شريك يسكن معك في حالات معينة).","De partner van wie het inkomen meetelt, zoals je echtgenoot of in bepaalde gevallen iemand met wie je samenwoont.","toeslagpartner-guide"),
("voorschot","فورسخوت","دفعة مقدمة","المبلغ الشهري الذي تستلمه <strong>مؤقتاً</strong> بناءً على دخل <strong>متوقع</strong>. ليس نهائياً.","Het maandbedrag dat je <strong>alvast</strong> krijgt op basis van een <strong>geschat</strong> inkomen. Nog niet definitief.","toeslagen-income-update"),
("voorschotbeschikking","فورسخوتبيسخيكينخ","قرار الدفعة المقدمة","رسالة سنوية فيها كم ستحصل في السنة القادمة، تصل بين 21 نوفمبر و14 ديسمبر، وأول دفعة في 20 ديسمبر ثم حوالي يوم 20 من كل شهر. تحقق من الدخل المذكور فيها.","Jaarlijkse brief met hoeveel toeslag je volgend jaar krijgt. Komt tussen 21 november en 14 december; eerste betaling 20 december, daarna rond de 20e van elke maand. Controleer het inkomen.","toeslagen-income-update"),
("definitieve berekening","ديفينيتيفه بيريكنينخ","الحساب النهائي","بعد انتهاء السنة ومعرفة دخلك الحقيقي يُحسب حقك النهائي. ينتج عنه: إرجاع أو دفعة إضافية أو لا شيء.","Na afloop van het jaar, als je echte inkomen bekend is, wordt de toeslag definitief berekend. Uitkomst: terugbetalen, nabetaling of niets.","toeslagen-income-update"),
("terugvordering","تيروخفوردرينخ","مطالبة بالإرجاع","حصلت على أكثر مما يحق لك (مثلاً لأن دخلك كان أعلى من التقدير)، فتُطالَب بإرجاع الفرق.","Je hebt te veel gekregen (bijvoorbeeld omdat je inkomen hoger was dan geschat) en moet het verschil terugbetalen.","toeslagen-income-update"),
("nabetaling","نابيتالينخ","دفعة لاحقة / مستحقات","حقك كان أكبر مما استلمت، فتحصل على الفرق.","Je had recht op meer dan je kreeg; je krijgt het verschil alsnog.",None),
("toetsingsinkomen","توتسينخس إنكومن","الدخل المعتمد للحساب","الدخل السنوي الذي تُحسب عليه الإعانة (مع دخل الشريك). ليس صافي راتبك الشهري.","Het jaarinkomen waarmee de toeslag wordt berekend (samen met de partner). Niet hetzelfde als je netto maandloon.","toeslagen-income-update"),
("vermogen","فيرموخن","الثروة / المدخرات","مدخراتك وممتلكاتك. إن تجاوزت حداً معيناً قد تخسر الإعانة.","Je spaargeld en bezittingen. Boven een bepaalde grens heb je geen recht op toeslag.",None),
("betalingsregeling","بيتالينخسريخلينخ","اتفاق تقسيط","اتفاق لدفع دَين (مثل إرجاع toeslag) على أقساط شهرية. اطلبه مبكراً.","Afspraak om een schuld, zoals terug te betalen toeslag, in delen te betalen. Vraag het op tijd aan.","debt-help-schuldhulp"),
]),
('tax','الضرائب (belasting)','Belastingen',[
("belasting","بيلاستينخ","ضريبة","مبلغ تدفعه للدولة أو البلدية.","Geld dat je aan de overheid of de gemeente betaalt.",None),
("Belastingdienst","بيلاستينخدينست","مصلحة الضرائب","الجهة الوطنية للضرائب. انتبه: رسائل احتيال كثيرة تنتحل اسمها.","De landelijke belastingorganisatie. Let op: oplichters doen zich vaak voor als de Belastingdienst.","scams-phishing-netherlands"),
("aangifte inkomstenbelasting","آنخيفته إنكومستنبيلاستينخ","الإقرار الضريبي السنوي","تصرّح فيه بدخلك عن السنة الماضية. إن وصلتك دعوة (uitnodiging) فهو واجب.","Je geeft je inkomen over het afgelopen jaar door. Kreeg je een uitnodiging? Dan ben je verplicht aangifte te doen.","annual-tax-return-2026"),
("vooringevulde aangifte","فورإنخيفولده آنخيفته","إقرار معبّأ مسبقاً","الإقرار يأتي فيه جزء من البيانات جاهزاً؛ لكن <strong>أنت مسؤول</strong> عن التحقق منها.","Een aangifte waarin al gegevens staan. Jij blijft <strong>verantwoordelijk</strong> om alles te controleren.","annual-tax-return-2026"),
("aanslag","آنسلاخ","قرار ضريبي (تقدير)","رسالة تقول كم ضريبة عليك أن تدفع أو كم ستسترد.","Brief waarin staat hoeveel belasting je moet betalen of terugkrijgt.",None),
("voorlopige aanslag","فورلوبيخه آنسلاخ","تقدير ضريبي مؤقت","<strong>تقدير</strong> لما ستدفعه أو تسترده، وقد يُدفع لك أو منك شهرياً، ثم يُصحَّح بعد الإقرار.","Een <strong>schatting</strong> van wat je betaalt of terugkrijgt, soms per maand. Na de aangifte wordt het verrekend.","annual-tax-return-2026"),
("definitieve aanslag","ديفينيتيفه آنسلاخ","التقدير الضريبي النهائي","القرار النهائي بعد فحص إقرارك. يمكنك الاعتراض عليه خلال المهلة المذكورة.","De laatste berekening na controle van je aangifte. Je kunt bezwaar maken binnen de termijn in de brief.",None),
("teruggave","تيروخخافه","استرداد ضريبي","مبلغ تعيده لك مصلحة الضرائب.","Geld dat je terugkrijgt van de Belastingdienst.",None),
("loonheffing","لونهيفينخ","ضريبة الراتب المقتطعة","الضريبة والاشتراكات التي يقتطعها صاحب العمل من راتبك قبل أن يصلك.","Belasting en premies die je werkgever al van je loon inhoudt.","dutch-payslip-explained"),
("heffingskorting","هيفينخسكورتينخ","خصم ضريبي","تخفيض يقلل الضريبة عليك (مثل الخصم العام وخصم العمل). اسأل صاحب العمل أن يطبّقه عند جهة عمل واحدة فقط.","Korting op de belasting die je betaalt, zoals de algemene heffingskorting en arbeidskorting. Laat die bij maar één werkgever of uitkering toepassen.","dutch-payslip-explained"),
("jaaropgaaf","يارأوبخاف","كشف الدخل السنوي","ورقة من صاحب العمل أو جهة الإعانة فيها مجموع دخلك والضريبة المقتطعة. تحتاجها للإقرار.","Overzicht van je werkgever of uitkeringsinstantie met je jaarinkomen en ingehouden loonheffing. Nodig voor de aangifte.","annual-tax-return-2026"),
("uitstel","أوتستيل","تأجيل / مهلة إضافية","طلب وقت إضافي لتقديم الإقرار أو للدفع. اطلبه قبل انتهاء المهلة.","Meer tijd vragen voor de aangifte of de betaling. Vraag het aan vóór de deadline.",None),
]),
('work','العمل وUWV','Werk en UWV',[
("werkgever / werknemer","فيركخيفر / فيركنيمر","صاحب العمل / الموظف","werkgever من يدفع الراتب، وwerknemer أنت العامل.","Werkgever: wie het loon betaalt. Werknemer: wie het werk doet.","employment-contracts-labor-law-2026"),
("arbeidsovereenkomst","آربايدسأوفريَنكومست","عقد العمل","العقد بينك وبين صاحب العمل: المدة، الساعات، الراتب. اطلب نسخة مكتوبة.","Het contract tussen werkgever en werknemer: duur, uren en loon. Vraag altijd een schriftelijke versie.","employment-contracts-labor-law-2026"),
("proeftijd","بروفتايد","فترة التجربة","فترة في بداية العقد يمكن فيها إنهاء العمل بسرعة. يجب أن تكون مكتوبة في العقد.","Een periode aan het begin van het contract waarin beide partijen snel kunnen stoppen. Moet in het contract staan.","employment-contracts-labor-law-2026"),
("loonstrook","لونستروك","كشف الراتب","ورقة تُظهر الراتب الإجمالي (bruto) والصافي (netto) والاقتطاعات. احتفظ بها.","Overzicht van je brutoloon, nettoloon en inhoudingen. Goed bewaren.","dutch-payslip-explained"),
("bruto / netto","برُوتو / نيتو","إجمالي / صافي","bruto قبل الضريبة والاقتطاعات، netto ما يصل حسابك فعلاً.","Bruto: vóór belasting en inhoudingen. Netto: wat je echt op je rekening krijgt.","dutch-payslip-explained"),
("vakantiegeld","فاكانسيخيلد","بدل العطلة","مبلغ إضافي يُدفع عادة مرة في السنة (غالباً في الربيع)، أو يُبنى شهرياً حسب عقدك.","Extra geld dat meestal één keer per jaar wordt uitbetaald (vaak in het voorjaar), of per maand opgebouwd volgens je contract.","dutch-payslip-explained"),
("ontslag","أونتسلاخ","فصل / إنهاء العمل","انتهاء عقد العمل. لا توقّع على إنهاء «بالتراضي» قبل أن تستشير، لأنه قد يؤثر على حقك في WW.","Einde van het dienstverband. Teken niet zomaar een beëindiging ‘met wederzijds goedvinden’; dat kan gevolgen hebben voor je WW.","unemployment-benefit-ww"),
("UWV","أو في في","مؤسسة تأمينات العاملين","الجهة التي تدفع إعانة البطالة والمرض والعجز وتساعد في البحث عن عمل.","De organisatie voor WW, Ziektewet, WIA en hulp bij werk zoeken.","unemployment-benefit-ww"),
("uitkering","أوتكيرينخ","إعانة / مخصص","مبلغ دوري تستلمه بدل الدخل (بطالة، مرض، مساعدة اجتماعية، تقاعد).","Een regelmatig bedrag als vervanging van inkomen, zoals WW, bijstand of AOW.",None),
("WW","في في","إعانة البطالة","لمن فقد عمله وعمل مدة كافية قبله. تقدَّم عبر UWV.","Werkloosheidsuitkering voor wie werk kwijt is en genoeg heeft gewerkt. Aanvragen bij UWV.","unemployment-benefit-ww"),
("ziekmelding","زيكميلدينخ","الإبلاغ عن المرض","أبلغ صاحب العمل بمرضك فوراً حسب قواعد الشركة.","Je meldt je ziek bij je werkgever volgens de regels van het bedrijf.","sick-pay-ziektewet-wia"),
("Ziektewet / WIA","زيكتهفيت / في إي آ","قانون المرض / إعانة العجز","Ziektewet عند المرض دون صاحب عمل يدفع لك، وWIA بعد مرض طويل يقلل قدرتك على العمل.","Ziektewet: ziek zonder werkgever die betaalt. WIA: na lange ziekte als je minder kunt werken.","sick-pay-ziektewet-wia"),
("sollicitatieplicht","سوليسيتاتسيبليخت","واجب البحث عن عمل","مع WW أو bijstand عليك غالباً أن تتقدم لوظائف وتسجل ذلك. عدم الالتزام قد يخفض إعانتك.","Bij WW of bijstand moet je meestal solliciteren en dat laten zien. Doe je dat niet, dan kan je uitkering lager worden.","unemployment-benefit-ww"),
("werk.nl","فيرك نيل","موقع UWV للعمل","موقع UWV لتسجيل نفسك كباحث عن عمل وتسليم النماذج والبحث عن وظائف.","Website van UWV om je als werkzoekende in te schrijven, formulieren in te vullen en vacatures te zoeken.",None),
]),
('housing','السكن','Wonen',[
("huurcontract","هوركونتراكت","عقد الإيجار","العقد بينك وبين المؤجر. اقرأ المدة والإيجار والتكاليف قبل التوقيع.","Het contract met de verhuurder. Lees de duur, de huur en de kosten voordat je tekent.","tenant-rights-netherlands"),
("verhuurder / huurder","فيرهوردر / هوردر","المؤجر / المستأجر","verhuurder صاحب السكن، وhuurder أنت.","Verhuurder: eigenaar die verhuurt. Huurder: wie de woning huurt.","tenant-rights-netherlands"),
("woningcorporatie","فونينخكوربوراتسيه","شركة السكن الاجتماعي","مؤسسة تؤجر بيوتاً اجتماعية بإيجار مضبوط.","Organisatie die sociale huurwoningen verhuurt.","social-housing-sociale-huurwoning"),
("inschrijfduur","إنسخرايفدور","مدة التسجيل","المدة التي مضت على تسجيلك للسكن الاجتماعي؛ كلما طالت زادت فرصتك. سجّل مبكراً.","Hoe lang je ingeschreven staat als woningzoekende. Hoe langer, hoe meer kans. Schrijf je vroeg in.","social-housing-sociale-huurwoning"),
("urgentie","أورخينسي","أولوية سكن طارئة","أولوية خاصة من البلدية في حالات صعبة جداً، بشروط صارمة.","Voorrang op een woning in een zeer moeilijke situatie, met strenge voorwaarden van de gemeente.","social-housing-sociale-huurwoning"),
("huurverhoging","هورفيرهوخينخ","زيادة الإيجار","زيادة سنوية لها حد أقصى قانوني. يمكنك الاعتراض عليها.","Jaarlijkse verhoging van de huur, met een wettelijk maximum. Bezwaar is mogelijk.","tenant-rights-netherlands"),
("servicekosten","سيرفيسكوستن","تكاليف الخدمات","تكاليف إضافية فوق الإيجار (تنظيف، إنارة مشتركة…). يحق لك كشف سنوي بها.","Extra kosten bovenop de huur, zoals schoonmaak of gemeenschappelijke verlichting. Je hebt recht op een jaaroverzicht.","tenant-rights-netherlands"),
("waarborgsom / borg","واربورخسوم / بورخ","مبلغ التأمين (الكفالة)","مبلغ تدفعه عند بدء الإيجار ويُعاد عند الخروج؛ له حد أقصى قانوني.","Geld dat je bij het begin betaalt en aan het einde terugkrijgt; er geldt een wettelijk maximum.","tenant-rights-netherlands"),
("Huurcommissie","هوركوميسي","لجنة الإيجار","جهة مستقلة تحسم الخلافات حول الإيجار والصيانة وتكاليف الخدمات.","Onafhankelijke instantie die geschillen over huurprijs, onderhoud en servicekosten beslecht.","tenant-rights-netherlands"),
("huurachterstand","هورآختيرستاند","متأخرات الإيجار","إيجار لم تدفعه بعد. تواصل فوراً مع المؤجر واطلب مساعدة الديون.","Huur die nog niet betaald is. Neem meteen contact op met de verhuurder en vraag schuldhulp.","debt-help-schuldhulp"),
("ontruiming","أونتراومينخ","الإخلاء","إخراجك من البيت. يحتاج المؤجر لذلك حكماً من القاضي؛ لا تنتظر حتى تصل الأمور إلى هذه المرحلة.","Gedwongen verlaten van de woning. De verhuurder heeft daarvoor een uitspraak van de rechter nodig.","tenant-rights-netherlands"),
]),
('health','الصحة والرعاية (zorg)','Gezondheid en zorg',[
("zorgverzekering","زورخفيرزيكرينخ","التأمين الصحي","إلزامي لكل من يسكن أو يعمل في هولندا ويجب عليه ذلك قانوناً.","Verplichte verzekering voor zorgkosten voor wie in Nederland woont of werkt.","health-insurance-newcomers"),
("basisverzekering","باسيسفيرزيكرينخ","التأمين الأساسي","الحزمة الإلزامية نفسها عند كل الشركات، يحددها القانون.","Het verplichte basispakket; de inhoud is bij elke verzekeraar hetzelfde.","health-insurance-2027"),
("aanvullende verzekering","آنفولنده فيرزيكرينخ","تأمين إضافي","اختياري: للأسنان للبالغين، والعلاج الطبيعي وغيرها.","Vrijwillige extra verzekering, bijvoorbeeld voor tandarts (volwassenen) of fysiotherapie.","health-insurance-2027"),
("premie","بريمي","القسط الشهري","المبلغ الشهري الذي تدفعه لشركة التأمين.","Het bedrag dat je elke maand aan de verzekeraar betaalt.","health-insurance-2027"),
("eigen risico","آيخن ريسيكو","التحمل الذاتي (الحصة الذاتية)","مبلغ سنوي تدفعه أنت أولاً من بعض تكاليف العلاج. زيارة طبيب العائلة لا تدخل فيه.","Bedrag per jaar dat je zelf eerst betaalt voor sommige zorg. De huisarts valt daar niet onder.","health-insurance-2027"),
("polis","بوليس","وثيقة التأمين","الورقة التي توضح تأمينك وما يغطيه ورقمك.","Het overzicht van je verzekering met je polisnummer en dekking.",None),
("huisarts","هاوسآرتس","طبيب العائلة","أول طبيب تذهب إليه. سجّل لدى طبيب قريب من بيتك.","De eerste dokter voor gezondheidsklachten. Schrijf je in bij een huisarts dichtbij.","huisarts-registration"),
("verwijzing","فيرفايزينخ","إحالة","ورقة من طبيب العائلة لتذهب إلى المختص أو المستشفى؛ بدونها قد لا يدفع التأمين.","Een doorverwijzing van de huisarts naar specialist of ziekenhuis; zonder verwijzing vergoedt de verzekeraar vaak niet.","huisarts-registration"),
("huisartsenpost","هاوسآرتسنبوست","عيادة الطوارئ خارج الدوام","للحالات العاجلة مساءً وليلاً وفي العطل. اتصل أولاً قبل الذهاب.","Voor spoed ’s avonds, ’s nachts en in het weekend. Eerst bellen.","huisarts-registration"),
("apotheek","آبوتيك","صيدلية","تصرف الأدوية بوصفة (recept) من الطبيب.","Waar je medicijnen met een recept ophaalt.",None),
("Wmo","في إم أو","قانون الدعم الاجتماعي","دعم من البلدية لتعيش باستقلالية: مساعدة منزلية، تعديلات، نقل.","Ondersteuning van de gemeente om zelfstandig te wonen, zoals huishoudelijke hulp of aanpassingen.","wmo-home-support"),
("GGD / consultatiebureau","خي خي دي / كونسولتاتسيبورو","الصحة العامة / مركز رعاية الطفل","GGD للصحة العامة والتطعيمات، وconsultatiebureau لمتابعة نمو الأطفال الصغار وتطعيماتهم.","GGD: publieke gezondheid en vaccinaties. Consultatiebureau: controle van groei en vaccinaties van jonge kinderen.","pregnancy-newborn-care"),
]),
('education','التعليم','Onderwijs',[
("leerplicht","ليربليخت","التعليم الإلزامي","على الأطفال في سن المدرسة الذهاب إليها. الغياب خارج العطل يحتاج إذناً من المدير.","Kinderen in de leerplichtige leeftijd moeten naar school. Verlof buiten de vakanties alleen met toestemming van de directeur.","dutch-school-system-basisschool"),
("leerplichtambtenaar","ليربليختأمبتنار","موظف التعليم الإلزامي","موظف بالبلدية يتابع الغياب غير المسموح به.","Ambtenaar van de gemeente die let op ongeoorloofd schoolverzuim.","dutch-school-system-basisschool"),
("basisschool","باسيسسخول","المدرسة الابتدائية","المرحلة الأولى من التعليم.","De school voor jonge kinderen, de eerste fase van het onderwijs.","dutch-school-system-basisschool"),
("schooladvies","سخولأدفيس","توصية المدرسة","نصيحة نهاية الابتدائي لأي مستوى من الثانوي يناسب الطفل.","Advies aan het einde van de basisschool over het niveau in het voortgezet onderwijs.","dutch-school-system-basisschool"),
("voortgezet onderwijs","فورتخيزيت أونديرفايس","التعليم الثانوي","بعد الابتدائي: vmbo أو havo أو vwo.","Middelbare school na de basisschool: vmbo, havo of vwo.","dutch-school-system-basisschool"),
("mbo / hbo / wo","إم بي أو / هاء بي أو / في أو","مهني / معاهد عليا / جامعة","مستويات التعليم بعد الثانوي.","Niveaus van vervolgonderwijs: middelbaar beroepsonderwijs, hogeschool en universiteit.","mbo-hbo-wo-comparison"),
("ouderbijdrage","آودربايدراخه","مساهمة الأهل","مبلغ تطلبه المدرسة للأنشطة؛ هو <strong>طوعي</strong> ولا يجوز حرمان الطفل من نشاط بسبب عدم دفعه.","Bijdrage die de school vraagt voor activiteiten. Die is <strong>vrijwillig</strong>; een kind mag niet worden uitgesloten als ouders niet betalen.","dutch-school-system-basisschool"),
("DUO","دو أو","مؤسسة التعليم التنفيذية","تدير تمويل الدراسة وقروض الاندماج وامتحانات الاندماج.","Organisatie voor studiefinanciering, lening voor inburgering en inburgeringsexamens.","student-finance"),
("studiefinanciering","ستوديفينانسيرينخ","تمويل الدراسة","منحة وقرض للطلاب حسب الشروط.","Beurs en lening voor studenten, onder voorwaarden.","student-finance"),
]),
('residence','الإقامة والـIND','Verblijf en IND',[
("IND","إي إن دي","دائرة الهجرة والتجنيس","الجهة التي تقرر في طلبات الإقامة والتجنيس.","De Immigratie- en Naturalisatiedienst; beslist over verblijfsvergunningen en naturalisatie.",None),
("verblijfsvergunning","فيربلايفسفيرخونينخ","تصريح الإقامة","الإذن الرسمي بالإقامة لهدف محدد ولمدة محددة.","Toestemming om in Nederland te wonen, voor een bepaald doel en een bepaalde tijd.","eu-permanent-residence-netherlands"),
("verblijfsdoel","فيربلايفسدول","هدف الإقامة","سبب إقامتك (عمل، دراسة، أسرة، لجوء). تغيّره يتطلب طلباً جديداً أحياناً.","De reden van verblijf, zoals werk, studie of gezin. Bij een ander doel is soms een nieuwe aanvraag nodig.",None),
("verblijfsdocument","فيربلايفسدوكومنت","بطاقة الإقامة","البطاقة المادية التي تثبت إقامتك.","Het pasje dat je verblijfsrecht laat zien.",None),
("mvv","إم في في","تأشيرة الإقامة الطويلة","تأشيرة دخول لإقامة أطول من 3 أشهر، يحتاجها كثيرون قبل القدوم.","Machtiging tot voorlopig verblijf: visum om Nederland in te reizen voor een verblijf van langer dan 3 maanden.","family-reunification-mvv-ind"),
("referent","ريفيرنت","الكفيل","الشخص أو الجهة في هولندا التي تتقدم بالطلب لصالحك (شريك، صاحب عمل…).","De persoon of organisatie in Nederland die de aanvraag voor iemand doet, zoals partner of werkgever.","family-reunification-mvv-ind"),
("leges","ليخس","رسوم الطلب","رسوم تدفعها مقابل دراسة الطلب، ولا تُعاد عادة إن رُفض. مع الطلب الورقي تصلك رسالة دفع ومهلة أسبوعين.","Kosten voor het behandelen van een aanvraag; meestal niet terug bij afwijzing. Bij een papieren aanvraag krijg je een betaalbrief en 2 weken om te betalen.",None),
("beslistermijn","بيسليستيرمين","مهلة اتخاذ القرار","المدة التي يجب أن يقرر فيها IND، مذكورة في إشعار الاستلام. يمكن تمديدها حتى 6 أشهر إن احتاج تحقيقاً إضافياً، وتتوقف إن طُلبت منك أوراق.","Hoe lang de IND mag doen over een beslissing; staat in de ontvangstbevestiging. Kan maximaal 6 maanden langer bij extra onderzoek en staat stil als de IND om stukken vraagt.",None),
("biometrie","بيوميتري","البصمة والصورة","موعد في مكتب IND لأخذ صورتك وبصماتك لبطاقة الإقامة.","Afspraak bij de IND voor pasfoto en vingerafdrukken voor het verblijfsdocument.",None),
("verlengen","فيرلينخن","التمديد","طلب تمديد الإقامة قبل انتهائها؛ IND يتيحه عندما تنتهي إقامتك خلال 3 أشهر. لا تنتظر للحظة الأخيرة.","Verlenging aanvragen voordat je vergunning verloopt; de IND noemt dit als je vergunning binnen 3 maanden verloopt. Niet tot het laatst wachten.",None),
("inburgeringsplicht","إنبورخرينخسبليخت","واجب الاندماج","واجب تعلم اللغة والمجتمع ضمن برنامج الاندماج، تتابعه البلدية وDUO.","De plicht om in te burgeren (taal en samenleving); de gemeente en DUO begeleiden.","inburgering-integration-law-2026"),
("naturalisatie","ناتوراليزاتسيه","التجنيس","طلب الحصول على الجنسية الهولندية، يقدَّم عبر البلدية.","Nederlander worden; je dient het verzoek in via de gemeente.","dutch-naturalisation-guide"),
]),
('municipality','البلدية (gemeente)','Gemeente',[
("gemeente","خيمينته","البلدية","تسجيل السكن، المساعدة الاجتماعية، Wmo، مساعدة الديون، الضرائب المحلية.","Inschrijving, bijstand, Wmo, schuldhulp en gemeentelijke belastingen.","bsn-municipality-registration"),
("BRP","بي إر بي","سجل السكان","السجل الرسمي لعنوانك وبياناتك. يجب أن يكون صحيحاً لأن الجهات كلها تعتمد عليه.","Basisregistratie Personen: officiële registratie van je adres en gegevens. Andere organisaties gebruiken deze gegevens.","bsn-municipality-registration"),
("BSN","بي إس إن","رقم المواطن (الرقم الشخصي)","رقمك الشخصي في كل المعاملات. لا تشاركه إلا مع جهات موثوقة.","Burgerservicenummer: je persoonlijke nummer. Alleen delen met betrouwbare instanties.","bsn-municipality-registration"),
("inschrijving / verhuizing doorgeven","إنسخرايفينخ / فيرهاوزينخ دورخيفن","التسجيل / الإبلاغ عن الانتقال","سجّل عنوانك وبلّغ عن الانتقال في الوقت؛ البريد الرسمي يُرسل إلى عنوان BRP.","Je inschrijven en een verhuizing op tijd doorgeven; officiële post gaat naar je BRP-adres.","change-address-netherlands"),
("uittreksel","أوتريكسل","مستخرج رسمي","وثيقة من البلدية بمعلوماتك المسجلة، تُطلب أحياناً لعقد أو طلب.","Een officieel overzicht van je gegevens uit de BRP, soms nodig voor een aanvraag.","bsn-municipality-registration"),
("afspraak","أفسبراك","موعد","معظم معاملات البلدية والـIND تحتاج موعداً مسبقاً.","Voor veel zaken bij gemeente of IND moet je eerst een afspraak maken.",None),
("gemeentelijke belastingen","خيمينتليكه بيلاستينخن","الضرائب البلدية","ضرائب محلية مثل رسوم النفايات والصرف الصحي.","Lokale belastingen, zoals afvalstoffenheffing en rioolheffing.","municipal-taxes-exemption-kwijtschelding"),
("kwijtschelding","كفايتسخيلدينخ","الإعفاء","إعفاء من بعض الضرائب البلدية لذوي الدخل المحدود جداً. يجب أن تطلبه.","Vrijstelling van sommige gemeentelijke belastingen bij een laag inkomen. Je moet het aanvragen.","municipal-taxes-exemption-kwijtschelding"),
("WOZ-waarde","في أو زد فارده","القيمة التقديرية للعقار","قيمة البيت التي تحددها البلدية، وتؤثر في بعض الضرائب، ونقاط الإيجار أحياناً.","De waarde van een woning volgens de gemeente; belangrijk voor sommige belastingen en soms voor de huurprijs.",None),
("bijstand","بايستاند","المساعدة الاجتماعية","دخل أدنى من البلدية لمن لا يكفيه دخله ولا يملك مالاً كافياً.","Uitkering van de gemeente voor wie te weinig inkomen en vermogen heeft.","social-assistance-bijstand"),
("bijzondere bijstand","بيزونديره بايستاند","المساعدة الخاصة","مساعدة لمصاريف ضرورية وغير عادية لا يغطيها دخلك.","Hulp van de gemeente voor noodzakelijke, bijzondere kosten die je niet zelf kunt betalen.","special-assistance-bijzondere-bijstand"),
("sociaal wijkteam","سوسيال فايكتيم","فريق الحي الاجتماعي","فريق في البلدية يساعدك في الأوراق والديون والمشاكل العائلية مجاناً (الاسم يختلف حسب البلدية).","Team van de gemeente dat gratis helpt met post, geld en zorgen in het gezin (de naam verschilt per gemeente).",None),
]),
('debts','المال والديون','Geld en schulden',[
("schuld","سخولد","دَين","مبلغ يجب أن تدفعه ولم تدفعه بعد.","Geld dat je nog moet betalen.","debt-help-schuldhulp"),
("betalingsachterstand","بيتالينخسأختيرستاند","تأخر في الدفع","فواتير متأخرة. تصرّف مبكراً قبل أن تكبر التكاليف.","Rekeningen die te laat zijn. Snel actie nemen voordat de kosten oplopen.","debt-help-schuldhulp"),
("incassobureau","إنكاسوبورو","مكتب تحصيل الديون","شركة يكلّفها الدائن بتحصيل الدَّين. لا يحق لها حجز أملاكك أو راتبك.","Bedrijf dat namens een schuldeiser geld int. Het mag geen beslag leggen op je spullen of loon.","debt-help-schuldhulp"),
("incassokosten","إنكاسوكوستن","تكاليف التحصيل","تكاليف إضافية لا يجوز فرضها إلا بعد رسالة دفع أولى تعطيك <strong>14 يوماً</strong> للدفع.","Extra kosten; die mogen pas na een eerste betalingsherinnering waarin je <strong>14 dagen</strong> krijgt om te betalen.","debt-help-schuldhulp"),
("deurwaarder","ديورواردر","المحضر القضائي","موظف رسمي وحده يستطيع تبليغ أوراق المحكمة وتنفيذ الحجز. خذ رسائله بجدية.","Gerechtsdeurwaarder: de enige die officiële stukken mag betekenen en beslag mag leggen. Neem zijn brieven serieus.","debt-help-schuldhulp"),
("beslag / loonbeslag","بيسلاخ / لونبيسلاخ","حجز / حجز على الراتب","حجز على مالك أو جزء من راتبك أو إعانتك لسداد الدَّين.","Beslag op je bezittingen of op een deel van je loon of uitkering om een schuld te betalen.","debt-help-schuldhulp"),
("beslagvrije voet","بيسلاخفرايه فوت","الحد المحمي من الحجز","جزء من دخلك لا يجوز حجزه لتعيش منه. إن بدا خاطئاً، أبلغ المحضر.","Het deel van je inkomen dat niet in beslag genomen mag worden, zodat je kunt leven. Klopt het niet? Meld het bij de deurwaarder.","debt-help-schuldhulp"),
("dwangbevel","دفانخبيفيل","أمر تنفيذ إداري","أمر تحصيل تصدره جهات حكومية (مثل الضرائب أو البلدية) بعد الإنذار، ويسمح بالحجز دون محكمة.","Een invorderingsbesluit van bijvoorbeeld de Belastingdienst of gemeente na een aanmaning; daarmee kan beslag volgen zonder rechter.","debt-help-schuldhulp"),
("schuldhulpverlening","سخولدهولبفيرلينينخ","مساعدة الديون","مساعدة <strong>مجانية</strong> من البلدية لترتيب ديونك.","<strong>Gratis</strong> hulp van de gemeente bij schulden.","debt-help-schuldhulp"),
("automatische incasso","أوتوماتيسه إنكاسو","الخصم التلقائي","إذن لجهة بسحب المبلغ من حسابك تلقائياً. تأكد أن الرصيد يكفي.","Toestemming om bedragen automatisch van je rekening af te schrijven. Zorg dat er genoeg saldo is.",None),
("CJIB","سي يي إي بي","مكتب التحصيل المركزي","يحصّل الغرامات المرورية وبعض الديون الحكومية.","Centraal Justitieel Incassobureau: int verkeersboetes en andere overheidsvorderingen.","traffic-fines-cjib"),
]),
('family','الأسرة','Gezin',[
("kinderbijslag","كندربايسلاخ","مخصصات الأطفال","مبلغ من SVB لتكاليف تربية الأطفال، لا يعتمد على دخلك.","Bijdrage van de SVB in de kosten van kinderen, niet afhankelijk van je inkomen.","kinderbijslag-guide"),
("SVB","إس في بي","بنك التأمينات الاجتماعية","الجهة التي تدفع kinderbijslag والتقاعد الحكومي (AOW).","Sociale Verzekeringsbank: betaalt kinderbijslag en AOW.","aow-aio-pension"),
("geboorteaangifte","خيبورتهآنخيفته","تسجيل المولود","تسجيل ولادة الطفل لدى البلدية خلال المهلة القانونية القصيرة.","De geboorte van een kind melden bij de gemeente, binnen de korte wettelijke termijn.","birth-parental-leave"),
("erkenning","إيركينينخ","الاعتراف بالأبوة","إن لم تكونا متزوجين أو شريكين مسجلين، يحتاج الأب أن يعترف بالطفل ليكون أباً قانونياً.","Als ouders niet getrouwd of geregistreerd partner zijn, moet de vader het kind erkennen om juridisch vader te zijn.","birth-parental-leave"),
("gezag","خيزاخ","الولاية / السلطة الأبوية","الحق القانوني في اتخاذ قرارات عن الطفل. مع الاعتراف لا يأتي دائماً تلقائياً.","Het recht om beslissingen over een kind te nemen. Erkenning geeft niet altijd automatisch gezag.","birth-parental-leave"),
("geregistreerd partnerschap","خيريخيستريرد بارتنرسخاب","الشراكة المسجلة","شكل رسمي للعلاقة مشابه للزواج في معظم الحقوق.","Officiële relatievorm die op de meeste punten lijkt op het huwelijk.",None),
("alimentatie","أليمينتاتسيه","النفقة","مبلغ يدفعه أحد الوالدين أو الشريك السابق بعد الانفصال.","Geld dat een ouder of ex-partner na een scheiding betaalt.","single-parent-support"),
("kinderopvang","كندرأوبفانخ","حضانة الأطفال","رعاية الأطفال أثناء عمل الوالدين؛ قد تحق لك إعانة.","Opvang van kinderen terwijl ouders werken; soms recht op toeslag.","childcare-allowance-kinderopvangtoeslag"),
("zwangerschapsverlof / ouderschapsverlof","زفانخرسخابسفيرلوف / آودرسخابسفيرلوف","إجازة الحمل والولادة / الإجازة الوالدية","إجازات مرتبطة بالحمل ورعاية الطفل، لها قواعد ومدد خاصة.","Verlof rond zwangerschap en bevalling, en verlof om voor je kind te zorgen.","birth-parental-leave"),
]),
]

def _link_ar(s): return f' <a href="/articles/{s}.html">الدليل</a>' if s else ''
def _link_nl(s): return f' <a href="/nl/articles/{s}.html">gids</a>' if s else ''
def _ar_table(terms): return T([[f'<strong>{d}</strong>',p,m,a+_link_ar(s)] for d,p,m,a,n,s in terms],['المصطلح','النطق','المعنى','ماذا يعني لك'])
def _nl_table(terms): return T([[f'<strong>{d}</strong>',m,n+_link_nl(s)] for d,p,m,a,n,s in terms],['Begrip','Arabisch','Uitleg in eenvoudig Nederlands (B1)'])
N_TERMS=sum(len(t[3]) for t in THEMES)
_ar_toc='<ul>'+''.join(f'<li><a href="#{i}">{a}</a> ({len(t)})</li>' for i,a,n,t in THEMES)+'</ul>'
_nl_toc='<ul>'+''.join(f'<li><a href="#{i}">{n}</a> ({len(t)})</li>' for i,a,n,t in THEMES)+'</ul>'
_ar_themes=''.join(f'<h2 id="{i}">{a}</h2>'+_ar_table(t) for i,a,n,t in THEMES)
_nl_themes=''.join(f'<h2 id="{i}">{n}</h2>'+_nl_table(t) for i,a,n,t in THEMES)

AR=dict(title=f'قاموس المصطلحات الحكومية الهولندية بالعربي: {N_TERMS} كلمة من الرسائل والمواقع الرسمية مع النطق والمعنى وماذا تفعل',
crumb='قاموس المصطلحات الحكومية',
desc=f'قاموس عربي–هولندي لـ{N_TERMS} مصطلحاً تجدها في رسائل الحكومة: beschikking وbezwaar (اعتراض خلال 6 أسابيع) وberoep وaanmaning وkenmerk وvoorschot والحساب النهائي وterugvordering، مع مصطلحات الإعانات والضرائب وUWV والسكن والصحة والتعليم والـIND والبلدية والديون والأسرة. لكل كلمة نطق تقريبي بالحروف العربية، معناها، وماذا تعني لك عملياً، وكيف تقرأ رسالة رسمية خطوة بخطوة.',
summary=f'<ol><li>هذا القاموس يضم <strong>{N_TERMS} مصطلحاً</strong> في 11 مجموعة، لكل منها <strong>نطق تقريبي بالعربي</strong> (مثل toeslag = توسلاخ) ومعنى وشرح عملي ورابط للدليل المناسب.</li><li><strong>bezwaar</strong> = اعتراض لدى نفس الجهة، عادة خلال <strong>6 أسابيع</strong>، مجاني. <strong>beroep</strong> = طعن أمام المحكمة بعد رفض الاعتراض، عادة خلال 6 أسابيع أيضاً.</li><li><strong>voorschot</strong> دفعة مقدمة غير نهائية؛ بعد السنة يأتي <strong>الحساب النهائي</strong> (definitieve berekening) الذي قد يعني <strong>terugvordering</strong> (إرجاع) أو <strong>nabetaling</strong> (دفعة إضافية).</li><li><strong>herinnering</strong> تذكير، و<strong>aanmaning</strong> إنذار؛ لا يجوز لمكتب التحصيل فرض تكاليف قبل رسالة تمنحك <strong>14 يوماً</strong>، ووحده <strong>المحضر (deurwaarder)</strong> يحجز.</li><li>في كل رسالة: انظر إلى <strong>التاريخ</strong> و<strong>kenmerk</strong> و<strong>المهلة</strong> وما المطلوب منك، واحتفظ بنسخة.</li></ol>',
body=(
'<h2 id="how">كيف تستخدم هذا القاموس؟</h2><p>الرسائل الحكومية الهولندية تستخدم كلمات ثابتة تتكرر. إن فهمت هذه الكلمات فهمت معظم الرسالة. النطق المكتوب بالحروف العربية <strong>تقريبي</strong>: حرف g في الهولندية يُنطق قريباً من «خ»، وoe مثل «و» الطويلة، وij وei مثل «اي»، وw قريبة من «ف/و». كتبنا النطق كما يكتبه الناس عادة حين يبحثون.</p><p>المجموعات:</p>'
+_ar_toc
+'<h2 id="read-letter">كيف تقرأ رسالة رسمية في 7 خطوات</h2><ol><li><strong>من المرسل؟</strong> الشعار والعنوان في الأعلى. تأكد أن الرسالة حقيقية: لا تدفع عبر رابط في SMS أو واتساب، وادخل بنفسك إلى الموقع الرسمي. انظر <a href="/articles/scams-phishing-netherlands.html">دليل الاحتيال</a>.</li><li><strong>التاريخ (datum / dagtekening)</strong>: اكتبه على ورقة. كثير من المهل تبدأ منه لا من يوم وصول الرسالة.</li><li><strong>رقم المرجع (kenmerk)</strong>: «ons kenmerk» هو رقم ملفك عندهم. ستحتاجه في كل اتصال. وقد تجد أيضاً BSN أو رقم الدفع (betalingskenmerk).</li><li><strong>الموضوع (onderwerp / betreft)</strong>: سطر قصير يقول عن ماذا الرسالة.</li><li><strong>القرار</strong>: ابحث عن «Wij hebben besloten» (قررنا) أو «U krijgt» (تحصل على) أو «U moet … terugbetalen» (يجب أن تعيد).</li><li><strong>المهلة (termijn)</strong>: ابحث عن «binnen … weken» (خلال … أسابيع)، «vóór» (قبل تاريخ)، «uiterlijk» (في موعد أقصاه).</li><li><strong>ماذا عليك أن تفعل؟</strong> فقرة «Wat moet u doen?» أو «U hoeft niets te doen» (لا يلزمك فعل شيء). وفي آخر الرسالة غالباً فقرة «Bent u het niet eens?» تشرح كيف تعترض وإلى أين.</li></ol>'
+T([['Wij hebben besloten','قررنا','هنا القرار نفسه؛ اقرأه بتمعن.'],['U hoeft niets te doen','لا يلزمك فعل شيء','للعلم فقط؛ لكن تحقق من الأرقام.'],['Wij verzoeken u…','نطلب منك…','طلب يجب تنفيذه، غالباً مع مهلة.'],['binnen 6 weken na de datum van deze brief','خلال 6 أسابيع من تاريخ الرسالة','العدّ يبدأ من التاريخ المطبوع.'],['uiterlijk / vóór','في موعد أقصاه / قبل','آخر يوم مقبول.'],['Bent u het niet eens met dit besluit?','هل أنت غير موافق على القرار؟','هنا طريقة الاعتراض (bezwaar) ومهلته.'],['Stuur ons de volgende gegevens','أرسل لنا البيانات التالية','قائمة أوراق مطلوبة؛ إن تأخرت قد يُرفض الطلب أو تتوقف الإعانة.'],['Let op','انتبه','معلومة مهمة جداً.'],['Heeft u vragen?','هل لديك أسئلة؟','رقم الهاتف وطريقة التواصل.']],['العبارة في الرسالة','الترجمة','ماذا تفعل'])
+'<h2 id="examples">ثلاث رسائل وكيف تفهمها</h2><p><strong>أمثلة توضيحية وليست حالات أشخاص حقيقيين.</strong></p>'
+T([['«Voorschotbeschikking huurtoeslag» تصل في ديسمبر، وفيها دخل متوقع أقل من دخلك الحقيقي الجديد','هذا قرار الدفعة المقدمة (voorschot). الدخل المكتوب تقديري.','غيّر الدخل في Mijn toeslagen فوراً، لتقل مخاطر terugvordering لاحقاً.'],['«Definitieve berekening zorgtoeslag»: «U moet € … terugbetalen»','الحساب النهائي بعد معرفة دخلك الحقيقي، والنتيجة مطالبة بالإرجاع.','تحقق من الدخل. إن كان خطأً: bezwaar خلال المهلة. إن كان صحيحاً ولا تستطيع الدفع مرة واحدة: اطلب betalingsregeling.'],['رسالة من مكتب تحصيل: «laatste aanmaning» مع incassokosten','إنذار بالدفع مع تكاليف تحصيل.','هل وصلتك قبلها رسالة بمهلة 14 يوماً؟ إن لا، اسأل عن التكاليف. اتصل للاتفاق على تقسيط، واطلب مساعدة الديون المجانية من البلدية.']],['الرسالة','ماذا تعني','الخطوة الصحيحة'])
+_ar_themes
+'<h2 id="steps">رسالة لا تفهمها؟ هكذا تتصرف</h2><ol><li>لا تتركها في الدرج. صوّرها فوراً واحفظ الصورة.</li><li>استخرج <strong>التاريخ والكلمات المفتاحية</strong> من هذا القاموس.</li><li>احسب <strong>المهلة</strong> واكتب آخر يوم في تقويم هاتفك.</li><li>إن كانت المهلة قريبة ولا تفهم القرار: اتصل بالجهة واذكر <strong>kenmerk</strong>، أو اطلب مساعدة مجانية (القسم التالي).</li><li>إن كنت غير موافق: أرسل <strong>bezwaar</strong> في الوقت، حتى لو قصيراً، ويمكنك إكمال الأسباب لاحقاً. انظر <a href="/articles/bezwaar-objection-letter.html">دليل رسالة الاعتراض</a>.</li><li>احتفظ بنسخة من كل ما ترسله، وبإشعار الاستلام (ontvangstbevestiging).</li></ol>'
+'<h2 id="mistakes">أخطاء شائعة</h2><ol><li><strong>الخلط بين bezwaar وklacht</strong>: الشكوى لا توقف القرار ولا تغيّره؛ للقرار تحتاج اعتراضاً.</li><li><strong>حساب المهلة من يوم القراءة</strong> بدل تاريخ الرسالة.</li><li><strong>اعتبار الـvoorschot نهائياً</strong> وإنفاقه، ثم مفاجأة الإرجاع.</li><li><strong>عدم فتح Berichtenbox</strong> بعد تفعيلها؛ الرسالة تُعد واصلة.</li><li><strong>إعطاء كلمة سر DigiD لقريب أو «مكتب»</strong> بدل استخدام DigiD Machtigen.</li><li><strong>نسخ رقم الدفع خطأً</strong> فيبقى الدَّين مفتوحاً وتزيد التكاليف.</li><li><strong>تجاهل رسائل المحضر (deurwaarder)</strong>؛ هو الوحيد الذي يستطيع الحجز.</li><li><strong>الاعتماد على ترجمة آلية لكلمة واحدة</strong>: termijn مثلاً قد تعني «مهلة» أو «قسطاً».</li></ol>'
+'<h2 id="help">أين تجد مساعدة مجانية في فهم الرسائل؟</h2><ul><li><strong>Juridisch Loket</strong>: نصيحة قانونية مجانية، ومفيد في الاعتراض والطعن. انظر <a href="/articles/legal-aid-lawyer-toevoeging.html">المساعدة القانونية</a>.</li><li><strong>البلدية</strong>: كثير من البلديات لديها sociaal raadslid أو Formulierenbrigade أو فريق الحي (wijkteam) لمساعدتك بالأوراق مجاناً.</li><li><strong>Informatiepunt Digitale Overheid</strong> في كثير من المكتبات العامة (bibliotheek): مساعدة في DigiD والمواقع الحكومية.</li><li><strong>مساعدة الديون</strong> من البلدية: <a href="/articles/debt-help-schuldhulp.html">مساعدة الديون المجانية</a>.</li><li><strong>الجهة نفسها</strong>: اتصل واذكر kenmerk، واطلب أن يشرحوا ببطء أو بلغة أبسط.</li><li>للاجئين: VluchtelingenWerk في منطقتك.</li></ul>'
+'<h2 id="related">أدلة مرتبطة</h2><ul><li><a href="/articles/bezwaar-objection-letter.html">كيف تكتب رسالة اعتراض (bezwaar)</a></li><li><a href="/articles/toeslagen-income-update.html">تحديث الدخل في toeslagen</a></li><li><a href="/articles/digid-registration-guide.html">DigiD</a></li><li><a href="/articles/debt-help-schuldhulp.html">مساعدة الديون المجانية</a></li><li><a href="/articles/scams-phishing-netherlands.html">رسائل الاحتيال</a></li><li><a href="/articles/annual-tax-return-2026.html">الإقرار الضريبي السنوي</a></li></ul>'),
faq=[('ما الفرق بين beschikking وbesluit؟','besluit هو أي قرار حكومي، وbeschikking قرار مكتوب يخصك أنت شخصياً (مثل مبلغ إعانتك). يمكنك الاعتراض على beschikking.'),
('ما الفرق بين bezwaar وberoep؟','bezwaar اعتراض لدى نفس الجهة التي أصدرت القرار، عادة خلال 6 أسابيع. beroep طعن أمام المحكمة الإدارية بعد رفض اعتراضك، عادة خلال 6 أسابيع أيضاً.'),
('هل bezwaar مكلف؟','لا، الاعتراض مجاني ولا يحتاج محامياً. أما الطعن أمام المحكمة (beroep) فغالباً عليه رسوم محكمة (griffierecht).'),
('ما معنى herinnering وaanmaning؟','herinnering تذكير بأن عليك شيئاً، وaanmaning إنذار رسمي بالدفع يأتي بعده وقد تُضاف معه تكاليف.'),
('ماذا يعني voorschot في toeslagen؟','دفعة مقدمة شهرية مبنية على دخل تقديري. ليست نهائية؛ بعد السنة يأتي الحساب النهائي وقد تُطالب بإرجاع جزء.'),
('ما معنى terugvordering وnabetaling؟','terugvordering: يجب أن تعيد ما أخذته زيادة. nabetaling: تحصل على مبلغ إضافي لأن حقك كان أكبر.'),
('ما هو kenmerk ولماذا مهم؟','رقم مرجع ملفك في الرسالة. اذكره في كل اتصال أو رد أو دفع، حتى يربطوا رسالتك بملفك.'),
('هل يمكن لأحد أن يرتب أموري الحكومية بدلاً مني؟','نعم عبر DigiD Machtigen، تعطي شخصاً أو جهة تفويضاً رسمياً. لا تعطِ كلمة سر DigiD لأحد.'),
('ما الفرق بين incassobureau وdeurwaarder؟','مكتب التحصيل يطالب بالدفع فقط، ولا يحق له حجز راتبك أو أغراضك. المحضر القضائي (deurwaarder) وحده يستطيع تبليغ أوراق المحكمة وتنفيذ الحجز.'),
('لماذا كتبتم النطق بالحروف العربية؟','لأن كثيرين يبحثون عن الكلمة كما يسمعونها، مثل «توسلاخ» أو «بيزوار». النطق تقريبي فقط، والكلمة الصحيحة هي المكتوبة بالحروف اللاتينية.')],
src_note='راجعنا Rijksoverheid والقضاء الهولندي (Rechtspraak) وBelastingdienst/Toeslagen وMijnOverheid وDigiD وIND في 7 أكتوبر 2026. التعريفات مبسطة لأغراض الفهم وليست نصوصاً قانونية؛ المهلة الدقيقة وطريقة الاعتراض مذكورتان دائماً في رسالتك. لم نذكر مبالغ (مثل التحمل الذاتي أو حدود الإعانات أو الكفالة) لأنها تتغير سنوياً؛ تجدها في الأدلة المرتبطة. النطق بالحروف العربية تقريبي. الأمثلة توضيحية.')

NL=dict(title=f'Overheidstaal uitgelegd: {N_TERMS} begrippen uit brieven van de overheid, in eenvoudig Nederlands en met het Arabische woord',
crumb='Woordenlijst overheidstaal',
desc=f'Woordenlijst Nederlands–Arabisch met {N_TERMS} begrippen uit overheidsbrieven, in eenvoudig Nederlands (B1) voor vrijwilligers en hulpverleners: beschikking, bezwaar (binnen 6 weken), beroep, aanmaning, kenmerk, voorschot, definitieve berekening, terugvordering, plus toeslagen, belasting, UWV, wonen, zorg, onderwijs, IND, gemeente, schulden en gezin. Met een stappenplan om een officiële brief samen te lezen.',
summary=f'<ol><li><strong>{N_TERMS} begrippen</strong> in 11 thema’s, telkens met het <strong>Arabische woord</strong>, een uitleg in <strong>eenvoudig Nederlands (B1)</strong> en een link naar de gids.</li><li><strong>Bezwaar</strong> = dezelfde organisatie vragen het besluit opnieuw te bekijken, meestal binnen <strong>6 weken</strong>, gratis. <strong>Beroep</strong> = daarna naar de rechtbank, meestal ook binnen 6 weken.</li><li>Een <strong>voorschot</strong> is niet definitief; na het jaar volgt de <strong>definitieve berekening</strong>, met mogelijk een <strong>terugvordering</strong> of <strong>nabetaling</strong>.</li><li>Een incassobureau mag pas kosten rekenen na een brief met <strong>14 dagen</strong> betaaltermijn; alleen een <strong>deurwaarder</strong> mag beslag leggen.</li><li>Lees elke brief op: <strong>datum</strong>, <strong>kenmerk</strong>, <strong>termijn</strong> en <strong>wat moet ik doen</strong>.</li></ol>',
body=(
'<h2 id="how">Voor wie is deze lijst?</h2><p>Deze woordenlijst is bedoeld voor <strong>vrijwilligers, taalmaatjes, buren en hulpverleners</strong> die Arabischsprekende nieuwkomers helpen met post van de overheid. Ambtelijke brieven gebruiken steeds dezelfde woorden. Als je het Arabische woord erbij noemt, begrijpt de ander sneller wat er bedoeld wordt. Op de Arabische versie van deze pagina staat bij elk begrip ook de uitspraak in Arabisch schrift (bijvoorbeeld ‘toeslag’ = توسلاخ), omdat mensen woorden vaak zo opzoeken.</p><p><strong>Tips voor helpers:</strong> spreek langzaam, gebruik één begrip tegelijk, laat de ander in eigen woorden herhalen wat de brief vraagt, en neem beslissingen niet over: help de persoon zelf te kiezen. Gebruik <strong>DigiD Machtigen</strong> als je iets online voor iemand regelt; vraag nooit iemands DigiD-wachtwoord.</p><p>Thema’s:</p>'
+_nl_toc
+'<h2 id="read-letter">Een officiële brief lezen in 7 stappen</h2><ol><li><strong>Wie is de afzender?</strong> Logo en adres bovenaan. Is de brief echt? Nooit betalen via een link in sms of WhatsApp; ga zelf naar de officiële website. Zie <a href="/nl/articles/scams-phishing-netherlands.html">Oplichting en phishing</a>.</li><li><strong>Datum (dagtekening)</strong>: schrijf die op. Veel termijnen tellen vanaf deze datum, niet vanaf de dag van ontvangst.</li><li><strong>Kenmerk</strong>: ‘ons kenmerk’ is het dossiernummer van de organisatie. Nodig bij elk contact. Soms staan er ook een BSN en een betalingskenmerk.</li><li><strong>Onderwerp (betreft)</strong>: waar gaat de brief over?</li><li><strong>Het besluit</strong>: zoek zinnen als ‘Wij hebben besloten’, ‘U krijgt’ of ‘U moet … terugbetalen’.</li><li><strong>Termijn</strong>: ‘binnen … weken’, ‘vóór [datum]’, ‘uiterlijk’.</li><li><strong>Wat moet u doen?</strong> Of juist ‘U hoeft niets te doen’. Onderaan staat vaak ‘Bent u het niet eens?’ met uitleg over bezwaar.</li></ol>'
+T([['Wij hebben besloten','قررنا','Hier staat het besluit zelf; samen rustig lezen.'],['U hoeft niets te doen','لا يلزمك فعل شيء','Alleen ter informatie; controleer wel de bedragen.'],['Wij verzoeken u…','نطلب منك…','Een opdracht, meestal met een termijn.'],['binnen 6 weken na de datum van deze brief','خلال 6 أسابيع من تاريخ الرسالة','Tellen vanaf de datum op de brief.'],['uiterlijk / vóór','في موعد أقصاه / قبل','Laatste dag waarop het nog kan.'],['Bent u het niet eens met dit besluit?','هل أنت غير موافق على القرار؟','Hier staat hoe en waar je bezwaar maakt.'],['Stuur ons de volgende gegevens','أرسل لنا البيانات التالية','Lijst met stukken; te laat kan betekenen: afwijzing of stopzetting.'],['Let op','انتبه','Belangrijke informatie.'],['Heeft u vragen?','هل لديك أسئلة؟','Telefoonnummer en contactmogelijkheden.']],['Zin in de brief','Arabisch','Wat betekent het voor de lezer?'])
+'<h2 id="examples">Drie brieven samen lezen</h2><p><strong>Illustratief, geen echte personen.</strong></p>'
+T([['‘Voorschotbeschikking huurtoeslag’ in december, met een geschat inkomen dat lager is dan het nieuwe echte inkomen','Besluit over het voorschot; het inkomen is een schatting.','Samen het inkomen aanpassen in Mijn toeslagen, zodat een terugvordering later kleiner wordt.'],['‘Definitieve berekening zorgtoeslag’: ‘U moet € … terugbetalen’','De definitieve berekening na het jaar, met een terugvordering.','Inkomen controleren. Fout? Bezwaar binnen de termijn. Klopt het maar lukt betalen niet? Betalingsregeling aanvragen.'],['Brief van een incassobureau: ‘laatste aanmaning’ met incassokosten','Betalingsaanmaning met extra kosten.','Was er eerst een brief met 14 dagen betaaltermijn? Zo niet, vraag naar de kosten. Bel voor een regeling en verwijs naar gratis schuldhulp van de gemeente.']],['Brief','Wat betekent het?','Goede vervolgstap'])
+_nl_themes
+'<h2 id="steps">Stappenplan bij een onduidelijke brief</h2><ol><li>Laat de brief niet liggen; maak direct een foto.</li><li>Zoek de <strong>datum</strong> en de <strong>kernwoorden</strong> op in deze lijst.</li><li>Bereken de <strong>termijn</strong> en zet de laatste dag in de agenda van de telefoon.</li><li>Termijn dichtbij en besluit onduidelijk? Bel de organisatie met het <strong>kenmerk</strong> erbij, of zoek gratis hulp (zie hieronder).</li><li>Niet eens? Stuur op tijd <strong>bezwaar</strong>, desnoods kort; de redenen kunnen later worden aangevuld. Zie <a href="/nl/articles/bezwaar-objection-letter.html">Bezwaar maken</a>.</li><li>Bewaar een kopie van alles wat je verstuurt, en de ontvangstbevestiging.</li></ol>'
+'<h2 id="mistakes">Veelgemaakte fouten</h2><ol><li><strong>Klacht en bezwaar door elkaar halen</strong>: een klacht verandert het besluit niet.</li><li><strong>Termijn tellen vanaf de dag van lezen</strong> in plaats van de datum op de brief.</li><li><strong>Het voorschot als definitief zien</strong> en uitgeven; daarna schrikken van een terugvordering.</li><li><strong>De Berichtenbox niet openen</strong> terwijl die aanstaat; de brief geldt als ontvangen.</li><li><strong>Het DigiD-wachtwoord aan familie of een ‘kantoortje’ geven</strong> in plaats van DigiD Machtigen te gebruiken.</li><li><strong>Een betalingskenmerk verkeerd overnemen</strong>, waardoor de schuld openblijft.</li><li><strong>Brieven van de deurwaarder negeren</strong>; alleen hij mag beslag leggen.</li><li><strong>Eén woord letterlijk vertalen</strong>: ‘termijn’ kan ‘deadline’ of ‘deelbetaling’ betekenen.</li></ol>'
+'<h2 id="help">Waar vind je gratis hulp?</h2><ul><li><strong>Juridisch Loket</strong>: gratis juridisch advies, ook bij bezwaar en beroep. Zie <a href="/nl/articles/legal-aid-lawyer-toevoeging.html">Rechtshulp en toevoeging</a>.</li><li><strong>Gemeente</strong>: veel gemeenten hebben een sociaal raadslid, Formulierenbrigade of wijkteam dat gratis helpt met post.</li><li><strong>Informatiepunt Digitale Overheid</strong> in veel bibliotheken: hulp bij DigiD en overheidswebsites.</li><li><strong>Schuldhulp</strong> van de gemeente: <a href="/nl/articles/debt-help-schuldhulp.html">Gratis schuldhulp</a>.</li><li><strong>De organisatie zelf</strong>: bel met het kenmerk en vraag om rustige of eenvoudige uitleg.</li><li>Voor statushouders: VluchtelingenWerk in de regio.</li></ul>'
+'<h2 id="related">Gerelateerde gidsen</h2><ul><li><a href="/nl/articles/bezwaar-objection-letter.html">Bezwaar maken: zo schrijf je een bezwaarschrift</a></li><li><a href="/nl/articles/toeslagen-income-update.html">Inkomen doorgeven bij toeslagen</a></li><li><a href="/nl/articles/digid-registration-guide.html">DigiD aanvragen</a></li><li><a href="/nl/articles/debt-help-schuldhulp.html">Gratis schuldhulp</a></li><li><a href="/nl/articles/scams-phishing-netherlands.html">Oplichting en phishing</a></li><li><a href="/nl/articles/annual-tax-return-2026.html">Aangifte inkomstenbelasting</a></li></ul>'),
faq=[('Wat is het verschil tussen een besluit en een beschikking?','Besluit is het algemene woord voor een beslissing van de overheid. Een beschikking is een schriftelijk besluit over één persoon, zoals de hoogte van een toeslag. Daartegen kun je bezwaar maken.'),
('Wat is het verschil tussen bezwaar en beroep?','Bezwaar maak je bij de organisatie die het besluit nam, meestal binnen 6 weken. Beroep stel je in bij de rechtbank nadat je bezwaar is afgewezen, meestal ook binnen 6 weken.'),
('Kost bezwaar maken geld?','Nee, bezwaar is gratis en je hebt geen advocaat nodig. Voor beroep bij de rechtbank betaal je meestal griffierecht.'),
('Wat is het verschil tussen een herinnering en een aanmaning?','Een herinnering wijst erop dat iets nog moet gebeuren. Een aanmaning is een formele betalingsaanmaning daarna, soms met extra kosten.'),
('Wat betekent voorschot bij toeslagen?','Een maandelijks bedrag op basis van een geschat inkomen. Het is niet definitief; na het jaar volgt de definitieve berekening.'),
('Wat betekenen terugvordering en nabetaling?','Terugvordering: je hebt te veel gekregen en betaalt terug. Nabetaling: je had recht op meer en krijgt het verschil.'),
('Waarom is het kenmerk belangrijk?','Het is het dossiernummer. Noem het bij elk telefoontje, elke brief en elke betaling, zodat alles bij het juiste dossier komt.'),
('Mag ik als vrijwilliger iemands zaken online regelen?','Ja, als de persoon je machtigt via DigiD Machtigen. Vraag nooit om iemands DigiD-inloggegevens.'),
('Wat is het verschil tussen een incassobureau en een deurwaarder?','Een incassobureau vraagt om betaling maar mag geen beslag leggen. Alleen een gerechtsdeurwaarder mag officiële stukken betekenen en beslag leggen.'),
('Waarom staat op de Arabische pagina de uitspraak in Arabisch schrift?','Veel mensen zoeken woorden zoals ze ze horen, bijvoorbeeld ‘توسلاخ’ voor toeslag. De uitspraak is een benadering; de juiste spelling blijft de Nederlandse.')],
src_note='Gecontroleerd bij Rijksoverheid, de Rechtspraak, Belastingdienst/Toeslagen, MijnOverheid, DigiD en de IND op 7 oktober 2026. De uitleg is vereenvoudigd en geen juridische tekst; de precieze termijn en bezwaarmogelijkheid staan altijd in de brief zelf. Bedragen (zoals eigen risico, toeslaggrenzen of borg) zijn bewust weggelaten omdat ze jaarlijks veranderen; zie de gekoppelde gidsen. Voorbeelden illustratief.')
