from a_student_finance import T
SLUG='health-insurance-newcomers'
SRC=[('Rijksoverheid · Moet ik een zorgverzekering afsluiten als ik in Nederland ga werken?','https://www.rijksoverheid.nl/vraag-en-antwoord/immigratie-naar-nederland/moet-ik-een-zorgverzekering-afsluiten-als-ik-in-nederland-ga-werken'),
('Rijksoverheid · Wat gebeurt er als ik niet verzekerd ben?','https://www.rijksoverheid.nl/vraag-en-antwoord/zorgverzekering/wat-gebeurt-er-als-ik-niet-verzekerd-ben-voor-de-zorgverzekering'),
('Rijksoverheid · Wanneer betaal ik een eigen risico?','https://www.rijksoverheid.nl/vraag-en-antwoord/zorgverzekering/eigen-risico-zorgverzekering'),
('Zorginstituut Nederland · Eigen risico (Zvw)','https://www.zorginstituutnederland.nl/verzekerde-zorg/e/eigen-risico-zvw'),
('Rijksoverheid · Wat moet ik regelen als ik in Nederland kom wonen?','https://www.rijksoverheid.nl/vraag-en-antwoord/immigratie-naar-nederland/wat-moet-ik-regelen-als-ik-in-nederland-kom-wonen')]
AR=dict(title='التأمين الصحي عند الوصول إلى هولندا: المهل، الغرامات، الإيجار الذاتي، وماذا تفعل أولاً',
crumb='التأمين الصحي للقادمين الجدد',
seo_title='التأمين الصحي zorgverzekering للقادمين',
desc='التأمين الصحي الإلزامي (zorgverzekering) للقادمين الجدد: مهلة 4 أشهر عند العمل، رسالة CAK و3 أشهر قبل الغرامة، وeigen risico بقيمة 385 يورو في 2026.',
summary='<ol><li>من يعمل في هولندا لدى صاحب عمل هولندي بشكل منتظم ويدفع ضريبة الأجور <strong>ملزم</strong> بتأمين صحي أساسي، ولديه <strong>4 أشهر</strong> على الأقل لعقده وفق الحكومة.</li><li>من يعيش في هولندا دون عمل يسجّل في البلدية، ثم تحدد <strong>SVB</strong> هل هو مؤمَّن.</li><li>إن لم تتأمّن يرسل <strong>CAK</strong> رسالة، ولديك <strong>3 أشهر</strong> للتأمين أو إثبات الإعفاء، وإلا فغرامة ثم تسجيل إجباري.</li><li>الـ<strong>eigen risico</strong> في 2026 هو <strong>385 يورو</strong>؛ والأطفال دون 18 لا يدفعون قسطاً ولا eigen risico.</li><li>قد تستحق <strong>zorgtoeslag</strong> إن كان دخلك منخفضاً (<a href="/articles/zorgtoeslag-guide.html">الدليل</a>).</li></ol>',
body=(
'<h2 id="who">هل أنا ملزم؟</h2><p>الحالات التي تحددها الحكومة:</p><ul><li><strong>تعمل في هولندا:</strong> إن كان لك صاحب عمل هولندي، وتعمل بشكل ثابت، وتدفع ضريبة الأجور، فعليك تأميناً صحياً هولندياً أساسياً. المهلة على الأقل <strong>4 أشهر</strong>. وهذا ينطبق ولو لم تكن تسكن في هولندا.</li><li><strong>تسكن ولا تعمل:</strong> سجّل في البلدية (<a href="/articles/bsn-municipality-registration.html">التسجيل وBSN</a>)، وتحدد هيئة التأمينات الاجتماعية <strong>SVB</strong> هل أنت مؤمَّن بحسب وضعك.</li><li><strong>لدى صاحب عمل أجنبي:</strong> قد تحتفظ بتأمين بلدك بقواعد معينة؛ راجع SVB.</li><li><strong>طالب أجنبي:</strong> قد يكون لديك تأمين في بلدك، وأحياناً يلزم تأمين هولندي. تحقق في SVB.</li><li><strong>طالب لجوء:</strong> تسري قواعد مختلفة (<a href="/articles/asylum-family-reunification.html">دليل اللجوء</a>).</li></ul>'
'<h2 id="deadline">المهل: ماذا يحدث بعد 4 أشهر؟</h2><p>إن أبرمت التأمين بعد أكثر من 4 أشهر فأنت <strong>غير مؤمَّن</strong> في المدة السابقة: تدفع تكاليف العلاج بنفسك. تبدأ دفع القسط من لحظة إبرام العقد، ومنه يُغطّى العلاج من الحزمة الأساسية. القسط <strong>لا يُطلب بأثر رجعي</strong>، لكنك تتحمل أي علاج حصل قبل التأمين.</p>'
'<p>ولا تتأخر: بمجرد أن تسجّل في البلدية دون تأمين، تصلك رسالة من <strong>CAK</strong>، الجهة التي تتأكد أن الجميع مؤمَّن.</p>'
'<h2 id="cak">رسالة CAK والغرامات</h2><ol><li>تصلك رسالة: لديك <strong>3 أشهر</strong> لعقد تأمين أو إثبات أنك لست ملزماً (مثل اعتراض ضمير).</li><li>إن لم تفعل: <strong>غرامة</strong>.</li><li>بعد غرامتين: يسجّلك CAK لدى شركة تأمين، ويخصم القسط من دخلك <strong>12 شهراً</strong> بما يسمى bestuursrechtelijke premie، وهي <strong>110%</strong> من القسط القياسي. إن لم يكن لديك دخل ثابت تصلك فاتورة.</li></ol><p>خلاصة: التأخير لا يوفر مالاً؛ يعرّضك لعلاج غير مغطى ثم لقسط أعلى.</p>'
'<h2 id="steps">خطوات عملية للقادم الجديد</h2><ol><li>احصل على BSN وسجّل في البلدية.</li><li>قارن بين شركات التأمين: الحزمة الأساسية متطابقة قانونياً، والفرق في القسط وطريقة السداد وملحقات (aanvullend) اختيارية. ولا نقدم هنا رقماً لمتوسط القسط لأننا لم نتحقق منه من مصدر رسمي.</li><li>تذكّر أن الـ <strong>eigen risico</strong> الإلزامي مبلغ قانوني ثابت لا تختلف فيه الشركات (انظر أدناه).</li><li>سجّل لدى <a href="/articles/huisarts-registration.html">huisarts (طبيب الأسرة)</a>.</li><li>قدّم على <a href="/articles/zorgtoeslag-guide.html">zorgtoeslag</a> إن كان دخلك منخفضاً.</li><li>عند تغيير العنوان حدّث بياناتك (<a href="/articles/change-address-netherlands.html">تغيير العنوان</a>).</li></ol>'
'<h2 id="cost">الإيجار الذاتي eigen risico والحزمة</h2><p>الـ eigen risico الإلزامي لعام <strong>2026: 385 يورو</strong>. تدفع أول 385 يورو من تكاليف الرعاية الداخلة فيه، ثم تتحمل الشركة. مثال من Zorginstituut: إن دفعت 150 يورو سابقاً يبقى 235. <strong>تنبيه:</strong> eigen risico يختلف عن eigen bijdrage (مساهمة ذاتية في خدمات معينة).</p><ul><li>الحزمة الأساسية تشمل مثلاً: طبيب الأسرة، المستشفى، الطبيب النفسي، الصيدلية (بحسب الحكومة). وعن رعاية الحمل والولادة راجع <a href="/articles/pregnancy-newborn-care.html">دليل الحمل والولادة</a>.</li><li>تأمين الأسنان للبالغين غير مشمول عادة، وهو من التأمين التكميلي الاختياري.</li><li>الأطفال دون 18: <strong>لا قسط ولا eigen risico</strong>. من بلغ 18 يتأمّن بنفسه.</li></ul>'
'<h2 id="other">حالات خاصة</h2><ul><li><strong>أفراد الأسرة في بلد المنشأ:</strong> قد يحصلون على رعاية عبر تأمينك الهولندي بنموذج E-106 عبر شركة التأمين.</li><li><strong>رعاية طويلة الأمد:</strong> قانون Wlz يسري على من يسكن في هولندا.</li><li><strong>موظفو المؤسسات الأوروبية:</strong> نظام GSZV الخاص.</li></ul>'
'<h2 id="mistakes">أخطاء شائعة</h2><ul><li><strong>تجاهل رسالة CAK.</strong></li><li><strong>الاعتقاد أن التأمين الأجنبي يكفي دائماً.</strong> يتوقف على صاحب العمل والوضع.</li><li><strong>الخلط بين eigen risico وaanvullende verzekering.</strong></li><li><strong>نسيان أن البالغ 18 يلزمه عقد خاص.</strong></li><li><strong>عدم التقديم على zorgtoeslag.</strong></li></ul>'
'<p>للتحضير للعام القادم: <a href="/articles/health-insurance-2027.html">التأمين الصحي 2027</a>.</p>'),
faq=[('كم مهلة التأمين عند العمل؟','تقول الحكومة: في أي حال خلال 4 أشهر، حتى لو لم تسكن في هولندا.'),
('ماذا لو تأخرت؟','تكون غير مؤمَّن في مدة التأخير وتدفع العلاج بنفسك، وقد تصلك رسالة CAK ثم غرامات.'),
('كم eigen risico في 2026؟','385 يورو.'),
('هل يدفع الأطفال؟','لا قسط ولا eigen risico دون 18 سنة.'),
('هل التأمين التكميلي إلزامي؟','لا، والأسنان تدخل فيه عادة.')],
src_note='الأحكام والمهل وeigen risico من Rijksoverheid وZorginstituut Nederland، راجعناها في 4 أكتوبر 2026. لا نذكر متوسط القسط لأننا لم نتحقق منه. الحالات الخاصة (الطلاب، صاحب عمل أجنبي) تحددها SVB.')
NL=dict(title='Zorgverzekering voor nieuwkomers: termijnen, boetes, eigen risico en wat je eerst regelt',
crumb='Zorgverzekering nieuwkomers',
seo_title='Zorgverzekering nieuwkomers: termijn en boetes',
desc='Zorgverzekering voor nieuwkomers: binnen 4 maanden als je werkt, 3 maanden na een CAK-brief voordat een boete volgt, en eigen risico € 385 in 2026.',
summary='<ol><li>Wie in Nederland werkt voor een Nederlandse werkgever, vast werkt en loonbelasting betaalt, moet een basisverzekering afsluiten, volgens de overheid in elk geval binnen <strong>4 maanden</strong>.</li><li>Woon je hier zonder te werken, dan schrijf je je in bij de gemeente en bepaalt de <strong>SVB</strong> of je verzekerd bent.</li><li>Ben je niet verzekerd, dan stuurt het <strong>CAK</strong> een brief: je hebt <strong>3 maanden</strong> om een verzekering af te sluiten of vrijstelling aan te tonen, anders volgt een boete.</li><li>Het verplichte <strong>eigen risico</strong> is in 2026 <strong>€ 385</strong>; kinderen onder 18 betalen geen premie en geen eigen risico.</li><li>Bij een laag inkomen kun je <strong>zorgtoeslag</strong> krijgen (<a href="/nl/articles/zorgtoeslag-guide.html">gids</a>).</li></ol>',
body=(
'<h2 id="who">Moet ik me verzekeren?</h2><ul><li><strong>Je werkt in Nederland:</strong> heb je een Nederlandse werkgever, werk je op vaste basis en betaal je loonbelasting, dan is een Nederlandse basisverzekering verplicht. Je hebt in elk geval <strong>4 maanden</strong>, ook als je niet in Nederland woont.</li><li><strong>Je woont hier en werkt niet:</strong> schrijf je in bij de gemeente (<a href="/nl/articles/bsn-municipality-registration.html">inschrijving en bsn</a>); de <strong>SVB</strong> bepaalt of je verzekerd bent.</li><li><strong>Buitenlandse werkgever:</strong> mogelijk mag je je buitenlandse verzekering houden, met regels; kijk bij de SVB.</li><li><strong>Buitenlandse student:</strong> vaak al een verzekering in het eigen land, soms ook een Nederlandse nodig. Controleer bij de SVB.</li><li><strong>Asielzoekers:</strong> andere regels (<a href="/nl/articles/asylum-family-reunification.html">gids asiel</a>).</li></ul>'
'<h2 id="deadline">De termijn: wat na 4 maanden?</h2><p>Sluit je pas na 4 maanden af, dan ben je in de tussentijd <strong>onverzekerd</strong> en betaal je zorgkosten zelf. Je betaalt premie vanaf het moment dat je de verzekering afsluit; vanaf dan wordt zorg uit het basispakket vergoed. Premie hoef je <strong>niet met terugwerkende kracht</strong> te betalen, maar zorg uit de onverzekerde periode blijft voor jouw rekening.</p><p>Schrijf je je in bij de gemeente zonder verzekering, dan krijg je een brief van het <strong>CAK</strong>.</p>'
'<h2 id="cak">CAK-brief en boetes</h2><ol><li>In de brief staat: sluit binnen <strong>3 maanden</strong> een verzekering af of toon aan dat je je niet hoeft te verzekeren (bijvoorbeeld gemoedsbezwaren).</li><li>Doe je dat niet: een <strong>boete</strong>.</li><li>Na 2 boetes meldt het CAK je aan bij een zorgverzekeraar en houdt <strong>12 maanden</strong> premie in op je inkomen: de bestuursrechtelijke premie, <strong>110%</strong> van de standaardpremie. Zonder vast inkomen krijg je een acceptgiro.</li></ol><p>Kortom: uitstel levert niets op; je loopt het risico op onverzekerde zorg en daarna een hogere premie.</p>'
'<h2 id="steps">Praktische stappen voor nieuwkomers</h2><ol><li>Regel je bsn en schrijf je in bij de gemeente.</li><li>Vergelijk verzekeraars: het basispakket is wettelijk gelijk; verschillen zitten in premie, betaalwijze en optionele aanvullende dekking. Een gemiddelde premie noemen we hier niet, omdat we die niet in een officiele bron hebben gecontroleerd.</li><li>Het verplichte eigen risico staat vast (zie hieronder).</li><li>Schrijf je in bij een <a href="/nl/articles/huisarts-registration.html">huisarts</a>.</li><li>Vraag <a href="/nl/articles/zorgtoeslag-guide.html">zorgtoeslag</a> aan als je inkomen laag is.</li><li>Verhuis je, geef het door (<a href="/nl/articles/change-address-netherlands.html">adreswijziging</a>).</li></ol>'
'<h2 id="cost">Eigen risico en pakket</h2><p>Het verplichte eigen risico voor <strong>2026 is € 385</strong>. Je betaalt zelf de eerste € 385 aan zorgkosten die eronder vallen; daarna betaalt de verzekeraar. Voorbeeld van Zorginstituut Nederland: heb je al € 150 betaald, dan resteert € 235. <strong>Let op:</strong> eigen risico is iets anders dan een eigen bijdrage voor bepaalde zorg.</p><ul><li>Het basispakket omvat o.a. huisarts, ziekenhuis, psychiater en apotheek (volgens de overheid). Zwanger? Zie onze <a href="/nl/articles/pregnancy-newborn-care.html">gids zwanger en bevallen</a>.</li><li>Tandzorg voor volwassenen zit normaal niet in het basispakket; dat is een optionele aanvullende verzekering.</li><li>Kinderen onder 18: <strong>geen premie en geen eigen risico</strong>. Vanaf 18 sluit iedereen een eigen verzekering af.</li></ul>'
'<h2 id="other">Bijzondere situaties</h2><ul><li><strong>Gezinsleden in het land van herkomst:</strong> soms zorg via je Nederlandse verzekering met verdragsformulier E-106, via je zorgverzekeraar.</li><li><strong>Langdurige zorg:</strong> de Wlz geldt voor wie in Nederland woont.</li><li><strong>EU-ambtenaren:</strong> eigen stelsel (GSZV).</li></ul>'
'<h2 id="mistakes">Veelgemaakte fouten</h2><ul><li><strong>De CAK-brief negeren.</strong></li><li><strong>Denken dat de buitenlandse verzekering altijd volstaat.</strong> Het hangt af van werkgever en situatie.</li><li><strong>Eigen risico en aanvullende verzekering verwarren.</strong></li><li><strong>Vergeten dat 18-plussers een eigen verzekering nodig hebben.</strong></li><li><strong>Geen zorgtoeslag aanvragen.</strong></li></ul>'
'<p>Zorgtoeslag nodig? Zie de <a href="/nl/articles/zorgtoeslag-guide.html">gids zorgtoeslag</a>.</p>'),
faq=[('Hoeveel tijd heb ik als ik werk?','Volgens de overheid in elk geval binnen 4 maanden, ook als je niet in Nederland woont.'),
('Wat als ik te laat ben?','Je bent in de tussentijd onverzekerd en betaalt zorg zelf; daarna kan een CAK-brief en een boete volgen.'),
('Hoe hoog is het eigen risico in 2026?','€ 385.'),
('Betalen kinderen premie?','Nee, onder 18 geen premie en geen eigen risico.'),
('Is aanvullend verplicht?','Nee; tandzorg valt daar normaal onder.')],
src_note='Regels, termijnen en eigen risico komen van Rijksoverheid en Zorginstituut Nederland, gecontroleerd op 4 oktober 2026. Een gemiddelde premie noemen we niet omdat die niet gecontroleerd is. Bijzondere situaties (studenten, buitenlandse werkgever) bepaalt de SVB.')
#xlink
AR['body']+='<p><strong>جرّب الحاسبة:</strong> <a href="/calculators/zorgtoeslag.html">حاسبة zorgtoeslag 2026</a> تقدّر بدلك من دخلك وأصولك.</p>'
NL['body']+='<p><strong>Probeer de rekenhulp:</strong> <a href="/nl/calculators/zorgtoeslag.html">Zorgtoeslag berekenen 2026</a> geeft een schatting op basis van inkomen en vermogen.</p>'
