from a_student_finance import T
SLUG='health-insurance-2027'
R='https://www.rijksoverheid.nl/'
SRC=[('Rijksoverheid · Kabinet zet in op gezondheid en zorg (Prinsjesdag 15-9-2026)',R+'actueel/nieuws/2026/09/15/kabinet-zet-in-op-gezondheid-en-op-zorg-die-klaar-is-voor-de-toekomst'),
('Rijksoverheid · Eigen risico zorgverzekering',R+'vraag-en-antwoord/zorgverzekering/eigen-risico-zorgverzekering'),
('Rijksoverheid · Overstappen van zorgverzekeraar',R+'vraag-en-antwoord/zorgverzekering/overstappen-zorgverzekeraar'),
('Rijksoverheid · Korting collectieve zorgverzekering',R+'vraag-en-antwoord/zorgverzekering/korting-collectieve-zorgverzekering'),
('Rijksoverheid · Ben ik verplicht een zorgverzekering af te sluiten?',R+'vraag-en-antwoord/zorgverzekering/ben-ik-verplicht-een-zorgverzekering-af-te-sluiten'),
('Rijksoverheid · Wat gebeurt er als ik niet verzekerd ben?',R+'vraag-en-antwoord/zorgverzekering/wat-gebeurt-er-als-ik-niet-verzekerd-ben-voor-de-zorgverzekering'),
('Rijksoverheid · Zorgverzekering zonder verblijfsvergunning / na vergunning',R+'vraag-en-antwoord/zorgverzekering/kan-ik-een-zorgverzekering-afsluiten-als-ik-nog-geen-verblijfsvergunning-heb'),
('Rijksoverheid · Veranderingen basispakket',R+'vraag-en-antwoord/zorgverzekering/veranderingen-basispakket'),
('Dienst Toeslagen · Hoeveel zorgtoeslag kan ik krijgen?','https://www.belastingdienst.nl/wps/wcm/connect/nl/zorgtoeslag/content/hoeveel-zorgtoeslag')]

AR=dict(title='التأمين الصحي في هولندا 2027: المخاطرة الذاتية 400 يورو، الأقساط الجديدة، بدل الرعاية، وكيف تبدّل قبل 31 ديسمبر',
crumb='التأمين الصحي 2027',
desc='دليل عميق للتأمين الصحي 2027: المخاطرة الذاتية المقترحة 400 يورو، القسط المتوقع 169 يورو شهرياً، موعد إعلان الأقساط 12 نوفمبر، بدل الرعاية 2026 و2027، قواعد التبديل (31 ديسمبر و1 فبراير)، التقسيط، الغرامات إن لم تكن مؤمَّناً، وقواعد اللاجئين بعد الإقامة.',
summary='<ol><li><strong>المخاطرة الذاتية (eigen risico)</strong> 385 يورو في 2026، والحكومة اقترحت <strong>400 يورو في 2027</strong>. الزيادة الكبيرة (60 يورو إضافية) أُجّلت إلى 2028.</li><li><strong>القسط:</strong> تتوقع الحكومة متوسط <strong>169 يورو شهرياً</strong> (+12.50). كل شركة تعلن قسطها حتى <strong>12 نوفمبر</strong>.</li><li><strong>التبديل:</strong> ألغِ تأمينك الحالي حتى <strong>31 ديسمبر</strong>، أو اشترك في تأمين جديد قبل ذلك فتلغي الشركة الجديدة القديم تلقائياً. لديك حتى <strong>1 فبراير</strong> لتأمين جديد يبدأ بأثر رجعي من 1 يناير.</li><li><strong>بدل الرعاية:</strong> حتى 129 يورو شهرياً لشخص وحيد في 2026، ويُتوقع نحو 140 يورو في 2027.</li><li><strong>التأمين إلزامي</strong> لكل من يسكن أو يعمل في هولندا، وإن لم تؤمّن تتراكم الغرامات.</li></ol>',
body=(
'<h2 id="basics">كيف يعمل التأمين الصحي في هولندا؟ في دقيقة</h2><ul><li><strong>التأمين الأساسي (basisverzekering)</strong> إلزامي ومحتواه واحد عند كل الشركات (تحدده الدولة). الفرق بين الشركات في السعر والخدمة ونوع البوليصة (natura أو restitutie أو combinatie).</li><li><strong>التأمين الإضافي (aanvullend)</strong> اختياري: أسنان للبالغين، علاج طبيعي إضافي، نظارات…</li><li><strong>المخاطرة الذاتية (eigen risico):</strong> أول مبلغ من تكاليف بعض العلاجات تدفعه أنت كل سنة قبل أن يدفع التأمين.</li><li><strong>لا مخاطرة ذاتية</strong> على: الطبيب العام (huisarts)، رعاية الولادة والقابلة، التمريض المنزلي، بعض برامج الأمراض المزمنة، والأطفال تحت 18 سنة.</li></ul><p>إن كنت جديداً في هولندا فابدأ بـ<a href="/articles/health-insurance-newcomers.html">دليل التأمين الصحي للقادمين الجدد</a>.</p>'
'<h2 id="numbers">أرقام 2026 و2027 جنباً إلى جنب</h2>'
+T([['المخاطرة الذاتية الإلزامية','385 يورو','<strong>400 يورو</strong>','مقترح (الحكومة)'],
    ['متوسط القسط الشهري للتأمين الأساسي','—','<strong>نحو 169 يورو</strong> (+12.50)','توقع وزارة الصحة'],
    ['الحد الأقصى لبدل الرعاية، شخص وحيد','129 يورو/شهر','<strong>نحو 140 يورو/شهر</strong>','توقع'],
    ['المساهمة الذاتية في الأدوية','حد أقصى 250 يورو','حد أقصى 250 يورو','مقرر'],
    ['خصم التأمين الجماعي على الأساسي','غير مسموح منذ 2023','غير مسموح','نافذ']],
   ['البند','2026','2027','الحالة'])
+'<p><strong>انتبه:</strong> مواقع تجارية كثيرة ما زالت تعرض مخاطرة ذاتية 455 أو 460 يورو لعام 2027. هذه أرقام من خطة قديمة أُجّلت؛ الرقم الحكومي المقترح الآن 400 يورو.</p>'
'<h2 id="zorgtoeslag">بدل الرعاية الصحية (zorgtoeslag)</h2><p>جدول 2026 حسب Dienst Toeslagen:</p>'
+T([['بلا شريك بدلات','حتى <strong>129 يورو</strong> شهرياً عند دخل حتى 29,500 يورو؛ يتناقص تدريجياً، ولا بدل من دخل <strong>41,000 يورو</strong>.'],
    ['مع شريك بدلات','حتى <strong>246 يورو</strong> شهرياً معاً عند دخل مشترك حتى 29,500 يورو؛ لا بدل من <strong>51,500 يورو</strong>.']],
   ['الحالة','2026'])
+'<p>لعام 2027 لم تُنشر الجداول الرسمية بعد؛ الحكومة تتوقع ارتفاع الحد الأقصى للشخص الوحيد إلى نحو 140 يورو. للتفاصيل: <a href="/articles/zorgtoeslag-guide.html">دليل بدل الرعاية</a>. وإن تغيّر دخلك فحدّث التقدير (<a href="/articles/toeslagen-income-update.html">كيف</a>).</p>'
'<h2 id="switch">التبديل: التواريخ التي لا يجب أن تفوتك</h2>'
+T([['حتى 12 نوفمبر 2026','الشركات تعلن أقساط 2027 وشروطها. تصلك رسالة من شركتك.'],
    ['من منتصف نوفمبر','قارن: القسط، نوع البوليصة (natura/restitutie)، المستشفيات المتعاقد معها، والتأمين الإضافي.'],
    ['حتى 31 ديسمبر 2026','ألغِ تأمينك بنفسك، <strong>أو</strong> اشترك في تأمين جديد قبل هذا التاريخ فتلغي الشركة الجديدة القديم تلقائياً.'],
    ['حتى 1 فبراير 2027','يمكنك الاشتراك في تأمين جديد يبدأ <strong>بأثر رجعي من 1 يناير</strong> (بشرط أنك ألغيت القديم قبل 31 ديسمبر).']],
   ['التاريخ','ماذا تفعل'])
+'<p><strong>التأمين الإضافي:</strong> الشركة قد تقبل أو ترفض طلبك للتأمين الإضافي (خاصة للأسنان) أو تطلب استبياناً صحياً، بعكس الأساسي الذي يجب أن تقبلك فيه. لذلك لا تلغِ إضافياً تحتاجه قبل أن تتأكد من قبولك عند الجديدة.</p>'
'<h2 id="choose">كيف تختار؟ قرار من 4 أسئلة</h2><ol><li><strong>هل تتوقع علاجاً في 2027؟</strong> (حمل، عملية، أدوية دائمة) إن نعم فلا تختر مخاطرة ذاتية طوعية أعلى لتوفير القسط؛ ستدفعها على الأرجح.</li><li><strong>هل تريد حرية اختيار أي مستشفى؟</strong> بوليصة natura أرخص لكنها قد لا تدفع كل التكلفة عند مقدم خدمة غير متعاقد. restitutie أغلى وأكثر حرية.</li><li><strong>هل تحتاج تأميناً إضافياً فعلاً؟</strong> احسب: قسط سنة مقابل ما تتوقع أن يُرد لك.</li><li><strong>هل دخلك منخفض؟</strong> اسأل بلديتك عن تأمين جماعي للدخل المنخفض (gemeentepolis) أو مساعدة في التكاليف؛ التفاصيل تختلف من بلدية لأخرى.</li></ol><p><strong>المخاطرة الذاتية الطوعية:</strong> يمكن زيادتها بخطوات 100 إلى 500 يورو مقابل قسط أقل (أرقام صفحة 2026). هي مخاطرة: في سنة مرض قد تدفع حتى 385 + 500 يورو.</p>'
'<h2 id="pay">لا تستطيع دفع المخاطرة الذاتية مرة واحدة؟</h2><ul><li>اتفق مع شركة التأمين على <strong>دفعها بالتقسيط</strong> (betalingsregeling). اسأل شركتك عن شروطها.</li><li>بدل الرعاية الصحية يتضمن جزءاً مخصصاً للمساعدة في المخاطرة الذاتية.</li><li>إن كانت لديك ديون أو صعوبة في الدفع فاطلب مساعدة الديون من البلدية مبكراً.</li></ul>'
'<h2 id="uninsured">ماذا يحدث إن لم تكن مؤمَّناً؟</h2><ol><li>إن ظهر في السجلات أنك غير مؤمَّن ترسل لك هيئة <strong>CAK</strong> رسالة: لديك <strong>3 أشهر</strong> لتؤمّن نفسك.</li><li>إن لم تفعل: <strong>غرامة</strong>، ثم غرامة ثانية.</li><li>بعد غرامتين تسجّلك CAK عند شركة تأمين، وتقتطع القسط من دخلك لمدة <strong>12 شهراً</strong> بقسط أعلى: <strong>110% من القسط المعياري</strong>.</li><li>لا يُطلب منك قسط بأثر رجعي، لكنك تدفع بنفسك كل تكاليف العلاج في الفترة غير المؤمَّنة.</li></ol><p><strong>المواليد الجدد:</strong> سجّلهم عند شركة التأمين خلال <strong>4 أشهر</strong> من الولادة (مجاناً للأطفال). <strong>العمال القادمون من الخارج:</strong> سجّلوا في أسرع وقت.</p>'
'<h2 id="newcomers">اللاجئون بعد الحصول على الإقامة</h2><ul><li>أثناء الإقامة في مركز الاستقبال تُغطّى الرعاية جماعياً عبر نظام RMA، ولا يمكن الاشتراك في تأمين هولندي قبل قرار طلب الإقامة.</li><li>بعد بدء تصريح الإقامة، يمكنك الاشتراك في تأمين هولندي <strong>خلال 4 أشهر</strong>، ويبدأ من تاريخ بدء التصريح، أي <strong>بأثر رجعي</strong>، وتدفع القسط عن تلك الفترة أيضاً.</li><li>اطلب بدل الرعاية فور اشتراكك، فهو أيضاً يمكن أن يُصرف عن الفترة نفسها.</li></ul>'
'<h2 id="package">ما الذي تغيّر في الباقة الأساسية؟</h2><p>تغييرات 2026 الرسمية (الأحدث المنشور): دعم الإقلاع عن التدخين يُغطّى 3 مرات بدل مرة، وتغطية علاج حركي لبالغين مصابين بالتهاب الفقار المحوري الشديد، و«الاستشارات بين الأطباء» لم تعد تُحسب من المخاطرة الذاتية. تغييرات 2027 في الباقة الأساسية لم تُنشر رسمياً بعد على الصفحة؛ سنضيفها عند نشرها. وتبدأ في 2027 حملة تطعيم ضد الحزام الناري لمن بلغوا 60 عاماً (برنامج تطعيم وليس جزءاً من التأمين).</p>'
'<h2 id="checklist">قائمة نوفمبر–ديسمبر</h2><ol><li>اقرأ رسالة شركتك عن قسط 2027 (حتى 12 نوفمبر).</li><li>قارن 3 عروض على الأقل للأساسي والإضافي.</li><li>تأكد من قبولك في الإضافي الجديد قبل إلغاء القديم.</li><li>بدّل قبل 31 ديسمبر.</li><li>حدّث حساب الخصم المباشر.</li><li>افحص بدل الرعاية 2027 في Mijn toeslagen.</li><li>إن كان دخلك منخفضاً: اسأل البلدية عن gemeentepolis.</li></ol>'),
faq=[('كم المخاطرة الذاتية في 2027؟','اقترحت الحكومة 400 يورو (من 385 في 2026). الزيادة الإضافية 60 يورو أُجّلت إلى 2028.'),
('متى أعرف أقساط 2027؟','تعلنها الشركات حتى 12 نوفمبر 2026. توقع الحكومة متوسط 169 يورو شهرياً.'),
('حتى متى يمكنني التبديل؟','ألغِ حتى 31 ديسمبر، ولديك حتى 1 فبراير للاشتراك في تأمين جديد يبدأ بأثر رجعي من 1 يناير.'),
('هل ما زال هناك خصم على التأمين الجماعي؟','لا على التأمين الأساسي منذ 2023. قد توجد خصومات على التأمين الإضافي.'),
('ماذا لو لم أؤمّن نفسي؟','ترسل CAK رسالة بمهلة 3 أشهر، ثم غرامتين، ثم تسجيل إجباري مع اقتطاع قسط 110% لمدة 12 شهراً، وتدفع علاج الفترة غير المؤمّنة بنفسك.'),
('حصلت على الإقامة، متى أشترك؟','خلال 4 أشهر من بدء التصريح، ويبدأ التأمين بأثر رجعي من تاريخ بدء التصريح.')],
src_note='راجعنا الأرقام والقواعد في Rijksoverheid وDienst Toeslagen في 4 أكتوبر 2026. أرقام 2027 مقترحة أو متوقعة حتى يقرها البرلمان وتعلن الشركات أقساطها؛ سنحدّث الدليل بعد 12 نوفمبر.')

NL=dict(title='Zorgverzekering 2027: eigen risico € 400, nieuwe premies, zorgtoeslag en overstappen vóór 31 december',
crumb='Zorgverzekering 2027',
desc='Uitgebreide gids zorgverzekering 2027: voorgesteld eigen risico € 400, verwachte premie € 169 per maand, premies uiterlijk 12 november, zorgtoeslag 2026 en 2027, overstapregels (31 december en 1 februari), betalingsregeling, boetes bij onverzekerd zijn en de regels voor statushouders.',
summary='<ol><li><strong>Eigen risico</strong> € 385 in 2026; het kabinet stelt <strong>€ 400 voor 2027</strong> voor. De extra € 60 is uitgesteld naar 2028.</li><li><strong>Premie:</strong> VWS verwacht gemiddeld <strong>€ 169 per maand</strong> (+€ 12,50). Verzekeraars maken premies uiterlijk <strong>12 november</strong> bekend.</li><li><strong>Overstappen:</strong> zeg op vóór <strong>31 december</strong>, of sluit vóór die datum een nieuwe polis af (de nieuwe verzekeraar zegt dan voor je op). Tot <strong>1 februari</strong> kun je een nieuwe polis afsluiten met terugwerkende kracht tot 1 januari.</li><li><strong>Zorgtoeslag:</strong> maximaal € 129 per maand voor alleenstaanden in 2026, naar verwachting circa € 140 in 2027.</li><li><strong>Verplicht</strong> voor iedereen die in Nederland woont of werkt.</li></ol>',
body=(
'<h2 id="basics">Zo werkt de zorgverzekering</h2><ul><li><strong>Basisverzekering:</strong> verplicht en bij elke verzekeraar dezelfde inhoud. Verschil zit in prijs, service en polisvorm (natura, restitutie of combinatie).</li><li><strong>Aanvullende verzekering:</strong> vrijwillig (tandarts volwassenen, extra fysiotherapie, brillen…).</li><li><strong>Eigen risico:</strong> het deel van bepaalde zorgkosten dat je eerst zelf betaalt.</li><li><strong>Geen eigen risico</strong> voor huisarts, verloskundige/kraamzorg, wijkverpleging, sommige ketenzorg en kinderen onder 18.</li></ul><p>Nieuw in Nederland? Lees eerst <a href="/nl/articles/health-insurance-newcomers.html">zorgverzekering voor nieuwkomers</a>.</p>'
'<h2 id="numbers">Cijfers 2026 en 2027</h2>'
+T([['Verplicht eigen risico','€ 385','<strong>€ 400</strong>','Voorstel kabinet'],['Gemiddelde premie basisverzekering','—','<strong>circa € 169 per maand</strong> (+€ 12,50)','Verwachting VWS'],['Maximale zorgtoeslag alleenstaande','€ 129 p/m','<strong>circa € 140 p/m</strong>','Verwachting'],['Eigen bijdrage geneesmiddelen','max. € 250','max. € 250','Besloten'],['Collectiviteitskorting basisverzekering','niet meer sinds 2023','niet','Definitief']],['Onderdeel','2026','2027','Status'])
+'<p><strong>Let op:</strong> veel commerciële sites tonen nog een eigen risico van € 455 of € 460 voor 2027. Dat komt uit een uitgesteld plan; het kabinetsvoorstel is nu € 400.</p>'
'<h2 id="zorgtoeslag">Zorgtoeslag</h2>'
+T([['Zonder toeslagpartner','Tot <strong>€ 129</strong> per maand bij toetsingsinkomen tot € 29.500; aflopend; geen zorgtoeslag vanaf <strong>€ 41.000</strong>.'],['Met toeslagpartner','Samen tot <strong>€ 246</strong> per maand tot € 29.500; geen zorgtoeslag vanaf <strong>€ 51.500</strong>.']],['Situatie','2026'])
+'<p>De tabellen voor 2027 zijn nog niet gepubliceerd. Zie de <a href="/nl/articles/zorgtoeslag-guide.html">gids zorgtoeslag</a> en <a href="/nl/articles/toeslagen-income-update.html">inkomen doorgeven</a>.</p>'
'<h2 id="switch">Overstappen: de data</h2>'
+T([['Uiterlijk 12 november 2026','Verzekeraars maken premies en voorwaarden 2027 bekend.'],['Vanaf half november','Vergelijk premie, polisvorm, gecontracteerde zorg en aanvullende dekking.'],['Uiterlijk 31 december 2026','Zelf opzeggen, <strong>of</strong> vóór die datum een nieuwe polis afsluiten; de nieuwe verzekeraar zegt dan je oude op.'],['Uiterlijk 1 februari 2027','Nieuwe polis afsluiten <strong>met terugwerkende kracht tot 1 januari</strong> (als je vóór 31 december hebt opgezegd).']],['Datum','Actie'])
+'<p><strong>Aanvullend:</strong> een verzekeraar mag je voor een aanvullende verzekering (vooral tandarts) weigeren of een gezondheidsverklaring vragen. Zeg je oude aanvullende verzekering dus niet op voordat je zeker bent van acceptatie.</p>'
'<h2 id="choose">Kiezen in 4 vragen</h2><ol><li><strong>Verwacht je zorg in 2027?</strong> Kies dan geen hoger vrijwillig eigen risico.</li><li><strong>Wil je vrije zorgkeuze?</strong> Natura is goedkoper maar vergoedt bij niet-gecontracteerde zorg soms niet alles; restitutie is duurder en vrijer.</li><li><strong>Heb je aanvullend echt nodig?</strong> Vergelijk jaarpremie met wat je verwacht terug te krijgen.</li><li><strong>Laag inkomen?</strong> Vraag je gemeente naar een gemeentepolis of hulp bij zorgkosten; dat verschilt per gemeente.</li></ol><p><strong>Vrijwillig eigen risico:</strong> € 100 tot € 500 extra voor een lagere premie (bedragen 2026). In een jaar met veel zorg betaal je dan tot € 385 + € 500.</p>'
'<h2 id="pay">Eigen risico niet in één keer betalen?</h2><ul><li>Spreek met je verzekeraar een <strong>betalingsregeling</strong> af om het eigen risico in termijnen te betalen.</li><li>De zorgtoeslag bevat een bijdrage voor het eigen risico.</li><li>Schulden? Meld je op tijd bij de gemeente voor schuldhulp.</li></ul>'
'<h2 id="uninsured">Niet verzekerd?</h2><ol><li>Het <strong>CAK</strong> stuurt een brief: je hebt <strong>3 maanden</strong> om je te verzekeren.</li><li>Doe je dat niet: een <strong>boete</strong>, daarna een tweede boete.</li><li>Na 2 boetes sluit het CAK een verzekering voor je af en houdt <strong>12 maanden</strong> een bestuursrechtelijke premie in van <strong>110% van de standaardpremie</strong>.</li><li>Geen premie met terugwerkende kracht, maar zorgkosten in de onverzekerde periode betaal je zelf.</li></ol><p><strong>Pasgeborenen:</strong> binnen <strong>4 maanden</strong> na de geboorte aanmelden. <strong>Buitenlandse werknemers:</strong> zo snel mogelijk.</p>'
'<h2 id="newcomers">Statushouders</h2><ul><li>In de opvang ben je collectief verzekerd via de RMA; een Nederlandse zorgverzekering kan pas na het besluit op je aanvraag.</li><li>Na de ingangsdatum van je verblijfsvergunning sluit je <strong>binnen 4 maanden</strong> een zorgverzekering af, die ingaat op de ingangsdatum van de vergunning (<strong>met terugwerkende kracht</strong>), inclusief premie over die periode.</li><li>Vraag direct zorgtoeslag aan.</li></ul>'
'<h2 id="package">Veranderingen basispakket</h2><p>Officiële wijzigingen 2026 (meest recent gepubliceerd): stoppen-met-rokenondersteuning 3 keer per jaar vergoed, oefentherapie voor volwassenen met ernstige axiale spondyloartritis, en meekijkconsulten tellen niet meer mee voor het eigen risico. Wijzigingen in het basispakket 2027 staan nog niet op de officiële pagina. In 2027 start ook gordelroosvaccinatie voor 60-jarigen (vaccinatieprogramma, geen onderdeel van de verzekering).</p>'
'<h2 id="checklist">Checklist november–december</h2><ol><li>Lees de brief van je verzekeraar (uiterlijk 12 november).</li><li>Vergelijk minstens 3 aanbiedingen.</li><li>Zeker van acceptatie voor aanvullend vóór je opzegt.</li><li>Overstappen vóór 31 december.</li><li>Automatische incasso aanpassen.</li><li>Zorgtoeslag 2027 controleren in Mijn toeslagen.</li><li>Laag inkomen: vraag naar de gemeentepolis.</li></ol>'),
faq=[('Hoe hoog is het eigen risico in 2027?','Het kabinet stelt € 400 voor (2026: € 385). De extra € 60 is uitgesteld naar 2028.'),
('Wanneer zijn de premies 2027 bekend?','Uiterlijk 12 november 2026. VWS verwacht gemiddeld € 169 per maand.'),
('Tot wanneer kan ik overstappen?','Opzeggen tot en met 31 december; tot 1 februari een nieuwe polis met terugwerkende kracht tot 1 januari.'),
('Bestaat collectiviteitskorting nog?','Niet op de basisverzekering sinds 2023; wel soms op aanvullende verzekeringen.'),
('Wat als ik niet verzekerd ben?','Brief van het CAK met 3 maanden, daarna 2 boetes en verplichte verzekering met 110% premie-inhouding gedurende 12 maanden.'),
('Ik heb een verblijfsvergunning gekregen. Wanneer verzekeren?','Binnen 4 maanden na de ingangsdatum; de verzekering gaat met terugwerkende kracht in.')],
src_note='Bedragen en regels gecontroleerd bij Rijksoverheid en Dienst Toeslagen op 4 oktober 2026. Cijfers voor 2027 zijn voorstel of verwachting tot het parlement beslist en verzekeraars hun premies publiceren; we werken deze gids na 12 november bij.')
