from a_student_finance import T
SLUG='housing-rent-allowance-2026'
SRC=[('Dienst Toeslagen · Kan ik huurtoeslag krijgen?','https://www.belastingdienst.nl/wps/wcm/connect/nl/huurtoeslag/content/kan-ik-huurtoeslag-krijgen'),
('Dienst Toeslagen · Huurtoeslag verandert vanaf 2026','https://www.belastingdienst.nl/wps/wcm/connect/nl/huurtoeslag/content/huurtoeslag-verandert-vanaf-2026'),
('Dienst Toeslagen · Hoeveel huurtoeslag kan ik krijgen?','https://www.belastingdienst.nl/wps/wcm/connect/nl/huurtoeslag/content/hoeveel-huurtoeslag'),
('Dienst Toeslagen · Maximaal vermogen huurtoeslag','https://www.belastingdienst.nl/wps/wcm/connect/nl/huurtoeslag/content/maximaal-vermogen-huurtoeslag'),
('Dienst Toeslagen · Maximaal inkomen huurtoeslag','https://www.belastingdienst.nl/wps/wcm/connect/nl/huurtoeslag/content/maximaal-inkomen-huurtoeslag')]
AR=dict(title='Huurtoeslag 2026: ما الذي تغيّر؟ الشروط، سقف الاحتساب، حد الأصول، ومن يُحتسب دخله',
seo_title='بدل الإيجار huurtoeslag 2026: الشروط',
crumb='Huurtoeslag',
desc='بدل الإيجار huurtoeslag 2026: لا سقف للإيجار كشرط بعد الآن، لكن الحساب على إيجار أقصى 932.93 يورو، وحد الأصول 38,479 يورو للساكن. الشروط والأمثلة.',
summary='<ol><li>Huurtoeslag مساهمة حكومية في الإيجار تتوقف على <strong>المسكن</strong> و<strong>الدخل</strong> و<strong>الأصول</strong> وتركيبة من يسكن معك.</li><li><strong>تغيير مهم في 2026:</strong> لم يعد هناك سقف أقصى للإيجار يحرمك من البدل؛ لكن الحساب يتم على إيجار أقصى قدره <strong>932.93 يورو</strong> (<strong>498.20</strong> لمن دون 21 سنة).</li><li>لم تعد <strong>servicekosten</strong> تُحتسب؛ يُعتمد الإيجار الأساسي «الكالي» (kale huur).</li><li>حد الأصول في 1 يناير 2026: <strong>38,479</strong> يورو لكل ساكن و<strong>76,958</strong> للشريكين.</li><li>تدفع دائماً جزءاً من إيجارك بنفسك؛ والجزء من الإيجار فوق 932.93 لا يُعوَّض.</li></ol>',
body=(
'<h2 id="change">ما الذي تغيّر في 2026؟</h2><ul><li><strong>لا سقف أقصى للإيجار كشرط.</strong> في السنوات السابقة لـ2026 كان الإيجار المرتفع يمنع البدل تماماً؛ من 2026 قد تحصل على بدل مع إيجار أعلى إذا استوفيت بقية الشروط.</li><li><strong>الحساب يتم بسقف:</strong> يُحسب البدل على إيجار أقصى <strong>932.93 يورو</strong>. وللشباب حتى 21 سنة السقف <strong>498.20 يورو</strong>. إن كان إيجارك أقل فيُحسب على إيجارك الفعلي.</li><li><strong>servicekosten لا تُحتسب</strong> بعد الآن: يُعتمد الإيجار الأساسي.</li><li>الحد العمري الخاص بالشباب أصبح <strong>حتى 21 سنة</strong>.</li></ul><p>إن كنت قد رُفضت سابقاً أو قررت عدم استئجار شقة بسبب ارتفاع الإيجار، فأعد الفحص لعام 2026. وإن كنت تبحث عن مسكن بإيجار أقل، راجع <a href="/articles/social-housing-sociale-huurwoning.html">دليل السكن الاجتماعي</a>.</p>'
'<h2 id="who">الشروط الأساسية</h2><ul><li>تستأجر <strong>مسكناً مستقلاً</strong>: باب خاص يُقفل ومطبخ ومرحاض على الأقل (وغالباً حمام/دش خاص). بعض المساكن لا تعطي حقاً كالقارب السكني ومساكن العطل، وبعض المساكن غير المستقلة تعطي حقاً في حالات؛ راجع صفحة المساكن.</li><li><strong>دخلك</strong> ودخل شريكك وسكانك مشاركيك ليس مرتفعاً. الحد يعتمد على إيجارك وعمرك وتركيبة الأسرة، لذلك لا رقم واحداً؛ استخدم <strong>proefberekening</strong>.</li><li><strong>أصولك</strong> ليست مرتفعة (انظر الجدول).</li><li>تسجيل عنوانك في البلدية وعقد إيجار موثق، ودفع الإيجار فعلاً.</li><li>إقامة قانونية في هولندا.</li></ul>'
'<h2 id="assets">حد الأصول 2026</h2>'
+T([['كل ساكن بمفرده','38,479 يورو'],['شريكان معاً','76,958 يورو']],['الوضع','الحد في 1 يناير 2026'])
+'<p>في 2025 كان الحد 37,395 يورو لكل ساكن. المهم الوضع في <strong>1 يناير</strong> فقط، والأصول = ممتلكاتك ناقص ديونك.</p>'
'<h2 id="income">من يُحتسب دخله؟</h2><p>دخل الأشخاص الآخرين في المسكن يُحتسب غالباً مع دخلك. دخل مؤجّر الغرفة من الباطن (onderhuurder) لا يُحتسب، ويُحتسب جزء فقط في حالات أخرى. تأكد من وضع كل ساكن في «Mijn toeslagen» لأن الخطأ فيه يغيّر الحساب. وللشريك الضريبي اقرأ <a href="/articles/toeslagpartner-guide.html">دليل شريك البدلات</a>.</p>'
'<h2 id="examples">أمثلة على أثر السقف الجديد</h2><ul><li><strong>إيجار أساسي 800 يورو:</strong> يُحتسب البدل على 800 (أقل من السقف).</li><li><strong>إيجار أساسي 1,000 يورو (بالغ):</strong> يُحتسب البدل على <strong>932.93</strong>، والجزء الزائد <strong>67.07 يورو</strong> (1,000 − 932.93) لا يُعوَّض بتاتاً، وتدفعه أنت كاملاً بالإضافة إلى حصتك الأساسية.</li><li><strong>شاب عمره 20 سنة، إيجار 600:</strong> يُحتسب على <strong>498.20</strong> فقط، والباقي 101.80 يورو عليه.</li></ul><p>مبلغ البدل النهائي يحدده الدخل والتركيبة، وهو غير منشور بجدول ثابت؛ استعمل proefberekening.</p>'
'<h2 id="apply">كيف تطلب؟</h2><ol><li>افحص مسكنك وعنوانك وعقدك.</li><li>اجمع بيانات دخل كل ساكن في العنوان.</li><li>افتح «Mijn toeslagen» بـ <a href="/articles/digid-registration-guide.html">DigiD</a> وجرّب الحساب الرسمي.</li><li>قدّم الطلب وأدخل الإيجار الأساسي الصحيح (دون servicekosten).</li><li>أبلغ فوراً عن أي تغيير: انتقال، تغير الإيجار، ساكن جديد، تغير الدخل (<a href="/articles/toeslagen-income-update.html">تحديث الدخل</a>).</li></ol>'
'<h2 id="mistakes">أخطاء شائعة</h2><ul><li><strong>الاعتماد على قواعد 2025 أو ما قبلها.</strong> سقف الإيجار كشرط ألغي في 2026.</li><li><strong>افتراض أن كامل إيجارك سيُعوَّض.</strong> السقف 932.93 وتدفع دائماً جزءاً.</li><li><strong>إدخال الإيجار شاملاً servicekosten.</strong></li><li><strong>نسيان دخل ساكن آخر.</strong></li><li><strong>تجاهل أصول 1 يناير.</strong></li><li><strong>عدم الإبلاغ عن الانتقال.</strong></li></ul>'
'<h2 id="glossary">مسرد</h2><ul><li><strong>Huurtoeslag:</strong> بدل الإيجار.</li><li><strong>Kale huur:</strong> الإيجار الأساسي بدون تكاليف الخدمات.</li><li><strong>Servicekosten:</strong> تكاليف الخدمات.</li><li><strong>Zelfstandige woonruimte:</strong> مسكن مستقل.</li><li><strong>Onderhuurder:</strong> مستأجر من الباطن.</li></ul>'),
faq=[('هل ما زال الإيجار المرتفع يحرمني من huurtoeslag؟','لا. من 2026 لم يعد هناك سقف أقصى كشرط، لكن البدل يُحتسب على إيجار أقصى 932.93 يورو (498.20 لمن دون 21).'),
('ما حد الأصول؟','38,479 يورو لكل ساكن و76,958 يورو للشريكين، في 1 يناير 2026.'),
('هل servicekosten تدخل في الحساب؟','لا، من 2026 يُعتمد الإيجار الأساسي.'),
('هل يُحتسب دخل من يسكن معي؟','غالباً نعم، إلا مؤجّر الغرفة من الباطن (onderhuurder).'),
('كم سأحصل بالضبط؟','لا رقم ثابتاً؛ يعتمد على الإيجار والدخل والتركيبة. استخدم proefberekening الرسمية.')],
src_note='راجعنا Dienst Toeslagen في 4 أكتوبر 2026 (أرقام 2026). حدود الدخل لا تُنشر برقم واحد؛ تعتمد على حالتك فاستخدم الحساب الرسمي.')
NL=dict(title='Huurtoeslag 2026: wat is er veranderd? Voorwaarden, rekenhuur, vermogensgrens en wie meetelt',
seo_title='Huurtoeslag 2026: voorwaarden en veranderingen',
crumb='Huurtoeslag',
desc='Huurtoeslag 2026: geen maximale huurgrens meer, wel berekening over maximaal € 932,93 kale huur en een vermogensgrens van € 38.479 per bewoner.',
summary='<ol><li>Huurtoeslag is een bijdrage in de huur en hangt af van je <strong>woning</strong>, <strong>inkomen</strong>, <strong>vermogen</strong> en wie er met je woont.</li><li><strong>Grote verandering in 2026:</strong> geen maximale huurgrens meer als voorwaarde; wel wordt de toeslag berekend over een maximale huur van <strong>€ 932,93</strong> (<strong>€ 498,20</strong> voor jongeren tot 21).</li><li><strong>Servicekosten</strong> tellen niet meer mee; uitgangspunt is de kale huur.</li><li>Vermogensgrens op 1 januari 2026: <strong>€ 38.479</strong> per bewoner en <strong>€ 76.958</strong> voor partners.</li><li>Je betaalt altijd een deel van de huur zelf; over het deel boven € 932,93 krijg je geen toeslag.</li></ol>',
body=(
'<h2 id="change">Wat is er in 2026 veranderd?</h2><ul><li><strong>Geen maximale huurgrens als voorwaarde.</strong> Vóór 2026 kon je bij een te hoge huur helemaal geen huurtoeslag krijgen; vanaf 2026 soms wel, als je aan de andere voorwaarden voldoet.</li><li><strong>Berekening met een maximum:</strong> de toeslag wordt berekend over een maximale huur van <strong>€ 932,93</strong>. Voor jongeren tot 21 jaar is dat <strong>€ 498,20</strong>. Is je huur lager, dan telt je werkelijke huur.</li><li><strong>Servicekosten tellen niet meer mee</strong>; het gaat om de kale huur.</li><li>De leeftijdsgrens voor jongeren is <strong>tot 21 jaar</strong>.</li></ul><p>Kreeg je eerder geen toeslag of zag je van een woning af vanwege de hoge huur, controleer dan opnieuw voor 2026. Zoek je een woning met een lagere huur? Zie onze <a href="/nl/articles/social-housing-sociale-huurwoning.html">gids over de sociale huurwoning</a>.</p>'
'<h2 id="who">Basisvoorwaarden</h2><ul><li>Je huurt een <strong>zelfstandige woonruimte</strong>: minimaal een eigen afsluitbare toegangsdeur, keuken en wc (vaak ook eigen douche of badkamer). Een woonboot of recreatiewoning geeft meestal geen recht; sommige onzelfstandige woningen wel. Lees de pagina over woningen.</li><li>Je <strong>inkomen</strong> en dat van je toeslagpartner en medebewoners is niet te hoog. De grens hangt af van je huur, leeftijd en huishouden; er is dus geen vast bedrag. Gebruik de <strong>proefberekening</strong>.</li><li>Je <strong>vermogen</strong> is niet te hoog (zie tabel).</li><li>Je staat ingeschreven op het adres, hebt een huurcontract en betaalt de huur daadwerkelijk.</li><li>Rechtmatig verblijf in Nederland.</li></ul>'
'<h2 id="assets">Vermogensgrens 2026</h2>'
+T([['Per bewoner','€ 38.479'],['Partners samen','€ 76.958']],['Situatie','Grens op 1 januari 2026'])
+'<p>In 2025 was de grens € 37.395 per bewoner. Alleen je vermogen op <strong>1 januari</strong> telt; vermogen is bezittingen min schulden.</p>'
'<h2 id="income">Wiens inkomen telt mee?</h2><p>Het inkomen van andere mensen in je woning telt meestal mee. Het inkomen van een onderhuurder telt niet mee; in andere situaties telt soms een deel niet mee. Geef elke bewoner correct door in Mijn toeslagen, want een fout verandert de berekening. Zie ook <a href="/nl/articles/toeslagpartner-guide.html">de gids over de toeslagpartner</a>.</p>'
'<h2 id="examples">Voorbeelden van het effect van het maximum</h2><ul><li><strong>Kale huur € 800:</strong> de toeslag wordt over € 800 berekend (onder het maximum).</li><li><strong>Kale huur € 1.000 (volwassene):</strong> de berekening gebruikt <strong>€ 932,93</strong>; de resterende <strong>€ 67,07</strong> (1.000 − 932,93) krijg je nooit vergoed en betaal je volledig zelf, naast je eigen aandeel.</li><li><strong>Jongere van 20, huur € 600:</strong> er wordt gerekend met <strong>€ 498,20</strong>; de overige € 101,80 komt voor eigen rekening.</li></ul><p>De hoogte van de toeslag hangt af van inkomen en huishouden en staat niet in één vaste tabel; gebruik de proefberekening.</p>'
'<h2 id="apply">Aanvragen</h2><ol><li>Controleer woning, adres en huurcontract.</li><li>Verzamel de inkomensgegevens van alle bewoners op het adres.</li><li>Log in op Mijn toeslagen met <a href="/nl/articles/digid-registration-guide.html">DigiD</a> en doe de proefberekening.</li><li>Dien de aanvraag in met de juiste kale huur (zonder servicekosten).</li><li>Geef wijzigingen direct door: verhuizing, andere huur, nieuwe bewoner, ander inkomen (<a href="/nl/articles/toeslagen-income-update.html">inkomen bijwerken</a>).</li></ol>'
'<h2 id="mistakes">Veelgemaakte fouten</h2><ul><li><strong>Regels van 2025 of eerder gebruiken.</strong> De maximale huurgrens als voorwaarde is in 2026 vervallen.</li><li><strong>Denken dat je hele huur wordt vergoed.</strong> Het maximum is € 932,93 en je betaalt altijd een deel zelf.</li><li><strong>Servicekosten meetellen in de huur.</strong></li><li><strong>Het inkomen van een medebewoner vergeten.</strong></li><li><strong>Het vermogen op 1 januari negeren.</strong></li><li><strong>Een verhuizing niet doorgeven.</strong></li></ul>'
'<h2 id="glossary">Begrippen</h2><ul><li><strong>Huurtoeslag:</strong> bijdrage in de huur.</li><li><strong>Kale huur:</strong> huur zonder servicekosten.</li><li><strong>Servicekosten:</strong> kosten voor diensten.</li><li><strong>Zelfstandige woonruimte:</strong> woning met eigen voorzieningen.</li><li><strong>Onderhuurder:</strong> iemand die van jou een kamer huurt.</li></ul>'),
faq=[('Krijg ik geen huurtoeslag meer bij een te hoge huur?','Dat is vanaf 2026 niet meer zo: er is geen maximale huurgrens als voorwaarde, maar de toeslag wordt berekend over een maximale huur van € 932,93 (€ 498,20 tot 21 jaar).'),
('Wat is de vermogensgrens?','€ 38.479 per bewoner en € 76.958 voor partners samen, op 1 januari 2026.'),
('Tellen servicekosten mee?','Nee, vanaf 2026 gaat het om de kale huur.'),
('Telt het inkomen van mijn huisgenoot mee?','Meestal wel, behalve dat van een onderhuurder.'),
('Hoeveel krijg ik precies?','Dat hangt af van huur, inkomen en huishouden. Gebruik de officiële proefberekening.')],
src_note='Dienst Toeslagen geraadpleegd op 4 oktober 2026 (cijfers 2026). Inkomensgrenzen zijn per situatie verschillend; gebruik de officiële proefberekening.')
