from a_student_finance import T
SLUG='inburgering-integration-law-2026'
SRC=[('Rijksoverheid · Moet ik als nieuwkomer inburgeren?','https://www.rijksoverheid.nl/vraag-en-antwoord/immigratie-naar-nederland/moet-ik-als-nieuwkomer-inburgeren'),
('Rijksoverheid · Nieuwe Wet inburgering','https://www.rijksoverheid.nl/themas/migratie-en-reizen/inburgeren-in-nederland/nieuwe-wet-inburgering'),
('Rijksoverheid · Tussenevaluatie Wet inburgering (28-1-2026)','https://www.rijksoverheid.nl/actueel/nieuws/2026/01/28/kabinet-publiceert-tussenevaluatie-wet-inburgering-en-neemt-aanbevelingen-rekenkamer-over'),
('Inburgeren.nl · U gaat inburgeren','https://www.inburgeren.nl/u-gaat-inburgeren/'),
('Inburgeren.nl · Boete','https://www.inburgeren.nl/u-gaat-inburgeren/boete.jsp'),
('Inburgeren.nl · Inburgeren betalen (examenprijzen)','https://www.inburgeren.nl/inburgeren-betalen/'),
('Inburgeren.nl · Hoeveel geld mag u lenen?','https://www.inburgeren.nl/inburgeren-betalen/hoeveel-geld-mag-u-lenen.jsp'),
('Inburgeren.nl · Inhoud kennisexamens','https://www.inburgeren.nl/examen-doen/inhoud-kennisexamens.jsp'),
('Inburgeren.nl · Aanmelden examen','https://www.inburgeren.nl/examen-doen/aanmelden-examen.jsp'),
('Inburgeren.nl · Naturaliseren','https://www.inburgeren.nl/u-gaat-inburgeren/naturaliseren.jsp'),
('IND · Civic integration for a more secure residence permit','https://ind.nl/en/living-in-the-netherlands-with-a-residence-permit/civic-integration-for-more-secure-residence-permit')]

AR=dict(title='الاندماج في هولندا (Inburgering) 2026: المقابلة الشاملة، المسارات الثلاثة، مهلة 3 سنوات، الامتحانات والتكاليف، الغرامات، والإقامة الدائمة والجنسية',
crumb='الاندماج (Inburgering)',
seo_title='الاندماج inburgering في هولندا 2026',
desc='الاندماج (inburgering) في 2026: المقابلة الشاملة وخطة PIP، المسارات الثلاثة، مهلة 3 سنوات، امتحانات بـ50 يورو، وأثره على الإقامة الدائمة والجنسية.',
summary='<ol><li><strong>البلدية</strong> هي التي ترشدك: تجري معك <strong>مقابلة شاملة (brede intake)</strong> وتضع <strong>خطة الاندماج والمشاركة (PIP)</strong>.</li><li><strong>ثلاثة مسارات:</strong> B1 (لغة بمستوى B1 مع عمل أو تطوع)، والتعليم (للشباب نحو MBO/HBO)، وZ (الاعتماد على النفس، مستوى A1).</li><li><strong>المهلة 3 سنوات</strong> تبدأ عادة بعد رسالة DUO، وقد يُمنح تمديد.</li><li><strong>حاملو إقامة اللجوء لا يُغرَّمون</strong> بعد قرار مجلس الدولة؛ البلدية تدفع دوراتهم، وأول محاولتين لكل امتحان مجاناً.</li><li><strong>مهاجرو لم الشمل وغيرهم</strong> يدفعون بأنفسهم أو بقرض من DUO، ويمكن تغريمهم حتى 1,000 يورو إن تأخروا.</li><li><strong>للإقامة الدائمة</strong> تحتاج شهادة الاندماج؛ و<strong>للجنسية</strong> حالياً A2 أو امتحان الدولة B1/B2.</li></ol>',
body=(
'<h2 id="who">هل أنت ملزم بالاندماج؟</h2><p><strong>غير ملزم</strong> إن كنت: من دولة أوروبية (الاتحاد، ليختنشتاين، النرويج، آيسلندا، سويسرا)، أو تحت 18 سنة، أو فوق سن التقاعد، أو عشت 8 سنوات في هولندا في سن التعليم الإلزامي، أو تحمل شهادات هولندية بالهولندية، أو جئت مؤقتاً للدراسة أو العمل. <strong>كل الحالات الأخرى ملزمة</strong>، وترسل DUO رسالة تلقائياً. قانون 2021 يسري على من أصبح ملزماً من 1 يناير 2022.</p>'
'<h2 id="intake">المقابلة الشاملة وخطة PIP</h2><ul><li>بعد حصولك على BSN والإقامة وتسجيلك في البلدية تصلك رسالة DUO (قد تستغرق حتى 8 أسابيع).</li><li>تدعوك البلدية لـ<strong>مقابلة شاملة</strong> عن تعليمك وعملك وصحتك وعائلتك، مع «اختبار قابلية التعلم» الذي يحدد: هل B1 ممكن خلال 3 سنوات؟</li><li>بناءً عليها تُكتب <strong>خطة PIP</strong> بالمسار والوحدات. <strong>اقرأها جيداً قبل التوقيع</strong>، واطلب تعديلها إن لم تناسب وضعك (عمل، أطفال، صحة).</li><li>مهاجرو <a href="/articles/family-reunification-mvv-ind.html">لم الشمل مع الشريك</a> وغيرهم يحصلون أيضاً على مقابلة وPIP، لكنهم ينظمون مسار التعلم ويدفعونه بأنفسهم، ويمكنهم أخذ MAP وPVT من البلدية.</li></ul>'
'<h2 id="routes">المسارات الثلاثة</h2>'
+T([['مسار B1','لغة بمستوى B1 خلال 3 سنوات كحد أقصى، مع عمل أو تطوع.','امتحانات: القراءة، الاستماع، الكتابة، المحادثة، وKNM.'],
    ['مسار التعليم (onderwijsroute)','غالباً للشباب: لغة B1 أو أعلى وتحضير لـMBO أو HBO أو الجامعة.','انظر <a href="/articles/mbo-dutch-language-options.html">خيارات اللغة لـMBO</a>.'],
    ['مسار Z (الاعتماد على النفس)','لمن يصعب عليه المساران الآخران: لغة بمستوى A1 ومشاركة في المجتمع.','ينتهي بشهادة (certificaat) وليس دبلوم، بشرط 800 ساعة لغة ومشاركة.']],
   ['المسار','ما هو','الامتحان'])
+'<ul><li><strong>KNM (معرفة المجتمع الهولندي)</strong> جزء من كل المسارات: امتحان حاسوبي 45 دقيقة.</li><li><strong>MAP (وحدة سوق العمل والمشاركة)</strong> لمساري B1 وZ، عند البلدية ومجاناً.</li><li><strong>PVT (إعلان المشاركة)</strong> عند البلدية ومجاناً، وتوقّعه خلال المهلة.</li><li><strong>من B1 إلى A2:</strong> يمكن خفض مستوى بعض المهارات أو كلها إلى A2 في مسار B1 بعد <strong>600 ساعة</strong> لغة على الأقل (الغياب لا يُحسب). لا يوجد حد لعدد محاولات الامتحان في مسار B1، والإعفاء الجزئي من الامتحانات فقط لأسباب طبية.</li></ul>'
'<h2 id="deadline">المهلة والتمديد</h2><ul><li><strong>المهلة 3 سنوات.</strong></li><li><strong>تمديد تلقائي</strong> مرة واحدة حتى 6 أشهر إن حضرت كل دروس اللغة في PIP، ونجحت في امتحانين لغويين على الأقل وفي KNM وMAP وPVT.</li><li>عند تجاوز المهلة (لغير حاملي إقامة اللجوء) تُفرض غرامة ويُعطى وقت إضافي حسب ما أنجزته:</li></ul>'
+T([['لم تنجح في أي امتحان','سنتان إضافيتان'],['امتحان واحد','سنة ونصف'],['امتحانان','سنة'],['3 أو 4 امتحانات','6 أشهر'],['مسار Z: حتى 200 ساعة / 200–400 / 400–600 / 600–800','سنتان / سنة ونصف / سنة / 6 أشهر'],['تأخر PVT أو MAP','6 أشهر؛ وكلاهما: سنة']],['ما أنجزته','الوقت الإضافي بعد الغرامة'])
+'<h2 id="fines">الغرامات</h2>'
+T([['تأخر مسار التعلم','حتى <strong>1,000 يورو</strong>'],['تأخر PVT','340 يورو'],['تأخر MAP','340 يورو'],['حاملو إقامة اللجوء','<strong>لا غرامة أبداً</strong>، ولا تطالبهم DUO باسترداد القروض']],['الحالة','الغرامة'])
+'<p>بعد قرار مجلس الدولة (فبراير 2026) أعلن الوزير في يوليو 2026 مراجعة قرارات قانون 2013 النهائية وإعادة الغرامات والقروض المدفوعة، والتحضير لتعديل قانوني يلغي غرامات حاملي إقامة اللجوء في قانون 2021. لكن البلدية يمكنها الاستمرار في متابعة التزامك بالجهد. إن دفعت غرامة اندماج سابقاً كحامل إقامة لجوء، فراجع موقع inburgeren.nl.</p>'
'<h2 id="costs">التكاليف ومن يدفع</h2>'
+T([['كل امتحان (القراءة، الاستماع، الكتابة، المحادثة، KNM)','50 يورو؛ المجموع 250 يورو'],['حاملو إقامة اللجوء','البلدية تدفع الدورة؛ أول محاولتين لكل امتحان مجاناً (ليس لمستوى أقل من PIP)'],['مهاجرو لم الشمل وغيرهم','يدفعون بأنفسهم أو بقرض من DUO لمدرسة معتمدة فقط (zoekinburgerschool.nl)؛ مبلغ القرض حسب الدخل'],['MAP وPVT','مجاناً']],['البند','التكلفة'])
+'<p>القرض يُسدد عادة خلال 10 سنوات مع فائدة. قبل التسجيل في مدرسة تأكد أنها معتمدة، وإلا لا يُقبل القرض.</p>'
'<h2 id="exam">حجز الامتحانات</h2><ul><li>KNM وA2 عبر <strong>Mijn Inburgering</strong> بـDigiD على inburgeren.nl.</li><li>امتحانات B1/B2 هي <strong>امتحان الدولة NT2</strong> لدى DUO (<a href="/articles/nt2-b1-exam-guide.html">دليل امتحان NT2 B1</a>).</li><li>PVT وMAP تحجزهما مع البلدية.</li><li>الانتظار قد يتجاوز 6 أسابيع؛ احجز مبكراً. التغيير أو الإلغاء ممكن حتى أسبوع قبل الامتحان مع استرداد المال.</li></ul>'
'<h2 id="residence">الاندماج والإقامة الدائمة والجنسية</h2><ul><li><strong>الإقامة الدائمة أو الإقامة الأوروبية طويلة الأمد:</strong> تحتاج شهادة الاندماج، مع إمكان الإعفاء في حالات (مثلاً بشهادة مسار Z) (<a href="/articles/eu-permanent-residence-netherlands.html">دليل الإقامة الدائمة</a>).</li><li><strong>الجنسية:</strong> حالياً امتحان الاندماج بمستوى <strong>A2</strong> أو امتحان الدولة NT2 B1/B2. شهادة مسار Z لا تكفي للجنسية. أعلنت الحكومة نيتها رفع الشرط إلى B1، لكننا لم نجد قانوناً نافذاً أو تاريخاً (<a href="/articles/dutch-naturalisation-guide.html">دليل الجنسية</a>).</li><li>نصيحة: إن كنت تستطيع، استهدف B1 من البداية؛ يفتح العمل والدراسة ويحميك من أي تشديد مستقبلي.</li></ul>'
'<h2 id="money">الأشهر الأولى لحاملي الإقامة</h2><p>في أول <strong>6 أشهر</strong> من حقك في المساعدة الاجتماعية، تدفع البلدية عنك الإيجار والفواتير الأساسية من مساعدتك («إزالة العبء المالي»)، ثم تتولاها بنفسك. هذا إلزامي بالقانون. استعد لذلك بفهم فواتيرك ومواعيدها.</p>'
'<h2 id="news">ما الجديد في 2026؟</h2><ul><li><strong>التقييم المرحلي (28 يناير 2026):</strong> 16 مليون يورو (2023–2026) لوظائف بداية، وتعديل القواعد لتسهيل الجمع بين العمل والاندماج، وتركيز أكبر في PVT على دولة القانون، والاعتراف بأن أوقات الانتظار طويلة.</li><li><strong>غرامات حاملي إقامة اللجوء:</strong> أُلغيت عملياً، وتعديل قانوني قيد التحضير.</li><li><strong>تقييم القانون الكامل</strong> مخطط لـ2027.</li><li>ميثاق الهجرة الأوروبي لم يغيّر مهلة أو شروط الاندماج.</li></ul>'
'<h2 id="tips">نصائح عملية</h2><ol><li>احتفظ بنسخة من PIP وكل رسائل البلدية وDUO.</li><li>سجّل ساعات دروسك (مهم للخفض إلى A2 وللتمديد).</li><li>اجمع الدروس مع عمل جزئي أو تطوع؛ القواعد تُعدَّل لتسهيل ذلك.</li><li>إن تغيّر وضعك (حمل، مرض، عمل بدوام كامل) فاطلب تعديل PIP.</li><li>لا تنتظر السنة الثالثة: ابدأ بالامتحانات الأسهل عليك مبكراً.</li></ol>'),
faq=[('هل أُغرَّم إن لم أُنهِ الاندماج في 3 سنوات وأنا حامل إقامة لجوء؟','لا. حسب inburgeren.nl لا يُغرَّم حاملو إقامة اللجوء، لكن البلدية تتابع التزامك.'),
('ما الفرق بين مسار B1 ومسار Z؟','مسار B1 يهدف لمستوى B1 مع عمل أو تطوع؛ مسار Z لمستوى A1 والمشاركة لمن يصعب عليه التعلم، وينتهي بشهادة لا تكفي للجنسية.'),
('كم تكلف الامتحانات؟','50 يورو لكل امتحان (5 امتحانات = 250 يورو). لحاملي إقامة اللجوء أول محاولتين مجاناً.'),
('هل يمكن النجاح بمستوى A2 بدل B1؟','نعم، في مسار B1 يمكن الخفض إلى A2 بعد 600 ساعة لغة على الأقل.'),
('أي مستوى أحتاج للجنسية؟','حالياً A2 أو امتحان الدولة NT2 B1/B2. هناك نية حكومية لرفعه إلى B1 دون قانون نافذ بعد.'),
('من يدفع لمهاجري لم الشمل؟','يدفعون بأنفسهم أو بقرض DUO لمدرسة معتمدة.')],
src_note='راجعنا القواعد في Rijksoverheid وinburgeren.nl (DUO) وIND في 4 أكتوبر 2026، وتفاصيل الخفض إلى A2 والتمديد كما تشرحها منظمة البلديات Divosa استناداً للقانون. القواعد تتغير؛ اعتمد على رسائل DUO وخطتك PIP.')

NL=dict(title='Inburgeren in 2026: brede intake, drie leerroutes, termijn van 3 jaar, examens en kosten, boetes, permanent verblijf en naturalisatie',
crumb='Inburgering',
seo_title='Inburgeren 2026: leerroutes, termijn en examens',
desc='Inburgeren in 2026: brede intake en PIP, B1-, onderwijs- en Z-route, termijn van 3 jaar, examens van € 50 en de gevolgen voor permanent verblijf.',
summary='<ol><li>De <strong>gemeente</strong> begeleidt je met een <strong>brede intake</strong> en een <strong>PIP</strong>.</li><li><strong>Drie routes:</strong> B1-route, onderwijsroute en Z-route (A1).</li><li><strong>Termijn 3 jaar</strong>, start meestal na de DUO-brief; verlenging mogelijk.</li><li><strong>Asielstatushouders krijgen geen boete</strong>; de gemeente betaalt de cursus en de eerste 2 pogingen per examen zijn gratis.</li><li><strong>Gezinsmigranten en overige migranten</strong> betalen zelf of lenen bij DUO; boete tot € 1.000 bij overschrijding.</li><li><strong>Permanent verblijf:</strong> inburgeringsdiploma; <strong>naturalisatie:</strong> nu A2 of staatsexamen Nt2 B1/B2.</li></ol>',
body=(
'<h2 id="who">Moet jij inburgeren?</h2><p><strong>Niet verplicht</strong> met nationaliteit van een EU-land, Liechtenstein, Noorwegen, IJsland of Zwitserland; onder 18 of boven de AOW-leeftijd; 8 jaar in Nederland gewoond in de leerplichtige leeftijd; Nederlandse diploma’s in het Nederlands; of tijdelijk verblijf voor studie of werk. <strong>Alle anderen zijn verplicht</strong>; DUO stuurt automatisch een brief. De Wi2021 geldt voor wie vanaf 1 januari 2022 inburgeringsplichtig is.</p>'
'<h2 id="intake">Brede intake en PIP</h2><ul><li>Na BSN, verblijfsvergunning en inschrijving volgt de DUO-brief (kan 8 weken duren).</li><li>De gemeente houdt een <strong>brede intake</strong> met een leerbaarheidstoets: is B1 binnen 3 jaar haalbaar?</li><li>Daarna volgt het <strong>PIP</strong>. Lees het goed en vraag om aanpassing als het niet past bij werk, kinderen of gezondheid.</li><li>Gezinsmigranten (zie <a href="/nl/articles/family-reunification-mvv-ind.html">gezinshereniging met een partner</a>) en overige migranten krijgen ook een intake en PIP, maar regelen en betalen hun leerroute zelf; MAP en PVT volgen ze bij de gemeente.</li></ul>'
'<h2 id="routes">De drie routes</h2>'
+T([['B1-route','Taal op B1 binnen maximaal 3 jaar, met (vrijwilligers)werk.','Lezen, Luisteren, Schrijven, Spreken en KNM.'],['Onderwijsroute','Vooral jongeren: B1 of hoger en voorbereiding op mbo, hbo of universiteit.','Zie <a href="/nl/articles/mbo-dutch-language-options.html">taal en mbo</a>.'],['Z-route','Als de andere routes te moeilijk zijn: taal op A1 en participatie.','Certificaat (geen diploma), 800 uur taal en participatie.']],['Route','Wat','Afronding'])
+'<ul><li><strong>KNM</strong> hoort bij alle routes: computerexamen van 45 minuten.</li><li><strong>MAP</strong> (B1- en Z-route) en <strong>PVT</strong> bij de gemeente, gratis.</li><li><strong>Afschalen naar A2</strong> in de B1-route kan na minimaal <strong>600 uur</strong> taal (verzuim telt niet). Geen maximum aantal pogingen; gedeeltelijke ontheffing alleen op medische gronden.</li></ul>'
'<h2 id="deadline">Termijn en verlenging</h2><ul><li><strong>3 jaar.</strong></li><li><strong>Automatische verlenging</strong> van eenmalig maximaal 6 maanden als je alle taallessen uit het PIP hebt gevolgd en minstens 2 taalexamens, KNM, MAP en PVT hebt gehaald.</li><li>Na een boete (niet voor asielstatushouders) krijg je extra tijd:</li></ul>'
+T([['0 examens gehaald','2 jaar'],['1 examen','1,5 jaar'],['2 examens','1 jaar'],['3 of 4 examens','6 maanden'],['Z-route: tot 200 / 200–400 / 400–600 / 600–800 uur','2 / 1,5 / 1 jaar / 6 maanden'],['PVT of MAP te laat','6 maanden; beide: 1 jaar']],['Behaald','Extra tijd'])
+'<h2 id="fines">Boetes</h2>'
+T([['Leerroute te laat','maximaal <strong>€ 1.000</strong>'],['PVT te laat','€ 340'],['MAP te laat','€ 340'],['Asielstatushouders','<strong>nooit een boete</strong>; DUO vordert geen leningen terug']],['Situatie','Boete'])
+'<p>Na de uitspraak van de Raad van State (februari 2026) meldde de minister in juli 2026 dat onherroepelijke Wi2013-besluiten worden herzien en betaalde boetes en leningen worden terugbetaald, en dat een wetswijziging voor de Wi2021 wordt voorbereid. Gemeenten kunnen wel blijven handhaven op inspanning.</p>'
'<h2 id="costs">Kosten</h2>'
+T([['Elk examen (Lezen, Luisteren, Schrijven, Spreken, KNM)','€ 50; totaal € 250'],['Asielstatushouders','Gemeente betaalt de cursus; eerste 2 pogingen per examen gratis (niet op lager niveau dan in het PIP)'],['Gezinsmigranten en overige migranten','Zelf betalen of DUO-lening, alleen bij een goedgekeurde school (zoekinburgerschool.nl); leenbedrag inkomensafhankelijk'],['MAP en PVT','Gratis']],['Onderdeel','Kosten'])
+'<h2 id="exam">Examens boeken</h2><ul><li>KNM en A2 via <strong>Mijn Inburgering</strong> met DigiD.</li><li>B1/B2: <strong>staatsexamen Nt2</strong> bij DUO (<a href="/nl/articles/nt2-b1-exam-guide.html">gids Nt2 B1</a>).</li><li>PVT en MAP via de gemeente.</li><li>Wachttijd kan langer dan 6 weken zijn; wijzigen of afzeggen tot 1 week vooraf, met geld terug.</li></ul>'
'<h2 id="residence">Inburgering, permanent verblijf en naturalisatie</h2><ul><li><strong>Permanent of EU-langdurig ingezetene:</strong> inburgeringsdiploma nodig, met vrijstelling of ontheffing in bepaalde gevallen (<a href="/nl/articles/eu-permanent-residence-netherlands.html">permanent verblijf</a>).</li><li><strong>Naturalisatie:</strong> nu inburgeringsexamen op <strong>A2</strong> of staatsexamen Nt2 B1/B2. Het Z-routecertificaat volstaat niet. De regering wil de taaleis naar B1 verhogen, maar we vonden geen wet of datum (<a href="/nl/articles/dutch-naturalisation-guide.html">naturalisatie</a>).</li></ul>'
'<h2 id="money">De eerste maanden voor statushouders</h2><p>In de eerste <strong>6 maanden</strong> van je bijstandsrecht betaalt de gemeente vaste lasten zoals huur en energie vanuit je uitkering («financieel ontzorgen», wettelijk verplicht). Daarna doe je het zelf.</p>'
'<h2 id="news">Nieuw in 2026</h2><ul><li><strong>Tussenevaluatie (28 januari 2026):</strong> € 16 miljoen (2023–2026) voor startbanen, betere combinatie van werk en inburgering, meer aandacht voor de democratische rechtsstaat in het PVT, en te lange wachttijden.</li><li><strong>Boetes asielstatushouders:</strong> in de praktijk geschrapt; wetswijziging in voorbereiding.</li><li><strong>Wetsevaluatie</strong> gepland in 2027.</li><li>Het EU-Migratiepact verandert termijn en eisen niet.</li></ul>'
'<h2 id="tips">Praktische tips</h2><ol><li>Bewaar je PIP en alle brieven van gemeente en DUO.</li><li>Houd je lesuren bij (voor afschalen en verlenging).</li><li>Combineer lessen met parttime werk of vrijwilligerswerk.</li><li>Vraag een PIP-aanpassing bij grote veranderingen.</li><li>Begin vroeg met de examens die je het makkelijkst haalt.</li></ol>'),
faq=[('Krijg ik als asielstatushouder een boete als ik niet op tijd klaar ben?','Nee, volgens inburgeren.nl krijgen asielstatushouders geen boete; de gemeente blijft wel letten op je inspanning.'),
('Wat is het verschil tussen de B1-route en de Z-route?','De B1-route gaat naar B1 met werk of vrijwilligerswerk; de Z-route naar A1 en participatie, met een certificaat dat niet genoeg is voor naturalisatie.'),
('Wat kosten de examens?','€ 50 per examen, € 250 voor alle vijf. Asielstatushouders: eerste 2 pogingen gratis.'),
('Kan ik A2 doen in plaats van B1?','In de B1-route kun je afschalen naar A2 na minimaal 600 uur taal.'),
('Welk niveau heb ik nodig voor naturalisatie?','Nu A2 of staatsexamen Nt2 B1/B2; een verhoging naar B1 is aangekondigd maar niet ingevoerd.'),
('Wie betaalt voor gezinsmigranten?','Zij betalen zelf of lenen bij DUO voor een goedgekeurde school.')],
src_note='Regels gecontroleerd bij Rijksoverheid, inburgeren.nl (DUO) en IND op 4 oktober 2026; details over afschalen en verlenging zoals Divosa ze op basis van de wet uitlegt. Ga altijd uit van je DUO-brieven en je PIP.')
