from a_student_finance import T
SLUG='trending-jobs-2026'
U='https://www.uwv.nl/'
SRC=[('CBS · Werkloosheid gedaald in tweede kwartaal 2026 (30-7-2026)','https://www.cbs.nl/nl-nl/nieuws/2026/31/werkloosheid-gedaald-in-tweede-kwartaal-2026'),
('UWV · Kansrijke beroepen','https://www.uwv.nl/nl/arbeidsmarktinformatie/kansen-beroep/kansrijke-beroepen'),
('UWV · Kansrijke beroepen 2026-2027 (pdf)',U+'assets-kai/files/cb477fc7-719f-43ea-ac31-c15f428b864c/kansrijke-beroepen-2026-2027.pdf'),
('UWV · Krapte neemt nog verder toe in 32 beroepen',U+'nl/arbeidsmarktinformatie/trends-ontwikkelingen/krapte-neemt-nog-verder-toe-in-32-beroepen'),
('UWV · Arbeidsmarktprognose 2026-2028',U+'nl/arbeidsmarktinformatie/trends-ontwikkelingen/arbeidsmarktprognose-2026-2028-minder-banengroei-door-dure-energie'),
('UWV · Regionaal kansrijke beroepen 2026-2027 Twente (pdf)',U+'assets-kai/files/553a9cae-3040-4ae5-aff6-f21270457fbf/regionaal-kansrijke-beroepen-2026-2027-twente.pdf'),
('UWV · Twente regionale arbeidsmarktprognose 2026-2028 (pdf)',U+'assets-kai/files/ee8632e8-c1f0-475c-ae0c-a6fec111166e/twente-regionale-arbeidsmarktprognose-2026-2028.pdf'),
('SBB · Baankansen voor mbo-gediplomeerden gunstig','https://www.s-bb.nl/nieuws/baankansen-voor-mbo-gediplomeerden-gunstig'),
('Nuffic · Diplomawaardering voor vluchtelingen','https://www.nuffic.nl/studeren-en-werken-in-nederland/diplomawaardering/diplomawaardering-voor-vluchtelingen'),
('BIG-register · Nederlandse taalvaardigheid (buitenlands diploma)','https://www.bigregister.nl/buitenlands-diploma/procedures/verklaring-vakbekwaamheid/nederlandse-taalvaardigheid')]

AR=dict(title='المهن المطلوبة في هولندا 2026–2027: أرقام الشواغر الرسمية، قائمة UWV للمهن الواعدة، سوق العمل في تفينته، وطريقك كقادم جديد',
crumb='المهن المطلوبة',
seo_title='المهن المطلوبة في هولندا 2026–2027',
desc='المهن المطلوبة في هولندا 2026–2027: 375 ألف شاغر و95 لكل 100 عاطل، أمثلة من قائمة UWV في الرعاية والتقنية والبناء، ومعادلة الشهادة مجاناً للاجئين.',
summary='<ol><li><strong>الشواغر:</strong> 375 ألف شاغر نهاية الربع الثاني 2026، و<strong>95 شاغراً لكل 100 عاطل</strong>. السوق ما زال ضيقاً لكنه تجاوز الذروة (142 في 2022).</li><li><strong>أكثر القطاعات شواغر:</strong> التجارة (70.5 ألف)، الرعاية (68.5 ألف)، الخدمات التجارية (61.2 ألف)؛ وأعلى نسبة شواغر في البناء.</li><li><strong>قائمة UWV</strong> فيها أكثر من 300 مهنة واعدة، أبرزها: المساعدة في الرعاية والتمريض، الكهرباء والتركيبات والتبريد، اللحام وCNC، البناء، سائقو الشاحنات والحافلات، العمل في المستودعات، رعاية الأطفال والتدريس.</li><li><strong>حتى 2028</strong> يتوقع UWV نحو 90 ألف وظيفة جديدة في الرعاية.</li><li><strong>للقادمين الجدد:</strong> معادلة الشهادة <strong>مجانية للاجئين</strong> عبر IDW، والدراسة مع العمل (BBL) لها أعلى فرص وظيفية.</li></ol>',
body=(
'<h2 id="numbers">سوق العمل بالأرقام (CBS، الربع الثاني 2026)</h2>'
+T([['التجارة','70.5'],['الرعاية الصحية','68.5'],['الخدمات التجارية','61.2'],['الصناعة','29.4'],['البناء','28.2'],['الضيافة (المطاعم والفنادق)','26.4'],['الإدارة العامة','22.7'],['المعلومات والاتصالات','16.3'],['النقل والتخزين','14.4'],['التعليم','9.5']],['القطاع','الشواغر (بالألف)'])
+'<ul><li>المجموع <strong>375 ألف شاغر</strong>، و<strong>95 شاغراً لكل 100 عاطل</strong>؛ البطالة 3.9%.</li><li>التجارة والرعاية والخدمات التجارية معاً أكثر من نصف الشواغر.</li><li>أعلى نسبة شواغر في <strong>البناء</strong> (73 لكل 1,000 وظيفة)، وأدناها في التعليم (18).</li><li>يقول UWV إن الضيق «تجاوز ذروته»، لكن الطلب ما زال أكبر من العرض.</li></ul>'
'<h2 id="list">المهن الواعدة حسب UWV (2026–2027)</h2><p>أمثلة بأسماء UWV نفسها؛ القائمة الكاملة أكثر من 300 مهنة:</p>'
+T([['الرعاية الصحية','مساعد/ة منزلي، مساعد/ة رعاية (Helpende)، مرافق سكني، مقدّم/ة رعاية (Verzorgende IG)، ممرض/ة عام، مساعد صيدلي، مساعد طبيب أسنان، مساعد طبيب. وعلى مستوى أعلى: ممرض الحي، معالج فيزيائي، طبيب عام.'],
    ['التقنية والتركيبات','كهربائي ومركّب (ومنها الألواح الشمسية ونقاط الشحن)، سبّاك ومركّب تدفئة وغاز، فني تكييف وتبريد، فني شبكات الكهرباء، ميكانيكي سيارات، لحّام، مشغّل CNC، مجمّع آلات.'],
    ['البناء','بنّاء، عامل أسقف، مبلّط، دهّان، مشغّل رافعة. ومهن «بداية» مثل عامل مساعد في البناء، يسميها UWV «خطوة للنمو إلى حرفي».'],
    ['تكنولوجيا المعلومات','مكتب الدعم الفني، مدير أنظمة وشبكات، مطوّر برمجيات، أخصائي أمن معلومات، محلل بيانات. ينبّه UWV: الفرص أساساً لمن لديه خبرة أو شهادة في المجال.'],
    ['النقل واللوجستيات','عامل مستودع وتجهيز طلبات، سائق رافعة شوكية، سائق شاحنة توصيل، سائق شاحنة، سائق حافلة، سائق قطار، مخطط نقل.'],
    ['التعليم ورعاية الأطفال','موظف رعاية أطفال، معلم ابتدائي، معلم تعليم خاص، مدرس مهني تقني. مدرس NT2 فقط مع شهادة تدريس.'],
    ['أخرى','عامل نظافة (قد يصعب الدوام الكامل)، حارس أمن، منظم مرور، كاشير، مساعد مطبخ، طباخ مطعم.']],
   ['المجال','أمثلة من قائمة UWV'])
+'<p>كثير من هذه المهن يحتاج «معرفة محددة»: دورة قصيرة أو طويلة، وأحياناً تكفي شهادة (certificaat). ابحث عن مهنتك في قائمة UWV الكاملة (رابط في المصادر).</p>'
'<h2 id="future">التوقعات حتى 2028–2030</h2><ul><li><strong>حتى 2028:</strong> نحو 125 ألف وظيفة جديدة إن بقيت أسعار الطاقة مرتفعة، ونحو 200 ألف إن انخفضت. الرعاية +90 ألف، الخدمات المتخصصة +60 ألف تقريباً، تكنولوجيا المعلومات +20 ألف.</li><li>مع طاقة غالية: لا نمو أو انخفاض في الصناعة والنقل والتجارة والضيافة ووكالات التوظيف.</li><li><strong>حتى 2030:</strong> يتوقع UWV ازدياد الضيق في 32 مهنة، منها المهندسون وميكانيكيو الآلات والسيارات وعمال التشطيب وسائقو الشاحنات والحافلات والممرضون والمعالجون الفيزيائيون والأطباء. أما مطورو البرمجيات ومديرو الأنظمة فصار إيجادهم «أسهل قليلاً».</li></ul>'
'<h2 id="twente">سوق العمل في تفينته (إنسخيدة وما حولها)</h2><ul><li>396,700 وظيفة في 2025، ونمو متوقع <strong>+5,200 (+1.3%)</strong> حتى 2028 (وطنياً +1.7%).</li><li><strong>الرعاية والرفاه</strong> أكبر قطاع (نحو 18% من الوظائف)، ونموه المتوقع <strong>+5%</strong>، الأقوى في التمريض والرعاية المنزلية.</li><li>نمو أيضاً في الخدمات المتخصصة (+5%) وتكنولوجيا المعلومات (+3.6%) والبناء (+2.4%)؛ وانكماش في المالية (−3.8%) والتجزئة (−1.2%).</li><li><strong>الصناعة:</strong> تقريباً كل المهن الصناعية ضيقة جداً (فنيون ومشغلون ومهندسون) رغم الانكماش المتوقع.</li><li>11% من العاملين بين 60 و67 سنة، أي طلب إحلال كبير قادم. في قائمة تفينته: «مساعد الرعاية يحصل على فرص جيدة خاصة إن تقدّم نحو Verzorgende IG (مستوى 3)».</li><li>للاستشارة: Werkcentrum Twente.</li></ul>'
'<h2 id="routes">طريقك كقادم جديد</h2>'
+T([['معادلة الشهادة','للاجئين <strong>مجاناً</strong> عبر IDW (Nuffic وSBB)، بإقامة لجوء ورسالة DUO للاندماج؛ النتيجة عادة بعد 6 أسابيع على الأقل (<a href="/articles/diploma-evaluation-sbb.html">دليل معادلة الشهادة</a>).'],
    ['الدراسة مع العمل (BBL)','حسب SBB: 94% من خريجي BBL درسوا مساقاً بفرصة وظيفية 7 من 10 أو أكثر. تعمل وتتقاضى أجراً أثناء الدراسة (<a href="/articles/bol-bbl-comparison.html">BOL أم BBL</a>).'],
    ['المهن الصحية بشهادة أجنبية','تحتاج تسجيل BIG: هولندية <strong>B1</strong> لمهن MBO (ممرض، Verzorgende IG)، و<strong>B2</strong> لـHBO (معالج فيزيائي)، و<strong>B2+</strong> للجامعة (طبيب، صيدلي) عبر امتحان الدولة NT2، مع إثبات إنجليزية (إلا لـVerzorgende IG).'],
    ['اختيار مساق MBO','موقع KiesMBO يعرض «فرصة العمل» لكل مساق من 1 إلى 10. أمثلة لمساقات بفرصة عالية وخريجين قليلين: فني تكييف ومضخات حرارية (<a href="/articles/mbo-conditions.html">شروط MBO</a>).'],
    ['رخصة القيادة','تفتح مهن التوصيل والنقل (<a href="/articles/cbr-driving-license-netherlands.html">دليل رخصة القيادة</a>).']],
   ['المسار','التفاصيل'])
+'<p><strong>تنبيه:</strong> «التدريب التجريبي» و«دعم تكلفة الأجر» من UWV ليست لكل القادمين الجدد؛ هي لمن لديه إعانة من UWV أو إعاقة في العمل. اسأل بلديتك عن برامج العمل الخاصة بحاملي الإقامة.</p>'
'<h2 id="choose">كيف تختار؟ 5 أسئلة</h2><ol><li>ما خبرتك وشهادتك؟ ابدأ بمعادلتها.</li><li>ما مستواك في الهولندية؟ الرعاية تحتاج B1 على الأقل؛ المستودعات والتنظيف أقل.</li><li>هل تحتاج دخلاً الآن؟ اختر BBL أو مهنة «بداية» مع دورة مسائية.</li><li>ما المطلوب في منطقتك؟ في تفينته: الرعاية والصناعة والبناء.</li><li>أين تريد أن تكون بعد 3 سنوات؟ مساعد الرعاية مثلاً يتقدم إلى Verzorgende IG ثم التمريض.</li></ol>'
'<h2 id="mistakes">أخطاء شائعة</h2><ol><li>اختيار مساق «مشهور» بفرصة عمل منخفضة دون فحص KiesMBO.</li><li>تأجيل معادلة الشهادة رغم أنها مجانية للاجئين.</li><li>الظن أن تكنولوجيا المعلومات سهلة الدخول دون خبرة؛ UWV يقول العكس.</li><li>قبول عمل عبر وكالة دون فهم الحقوق (<a href="/articles/temporary-agency-work-rights.html">العمل عبر الوكالات</a>)، أو العمل كمستقل دون معرفة القواعد (<a href="/articles/kvk-zzp-business-netherlands.html">دليل العمل الحر zzp</a>).</li><li>إهمال اللغة: هي أكبر رافعة للأجر في أغلب المهن.</li></ol>'),
faq=[('ما أكثر القطاعات طلباً في هولندا 2026؟','حسب CBS: التجارة والرعاية الصحية والخدمات التجارية لديها أكثر الشواغر، والبناء أعلى نسبة شواغر.'),
('هل سوق العمل ما زال جيداً؟','نعم لكنه أهدأ من 2022: 95 شاغراً لكل 100 عاطل في الربع الثاني 2026 مقابل 142 في 2022.'),
('ما المهن المطلوبة في تفينته؟','الرعاية (أكبر قطاع ونمو متوقع 5% حتى 2028)، والمهن الصناعية التقنية، والبناء، والنقل.'),
('كم تكلف معادلة الشهادة للاجئين؟','مجانية عبر IDW لمن لديه إقامة لجوء ورسالة DUO للاندماج.'),
('أي مستوى هولندية أحتاج للعمل كممرض بشهادة أجنبية؟','B1 لمهن MBO مثل الممرض وVerzorgende IG، عبر امتحان الدولة NT2، مع تسجيل BIG.'),
('هل تكنولوجيا المعلومات خيار جيد للمبتدئين؟','يقول UWV إن الفرص أساساً لمن لديه خبرة أو شهادة في المجال، وإن الضيق في بعض مهن IT يخف.')],
src_note='راجعنا الأرقام في CBS وUWV (قائمة المهن الواعدة 2026–2027 وتوقعات 2026–2028 وتقارير تفينته) وSBB وNuffic وسجل BIG في 4 أكتوبر 2026. لم نذكر أجوراً لأننا لم نجد مصدراً رسمياً موحداً لها.')

NL=dict(title='Kansrijke beroepen in Nederland 2026–2027: officiële vacaturecijfers, de UWV-lijst, de arbeidsmarkt in Twente en jouw route als nieuwkomer',
crumb='Kansrijke beroepen',
seo_title='Kansrijke beroepen 2026–2027: UWV-lijst',
desc='Kansrijke beroepen 2026–2027: 375.000 vacatures en 95 per 100 werklozen, voorbeelden uit de UWV-lijst in zorg, techniek en bouw, routes voor nieuwkomers.',
summary='<ol><li><strong>Vacatures:</strong> 375.000 eind Q2 2026 en <strong>95 vacatures per 100 werklozen</strong>; krap, maar over het hoogtepunt (142 in 2022).</li><li><strong>Meeste vacatures:</strong> handel (70,5 duizend), zorg (68,5 duizend), zakelijke dienstverlening (61,2 duizend); hoogste vacaturegraad in de bouw.</li><li><strong>UWV</strong> noemt ruim 300 kansrijke beroepen: zorg, installatietechniek, lassen en CNC, bouw, chauffeurs, magazijn, kinderopvang en onderwijs.</li><li><strong>Tot 2028</strong> verwacht UWV circa 90.000 extra banen in de zorg.</li><li><strong>Nieuwkomers:</strong> diplomawaardering is <strong>gratis voor vluchtelingen</strong> via IDW; bbl heeft de beste baankansen.</li></ol>',
body=(
'<h2 id="numbers">De arbeidsmarkt in cijfers (CBS, Q2 2026)</h2>'
+T([['Handel','70,5'],['Zorg','68,5'],['Zakelijke dienstverlening','61,2'],['Industrie','29,4'],['Bouwnijverheid','28,2'],['Horeca','26,4'],['Openbaar bestuur','22,7'],['Informatie en communicatie','16,3'],['Vervoer en opslag','14,4'],['Onderwijs','9,5']],['Sector','Vacatures (× 1.000)'])
+'<ul><li>Totaal <strong>375.000 vacatures</strong>, <strong>95 per 100 werklozen</strong>; werkloosheid 3,9%.</li><li>Handel, zorg en zakelijke dienstverlening samen ruim de helft.</li><li>Hoogste vacaturegraad in de <strong>bouw</strong> (73 per 1.000 banen), laagste in het onderwijs (18).</li><li>UWV: krapte «over het hoogtepunt heen», maar de vraag is nog groter dan het aanbod.</li></ul>'
'<h2 id="list">Kansrijke beroepen volgens UWV (2026–2027)</h2>'
+T([['Zorg','Huishoudelijk medewerkers, helpenden, (assistent-)woonbegeleiders, verzorgenden IG, algemeen verpleegkundigen, apothekers-, tandarts- en doktersassistenten; hoger: wijkverpleegkundigen, fysiotherapeuten, huisartsen.'],['Techniek en installatie','Elektriciens en installateurs (ook zonnepanelen en laadpalen), loodgieters en installateurs gas/water/verwarming, koeltechniek, monteurs laag-, midden- en hoogspanning, automonteurs, lassers, CNC-verspaners, assemblagemonteurs.'],['Bouw','Metselaars, dakdekkers, tegelzetters, schilders, kraanmachinisten; opstapfuncties zoals opperman en hulparbeider.'],['ICT','Servicedesk, systeem- en netwerkbeheer, softwareontwikkelaars, securityspecialisten, data-analisten; vooral kansen met ICT-ervaring of -opleiding.'],['Transport en logistiek','Magazijn- en expeditiemedewerkers, orderpickers, heftruck-, bestelwagen-, vrachtwagen- en buschauffeurs, treinmachinisten, transportplanners.'],['Onderwijs en kinderopvang','Pedagogisch medewerkers kinderopvang, leerkrachten basis- en speciaal onderwijs, vakdocenten techniek; NT2-docent alleen met tweedegraadsbevoegdheid.'],['Overig','Schoonmakers (fulltime soms lastig), beveiligers, verkeersregelaars, kassamedewerkers, keukenassistenten, restaurantkoks.']],['Gebied','Voorbeelden uit de UWV-lijst'])
+'<p>Veel beroepen vragen specifieke kennis: een korte of langere opleiding, soms is een certificaat genoeg.</p>'
'<h2 id="future">Vooruitzichten tot 2028–2030</h2><ul><li><strong>Tot 2028:</strong> circa 125.000 banen erbij bij hoge energieprijzen, circa 200.000 bij dalende prijzen. Zorg +90.000, specialistische zakelijke dienstverlening bijna +60.000, ICT +20.000.</li><li>Bij dure energie geen groei of krimp in industrie, vervoer, handel, horeca en uitzendbranche.</li><li><strong>Tot 2030:</strong> verdere krapte in 32 beroepen, waaronder ingenieurs, machine- en automonteurs, afbouw, vrachtwagen- en buschauffeurs, verpleegkundigen, fysiotherapeuten en artsen; softwareontwikkelaars en systeembeheerders zijn «iets makkelijker te vinden».</li></ul>'
'<h2 id="twente">Twente</h2><ul><li>396.700 banen in 2025; verwachte groei <strong>+5.200 (+1,3%)</strong> tot 2028 (landelijk +1,7%).</li><li><strong>Zorg en welzijn</strong> is de grootste sector (bijna 18%) met +5,0% groei, vooral verpleging, verzorging en thuiszorg.</li><li>Groei ook in specialistische zakelijke diensten (+5,0%), ICT (+3,6%) en bouw (+2,4%); krimp in financiële diensten (−3,8%) en detailhandel (−1,2%).</li><li>Industrie: voor bijna alle industriële beroepen (zeer) krap, ondanks verwachte krimp.</li><li>11% van de werknemers is 60–67 jaar: veel vervangingsvraag. Helpenden: vooral kansen bij doorstroom naar verzorgende IG (niveau 3).</li><li>Advies: Werkcentrum Twente.</li></ul>'
'<h2 id="routes">Jouw route als nieuwkomer</h2>'
+T([['Diplomawaardering','<strong>Gratis voor vluchtelingen</strong> via IDW (Nuffic en SBB), met asielvergunning en DUO-brief over inburgering; meestal na minimaal 6 weken (<a href="/nl/articles/diploma-evaluation-sbb.html">diplomawaardering</a>).'],['Werken en leren (bbl)','Volgens SBB volgde 94% van de bbl-gediplomeerden een opleiding met baankans 7 of hoger (<a href="/nl/articles/bol-bbl-comparison.html">bol of bbl</a>).'],['Zorg met buitenlands diploma','BIG-registratie met Nederlands <strong>B1</strong> (mbo, bijv. verpleegkundige, verzorgende IG), <strong>B2</strong> (hbo) of <strong>B2+</strong> (wo) via staatsexamen Nt2, plus Engels (niet voor verzorgende IG).'],['Mbo-opleiding kiezen','KiesMBO toont de baankans (1–10) per opleiding, bijv. airco- en warmtepompmonteur (<a href="/nl/articles/mbo-conditions.html">mbo-toelating</a>).'],['Rijbewijs','Opent bezorg- en transportberoepen (<a href="/nl/articles/cbr-driving-license-netherlands.html">rijbewijs</a>).']],['Route','Details'])
+'<p><strong>Let op:</strong> proefplaatsing en loonkostensubsidie van UWV zijn er voor mensen met een UWV-uitkering of arbeidsbeperking, niet voor alle nieuwkomers. Vraag je gemeente naar werkprogramma’s voor statushouders.</p>'
'<h2 id="choose">Kiezen in 5 vragen</h2><ol><li>Welke ervaring en diploma heb je? Laat het waarderen.</li><li>Welk taalniveau? Zorg vraagt minstens B1.</li><li>Heb je nu inkomen nodig? Kies bbl of een opstapfunctie.</li><li>Wat is er in jouw regio nodig?</li><li>Waar wil je over 3 jaar staan?</li></ol>'
'<h2 id="mistakes">Veelgemaakte fouten</h2><ol><li>Een populaire opleiding kiezen met lage baankans.</li><li>Diplomawaardering uitstellen terwijl die gratis is voor vluchtelingen.</li><li>Denken dat ICT zonder ervaring makkelijk is.</li><li>Uitzendwerk aannemen zonder je rechten te kennen (<a href="/nl/articles/temporary-agency-work-rights.html">uitzendwerk</a>), of als zelfstandige beginnen zonder de regels te kennen (<a href="/nl/articles/kvk-zzp-business-netherlands.html">zzp’er worden</a>).</li><li>Taal laten liggen: de grootste hefboom voor je loon.</li></ol>'),
faq=[('Welke sectoren hebben in 2026 de meeste vacatures?','Volgens het CBS handel, zorg en zakelijke dienstverlening; de bouw heeft de hoogste vacaturegraad.'),
('Is de arbeidsmarkt nog krap?','Ja, maar minder dan in 2022: 95 vacatures per 100 werklozen in Q2 2026, tegen 142 in 2022.'),
('Welke beroepen zijn kansrijk in Twente?','Zorg (grootste sector, +5% tot 2028), technische industrieberoepen, bouw en transport.'),
('Wat kost diplomawaardering voor vluchtelingen?','Niets: gratis via IDW met asielvergunning en DUO-brief.'),
('Welk taalniveau heb ik nodig als verpleegkundige met een buitenlands diploma?','B1 voor mbo-beroepen via het staatsexamen Nt2, plus BIG-registratie.'),
('Is ICT een goede keuze voor beginners?','UWV zegt dat de kansen vooral liggen bij mensen met ICT-ervaring of -opleiding.')],
src_note='Cijfers gecontroleerd bij CBS, UWV (kansrijke beroepen 2026–2027, prognose 2026–2028 en Twente), SBB, Nuffic en het BIG-register op 4 oktober 2026. Salarissen noemen we niet, omdat we geen eenduidige officiële bron vonden.')
