from a_student_finance import T
SLUG='kindgebonden-budget-guide'
SRC=[('Dienst Toeslagen · Voorwaarden kindgebonden budget','https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/toeslagen/kindgebonden-budget/voorwaarden/voorwaarden-kindgebonden-budget'),
('Dienst Toeslagen · Hoeveel kindgebonden budget krijg ik?','https://www.belastingdienst.nl/wps/wcm/connect/nl/kindgebonden-budget/content/hoeveel-kindgebonden-budget'),
('Dienst Toeslagen · Maximaal vermogen kindgebonden budget','https://www.belastingdienst.nl/wps/wcm/connect/nl/kindgebonden-budget/content/maximaal-vermogen-kindgebonden-budget'),
('Dienst Toeslagen · Maximaal inkomen kindgebonden budget','https://www.belastingdienst.nl/wps/wcm/connect/nl/kindgebonden-budget/content/maximaal-inkomen-kindgebonden-budget'),
('Dienst Toeslagen · Wat verandert er in 2026 voor uw toeslagen?','https://www.belastingdienst.nl/wps/wcm/connect/nl/toeslagen-2026/topics/veranderingen-toeslagen-2026')]
AR=dict(title='Kindgebonden budget 2026: من يستحقه، حدود الأصول، وكيف يتغير المبلغ مع عمر الطفل',
crumb='Kindgebonden budget',
seo_title='ميزانية الطفل kindgebonden budget 2026',
desc='ميزانية الطفل kindgebonden budget 2026: الشروط، حد الأصول 146,011 يورو (184,633 مع الشريك)، والزيادة عند 12 و16 سنة وللوالد الوحيد.',
summary='<ol><li>Kindgebonden budget مساهمة حكومية لتكاليف الأطفال دون 18، <strong>تتوقف على الدخل والأصول</strong>، وتطلبها بنفسك عبر Mijn toeslagen.</li><li>الحق للوالد الذي <strong>تُسجَّل عليه kinderbijslag</strong>.</li><li>لا مبلغ ثابتاً للجميع: يتغير حسب دخلك وعدد الأطفال وأعمارهم ووضعك (والد وحيد أو لا). استخدم proefberekening الرسمية.</li><li>حد الأصول في 1 يناير 2026: <strong>146,011</strong> يورو بدون شريك و<strong>184,633</strong> معه.</li><li>يزيد المبلغ للوالد الوحيد وعند بلوغ الطفل 12 و16 سنة (بحسب الدخل).</li></ol>',
body=(
'<h2 id="who">الشروط الأساسية</h2><ul><li>لديك <strong>طفل واحد أو أكثر دون 18 سنة</strong>.</li><li>أنت الوالد الذي تُدفع له <strong>kinderbijslag</strong> (<a href="/articles/kinderbijslag-guide.html">دليل kinderbijslag</a>). إن كنتما والدين فالذي تُسجَّل عليه kinderbijslag هو صاحب الحق.</li><li>دخلك (ودخل <a href="/articles/toeslagpartner-guide.html">شريك البدلات</a>) ليس مرتفعاً؛ الحد يختلف حسب تركيبة الأسرة.</li><li>أصولك ليست مرتفعة.</li><li>تطلبه بنفسك عبر Mijn toeslagen، ولا يأتي تلقائياً.</li></ul>'
'<h2 id="assets">حد الأصول 2026</h2>'
+T([['بدون شريك بدلات','146,011 يورو'],['مع شريك بدلات (معاً)','184,633 يورو']],['الوضع','الحد الأقصى للأصول في 1 يناير 2026'])
+'<ul><li>الأصول = ممتلكاتك ناقص ديونك. تُحتسب كما هي في <strong>1 يناير</strong> فقط.</li><li>إن كان الطفل دون 18 فأصوله تُضاف إلى أصولك؛ وإن كان 18 فأكثر فلا تُحتسب.</li><li>الاستثمارات الخضراء (groene beleggingen) تُحتسب كأصول.</li><li><strong>مثال رسمي:</strong> بلا شريك، لديك في 1 يناير 2025 مبلغ 5,000 يورو، وفي يونيو ورثت 250,000 يورو. لك الحق عن 2025 لكن <strong>لا حق عن 2026</strong> لأن أصولك في 1 يناير 2026 تجاوزت الحد. وزوجان أصولهما المشتركة 190,000 في 1 يناير 2026 لا يستحقان عن 2026 لأنها فوق 184,633.</li><li>إن كنت تتلقاه وتجاوزت الأصول الحد في 1 يناير، أبلغ Toeslagen سريعاً؛ يتوقف الدفع وتُرد المبالغ التي استلمتها هذه السنة.</li></ul>'
'<h2 id="amount">كم ستحصل؟</h2><p>تقول Dienst Toeslagen إن المبلغ يعتمد على: <strong>دخلك، وضعك الأسري، وعدد الأطفال</strong>. لذلك لا يصح أن ننشر رقماً واحداً كأنه يناسب الجميع، والأدق استخدام «proefberekening» الرسمية التي تعطيك المبلغ مباشرة.</p>'
'<ul><li><strong>الوالد الوحيد</strong> (بدون شريك بدلات) يحصل على مبلغ أكبر من الأسر ذات الوالدين؛ راجع <a href="/articles/single-parent-support.html">دليل دعم الوالد الوحيد</a>.</li><li><strong>12 و16 سنة:</strong> عند بلوغ الطفل 12 أو 16 يزيد المبلغ كمساهمة في تكاليف المدرسة. تبدأ الزيادة في الشهر <em>التالي</em> لشهر ميلاده، وتعتمد على دخلك.</li><li><strong>تغييرات 2026:</strong> بحسب Dienst Toeslagen ارتفع المبلغ قليلاً للآباء الوحيدين الذين دخلهم حتى 29,736 يورو وللزوجين حتى 39,141 يورو، أما من دخلهم أعلى من ذلك فيحصلون على مبلغ أقل قليلاً في 2026.</li><li>يُدفع المبلغ شهرياً في أواخر الشهر السابق (مثلاً: يوم 20 أكتوبر قبل منتصف الليل لشهر نوفمبر 2026).</li></ul>'
'<h2 id="example">مثال على كيف يُفكَّر في الأمر</h2><p>أم وحيدة لطفلين (7 و11 سنة)، دخلها 27,000 يورو، وأصولها في 1 يناير 2026 هي 12,000 يورو. تفحص الشروط:</p><ol><li>أطفال دون 18: نعم.</li><li>تتلقى kinderbijslag: نعم (شرط للحق).</li><li>الأصول 12,000 &lt; 146,011: ضمن الحد.</li><li>الدخل 27,000 أقل من 29,736 وهو الحد الذي ذكرته Toeslagen لتحسّن 2026 للوالد الوحيد، فهي ضمن الفئة التي زاد لها المبلغ قليلاً.</li><li>المبلغ الدقيق: تدخل بياناتها في proefberekening لتعرفه؛ لا نخمّنه هنا.</li></ol><p>بعد أن يبلغ الأصغر 12 سنة يزيد المبلغ بدءاً من الشهر التالي لعيد ميلاده.</p>'
'<h2 id="apply">كيف تطلبه؟</h2><ol><li>تأكد أن kinderbijslag مسجّلة عليك.</li><li>افتح Mijn toeslagen بـ <a href="/articles/digid-registration-guide.html">DigiD</a> وأدخل دخلك المتوقع للسنة كاملة.</li><li>جرّب الحساب الرسمي قبل الطلب.</li><li>أبلغ عن أي تغيير في الدخل (<a href="/articles/toeslagen-income-update.html">كيف تحدّث دخلك</a>) والأسرة والسكن وشريك البدلات.</li><li>إن كنتما والدين منفصلين مع رعاية مشتركة (co-ouderschap) فاقرأ قواعد Toeslagen للحالة قبل الطلب.</li></ol>'
'<h2 id="mistakes">أخطاء شائعة</h2><ul><li><strong>الخلط بين kinderbijslag وkindgebonden budget.</strong> الأول من SVB ولا يرتبط بالدخل، والثاني من Toeslagen ويرتبط بالدخل والأصول.</li><li><strong>إهمال أصول 1 يناير</strong> بعد ميراث أو بيع أصل.</li><li><strong>تقدير الدخل أقل من الواقع.</strong></li><li><strong>عدم تحديث البيانات</strong> عند ولادة طفل أو بلوغه 12 أو 16 أو تغيّر الشريك.</li></ul>'
'<h2 id="glossary">مسرد</h2><ul><li><strong>Kindgebonden budget:</strong> ميزانية مرتبطة بالطفل، مساهمة حكومية.</li><li><strong>Alleenstaande ouder:</strong> والد وحيد بلا شريك بدلات.</li><li><strong>Vermogen:</strong> الأصول في 1 يناير.</li><li><strong>Proefberekening:</strong> حساب تجريبي رسمي.</li></ul>'),
faq=[('هل أحتاج kinderbijslag لأحصل على kindgebonden budget؟','نعم، الحق للوالد الذي kinderbijslag مسجّلة باسمه.'),
('هل المبلغ ثابت؟','لا. يعتمد على الدخل ووضع الأسرة وعدد الأطفال وأعمارهم.'),
('هل مدخراتي كلها تُحتسب؟','تُحتسب أصولك في 1 يناير ناقص الديون، مع استثناءات خاصة لبعض الأصول؛ والحد في 2026 هو 146,011 يورو (184,633 مع الشريك).'),
('ماذا لو ورثت مبلغاً كبيراً في منتصف السنة؟','المهم هو الأصول في 1 يناير. الميراث بعده يؤثر في السنة التالية وليس في السنة الجارية.')],
src_note='راجعنا Dienst Toeslagen في 4 أكتوبر 2026. مبالغ كل أسرة غير منشورة هنا لأنها تعتمد على الدخل؛ استخدم الحساب الرسمي.')
NL=dict(title='Kindgebonden budget 2026: wie heeft recht, vermogensgrens en hoe het bedrag met de leeftijd verandert',
crumb='Kindgebonden budget',
seo_title='Kindgebonden budget 2026: voorwaarden en bedrag',
desc='Kindgebonden budget 2026: voorwaarden, vermogensgrens € 146.011 (€ 184.633 met toeslagpartner) en hogere bedragen bij 12 en 16 jaar en voor alleenstaanden.',
summary='<ol><li>Kindgebonden budget is een bijdrage in de kosten van kinderen tot 18, <strong>afhankelijk van inkomen en vermogen</strong>, die je zelf aanvraagt via Mijn toeslagen.</li><li>Recht heeft de ouder die de <strong>kinderbijslag op zijn naam</strong> heeft staan.</li><li>Er is geen vast bedrag: het hangt af van inkomen, aantal kinderen, leeftijd en gezinssituatie. Gebruik de officiële proefberekening.</li><li>Vermogensgrens op 1 januari 2026: <strong>€ 146.011</strong> zonder toeslagpartner en <strong>€ 184.633</strong> met.</li><li>Het bedrag is hoger voor alleenstaande ouders en gaat omhoog als je kind 12 of 16 wordt (afhankelijk van inkomen).</li></ol>',
body=(
'<h2 id="who">Basisvoorwaarden</h2><ul><li>Je hebt <strong>1 of meer kinderen jonger dan 18</strong>.</li><li>Jij bent de ouder met <strong>kinderbijslag</strong> op je naam (<a href="/nl/articles/kinderbijslag-guide.html">gids kinderbijslag</a>).</li><li>Je inkomen (samen met dat van je <a href="/nl/articles/toeslagpartner-guide.html">toeslagpartner</a>) is niet te hoog; de grens hangt af van je gezinssamenstelling.</li><li>Je vermogen is niet te hoog.</li><li>Je vraagt het zelf aan via Mijn toeslagen; het komt niet automatisch.</li></ul>'
'<h2 id="assets">Vermogensgrens 2026</h2>'
+T([['Zonder toeslagpartner','€ 146.011'],['Met toeslagpartner (samen)','€ 184.633']],['Situatie','Maximaal vermogen op 1 januari 2026'])
+'<ul><li>Vermogen = bezittingen min schulden, alleen op <strong>1 januari</strong>.</li><li>Is je kind jonger dan 18, dan telt het vermogen van het kind mee; is het 18 of ouder, dan niet.</li><li>Groene beleggingen tellen wél mee als vermogen.</li><li><strong>Officieel voorbeeld:</strong> geen toeslagpartner, € 5.000 spaargeld op 1 januari 2025 en in juni een erfenis van € 250.000. Je hebt recht over 2025, maar <strong>niet over 2026</strong>, omdat je vermogen op 1 januari 2026 te hoog is. Een stel met samen € 190.000 op 1 januari 2026 krijgt over 2026 niets, omdat dat boven € 184.633 ligt.</li><li>Krijg je het nu en heb je op 1 januari te veel vermogen? Meld het snel; de uitbetaling stopt en wat je dit jaar kreeg moet je terugbetalen.</li></ul>'
'<h2 id="amount">Hoeveel krijg je?</h2><p>Dienst Toeslagen zegt dat het bedrag afhangt van: <strong>je inkomen, je gezinssituatie en het aantal kinderen</strong>. Daarom publiceren we geen enkel bedrag alsof het voor iedereen geldt; gebruik de officiële “proefberekening”.</p>'
'<ul><li><strong>Alleenstaande ouders</strong> (zonder toeslagpartner) krijgen meer dan gezinnen met 2 ouders; zie ook <a href="/nl/articles/single-parent-support.html">steun voor alleenstaande ouders</a>.</li><li><strong>12 en 16 jaar:</strong> wordt je kind 12 of 16, dan stijgt het bedrag als tegemoetkoming in schoolkosten. De verhoging gaat in <em>na</em> de maand van de verjaardag en hangt af van je inkomen.</li><li><strong>Wijzigingen 2026:</strong> volgens Dienst Toeslagen steeg het bedrag iets voor alleenstaande ouders met een inkomen tot € 29.736 en voor stellen tot € 39.141; wie meer verdient krijgt in 2026 iets minder.</li><li>Uitbetaling maandelijks vooraf (bijvoorbeeld op 20 oktober vóór 24.00 uur voor november 2026).</li></ul>'
'<h2 id="example">Zo denk je erover na</h2><p>Alleenstaande moeder met twee kinderen (7 en 11), inkomen € 27.000, vermogen op 1 januari 2026 € 12.000. Je controleert:</p><ol><li>Kinderen jonger dan 18: ja.</li><li>Kinderbijslag op haar naam: ja (voorwaarde).</li><li>Vermogen € 12.000 &lt; € 146.011: binnen de grens.</li><li>Inkomen € 27.000 is lager dan € 29.736, de grens die Toeslagen noemt voor de verbetering in 2026 voor alleenstaande ouders; zij valt dus in de groep waarvoor het bedrag iets omhoog ging.</li><li>Het precieze bedrag vind je met de proefberekening; dat gokken we hier niet.</li></ol><p>Wordt het jongste kind 12, dan stijgt het bedrag vanaf de maand na de verjaardag.</p>'
'<h2 id="apply">Aanvragen</h2><ol><li>Controleer dat de kinderbijslag op jouw naam staat.</li><li>Log in op Mijn toeslagen met <a href="/nl/articles/digid-registration-guide.html">DigiD</a> en vul je verwachte jaarinkomen in.</li><li>Gebruik eerst de officiële proefberekening.</li><li>Meld wijzigingen in inkomen (<a href="/nl/articles/toeslagen-income-update.html">inkomen doorgeven</a>), gezin, woonsituatie of toeslagpartner direct.</li><li>Zijn jullie gescheiden ouders met co-ouderschap, lees dan de regels van Toeslagen vóór je aanvraagt.</li></ol>'
'<h2 id="mistakes">Veelgemaakte fouten</h2><ul><li><strong>Kinderbijslag en kindgebonden budget verwarren.</strong> Het eerste komt van de SVB en is niet inkomensafhankelijk; het tweede komt van Toeslagen en hangt af van inkomen en vermogen.</li><li><strong>Vermogen op 1 januari vergeten</strong> na een erfenis of verkoop.</li><li><strong>Inkomen te laag schatten.</strong></li><li><strong>Gegevens niet bijwerken</strong> bij geboorte, 12e of 16e verjaardag of een nieuwe partner.</li></ul>'
'<h2 id="glossary">Begrippen</h2><ul><li><strong>Kindgebonden budget:</strong> bijdrage in kosten van kinderen.</li><li><strong>Alleenstaande ouder:</strong> ouder zonder toeslagpartner.</li><li><strong>Vermogen:</strong> bezittingen min schulden op 1 januari.</li><li><strong>Proefberekening:</strong> officiële rekenhulp.</li></ul>'),
faq=[('Heb ik kinderbijslag nodig voor kindgebonden budget?','Ja, recht heeft de ouder met kinderbijslag op zijn naam.'),
('Is het bedrag vast?','Nee. Het hangt af van inkomen, gezinssituatie, aantal kinderen en leeftijd.'),
('Telt al mijn spaargeld mee?','Je vermogen op 1 januari min schulden telt, met enkele uitzonderingen; de grens in 2026 is € 146.011 (€ 184.633 met toeslagpartner).'),
('Wat als ik halverwege het jaar een grote erfenis krijg?','Alleen je vermogen op 1 januari telt. Een erfenis daarna heeft pas het jaar erop gevolgen.')],
src_note='Dienst Toeslagen geraadpleegd op 4 oktober 2026. Bedragen per gezin zijn hier niet opgenomen omdat ze van je inkomen afhangen; gebruik de officiële proefberekening.')
#xlink
AR['body']+='<p><strong>جرّب الحاسبة:</strong> <a href="/calculators/kindgebonden-budget.html">حاسبة kindgebonden budget 2026</a> تقدّر المبلغ حسب الدخل وعدد الأطفال وأعمارهم.</p>'
NL['body']+='<p><strong>Probeer de rekenhulp:</strong> <a href="/nl/calculators/kindgebonden-budget.html">Kindgebonden budget berekenen 2026</a> geeft een schatting per jaar en maand.</p>'
