from a_student_finance import T
SLUG='childcare-allowance-kinderopvangtoeslag'
SRC=[('Rijksoverheid · Bedragen kinderopvangtoeslag 2026','https://www.rijksoverheid.nl/themas/belastingen-uitkeringen-en-toeslagen/kinderopvangtoeslag/bedragen-kinderopvangtoeslag-2026'),
('Dienst Toeslagen · Maximale uurprijs kinderopvangtoeslag','https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/toeslagen/kinderopvangtoeslag/hoeveel-kinderopvangtoeslag-kan-ik-krijgen/maximaal-uurtarief-voor-de-kinderopvang'),
('Dienst Toeslagen · Wat verandert er in 2026 voor uw toeslagen?','https://www.belastingdienst.nl/wps/wcm/connect/nl/toeslagen-2026/topics/veranderingen-toeslagen-2026'),
('Dienst Toeslagen · Hoe moet ik kinderopvangtoeslag aanvragen?','https://www.belastingdienst.nl/wps/wcm/connect/nl/kinderopvangtoeslag/content/hoe-moet-ik-kinderopvangtoeslag-aanvragen')]
AR=dict(title='Kinderopvangtoeslag 2026: كم تعوّضك الدولة عن الحضانة؟ الأسعار القصوى والنسب وأمثلة',
crumb='Kinderopvangtoeslag',
desc='Kinderopvangtoeslag لعام 2026: الأسعار القصوى للساعة (حضانة 11.23، رعاية بعد المدرسة 9.98، gastouder 8.49)، نسبة التعويض 96% حتى دخل مشترك نحو 56,412 يورو، مثال محسوب، وأخطاء شائعة.',
summary='<ol><li>Kinderopvangtoeslag تعويض حكومي عن تكاليف الحضانة المسجّلة، وهو نسبة مئوية من <strong>سعر ساعة أقصى</strong> وليس من السعر الذي تطلبه الحضانة.</li><li>في 2026 الأسعار القصوى للساعة: <strong>11.23</strong> يورو حضانة (dagopvang)، <strong>9.98</strong> رعاية بعد المدرسة، <strong>8.49</strong> gastouder.</li><li>الأسر ذات الدخل المشترك حتى نحو <strong>56,412 يورو</strong> تحصل على أعلى نسبة: <strong>96%</strong>.</li><li>إن كان سعر حضانتك أعلى من السعر الأقصى فالفرق كله عليك.</li><li>الحد الأقصى للساعات المعوَّضة نحو <strong>230 ساعة شهرياً لكل طفل</strong>.</li></ol>',
body=(
'<h2 id="what">كيف يُحسب التعويض؟</h2><p>الصيغة: <strong>التعويض = الساعات × min(سعر الساعة الفعلي، السعر الأقصى) × نسبة التعويض</strong>. النسبة تتحدد حسب دخلك المشترك مع شريكك، وفي 2026 تصل إلى 96% للأسر ذات الدخل المشترك حتى حوالي 56,412 يورو، وما فوق ذلك تحصل الأسرة على نسبة أقل لكنها في 2026 أعلى مما كانت في 2025.</p>'
'<h2 id="max">الأسعار القصوى للساعة 2026</h2>'
+T([['Dagopvang (حضانة نهارية)','11.23'],['Buitenschoolse opvang (رعاية بعد المدرسة)','9.98'],['Gastouderopvang (رعاية منزلية مسجلة)','8.49']],['نوع الرعاية','السعر الأقصى (يورو/ساعة)'])
+'<p>تعوّض الدولة أيضاً حتى <strong>230 ساعة شهرياً لكل طفل</strong> حسب Rijksoverheid.</p>'
'<h2 id="example">مثال محسوب</h2><p>أسرة دخلها المشترك 50,000 يورو (ضمن شريحة 96%) ولها طفل في dagopvang 100 ساعة شهرياً، والحضانة تطلب 12.00 يورو للساعة:</p><ul><li>سعر الساعة المعتمد = min(12.00 ، 11.23) = <strong>11.23</strong></li><li>التعويض للساعة = 11.23 × 0.96 = <strong>10.78</strong> يورو (10.7808)</li><li>التعويض الشهري = 11.23 × 0.96 × 100 ≈ <strong>1,078.08 يورو</strong></li><li>فاتورة الحضانة = 12.00 × 100 = 1,200 يورو</li><li>ما تدفعه الأسرة فعلياً ≈ <strong>121.92 يورو</strong> شهرياً: 4% من 11.23 على الساعات، مضافاً إليها الفرق فوق السعر الأقصى (0.77 يورو للساعة).</li></ul><p>لو كان سعر الحضانة 11.23 بالضبط لدفعت الأسرة فقط 4% (نحو 44.92 يورو شهرياً لـ100 ساعة).</p>'
'<h2 id="who">من يستحق؟</h2><ul><li>الأبوان (أو الوالد الوحيد) <strong>يعملان</strong> أو يدرسان أو يتابعان مساراً مقبولاً وفق قواعد Toeslagen؛ اقرأ الشروط الحالية لحالتك.</li><li>الرعاية يجب أن تكون <strong>مسجلة رسمياً</strong> (حضانة أو BSO أو gastouder مسجّل) لا اتفاقاً غير رسمي.</li><li>يُحتسب دخلك ودخل شريك البدلات؛ انظر <a href="/articles/toeslagpartner-guide.html">دليل شريك البدلات</a>.</li></ul>'
'<h2 id="apply">خطوات الطلب</h2><ol><li>اختر مقدم رعاية مسجلاً واحصل على اتفاق كتابي وبيانات تسجيله.</li><li>افتح «Mijn toeslagen» بـ DigiD وقدّم الطلب <strong>قبل</strong> أو مع بدء الرعاية؛ التأخر قد يضيّع أشهراً من التعويض.</li><li>أدخل ساعات الرعاية المتوقعة وسعر الساعة وتقدير الدخل السنوي الكامل.</li><li>أبلغ عن أي تغيير في الساعات أو السعر أو العمل أو الدخل أو مقدم الرعاية فوراً.</li><li>بعد نهاية السنة يأتي الحساب النهائي وقد تُطالب بإعادة جزء إن كانت تقديراتك خاطئة.</li></ol>'
'<h2 id="mistakes">أخطاء شائعة</h2><ul><li><strong>افتراض أن 96% من فاتورتك كاملة.</strong> النسبة تطبق على السعر الأقصى فقط.</li><li><strong>الطلب متأخراً.</strong></li><li><strong>تقدير ساعات أكثر من الواقع</strong> فتحصل على مبلغ أعلى ثم يُطلب منك رده.</li><li><strong>عدم إبلاغ تغيير العمل.</strong> فقدان العمل أو تقليص الساعات يغيّر الحق.</li><li><strong>استخدام رعاية غير مسجلة.</strong></li></ul>'
'<h2 id="glossary">مسرد</h2><ul><li><strong>Dagopvang:</strong> حضانة نهارية.</li><li><strong>BSO (buitenschoolse opvang):</strong> رعاية بعد المدرسة.</li><li><strong>Gastouder:</strong> رعاية في منزل مقدم رعاية مسجل.</li><li><strong>Toetsingsinkomen:</strong> الدخل المعتمد في الحساب.</li></ul>'),
faq=[('هل التعويض 96% من ما أدفع للحضانة؟','لا. 96% من <em>السعر الأقصى للساعة</em> (11.23 للحضانة النهارية في 2026) وليس من السعر الذي تحدده الحضانة.'),
('ما الأسعار القصوى لعام 2026؟','11.23 يورو للحضانة النهارية، 9.98 للرعاية بعد المدرسة، 8.49 لـgastouder.'),
('حتى أي دخل أحصل على 96%؟','حسب Rijksoverheid: دخل مشترك حتى نحو 56,412 يورو في 2026.'),
('هل أطلب قبل بدء الحضانة؟','نعم، الأفضل أن تطلب مبكراً؛ التأخر قد يعني خسارة جزء من التعويض.')],
src_note='راجعنا Rijksoverheid وDienst Toeslagen في 4 أكتوبر 2026. شرائح الدخل الأعلى من 56,412 يورو غير مفصلة هنا؛ استخدم proefberekening الرسمية.')
NL=dict(title='Kinderopvangtoeslag 2026: hoeveel vergoedt de overheid? Maximale uurprijzen, percentages en voorbeeld',
crumb='Kinderopvangtoeslag',
desc='Kinderopvangtoeslag 2026: maximale uurprijzen (dagopvang € 11,23, bso € 9,98, gastouder € 8,49), vergoeding van 96% tot een gezamenlijk inkomen van circa € 56.412, rekenvoorbeeld en veelgemaakte fouten.',
summary='<ol><li>Kinderopvangtoeslag is een vergoeding voor erkende kinderopvang en een percentage van de <strong>maximale uurprijs</strong>, niet van de prijs die de opvang rekent.</li><li>Maximale uurprijzen 2026: <strong>€ 11,23</strong> dagopvang, <strong>€ 9,98</strong> buitenschoolse opvang, <strong>€ 8,49</strong> gastouder.</li><li>Ouders met een gezamenlijk inkomen tot circa <strong>€ 56.412</strong> krijgen het hoogste percentage: <strong>96%</strong>.</li><li>Rekent je opvang meer dan de maximale uurprijs, dan betaal je dat verschil zelf.</li><li>Maximaal ongeveer <strong>230 uur per maand per kind</strong> wordt vergoed.</li></ol>',
body=(
'<h2 id="what">Hoe wordt het berekend?</h2><p>De formule: <strong>vergoeding = uren × min(werkelijke uurprijs, maximale uurprijs) × vergoedingspercentage</strong>. Het percentage hangt af van je gezamenlijk inkomen en is in 2026 96% voor gezinnen tot circa € 56.412; daarboven krijg je een lager percentage, in 2026 wel hoger dan in 2025.</p>'
'<h2 id="max">Maximale uurprijzen 2026</h2>'
+T([['Dagopvang','11,23'],['Buitenschoolse opvang (bso)','9,98'],['Gastouderopvang','8,49']],['Soort opvang','Maximale uurprijs (€/uur)'])
+'<p>Volgens Rijksoverheid wordt per kind maximaal <strong>230 uur per maand</strong> vergoed.</p>'
'<h2 id="example">Rekenvoorbeeld</h2><p>Gezin met gezamenlijk inkomen € 50.000 (96%-klasse), één kind in de dagopvang, 100 uur per maand, uurprijs van de opvang € 12,00:</p><ul><li>Gebruikte uurprijs = min(12,00; 11,23) = <strong>11,23</strong></li><li>Vergoeding per uur = 11,23 × 0,96 = <strong>€ 10,78</strong> (10,7808)</li><li>Toeslag per maand = 11,23 × 0,96 × 100 ≈ <strong>€ 1.078,08</strong></li><li>Rekening opvang = 12,00 × 100 = € 1.200</li><li>Eigen bijdrage ≈ <strong>€ 121,92</strong> per maand: 4% van € 11,23 over de uren, plus het verschil boven de maximale uurprijs (€ 0,77 per uur).</li></ul><p>Rekent de opvang precies € 11,23, dan betaal je alleen de 4% (circa € 44,92 per maand voor 100 uur).</p>'
'<h2 id="who">Wie komt in aanmerking?</h2><ul><li>Beide ouders (of de enige ouder) <strong>werken</strong>, studeren of volgen een traject dat volgens Toeslagen telt; lees de actuele voorwaarden voor jouw situatie.</li><li>De opvang moet <strong>erkend en geregistreerd</strong> zijn (kinderdagverblijf, bso of geregistreerd gastouder), geen informele afspraak.</li><li>Jouw inkomen en dat van je toeslagpartner tellen mee; zie <a href="/nl/articles/toeslagpartner-guide.html">de gids over de toeslagpartner</a>.</li></ul>'
'<h2 id="apply">Aanvragen in stappen</h2><ol><li>Kies een geregistreerde opvang en maak een schriftelijke overeenkomst met registratiegegevens.</li><li>Log in op “Mijn toeslagen” met DigiD en vraag aan <strong>vóór</strong> of bij de start van de opvang; te laat aanvragen kan maanden vergoeding kosten.</li><li>Vul verwachte uren, uurprijs en je volledige jaarinkomen in.</li><li>Geef wijzigingen in uren, prijs, werk, inkomen of opvang direct door.</li><li>Na het jaar volgt de definitieve berekening; zijn je schattingen onjuist, dan kun je moeten terugbetalen.</li></ol>'
'<h2 id="mistakes">Veelgemaakte fouten</h2><ul><li><strong>Denken dat 96% van je hele rekening wordt vergoed.</strong> Het percentage geldt voor de maximale uurprijs.</li><li><strong>Te laat aanvragen.</strong></li><li><strong>Te veel uren schatten</strong>, waardoor je later terug moet betalen.</li><li><strong>Werkwijzigingen niet melden.</strong> Werkloos worden of minder uren werken kan het recht veranderen.</li><li><strong>Niet-erkende opvang gebruiken.</strong></li></ul>'
'<h2 id="glossary">Begrippen</h2><ul><li><strong>Dagopvang:</strong> kinderdagverblijf.</li><li><strong>Bso:</strong> buitenschoolse opvang.</li><li><strong>Gastouder:</strong> opvang bij een geregistreerde gastouder thuis.</li><li><strong>Toetsingsinkomen:</strong> het inkomen waarmee Toeslagen rekent.</li></ul>'),
faq=[('Is de vergoeding 96% van wat ik de opvang betaal?','Nee. Het is 96% van de <em>maximale uurprijs</em> (€ 11,23 voor dagopvang in 2026), niet van de prijs die de opvang rekent.'),
('Wat zijn de maximale uurprijzen in 2026?','€ 11,23 dagopvang, € 9,98 bso en € 8,49 gastouder.'),
('Tot welk inkomen krijg ik 96%?','Volgens Rijksoverheid tot een gezamenlijk inkomen van circa € 56.412 in 2026.'),
('Moet ik vóór de start van de opvang aanvragen?','Ja, aanvragen bij de start of daarvóór is verstandig; te laat aanvragen kan vergoeding kosten.')],
src_note='Rijksoverheid en Dienst Toeslagen geraadpleegd op 4 oktober 2026. Inkomensklassen boven € 56.412 staan hier niet uitgewerkt; gebruik de officiële proefberekening.')
