from a_student_finance import T
SLUG='kinderbijslag-guide'
SRC=[('SVB · Bedragen en betaaldagen kinderbijslag','https://www.svb.nl/nl/kinderbijslag/bedragen-betaaldagen/bedragen-kinderbijslag'),
('SVB · Voor welke kinderen krijgt u kinderbijslag','https://www.svb.nl/nl/kinderbijslag/kinderbijslag-voor-uw-kind/voor-welke-kinderen-krijgt-u-kinderbijslag'),
('SVB · Onderwijs kinderen 16 en 17 jaar','https://www.svb.nl/nl/kinderbijslag/uw-kind-is-16-of-ouder/onderwijs-als-uw-kind-16-of-17-jaar-is'),
('SVB · Kinderbijslag aanvragen','https://www.svb.nl/nl/kinderbijslag/hoe-vraagt-u-kinderbijslag-aan/kinderbijslag-aanvragen'),
('SVB · Nieuws: kinderbijslag per 1 juli 2026 omhoog','https://www.svb.nl/nl/kinderbijslag/nieuws/kinderbijslag-gaat-per-1-juli-2026-omhoog')]
AR=dict(title='Kinderbijslag 2026: مبالغ مخصصات الأطفال من SVB وكيف تطلبها',
crumb='Kinderbijslag',
seo_title='مخصصات الأطفال kinderbijslag 2026',
desc='مخصصات الأطفال kinderbijslag 2026: من 298.40 إلى 426.29 يورو لكل طفل في الربع حسب العمر. مواعيد الدفع، شروط عمر 16 و17، والطلب عبر Mijn SVB.',
summary='<ol><li>Kinderbijslag مساهمة من الدولة في تكاليف تربية الطفل تدفعها <strong>SVB كل ربع سنة</strong>، لكل طفل دون 18 سنة.</li><li>المبلغ حسب عمر الطفل. من الربع الثالث 2026 (يبدأ 1 يوليو): <strong>298.40</strong> يورو (0–5 سنوات)، <strong>362.35</strong> (6–11)، <strong>426.29</strong> (12–17) لكل طفل في الربع.</li><li>الدفع يكون <strong>بعد انتهاء الربع</strong>؛ أول دفعة بالمبلغ الجديد وصلت في 1 أكتوبر 2026.</li><li>للطفل 16–17 سنة شروط خاصة: دراسة أو شهادة startkwalificatie أو إعفاء منها.</li><li>kinderbijslag غير kindgebonden budget وغير kinderopvangtoeslag؛ ثلاثة أنظمة بجهات مختلفة.</li></ol>',
body=(
'<h2 id="amounts">كم تبلغ Kinderbijslag في 2026؟</h2><p>المبالغ <strong>لكل طفل في الربع الواحد</strong> (3 أشهر)، من صفحة SVB الرسمية:</p>'
+T([['0 إلى 5 سنوات','295.07','298.40'],['6 إلى 11 سنة','358.30','362.35'],['12 إلى 17 سنة','421.53','426.29']],['عمر الطفل','الربع 1 و2 من 2026','الربع 3 من 2026 (من 1 يوليو)'])
+'<p>تُدفع المبالغ بعد انتهاء الربع. مواعيد الدفع المعلنة في 2026: <strong>2 يناير</strong> (الربع الرابع من 2025)، <strong>1 أبريل</strong> (الربع الأول)، <strong>1 يوليو</strong> (الربع الثاني)، <strong>1 أكتوبر</strong> (الربع الثالث بالمبلغ الجديد).</p>'
'<aside class="notice"><strong>لماذا حصلتُ على المبلغ القديم رغم أن طفلي صار عمره 6 أو 12؟</strong> تقول SVB: إن لم يكن الطفل قد أتم 6 أو 12 سنة في <em>اليوم الأول</em> من الربع المدفوع، تحصل على المبلغ القديم لذلك الربع.</aside>'
'<h2 id="examples">أمثلة محسوبة</h2><ul><li><strong>طفلان، عمرهما 4 و8، الربع 3 من 2026:</strong> 298.40 + 362.35 = <strong>660.75 يورو</strong> للربع كله، أي نحو 220.25 شهرياً.</li><li><strong>نفس الأسرة في الربع 1 و2:</strong> 295.07 + 358.30 = <strong>653.37 يورو</strong> للربع. الفرق بين الفترتين 7.38 يورو في الربع.</li><li><strong>ثلاثة أطفال (3 و7 و13) في الربع 3:</strong> 298.40 + 362.35 + 426.29 = <strong>1,087.04 يورو</strong> للربع.</li></ul><p>مهم: هذه المبالغ لا ترتبط بدخلك؛ يمكن للأسرة أن تحصل على kinderbijslag مهما كان دخلها، بخلاف zorgtoeslag وkindgebonden budget. وإن كنت تربي أطفالك وحدك فراجع <a href="/articles/single-parent-support.html">دليل دعم الوالد الوحيد</a>.</p>'
'<h2 id="who">لأي أطفال تُدفع؟</h2><p>تُدفع للأطفال دون <strong>18 سنة</strong>: ولدك طبعاً، وأحياناً أطفال آخرون:</p><ul><li><strong>طفل شريكك يسكن معك:</strong> تحددان معاً من يتلقى المبلغ. إن كانت هناك اتفاقات مع الوالد الآخر (مثل co-ouderschap) فالاتفاق يقرر أي والد يتلقاه.</li><li><strong>طفل رعاية (pleegkind):</strong> يمكن تلقيها بشرط ألا تتلقى تعويض رعاية (pleegvergoeding).</li><li><strong>طفل تربيه كطفلك:</strong> بشروط (مثلاً ألا يتلقاها شخص آخر لنفس الطفل). إن بقي للطفل والد طبيعي فهو يتلقاها عادةً ويمكنه ترتيب أن تُدفع إلى حسابك.</li></ul>'
'<h2 id="age16">الأطفال بعمر 16 و17</h2><p>القواعد تختلف عن الأطفال الأصغر. لتستمر kinderbijslag يجب أن يكون الطفل:</p><ul><li>يدرس (vmbo أو havo أو vwo أو MBO مستوى 2 فأعلى أو HBO أو vavo؛ راجع <a href="/articles/dutch-school-system-basisschool.html">دليل المدرسة والتعليم الإلزامي</a>)، أو</li><li>حاصلاً على <strong>startkwalificatie</strong>، أو</li><li>معفى من شرط startkwalificatie.</li></ul><p>ولطفل لم يحصل بعد على startkwalificatie تستمر kinderbijslag ما دام يذهب إلى المدرسة نهاراً. وإن كان الطفل <strong>لا يسكن معك</strong> فيمكن تلقيها إذا أنفقت <strong>540 يورو في الربع</strong> على إعالته (حسب صفحة SVB الحالية).</p>'
'<h2 id="apply">كيف تطلبها وتتحقق منها؟</h2><ol><li>بعد ولادة <strong>طفلك الأول</strong> قد ترسل لك SVB رسالة تقول إن بإمكانك الطلب، فيكون الطلب جاهزاً داخل <strong>Mijn SVB</strong>. عن خطوات ما بعد الولادة راجع <a href="/articles/pregnancy-newborn-care.html">دليل الحمل والولادة</a> و<a href="/articles/birth-parental-leave.html">إجازات الولادة والوالدين</a>.</li><li>إن لم تصلك رسالة أو كنت قادماً حديثاً أو طفلك وصل إلى هولندا، افتح الصفحة الرسمية واختر حالتك.</li><li>ادخل Mijn SVB بـ DigiD ودقق في بيانات الطفل واسم مقدم الطلب.</li><li>احفظ التأكيد والقرار.</li><li>أبلغ SVB بأي تغيير في الأسرة (انتقال طفل، سفر، زواج، سكن) عبر «Wijzigingen doorgeven».</li></ol><p>لا تعتبر غياب الرسالة دليلاً على الرفض ولا على أنك لا تستحق؛ راجع حالتك مباشرة لدى SVB.</p>'
'<h2 id="related">الفرق بين kinderbijslag وما يشبهها</h2>'
+T([['<strong>Kinderbijslag</strong>','SVB','لا يرتبط بالدخل. حسب عمر الطفل. كل ربع.'],['<strong>Kindgebonden budget</strong>','Dienst Toeslagen','يرتبط بالدخل والأصول. شرطه أن تتلقى kinderbijslag (انظر <a href="/articles/kindgebonden-budget-guide.html">الدليل</a>).'],['<strong>Kinderopvangtoeslag</strong>','Dienst Toeslagen','لتكاليف الحضانة للأبوين العاملين (<a href="/articles/childcare-allowance-kinderopvangtoeslag.html">الدليل</a>).']],['الاسم','الجهة','الفكرة'])
+'<h2 id="mistakes">أخطاء شائعة</h2><ul><li><strong>الخلط بين الأنظمة الثلاثة.</strong> كل نظام له جهة وشروط ومواعيد.</li><li><strong>افتراض أن الدفع شهري.</strong> هو ربع سنوي ويأتي بعد انتهاء الربع.</li><li><strong>عدم إبلاغ SVB بتغيير</strong> (طفل يسافر للعيش خارج هولندا، أو يتوقف عن الدراسة عند 16–17) فتتراكم مبالغ قد تُسترد.</li><li><strong>الانتظار بلا تحقق.</strong> إن لم تصلك رسالة بعد ولادة طفلك الأول فاسأل SVB.</li></ul>'
'<h2 id="glossary">مسرد</h2><ul><li><strong>Kwartaal:</strong> ربع سنة (3 أشهر).</li><li><strong>Startkwalificatie:</strong> مؤهل أساسي (MBO مستوى 2 فأعلى أو havo أو vwo).</li><li><strong>Co-ouderschap:</strong> رعاية مشتركة بين الوالدين.</li><li><strong>Pleegkind:</strong> طفل في رعاية أسرة بديلة.</li></ul>'),
faq=[('هل تتوقف kinderbijslag إذا كان دخلي مرتفعاً؟','لا. kinderbijslag لا ترتبط بدخل الوالدين. المرتبط بالدخل هو kindgebonden budget.'),
('كم مرة تُدفع في السنة؟','أربع مرات، كل ربع سنة، بعد انتهاء الربع (2 يناير و1 أبريل و1 يوليو و1 أكتوبر في 2026).'),
('هل تُدفع لطفل عمره 17 ولا يدرس؟','قد لا تُدفع. للطفل 16–17 يجب أن يدرس أو يملك startkwalificatie أو يكون معفىً منها.'),
('هل يجب أن أطلبها دائماً؟','ليس دائماً؛ بعد ولادة الطفل الأول قد تصلك رسالة من SVB. في حالات أخرى (قدوم طفل، انتقال) راجع إجراء حالتك.')],
src_note='راجعنا صفحات SVB في 4 أكتوبر 2026 (مبالغ 2026). المبالغ تتغير كل ربع تقريباً؛ تحقق من الصفحة الحالية.')
NL=dict(title='Kinderbijslag 2026: bedragen van de SVB en hoe je het aanvraagt',
crumb='Kinderbijslag',
seo_title='Kinderbijslag 2026: bedragen en aanvragen',
desc='Kinderbijslag 2026: € 298,40 tot € 426,29 per kind per kwartaal, naar leeftijd. Betaaldagen, regels bij 16 en 17 jaar en aanvragen via Mijn SVB.',
summary='<ol><li>Kinderbijslag is een bijdrage van de overheid in de kosten van een kind, <strong>per kwartaal uitbetaald door de SVB</strong>, voor kinderen jonger dan 18.</li><li>Het bedrag hangt af van de leeftijd. Vanaf het derde kwartaal 2026 (1 juli): <strong>€ 298,40</strong> (0–5 jaar), <strong>€ 362,35</strong> (6–11) en <strong>€ 426,29</strong> (12–17) per kind per kwartaal.</li><li>Betaling volgt <strong>na afloop van het kwartaal</strong>; het nieuwe bedrag kwam voor het eerst begin oktober 2026.</li><li>Voor kinderen van 16 en 17 gelden extra regels: onderwijs, startkwalificatie of vrijstelling.</li><li>Kinderbijslag is niet hetzelfde als kindgebonden budget of kinderopvangtoeslag: drie regelingen, andere instanties.</li></ol>',
body=(
'<h2 id="amounts">Hoeveel kinderbijslag krijg je in 2026?</h2><p>De bedragen gelden <strong>per kind per kwartaal</strong>, volgens de officiële SVB-pagina:</p>'
+T([['0 t/m 5 jaar','€ 295,07','€ 298,40'],['6 t/m 11 jaar','€ 358,30','€ 362,35'],['12 t/m 17 jaar','€ 421,53','€ 426,29']],['Leeftijd kind','1e en 2e kwartaal 2026','3e kwartaal 2026 (vanaf 1 juli)'])
+'<p>Uitbetaling vindt plaats na afloop van het kwartaal. Betaaldagen in 2026: <strong>2 januari</strong> (4e kwartaal 2025), <strong>1 april</strong> (1e kwartaal), <strong>1 juli</strong> (2e kwartaal) en <strong>1 oktober</strong> (3e kwartaal, nieuw bedrag).</p>'
'<aside class="notice"><strong>Waarom krijg ik het oude bedrag terwijl mijn kind 6 of 12 is geworden?</strong> Volgens de SVB: was je kind op de <em>eerste dag</em> van het te betalen kwartaal nog geen 6 of 12, dan krijg je voor dat kwartaal nog het oude bedrag.</aside>'
'<h2 id="examples">Rekenvoorbeelden</h2><ul><li><strong>Twee kinderen van 4 en 8, 3e kwartaal 2026:</strong> 298,40 + 362,35 = <strong>€ 660,75</strong> per kwartaal, ongeveer € 220,25 per maand.</li><li><strong>Hetzelfde gezin in het 1e en 2e kwartaal:</strong> 295,07 + 358,30 = <strong>€ 653,37</strong>. Het verschil is € 7,38 per kwartaal.</li><li><strong>Drie kinderen (3, 7 en 13), 3e kwartaal:</strong> 298,40 + 362,35 + 426,29 = <strong>€ 1.087,04</strong> per kwartaal.</li></ul><p>Belangrijk: deze bedragen hangen niet af van je inkomen. Anders dan zorgtoeslag en kindgebonden budget. Voed je je kinderen alleen op, zie dan onze <a href="/nl/articles/single-parent-support.html">gids over steun voor alleenstaande ouders</a>.</p>'
'<h2 id="who">Voor welke kinderen?</h2><p>Voor kinderen jonger dan <strong>18 jaar</strong>: je eigen kind en soms andere kinderen:</p><ul><li><strong>Kind van je partner dat bij je woont:</strong> jullie bepalen samen wie de kinderbijslag krijgt. Zijn er afspraken met de andere ouder (bijvoorbeeld co-ouderschap), dan hangt het van die afspraken af.</li><li><strong>Pleegkind:</strong> mogelijk als je geen pleegvergoeding krijgt.</li><li><strong>Kind dat je verzorgt alsof het je eigen kind is:</strong> onder voorwaarden (bijvoorbeeld dat niemand anders kinderbijslag voor het kind krijgt). Heeft het kind nog een natuurlijke ouder, dan krijgt die meestal de kinderbijslag; die ouder kan regelen dat het op jouw rekening komt.</li></ul>'
'<h2 id="age16">Kinderen van 16 en 17</h2><p>De regels verschillen van die voor jongere kinderen. Je kind moet:</p><ul><li>onderwijs volgen (vmbo, havo, vwo, mbo niveau 2 of hoger, hbo of vavo; zie onze <a href="/nl/articles/dutch-school-system-basisschool.html">gids over school en leerplicht</a>), of</li><li>een <strong>startkwalificatie</strong> hebben, of</li><li>vrijstelling van de startkwalificatie hebben.</li></ul><p>Heeft je kind nog geen startkwalificatie, dan krijg je kinderbijslag zolang het overdag naar school gaat. Woont het kind <strong>niet thuis</strong>, dan kun je kinderbijslag krijgen als je <strong>€ 540 per kwartaal</strong> aan het onderhoud besteedt (volgens de huidige SVB-pagina).</p>'
'<h2 id="apply">Aanvragen en controleren</h2><ol><li>Is je <strong>eerste kind</strong> geboren, dan stuurt de SVB je mogelijk een bericht dat je kinderbijslag kunt aanvragen; de aanvraag staat dan klaar in <strong>Mijn SVB</strong>. Wat je verder rond de geboorte regelt, lees je in <a href="/nl/articles/pregnancy-newborn-care.html">zwanger en bevallen</a> en <a href="/nl/articles/birth-parental-leave.html">geboorte- en ouderschapsverlof</a>.</li><li>Kreeg je geen bericht, ben je net in Nederland of komt je kind hier wonen? Open de officiële pagina en kies je situatie.</li><li>Log in op Mijn SVB met DigiD en controleer de gegevens van je kind en de aanvrager.</li><li>Bewaar de bevestiging en het besluit.</li><li>Geef wijzigingen (kind verhuist, gezin verandert, kind stopt met school) door via “Wijzigingen doorgeven”.</li></ol><p>Geen bericht ontvangen betekent niet dat je geen recht hebt; vraag het na bij de SVB.</p>'
'<h2 id="related">Verschil met vergelijkbare regelingen</h2>'
+T([['<strong>Kinderbijslag</strong>','SVB','Niet inkomensafhankelijk. Per leeftijd. Per kwartaal.'],['<strong>Kindgebonden budget</strong>','Dienst Toeslagen','Inkomens- en vermogensafhankelijk. Recht heeft de ouder met kinderbijslag (zie <a href="/nl/articles/kindgebonden-budget-guide.html">gids</a>).'],['<strong>Kinderopvangtoeslag</strong>','Dienst Toeslagen','Voor kosten van kinderopvang bij werkende ouders (<a href="/nl/articles/childcare-allowance-kinderopvangtoeslag.html">gids</a>).']],['Naam','Instantie','Kern'])
+'<h2 id="mistakes">Veelgemaakte fouten</h2><ul><li><strong>De drie regelingen door elkaar halen.</strong> Elk heeft eigen instantie, voorwaarden en data.</li><li><strong>Denken dat het maandelijks wordt betaald.</strong> Het is per kwartaal, achteraf.</li><li><strong>Wijzigingen niet doorgeven</strong> (kind gaat buiten Nederland wonen, stopt met school op 16–17); dan kan achteraf terugbetaling volgen.</li><li><strong>Afwachten zonder te controleren.</strong> Kreeg je na de geboorte van je eerste kind geen bericht, vraag het dan na bij de SVB.</li></ul>'
'<h2 id="glossary">Begrippen</h2><ul><li><strong>Kwartaal:</strong> drie maanden.</li><li><strong>Startkwalificatie:</strong> basiskwalificatie (mbo niveau 2 of hoger, havo of vwo).</li><li><strong>Co-ouderschap:</strong> gedeeld ouderschap.</li><li><strong>Pleegkind:</strong> kind in een pleeggezin.</li></ul>'),
faq=[('Vervalt kinderbijslag bij een hoog inkomen?','Nee. Kinderbijslag hangt niet af van het inkomen van de ouders. Kindgebonden budget wel.'),
('Hoe vaak wordt het uitbetaald?','Vier keer per jaar, per kwartaal achteraf (in 2026 op 2 januari, 1 april, 1 juli en 1 oktober).'),
('Krijg ik het voor een kind van 17 dat niet studeert?','Mogelijk niet. Bij 16 en 17 moet het kind onderwijs volgen, een startkwalificatie hebben of vrijgesteld zijn.'),
('Moet ik het altijd zelf aanvragen?','Niet altijd; na de geboorte van je eerste kind kan de SVB je een bericht sturen. In andere situaties kies je je situatie op de SVB-site.')],
src_note='SVB-pagina’s geraadpleegd op 4 oktober 2026 (bedragen 2026). Bedragen wijzigen regelmatig; controleer de actuele pagina.')
#xlink
AR['body']+='<p><strong>جرّب الحاسبة:</strong> <a href="/calculators/kindgebonden-budget.html">حاسبة kindgebonden budget 2026</a> تقدّر المبلغ حسب الدخل وعدد الأطفال وأعمارهم.</p>'
NL['body']+='<p><strong>Probeer de rekenhulp:</strong> <a href="/nl/calculators/kindgebonden-budget.html">Kindgebonden budget berekenen 2026</a> geeft een schatting per jaar en maand.</p>'
