from a_student_finance import T
SLUG='kvk-zzp-business-netherlands'
BD='https://www.belastingdienst.nl/wps/wcm/connect/'
SRC=[('KVK · Inschrijfvergoeding','https://www.kvk.nl/inschrijven/inschrijfvergoeding/'),
('KVK · Hulp bij inschrijven','https://www.kvk.nl/hulp-en-contact/hulp-bij-inschrijven/'),
('KVK · Wat is een geldig legitimatiebewijs?','https://www.kvk.nl/inschrijven/wat-is-een-geldig-legitimatiebewijs/'),
('Rijksoverheid · Kan ik als buitenlandse zelfstandige in Nederland werken?','https://www.rijksoverheid.nl/onderwerpen/buitenlandse-werknemers/vraag-en-antwoord/kan-ik-als-buitenlandse-zelfstandig-ondernemer-in-nederland-werken'),
('Rijksoverheid · Mogen asielzoekers werken?','https://www.rijksoverheid.nl/onderwerpen/asielbeleid/vraag-en-antwoord/mogen-asielzoekers-werken'),
('KVK · Alles over belastingen voor starters','https://www.kvk.nl/starten/alles-over-belastingen-voor-starters/'),
('Belastingdienst · Voorwaarden kleineondernemersregeling (KOR)',BD+'nl/btw/content/kor-voorwaarden'),
('Belastingdienst · Zelfstandigenaftrek en startersaftrek 2026',BD+'bldcontentnl/belastingdienst/zakelijk/winst/inkomstenbelasting/veranderingen-inkomstenbelasting-2026/ondernemersaftrek-2026/zelfstandigenaftrek-2026'),
('KVK · Het urencriterium (1.225 uur)','https://www.kvk.nl/starten/de-magische-1225-uur-alles-over-het-urencriterium/'),
('Belastingdienst · Handhaving arbeidsrelaties (Wet DBA)',BD+'nl/arbeidsrelaties/content/handhaving'),
('Rijksoverheid · Kabinet kiest voor meer rust en duidelijkheid voor zzp’ers (6-3-2026)','https://www.rijksoverheid.nl/actueel/nieuws/2026/03/06/kabinet-kiest-voor-meer-rust-en-duidelijkheid-voor-zzpers-en-opdrachtgevers'),
('Belastingdienst · Percentages bijdrage Zvw',BD+'bldcontentnl/belastingdienst/prive/werk_en_inkomen/zorgverzekeringswet/veranderingen-bijdrage-zvw/percentages-zvw'),
('Ondernemersplein · Bijstand voor zelfstandigen (Bbz)','https://ondernemersplein.overheid.nl/subsidies-en-regelingen/bijstand-voor-zelfstandigen-bbz/'),
('KVK · Plannen voor je eenmanszaak (Belastingplan 2027)','https://www.kvk.nl/wetten-en-regels/plannen-voor-je-eenmanszaak-vof-maatschap-of-cv/'),
('Rijksoverheid · Factsheetbundel Belastingplan 2027','https://www.rijksoverheid.nl/documenten/2026/09/15/factsheetbundel')]

AR=dict(title='العمل الحر (ZZP) في هولندا 2026: التسجيل في KvK، من يحق له، الضريبة المضافة وKOR، خصومات الضريبة وما يتغير في 2027، وقانون DBA',
crumb='العمل الحر وKvK',
desc='دليل عميق لبدء عمل حر (eenmanszaak) في هولندا: رسوم التسجيل في KvK والموعد والوثائق، من يحق له العمل الحر حسب الإقامة، الضريبة المضافة والإعفاء للصغار حتى 20,000 يورو، شرط 1,225 ساعة، خصم المستقل 1,200 وخصم المبتدئ 2,123 يورو في 2026 وخفضهما المقترح في 2027، خطر «المستقل الوهمي»، التأمين الصحي، والمساعدة من البلدية (Bbz).',
summary='<ol><li><strong>التسجيل في KvK:</strong> تحضّر الطلب أونلاين بـDigiD ثم تكمله في <strong>موعد شخصي</strong> بمكتب KvK. الرسوم <strong>85.15 يورو</strong> (تُعدَّل سنوياً).</li><li><strong>من يحق له:</strong> مواطنو أوروبا، و<strong>حاملو الإقامة كلاجئين</strong> بحرية كاملة. غير الأوروبيين بإقامة أخرى قد يحتاجون إقامة «عمل كمستقل». طالب اللجوء يحتاج تصريح عمل TWV.</li><li><strong>الضريبة المضافة:</strong> 21% أو 9%، وإقرار كل 3 أشهر. إن كان دخلك السنوي أقل من <strong>20,000 يورو</strong> يمكنك اختيار الإعفاء (KOR).</li><li><strong>خصومات 2026</strong> مع 1,225 ساعة عمل سنوياً: خصم المستقل <strong>1,200 يورو</strong>، وخصم المبتدئ <strong>2,123 يورو</strong>. في 2027 يُقترح خفضهما إلى 900 و<strong>10 يورو</strong>.</li><li><strong>احذر «المستقل الوهمي»:</strong> الرقابة كاملة منذ 2025، والعبرة بطريقة عملك الفعلية لا بالعقد.</li></ol>',
body=(
'<h2 id="who">هل يحق لك العمل الحر؟</h2>'
+T([['مواطن الاتحاد الأوروبي/EEA/سويسرا','نعم، دون تصريح.'],
    ['حامل إقامة لجوء (statushouder)','نعم، بحقوق عمل كاملة مثل المواطن الهولندي، ومنها العمل الحر.'],
    ['غير أوروبي بإقامة أخرى','حسب تصريحك؛ بعض الإقامات تحتاج إقامة خاصة «عمل كمستقل» من IND، التي تفحص دخلاً مستقلاً ومستداماً وكافياً.'],
    ['طالب لجوء','بعد 6 أشهر من الطلب، وبتصريح TWV فقط (يطلبه الزبون من UWV). ومن 12 يونيو 2026 لا يحق العمل لطالبي اللجوء من «دول آمنة» أو من قدّم معلومات خاطئة أو لديه قرار نقل أوروبي.']],
   ['حالتك','العمل الحر'])
+'<h2 id="register">التسجيل في KvK خطوة بخطوة</h2><ol><li><strong>جهّز الطلب أونلاين</strong> بـDigiD (لازم BSN للـeenmanszaak).</li><li><strong>احجز موعداً</strong> في مكتب KvK (حتى 8 أسابيع مسبقاً). التسجيل يصبح رسمياً فقط بعد الموعد والتحقق من هويتك.</li><li><strong>الوثائق:</strong> هوية سارية: جواز سفر هولندي أو أجنبي، رخصة قيادة هولندية، بطاقة إقامة هولندية، أو جواز لاجئ/أجنبي. جواز الطوارئ غير مقبول. إن كان عنوان العمل غير عنوان سكنك: عقد إيجار أو إذن.</li><li><strong>ادفع الرسوم:</strong> 85.15 يورو.</li><li><strong>رقم KvK:</strong> فوراً إن سجّلت خلال أسبوع قبل أو بعد بدء العمل؛ أو بالبريد في أسبوع البدء إن سجلت مبكراً (حتى 3 أشهر).</li><li><strong>من Belastingdienst:</strong> يصلك رقم الضريبة المضافة خلال أسبوعين من البدء، ورقم btw-id منفصلاً.</li></ol>'
'<h2 id="btw">الضريبة المضافة (btw) والإعفاء KOR</h2><ul><li><strong>النسب:</strong> 21% عادة، و9% لبعض السلع والخدمات، و0% في حالات خاصة. منذ 1 يناير 2026 أصبحت الفنادق وأماكن الإقامة السياحية 21%.</li><li><strong>الإقرار:</strong> كل ربع سنة؛ المواعيد حسب KvK: 30 أبريل، 31 يوليو، 31 أكتوبر، 31 يناير.</li><li><strong>KOR (نظام الشركات الصغيرة):</strong> إن كان رقم أعمالك أقل من <strong>20,000 يورو</strong> سنوياً (في السنة الحالية والسابقة) يمكنك اختيار عدم فرض الضريبة المضافة. لكنك عندها <strong>لا تسترد</strong> الضريبة المضافة على مشترياتك. مناسب لخدمات قليلة التكاليف.</li></ul>'
'<h2 id="income-tax">ضريبة الدخل: الخصومات الخاصة بالمستقلين</h2>'
+T([['شرط الساعات (urencriterium)','1,225 ساعة على الأقل في السنة لعملك','1,225 ساعة'],
    ['خصم المستقل (zelfstandigenaftrek)','1,200 يورو (600 من سن AOW)','<strong>900 يورو</strong> (مقترح)'],
    ['خصم المبتدئ (startersaftrek)','2,123 يورو، إن لم تكن مستقلاً في سنة على الأقل من آخر 5 سنوات واستخدمت خصم المستقل مرتين كحد أقصى','<strong>10 يورو</strong> (مقترح)، والإلغاء 2028'],
    ['إعفاء أرباح الشركات الصغيرة (MKB-winstvrijstelling)','12.7% من الربح بعد الخصومات','لم يُؤكد بعد'],
    ['مساهمة التأمين الصحي على الربح (Zvw)','4.85% حتى ربح 79,409 يورو','—']],
   ['البند','2026','2027'])
+'<p><strong>ما يعنيه هذا عملياً:</strong> 2026 هي آخر سنة بخصم المبتدئ الكامل حسب الخطة الحالية. احتفظ بسجل ساعات دقيق (التقويم، الفواتير، المواعيد)، لأن Belastingdienst قد تطلب الإثبات. الخصومات تُحسب بنسبة 37.56% كحد أقصى في 2026. شرح الإقرار السنوي في <a href="/articles/annual-tax-return-2026.html">دليل الإقرار الضريبي</a>.</p>'
'<h2 id="dba">«المستقل الوهمي» وقانون DBA</h2><ul><li>منذ <strong>1 يناير 2025</strong> تراقب Belastingdienst بالكامل هل أنت فعلاً مستقل أم موظف متخفٍ.</li><li>من <strong>1 يناير 2026</strong> يمكن فرض غرامات على المخالفات المقصودة.</li><li><strong>العبرة بطريقة العمل الفعلية</strong>: هل يحدد الزبون ساعاتك وطريقة عملك؟ هل تعمل كموظف ضمن فريقه؟ هل لديك زبون واحد لفترة طويلة؟ هذه إشارات خطر.</li><li>أكدت الحكومة في 6 مارس 2026 أن الرقابة الكاملة باقية. وهناك اقتراح «قانون المستقلين» من 2028 (مقترح فقط).</li><li>إن كان العمل في الحقيقة وظيفة، فعقد العمل يعطيك حماية أكبر: أجر في المرض، وإجازة، وتعويض فصل (<a href="/articles/employment-contracts-labor-law-2026.html">دليل عقد العمل</a>).</li></ul>'
'<h2 id="insurance">التأمين والتقاعد</h2><ul><li><strong>التأمين الصحي</strong> إلزامي كالجميع، وتدفع مساهمة Zvw على ربحك (4.85% في 2026).</li><li><strong>تأمين العجز:</strong> لا يوجد تأمين إلزامي حتى الآن. هناك مشروع قانون لتأمين أساسي إلزامي للمستقلين، والتاريخ المتوقع حسب KvK هو 2030، لكنه غير مقرر بعد. فكّر في تأمين خاص أو احتياطي مالي.</li><li><strong>التقاعد:</strong> لا يُبنى لك تقاعد تكميلي تلقائياً؛ خطط بنفسك.</li></ul>'
'<h2 id="help">مساعدة للبدء</h2><ul><li><strong>Bbz (المساعدة الاجتماعية للمستقلين):</strong> من البلدية لمن يبدأ من مساعدة اجتماعية أو WW أو إعانة عجز: دخل مؤقت أو رأس مال (غالباً قرض).</li><li><strong>KvK وOndernemersplein:</strong> نصائح مجانية للمبتدئين.</li><li><strong>البدلات:</strong> للمستقل يُحسب دخله لـToeslagen من الربح النهائي. قدّر ربحك <strong>أعلى قليلاً</strong> وحدّثه مع كل إقرار ضريبة مضافة (<a href="/articles/toeslagen-income-update.html">كيف تحدّث دخلك</a>).</li></ul>'
'<h2 id="checklist">قائمة البدء</h2><ol><li>تأكد أن إقامتك تسمح بالعمل الحر.</li><li>اختر اسماً ونشاطاً واضحاً، وافحص أن الاسم غير مستخدم.</li><li>احجز موعد KvK وجهّز الهوية والعنوان.</li><li>افتح حساباً بنكياً منفصلاً للعمل.</li><li>قرر: KOR أم لا؟</li><li>اضبط نظام فواتير وسجل ساعات من اليوم الأول.</li><li>ادّخر جزءاً من كل دفعة للضريبة (ضريبة الدخل والمضافة).</li><li>افحص عقودك مع الزبائن ضد خطر «المستقل الوهمي».</li><li>حدّث تقدير دخلك في Toeslagen.</li></ol>'
'<h2 id="mistakes">أخطاء شائعة</h2><ol><li>صرف مبلغ الضريبة المضافة المحصّل كأنه دخل.</li><li>عدم تسجيل الساعات ثم فقدان الخصومات.</li><li>العمل لزبون واحد بشروط موظف دون فهم المخاطر.</li><li>نسيان إقرار ربع السنة ولو كان صفراً.</li><li>تقدير ربح منخفض في Toeslagen ثم الاسترداد.</li></ol>'),
faq=[('كم تكلف التسجيل في KvK؟','85.15 يورو للتسجيل الأول، والرسوم تُعدَّل سنوياً.'),
('هل يمكنني التسجيل أونلاين بالكامل؟','لا للـeenmanszaak: تحضّر أونلاين ثم تكمل في موعد شخصي في مكتب KvK.'),
('أنا لاجئ بإقامة، هل يحق لي العمل الحر؟','نعم، حاملو إقامة اللجوء لهم حقوق عمل كاملة ومنها العمل الحر.'),
('ما هو KOR؟','نظام إعفاء من الضريبة المضافة لمن رقم أعماله السنوي أقل من 20,000 يورو؛ لكنك لا تسترد الضريبة على مشترياتك.'),
('هل سيُلغى خصم المبتدئ؟','حسب خطة الضرائب 2027 (مقترح): يصبح 10 يورو في 2027 ويُلغى في 2028. لذلك 2026 آخر سنة بالمبلغ الكامل 2,123 يورو.'),
('هل التأمين ضد العجز إلزامي؟','ليس بعد. هناك مشروع قانون، والتاريخ المتوقع حسب KvK 2030، لكنه غير مقرر.')],
src_note='راجعنا القواعد والمبالغ في KvK وBelastingdienst وRijksoverheid وOndernemersplein في 4 أكتوبر 2026. أرقام 2027 مقترحة حتى يقرها البرلمان. رسوم KvK معروضة دون سنة محددة على صفحتها.')

NL=dict(title='Zzp’er worden in 2026: inschrijven bij KVK, wie mag zelfstandig werken, btw en KOR, ondernemersaftrek en wat er in 2027 verandert, en de Wet DBA',
crumb='Zzp en KVK',
desc='Uitgebreide gids voor starters met een eenmanszaak: inschrijfvergoeding en afspraak bij KVK, verblijfsvergunning en zelfstandig werken, btw en de KOR tot € 20.000, het urencriterium van 1.225 uur, zelfstandigenaftrek € 1.200 en startersaftrek € 2.123 in 2026 met de voorgestelde verlaging in 2027, schijnzelfstandigheid, Zvw-bijdrage en de Bbz.',
summary='<ol><li><strong>KVK-inschrijving:</strong> online voorbereiden met DigiD en afronden op een <strong>afspraak</strong> bij een KVK-kantoor. Inschrijfvergoeding <strong>€ 85,15</strong> (jaarlijks aangepast).</li><li><strong>Wie mag:</strong> EU-burgers en <strong>asielstatushouders</strong> volledig. Andere niet-EU-burgers hebben soms een vergunning «arbeid als zelfstandige» nodig; asielzoekers alleen met TWV.</li><li><strong>Btw:</strong> 21% of 9%, aangifte per kwartaal; onder <strong>€ 20.000</strong> omzet kun je kiezen voor de KOR.</li><li><strong>Aftrek 2026</strong> bij 1.225 uur: zelfstandigenaftrek <strong>€ 1.200</strong>, startersaftrek <strong>€ 2.123</strong>. Voorstel 2027: € 900 en <strong>€ 10</strong>.</li><li><strong>Schijnzelfstandigheid:</strong> volledige handhaving sinds 2025; het gaat om hoe je werkelijk werkt.</li></ol>',
body=(
'<h2 id="who">Mag jij zelfstandig werken?</h2>'
+T([['EU/EER/Zwitserland','Ja, zonder vergunning.'],['Asielstatushouder','Ja, volledig, net als een Nederlander.'],['Niet-EU met andere vergunning','Afhankelijk van je vergunning; soms een vergunning «arbeid als zelfstandige» van de IND (toets op zelfstandig, duurzaam en voldoende inkomen).'],['Asielzoeker','Na 6 maanden en alleen met TWV (aangevraagd door de opdrachtgever bij UWV). Sinds 12 juni 2026 niet voor asielzoekers uit veilige landen, bij onjuiste informatie of een EU-overdrachtsbesluit.']],['Situatie','Zelfstandig werken'])
+'<h2 id="register">Inschrijven bij KVK</h2><ol><li><strong>Online voorbereiden</strong> met DigiD (BSN nodig voor een eenmanszaak).</li><li><strong>Afspraak maken</strong> bij een KVK-kantoor (tot 8 weken vooruit); pas na de afspraak en identiteitscontrole ben je ingeschreven.</li><li><strong>Documenten:</strong> geldig ID (Nederlands of buitenlands paspoort, Nederlands rijbewijs, verblijfsdocument, vreemdelingen- of vluchtelingenpaspoort; geen noodpaspoort). Ander bedrijfsadres dan woonadres: huurcontract of toestemming.</li><li><strong>Betalen:</strong> € 85,15.</li><li><strong>KVK-nummer:</strong> direct bij inschrijving binnen 1 week voor of na de start; bij vroeger inschrijven (tot 3 maanden) per post in je startweek.</li><li><strong>Belastingdienst:</strong> omzetbelastingnummer binnen 2 weken na de start, btw-id apart.</li></ol>'
'<h2 id="btw">Btw en KOR</h2><ul><li><strong>Tarieven:</strong> 21%, 9% en 0% in bijzondere gevallen; hotels en vakantieverblijven sinds 1 januari 2026 21%.</li><li><strong>Aangifte</strong> per kwartaal (volgens KVK uiterlijk 30 april, 31 juli, 31 oktober, 31 januari).</li><li><strong>KOR:</strong> bij een omzet onder <strong>€ 20.000</strong> per jaar (dit en vorig jaar) kun je kiezen geen btw te rekenen; je kunt dan geen btw aftrekken.</li></ul>'
'<h2 id="income-tax">Inkomstenbelasting: ondernemersaftrek</h2>'
+T([['Urencriterium','minimaal 1.225 uur per jaar','1.225 uur'],['Zelfstandigenaftrek','€ 1.200 (AOW-leeftijd € 600)','<strong>€ 900</strong> (voorstel)'],['Startersaftrek','€ 2.123 (niet ondernemer in ≥1 van de 5 vorige jaren, max. 2× zelfstandigenaftrek)','<strong>€ 10</strong> (voorstel), afgeschaft 2028'],['MKB-winstvrijstelling','12,7% van de winst na ondernemersaftrek','nog niet bevestigd'],['Bijdrage Zvw over winst','4,85% tot € 79.409','—']],['Onderdeel','2026','2027'])
+'<p>2026 is volgens de huidige plannen het laatste jaar met de volledige startersaftrek. Houd een sluitende urenregistratie bij. Het voordeel van de aftrek wordt in 2026 tegen maximaal 37,56% berekend. Zie ook <a href="/nl/articles/annual-tax-return-2026.html">aangifte inkomstenbelasting</a>.</p>'
'<h2 id="dba">Schijnzelfstandigheid en de Wet DBA</h2><ul><li>Sinds <strong>1 januari 2025</strong> handhaaft de Belastingdienst weer volledig.</li><li>Vanaf <strong>1 januari 2026</strong> zijn vergrijpboetes mogelijk.</li><li><strong>Het gaat om de praktijk:</strong> bepaalt de opdrachtgever je werktijden en werkwijze, werk je als een werknemer in zijn team, heb je langdurig één opdrachtgever? Dat zijn risicosignalen.</li><li>Het kabinet bevestigde op 6 maart 2026 dat volledige handhaving blijft. Een Zelfstandigenwet per 2028 is alleen een voorstel.</li><li>Is het eigenlijk een baan, dan geeft een arbeidscontract meer bescherming (<a href="/nl/articles/employment-contracts-labor-law-2026.html">arbeidscontract</a>).</li></ul>'
'<h2 id="insurance">Verzekeringen en pensioen</h2><ul><li><strong>Zorgverzekering</strong> verplicht; Zvw-bijdrage over je winst (4,85% in 2026).</li><li><strong>Arbeidsongeschiktheid:</strong> nog geen verplichte verzekering; er ligt een wetsvoorstel voor een basisverzekering, volgens KVK verwacht in 2030, maar nog niet aangenomen.</li><li><strong>Pensioen:</strong> bouw je niet automatisch op; regel het zelf.</li></ul>'
'<h2 id="help">Hulp bij starten</h2><ul><li><strong>Bbz:</strong> via de gemeente bij starten vanuit bijstand, WW of arbeidsongeschiktheid: tijdelijk inkomen of bedrijfskapitaal (vaak lening).</li><li><strong>KVK en Ondernemersplein:</strong> gratis startersinformatie.</li><li><strong>Toeslagen:</strong> voor ondernemers telt de winst; schat liever iets te hoog en pas aan bij elke btw-aangifte (<a href="/nl/articles/toeslagen-income-update.html">inkomen doorgeven</a>).</li></ul>'
'<h2 id="checklist">Startchecklist</h2><ol><li>Check of je vergunning zelfstandig werken toestaat.</li><li>Kies naam en activiteit; controleer de naam.</li><li>KVK-afspraak, ID en adresbewijs.</li><li>Aparte zakelijke rekening.</li><li>KOR: ja of nee?</li><li>Facturatie en urenregistratie vanaf dag 1.</li><li>Reserveer belasting van elke betaling.</li><li>Toets je opdrachten op schijnzelfstandigheid.</li><li>Inkomen doorgeven bij Toeslagen.</li></ol>'
'<h2 id="mistakes">Veelgemaakte fouten</h2><ol><li>Ontvangen btw uitgeven alsof het omzet is.</li><li>Geen urenregistratie en zo aftrek missen.</li><li>Als werknemer werken voor één opdrachtgever zonder het risico te kennen.</li><li>Een kwartaalaangifte vergeten, ook als die nul is.</li><li>Winst te laag schatten bij Toeslagen.</li></ol>'),
faq=[('Wat kost inschrijven bij KVK?','€ 85,15 voor de eerste inschrijving; het bedrag wordt jaarlijks aangepast.'),
('Kan ik volledig online inschrijven?','Niet voor een eenmanszaak: online voorbereiden en afronden op een afspraak.'),
('Mag ik als statushouder zzp’er worden?','Ja, asielstatushouders hebben volledige arbeidsrechten, ook als zelfstandige.'),
('Wat is de KOR?','Btw-vrijstelling bij een omzet onder € 20.000 per jaar; je trekt dan geen btw af.'),
('Verdwijnt de startersaftrek?','Volgens het Belastingplan 2027 (voorstel): € 10 in 2027 en afgeschaft in 2028.'),
('Is een AOV verplicht?','Nog niet; er ligt een wetsvoorstel, volgens KVK verwacht in 2030.')],
src_note='Regels en bedragen gecontroleerd bij KVK, Belastingdienst, Rijksoverheid en Ondernemersplein op 4 oktober 2026. Bedragen 2027 zijn voorstellen tot het parlement beslist; de KVK-inschrijfvergoeding staat zonder jaartal op de KVK-pagina.')
