from a_student_finance import T
SLUG='municipal-taxes-exemption-kwijtschelding'
R='https://www.rijksoverheid.nl/'
SRC=[('Rijksoverheid · Wanneer kom ik in aanmerking voor kwijtschelding van gemeentelijke belastingen?',R+'vraag-en-antwoord/gemeenten/wanneer-kom-ik-in-aanmerking-voor-kwijtschelding-van-gemeentelijke-belastingen'),
('Wetten.overheid.nl · Uitvoeringsregeling Invorderingswet 1990','https://wetten.overheid.nl/BWBR0004766/'),
('Wetten.overheid.nl · Regeling kwijtschelding belastingen medeoverheden','https://wetten.overheid.nl/BWBR0047157/2022-09-17/0'),
('Wetten.overheid.nl · Leidraad Invordering 2008','https://wetten.overheid.nl/BWBR0024096/2026-07-01/0'),
('Rijksoverheid · Hoe hoog is mijn bijstandsuitkering?',R+'vraag-en-antwoord/bijstand/hoe-hoog-is-mijn-bijstandsuitkering'),
('Nationale ombudsman · Vragen over kwijtschelding','https://www.nationaleombudsman.nl/vraag-en-antwoord/ik-heb-vragen-over-kwijtschelding-van-gemeentelijke-enof-waterschapsbelastingen'),
('Gemeente Enschede · Verordening kwijtschelding gemeentelijke belastingen 2026','https://lokaleregelgeving.overheid.nl/CVDR749442/1'),
('GBTwente · Kwijtschelding','https://gbtwente.nl/Alles-over/Kwijtschelding'),
('GBTwente · Kwijtschelding Enschede','https://gbtwente.nl/Alles-over/Kwijtschelding-enschede'),
('GBLT · Regels en voorwaarden kwijtschelding','https://gblt.nl/regels-voorwaarden-kwijtschelding'),
('Rijksoverheid · Schuldhulpverlening aanvragen',R+'vraag-en-antwoord/schulden/schuldhulpverlening-aanvragen'),
('Rijksoverheid · Bijzondere bijstand',R+'vraag-en-antwoord/bijstand/wanneer-heb-ik-recht-op-bijzondere-bijstand')]

AR=dict(title='الإعفاء من ضرائب البلدية والمياه في هولندا (Kwijtschelding) 2026: من يستحقه، الشروط، المستندات، ومثال إنسخيدة',
crumb='إعفاء ضرائب البلدية',
desc='دليل عميق للإعفاء من ضرائب البلدية (النفايات والصرف) وضرائب هيئة المياه: أي الضرائب يشملها، معيار الدخل 90–100% من حد الإعانة، حدود الرصيد والسيارة 3,350 يورو، المستندات، الطلب الآلي، الاعتراض خلال 10 أيام، وما تفعله أثناء الانتظار، مع مثال Enschede وVechtstromen.',
summary='<ol><li><strong>Kwijtschelding</strong> يعني أن البلدية أو هيئة المياه تُلغي (كلياً أو جزئياً) ضرائب مثل النفايات (afvalstoffenheffing) والصرف (rioolheffing) وضريبة المياه، إن كان دخلك ومالك قليلين.</li><li><strong>كل بلدية تحدد أي ضرائب تُعفى منها.</strong> عادة لا إعفاء من ضريبة الكلاب أو الوقوف أو الرسوم.</li><li><strong>معيار الدخل:</strong> القانون الوطني يستخدم 90% من حد إعانة bijstand، ويحق للبلدية رفعه حتى 100% (إنسخيدة وVechtstromen: 100%).</li><li><strong>المال:</strong> يجب ألا يكون لديك رصيد فوق حد صغير، والسيارة لا تُحسب إن كانت قيمتها 3,350 يورو أو أقل.</li><li><strong>إن رُفض طلبك</strong> فلديك <strong>10 أيام فقط</strong> لتقديم «استئناف إداري» (administratief beroep)، وليس 6 أسابيع.</li><li><strong>أثناء دراسة طلبك</strong> لا تُتخذ إجراءات تحصيل قسري لتلك الضريبة.</li></ol>',
body=(
'<h2 id="what">ما هي الضرائب المعنية؟</h2><p>تصلك كل سنة (غالباً في الربيع) فاتورة من البلدية أو من مكتب ضرائب مشترك (مثل GBTwente في تفينته)، وفاتورة من هيئة المياه (waterschap) أو مكتبها (مثل GBLT). الإعفاء ممكن حسب القانون لـ«ضرائب البلدية» و«ضرائب هيئة المياه»، لكن <strong>كل جهة تحدد في لائحتها أي ضريبة بالضبط</strong>.</p>'
+T([['ضريبة النفايات (afvalstoffenheffing)','غالباً نعم. في إنسخيدة: الجزء الثابت، وجزء محدود من الجزء المتغير (حتى 33.08 يورو).'],
    ['ضريبة الصرف والمياه (rioolheffing)','غالباً نعم. في إنسخيدة: عن أول 500 م³ من الماء.'],
    ['ضريبة العقار OZB','للمالك على منزله السكني ممكنة في بعض البلديات (حسب GBTwente لإنسخيدة)، وليس على العقارات غير السكنية.'],
    ['ضرائب هيئة المياه (Vechtstromen)','ضريبة التنقية (zuiveringsheffing)، وضريبة نظام المياه للسكان (watersysteemheffing ingezetenen)، وضريبة التلوث، للأشخاص فقط.'],
    ['لا إعفاء عادة','ضريبة الكلاب، الوقوف، السياحة، الإعلانات، الأسواق، المقابر، ومعظم الرسوم (leges).']],
   ['الضريبة','هل يشملها الإعفاء؟'])
+'<h2 id="who">من يستحق الإعفاء؟ المنطق ببساطة</h2><p>لا يوجد «حد دخل ثابت» واحد. تحسب الجهة <strong>قدرتك على الدفع</strong>:</p><ol><li>تأخذ دخلك الصافي المتوقع للـ12 شهراً القادمة.</li><li>تطرح منه «تكاليف المعيشة» حسب المعيار (90% أو 100% من حد bijstand)، و<strong>صافي تكلفة السكن</strong> (الإيجار بعد بدل الإيجار)، وجزءاً من <strong>قسط التأمين الصحي</strong> بعد بدل الرعاية، والنفقة التي تدفعها، وأقساط ديون الضرائب، وبعض تكاليف الأطفال.</li><li>إن بقي فائض، يجب أن يذهب <strong>80% منه</strong> على الأقل لدفع الضريبة؛ والباقي قد يُعفى.</li><li><strong>المال الموجود يُستخدم أولاً:</strong> رصيد بنكي فوق الحد، أو سيارة قيمتها فوق 3,350 يورو، أو قيمة فائضة في منزل تملكه.</li></ol>'
+T([['حد الإعانة (bijstandsnorm) شخص وحيد 21 سنة حتى سن AOW','1,401.50 يورو','<strong>1,419.46 يورو</strong>'],
    ['متزوجان أو ساكنان معاً 21 سنة حتى سن AOW','2,002.13 يورو','<strong>2,027.79 يورو</strong>'],
    ['شخص وحيد من سن AOW','1,564.69 يورو','<strong>1,587.34 يورو</strong>'],
    ['متزوجان من سن AOW','2,144.16 يورو','<strong>2,176.10 يورو</strong>']],
   ['الحالة (صافي شهرياً)','1 يناير 2026','1 يوليو 2026'])
+'<p>هذه حدود الإعانة الرسمية، وليست «حد الإعفاء» مباشرة: الحساب يطرح السكن والتأمين ويطبق النسبة التي اختارتها بلديتك. تفترض البلدية أيضاً أن بدل العطلة نحو 7% من دخلك الصافي. وإن كان معك بالغون في البيت فقد ينخفض الحد (قاعدة تقاسم التكاليف).</p>'
'<h2 id="money">حدود المال والسيارة والبيت</h2><ul><li><strong>السيارة:</strong> لا تُحسب إن كانت قيمتها (ما يدفعه تاجر لشرائها) <strong>3,350 يورو أو أقل</strong>، أو إن كانت ضرورية للعمل أو بسبب إعاقة.</li><li><strong>الرصيد البنكي:</strong> المسموح يساوي تقريباً تكاليف معيشة شهر مع متوسط السكن والتأمين وتكاليف الأطفال، وقد تضيف بعض الجهات هامشاً حتى 2,000 يورو للزوجين. مثال GBLT (هيئة المياه Vechtstromen) من 1 يناير 2026: زوجان 4,974 يورو، والد وحيد 4,560 يورو، شخص وحيد 3,758 يورو (بلا AOW).</li><li><strong>منزل مملوك:</strong> لا إعفاء إن كانت فيه «قيمة فائضة» (overwaarde) فوق الرهن.</li><li>حدود الإعفاء <strong>أشد</strong> من حدود إعانة bijstand (8,000 / 16,000 يورو).</li></ul>'
'<h2 id="apply">كيف تقدّم الطلب؟ خطوة بخطوة (مثال إنسخيدة)</h2><ol><li><strong>انظر إلى فاتورتك أولاً:</strong> إن كُتب عليها «geautomatiseerde kwijtschelding» فقد حصلت على الإعفاء الكامل تلقائياً ولا تحتاج شيئاً.</li><li>ادخل <strong>MijnGBTwente</strong> بـDigiD الخاص بالشخص المكتوب اسمه على الفاتورة (للبلدية)، و<strong>MijnGBLT</strong> لهيئة المياه Vechtstromen.</li><li>أجب عن الأسئلة، ووافق على «الفحص الآلي» لتقليل المستندات المطلوبة.</li><li>ارفع المستندات: قسائم الراتب أو الإعانة أو التقاعد لآخر <strong>3 أشهر</strong>؛ كشوف بنكية لشهر كامل مع الرصيد لكل الحسابات؛ ومستندات الشريك. وحسب حالتك: كشف الرهن، إثبات ضرورة السيارة، نفقة، بيان DUO للطلاب، أو إقرار الدخل من Belastingdienst للعاملين لحسابهم.</li><li>يصلك القرار عادة <strong>خلال 3 أشهر</strong> بالبريد (GBTwente).</li></ol><ul><li><strong>بلا DigiD:</strong> GBLT تتيح الطلب هاتفياً (088-064 55 55، من الاثنين للجمعة 9–17) وترسل نموذجاً خلال 10 أيام.</li><li><strong>العام القادم:</strong> في إنسخيدة لا يتكرر الإعفاء تلقائياً إن لم يُكتب ذلك على الفاتورة؛ «قدّم طلباً جديداً».</li><li><strong>إعفاء البلدية لا يعني إعفاء هيئة المياه تلقائياً</strong>: قواعد الهيئات أضيق قليلاً، فقدّم للجهتين.</li></ul>'
'<h2 id="deadline">المواعيد: متى تقدّم؟</h2><ul><li>لا يوجد موعد وطني موحد للفواتير غير المدفوعة؛ كل جهة تحدد مهلة. وحسب أمين المظالم الوطني يجب على الجهة دراسة الطلب حتى لو جاء متأخراً.</li><li><strong>إن كنت دفعت الفاتورة بالفعل:</strong> القاعدة الوطنية (Leidraad Invordering) هي التقديم خلال <strong>3 أشهر من آخر دفعة</strong>. بعض الجهات تعطي مدة أطول (GBLT تذكر 6 أشهر). اقرأ فاتورتك.</li><li><strong>نصيحتنا:</strong> قدّم فور وصول الفاتورة، ولا تدفع ولا تتجاهل.</li></ul>'
'<h2 id="waiting">ماذا يحدث أثناء الانتظار؟</h2><ul><li>أثناء دراسة طلبك <strong>لا تُتخذ إجراءات تحصيل قسري</strong> لتلك الضريبة (إلا في حالات نادرة). GBLT: «حتى يصلك قرارنا لا تحتاج للدفع» للضرائب المعنية.</li><li>بعد الرفض لديك <strong>14 يوماً</strong> من تاريخ القرار (أو مهلة الدفع على الفاتورة) قبل بدء التحصيل.</li><li>إن لم تستحق الإعفاء فاسأل عن تقسيط الدفع؛ ليس حقاً مضموناً لكنه ممكن غالباً.</li><li>إن لم تدفع ولم تطلب إعفاء، قد ترتفع تكاليف التحصيل كثيراً.</li></ul>'
'<h2 id="appeal">رُفض طلبك؟ الاستئناف خلال 10 أيام</h2><p>ضد قرار الإعفاء لا تُقدّم «اعتراضاً» عادياً بل <strong>استئنافاً إدارياً (administratief beroep)</strong> خلال <strong>10 أيام</strong> من تاريخ القرار، إلى مجلس رئيس البلدية والمستشارين (أو الإدارة اليومية لهيئة المياه). في GBTwente: أرسل بريداً أو رسالة تشرح لماذا لا توافق، والعنوان مكتوب في القرار. نتيجة هذا الاستئناف لا تُعرض على المحكمة، لكن يمكن تقديم شكوى لأمين المظالم الوطني.</p><p><strong>ملاحظة:</strong> من 1 يناير 2027 يتغير هذا الطريق للضرائب الوطنية فقط؛ للضرائب المحلية يستمر النظام الحالي «مؤقتاً». سنراجع ذلك قبل 2027. والاعتراض على <strong>قيمة الفاتورة نفسها</strong> (مثلاً عدد الأشخاص خطأ) أمر مختلف له مهلة أخرى مكتوبة على الفاتورة.</p>'
'<h2 id="zzp">العاملون لحسابهم (zzp)</h2><p>يمكن الإعفاء فقط من <strong>الضرائب الخاصة</strong> وليس المرتبطة بالعمل، إن اختارت البلدية ذلك (إنسخيدة وVechtstromen تسمحان)، ويُطلب آخر إقرار دخل من Belastingdienst.</p>'
'<h2 id="more">مساعدة إضافية لذوي الدخل المنخفض</h2><ul><li><strong>المساعدة الخاصة (bijzondere bijstand):</strong> لتكاليف ضرورية وغير متوقعة، تقررها البلدية (هبة أو قرض).</li><li><strong>مساعدة الديون:</strong> تبلغ البلدية، وخلال 4 أسابيع تعرف نوع المساعدة، وخلال 8 أسابيع القرار. في خطر الطرد أو قطع الغاز أو الماء أو الكهرباء يجب أن تساعدك البلدية خلال <strong>3 أيام</strong>.</li><li><strong>الطاقة:</strong> صندوق طوارئ الطاقة يفتح للطلبات من 4 يناير 2027 (<a href="/articles/energy-contracts-saving-2026.html">دليل الطاقة</a>).</li><li>مساعدة مجانية: Juridisch Loket (0800 8020) والمستشارون الاجتماعيون (sociaal raadslieden).</li></ul>'
'<h2 id="mistakes">أخطاء شائعة</h2><ol><li>دفع الفاتورة ثم تفويت مهلة الأشهر الثلاثة.</li><li>الظن أن إعفاء البلدية يشمل هيئة المياه.</li><li>إرسال كشوف ناقصة أو حساب واحد فقط.</li><li>تفويت مهلة الأيام العشرة للاستئناف.</li><li>عدم تقديم طلب جديد في السنة التالية.</li></ol>'),
faq=[('ما الضرائب التي يمكن الإعفاء منها؟','غالباً ضريبة النفايات والصرف وضرائب هيئة المياه للسكان. كل بلدية تحدد القائمة، وعادة لا إعفاء من ضريبة الكلاب أو الوقوف أو الرسوم.'),
('ما حد الدخل؟','لا يوجد رقم واحد: تُحسب قدرتك على الدفع بعد تكاليف المعيشة (90–100% من حد bijstand) والسكن والتأمين الصحي. إنسخيدة تستخدم 100%.'),
('هل تمنعني سيارتي من الإعفاء؟','لا إن كانت قيمتها 3,350 يورو أو أقل، أو كانت ضرورية للعمل أو بسبب إعاقة.'),
('رُفض طلبي، كم لدي من الوقت؟','10 أيام من تاريخ القرار لتقديم استئناف إداري (administratief beroep).'),
('هل يتجدد الإعفاء تلقائياً؟','حسب البلدية. في إنسخيدة لا، إلا إن كُتب «geautomatiseerde kwijtschelding» على الفاتورة.'),
('دفعت الفاتورة، هل يمكنني طلب الإعفاء؟','نعم غالباً خلال 3 أشهر من آخر دفعة؛ بعض الجهات تعطي مدة أطول. انظر فاتورتك.')],
src_note='راجعنا القواعد في القانون الوطني (wetten.overheid.nl) وRijksoverheid وأمين المظالم ولوائح إنسخيدة وGBTwente وGBLT في 4 أكتوبر 2026. قواعد بلديتك قد تختلف؛ اعتمد على لائحتها وفاتورتك.')

NL=dict(title='Kwijtschelding van gemeentelijke en waterschapsbelastingen 2026: wie komt in aanmerking, voorwaarden, documenten en het voorbeeld Enschede',
crumb='Kwijtschelding',
desc='Uitgebreide gids over kwijtschelding van afvalstoffenheffing, rioolheffing en waterschapsbelasting: welke belastingen, de norm van 90–100% van de bijstandsnorm, vermogens- en autogrens € 3.350, documenten, geautomatiseerde kwijtschelding, administratief beroep binnen 10 dagen en wat je tijdens het wachten doet, met Enschede en Vechtstromen als voorbeeld.',
summary='<ol><li><strong>Kwijtschelding</strong>: de gemeente of het waterschap scheldt (een deel van) belastingen als afvalstoffenheffing, rioolheffing en waterschapsbelasting kwijt bij een laag inkomen en weinig vermogen.</li><li><strong>Elke gemeente bepaalt welke belastingen.</strong> Hondenbelasting, parkeren en leges meestal niet.</li><li><strong>Norm:</strong> landelijk 90% van de bijstandsnorm; gemeenten mogen tot 100% gaan (Enschede en Vechtstromen: 100%).</li><li><strong>Vermogen:</strong> weinig spaargeld; een auto tot € 3.350 telt niet mee.</li><li><strong>Afgewezen?</strong> Je hebt maar <strong>10 dagen</strong> voor administratief beroep.</li><li><strong>Tijdens de behandeling</strong> geen dwanginvordering voor die aanslag.</li></ol>',
body=(
'<h2 id="what">Om welke belastingen gaat het?</h2><p>Elk jaar (meestal in het voorjaar) krijg je een aanslag van de gemeente of een belastingsamenwerking (zoals GBTwente) en van het waterschap (bijvoorbeeld via GBLT). Kwijtschelding kan voor gemeentelijke en waterschapsbelastingen, maar <strong>elke organisatie bepaalt in haar verordening welke precies</strong>.</p>'
+T([['Afvalstoffenheffing','Meestal ja. Enschede: vast deel en maximaal € 33,08 van het variabele deel.'],['Rioolheffing','Meestal ja. Enschede: voor de eerste 500 m³ water.'],['OZB','Voor eigenaren van een woning in sommige gemeenten (volgens GBTwente ook in Enschede); niet voor niet-woningen.'],['Waterschap (Vechtstromen)','Zuiveringsheffing, watersysteemheffing ingezetenen en verontreinigingsheffing, alleen voor natuurlijke personen.'],['Meestal geen kwijtschelding','Hondenbelasting, parkeerbelasting, toeristenbelasting, reclame, marktgelden, begraafrechten en de meeste leges.']],['Belasting','Kwijtschelding?'])
+'<h2 id="who">Wie komt in aanmerking?</h2><p>Er is geen vaste inkomensgrens. De organisatie berekent je <strong>betalingscapaciteit</strong>:</p><ol><li>Je verwachte netto-inkomen over de komende 12 maanden.</li><li>Min de kosten van bestaan (90% of 100% van de bijstandsnorm), <strong>netto woonlasten</strong> (huur na huurtoeslag), zorgpremie min normpremie en zorgtoeslag, betaalde alimentatie, aflossing belastingschulden en kinderkosten.</li><li>Blijft er iets over, dan gaat minstens <strong>80%</strong> daarvan naar de belasting.</li><li><strong>Vermogen gaat voor:</strong> spaargeld boven de grens, een auto boven € 3.350 of overwaarde in je huis.</li></ol>'
+T([['Alleenstaande 21 jaar tot AOW','€ 1.401,50','<strong>€ 1.419,46</strong>'],['Gehuwd/samenwonend 21 jaar tot AOW','€ 2.002,13','<strong>€ 2.027,79</strong>'],['Alleenstaande vanaf AOW','€ 1.564,69','<strong>€ 1.587,34</strong>'],['Gehuwd vanaf AOW','€ 2.144,16','<strong>€ 2.176,10</strong>']],['Bijstandsnorm (netto p/m)','1 januari 2026','1 juli 2026'])
+'<p>Dit zijn de bijstandsnormen, niet direct de kwijtscheldingsgrens: woonlasten en zorg worden apart verrekend en je gemeente kiest het percentage. De gemeente gaat uit van vakantiegeld van 7% van je netto-inkomen; met volwassen huisgenoten kan de kostendelersnorm gelden.</p>'
'<h2 id="money">Vermogen, auto en eigen huis</h2><ul><li><strong>Auto:</strong> telt niet mee bij een waarde (inkoopprijs autohandelaar) tot <strong>€ 3.350</strong>, of als hij onmisbaar is voor werk of door invaliditeit.</li><li><strong>Banksaldo:</strong> toegestaan is ongeveer een maand kosten van bestaan plus gemiddelde woonlasten, zorgpremie en kinderkosten; sommige organisaties tellen tot € 2.000 extra voor echtparen. Voorbeeld GBLT (Vechtstromen) per 1 januari 2026: echtgenoten € 4.974, alleenstaande ouder € 4.560, alleenstaande € 3.758 (zonder AOW).</li><li><strong>Koopwoning:</strong> geen kwijtschelding bij overwaarde.</li><li>De grenzen zijn <strong>strenger</strong> dan bij de bijstand (€ 8.000 / € 16.000).</li></ul>'
'<h2 id="apply">Aanvragen in stappen (voorbeeld Enschede)</h2><ol><li><strong>Kijk eerst op je aanslag:</strong> staat er «geautomatiseerde kwijtschelding», dan heb je al maximale kwijtschelding en hoef je niets te doen.</li><li>Log in op <strong>MijnGBTwente</strong> met de DigiD van degene op wie de aanslag staat (gemeente), en op <strong>MijnGBLT</strong> voor waterschap Vechtstromen.</li><li>Beantwoord de vragen en geef toestemming voor de geautomatiseerde toets (minder documenten).</li><li>Upload: loonstroken of uitkerings-/pensioenspecificaties van de laatste <strong>3 maanden</strong>; bankafschriften van een volle maand met saldo van alle rekeningen; documenten van je partner. Afhankelijk van je situatie: hypotheekoverzicht, bewijs auto, alimentatie, DUO-overzicht of inkomensverklaring (ondernemers).</li><li>GBTwente beslist meestal <strong>binnen 3 maanden</strong> per post.</li></ol><ul><li><strong>Geen DigiD:</strong> GBLT neemt aanvragen telefonisch aan (088-064 55 55, ma–vr 9–17 uur) en stuurt binnen 10 dagen een formulier.</li><li><strong>Volgend jaar:</strong> in Enschede gaat kwijtschelding niet automatisch opnieuw, tenzij dat op de aanslag staat; vraag opnieuw aan.</li><li><strong>Gemeente ≠ waterschap:</strong> waterschappen hebben iets strengere regels; vraag bij allebei aan.</li></ul>'
'<h2 id="deadline">Termijnen</h2><ul><li>Voor onbetaalde aanslagen stelt elke organisatie een termijn; volgens de Nationale ombudsman moet een te late aanvraag toch worden behandeld.</li><li><strong>Al betaald?</strong> Landelijke regel (Leidraad Invordering): aanvragen binnen <strong>3 maanden na de laatste betaling</strong>. Sommige organisaties geven langer (GBLT noemt 6 maanden). Kijk op je aanslag.</li><li><strong>Advies:</strong> vraag direct aan na ontvangst van de aanslag.</li></ul>'
'<h2 id="waiting">Tijdens het wachten</h2><ul><li>Tijdens de behandeling worden <strong>geen dwangmaatregelen</strong> genomen voor die aanslag (behalve in uitzonderingsgevallen). GBLT: «Totdat u onze beslissing ontvangt hoeft u niet te betalen.»</li><li>Na afwijzing heb je <strong>14 dagen</strong> (of de betaaltermijn van de aanslag) voordat de invordering start.</li><li>Geen recht op kwijtschelding? Vraag naar een betalingsregeling; daar is geen recht op, maar het kan vaak.</li><li>Niets doen leidt tot hoge invorderingskosten.</li></ul>'
'<h2 id="appeal">Afgewezen: administratief beroep binnen 10 dagen</h2><p>Tegen een kwijtscheldingsbeslissing dien je <strong>administratief beroep</strong> in, <strong>binnen 10 dagen</strong> na de datum van de beschikking, bij het college van B&amp;W (of het dagelijks bestuur van het waterschap). Bij GBTwente stuur je een e-mail of brief met je motivering. De uitkomst kun je niet aan de rechter voorleggen, wel aan de Nationale ombudsman.</p><p>Per 1 januari 2027 verandert deze route alleen voor rijksbelastingen; voor gemeentelijke belastingen blijft het huidige regime «voorlopig». Bezwaar tegen de <strong>hoogte van de aanslag zelf</strong> is iets anders, met een eigen termijn op de aanslag.</p>'
'<h2 id="zzp">Zzp’ers</h2><p>Alleen kwijtschelding voor <strong>privébelastingen</strong>, als de gemeente daarvoor kiest (Enschede en Vechtstromen doen dat), met de laatste inkomensverklaring van de Belastingdienst.</p>'
'<h2 id="more">Meer hulp bij een laag inkomen</h2><ul><li><strong>Bijzondere bijstand</strong> voor noodzakelijke, onvoorziene kosten (gift of lening).</li><li><strong>Schuldhulp:</strong> binnen 4 weken weet je welke hulp, binnen 8 weken een besluit; bij dreigende uitzetting of afsluiting moet de gemeente binnen <strong>3 dagen</strong> helpen.</li><li><strong>Energie:</strong> het Noodfonds Energie opent voor aanvragen op 4 januari 2027 (<a href="/nl/articles/energy-contracts-saving-2026.html">gids energie</a>).</li><li>Gratis hulp: Juridisch Loket (0800 8020) en sociaal raadslieden.</li></ul>'
'<h2 id="mistakes">Veelgemaakte fouten</h2><ol><li>Betalen en dan de 3 maanden laten verlopen.</li><li>Denken dat kwijtschelding van de gemeente ook voor het waterschap geldt.</li><li>Onvolledige bankafschriften.</li><li>De beroepstermijn van 10 dagen missen.</li><li>Volgend jaar niet opnieuw aanvragen.</li></ol>'),
faq=[('Voor welke belastingen kan ik kwijtschelding krijgen?','Meestal afvalstoffenheffing, rioolheffing en waterschapsbelastingen voor ingezetenen. De gemeente bepaalt de lijst.'),
('Wat is de inkomensgrens?','Er is geen vast bedrag: je betalingscapaciteit wordt berekend na kosten van bestaan (90–100% bijstandsnorm), woonlasten en zorg. Enschede rekent met 100%.'),
('Telt mijn auto mee?','Niet bij een waarde tot € 3.350, of als hij onmisbaar is voor werk of invaliditeit.'),
('Mijn verzoek is afgewezen. Hoeveel tijd heb ik?','10 dagen na de datum van de beschikking voor administratief beroep.'),
('Gaat kwijtschelding automatisch elk jaar?','Hangt af van de gemeente. In Enschede niet, tenzij «geautomatiseerde kwijtschelding» op je aanslag staat.'),
('Ik heb al betaald. Kan ik nog kwijtschelding vragen?','Meestal binnen 3 maanden na de laatste betaling; sommige organisaties geven langer.')],
src_note='Regels gecontroleerd in de landelijke regelgeving (wetten.overheid.nl), bij de Rijksoverheid, de Nationale ombudsman en in de verordeningen en pagina’s van Enschede, GBTwente en GBLT op 4 oktober 2026. Jouw gemeente kan andere keuzes maken; ga uit van haar verordening en je aanslag.')
