from a_student_finance import T
SLUG='legal-aid-lawyer-toevoeging'
RB='https://www.rechtsbijstand.nl/mediation-rechtsbijstand/'
JL='https://www.juridischloket.nl/'
SRC=[('Raad voor Rechtsbijstand · Inkomen, vermogen en eigen bijdrage 2026','https://www.rvr.org/@20455/inkomen-vermogen-eigen-bijdrage-2026/'),
('Rechtsbijstand.nl · Eigen bijdrage',RB+'hoeveel-betalen/eigen-bijdrage/'),
('Rechtsbijstand.nl · Geen eigen bijdrage',RB+'hoeveel-betalen/geen-eigen-bijdrage/'),
('Rechtsbijstand.nl · Brief ontvangen: civiele toevoeging (peiljaarverlegging, resultaatsbeoordeling, bezwaar)','https://www.rechtsbijstand.nl/krijg-mediation-rechtsbijstand/brief-ontvangen/civiel-toevoeging'),
('RvR Beleidswijzer · Geen eigen bijdrage','https://beleidswijzer.rvr.org/beleidsbundel/financiele-beoordeling-aanvraag/2-3-eigen-bijdrage-(uitzonderingen/eigen-bijdrage/'),
('Het Juridisch Loket · Kosten advocaat of mediator met toevoeging',JL+'hoe-we-werken/toevoeging-advocaat/'),
('Het Juridisch Loket · Advocaat nodig?',JL+'hoe-we-werken/advocaat-nodig/'),
('Het Juridisch Loket · Contact',JL+'contact/'),
('Het Juridisch Loket · Wat kost een rechtszaak?',JL+'politie-en-justitie/justitie/kosten-rechtszaak/'),
('Het Juridisch Loket · Loonbeslag? Lagere eigen bijdrage',JL+'actueel/loonbeslag-lagere-eigen-bijdrage/'),
('Het Juridisch Loket · Gratis advocaat bij verlies ouderlijk gezag',JL+'actueel/advocaat-gezag/'),
('Rijksoverheid · Hoe verloopt het aanvragen van gesubsidieerde rechtsbijstand?','https://www.rijksoverheid.nl/onderwerpen/rechtspraak-en-geschiloplossing/vraag-en-antwoord/hoe-verloopt-het-aanvragen-van-gesubsidieerde-rechtsbijstand'),
('Rijksoverheid · Productbeschrijving gesubsidieerde rechtsbijstand of mediation','https://www.rijksoverheid.nl/wetten-en-regelingen/productbeschrijvingen/gesubsidieerde-rechtsbijstand-of-mediation'),
('IND · Asylum procedures in the Netherlands (lawyer via RvR)','https://ind.nl/en/asylum-procedures-in-the-netherlands')]

AR=dict(title='المحامي المدعوم (toevoeging) في هولندا 2026: حدود الدخل والمدخرات، جدول المساهمة الذاتية، خصم 69 يورو، والمساعدة القانونية المجانية — مع أمثلة',
seo_title='المحامي المدعوم toevoeging 2026',
crumb='المحامي المدعوم (toevoeging)',
desc='المحامي المدعوم (toevoeging) 2026: حد الدخل 35,400 يورو للأعزب و50,000 للمتزوج، مساهمة ذاتية من 257 يورو مع خصم 69 يورو، ونصيحة مجانية على 0800-8020.',
summary='<ol><li><strong>لا تقدّم الطلب بنفسك</strong>: المحامي أو الوسيط (mediator) يقدّم طلب «toevoeging» إلى <strong>Raad voor Rechtsbijstand</strong> نيابةً عنك.</li><li><strong>حد الدخل 2026</strong> (من بيانات الضرائب لسنة <strong>2024</strong>): <strong>35,400 يورو</strong> للأعزب، و<strong>50,000 يورو</strong> للمتزوج أو المساكن أو الأسرة أحادية الوالد. <strong>حد المدخرات</strong> (box 3): <strong>36,952 يورو للشخص</strong>.</li><li><strong>المساهمة الذاتية (eigen bijdrage)</strong> تدفعها للمحامي مباشرة: من <strong>257</strong> إلى <strong>1,084 يورو</strong> للقضايا العادية، ومن <strong>448</strong> إلى <strong>1,120 يورو</strong> لقضايا الأسرة، ويُخصم منها <strong>69 يورو تلقائياً</strong>.</li><li><strong>انخفض دخلك الآن 15% أو أكثر</strong> مقارنة بسنة 2024؟ اطلب <strong>peiljaarverlegging</strong> خلال 6 أسابيع من القرار.</li><li><strong>نصيحة مجانية أولاً</strong>: Het Juridisch Loket على الرقم المجاني <strong>0800-8020</strong> (الاثنين–الجمعة 9:00–17:00).</li><li>بعض الحالات <strong>بلا مساهمة ذاتية</strong>: معظم إجراءات اللجوء، محامي المناوبة (piket) عند التوقيف في جريمة خطيرة، ضحايا العنف الجسيم أو الجرائم الجنسية.</li></ol>',
body=(
'<h2 id="what">ما هي «الإضافة» (toevoeging)؟</h2><p>الـ<strong>toevoeging</strong> هي دعم حكومي من <strong>مجلس المساعدة القانونية (Raad voor Rechtsbijstand، اختصاراً RvR)</strong> يغطي معظم أتعاب المحامي أو الوسيط، وتدفع أنت جزءاً صغيراً اسمه <strong>المساهمة الذاتية (eigen bijdrage)</strong>. تُسمى أيضاً «المساعدة القانونية المدعومة» (gesubsidieerde rechtsbijstand).</p><ul><li><strong>المحامي يقدّم الطلب</strong>، لا أنت: يجهّزه معك ثم يرسله إلى المجلس، والمجلس يقرر.</li><li>يحصل المجلس على بيانات دخلك ومدخراتك من مصلحة الضرائب (Belastingdienst) مباشرة.</li><li>تدفع المساهمة الذاتية <strong>للمحامي أو الوسيط مباشرة</strong>، وليس للمجلس.</li><li>يجب أن تكون المساعدة ضرورية فعلاً، وأن تكون قيمة المسألة <strong>500 يورو على الأقل</strong> (أو <strong>250 يورو</strong> إن احتاج المحامي 3 ساعات أو أقل).</li><li><strong>لا يغطي</strong> الدعم رسوم المحكمة (griffierecht) ولا تكاليف الدعوى (proceskosten) إن خسرت وحكم القاضي عليك بها.</li></ul>'
'<h2 id="limits">حدود الدخل والمدخرات 2026</h2><p>للطلبات المقدّمة منذ 1 يناير 2026 ينظر المجلس إلى <strong>الدخل الضريبي السنوي (fiscaal jaarinkomen) لسنة 2024</strong>، وهي «سنة القياس» (peiljaar)، أي قبل سنتين.</p>'
+T([['أعزب (alleenstaand)','حتى 35,400 يورو','36,952 يورو'],['متزوج، مساكن، أو أسرة أحادية الوالد (eenoudergezin)','حتى 50,000 يورو','73,904 يورو (للشريكين)']],['الوضع','حد الدخل (سنة 2024)','حد المدخرات box 3 (سنة 2024)'])
+'<p>لاحظ أن <strong>الأم أو الأب الوحيد مع أطفال</strong> يُعامل مثل المتزوجين في جدول الدخل. المدخرات تعني ثروتك في box 3 (حسابات توفير، استثمارات…) في سنة 2024. إذا تجاوزت أحد الحدين، لا تحصل على toevoeging عادةً.</p>'
'<h2 id="table">جدول المساهمة الذاتية (eigen bijdrage) 2026</h2>'
+T([['حتى 25,200','حتى 35,000','257','448'],['25,201 – 25,900','35,001 – 36,200','475','543'],['25,901 – 27,500','36,201 – 37,900','678','747'],['27,501 – 29,800','37,901 – 42,400','882','950'],['29,801 – 35,400','42,401 – 50,000','1,084','1,120'],['أكثر من 35,400','أكثر من 50,000','لا toevoeging','لا toevoeging']],['دخل 2024 — أعزب (يورو)','دخل 2024 — متزوج/أسرة أحادية الوالد (يورو)','قضية عادية (يورو)','قضايا الأسرة والأحوال الشخصية (يورو)'])
+'<p><strong>خصم 69 يورو</strong>: عندما يمنح المجلس الـtoevoeging يخصم <strong>69 يورو</strong> من هذه المساهمة. منذ مارس 2020 يُطبَّق الخصم <strong>تلقائياً</strong>، ولم تعد بحاجة لزيارة Juridisch Loket أولاً للحصول على «وثيقة تشخيص» (diagnosedocument). لذلك يذكر Juridisch Loket مبالغ بعد الخصم: مثلاً 188 يورو بدل 257، و1,015 بدل 1,084، و379 بدل 448 في قضايا الأسرة.</p>'
+T([['الاستشارة الخفيفة (LAT) — عادية','101','170'],['الاستشارة الخفيفة (LAT) — قضايا الأسرة','141','187'],['الوساطة (mediation)','69','138']],['النوع','الشريحة الدنيا (أعزب حتى 25,900 / متزوج حتى 36,200؛ للوساطة: 25,200 / 35,000)','الشريحة العليا (حتى 35,400 / 50,000)'])
+'<p><strong>الاستشارة الخفيفة (Lichte Advies Toevoeging، LAT)</strong> للمسائل التي يحلّها المحامي في <strong>3 ساعات أو أقل</strong>، مثل رسالة أو نصيحة قصيرة. <strong>قضايا الأسرة</strong> (الطلاق، النفقة، الحضانة) لها مساهمة أعلى من القضايا العادية.</p>'
'<h2 id="examples">أمثلة محسوبة</h2>'
+T([['أعزب، دخل 2024: 22,000 يورو، نزاع مع المؤجر','الشريحة الأولى: 257 − 69 = <strong>188 يورو</strong>'],['أسرة أحادية الوالد، دخل 2024: 36,000 يورو، نزاع على النفقة','شريحة 35,001–36,200 في قضايا الأسرة: 543 − 69 = <strong>474 يورو</strong>'],['أعزب، دخل 2024: 38,000 يورو (أكثر من الحد)، فقد عمله ودخله في 2026 نحو 24,000','انخفاض أكثر من 15%: يطلب <strong>peiljaarverlegging</strong>؛ إن قُبل: 257 − 69 = <strong>188 يورو</strong>'],['أعزب، دخل 2024: 30,000 يورو، يحتاج نصيحة قصيرة عن عقد عمل','LAT عادية، الشريحة العليا: <strong>170 يورو</strong>'],['زوجان، دخل 2024: 45,000 يورو، يريدان وساطة','الوساطة، الشريحة العليا: <strong>138 يورو</strong>'],['أعزب، مدخرات 2024: 45,000 يورو','أكثر من 36,952: <strong>لا toevoeging</strong> عادةً؛ يدفع المحامي بنفسه أو يبحث عن تأمين'],['أعزب ربح من القضية 25,000 يورو','أكثر من 19,239.50 (نصف حد المدخرات 2026): قد يُسحب الـtoevoeging بأثر رجعي ويدفع الأتعاب كاملة']],['الحالة','الحساب'])
+'<p>أمثلة توضيحية وليست حالات أشخاص حقيقيين. القرار النهائي والمبلغ الدقيق يحددهما مجلس المساعدة القانونية.</p>'
'<h2 id="routes">أي طريق لأي مشكلة؟</h2>'
+T([['سؤال قانوني أو رسالة لا تفهمها','Het Juridisch Loket: نصيحة مجانية لذوي الدخل المنخفض','0800-8020 (مجاني)'],['مسألة بسيطة يحلها محامٍ في 3 ساعات أو أقل','الاستشارة الخفيفة (LAT)','101–187 يورو'],['نزاع أو قضية: إيجار، عمل، إعانة، اعتراض على قرار','toevoeging عادية عبر محامٍ','257–1,084 يورو (ناقص 69)'],['طلاق، نفقة، حضانة','toevoeging للأسرة؛ المحامي إلزامي في الطلاق','448–1,120 يورو (ناقص 69)'],['تريدان حلاً بالتفاهم (انفصال، جيران)','وساطة مدعومة (mediationtoevoeging)','69 أو 138 يورو'],['أُوقفت بسبب جريمة خطيرة','محامي المناوبة (piketadvocaat) تُبلغ به الشرطة','بلا مساهمة ذاتية'],['طلب لجوء','المجلس يرتّب محامياً، غالباً مجاناً','عادةً بلا مساهمة'],['إنهاء السلطة الأبوية أو أول إخراج للطفل من البيت','محامٍ مجاني (مؤقت حتى 1 يناير 2027)','مجاني'],['لديك حجز على الراتب (loonbeslag)','غالباً أدنى مساهمة ذاتية (مؤقت حتى 1 أبريل 2028)','الشريحة الدنيا'],['لديك تأمين قانوني (rechtsbijstandverzekering) أو نقابة','اتصل بهم أولاً','حسب الوثيقة']],['المشكلة','الطريق','التكلفة عليك'])
+'<h2 id="steps">خطوة بخطوة: كيف تحصل على محامٍ مدعوم</h2><ol><li><strong>اجمع الأوراق</strong>: الرسالة أو القرار أو العقد، والتواريخ المهمة (مهلة الاعتراض!).</li><li><strong>اتصل بـJuridisch Loket</strong> على <strong>0800-8020</strong> أو زر أحد مكاتبه. يعطيك نصيحة مجانية ويقرر إن كنت تحتاج محامياً.</li><li><strong>ابحث عن محامٍ يعمل بـtoevoeging</strong>: اسأل المحامي صراحة «Werkt u op toevoeging?». سجل المحامين في هولندا لدى نقابة المحامين (Nederlandse Orde van Advocaten): <strong>zoekeenadvocaat.advocatenorde.nl</strong>. وإن أحالك Juridisch Loket برسالة، يرسل لك المجلس قائمة محامين مناسبين (خدمة «matching»)، والمحامي يقرر إن كان يقبل قضيتك.</li><li><strong>المحامي يقدّم الطلب</strong> معك إلى Raad voor Rechtsbijstand. قل له إن انخفض دخلك (peiljaarverlegging) أو إن كان عليك حجز على الراتب.</li><li><strong>يصلك القرار</strong> وفيه مبلغ المساهمة الذاتية. ادفعه للمحامي حسب فاتورته.</li><li><strong>لست موافقاً على القرار؟</strong> قدّم اعتراضاً (bezwaar) <strong>خلال 6 أسابيع</strong> من تاريخ القرار. وطلب peiljaarverlegging أيضاً خلال 6 أسابيع.</li><li><strong>رسوم المحكمة</strong>: إن ذهبت للمحكمة، اطلب <strong>رسوماً مخفّضة</strong> مع إثبات الـtoevoeging (انظر القسم التالي).</li></ol>'
'<h2 id="peiljaar">سنة القياس وتغيّر الدخل</h2><ul><li><strong>سنة القياس (peiljaar)</strong> = قبل سنتين: في 2026 يُنظر إلى 2024.</li><li><strong>انخفض دخلك؟</strong> إن انخفض دخلك أو مدخراتك في السنة الحالية <strong>15% على الأقل</strong> مقارنة بسنة القياس (أو أقل من ذلك إن كان الانخفاض يدخلك تحت الحدود)، يمكن طلب <strong>peiljaarverlegging</strong>، أي الحساب على بيانات السنة الحالية. يُطلب مع الطلب أو <strong>خلال 6 أسابيع</strong> من القرار.</li><li><strong>ارتفع دخلك بعد 2024؟</strong> القاعدة القانونية أن المجلس يحسب على سنة القياس، فارتفاع دخلك هذا العام لا يُدخل في الحساب العادي. لكن انتبه للبند التالي.</li><li><strong>ربحت مالاً من القضية (resultaatsbeoordeling)</strong>: إن حصلت من القضية على مبلغ يساوي <strong>50% أو أكثر من حد المدخرات المعفى</strong> (في 2026: <strong>19,239.50 يورو للشخص</strong>، أي نصف 38,479)، أو إن أمكن تحميل أتعاب المحامي على طرف آخر، قد يُسحب الـtoevoeging <strong>بأثر رجعي</strong> وتدفع الأتعاب بنفسك.</li></ul>'
'<h2 id="reduced">مساهمة أقل، أعلى، أو لا شيء</h2><ul><li><strong>أدنى مساهمة</strong>: من هو في تسوية ديون قانونية (Wsnp) أو مساعدة ديون (schuldhulpverlening) أو إفلاس يدفع الشريحة الدنيا.</li><li><strong>حجز على الراتب أو الأموال (loonbeslag)</strong>: ترتيب مؤقت <strong>حتى 1 أبريل 2028</strong>: غالباً أدنى مساهمة، حتى لو كان دخلك أو مدخراتك عادةً أعلى. لا يشمل من لديه تأمين قانوني. أسئلة: Raad voor Rechtsbijstand <strong>088-787 1234</strong>.</li><li><strong>مساهمة جديدة دون خصم</strong>: إن غيّرت محاميك أو طُلبت ساعات إضافية بـtoevoeging جديدة، قد تدفع مساهمة جديدة <strong>بلا خصم الـ69 يورو</strong>.</li><li><strong>بلا مساهمة ذاتية</strong> (بشروط): إن طلب القاضي أو النيابة تعيين محامٍ لك، ضحايا العنف الجسيم أو الجرائم الجنسية، المحتجزون بلا دخل (نموذج «Eigen verklaring vrijheidsontneming»)، الإدخال الإجباري للعلاج النفسي، قاصر له وصي خاص (bijzondere curator)، طالبو اللجوء (نموذج «Eigen verklaring asielzoeker»)، والموقوف في جريمة خطيرة مع محامي المناوبة.</li></ul>'
'<h2 id="asylum">اللجوء والقضايا الجنائية</h2><ul><li><strong>اللجوء</strong>: حسب IND، يرتّب مجلس المساعدة القانونية محامياً لك، <strong>غالباً مجاناً</strong>، في كل إجراءات اللجوء، ويلتقي بك عادةً قبل مقابلتك مع IND بقليل. يملأ المحامي معك نموذج «Eigen verklaring asielzoeker». انظر <a href="/articles/asylum-family-reunification.html">لمّ شمل عائلة اللاجئ</a>.</li><li><strong>التوقيف</strong>: إن أوقفتك الشرطة بسبب جريمة خطيرة، تُبلغ الشرطة <strong>محامي المناوبة (piketadvocaat)</strong>، وهذا بلا مساهمة ذاتية. وإن طلب القاضي أو النيابة تعيين محامٍ لك (ambtshalve)، فلا مساهمة أيضاً.</li><li><strong>قضايا جنائية خفيفة</strong> دون توقيف: المحامي ليس إلزامياً لكنه مستحسن؛ اسأل عن toevoeging عادية.</li></ul>'
'<h2 id="court">رسوم المحكمة (griffierecht) وتكاليف الدعوى</h2><ul><li>الـtoevoeging <strong>لا يدفع رسوم المحكمة</strong>. لكن مع إثبات الـtoevoeging (أو إفادة دخل) تدفع <strong>الرسم المخفّض</strong> لذوي الدخل المنخفض، وهو حسب Juridisch Loket <strong>93 يورو في 2026</strong>. تحقق من الرسم الدقيق لنوع قضيتك على rechtspraak.nl؛ للقضاء الإداري قواعد أخرى.</li><li><strong>تكاليف الدعوى (proceskosten)</strong>: إن خسرت قد يحكم القاضي عليك بدفع جزء من تكاليف الطرف الآخر، وهذه لا يغطيها الـtoevoeging.</li><li><strong>المحامي إلزامي</strong> في الطلاق وفي الدعاوى المدنية التي تزيد قيمتها على 25,000 يورو. في نزاعات العمل والقضايا الإدارية والجنائية ليس إلزامياً لكنه مستحسن.</li></ul>'
'<h2 id="insurance">بدائل: التأمين القانوني والنقابة والوساطة</h2><ul><li><strong>تأمين المساعدة القانونية (rechtsbijstandverzekering)</strong>: إن كان لديك، أو كنت عضواً في نقابة (vakbond)، اتصل بهم <strong>أولاً</strong>، خصوصاً في قضايا العمل والتعويض.</li><li><strong>الوساطة المدعومة (mediationtoevoeging)</strong>: وسيط مسجّل لدى المجلس يساعد الطرفين على الاتفاق؛ المساهمة <strong>69 يورو</strong> (دخل حتى 25,200 للأعزب / 35,000 للمتزوج) أو <strong>138 يورو</strong> (حتى 35,400 / 50,000).</li><li><strong>دخلك أعلى من الحدود؟</strong> اسأل المحامي عن سعر ثابت أو اتفاق دفع، أو ابدأ بنصيحة مجانية من Juridisch Loket لتعرف موقفك.</li></ul>'
'<h2 id="mistakes">أخطاء شائعة</h2><ol><li><strong>الانتظار حتى تفوت المهلة</strong>: مهل الاعتراض والطعن قصيرة ومذكورة في الرسالة. اتصل بـJuridisch Loket فوراً.</li><li><strong>محاولة تقديم الطلب بنفسك</strong> لدى المجلس: المحامي هو من يقدّمه.</li><li><strong>عدم سؤال المحامي</strong> إن كان يعمل بـtoevoeging قبل البدء؛ قد تصلك فاتورة بالسعر الكامل.</li><li><strong>نسيان peiljaarverlegging</strong> بعد فقدان العمل أو الطلاق: المهلة 6 أسابيع.</li><li><strong>نسيان أن رسوم المحكمة منفصلة</strong>: اطلب الرسم المخفّض.</li><li><strong>الاعتماد على «مستشارين» غير مسجلين</strong> يطلبون مالاً مقدماً عبر واتساب. تحقق من أن المحامي مسجل في سجل نقابة المحامين.</li><li><strong>استخدام رقم 0900 قديم</strong>: رقم Juridisch Loket الحالي <strong>0800-8020</strong> مجاني.</li></ol>'
'<h2 id="help">أين تجد مساعدة مجانية؟</h2><ul><li><strong>Het Juridisch Loket</strong>: <strong>0800-8020</strong> مجاناً، الاثنين–الجمعة 9:00–17:00؛ من خارج هولندا <strong>+31 30 239 2030</strong> بتكلفة المكالمة العادية. نصيحة شخصية لكل من دخله منخفض ومدخراته قليلة، ومكاتب في مدن كثيرة.</li><li><strong>Raad voor Rechtsbijstand</strong>: أسئلة عن الـtoevoeging: <strong>088-787 1234</strong>.</li><li><strong>مساعدة الديون من البلدية</strong> إن كانت المشكلة ديوناً: <a href="/articles/debt-help-schuldhulp.html">مساعدة الديون المجانية</a>.</li></ul>'
'<h2 id="related">أدلة مرتبطة</h2><ul><li><a href="/articles/tenant-rights-netherlands.html">حقوق المستأجر</a></li><li><a href="/articles/debt-help-schuldhulp.html">مساعدة الديون المجانية</a></li><li><a href="/articles/social-assistance-bijstand.html">المساعدة الاجتماعية (bijstand)</a></li><li><a href="/articles/unemployment-benefit-ww.html">إعانة البطالة WW</a></li><li><a href="/articles/asylum-family-reunification.html">لمّ شمل عائلة اللاجئ</a></li><li><a href="/articles/traffic-fines-cjib.html">المخالفات المرورية وCJIB</a></li></ul>'),
faq=[('هل أستطيع طلب محامٍ مدعوم بنفسي؟','لا. المحامي أو الوسيط يقدّم طلب الـtoevoeging إلى Raad voor Rechtsbijstand معك. ابدأ بـJuridisch Loket على 0800-8020 إن لم يكن لديك محامٍ.'),
('ما حد الدخل في 2026؟','35,400 يورو للأعزب و50,000 للمتزوج أو المساكن أو الأسرة أحادية الوالد، حسب الدخل الضريبي لسنة 2024.'),
('ما حد المدخرات؟','36,952 يورو للشخص في box 3 لسنة 2024، و73,904 للشريكين حسب Juridisch Loket.'),
('كم المساهمة الذاتية؟','للقضايا العادية من 257 إلى 1,084 يورو، ولقضايا الأسرة من 448 إلى 1,120، ثم يُخصم 69 يورو تلقائياً. الاستشارة الخفيفة 101–187 والوساطة 69 أو 138.'),
('لماذا ينظر المجلس إلى دخل 2024؟','لأن القانون يحدد سنة القياس (peiljaar) قبل سنتين. إن انخفض دخلك الآن 15% أو أكثر، اطلب peiljaarverlegging خلال 6 أسابيع من القرار.'),
('هل رقم Juridisch Loket مدفوع؟','لا، الرقم 0800-8020 مجاني من داخل هولندا، من الاثنين إلى الجمعة 9:00–17:00.'),
('هل يدفع الـtoevoeging رسوم المحكمة؟','لا، لكنه يتيح لك دفع الرسم المخفّض (93 يورو في 2026 حسب Juridisch Loket). تكاليف الطرف الآخر إن خسرت لا يغطيها أيضاً.'),
('هل محامي اللجوء مجاني؟','حسب IND يرتّب المجلس محامياً غالباً مجاناً في إجراءات اللجوء، ولا تُفرض عادةً مساهمة ذاتية مع نموذج «Eigen verklaring asielzoeker».'),
('أوقفتني الشرطة، هل أدفع للمحامي؟','عند التوقيف بسبب جريمة خطيرة يأتي محامي المناوبة (piketadvocaat) دون مساهمة ذاتية.'),
('ماذا لو ربحت مالاً من القضية؟','إن حصلت على 50% أو أكثر من حد المدخرات المعفى (19,239.50 يورو للشخص في 2026)، قد يُسحب الـtoevoeging بأثر رجعي وتدفع الأتعاب بنفسك.')],
src_note='راجعنا Raad voor Rechtsbijstand (rvr.org وrechtsbijstand.nl) وHet Juridisch Loket وRijksoverheid وIND في 7 أكتوبر 2026. الجداول للطلبات المقدمة في 2026 (سنة القياس 2024). حد المدخرات للشريكين وحد ربح القضية للشريكين من Juridisch Loket. رسم المحكمة المخفّض يختلف حسب نوع القضية؛ تحقق على rechtspraak.nl. أرقام 2027 لم تُنشر بعد. الأمثلة توضيحية.')

NL=dict(title='Advocaat met toevoeging in 2026: inkomens- en vermogensgrenzen, eigen bijdrage, € 69 korting en gratis juridisch advies — met voorbeelden',
seo_title='Advocaat met toevoeging 2026: grenzen en kosten',
crumb='Advocaat met toevoeging',
desc='Advocaat met toevoeging 2026: inkomensgrens € 35.400 alleenstaand en € 50.000 gehuwd, eigen bijdrage vanaf € 257 met € 69 korting, gratis advies 0800-8020.',
summary='<ol><li><strong>Je vraagt het niet zelf aan</strong>: je advocaat of mediator vraagt de toevoeging aan bij de <strong>Raad voor Rechtsbijstand</strong>.</li><li><strong>Inkomensgrens 2026</strong> (fiscale gegevens <strong>2024</strong>): <strong>€ 35.400</strong> alleenstaand, <strong>€ 50.000</strong> gehuwd, samenwonend of eenoudergezin. <strong>Vermogensgrens</strong> (box 3): <strong>€ 36.952 per persoon</strong>.</li><li><strong>Eigen bijdrage</strong> betaal je aan de advocaat: <strong>€ 257</strong> tot <strong>€ 1.084</strong> in gewone zaken, <strong>€ 448</strong> tot <strong>€ 1.120</strong> in personen- en familierecht, met <strong>automatisch € 69 korting</strong>.</li><li><strong>Inkomen nu minstens 15% lager</strong> dan in 2024? Vraag <strong>peiljaarverlegging</strong> aan, uiterlijk 6 weken na het besluit.</li><li><strong>Eerst gratis advies</strong>: Het Juridisch Loket, gratis <strong>0800-8020</strong> (ma–vr 9.00–17.00).</li><li><strong>Geen eigen bijdrage</strong> in o.a. de meeste asielprocedures, bij een piketadvocaat na aanhouding voor een ernstig strafbaar feit en voor slachtoffers van ernstige gewelds- of zedendelicten.</li></ol>',
body=(
'<h2 id="what">Wat is een toevoeging?</h2><p>Een <strong>toevoeging</strong> is een bijdrage van de <strong>Raad voor Rechtsbijstand (RvR)</strong> in de kosten van een advocaat of mediator. Jij betaalt een deel zelf: de <strong>eigen bijdrage</strong>. Dit heet ook <strong>gesubsidieerde rechtsbijstand</strong>.</p><ul><li><strong>De advocaat vraagt aan</strong>: hij of zij stelt de aanvraag samen met jou op en dient die in; de Raad beslist.</li><li>De Raad krijgt je inkomens- en vermogensgegevens rechtstreeks van de Belastingdienst.</li><li>De eigen bijdrage betaal je <strong>rechtstreeks aan de advocaat of mediator</strong>, niet aan de Raad.</li><li>Rechtsbijstand moet echt nodig zijn en het belang moet minimaal <strong>€ 500</strong> zijn (of <strong>€ 250</strong> als de advocaat maximaal 3 uur nodig heeft).</li><li><strong>Niet gedekt</strong>: griffierecht en proceskosten waartoe je wordt veroordeeld als je verliest.</li></ul>'
'<h2 id="limits">Inkomens- en vermogensgrenzen 2026</h2><p>Voor aanvragen vanaf 1 januari 2026 kijkt de Raad naar je <strong>fiscaal jaarinkomen van 2024</strong>: het <strong>peiljaar</strong>, twee jaar terug.</p>'
+T([['Alleenstaand','t/m € 35.400','€ 36.952'],['Gehuwd, samenwonend of eenoudergezin','t/m € 50.000','€ 73.904 (samen)']],['Situatie','Inkomensgrens (2024)','Vermogensgrens box 3 (2024)'])
+'<p>Een <strong>alleenstaande ouder met kinderen</strong> (eenoudergezin) valt in de kolom van gehuwden en samenwonenden. Vermogen is je box 3-vermogen in 2024 (spaargeld, beleggingen). Boven een van beide grenzen krijg je in principe geen toevoeging.</p>'
'<h2 id="table">Tabel eigen bijdrage 2026</h2>'
+T([['t/m € 25.200','t/m € 35.000','€ 257','€ 448'],['€ 25.201 – € 25.900','€ 35.001 – € 36.200','€ 475','€ 543'],['€ 25.901 – € 27.500','€ 36.201 – € 37.900','€ 678','€ 747'],['€ 27.501 – € 29.800','€ 37.901 – € 42.400','€ 882','€ 950'],['€ 29.801 – € 35.400','€ 42.401 – € 50.000','€ 1.084','€ 1.120'],['boven € 35.400','boven € 50.000','geen toevoeging','geen toevoeging']],['Inkomen 2024 alleenstaand','Inkomen 2024 gehuwd/samenwonend/eenoudergezin','Reguliere toevoeging','Personen- en familierecht'])
+'<p><strong>€ 69 korting</strong>: verleent de Raad een toevoeging, dan gaat er <strong>€ 69</strong> van de eigen bijdrage af. Sinds maart 2020 past de Raad die korting <strong>automatisch</strong> toe; je hoeft niet eerst naar het Juridisch Loket voor een diagnosedocument. Het Juridisch Loket noemt daarom bedragen na korting, zoals € 188 in plaats van € 257, € 1.015 in plaats van € 1.084 en € 379 in plaats van € 448 bij familiezaken.</p>'
+T([['Lichte adviestoevoeging (LAT)','€ 101','€ 170'],['LAT personen- en familierecht','€ 141','€ 187'],['Mediation','€ 69','€ 138']],['Soort','Lage schijf (alleenstaand t/m € 25.900 / gehuwd t/m € 36.200; mediation: € 25.200 / € 35.000)','Hoge schijf (t/m € 35.400 / € 50.000)'])
+'<p>De <strong>Lichte Advies Toevoeging (LAT)</strong> is voor zaken die de advocaat in <strong>maximaal 3 uur</strong> afhandelt, zoals een brief of kort advies. Voor <strong>personen- en familierecht</strong> (scheiding, alimentatie, gezag) is de eigen bijdrage hoger dan voor andere zaken.</p>'
'<h2 id="examples">Rekenvoorbeelden</h2>'
+T([['Alleenstaand, inkomen 2024 € 22.000, conflict met verhuurder','Laagste schijf: € 257 − € 69 = <strong>€ 188</strong>'],['Eenoudergezin, inkomen 2024 € 36.000, alimentatiezaak','Schijf € 35.001–€ 36.200 familierecht: € 543 − € 69 = <strong>€ 474</strong>'],['Alleenstaand, inkomen 2024 € 38.000 (te hoog), in 2026 werkloos met ca. € 24.000','Daling meer dan 15%: <strong>peiljaarverlegging</strong>; bij toekenning € 257 − € 69 = <strong>€ 188</strong>'],['Alleenstaand, inkomen 2024 € 30.000, kort advies over arbeidscontract','LAT, hoge schijf: <strong>€ 170</strong>'],['Stel, inkomen 2024 € 45.000, mediation','Mediation, hoge schijf: <strong>€ 138</strong>'],['Alleenstaand, vermogen 2024 € 45.000','Boven € 36.952: in principe <strong>geen toevoeging</strong>'],['Alleenstaand, krijgt € 25.000 uit de zaak','Meer dan € 19.239,50 (helft van de vrijstelling 2026): toevoeging kan met terugwerkende kracht vervallen']],['Situatie','Berekening'])
+'<p>Illustratief, geen echte personen. De Raad voor Rechtsbijstand beslist over de toevoeging en het precieze bedrag.</p>'
'<h2 id="routes">Welke route bij welk probleem?</h2>'
+T([['Juridische vraag of onduidelijke brief','Het Juridisch Loket: gratis advies bij laag inkomen','0800-8020 (gratis)'],['Kleine zaak, max. 3 uur werk','Lichte adviestoevoeging (LAT)','€ 101–€ 187'],['Geschil of procedure: huur, werk, uitkering, bezwaar','Reguliere toevoeging via advocaat','€ 257–€ 1.084 (min € 69)'],['Scheiding, alimentatie, gezag','Toevoeging personen- en familierecht; advocaat verplicht bij scheiding','€ 448–€ 1.120 (min € 69)'],['Samen tot een oplossing komen','Mediationtoevoeging','€ 69 of € 138'],['Aangehouden voor ernstig strafbaar feit','Piketadvocaat via de politie','Geen eigen bijdrage'],['Asielaanvraag','RvR regelt een advocaat, meestal kosteloos','Meestal geen eigen bijdrage'],['Beëindiging ouderlijk gezag of eerste uithuisplaatsing','Gratis advocaat (tijdelijk, tot 1 januari 2027)','Gratis'],['Loonbeslag of beslag op vermogen','Meestal laagste eigen bijdrage (tijdelijk, tot 1 april 2028)','Laagste schijf'],['Rechtsbijstandverzekering of vakbond','Eerst daar aankloppen','Volgens polis']],['Probleem','Route','Wat betaal je?'])
+'<h2 id="steps">Stap voor stap naar een advocaat met toevoeging</h2><ol><li><strong>Verzamel je papieren</strong>: brief, besluit of contract en de belangrijke data (bezwaartermijn!).</li><li><strong>Bel het Juridisch Loket</strong> (<strong>0800-8020</strong>) of ga langs bij een vestiging. Je krijgt gratis advies en hoort of je een advocaat nodig hebt.</li><li><strong>Zoek een advocaat die op toevoeging werkt</strong>: vraag het altijd vooraf. Alle advocaten staan in het register van de Nederlandse Orde van Advocaten: <strong>zoekeenadvocaat.advocatenorde.nl</strong>. Verwijst het Juridisch Loket je door, dan kan de Raad je een lijst met geschikte advocaten mailen (matching); de advocaat beslist zelf of hij je zaak aanneemt.</li><li><strong>De advocaat dient de aanvraag in</strong> bij de Raad voor Rechtsbijstand. Meld een inkomensdaling (peiljaarverlegging) of beslag op je loon.</li><li><strong>Je ontvangt het besluit</strong> met de eigen bijdrage en betaalt die volgens de factuur van je advocaat.</li><li><strong>Niet eens met het besluit?</strong> Maak <strong>binnen 6 weken</strong> na de dagtekening bezwaar. Ook peiljaarverlegging vraag je uiterlijk binnen 6 weken aan.</li><li><strong>Griffierecht</strong>: ga je naar de rechter, vraag dan het <strong>verlaagde griffierecht</strong> aan met je toevoeging als bewijs.</li></ol>'
'<h2 id="peiljaar">Peiljaar en inkomenswijziging</h2><ul><li><strong>Peiljaar</strong> = twee jaar terug: in 2026 is dat 2024.</li><li><strong>Inkomen gedaald?</strong> Is je inkomen of vermogen in het lopende jaar <strong>minstens 15%</strong> lager dan in het peiljaar (of minder, als je daardoor onder de grenzen komt), dan kun je <strong>peiljaarverlegging</strong> vragen: de Raad rekent dan met het huidige jaar. Dat kan bij de aanvraag of <strong>binnen 6 weken</strong> na het besluit.</li><li><strong>Inkomen gestegen na 2024?</strong> De wet schrijft voor dat de Raad uitgaat van het peiljaar; een hoger inkomen dit jaar telt in de gewone beoordeling niet mee. Let wel op de resultaatsbeoordeling.</li><li><strong>Resultaatsbeoordeling</strong>: krijg je uit de zaak een bedrag van <strong>minstens 50% van het vrijgestelde vermogen</strong> (in 2026: <strong>€ 19.239,50 per persoon</strong>, de helft van € 38.479), of kunnen de kosten op een ander worden verhaald, dan kan de toevoeging <strong>met terugwerkende kracht</strong> worden ingetrokken en betaal je de advocaat zelf.</li></ul>'
'<h2 id="reduced">Lagere, hogere of geen eigen bijdrage</h2><ul><li><strong>Laagste eigen bijdrage</strong> bij Wsnp, schuldhulpverlening of faillissement.</li><li><strong>Loonbeslag of beslag op vermogen</strong>: tijdelijke regeling <strong>tot 1 april 2028</strong>; meestal de laagste eigen bijdrage, ook als je inkomen of vermogen eigenlijk te hoog is. Niet als je een rechtsbijstandverzekering hebt. Vragen: Raad voor Rechtsbijstand <strong>088-787 1234</strong>.</li><li><strong>Nieuwe eigen bijdrage zonder korting</strong>: wissel je van advocaat of zijn extra uren met een nieuwe toevoeging nodig, dan kan een nieuwe eigen bijdrage zonder de € 69 korting volgen.</li><li><strong>Geen eigen bijdrage</strong> (onder voorwaarden): toevoeging op verzoek van rechter of officier van justitie, slachtoffers van ernstige gewelds- of zedendelicten, gedetineerden zonder inkomen (formulier ‘Eigen verklaring vrijheidsontneming’), gedwongen psychiatrische opname, minderjarigen met een bijzondere curator, asielzoekers (formulier ‘Eigen verklaring asielzoeker’) en aanhouding voor een ernstig strafbaar feit met piketadvocaat.</li></ul>'
'<h2 id="asylum">Asiel en strafzaken</h2><ul><li><strong>Asiel</strong>: volgens de IND regelt de Raad voor Rechtsbijstand een advocaat, <strong>meestal kosteloos</strong>, in alle asielprocedures; de kennismaking is meestal kort voor je gehoor bij de IND. Samen met de advocaat vul je de ‘Eigen verklaring asielzoeker’ in. Zie <a href="/nl/articles/asylum-family-reunification.html">Gezinshereniging voor vluchtelingen</a>.</li><li><strong>Aanhouding</strong>: word je aangehouden voor een ernstig strafbaar feit, dan meldt de politie een <strong>piketadvocaat</strong>; daarvoor betaal je geen eigen bijdrage. Wijst de rechter of officier je ambtshalve een advocaat toe, dan ook niet.</li><li><strong>Lichtere strafzaken</strong> zonder aanhouding: een advocaat is niet verplicht maar wel verstandig; vraag naar een reguliere toevoeging.</li></ul>'
'<h2 id="court">Griffierecht en proceskosten</h2><ul><li>De toevoeging betaalt het <strong>griffierecht niet</strong>. Met je toevoeging (of een inkomensverklaring) betaal je wel het <strong>verlaagde tarief</strong> voor lage inkomens: volgens het Juridisch Loket <strong>€ 93 in 2026</strong>. Controleer het tarief voor jouw zaak op rechtspraak.nl; bij de bestuursrechter gelden andere regels.</li><li><strong>Proceskosten</strong>: verlies je, dan kan de rechter je veroordelen in de kosten van de tegenpartij. Die vallen niet onder de toevoeging.</li><li><strong>Advocaat verplicht</strong> bij scheiding en bij civiele zaken boven € 25.000. Bij arbeidszaken, bestuursrecht en strafzaken niet verplicht, wel aan te raden.</li></ul>'
'<h2 id="insurance">Alternatieven: verzekering, vakbond en mediation</h2><ul><li><strong>Rechtsbijstandverzekering</strong> of lid van een <strong>vakbond</strong>? Neem eerst contact met hen op, zeker bij arbeidszaken en letselschade.</li><li><strong>Mediationtoevoeging</strong>: een bij de Raad ingeschreven mediator helpt beide partijen tot afspraken te komen; eigen bijdrage <strong>€ 69</strong> (t/m € 25.200 alleenstaand / € 35.000 gehuwd) of <strong>€ 138</strong> (t/m € 35.400 / € 50.000).</li><li><strong>Inkomen te hoog?</strong> Vraag de advocaat naar een vaste prijs of betalingsafspraak, of begin met gratis advies van het Juridisch Loket.</li></ul>'
'<h2 id="mistakes">Veelgemaakte fouten</h2><ol><li><strong>Te lang wachten</strong> tot een termijn verlopen is: bezwaar- en beroepstermijnen zijn kort en staan in de brief. Bel direct het Juridisch Loket.</li><li><strong>Zelf een toevoeging willen aanvragen</strong>: dat doet de advocaat.</li><li><strong>Niet vooraf vragen</strong> of de advocaat op toevoeging werkt; dan volgt misschien een factuur tegen het volle tarief.</li><li><strong>Peiljaarverlegging vergeten</strong> na baanverlies of scheiding: de termijn is 6 weken.</li><li><strong>Vergeten dat griffierecht apart is</strong>: vraag het verlaagde tarief.</li><li><strong>Ongeregistreerde ‘adviseurs’</strong> die via WhatsApp vooruitbetaling vragen. Controleer het advocatenregister.</li><li><strong>Een oud 0900-nummer bellen</strong>: het Juridisch Loket is gratis bereikbaar via <strong>0800-8020</strong>.</li></ol>'
'<h2 id="help">Gratis hulp</h2><ul><li><strong>Het Juridisch Loket</strong>: gratis <strong>0800-8020</strong>, ma–vr 9.00–17.00; vanuit het buitenland <strong>+31 30 239 2030</strong> (normaal beltarief). Persoonlijk advies voor iedereen met een laag inkomen en weinig spaargeld, met vestigingen in veel steden.</li><li><strong>Raad voor Rechtsbijstand</strong>: vragen over je toevoeging via <strong>088-787 1234</strong>.</li><li><strong>Schulden?</strong> Zie <a href="/nl/articles/debt-help-schuldhulp.html">Gratis schuldhulp</a>.</li></ul>'
'<h2 id="related">Gerelateerde gidsen</h2><ul><li><a href="/nl/articles/tenant-rights-netherlands.html">Huurrechten</a></li><li><a href="/nl/articles/debt-help-schuldhulp.html">Gratis schuldhulp</a></li><li><a href="/nl/articles/social-assistance-bijstand.html">Bijstand</a></li><li><a href="/nl/articles/unemployment-benefit-ww.html">WW-uitkering</a></li><li><a href="/nl/articles/asylum-family-reunification.html">Gezinshereniging voor vluchtelingen</a></li><li><a href="/nl/articles/traffic-fines-cjib.html">Verkeersboetes en CJIB</a></li></ul>'),
faq=[('Kan ik zelf een toevoeging aanvragen?','Nee. Je advocaat of mediator vraagt de toevoeging samen met jou aan bij de Raad voor Rechtsbijstand. Nog geen advocaat? Begin bij het Juridisch Loket, 0800-8020.'),
('Wat is de inkomensgrens in 2026?','€ 35.400 voor alleenstaanden en € 50.000 voor gehuwden, samenwonenden en eenoudergezinnen, op basis van het fiscaal jaarinkomen 2024.'),
('Wat is de vermogensgrens?','€ 36.952 per persoon in box 3 over 2024; volgens het Juridisch Loket € 73.904 voor partners samen.'),
('Hoe hoog is de eigen bijdrage?','Regulier € 257 tot € 1.084, personen- en familierecht € 448 tot € 1.120, met automatisch € 69 korting. LAT € 101–€ 187, mediation € 69 of € 138.'),
('Waarom kijkt de Raad naar 2024?','De wet schrijft het peiljaar van twee jaar terug voor. Is je inkomen nu minstens 15% lager, vraag dan binnen 6 weken na het besluit peiljaarverlegging aan.'),
('Kost bellen met het Juridisch Loket geld?','Nee, 0800-8020 is gratis vanuit Nederland, maandag tot en met vrijdag 9.00–17.00.'),
('Betaalt de toevoeging het griffierecht?','Nee, maar je betaalt wel het verlaagde griffierecht (volgens het Juridisch Loket € 93 in 2026). Proceskosten van de tegenpartij vallen er ook niet onder.'),
('Is een asieladvocaat gratis?','Volgens de IND regelt de Raad meestal kosteloos een advocaat in asielprocedures; met de ‘Eigen verklaring asielzoeker’ geldt in de regel geen eigen bijdrage.'),
('Ik ben aangehouden. Moet ik de advocaat betalen?','Bij aanhouding voor een ernstig strafbaar feit komt een piketadvocaat zonder eigen bijdrage.'),
('Wat als ik geld krijg uit de zaak?','Krijg je minstens 50% van het vrijgestelde vermogen (€ 19.239,50 per persoon in 2026), dan kan de toevoeging met terugwerkende kracht vervallen en betaal je de advocaat zelf.')],
src_note='Gecontroleerd bij de Raad voor Rechtsbijstand (rvr.org en rechtsbijstand.nl), Het Juridisch Loket, Rijksoverheid en de IND op 7 oktober 2026. Tabellen gelden voor aanvragen in 2026 (peiljaar 2024). Vermogensgrens en resultaatsgrens voor partners volgens het Juridisch Loket. Het verlaagde griffierecht verschilt per soort zaak; check rechtspraak.nl. Bedragen voor 2027 zijn nog niet gepubliceerd. Voorbeelden illustratief.')
