from a_student_finance import T
SLUG='birth-parental-leave'
SRC=[('Rijksoverheid · Zwangerschapsverlof en zwangerschapsuitkering aanvragen','https://www.rijksoverheid.nl/onderwerpen/zwangerschapsverlof-en-bevallingsverlof/vraag-en-antwoord/aanvragen-zwangerschapsverlof-en-zwangerschapsuitkering'),
('UWV · Zwangerschapsverlof en bevallingsverlof','https://www.uwv.nl/nl/zwangerschapsverlof-bevallingsverlof'),
('Rijksoverheid · Geboorteverlof voor partners','https://www.rijksoverheid.nl/themas/werk/geboorteverlof-en-partnerverlof/geboorteverlof-voor-partners'),
('UWV · Rekenhulp aanvullend geboorteverlof en betaald ouderschapsverlof','https://www.uwv.nl/particulieren/rekenhulpen/hoe-hoog-is-mijn-uitkering-aanvullend-geboorteverlof-of-betaald-ouderschapsverlof/'),
('Rijksoverheid · Wanneer heb ik recht op betaald ouderschapsverlof?','https://www.rijksoverheid.nl/vraag-en-antwoord/ouderschapsverlof/wanneer-heb-ik-recht-op-betaald-ouderschapsverlof'),
('UWV · Maximum dagloon','https://www.uwv.nl/nl/premies-bedragen/maximum-dagloon')]

AR=dict(title='إجازة الحمل والولادة والأبوة في هولندا 2026: 16 أسبوعاً للأم بأجر كامل، أسبوع للشريك ثم 5 أسابيع بـ70%، و9 أسابيع مدفوعة للأهل — مع أمثلة محسوبة',
crumb='إجازات الولادة',
seo_title='إجازة الحمل والولادة والأبوة 2026',
desc='إجازة الحمل والولادة في هولندا 2026: 16 أسبوعاً للأم بأجر كامل، أسبوع للشريك ثم حتى 5 أسابيع بـ70%، و9 أسابيع إجازة أهل مدفوعة عبر UWV.',
summary='<ol><li><strong>الأم:</strong> إجازة حمل وولادة <strong>16 أسبوعاً على الأقل</strong>، تبدأ <strong>4 أسابيع على الأقل قبل الموعد</strong>، بـ<strong>100%</strong> من الأجر اليومي (بحد أقصى 309.91 يورو يومياً في 2026). أبلغ صاحب العمل قبل 3 أسابيع.</li><li><strong>الشريك:</strong> <strong>أسبوع</strong> (ساعات أسبوع عملك) بأجر كامل من صاحب العمل خلال 4 أسابيع من الولادة، ثم <strong>حتى 5 أسابيع إضافية بـ70%</strong> من UWV خلال 6 أشهر.</li><li><strong>إجازة الأهل المدفوعة:</strong> <strong>9 أسابيع</strong> لكل والد عامل بـ<strong>70%</strong> في السنة الأولى للطفل، من مجموع 26 أسبوعاً.</li><li><strong>العاملون لحسابهم:</strong> إعانة ZEZ من UWV لمدة 16 أسبوعاً على الأقل.</li><li>إن بقي الطفل في المستشفى أكثر من أسبوع: حتى 10 أسابيع إضافية للأم.</li></ol>',
body=(
'<h2 id="overview">كل الإجازات في جدول</h2>'
+T([['إجازة الحمل والولادة','الأم','16 أسبوعاً على الأقل','100% (UWV عبر صاحب العمل)'],['إجازة الولادة للشريك','الشريك','أسبوع واحد خلال 4 أسابيع','100% من صاحب العمل'],['إجازة الولادة الإضافية','الشريك','حتى 5 أسابيع خلال 6 أشهر','70% من UWV'],['إجازة الأهل المدفوعة','كل والد عامل','9 أسابيع في السنة الأولى','70% من UWV'],['إجازة الأهل غير المدفوعة','كل والد عامل','بقية الـ26 أسبوعاً','غير مدفوعة (إلا إن نص الـCAO)']],['الإجازة','لمن','المدة','الأجر'])
+'<h2 id="mother">إجازة الحمل والولادة للأم</h2><ul><li><strong>16 أسبوعاً على الأقل</strong>؛ تبدأ إجازة الحمل <strong>بين 6 و4 أسابيع</strong> قبل الموعد المتوقع (4 أسابيع قبل الموعد على الأقل إلزامياً).</li><li>اطلبها من صاحب العمل <strong>قبل 3 أسابيع على الأقل</strong> مع إفادة الحمل من القابلة أو الطبيب (عن متابعة الحمل والقابلة راجع <a href="/articles/pregnancy-newborn-care.html">دليل الحمل والولادة</a>). صاحب العمل يطلب الإعانة من UWV.</li><li>الإعانة <strong>100%</strong> من أجرك اليومي، بحد أقصى <strong>309.91 يورو</strong> إجمالي يومياً (2026).</li><li>إن وُلد الطفل متأخراً فلا تخسرين من إجازة الولادة؛ وإن بقي الطفل في المستشفى أكثر من أسبوع تحصلين على حتى <strong>10 أسابيع إضافية</strong>.</li><li><strong>العاملة لحسابها:</strong> تطلب إعانة <strong>ZEZ</strong> من UWV بنفسها (16 أسبوعاً على الأقل). راجع <a href="/articles/kvk-zzp-business-netherlands.html">دليل العمل الحر</a>.</li></ul>'
'<h2 id="partner">إجازة الشريك</h2><ol><li><strong>الأسبوع الأول:</strong> مرة واحدة ساعات عملك الأسبوعية، <strong>بأجر كامل من صاحب العمل</strong>، خلال 4 أسابيع من الولادة.</li><li><strong>الإجازة الإضافية:</strong> حتى <strong>5 أضعاف</strong> ساعات عملك الأسبوعية، خلال <strong>6 أشهر</strong> من الولادة، بإعانة UWV بنسبة <strong>70%</strong> من الأجر اليومي (بحد أقصى 70% من الحد الأقصى اليومي). يجب أخذ الأسبوع المدفوع أولاً.</li><li>صاحب العمل يطلب الإعانة من UWV ويدفعها لك، ويدفع UWV معها بدل العطلة. وقد يكمّل الـCAO.</li></ol>'
'<h2 id="parental">إجازة الأهل المدفوعة (9 أسابيع)</h2><ul><li>لكل والد عامل <strong>9 أسابيع</strong> مدفوعة بـ<strong>70%</strong> من الأجر (بحد أقصى 70% من الحد الأقصى اليومي).</li><li>تؤخذ في <strong>السنة الأولى</strong> للطفل، متصلة أو موزعة. ما لم يؤخذ في السنة الأولى يصبح غير مدفوع.</li><li>المجموع الكلي لإجازة الأهل <strong>26 أسبوعاً</strong> (بساعات عملك الأسبوعية).</li><li><strong>لا يجوز لصاحب العمل رفضها</strong>؛ هو يطلب الإعانة من UWV (المعالجة نحو 4 أسابيع).</li><li>للتوائم: فترتان منفصلتان من 9 أسابيع. للتبني والرعاية: خلال سنة من الاستقبال.</li></ul>'
'<h2 id="examples">أمثلة محسوبة (توضيحية)</h2><p>طريقة UWV: <strong>الأجر اليومي (مع بدل العطلة) × 0.70 × 5 أيام</strong> في الأسبوع، حتى للدوام الجزئي.</p>'
+T([['ليلى، أجرها اليومي 150 يورو، إجازة حمل وولادة','150 × 100% = <strong>150 يورو يومياً</strong>؛ نحو 750 يورو أسبوعياً لمدة 16 أسبوعاً'],
    ['يوسف، أجره اليومي 140 يورو، يأخذ 5 أسابيع إضافية','140 × 0.70 × 5 = <strong>490 يورو أسبوعياً</strong> من UWV، لمدة 5 أسابيع ≈ 2,450 يورو'],
    ['رنا، أجرها اليومي 400 يورو، إجازة أهل مدفوعة','الحد: 309.91 × 0.70 = 216.94 يومياً ← × 5 = <strong>1,084.70 يورو أسبوعياً</strong> (لا 1,400)'],
    ['عمر، يعمل 24 ساعة أسبوعياً','إجازة الولادة الإضافية حتى 5 × 24 = 120 ساعة؛ وإجازة الأهل الكلية 26 × 24 = 624 ساعة']],
   ['الحالة','الحساب'])
+'<p>الأسماء والأرقام أمثلة توضيحية على القواعد الرسمية، وليست حالات حقيقية. الأرقام إجمالية قبل الضريبة. احسب حالتك بأداة UWV (رابط في المصادر).</p>'
'<h2 id="money">مع الإجازات: المال والبدلات</h2><ul><li>تُحسب إعانات UWV دخلاً؛ إن انخفض دخلك فحدّث Toeslagen (<a href="/articles/toeslagen-income-update.html">كيف</a>).</li><li>بعد الولادة: سجّل الطفل في البلدية، واطلب إعانة الأطفال وميزانية الأطفال، وأضفه للتأمين الصحي خلال 4 أشهر (<a href="/articles/kinderbijslag-guide.html">إعانة الأطفال</a>).</li><li>عند العودة للعمل: <a href="/articles/childcare-allowance-kinderopvangtoeslag.html">بدل الحضانة</a>.</li></ul>'
'<h2 id="timeline">جدول زمني عملي</h2><ol><li><strong>الأسبوع 20 تقريباً:</strong> أبلغ صاحب العمل بالحمل وخطط للإجازات.</li><li><strong>قبل بدء الإجازة بـ3 أسابيع:</strong> قدّم طلب إجازة الحمل مع الإفادة.</li><li><strong>الولادة:</strong> الشريك يأخذ أسبوعه خلال 4 أسابيع.</li><li><strong>حتى 6 أشهر:</strong> الشريك يأخذ الأسابيع الإضافية.</li><li><strong>قبل عيد الميلاد الأول:</strong> خذ الأسابيع التسعة المدفوعة.</li></ol>'
'<h2 id="mistakes">أخطاء شائعة</h2><ol><li>تأخير طلب إجازة الحمل عن 3 أسابيع.</li><li>الشريك يفوّت مهلة الأشهر الستة.</li><li>ترك الأسابيع التسعة المدفوعة حتى بعد السنة الأولى فتصبح غير مدفوعة.</li><li>نسيان إضافة الطفل للتأمين الصحي.</li></ol>'),
faq=[('كم مدة إجازة الحمل والولادة؟','16 أسبوعاً على الأقل بأجر كامل، تبدأ 4 أسابيع على الأقل قبل الموعد.'),
('كم إجازة الشريك؟','أسبوع بأجر كامل من صاحب العمل، ثم حتى 5 أسابيع بـ70% من UWV خلال 6 أشهر.'),
('ما هي إجازة الأهل المدفوعة؟','9 أسابيع لكل والد عامل بـ70% في السنة الأولى للطفل، من مجموع 26 أسبوعاً.'),
('هل هناك حد أقصى للمبلغ؟','نعم، الأجر اليومي محدود بـ309.91 يورو إجمالي في 2026؛ و70% منه للإجازات بنسبة 70%.'),
('أنا أعمل لحسابي، هل لي إجازة مدفوعة؟','نعم، إعانة ZEZ من UWV لمدة 16 أسبوعاً على الأقل تطلبها بنفسك.'),
('هل يمكن لصاحب العمل رفض إجازة الأهل؟','لا يمكنه رفض إجازة الأهل المدفوعة.')],
src_note='راجعنا Rijksoverheid وUWV في 5 أكتوبر 2026. الأمثلة توضيحية؛ الـCAO قد يعطي أكثر. الحد الأقصى اليومي يُراجع في 1 يناير و1 يوليو.')

NL=dict(title='Zwangerschaps-, geboorte- en ouderschapsverlof in 2026: 16 weken voor de moeder op 100%, partner 1 week plus 5 weken op 70% en 9 weken betaald ouderschapsverlof — met rekenvoorbeelden',
crumb='Verlof rond geboorte',
seo_title='Zwangerschapsverlof en ouderschapsverlof 2026',
desc='Zwangerschapsverlof 2026: minimaal 16 weken op 100%, partner 1 week plus tot 5 weken op 70%, en 9 weken betaald ouderschapsverlof via UWV.',
summary='<ol><li><strong>Moeder:</strong> minimaal <strong>16 weken</strong>, start uiterlijk <strong>4 weken vóór</strong> de uitgerekende datum, <strong>100%</strong> van het dagloon (max. € 309,91 per dag in 2026). Aanvragen minstens 3 weken vooraf.</li><li><strong>Partner:</strong> <strong>1 week</strong> doorbetaald door de werkgever binnen 4 weken, daarna <strong>tot 5 weken op 70%</strong> via UWV binnen 6 maanden.</li><li><strong>Betaald ouderschapsverlof:</strong> <strong>9 weken</strong> per werkende ouder op <strong>70%</strong> in het eerste levensjaar, van in totaal 26 weken.</li><li><strong>Zelfstandigen:</strong> ZEZ-uitkering van UWV, minimaal 16 weken.</li><li>Ligt de baby langer dan een week in het ziekenhuis: tot 10 weken extra.</li></ol>',
body=(
'<h2 id="overview">Alle verloven</h2>'
+T([['Zwangerschaps- en bevallingsverlof','Moeder','Minimaal 16 weken','100% (UWV via werkgever)'],['Geboorteverlof','Partner','1 week binnen 4 weken','100% door werkgever'],['Aanvullend geboorteverlof','Partner','Tot 5 weken binnen 6 maanden','70% via UWV'],['Betaald ouderschapsverlof','Elke werkende ouder','9 weken in eerste jaar','70% via UWV'],['Onbetaald ouderschapsverlof','Elke werkende ouder','Rest van 26 weken','Onbetaald (tenzij cao)']],['Verlof','Voor','Duur','Betaling'])
+'<h2 id="mother">Zwangerschaps- en bevallingsverlof</h2><ul><li><strong>Minimaal 16 weken</strong>; zwangerschapsverlof start tussen 6 en 4 weken vóór de uitgerekende datum (uiterlijk 4 weken vooraf).</li><li>Aanvragen bij de werkgever <strong>minstens 3 weken</strong> vooraf met zwangerschapsverklaring (over verloskundige en kraamzorg: zie onze <a href="/nl/articles/pregnancy-newborn-care.html">gids zwanger en bevallen</a>); de werkgever vraagt de uitkering aan bij UWV.</li><li><strong>100%</strong> van het dagloon, maximaal <strong>€ 309,91</strong> bruto per dag (2026).</li><li>Bij een ziekenhuisopname van de baby langer dan een week: tot <strong>10 weken extra</strong>.</li><li><strong>Zelfstandigen:</strong> <strong>ZEZ</strong>-uitkering zelf aanvragen bij UWV (minimaal 16 weken). Zie ook <a href="/nl/articles/kvk-zzp-business-netherlands.html">zzp’er worden</a>.</li></ul>'
'<h2 id="partner">Geboorteverlof partner</h2><ol><li><strong>Eerste week:</strong> 1× je wekelijkse uren, <strong>100% door de werkgever</strong>, binnen 4 weken na de bevalling.</li><li><strong>Aanvullend:</strong> tot <strong>5×</strong> je wekelijkse uren binnen <strong>6 maanden</strong>, UWV-uitkering van <strong>70%</strong> van het dagloon (max. 70% van het maximumdagloon). Eerst de betaalde week.</li><li>De werkgever vraagt aan bij UWV en betaalt door; UWV betaalt vakantiegeld mee; cao kan aanvullen.</li></ol>'
'<h2 id="parental">Betaald ouderschapsverlof</h2><ul><li><strong>9 weken</strong> per werkende ouder op <strong>70%</strong> (max. 70% van het maximumdagloon).</li><li>In het <strong>eerste levensjaar</strong>, aaneengesloten of flexibel; niet opgenomen weken worden onbetaald.</li><li>Totaal ouderschapsverlof <strong>26 weken</strong>.</li><li><strong>De werkgever kan het niet weigeren</strong>; UWV-verwerking circa 4 weken.</li><li>Tweeling: 2 aparte periodes van 9 weken. Adoptie/pleeg: binnen 1 jaar na plaatsing.</li></ul>'
'<h2 id="examples">Rekenvoorbeelden (illustratief)</h2><p>UWV-methode: <strong>dagloon (incl. vakantiegeld) × 0,70 × 5 dagen</strong> per week, ook bij deeltijd.</p>'
+T([['Laila, dagloon € 150, zwangerschapsverlof','€ 150 × 100% = <strong>€ 150 per dag</strong>; circa € 750 per week, 16 weken'],['Youssef, dagloon € 140, 5 weken aanvullend','140 × 0,70 × 5 = <strong>€ 490 per week</strong>; 5 weken ≈ € 2.450'],['Rana, dagloon € 400, betaald ouderschapsverlof','Max: 309,91 × 0,70 = 216,94 per dag → × 5 = <strong>€ 1.084,70 per week</strong> (niet € 1.400)'],['Omar, 24 uur per week','Aanvullend geboorteverlof tot 5 × 24 = 120 uur; totaal ouderschapsverlof 26 × 24 = 624 uur']],['Situatie','Berekening'])
+'<p>Illustratieve voorbeelden op basis van de officiële regels, geen echte personen; bedragen bruto. Gebruik de UWV-rekenhulp.</p>'
'<h2 id="money">Geld en toeslagen</h2><ul><li>UWV-uitkeringen tellen als inkomen; pas Toeslagen aan (<a href="/nl/articles/toeslagen-income-update.html">inkomen doorgeven</a>).</li><li>Na de geboorte: aangifte bij de gemeente, kinderbijslag en kindgebonden budget, baby binnen 4 maanden bij de zorgverzekeraar (<a href="/nl/articles/kinderbijslag-guide.html">kinderbijslag</a>).</li><li>Terug aan het werk: <a href="/nl/articles/childcare-allowance-kinderopvangtoeslag.html">kinderopvangtoeslag</a>.</li></ul>'
'<h2 id="timeline">Tijdlijn</h2><ol><li><strong>Rond week 20:</strong> werkgever informeren en verlof plannen.</li><li><strong>3 weken vóór verlof:</strong> zwangerschapsverlof aanvragen.</li><li><strong>Geboorte:</strong> partner neemt de betaalde week binnen 4 weken.</li><li><strong>Tot 6 maanden:</strong> aanvullend geboorteverlof.</li><li><strong>Vóór de eerste verjaardag:</strong> 9 betaalde weken.</li></ol>'
'<h2 id="mistakes">Veelgemaakte fouten</h2><ol><li>Zwangerschapsverlof te laat aanvragen.</li><li>Partner mist de 6-maandentermijn.</li><li>De 9 betaalde weken na het eerste jaar opnemen (dan onbetaald).</li><li>Baby niet op tijd bij de zorgverzekeraar.</li></ol>'),
faq=[('Hoe lang is zwangerschaps- en bevallingsverlof?','Minimaal 16 weken op 100%, start uiterlijk 4 weken vóór de uitgerekende datum.'),
('Hoeveel verlof krijgt de partner?','1 week doorbetaald door de werkgever, daarna tot 5 weken op 70% via UWV binnen 6 maanden.'),
('Wat is betaald ouderschapsverlof?','9 weken per werkende ouder op 70% in het eerste levensjaar, van in totaal 26 weken.'),
('Is er een maximum?','Ja, het dagloon is begrensd op € 309,91 bruto (2026); bij 70%-verlof 70% daarvan.'),
('Ik ben zelfstandige. Krijg ik verlof?','Ja, een ZEZ-uitkering van UWV van minimaal 16 weken.'),
('Mag de werkgever ouderschapsverlof weigeren?','Betaald ouderschapsverlof kan de werkgever niet weigeren.')],
src_note='Gecontroleerd bij Rijksoverheid en UWV op 5 oktober 2026. Voorbeelden zijn illustratief; je cao kan meer geven. Het maximumdagloon wijzigt per 1 januari en 1 juli.')
