from a_student_finance import T
SLUG='foreign-driving-license-exchange'
RDW='https://www.rdw.nl/'
SRC=[('RDW · Buitenlands rijbewijs omwisselen',RDW+'het-rijbewijs/buitenlands-rijbewijs/buitenlands-rijbewijs-omwisselen'),
('RDW · Exchanging a foreign driving licence (voorwaarden en landenlijst)',RDW+'en/driving-licence/foreign-driving-licence/exchanging-a-foreign-driving-licence'),
('RDW · Rijden met een buitenlands rijbewijs',RDW+'het-rijbewijs/buitenlands-rijbewijs/rijden-met-een-buitenlands-rijbewijs'),
('RDW · Buitenlands rijbewijs kwijt of gestolen',RDW+'het-rijbewijs/buitenlands-rijbewijs/buitenlands-rijbewijs-kwijt'),
('CBR · Hoeveel tijd heb ik om mijn rijbewijs aan te vragen? (Verklaring van geschiktheid en rijvaardigheid)','https://www.cbr.nl/nl/veelgestelde-vragen/hoeveel-tijd-heb-ik-om-mijn-rijbewijs-aan-te-vragen'),
('CBR · Moet ik een gezondheidsverklaring invullen?','https://www.cbr.nl/nl/rijden-en-uw-gezondheid/moet-ik-een-gezondheidsverklaring-invullen'),
('Rijksoverheid · Fotomatrix (eisen pasfoto)','https://www.rijksoverheid.nl/documenten/brochures/2020/03/23/fotomatrix-2020'),
('Rijksoverheid · Mag ik met mijn buitenlandse rijbewijs in Nederland rijden?','https://www.rijksoverheid.nl/vraag-en-antwoord/mag-ik-met-mijn-buitenlandse-rijbewijs-in-nederland-aan-het-verkeer-deelnemen')]
AR=dict(title='تبديل رخصة القيادة الأجنبية في هولندا 2026: من يحق له، مهلة 185 يوماً، قاعدة 15 سنة لرخص أوروبا، الوثائق والخطوات — مع أمثلة',
crumb='تبديل الرخصة الأجنبية',
desc='دليل عميق لتبديل رخصة القيادة الأجنبية بهولندية عبر البلدية وRDW: الفرق بين رخص الاتحاد الأوروبي (15 سنة، أو سنتان) ورخص خارج أوروبا (185 يوماً)، قائمة الدول المسموحة، شرط تصريح الإقامة، قاعدة 30% (expatregeling)، الوثائق، مدة المعالجة 15 يوم عمل، الرخصة المفقودة، ولماذا يحتاج حامل الرخصة السورية أو العراقية لامتحان CBR.',
summary='<ol><li><strong>رخصة من خارج أوروبا</strong> (سوريا، العراق، تركيا، المغرب، مصر…): تقود بها <strong>185 يوماً</strong> فقط من بدء سكنك في هولندا، ثم لا يجوز القيادة بها، حتى لو كان طلبك قيد المعالجة.</li><li><strong>التبديل دون امتحان</strong> ممكن فقط لرخص الاتحاد الأوروبي/EFTA، ولقائمة RDW (منها بريطانيا، إسرائيل، اليابان، كوريا الجنوبية، سنغافورة، تايوان، ألبرتا وكيبيك)، ولمن لديه <strong>قرار expatregeling (30%)</strong>. <strong>سوريا ليست في القائمة</strong>.</li><li><strong>رخصة أوروبية:</strong> تقود بها حتى <strong>15 سنة</strong> من تاريخ إصدارها (فئات A وB)، أو <strong>سنتين</strong> من بدء سكنك إن كانت أقدم من 15 سنة وما زالت سارية.</li><li><strong>الطلب في البلدية فقط</strong>: صورة، الرخصة الأجنبية، وإفادة صحة من CBR لرخص خارج أوروبا. الرسوم حسب البلدية. خلال <strong>15 يوم عمل</strong> تصلك رسالة، وتستلم بعد <strong>5 أيام عمل</strong>. الرخصة الأجنبية لا تُعاد.</li><li><strong>لا تبديل لرخصة منتهية</strong> من خارج أوروبا، ولا تبديل وأنت تنتظر تصريح إقامة (جديد).</li></ol>',
body=(
'<h2 id="who">من يستطيع التبديل؟ جدول القرار السريع</h2>'
+T([['رخصة من الاتحاد الأوروبي أو EFTA (مثل ألمانيا، بلجيكا، السويد، سويسرا، النرويج)','نعم، دائماً، حتى لو انتهت صلاحيتها.','تقود بها في هولندا حتى 15 سنة من إصدارها (A/B)، أو سنتين من بدء سكنك إن كانت أقدم.'],
    ['رخصة من دولة في قائمة RDW (الجدول التالي)','نعم، بشرط أنك عشت في تلك الدولة 185 يوماً في سنة حصولك على الرخصة.','185 يوماً من بدء سكنك.'],
    ['رخصة من أي دولة + قرار expatregeling (قاعدة 30%) سارٍ','نعم، مع القرار الساري من Belastingdienst.','185 يوماً من بدء سكنك.'],
    ['كان لديك سابقاً رخصة هولندية سارية بعد 30 يونيو 1985','نعم، تحصل على نفس الفئات التي كانت على رخصتك الهولندية.','185 يوماً.'],
    ['رخصة من دولة خارج القائمة: سوريا، العراق، تركيا، المغرب، مصر، إيران، أفغانستان، الولايات المتحدة…','<strong>لا.</strong> يجب اجتياز الامتحان النظري والعملي لدى CBR.','185 يوماً من بدء سكنك، ثم يجب التوقف.'],
    ['أوكرانيا مع حماية مؤقتة (تصريح 46)','التبديل فقط مع قاعدة 30%.','تقود برخصتك ولو انتهت، طوال وضع الحماية المؤقتة.']],
   ['حالة رخصتك','هل تُبدَّل دون امتحان؟','إلى متى تقود بها في هولندا؟'])
+'<p><strong>للاجئين وحاملي الإقامة:</strong> لا توجد في صفحات RDW أي قاعدة خاصة تسمح بتبديل رخصة من دولة خارج القائمة بسبب اللجوء. حتى لو كانت رخصتك قديمة وخبرتك طويلة، فالطريق هو امتحانات CBR. التفاصيل والأسعار في دليلنا <a href="/articles/cbr-driving-license-netherlands.html">رخصة القيادة وامتحان CBR</a>.</p>'
'<h2 id="list">قائمة الدول خارج أوروبا التي تُبدَّل رخصها (حسب RDW)</h2>'
+T([['أندورا','B (سيارة)'],['ألبرتا (كندا)','B (class 5)'],['كيبيك (كندا)','B (class 5)'],['جبل طارق، غيرنزي، جيرسي، جزيرة مان، موناكو','كل الفئات'],['بريطانيا العظمى وإيرلندا الشمالية','كل الفئات (BE فقط إن قدّمت امتحاناً منفصلاً لها)'],['إسرائيل','B (سيارة)'],['اليابان','A وB (1B)'],['سنغافورة','A (class 2) وB (class 3)'],['تايوان','B (سيارة)'],['كوريا الجنوبية','B (الدرجة الأولى والثانية العادية)'],['جزر الأنتيل الهولندية السابقة (أروبا، بونير، كوراساو، سابا، سينت أوستاتيوس، سينت مارتن)','كل الفئات']],['الدولة','الفئة التي تحصل عليها'])
+'<p>القائمة قد تتغير؛ تحقق منها في صفحة RDW قبل الذهاب إلى البلدية. <strong>لا توجد دولة عربية في القائمة</strong> حالياً.</p>'
'<h2 id="conditions">الشروط الأربعة (يجب أن تتوفر كلها)</h2><ol><li><strong>رخصة سارية</strong> من الاتحاد الأوروبي/EFTA أو من دولة في القائمة (رخصة أوروبية منتهية مقبولة؛ رخصة من خارج أوروبا منتهية <strong>غير مقبولة</strong>).</li><li><strong>مسجل في البلدية (BRP)</strong>: انظر <a href="/articles/bsn-municipality-registration.html">التسجيل في البلدية وBSN</a>.</li><li><strong>جنسية أوروبية</strong>، أو <strong>تصريح إقامة مؤقت أو دائم</strong>، أو وضع تركي حسب قرار الشراكة 1/80، أو حماية مؤقتة (تصريح 46). <strong>إن كنت تنتظر تصريح إقامة (جديداً) فلا يمكن التبديل.</strong></li><li>لرخص خارج أوروبا: أنك <strong>عشت 185 يوماً</strong> في البلد المُصدِر في سنة حصولك على الرخصة.</li></ol>'
'<h2 id="eu">رخصة من الاتحاد الأوروبي: كم سنة تقود بها؟</h2>'
+T([['AM، A1، A2، A، B، BE','حتى 15 سنة من تاريخ الإصدار، بشرط أن تكون سارية'],['C1، C، D1، D، C1E، CE، D1E، DE','حتى 5 سنوات من تاريخ الإصدار، بشرط أن تكون سارية'],['رخصة صدرت منذ أكثر من 15 سنة (أو 5 لفئات C/D) وما زالت سارية','سنتان من تاريخ بدء سكنك في هولندا'],['رخصة أوروبية صدرت وأنت مسجل في هولندا','لا يجوز القيادة بها؛ يجب تبديلها']],['الفئة','مدة القيادة في هولندا'])
+'<p>بعد هذه المدة لا يجوز القيادة دون رخصة هولندية، حتى لو كان طلب التبديل قيد المعالجة. RDW تحتاج <strong>15 يوم عمل على الأقل</strong>، فقدّم مبكراً.</p>'
'<h2 id="examples">أمثلة محسوبة (توضيحية)</h2>'
+T([['شخص سجّل في البلدية يوم 1 مارس 2026 ومعه رخصة سورية سارية','آخر يوم للقيادة بها تقريباً بعد 185 يوماً، أي نحو 2 سبتمبر 2026. بعده: لا قيادة حتى ينجح في امتحانَي CBR.'],
    ['شخص لديه رخصة ألمانية B صدرت في 1 يناير 2019، وسكن في هولندا منذ 15 يونيو 2024','يقود بها حتى 1 يناير 2034 (15 سنة من الإصدار) إن بقيت سارية. (هذا المثال مأخوذ من صفحة RDW.)'],
    ['شخص لديه رخصة بلجيكية B صدرت عام 2008، وسكن في هولندا في 1 فبراير 2026','الرخصة أقدم من 15 سنة: يقود بها سنتين حتى 1 فبراير 2028، ثم يجب التبديل.'],
    ['شخص يعمل بقرار expatregeling ومعه رخصة أمريكية','يستطيع التبديل مع القرار الساري، رغم أن الولايات المتحدة ليست في القائمة.'],
    ['شخص معه رخصة كورية جنوبية حصل عليها وهو يدرس هناك 4 أشهر فقط','قد يُرفض: شرط 185 يوماً من السكن في كوريا في سنة الحصول عليها غير متحقق.']],
   ['الحالة','النتيجة'])
+'<p>هذه أمثلة توضيحية وليست حالات أشخاص حقيقيين. احسب الأيام من تاريخ بدء سكنك المسجل، وتأكد من تاريخك الدقيق عند البلدية.</p>'
'<h2 id="steps">خطوات التبديل في البلدية</h2><ol><li><strong>تحقق من الأهلية</strong> عبر قائمة RDW الإلكترونية (checklist) قبل الحجز.</li><li><strong>إفادة الصحة (Gezondheidsverklaring)</strong> عبر Mijn CBR إن كانت رخصتك من خارج أوروبا (وأحياناً لرخص أوروبية، مثلاً لفئات C/D أو لأسباب صحية). تستغرق وقتاً، فابدأ بها مبكراً. يمكن تسليمها لاحقاً إن كانت رخصتك على وشك الانتهاء.</li><li><strong>احجز موعداً في البلدية</strong> واحمل معك:<ul><li>صورة شخصية ملونة حسب معايير الصور الرسمية.</li><li>الرخصة الأجنبية الأصلية. إن كانت بحروف غير لاتينية (مثل العربية أو اليابانية) فاحضر <strong>ترجمة محلّفة</strong> أو ترجمة من السفارة أو القنصلية.</li><li>رخصة هولندية قديمة إن وُجدت.</li><li>قرار expatregeling الساري إن كنت تعتمد عليه.</li><li>وثيقة هوية سارية أو تصريح الإقامة.</li></ul></li><li><strong>املأ استمارة الطلب وادفع الرسوم</strong>. الرسوم تختلف من بلدية لأخرى؛ تحقق من موقع بلديتك.</li><li><strong>البلدية ترسل الطلب إلى RDW</strong>؛ أنت لا تستطيع التقديم مباشرة لدى RDW.</li><li><strong>خلال 15 يوم عمل</strong> تصلك رسالة بأن الرخصة جاهزة للاستلام بعد <strong>5 أيام عمل</strong>. إن نقصت معلومات تصلك رسالة وتطول المدة.</li><li><strong>استلم الرخصة الهولندية</strong>. الرخصة الأجنبية لا تُعاد إليك.</li></ol>'
'<h2 id="during">القيادة أثناء معالجة الطلب</h2><ul><li>القرار لك: يجوز القيادة إن كانت لديك رخصة سارية ولم تنتهِ مدة الـ185 يوماً (أو 15 سنة/سنتين للأوروبية).</li><li>إن أوقفتك الشرطة يجب أن تُظهر رخصتك، وقد تعطيك غرامة إن لم تستطع. تستطيع الشرطة التحقق لدى RDW من طلب التبديل، فالخطر صغير لكنه موجود.</li><li>احمل جوازك أو بطاقتك دائماً.</li><li>التأمين: إن كانت لديك رخصة سارية وتأمين، فأنت مؤمَّن حتى لو لم تستطع إظهار الرخصة؛ استفسر من شركة التأمين.</li><li>RDW تنصح بعدم القيادة في دول أخرى أثناء الطلب.</li></ul>'
'<h2 id="lost">رخصتك الأجنبية ضاعت أو سُرقت</h2>'
+T([['رخصة من الاتحاد الأوروبي/EFTA أو أروبا أو الأنتيل السابقة','اذهب للبلدية بمحضر من الشرطة الهولندية أو إفادة فقدان من البلدية، مع صورة وهوية. تحصل على رخصة هولندية (لا رخصة أجنبية جديدة). شهادة الأصالة (echtheidsverklaring) غير إلزامية للرخص الأوروبية؛ إن لم تكن معك تطلبها RDW ويطول الطلب.'],
    ['رخصة من خارج أوروبا','اطلب رخصة جديدة من البلد الذي أصدرها. إن تعذّر ذلك، فيجب الامتحان في هولندا. استثناء: من كانت لديه رخصة هولندية سارية بعد 30 يونيو 1985 يتواصل مع RDW.']],
   ['نوع الرخصة','ماذا تفعل'])
+'<h2 id="exam">إن لم يكن التبديل ممكناً: طريق CBR</h2><ul><li>تقدّم الامتحان النظري ثم العملي لدى CBR. اللغات: الهولندية أو الإنجليزية، أو مع مترجم معتمد. الأسعار والتفاصيل في <a href="/articles/cbr-driving-license-netherlands.html">دليل رخصة القيادة وCBR</a>.</li><li>بعد النجاح في العملي يسجل CBR باسمك <strong>إفادتين</strong> في سجل الرخص:<ul><li><strong>Verklaring van geschiktheid</strong> (الأهلية الصحية): صالحة <strong>سنة واحدة</strong> من يوم النجاح.</li><li><strong>Verklaring van rijvaardigheid</strong> (إثبات مهارة القيادة): صالحة <strong>3 سنوات</strong> من يوم النجاح. إن لم تطلب الرخصة خلالها، تعيد النظري والعملي.</li></ul></li><li>اطلب الرخصة من البلدية بسرعة بعد النجاح حتى لا تنتهي إفادة الأهلية الصحية.</li></ul>'
'<h2 id="mistakes">أخطاء شائعة</h2><ol><li><strong>الاستمرار بالقيادة</strong> برخصة سورية أو عراقية بعد مرور 185 يوماً على التسجيل.</li><li><strong>ترك رخصة قابلة للتبديل تنتهي</strong> (مثلاً بريطانية أو يابانية) قبل التقديم؛ بعد الانتهاء لا تُبدَّل. ابدأ الطلب قبل الانتهاء وسلّم إفادة الصحة لاحقاً.</li><li><strong>التقديم وأنت تنتظر تصريح إقامة جديد</strong>؛ سيُرفض.</li><li><strong>نسيان الترجمة المحلّفة</strong> لرخصة بحروف غير لاتينية.</li><li><strong>تصديق شائعات المجموعات</strong> بأن «اللاجئ يبدّل رخصته»؛ لا توجد قاعدة رسمية كهذه.</li><li><strong>تأجيل إفادة الصحة</strong> حتى آخر لحظة؛ هي غالباً سبب التأخير.</li></ol>'
'<h2 id="related">أدلة مرتبطة</h2><ul><li><a href="/articles/cbr-driving-license-netherlands.html">رخصة القيادة وامتحانات CBR وأسعارها</a></li><li><a href="/articles/traffic-fines-cjib.html">المخالفات المرورية وCJIB: الدفع والاعتراض والتقسيط</a></li><li><a href="/articles/bsn-municipality-registration.html">التسجيل في البلدية</a></li><li><a href="/articles/change-address-netherlands.html">تغيير العنوان</a></li><li><a href="/articles/trending-jobs-2026.html">المهن المطلوبة (منها السائقون)</a></li></ul>'),
faq=[('هل أستطيع تبديل رخصتي السورية أو العراقية بهولندية؟','لا. هذه الدول ليست في قائمة RDW، ولا يوجد استثناء للاجئين. يجب اجتياز النظري والعملي لدى CBR، إلا إن كان لديك قرار expatregeling (30%).'),
('كم يوماً أقود برخصتي الأجنبية بعد وصولي؟','لرخص خارج أوروبا: 185 يوماً من بدء سكنك المسجل. لرخص الاتحاد الأوروبي: حتى 15 سنة من الإصدار (A/B)، أو سنتين من بدء السكن إن كانت أقدم.'),
('أين أقدم طلب التبديل؟','في البلدية التي أنت مسجل فيها فقط، وهي ترسل الطلب إلى RDW.'),
('كم يستغرق التبديل؟','إن كان كل شيء صحيحاً: رسالة خلال 15 يوم عمل، ثم الاستلام بعد 5 أيام عمل. إفادة الصحة من CBR تحتاج وقتاً إضافياً.'),
('هل تُعاد لي رخصتي الأجنبية؟','لا. RDW لا تعيد الرخصة الأجنبية بعد التبديل.'),
('رخصتي من خارج أوروبا انتهت صلاحيتها، هل أستطيع تبديلها؟','لا، RDW لا تبدّل رخصة منتهية من خارج أوروبا. ابدأ الطلب قبل الانتهاء. الرخص الأوروبية المنتهية تُبدَّل.')],
src_note='راجعنا صفحات RDW (بالهولندية والإنجليزية) وCBR في 7 أكتوبر 2026. رسوم البلدية للتبديل وسعر إفادة الصحة يتغيران؛ لم نذكر مبلغاً، فتحقق في موقع بلديتك وفي Mijn CBR. الأمثلة توضيحية وليست أشخاصاً حقيقيين.')
NL=dict(title='Buitenlands rijbewijs omwisselen in 2026: wie mag het, de 185-dagenregel, 15 jaar voor EU-rijbewijzen, documenten en stappen — met voorbeelden',
crumb='Buitenlands rijbewijs omwisselen',
desc='Uitgebreide gids voor het omwisselen van een buitenlands rijbewijs via gemeente en RDW: EU/EVA (15 jaar of 2 jaar) versus niet-EU (185 dagen), de landenlijst, verblijfsvergunning als voorwaarde, de expatregeling (30%), documenten, 15 werkdagen behandeltijd, rijbewijs kwijt, en waarom een Syrisch of Iraaks rijbewijs CBR-examen vraagt.',
summary='<ol><li><strong>Rijbewijs van buiten Europa</strong> (Syrië, Irak, Turkije, Marokko, Egypte…): rijden mag tot <strong>185 dagen</strong> na vestiging in Nederland, daarna niet meer, ook niet als de aanvraag loopt.</li><li><strong>Omwisselen zonder examen</strong> kan alleen met een EU/EVA-rijbewijs, een rijbewijs uit de RDW-landenlijst (o.a. VK, Israël, Japan, Zuid-Korea, Singapore, Taiwan, Alberta, Québec) of met een <strong>beschikking expatregeling (30%)</strong>. <strong>Syrië staat niet op de lijst.</strong></li><li><strong>EU-rijbewijs:</strong> rijden tot <strong>15 jaar</strong> na afgifte (A/B), of <strong>2 jaar</strong> na vestiging als het ouder is dan 15 jaar en nog geldig.</li><li><strong>Aanvragen alleen via de gemeente</strong>: pasfoto, buitenlands rijbewijs, CBR-gezondheidsverklaring bij niet-EU. Kosten per gemeente. Binnen <strong>15 werkdagen</strong> een brief, ophalen na <strong>5 werkdagen</strong>. Het buitenlandse rijbewijs krijg je niet terug.</li><li><strong>Geen omwisseling</strong> van een verlopen niet-EU-rijbewijs, of als je wacht op een (nieuwe) verblijfsvergunning.</li></ol>',
body=(
'<h2 id="who">Wie kan omwisselen? Beslistabel</h2>'
+T([['EU/EVA-rijbewijs (bijv. Duitsland, België, Zweden, Zwitserland, Noorwegen)','Ja, altijd, ook als het verlopen is.','Tot 15 jaar na afgifte (A/B), of 2 jaar na vestiging als het ouder is.'],
    ['Rijbewijs uit een land op de RDW-lijst','Ja, als je in het jaar van afgifte 185 dagen in dat land woonde.','185 dagen na vestiging.'],
    ['Rijbewijs uit elk land + geldige beschikking expatregeling (30%)','Ja.','185 dagen na vestiging.'],
    ['Eerder een Nederlands rijbewijs gehad dat na 30 juni 1985 geldig was','Ja, met dezelfde categorieën als op dat Nederlandse rijbewijs.','185 dagen.'],
    ['Land niet op de lijst: Syrië, Irak, Turkije, Marokko, Egypte, Iran, Afghanistan, VS…','<strong>Nee.</strong> Theorie- en praktijkexamen bij het CBR.','185 dagen na vestiging, daarna stoppen.'],
    ['Oekraïne met tijdelijke bescherming (verblijfstitel 46)','Alleen met 30%-regeling.','Rijden met eigen rijbewijs, ook als het verlopen is.']],
   ['Jouw rijbewijs','Omwisselen zonder examen?','Hoe lang rijden in NL?'])
+'<p><strong>Statushouders:</strong> RDW kent geen aparte regel waarmee een rijbewijs van buiten de lijst vanwege een asielstatus kan worden omgewisseld. De route is het CBR-examen; zie <a href="/nl/articles/cbr-driving-license-netherlands.html">Rijbewijs halen bij het CBR</a>.</p>'
'<h2 id="list">Landen buiten de EU/EVA waarvan je het rijbewijs kunt omwisselen (RDW)</h2>'
+T([['Andorra','B'],['Alberta (Canada)','B (class 5)'],['Québec (Canada)','B (class 5)'],['Gibraltar, Guernsey, Jersey, Isle of Man, Monaco','Alle categorieën'],['Groot-Brittannië en Noord-Ierland','Alle categorieën (BE alleen met apart examen)'],['Israël','B'],['Japan','A en B (1B)'],['Singapore','A (class 2) en B (class 3)'],['Taiwan','B'],['Zuid-Korea','B (1st/2nd class ordinary)'],['Voormalige Nederlandse Antillen (Aruba, Bonaire, Curaçao, Saba, Sint Eustatius, Sint Maarten)','Alle categorieën']],['Land','Categorie'])
+'<p>De lijst kan wijzigen; controleer de RDW-site vóór je naar de gemeente gaat. Er staat <strong>geen Arabisch land</strong> op de lijst.</p>'
'<h2 id="conditions">Vier voorwaarden (allemaal)</h2><ol><li><strong>Geldig rijbewijs</strong> uit de EU/EVA of een lijstland (verlopen EU/EVA mag; verlopen niet-EU <strong>niet</strong>).</li><li><strong>Ingeschreven in de BRP</strong>: zie <a href="/nl/articles/bsn-municipality-registration.html">Inschrijven bij de gemeente</a>.</li><li><strong>EU/EVA-nationaliteit</strong>, of een <strong>tijdelijke of permanente verblijfsvergunning</strong>, of Besluit 1/80 EEG-Turkije, of tijdelijke bescherming (46). <strong>Wacht je op een (nieuwe) verblijfsvergunning, dan kan het niet.</strong></li><li>Bij niet-EU: <strong>185 dagen</strong> gewoond in het land van afgifte in het jaar van afgifte.</li></ol>'
'<h2 id="eu">EU-rijbewijs: hoe lang mag je ermee rijden?</h2>'
+T([['AM, A1, A2, A, B, BE','Tot 15 jaar na afgifte, mits geldig'],['C1, C, D1, D, C1E, CE, D1E, DE','Tot 5 jaar na afgifte, mits geldig'],['Afgegeven langer dan 15 jaar (of 5 jaar voor C/D) geleden en nog geldig','2 jaar na vestiging in Nederland'],['EU-rijbewijs afgegeven terwijl je al in NL ingeschreven stond','Niet mee rijden; omwisselen']],['Categorie','Rijden in Nederland'])
+'<p>Daarna mag je niet rijden zonder Nederlands rijbewijs, ook niet als de aanvraag nog loopt. RDW heeft <strong>minimaal 15 werkdagen</strong> nodig.</p>'
'<h2 id="examples">Rekenvoorbeelden (illustratief)</h2>'
+T([['Ingeschreven op 1 maart 2026 met geldig Syrisch rijbewijs','Rijden tot ongeveer 185 dagen later, rond 2 september 2026. Daarna pas weer na CBR-examens.'],
    ['Duits B-rijbewijs afgegeven 1 januari 2019, in NL sinds 15 juni 2024','Rijden tot 1 januari 2034 (15 jaar na afgifte), mits geldig. (Voorbeeld van de RDW-site.)'],
    ['Belgisch B-rijbewijs uit 2008, in NL sinds 1 februari 2026','Ouder dan 15 jaar: rijden tot 1 februari 2028, daarna omwisselen.'],
    ['Expat met 30%-beschikking en Amerikaans rijbewijs','Omwisselen mogelijk met geldige beschikking.'],
    ['Zuid-Koreaans rijbewijs, gehaald tijdens 4 maanden studie daar','Mogelijk afgewezen: niet 185 dagen in Korea gewoond in het jaar van afgifte.']],
   ['Situatie','Uitkomst'])
+'<p>Illustratieve voorbeelden, geen echte personen. Reken vanaf je ingeschreven vestigingsdatum.</p>'
'<h2 id="steps">Stappen bij de gemeente</h2><ol><li><strong>Check</strong> met de RDW-checklist of omwisselen kan.</li><li><strong>Gezondheidsverklaring</strong> via Mijn CBR bij een niet-EU-rijbewijs (soms ook bij EU, bijv. C/D). Begin op tijd; je mag hem later nasturen als je rijbewijs bijna verloopt.</li><li><strong>Afspraak bij de gemeente</strong> met:<ul><li>kleurenpasfoto volgens de fotomatrix;</li><li>origineel buitenlands rijbewijs, met <strong>beëdigde vertaling</strong> (of van ambassade/consulaat) bij niet-Latijnse tekens zoals Arabisch;</li><li>oud Nederlands rijbewijs indien aanwezig;</li><li>geldige beschikking expatregeling indien van toepassing;</li><li>geldig identiteitsbewijs of verblijfsdocument.</li></ul></li><li><strong>Formulier invullen en betalen</strong>; de kosten verschillen per gemeente.</li><li><strong>De gemeente stuurt alles naar RDW</strong>; zelf indienen bij RDW kan niet.</li><li><strong>Binnen 15 werkdagen</strong> een brief; ophalen na <strong>5 werkdagen</strong>. Ontbreekt iets, dan duurt het langer.</li><li><strong>Ophalen</strong>; het buitenlandse rijbewijs krijg je niet terug.</li></ol>'
'<h2 id="during">Rijden tijdens de aanvraag</h2><ul><li>Je kiest zelf; rijden mag als je een geldig rijbewijs hebt en de termijn nog loopt.</li><li>Bij een controle moet je een rijbewijs tonen; anders kan een boete volgen. De politie kan bij RDW de aanvraag nagaan: klein maar reëel risico.</li><li>Neem altijd paspoort of ID mee.</li><li>Met geldig rijbewijs en verzekering ben je verzekerd, ook als je het niet kunt tonen; vraag het je verzekeraar.</li><li>RDW raadt rijden in andere landen tijdens de aanvraag af.</li></ul>'
'<h2 id="lost">Buitenlands rijbewijs kwijt of gestolen</h2>'
+T([['EU/EVA, Aruba of voormalige Antillen','Naar de gemeente met proces-verbaal of verklaring van vermissing, pasfoto en ID. Je krijgt een Nederlands rijbewijs. Echtheidsverklaring bij EU/EVA niet verplicht; RDW vraagt hem anders zelf op (duurt langer).'],
    ['Buiten de EU/EVA','Nieuw rijbewijs aanvragen in het land van afgifte; lukt dat niet, dan examen in Nederland. Had je een NL-rijbewijs geldig na 30 juni 1985? Neem contact op met RDW.']],
   ['Rijbewijs','Wat doe je'])
+'<h2 id="exam">Omwisselen kan niet: de CBR-route</h2><ul><li>Theorie- en praktijkexamen bij het CBR (Nederlands, Engels of met tolk). Tarieven in <a href="/nl/articles/cbr-driving-license-netherlands.html">Rijbewijs halen bij het CBR</a>.</li><li>Na het slagen zet het CBR twee verklaringen in het rijbewijsregister:<ul><li><strong>Verklaring van geschiktheid</strong>: <strong>1 jaar</strong> geldig vanaf de slagingsdatum.</li><li><strong>Verklaring van rijvaardigheid</strong>: <strong>3 jaar</strong> geldig; daarna opnieuw theorie en praktijk.</li></ul></li><li>Vraag je rijbewijs dus snel aan bij de gemeente.</li></ul>'
'<h2 id="mistakes">Veelgemaakte fouten</h2><ol><li>Na 185 dagen doorrijden met een Syrisch of Iraaks rijbewijs.</li><li>Een omwisselbaar niet-EU-rijbewijs laten verlopen; daarna kan het niet meer.</li><li>Aanvragen terwijl je op een nieuwe verblijfsvergunning wacht.</li><li>Geen beëdigde vertaling bij niet-Latijns schrift.</li><li>Geloven dat statushouders altijd mogen omwisselen: die regel bestaat niet.</li><li>De gezondheidsverklaring te laat aanvragen.</li></ol>'
'<h2 id="related">Gerelateerde gidsen</h2><ul><li><a href="/nl/articles/cbr-driving-license-netherlands.html">Rijbewijs halen bij het CBR</a></li><li><a href="/nl/articles/traffic-fines-cjib.html">Verkeersboetes en het CJIB</a></li><li><a href="/nl/articles/bsn-municipality-registration.html">Inschrijven bij de gemeente</a></li><li><a href="/nl/articles/change-address-netherlands.html">Adres wijzigen</a></li><li><a href="/nl/articles/trending-jobs-2026.html">Kansberoepen (o.a. chauffeur)</a></li></ul>'),
faq=[('Kan ik mijn Syrische of Iraakse rijbewijs omwisselen?','Nee. Die landen staan niet op de RDW-lijst en er is geen uitzondering voor statushouders. Je doet CBR-examen, tenzij je een beschikking expatregeling hebt.'),
('Hoe lang mag ik met mijn buitenlandse rijbewijs rijden?','Niet-EU: 185 dagen na vestiging. EU/EVA: tot 15 jaar na afgifte (A/B), of 2 jaar na vestiging als het ouder is.'),
('Waar vraag ik omwisseling aan?','Alleen bij de gemeente waar je ingeschreven staat; die stuurt het naar RDW.'),
('Hoe lang duurt omwisselen?','Binnen 15 werkdagen een brief, daarna ophalen na 5 werkdagen. De CBR-gezondheidsverklaring kost extra tijd.'),
('Krijg ik mijn buitenlandse rijbewijs terug?','Nee.'),
('Mijn niet-EU-rijbewijs is verlopen. Kan ik nog omwisselen?','Nee. Start vóór de vervaldatum; een verlopen EU/EVA-rijbewijs kan wel.')],
src_note='Gecontroleerd bij RDW (NL en EN) en CBR op 7 oktober 2026. Gemeentelijke kosten en het tarief van de gezondheidsverklaring wisselen; daarom geen bedrag — check je gemeente en Mijn CBR. Voorbeelden illustratief, geen echte personen.')
