from a_student_finance import T
SLUG='mbo-hbo-wo-comparison'
SRC=[('Nuffic · Higher education in the Netherlands','https://www.nuffic.nl/en/education-systems/the-netherlands/higher-education'),
('Rijksoverheid · Met welke diplomas kan ik naar hbo of universiteit?','https://www.rijksoverheid.nl/vraag-en-antwoord/hoger-onderwijs/met-welke-diploma-s-kan-ik-naar-de-universiteit-of-hogeschool'),
('DUO · Collegegeld','https://www.duo.nl/particulier/collegegeld.jsp'),
('Rijksoverheid · Hoogte collegegeld hogeschool/universiteit','https://www.rijksoverheid.nl/vraag-en-antwoord/hoger-onderwijs/hoogte-van-het-collegegeld-hogeschool-universiteit'),
('Rijksoverheid · Hoogte lesgeld en cursusgeld mbo','https://www.rijksoverheid.nl/vraag-en-antwoord/middelbaar-beroepsonderwijs/hoogte-lesgeld-en-cursusgeld-mbo'),
('Rijksoverheid · Uit welke mbo-opleidingen kan ik kiezen?','https://www.rijksoverheid.nl/vraag-en-antwoord/middelbaar-beroepsonderwijs/uit-welke-mbo-opleidingen-kan-ik-kiezen')]
AR=dict(title='MBO وHBO وWO: الفرق بين المسارات، والقبول، والتكلفة، وكيف تنتقل بينها',
crumb='MBO وHBO وWO',
seo_title='الفرق بين MBO وHBO وWO في هولندا',
desc='الفرق بين MBO وHBO وWO: المدة وشروط القبول (havo أو vwo أو MBO-4)، والرسوم (collegegeld 2,694 يورو في 2026/27)، وكيف تنتقل بين المسارات.',
summary='<ol><li><strong>MBO:</strong> تعليم مهني عملي. <strong>HBO:</strong> جامعات علوم تطبيقية موجهة لمهنة. <strong>WO:</strong> جامعات بحثية أكثر نظرية.</li><li>إلى <strong>HBO</strong> تدخل بشهادة <strong>havo</strong> أو <strong>MBO مستوى 4</strong>؛ وإلى <strong>WO</strong> بشهادة <strong>vwo</strong> أو <strong>propedeuse</strong> من HBO (أحياناً مع شروط إضافية).</li><li>مدة بكالوريوس HBO <strong>4 سنوات</strong> (240 ECTS)، وWO <strong>3 سنوات</strong> (180 ECTS)، وMBO مستوى 4 عادة <strong>3–4 سنوات</strong>.</li><li>الـ<strong>collegegeld</strong> القانوني في HBO وWO لعام 2026/27: <strong>2,694 يورو</strong>؛ وفي MBO BOL 18+ يدفع lesgeld 1,511 يورو.</li><li>الانتقال ممكن بين المسارات؛ والمعيار شهادتك وشروط البرنامج.</li></ol>',
body=(
'<h2 id="table">الفروق باختصار</h2>'
+T([['الطابع','عملي مهني، تأهيل لمهنة','عملي ومهني بمستوى أعلى، موجه لمهنة (Nuffic)','نظري وبحثي أكثر (جامعات)'],['الشهادة','Diploma MBO','Bachelor (مثل BBA وBSc)','Bachelor (BA/BSc/LLB)'],['المدة','مستوى 4: 3 أو 4 سنوات','4 سنوات (240 ECTS)','3 سنوات (180 ECTS)'],['القبول','شهادة الدراسة السابقة (حسب المستوى)','havo أو MBO-4 (وأحياناً شروط إضافية)','vwo أو propedeuse من HBO (وأحياناً شروط إضافية)'],['الرسوم القانونية 2026/27','lesgeld 1,511 (BOL، 18+)؛ cursusgeld لـBBL','collegegeld 2,694 (دوام كامل)','collegegeld 2,694 (دوام كامل)'],['بعدها','عمل، أو HBO من مستوى 4','عمل، أو ماستر HBO','ماستر WO (وقد يكون ماستر HBO ممكناً)']],['','MBO','HBO','WO'])
+'<p>مصادر المدد والقبول: Nuffic وRijksoverheid. بعض برامج HBO فيها مسارات مكثفة لحاملي vwo (3 سنوات).</p>'
'<h2 id="mbo">MBO: متى؟</h2><ul><li>تريد مهنة محددة سريعاً (رعاية، تقنية، ضيافة، تجارة...).</li><li>لا تملك شهادة havo أو vwo، أو تفضل التعلم بالممارسة.</li><li>تقدر أن تعمل أثناء الدراسة عبر BBL (<a href="/articles/bol-bbl-comparison.html">BOL أم BBL</a>).</li></ul><p>شروط التسجيل في <a href="/articles/mbo-conditions.html">شروط MBO</a>.</p>'
'<h2 id="hbo">HBO: متى؟</h2><ul><li>تريد مهنة بمستوى بكالوريوس مع تدريب عملي (في السنة الثالثة غالباً تدريب نحو 9 أشهر بحسب Nuffic).</li><li>تحمل havo أو MBO-4.</li><li>بعد HBO: العمل، أو <strong>ماستر HBO</strong>، وهو غالباً سنة واحدة (60 ECTS).</li></ul>'
'<h2 id="wo">WO: متى؟</h2><ul><li>تريد دراسة أكاديمية وبحثاً.</li><li>تحمل vwo أو propedeuse من HBO.</li><li>الماستر بعد بكالوريوس WO يفتح مسار الدكتوراه والأعمال البحثية.</li></ul>'
'<h2 id="admission">القبول والشهادات الأجنبية</h2><p>كل برنامج قد يضع <strong>شروطاً إضافية</strong> (مواد معينة، مهارات). والشهادة الأجنبية تحتاج تقييماً (<a href="/articles/diploma-evaluation-sbb.html">دليل التقييم</a>) ليقرر المعهد معادلها الهولندي. أسئلة تستحق التأكد منها مع المعهد: هل شهادتي تعادل havo أو vwo؟ وما متطلبات اللغة (هولندية أو إنجليزية)؟ وهل هناك تخصصات بعدد مقاعد محدود؟ هذه نقاط للسؤال لا قواعد عامة، وتتغير بين البرامج.</p>'
'<h2 id="cost">الرسوم والتمويل</h2>'
+T([['MBO BOL 18+ (lesgeld)','1,511','1,554'],['MBO BBL (cursusgeld)','314 أو 762','323 أو 784'],['HBO/WO دوام كامل (collegegeld قانوني)','2,694','—'],['HBO/WO دوام جزئي أو duaal','بين 1,604 و2,694','—']],['النوع','2026/2027 (يورو)','2027/2028 (يورو)'])
+'<ul><li>يدفع <strong>collegegeld القانوني</strong> غالب الطلاب: من هو مسجل في برنامج ممول حكومياً، ولم يحصل بعد على شهادة بالمستوى نفسه، وله جنسية هولندية أو من الاتحاد الأوروبي/EEA أو سويسرا أو سورينام، <strong>أو إقامة هولندية من أنواع محددة</strong> (وفق DUO: النوع II وIII وIV وV، أو النوع I الذي يعطي حق studiefinanciering، وغيرها). غير ذلك قد يدفع <strong>instellingscollegegeld</strong> وهو لا يقل أبداً عن القانوني.</li><li>التمويل (studiefinanciering وقرض الرسوم) في <a href="/articles/student-finance.html">دليل تمويل الدراسة</a>. يمكن الاقتراض لدفع الرسوم بحد أقصى 5 أضعاف collegegeld القانوني.</li><li>إن كنت أكبر سناً أو انتهى حقك في التمويل فراجع <a href="/articles/adult-learning-finance.html">دليل تمويل الدراسة للبالغين</a>.</li></ul><p><strong>مهم:</strong> إن غيّرت الدراسة أو أوقفتها فراجع شروط الاسترداد والتمويل قبل أي قرار (<a href="/articles/student-finance.html">DUO</a>).</p>'
'<h2 id="paths">الانتقال بين المسارات</h2><ol><li><strong>MBO-4 إلى HBO:</strong> مباشر بشهادة MBO مستوى 4.</li><li><strong>HBO propedeuse إلى WO:</strong> ممكن بعد إتمام السنة الأولى (propedeuse).</li><li><strong>havo إلى HBO</strong> أو <strong>vwo إلى WO/HBO.</strong></li><li><strong>MBO مستوى 3 إلى 4</strong> ثم HBO.</li></ol><p>تحقق من شروط البرنامج المحدد لأن بعضها يطلب مواد أو مهارات معينة.</p>'
'<h2 id="mistakes">أخطاء شائعة</h2><ul><li><strong>الاعتقاد أن HBO وWO متماثلان.</strong> الفرق في الطابع والمدة والشهادة.</li><li><strong>دخول المسار الأعلى دون التأكد من القبول.</strong></li><li><strong>إهمال الرسوم:</strong> الفرق بين MBO وHBO واضح.</li><li><strong>عدم تقييم الشهادة الأجنبية.</strong></li><li><strong>اعتبار قرار الدراسة نهائياً قبل حساب التمويل.</strong></li></ul>'
'<p>بعد اختيار المسار: <a href="/articles/mbo-dutch-language-options.html">اللغة في MBO</a>.</p>'),
faq=[('ما الفرق بين HBO وWO؟','HBO موجه لمهنة وتدريب عملي ومدته 4 سنوات؛ WO أكاديمي وبحثي وبكالوريوسه 3 سنوات.'),
('هل يفتح MBO-4 باب HBO؟','نعم، بحسب الحكومة وNuffic.'),
('كيف أدخل WO؟','بشهادة vwo أو propedeuse من HBO، وأحياناً مع شروط إضافية.'),
('كم collegegeld في 2026/27؟','2,694 يورو للقانوني بدوام كامل؛ ودوام جزئي أو duaal بين 1,604 و2,694.'),
('هل شهادتي الأجنبية تكفي؟','يتوقف على التقييم وقرار المعهد؛ ابدأ بتقييم رسمي.')],
src_note='مدد الدراسة وشروط القبول من Nuffic وRijksoverheid، والرسوم من DUO وRijksoverheid، راجعناها في 4 أكتوبر 2026. أسئلة القبول للشهادة الأجنبية توجيه عام منا وليست قاعدة رسمية.')
NL=dict(title='Mbo, hbo en wo: verschillen, toelating, kosten en overstappen',
crumb='Mbo, hbo en wo',
seo_title='Verschil mbo, hbo en wo: toelating en kosten',
desc='Het verschil tussen mbo, hbo en wo: duur, toelating (havo, vwo of mbo-4), kosten (collegegeld € 2.694 in 2026-2027) en hoe je overstapt tussen de niveaus.',
summary='<ol><li><strong>Mbo:</strong> praktijkgericht beroepsonderwijs. <strong>Hbo:</strong> hogescholen, gericht op een beroep. <strong>Wo:</strong> universiteiten, meer theoretisch en onderzoeksgericht.</li><li>Naar het <strong>hbo</strong> met <strong>havo</strong> of <strong>mbo-4</strong>; naar het <strong>wo</strong> met <strong>vwo</strong> of een hbo-<strong>propedeuse</strong> (soms extra eisen).</li><li>Hbo-bachelor <strong>4 jaar</strong> (240 ECTS), wo-bachelor <strong>3 jaar</strong> (180 ECTS), mbo-4 meestal <strong>3 tot 4 jaar</strong>.</li><li>Wettelijk <strong>collegegeld</strong> in hbo en wo in 2026-2027: <strong>€ 2.694</strong>; mbo-bol 18+ betaalt lesgeld € 1.511.</li><li>Overstappen kan; je diploma en de eisen van de opleiding bepalen wat mogelijk is.</li></ol>',
body=(
'<h2 id="table">De verschillen in het kort</h2>'
+T([['Karakter','Praktijkgericht, opleiding voor een beroep','Praktijkgericht op hoger niveau, beroepsgericht (Nuffic)','Theoretischer en onderzoeksgericht (universiteit)'],['Diploma','Mbo-diploma','Bachelor (bijv. BBA, BSc)','Bachelor (BA/BSc/LLB)'],['Duur','Niveau 4: 3 of 4 jaar','4 jaar (240 ECTS)','3 jaar (180 ECTS)'],['Toelating','Vooropleiding (afhankelijk van niveau)','Havo of mbo-4 (soms extra eisen)','Vwo of hbo-propedeuse (soms extra eisen)'],['Wettelijke kosten 2026-2027','Lesgeld € 1.511 (bol, 18+); cursusgeld bbl','Collegegeld € 2.694 (voltijd)','Collegegeld € 2.694 (voltijd)'],['Daarna','Werk, of hbo vanaf niveau 4','Werk of hbo-master','Wo-master (hbo-master kan ook)']],['','Mbo','Hbo','Wo'])
+'<p>Bronnen voor duur en toelating: Nuffic en Rijksoverheid. Sommige hogescholen bieden intensieve trajecten voor vwo-ers (3 jaar).</p>'
'<h2 id="mbo">Mbo: wanneer?</h2><ul><li>Je wilt snel een concreet beroep (zorg, techniek, horeca, handel...).</li><li>Je hebt geen havo- of vwo-diploma of leert liever door te doen.</li><li>Je wilt kunnen werken tijdens je opleiding via de bbl (<a href="/nl/articles/bol-bbl-comparison.html">bol of bbl</a>).</li></ul><p>Inschrijving: <a href="/nl/articles/mbo-conditions.html">toelating mbo</a>.</p>'
'<h2 id="hbo">Hbo: wanneer?</h2><ul><li>Je wilt een beroep op bachelorniveau met veel praktijk (in het 3e jaar vaak een stage van ongeveer 9 maanden volgens Nuffic).</li><li>Je hebt havo of mbo-4.</li><li>Daarna: werk of een <strong>hbo-master</strong>, meestal 1 jaar (60 ECTS).</li></ul>'
'<h2 id="wo">Wo: wanneer?</h2><ul><li>Je wilt een academische studie en onderzoek.</li><li>Je hebt vwo of een hbo-propedeuse.</li><li>Een master na de wo-bachelor opent onderzoeks- en promotietrajecten.</li></ul>'
'<h2 id="admission">Toelating en buitenlandse diplomas</h2><p>Elke opleiding kan <strong>extra eisen</strong> stellen (vakkenpakket, vaardigheden). Een buitenlands diploma heeft een waardering nodig (<a href="/nl/articles/diploma-evaluation-sbb.html">diplomawaardering</a>) zodat de instelling het Nederlandse equivalent kan bepalen. Vragen om vooraf aan de instelling te stellen: is mijn diploma gelijkwaardig aan havo of vwo? Welke taaleisen gelden (Nederlands of Engels)? Is er een numerus fixus? Dit zijn vragen om te stellen, geen algemene regels; ze verschillen per opleiding.</p>'
'<h2 id="cost">Kosten en financiering</h2>'
+T([['Mbo bol 18+ (lesgeld)','1.511','1.554'],['Mbo bbl (cursusgeld)','314 of 762','323 of 784'],['Hbo/wo voltijd (wettelijk collegegeld)','2.694','—'],['Hbo/wo deeltijd of duaal','Tussen 1.604 en 2.694','—']],['Soort','2026-2027 (€)','2027-2028 (€)'])
+'<ul><li><strong>Wettelijk collegegeld</strong> betalen de meeste studenten: ingeschreven bij een bekostigde opleiding, nog geen diploma op hetzelfde niveau, en Nederlandse of EU/EER-, Zwitserse of Surinaamse nationaliteit, <strong>of een bepaalde Nederlandse verblijfsvergunning</strong> (volgens DUO onder meer type II, III, IV en V, of type I met recht op studiefinanciering). Anders kan <strong>instellingscollegegeld</strong> gelden; dat is nooit lager dan het wettelijke.</li><li>Financiering en lening: <a href="/nl/articles/student-finance.html">gids studiefinanciering</a>. Je kunt voor het collegegeld lenen tot maximaal 5 keer het wettelijk collegegeld.</li><li>Ben je ouder of is je recht op studiefinanciering op? Zie onze <a href="/nl/articles/adult-learning-finance.html">gids over studiefinanciering voor volwassenen</a>.</li></ul><p><strong>Let op:</strong> stop je of wissel je van studie, kijk dan eerst naar de regels voor terugbetaling en financiering (<a href="/nl/articles/student-finance.html">DUO</a>).</p>'
'<h2 id="paths">Overstappen</h2><ol><li><strong>Mbo-4 naar hbo:</strong> direct met een mbo-4-diploma.</li><li><strong>Hbo-propedeuse naar wo:</strong> mogelijk na het eerste jaar.</li><li><strong>Havo naar hbo</strong> of <strong>vwo naar wo/hbo.</strong></li><li><strong>Mbo-3 naar mbo-4</strong> en dan hbo.</li></ol><p>Controleer de eisen van de specifieke opleiding; sommige vragen bepaalde vakken of vaardigheden.</p>'
'<h2 id="mistakes">Veelgemaakte fouten</h2><ul><li><strong>Denken dat hbo en wo hetzelfde zijn.</strong> Ze verschillen in karakter, duur en diploma.</li><li><strong>Je aanmelden zonder toelating te checken.</strong></li><li><strong>De kosten negeren.</strong></li><li><strong>Je buitenlandse diploma niet laten waarderen.</strong></li><li><strong>Stoppen zonder naar financiering te kijken.</strong></li></ul>'
'<p>Na je keuze: <a href="/nl/articles/mbo-dutch-language-options.html">taal in het mbo</a>.</p>'),
faq=[('Wat is het verschil tussen hbo en wo?','Hbo is beroepsgericht met veel praktijk en duurt 4 jaar; wo is academisch en onderzoeksgericht, bachelor 3 jaar.'),
('Geeft mbo-4 toegang tot het hbo?','Ja, volgens de overheid en Nuffic.'),
('Hoe kom ik op het wo?','Met vwo of een hbo-propedeuse, soms met extra eisen.'),
('Hoeveel is het collegegeld in 2026-2027?','€ 2.694 wettelijk voltijd; deeltijd of duaal tussen € 1.604 en € 2.694.'),
('Is mijn buitenlandse diploma voldoende?','Dat hangt af van de waardering en de instelling; begin met een officiele waardering.')],
src_note='Duur en toelating komen van Nuffic en Rijksoverheid, kosten van DUO en Rijksoverheid, gecontroleerd op 4 oktober 2026. De vragen over buitenlandse diplomas zijn ons algemene advies, geen officiele regel.')
