from a_student_finance import T
SLUG='mbo-conditions'
SRC=[('Rijksoverheid · Uit welke mbo-opleidingen kan ik kiezen?','https://www.rijksoverheid.nl/vraag-en-antwoord/middelbaar-beroepsonderwijs/uit-welke-mbo-opleidingen-kan-ik-kiezen'),
('Rijksoverheid · Wat zijn de toelatingseisen voor het mbo?','https://www.rijksoverheid.nl/vraag-en-antwoord/middelbaar-beroepsonderwijs/wat-zijn-de-toelatingseisen-voor-het-mbo'),
('Rijksoverheid · Hoogte lesgeld en cursusgeld mbo','https://www.rijksoverheid.nl/vraag-en-antwoord/middelbaar-beroepsonderwijs/hoogte-lesgeld-en-cursusgeld-mbo'),
('Rijksoverheid · Studiefinanciering mbo','https://www.rijksoverheid.nl/themas/onderwijs/studiefinanciering/studiefinanciering-mbo'),
('Rijksoverheid · Met welke diplomas kan ik naar hbo of universiteit?','https://www.rijksoverheid.nl/vraag-en-antwoord/hoger-onderwijs/met-welke-diploma-s-kan-ik-naar-de-universiteit-of-hogeschool')]
AR=dict(title='شروط الدراسة في MBO: المستويات الأربعة، الشهادات المطلوبة، التكاليف، وماذا يعني ذلك لك',
seo_title='شروط القبول في MBO toelatingseisen',
crumb='شروط MBO',
desc='شروط القبول في MBO: ما تحتاجه لكل مستوى من 1 إلى 4، الشهادة الأجنبية، وlesgeld بقيمة 1,511 يورو في 2026/27 مع cursusgeld لـBBL.',
summary='<ol><li>MBO له <strong>4 مستويات</strong>، وشهادتك السابقة هي التي تحدد المستوى الذي تقبله فيه.</li><li>المستوى 1 (entree) لمن لا يستوفي شروط المستويات 2 إلى 4. المستوى 2 يحتاج غالباً شهادة vmbo أو ما يعادلها. المستوى 3 و4 يحتاجان شهادة vmbo (kader أو theoretisch) أو ما فوقها.</li><li>للمعهد حق <strong>الرفض</strong> مثلاً عند زيادة الطلبات على الأماكن أو لشروط بدنية في بعض التخصصات.</li><li>من هو 18+ في BOL يدفع <strong>lesgeld 1,511 يورو</strong> في 2026/27؛ وفي BBL يدفع <strong>cursusgeld</strong> (314 أو 762 يورو).</li><li>القادم بشهادة أجنبية يحتاج غالباً <strong>تقييماً للشهادة</strong> (<a href="/articles/diploma-evaluation-sbb.html">دليل التقييم</a>).</li></ol>',
body=(
'<h2 id="levels">المستويات الأربعة</h2><p>تقدم معاهد MBO دراسات على 4 مستويات (Rijksoverheid):</p>'
+T([['1','Entreeopleiding','لمن لا يستوفي شروط المستويات 2 و3 و4.'],['2','Basisberoepsopleiding','شهادة lbo أو vbo أو vmbo (basis أو kader أو theoretisch/mavo أو gemengd) أو شهادة entree أو basis، أو إثبات اجتياز أول 3 سنوات من havo/vwo بنجاح.'],['3','Vakopleiding','شهادة lbo أو vbo أو vmbo kader أو theoretisch أو mavo أو gemengd، أو شهادة basisberoep (2) أو شهادة vakopleiding (3)، أو إثبات اجتياز أول 3 سنوات من havo/vwo، أو شهادة/إثبات آخر تعترف به الحكومة.'],['4','Middenkader أو specialist','المتوسط (3 أو 4 سنوات): الشروط نفسها للمستوى 3. التخصصي (سنة واحدة): بعد شهادة المستوى 3 في المهنة نفسها.']],['المستوى','الاسم','الشرط (بحسب Rijksoverheid)'])
+'<p>مستوى 4 يؤهل للعمل المستقل الكامل (مثل مدير فرع) ويفتح <strong>الباب إلى HBO</strong> (<a href="/articles/mbo-hbo-wo-comparison.html">المقارنة بين MBO وHBO وWO</a>).</p>'
'<h2 id="entry">شروط القبول والتسجيل</h2><ul><li>تستوفي <strong>شروط الشهادة السابقة</strong> للدراسة التي تريدها.</li><li>تقدّم نسخة من شهادتك للمعهد عند التسجيل.</li><li>للمعهد حق <strong>رفض</strong> الطلب في حالات منها: أن الطلبات أكثر من المقاعد، أو لشروط بدنية (كالدراسات الرياضية).</li></ul>'
'<h2 id="foreign">القادم بشهادة أجنبية أو من دون شهادة</h2><p>الجداول أعلاه تذكر الشهادات الهولندية. للشهادة الأجنبية <strong>لا يوجد قياس تلقائي</strong>: يُقرر المعهد مستواك مقابل المعادل الهولندي. ولذلك:</p><ol><li>اطلب تقييماً رسمياً لشهادتك (<a href="/articles/diploma-evaluation-sbb.html">دليل التقييم</a>) قبل التسجيل.</li><li>اتصل بالمعهد وقدّم الشهادة المترجمة والمصدّقة واسأل عن المستوى الذي يعتمدونه لك.</li><li>اسأل عن <strong>متطلبات اللغة الهولندية</strong> واختبارات التحديد: تختلف بين المعاهد، ولا نستطيع تعميم رقم (<a href="/articles/mbo-dutch-language-options.html">خيارات اللغة في MBO</a>).</li><li>إن لم تكن لديك شهادة تعادل vmbo، فالمسار المتاح عادة هو <strong>المستوى 1 (Entree)</strong> ثم الانتقال إلى المستوى 2 فما فوق. اسأل المعهد عن إمكانية القبول المباشر في مستوى أعلى بعد الاختبار.</li></ol><p>البندان 3 و4 توجيه عام منا لا قاعدة حكومية: القرار بيد المعهد.</p>'
'<h2 id="costs">التكاليف: lesgeld وcursusgeld</h2><p>الدراسة الكاملة BOL لمن هو <strong>18 سنة فأكثر</strong> تدفع lesgeld. أما BBL والدوام الجزئي لمن هو 18+ فيدفعون cursusgeld.</p>'
+T([['BOL بدوام كامل (lesgeld، 18+)','1,511','1,554'],['BBL مستوى 1 و2 (cursusgeld)','314','323'],['BBL مستوى 3 و4 (cursusgeld)','762','784']],['النوع','2026/2027 (يورو)','2027/2028 (يورو)'])
+'<ul><li>رسوم الكتب والمواد (schoolkosten) تُضاف خارج هذه الأرقام وتختلف بين المعاهد.</li><li>يمكن دفع lesgeld دفعة واحدة أو أقساطاً حسب شهر التسجيل (DUO).</li><li>للقاصر دون 18 قواعد مختلفة؛ اسأل المعهد وDUO.</li></ul>'
'<h2 id="finance">التمويل</h2><p>طلاب BOL لهم حق في <strong>studiefinanciering</strong>: basisbeurs، وaanvullende beurs، وstudentenreisproduct، وقرض اختياري. في المستوى 1 و2 المنحة والمواصلات <strong>هبة</strong>. وفي المستوى 3 و4 تكون <strong>prestatiebeurs</strong>: تتحول إلى هبة إذا حصلت على الدبلوم خلال 10 سنوات، وإلا تعيدها. أول 12 شهراً من aanvullende beurs هبة دائماً. تفاصيل الأرقام في <a href="/articles/student-finance.html">دليل تمويل الدراسة</a>. وإن كنت أكبر سناً أو لا تستوفي شروط هذا التمويل فراجع <a href="/articles/adult-learning-finance.html">دليل تمويل الدراسة للبالغين</a>.</p><p>طالب BBL عادةً <strong>يعمل ويتقاضى راتباً</strong> فلا يندرج تحت هذا التمويل (<a href="/articles/bol-bbl-comparison.html">BOL أم BBL</a>).</p>'
'<h2 id="plan">كيف أختار المستوى؟</h2><ol><li>حدد المهنة التي تريدها، ثم انظر المستوى الذي تتطلبه فعلاً.</li><li>قدّر شهادتك مقابل الجدول.</li><li>قارن BOL وBBL.</li><li>احسب التكلفة الكلية: lesgeld أو cursusgeld + الكتب + السفر.</li><li>اسأل المعهد عن يوم مفتوح وlevel check.</li></ol>'
'<h2 id="mistakes">أخطاء شائعة</h2><ul><li><strong>افتراض أن شهادتك الأجنبية تُقبل تلقائياً بمستوى معين.</strong></li><li><strong>تقديم الطلب بعد امتلاء الأماكن.</strong> للمعهد حق الرفض.</li><li><strong>نسيان cursusgeld في BBL.</strong></li><li><strong>خلط BOL بـBBL.</strong></li><li><strong>اختيار مستوى أدنى من اللازم</strong> فيعيقك عن HBO لاحقاً.</li></ul>'),
faq=[('ما شروط القبول في MBO مستوى 3؟','شهادة vmbo kader أو theoretisch أو ما يعادلها، أو شهادة MBO مستوى 2 أو 3، أو إثبات اجتياز 3 سنوات من havo/vwo، وفق Rijksoverheid.'),
('كم lesgeld في 2026/27؟','1,511 يورو لـBOL بدوام كامل لمن هو 18+.'),
('كم cursusgeld في BBL؟','314 يورو للمستوى 1 و2، و762 يورو للمستوى 3 و4 في 2026/27.'),
('هل يستطيع المعهد رفضي؟','نعم، مثلاً إن زادت الطلبات على الأماكن أو لشروط بدنية.'),
('هل أحتاج تقييم شهادتي؟','غالباً نعم، فاسأل المعهد وابدأ بتقييم رسمي.')],
src_note='شروط المستويات والتكاليف والتمويل من Rijksoverheid، راجعناها في 4 أكتوبر 2026. وضع الشهادة الأجنبية واللغة نصيحة عامة منا ويقررها كل معهد.')
NL=dict(title='Toelatingseisen mbo: de 4 niveaus, vooropleiding, kosten en wat het voor jou betekent',
seo_title='Toelatingseisen mbo: de 4 niveaus en kosten',
crumb='Toelating mbo',
desc='Toelatingseisen mbo: welke vooropleiding je per niveau 1 tot 4 nodig hebt, wat met een buitenlands diploma, en lesgeld van € 1.511 in 2026-2027.',
summary='<ol><li>Het mbo heeft <strong>4 niveaus</strong>; je vooropleiding bepaalt voor welk niveau je in aanmerking komt.</li><li>Niveau 1 (entree) is voor wie niet voldoet aan de eisen voor niveau 2 tot en met 4. Niveau 2 vraagt meestal een vmbo-diploma of gelijkwaardig; niveau 3 en 4 een vmbo kader of theoretisch of hoger.</li><li>Een school mag <strong>weigeren</strong>, bijvoorbeeld bij meer aanmeldingen dan plekken of bij lichamelijke eisen.</li><li>Ben je 18+ in de bol, dan betaal je <strong>lesgeld € 1.511</strong> in 2026-2027; in de bbl betaal je <strong>cursusgeld</strong> (€ 314 of € 762).</li><li>Met een buitenlands diploma heb je meestal een <strong>diplomawaardering</strong> nodig (<a href="/nl/articles/diploma-evaluation-sbb.html">gids</a>).</li></ol>',
body=(
'<h2 id="levels">De 4 niveaus</h2><p>Mbo-scholen bieden opleidingen aan op 4 niveaus (Rijksoverheid):</p>'
+T([['1','Entreeopleiding','Voor wie niet voldoet aan de toelatingseisen van niveau 2, 3 of 4.'],['2','Basisberoepsopleiding','Diploma lbo, vbo, vmbo (basis, kader, theoretisch/mavo of gemengd), diploma entree- of basisberoepsopleiding, of bewijs dat je de eerste 3 leerjaren havo/vwo goed hebt doorlopen.'],['3','Vakopleiding','Diploma lbo, vbo, vmbo kader of theoretisch, mavo of gemengd; of diploma basisberoep (2) of vakopleiding (3); of bewijs eerste 3 leerjaren havo/vwo; of een ander erkend diploma of bewijsstuk.'],['4','Middenkader of specialist','Middenkader (3 of 4 jaar): dezelfde eisen als niveau 3. Specialist (1 jaar): na mbo-3 in hetzelfde beroep.']],['Niveau','Naam','Eis (volgens Rijksoverheid)'])
+'<p>Niveau 4 leidt op tot volledig zelfstandig werk (bijvoorbeeld filiaalbeheerder) en geeft toegang tot het <strong>hbo</strong> (<a href="/nl/articles/mbo-hbo-wo-comparison.html">mbo, hbo en wo vergeleken</a>).</p>'
'<h2 id="entry">Toelating en inschrijving</h2><ul><li>Je voldoet aan de <strong>vooropleidingseisen</strong> van de opleiding.</li><li>De school wil een kopie van je diploma bij inschrijving.</li><li>De school mag <strong>weigeren</strong>, bijvoorbeeld bij meer aanmeldingen dan plekken of bij lichamelijke eisen (sportopleidingen).</li></ul>'
'<h2 id="foreign">Met een buitenlands diploma of zonder diploma</h2><p>De tabellen noemen Nederlandse diplomas. Voor een buitenlands diploma is er <strong>geen automatische omrekening</strong>: de school bepaalt je niveau tegenover het Nederlandse equivalent. Dus:</p><ol><li>Laat je diploma officieel waarderen (<a href="/nl/articles/diploma-evaluation-sbb.html">diplomawaardering</a>) vóór je je inschrijft.</li><li>Neem contact op met de school met je vertaalde en gelegaliseerde diploma en vraag welk niveau zij toekennen.</li><li>Vraag naar <strong>eisen voor Nederlands</strong> en plaatsingstoetsen: die verschillen per school en we noemen daarom geen algemeen cijfer (<a href="/nl/articles/mbo-dutch-language-options.html">taalopties in het mbo</a>).</li><li>Heb je geen diploma dat gelijkwaardig is aan vmbo, dan is meestal <strong>niveau 1 (entree)</strong> de weg, daarna door naar niveau 2 of hoger. Vraag de school of toelating tot een hoger niveau na een toets kan.</li></ol><p>Punt 3 en 4 zijn ons algemene advies, geen overheidsregel: de school beslist.</p>'
'<h2 id="costs">Kosten: lesgeld en cursusgeld</h2><p>Voltijd bol vanaf <strong>18 jaar</strong>: lesgeld. Bbl of deeltijd vanaf 18: cursusgeld.</p>'
+T([['Bol voltijd (lesgeld, 18+)','1.511','1.554'],['Bbl niveau 1 en 2 (cursusgeld)','314','323'],['Bbl niveau 3 en 4 (cursusgeld)','762','784']],['Soort','2026-2027 (€)','2027-2028 (€)'])
+'<ul><li>Kosten voor boeken en materiaal (schoolkosten) komen daar bovenop en verschillen per school.</li><li>Lesgeld kun je in een keer of in termijnen betalen, afhankelijk van je inschrijfmaand (DUO).</li><li>Voor minderjarigen gelden andere regels; vraag het de school en DUO.</li></ul>'
'<h2 id="finance">Studiefinanciering</h2><p>Bol-studenten hebben recht op <strong>studiefinanciering</strong>: basisbeurs, aanvullende beurs, studentenreisproduct en een optionele lening. Op niveau 1 en 2 zijn beurs en reisproduct een <strong>gift</strong>. Op niveau 3 en 4 is het een <strong>prestatiebeurs</strong>: een gift als je binnen 10 jaar je diploma haalt, anders terugbetalen. De eerste 12 maanden aanvullende beurs zijn altijd een gift. Bedragen: <a href="/nl/articles/student-finance.html">gids studiefinanciering</a>. Ben je ouder of kom je hiervoor niet in aanmerking, zie dan <a href="/nl/articles/adult-learning-finance.html">studiefinanciering voor volwassenen</a>.</p><p>Een bbl-student werkt meestal en <strong>krijgt loon</strong> (<a href="/nl/articles/bol-bbl-comparison.html">bol of bbl</a>).</p>'
'<h2 id="plan">Zo kies je een niveau</h2><ol><li>Bepaal welk beroep je wilt en welk niveau dat echt vraagt.</li><li>Leg je diploma naast de tabel.</li><li>Vergelijk bol en bbl.</li><li>Reken de totale kosten: lesgeld of cursusgeld + boeken + reizen.</li><li>Ga naar een open dag en vraag naar een intake of niveauonderzoek.</li></ol>'
'<h2 id="mistakes">Veelgemaakte fouten</h2><ul><li><strong>Denken dat een buitenlands diploma vanzelf een niveau oplevert.</strong></li><li><strong>Te laat aanmelden.</strong> De school mag weigeren.</li><li><strong>Cursusgeld in de bbl vergeten.</strong></li><li><strong>Bol en bbl verwarren.</strong></li><li><strong>Een te laag niveau kiezen</strong> terwijl je later naar het hbo wilt.</li></ul>'),
faq=[('Welke eisen gelden voor mbo-niveau 3?','Diploma vmbo kader of theoretisch of gelijkwaardig, of mbo-2/3, of bewijs eerste 3 leerjaren havo/vwo, volgens Rijksoverheid.'),
('Hoeveel is het lesgeld in 2026-2027?','€ 1.511 voor bol voltijd vanaf 18 jaar.'),
('Hoeveel is cursusgeld in de bbl?','€ 314 voor niveau 1 en 2 en € 762 voor niveau 3 en 4 in 2026-2027.'),
('Mag een school mij weigeren?','Ja, bijvoorbeeld bij meer aanmeldingen dan plekken of lichamelijke eisen.'),
('Heb ik diplomawaardering nodig?','Meestal wel; vraag het de school en begin met een officiele waardering.')],
src_note='Niveaus, kosten en financiering komen van Rijksoverheid, gecontroleerd op 4 oktober 2026. Het advies over buitenlandse diplomas en taal is ons algemene advies; elke school beslist zelf.')
