from a_student_finance import T
SLUG='asylum-family-reunification'
SRC=[('IND · Gezinshereniging asiel (nareis)','https://ind.nl/nl/verblijfsvergunningen/asiel/gezinshereniging-asiel'),
('IND · Wanneer begint de IND met mijn nareisaanvraag?','https://ind.nl/nl/asiel-en-nareis-het-migratiepact-en-andere-ontwikkelingen/wanneer-begint-de-ind-met-mijn-nareisaanvraag'),
('IND · Nieuwe wetten en regels asiel en nareis','https://ind.nl/nl/nieuwe-wetten-en-regels-asiel-en-nareis'),
('Rijksoverheid · Mogen familieleden van asielzoekers naar Nederland komen?','https://www.rijksoverheid.nl/onderwerpen/asielbeleid/vraag-en-antwoord/mogen-familieleden-van-asielzoekers-naar-nederland-komen'),
('Eerste Kamer · Wet invoering tweestatusstelsel (36 703)','https://www.eerstekamer.nl/wetsvoorstel/36703_wet_invoering'),
('Eerste Kamer · Senaat verwerpt strafbaarstelling (21-4-2026)','https://www.eerstekamer.nl/nieuws/20260421/senaat_verwerpt_strafbaarstelling')]

AR=dict(title='لم شمل عائلة اللاجئ (Nareis) في هولندا 2026: مهلة 3 أشهر، من يحق له، نظام الحالتين منذ 12 يونيو، والطلبات المجمّدة عند IND',
crumb='لم شمل اللاجئين',
seo_title='لم شمل اللاجئين nareis 2026',
desc='لم شمل اللاجئين عبر nareis في 2026: قدّم خلال 3 أشهر من إقامة اللجوء. من يحق له المجيء، نظام الحالتين منذ 12 يونيو، والطلبات التي جمّدها IND.',
summary='<ol><li><strong>قدّم خلال 3 أشهر</strong> من حصولك على إقامة اللجوء: بعدها تصبح الشروط أصعب (لم شمل عادي بشرط دخل).</li><li><strong>العائلة:</strong> الزوج أو الشريك المسجل، والأطفال تحت 18، ووالدا وإخوة القاصر غير المصحوب. يجب أن تكون العائلة قائمة <strong>قبل وصولك</strong> لهولندا.</li><li><strong>منذ 12 يونيو 2026</strong> يسري نظام الحالتين: حاملو <strong>الحماية الثانوية</strong> ينتظرون سنتين ويحتاجون دخلاً بمستوى الحد الأدنى وسكناً مناسباً؛ <strong>اللاجئون المعترف بهم</strong> لا.</li><li><strong>IND جمّد مؤقتاً</strong> البت في طلبات الحماية الثانوية وبعض طلبات اللاجئين، بانتظار حكم قضائي حول الأثر الرجعي.</li><li><strong>مدة القرار</strong> 9 أشهر قابلة للتمديد.</li></ol>',
body=(
'<h2 id="who">من يحق له المجيء؟</h2>'
+T([['الزوج/الزوجة أو الشريك المسجل','نعم، إن كانت العلاقة قائمة قبل وصولك إلى هولندا'],
    ['الأطفال تحت 18','نعم'],
    ['والدا القاصر غير المصحوب وإخوته القاصرون','نعم، إن كان مقدم الطلب دون 18 عند طلب اللجوء'],
    ['أقارب آخرون (إخوة بالغون، أبناء بالغون…)','ليس عبر nareis عادة؛ فقط في حالات استثنائية (المادة 8 من الاتفاقية الأوروبية)']],
   ['فرد العائلة','nareis'])
+'<h2 id="deadline">مهلة الأشهر الثلاثة</h2><ul><li>قدّم طلب nareis <strong>خلال 3 أشهر</strong> من قرار منحك إقامة اللجوء (حسب Rijksoverheid).</li><li>بعد الأشهر الثلاثة يبقى أمامك طريق «لم الشمل العادي»، وفيه شروط مثل الدخل الكافي.</li><li>إن لم تكن وثائق القرابة متاحة، يمكن أن يعرض IND <strong>فحص DNA</strong> أو <strong>مقابلة تعريفية</strong>.</li></ul>'
'<h2 id="two-status">نظام الحالتين منذ 12 يونيو 2026</h2><p>صادق مجلس الشيوخ في 21 أبريل 2026 (41 مقابل 34) على قانون نظام الحالتين، وبدأ في 12 يونيو 2026. حسب التحليل القانوني المنشور عن القانون:</p>'
+T([['لاجئ معترف به (اتفاقية اللاجئين)','بلا فترة انتظار، وبلا شرط دخل أو سكن إضافي في nareis.'],
    ['حماية ثانوية (subsidiair)','انتظار <strong>سنتين</strong>، و<strong>دخل مستقل بمستوى الحد الأدنى للأجر</strong>، و<strong>سكن مناسب</strong>.'],
    ['من يُشمل','العائلة الأساسية: الزوج والأطفال القاصرون؛ الوالدان والإخوة القاصرون فقط للقاصر غير المصحوب.']],
   ['نوع الحماية','قواعد nareis'])
+'<p>في اليوم نفسه <strong>رفض</strong> مجلس الشيوخ «قانون إجراءات اللجوء الطارئة» (31 مقابل 44) وتجريم الإقامة غير القانونية (37 مقابل 38). لذلك انتبه للأخبار المتداولة: ليس كل ما أُعلن أصبح قانوناً.</p>'
'<h2 id="frozen">الطلبات المجمّدة مؤقتاً عند IND</h2><p>حسب IND، لا يبت حالياً في:</p><ul><li>كل طلبات nareis لحاملي <strong>الحماية الثانوية</strong>؛</li><li>طلبات اللاجئين الذين لا ينطبق على أفراد عائلتهم المعيار الجديد،</li></ul><p>لأن IND ينتظر حكماً قضائياً حول قانونية تطبيق الشروط الجديدة بأثر رجعي، وإن لم يتضح الأمر بنهاية 2026 يحدد IND الخطوة التالية.</p><p><strong>ما يستمر طبيعياً:</strong> لاجئ معترف به مع زوج وأطفال قاصرين بيولوجيين، والقاصر غير المصحوب سابقاً بحماية ثانوية، وحالات المادة 8. وذكر IND أن معالجة بعض الحالات السريعة (طلبات أغسطس–سبتمبر 2025) والمعقدة (يوليو 2024) تبدأ في سبتمبر 2026.</p>'
'<h2 id="process">الإجراءات خطوة بخطوة</h2><ol><li><strong>قدّم الطلب خلال 3 أشهر</strong> من إقامة اللجوء (غالباً بمساعدة VluchtelingenWerk).</li><li>أرفق إثبات القرابة: عقد الزواج، شهادات الميلاد، صور ووثائق تثبت أن العائلة كانت قائمة قبل وصولك.</li><li>عند غياب الوثائق: فحص DNA أو مقابلة.</li><li>قرار IND: خلال <strong>9 أشهر</strong>، قابلة للتمديد.</li><li>عند الموافقة: يحصل أفراد العائلة على تأشيرة MVV من السفارة الهولندية، ثم يسافرون.</li><li>بعد الوصول: التسجيل في البلدية و<a href="/articles/health-insurance-newcomers.html">التأمين الصحي</a> والبدلات (<a href="/articles/bsn-municipality-registration.html">التسجيل في البلدية</a>).</li></ol>'
'<h2 id="after3">فاتتك الأشهر الثلاثة؟</h2><p>يبقى طريق <strong>لم الشمل العادي</strong> (<a href="/articles/family-reunification-mvv-ind.html">دليل لم الشمل وMVV</a>): فيه شروط مثل دخل كافٍ ومستقر، ورسوم، وامتحان الاندماج في الخارج للزوج في كثير من الحالات. لم نتمكن من تأكيد كل الاستثناءات من صفحة رسمية، فاستشر VluchtelingenWerk.</p>'
'<h2 id="money">التكاليف والمساعدة</h2><ul><li>رسوم طلبات لم الشمل لدى IND بين 85 و254 يورو حسب النوع؛ لم نؤكد ما إذا كان طلب nareis خلال الأشهر الثلاثة معفى، فاسأل عند التقديم.</li><li>تكاليف السفر والتذاكر غالباً على العائلة.</li><li>مساعدة مجانية: VluchtelingenWerk Nederland (منظمة غير حكومية) وJuridisch Loket. وإن احتجت محامياً فراجع <a href="/articles/legal-aid-lawyer-toevoeging.html">دليل المحامي المدعوم (toevoeging)</a>.</li></ul>'
'<h2 id="mistakes">أخطاء شائعة</h2><ol><li>تفويت مهلة الأشهر الثلاثة بانتظار الوثائق: قدّم الطلب ثم أكمل الوثائق.</li><li>تقديم معلومات مختلفة عما قلته في مقابلة اللجوء عن عائلتك.</li><li>الاعتماد على أخبار عن قوانين رُفضت أو لم تُطبق بعد.</li><li>عدم تجديد الإقامة في وقتها أثناء الانتظار (راجع <a href="/articles/eu-permanent-residence-netherlands.html">دليل الإقامة الدائمة</a>).</li></ol>'),
faq=[('كم لدي من الوقت لطلب لم الشمل؟','3 أشهر من منحك إقامة اللجوء. بعدها يصبح لم الشمل عادياً بشروط دخل.'),
('من يمكنه المجيء؟','الزوج أو الشريك المسجل، والأطفال تحت 18، ووالدا وإخوة القاصر غير المصحوب. يجب أن تكون العائلة قائمة قبل وصولك.'),
('ما الفرق بين اللاجئ والحماية الثانوية في لم الشمل؟','منذ 12 يونيو 2026: الحماية الثانوية تنتظر سنتين وتحتاج دخلاً بمستوى الحد الأدنى وسكناً مناسباً؛ اللاجئ المعترف به لا.'),
('لماذا لم يبت IND في طلبي؟','IND جمّد مؤقتاً طلبات الحماية الثانوية وبعض طلبات اللاجئين بانتظار حكم قضائي حول الأثر الرجعي للقواعد الجديدة.'),
('كم يستغرق القرار؟','9 أشهر قابلة للتمديد.'),
('هل أُقر قانون إجراءات اللجوء الطارئة؟','لا، رفضه مجلس الشيوخ في 21 أبريل 2026.')],
src_note='راجعنا IND وRijksoverheid ومجلس الشيوخ في 5 أكتوبر 2026. تفاصيل شروط الحماية الثانوية من تحليل قانوني منشور (NJB) يتوافق مع القانون؛ الوضع يتغير بسرعة، فراجع صفحة IND قبل أي خطوة واستشر VluchtelingenWerk.')

NL=dict(title='Nareis (gezinshereniging asiel) in 2026: termijn van 3 maanden, wie mag komen, het tweestatusstelsel sinds 12 juni en aangehouden aanvragen bij de IND',
crumb='Nareis',
seo_title='Nareis 2026: gezinshereniging asiel',
desc='Nareis in 2026: vraag binnen 3 maanden na je asielvergunning aan. Wie mag komen, het tweestatusstelsel sinds 12 juni en welke aanvragen de IND aanhoudt.',
summary='<ol><li><strong>Vraag binnen 3 maanden</strong> na je asielvergunning aan; daarna geldt reguliere gezinshereniging met inkomenseis.</li><li><strong>Gezin:</strong> echtgenoot of geregistreerd partner, kinderen onder 18, ouders en minderjarige broers/zussen van een alleenstaande minderjarige; het gezin moet al vóór aankomst bestaan.</li><li><strong>Sinds 12 juni 2026</strong> geldt het tweestatusstelsel: <strong>subsidiair beschermden</strong> wachten 2 jaar en hebben inkomen op minimumloonniveau en passende huisvesting nodig; <strong>vluchtelingen</strong> niet.</li><li><strong>De IND houdt aanvragen</strong> van subsidiair beschermden en sommige vluchtelingen tijdelijk aan.</li><li><strong>Beslistermijn</strong> 9 maanden, verlengbaar.</li></ol>',
body=(
'<h2 id="who">Wie mag komen?</h2>'
+T([['Echtgenoot of geregistreerd partner','Ja, als de relatie al bestond vóór je aankomst'],['Kinderen onder 18','Ja'],['Ouders en minderjarige broers/zussen van een alleenstaande minderjarige','Ja, als de referent bij de asielaanvraag jonger dan 18 was'],['Andere familieleden','Meestal niet via nareis; alleen uitzonderlijk (artikel 8 EVRM)']],['Gezinslid','Nareis'])
+'<h2 id="deadline">Termijn van 3 maanden</h2><ul><li>Aanvragen <strong>binnen 3 maanden</strong> na verlening van de asielvergunning.</li><li>Daarna blijft reguliere gezinshereniging over, met onder meer een inkomenseis.</li><li>Ontbreken documenten, dan kan de IND <strong>DNA-onderzoek</strong> of een <strong>identificerend gehoor</strong> aanbieden.</li></ul>'
'<h2 id="two-status">Tweestatusstelsel sinds 12 juni 2026</h2><p>De Eerste Kamer stemde op 21 april 2026 in (41–34); in werking per 12 juni 2026. Volgens de juridische analyse van de wet:</p>'
+T([['Vluchteling (Vluchtelingenverdrag)','Geen wachttijd, geen extra inkomens- of huisvestingseis voor nareis.'],['Subsidiair beschermde','<strong>2 jaar</strong> wachttijd, <strong>zelfstandig inkomen op minimumloonniveau</strong> en <strong>passende huisvesting</strong>.'],['Wie','Kerngezin; ouders en minderjarige broers/zussen alleen bij een alleenstaande minderjarige.']],['Status','Nareisregels'])
+'<p>Dezelfde dag <strong>verwierp</strong> de Eerste Kamer de Asielnoodmaatregelenwet (31–44) en de strafbaarstelling van illegaliteit (37–38).</p>'
'<h2 id="frozen">Aangehouden aanvragen</h2><p>Volgens de IND wordt tijdelijk niet beslist over:</p><ul><li>alle nareisaanvragen van <strong>subsidiair beschermden</strong>;</li><li>aanvragen van vluchtelingen van wie de gezinsleden niet onder de nieuwe criteria vallen,</li></ul><p>omdat wordt getoetst of de nieuwe voorwaarden met terugwerkende kracht rechtmatig zijn; is er eind 2026 geen duidelijkheid, dan bepaalt de IND het vervolg. <strong>Wel in behandeling:</strong> vluchteling met echtgenoot en minderjarige biologische kinderen, voormalig amv met subsidiaire bescherming en artikel-8-zaken. Snelle zaken (aanvragen aug–sep 2025) en complexe zaken (juli 2024) zouden in september 2026 starten.</p>'
'<h2 id="process">Procedure</h2><ol><li>Aanvraag <strong>binnen 3 maanden</strong> (vaak met hulp van VluchtelingenWerk).</li><li>Bewijs van gezinsband: huwelijksakte, geboorteakten, foto’s en documenten van vóór je aankomst.</li><li>Zonder documenten: DNA-onderzoek of gehoor.</li><li>Besluit binnen <strong>9 maanden</strong>, verlengbaar.</li><li>Na inwilliging: mvv bij de Nederlandse ambassade, daarna reizen.</li><li>Na aankomst: inschrijven bij de gemeente, <a href="/nl/articles/health-insurance-newcomers.html">zorgverzekering</a> en toeslagen (<a href="/nl/articles/bsn-municipality-registration.html">inschrijven</a>).</li></ol>'
'<h2 id="after3">Termijn gemist?</h2><p>Dan reguliere gezinshereniging (<a href="/nl/articles/family-reunification-mvv-ind.html">gezinshereniging en mvv</a>) met onder meer een inkomenseis, leges en vaak het basisexamen inburgering buitenland. Vraag VluchtelingenWerk om advies.</p>'
'<h2 id="money">Kosten en hulp</h2><ul><li>IND-leges voor gezinshereniging € 85–€ 254; of nareis binnen 3 maanden is vrijgesteld konden we niet bevestigen.</li><li>Reiskosten meestal voor het gezin.</li><li>Gratis hulp: VluchtelingenWerk Nederland (ngo) en Juridisch Loket. Heb je een advocaat nodig, zie dan onze <a href="/nl/articles/legal-aid-lawyer-toevoeging.html">gids over een advocaat met toevoeging</a>.</li></ul>'
'<h2 id="mistakes">Veelgemaakte fouten</h2><ol><li>De 3 maanden laten verlopen in afwachting van documenten.</li><li>Andere gezinsinformatie geven dan in je asielgehoor.</li><li>Vertrouwen op berichten over wetten die zijn verworpen.</li><li>Je vergunning niet op tijd verlengen tijdens het wachten (zie <a href="/nl/articles/eu-permanent-residence-netherlands.html">permanent verblijf</a>).</li></ol>'),
faq=[('Hoeveel tijd heb ik voor nareis?','3 maanden na verlening van je asielvergunning.'),
('Wie mag komen?','Echtgenoot/partner, kinderen onder 18, en ouders en minderjarige broers/zussen van een alleenstaande minderjarige; het gezin moet al vóór aankomst bestaan.'),
('Wat is het verschil tussen vluchteling en subsidiair beschermde?','Sinds 12 juni 2026: subsidiair beschermden wachten 2 jaar en hebben inkomen en huisvesting nodig; vluchtelingen niet.'),
('Waarom beslist de IND niet?','De IND houdt aanvragen van subsidiair beschermden en sommige vluchtelingen aan tot de rechter oordeelt over de terugwerkende kracht.'),
('Hoe lang duurt het?','9 maanden, verlengbaar.'),
('Is de Asielnoodmaatregelenwet aangenomen?','Nee, de Eerste Kamer verwierp die op 21 april 2026.')],
src_note='Gecontroleerd bij IND, Rijksoverheid en Eerste Kamer op 5 oktober 2026. Details over subsidiaire bescherming uit de gepubliceerde juridische analyse (NJB). De situatie verandert snel; check de IND-pagina en vraag VluchtelingenWerk om advies.')
