from a_student_finance import T
SLUG='dutch-payslip-explained'
SRC=[('Rijksoverheid · Wat staat er op mijn loonstrook?','https://www.rijksoverheid.nl/vraag-en-antwoord/arbeidsovereenkomst-en-cao/wat-staat-er-op-mijn-loonstrook'),
('Rijksoverheid · Wat is een heffingskorting en welke heffingskortingen zijn er?','https://www.rijksoverheid.nl/vraag-en-antwoord/inkomstenbelasting/wat-is-een-heffingskorting-en-welke-heffingskortingen-zijn-er'),
('Belastingdienst · Loonheffingskorting met AOW en pensioen of meerdere werkgevers','https://www.belastingdienst.nl/wps/wcm/connect/nl/werk-en-inkomen/content/loonheffingskorting-meerdere-inkomens'),
('Belastingdienst · Loonheffingskorting toepassen of stoppen','https://www.belastingdienst.nl/wps/wcm/connect/nl/werk-en-inkomen/content/loonheffingskorting-toepassen-of-stoppen'),
('Belastingdienst · Algemene heffingskorting','https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/heffingskortingen_boxen_tarieven/heffingskortingen/algemene_heffingskorting/algemene_heffingskorting'),
('Belastingdienst · Arbeidskorting','https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/heffingskortingen_boxen_tarieven/heffingskortingen/arbeidskorting/arbeidskorting'),
('UWV · Arbeidskorting over uitkering stopt per 1 januari 2027','https://www.uwv.nl/nl/magazines-nieuwsbrieven/nieuwsbrief-werkgevers/arbeidskorting-over-uitkering-stopt-per-1-januari-2027'),
('Rijksoverheid · Hoe hoog is mijn vakantiegeld?','https://www.rijksoverheid.nl/vraag-en-antwoord/vakantiedagen-en-vakantiegeld/hoe-hoog-is-mijn-vakantiegeld'),
('Rijksoverheid · Bedragen minimumloon 2026','https://www.rijksoverheid.nl/themas/werk/minimumloon/bedragen-minimumloon/bedragen-minimumloon-2026')]

AR=dict(title='قسيمة الراتب في هولندا (loonstrook) 2026 سطراً سطراً: من الإجمالي إلى الصافي، loonheffingskorting، بدل العطلة، وكيف تكتشف الأخطاء',
crumb='قسيمة الراتب',
seo_title='قسيمة الراتب loonstrook سطراً سطراً 2026',
desc='شرح قسيمة الراتب (loonstrook) سطراً سطراً: من الإجمالي إلى الصافي، loonheffingskorting عند صاحب عمل واحد فقط، بدل العطلة 8%، وكيف تكتشف الأخطاء.',
summary='<ol><li><strong>القسيمة إلزامية</strong>: يجب أن تصلك عند أول دفعة، وكلما تغيّر شيء في راتبك.</li><li><strong>الإجمالي (bruto)</strong> ناقص الضرائب والاشتراكات (loonheffing) وحصة التقاعد = <strong>الصافي (netto)</strong> تقريباً.</li><li><strong>loonheffingskorting</strong> تخفض الضريبة الشهرية. طبّقها عند <strong>صاحب عمل واحد فقط</strong>؛ عند اثنين تُستحق عليك غالباً ضريبة إضافية لاحقاً.</li><li>الحد الأقصى للخصم العام (algemene heffingskorting) في 2026: <strong>3,115 يورو</strong> سنوياً، ويبدأ بالتناقص فوق دخل <strong>29,736 يورو</strong>.</li><li><strong>بدل العطلة 8% على الأقل</strong>؛ إما يُدَّخر ويُدفع مرة (غالباً مايو أو يونيو) أو يظهر مع كل راتب.</li><li><strong>افحص القسيمة كل شهر</strong>: الساعات، الأجر بالساعة مقابل الحد الأدنى، الإجازة، والخصومات.</li></ol>',
body=(
'<h2 id="must">ما الذي يجب أن تتضمنه القسيمة قانوناً؟</h2><p>حسب Rijksoverheid يجب أن يعطيك صاحب العمل قسيمة راتب (loonstrook) <strong>عند أول دفعة</strong>، ثم <strong>كلما تغير المبلغ</strong> (وكثير من الشركات ترسلها كل شهر). ويجب أن تتضمن على الأقل:</p>'
+T([['الأجر الإجمالي ومكوناته','الأجر الأساسي، والعمل الإضافي، والعلاوات، والبدلات، ومنها الحد الأدنى من بدل العطلة'],
    ['الخصومات','ضريبة الأجر، والاشتراكات، وحصة التقاعد (pensioen)، وأي خصم آخر'],
    ['الحد الأدنى للأجر المطبق عليك','بالساعة، حتى تقارن بنفسك'],
    ['اسمك واسم صاحب العمل','وبياناتهما'],
    ['الفترة','الشهر أو الأسابيع الأربعة التي تغطيها القسيمة'],
    ['عدد الساعات','ساعات العمل المتفق عليها أو التي عملتها'],
    ['معلومات العقد','هل العقد مكتوب؟ هل هو لمدة غير محددة؟ هل هو عقد استدعاء؟']],
   ['البند','ما يعنيه'])
+'<h2 id="lines">قراءة القسيمة سطراً سطراً</h2>'
+T([['Bruto loon / Salaris','الأجر الإجمالي قبل أي خصم.'],
    ['Uren / Gewerkte uren','الساعات المدفوعة. قارنها بسجلك.'],
    ['Uurloon','الأجر بالساعة. يجب ألا يقل عن الحد الأدنى لعمرك (<a href="/articles/minimum-wage-netherlands.html">جدول 2026</a>).'],
    ['Toeslagen (onregelmatigheid, overwerk)','علاوات العمل غير المنتظم أو الإضافي (حسب CAO)، وليست «Toeslagen» الحكومية.'],
    ['Pensioenpremie (werknemersdeel)','حصتك من اشتراك التقاعد؛ تُخصم قبل الضريبة عادة.'],
    ['Loon voor de loonheffing / Fiscaal loon','الأساس الذي تُحسب عليه الضريبة.'],
    ['Loonheffing','ضريبة الأجر + اشتراكات التأمينات الوطنية (AOW وغيرها) معاً.'],
    ['Loonheffingskorting: ja/nee','هل يطبق صاحب العمل الخصم الضريبي العام على راتبك.'],
    ['Inhouding Zvw / Bijdrage Zvw','مساهمة قانون التأمين الصحي المرتبطة بالدخل؛ في الغالب يتحملها صاحب العمل.'],
    ['Reservering vakantiegeld','بدل العطلة المدَّخر (8%)، يُدفع لاحقاً.'],
    ['Vakantie-uren / Verlofsaldo','رصيد ساعات الإجازة.'],
    ['Netto loon / Uit te betalen','المبلغ الذي يصل حسابك.'],
    ['Cumulatief / Tot en met deze periode','مجموع السنة حتى هذا الشهر. مفيد للتقدير السنوي للبدلات.']],
   ['ما يظهر في القسيمة','معناه'])
+'<p><strong>تنبيه:</strong> الأسماء تختلف قليلاً بين برامج الرواتب، لكن المعنى واحد. إن وجدت سطراً لا تفهمه فاطلب شرحه من قسم الرواتب (salarisadministratie) كتابياً.</p>'
'<h2 id="loonbegrip">لماذا تُحسب الضريبة على أساسات مختلفة؟</h2><p>في هولندا يُستخدم ما يسمى «مفهوم الأجر الموحد» (uniform loonbegrip). ببساطة: من الأجر نفسه تُحسب ثلاثة أنواع من الاقتطاعات:</p><ul><li><strong>ضريبة الأجر واشتراكات التأمينات الوطنية</strong> (loonbelasting/volksverzekeringen) — تُخصم منك وتظهر في «loonheffing».</li><li><strong>اشتراكات تأمين الموظفين</strong> (WW وWIA) — يدفعها صاحب العمل عادة.</li><li><strong>مساهمة التأمين الصحي المرتبطة بالدخل (Zvw)</strong> — يدفعها صاحب العمل في الغالب.</li></ul><p>لهذا قد ترى في القسيمة أكثر من «أساس» للأجر. ما يهمك عملياً: سطر <strong>loonheffing</strong> هو الضريبة التي تُخصم منك.</p>'
'<h2 id="korting">loonheffingskorting: أهم سطر قد يكلفك مالاً</h2><p><strong>loonheffingskorting</strong> هي الخصومات الضريبية (أهمها الخصم العام <strong>algemene heffingskorting</strong> وخصم العمل <strong>arbeidskorting</strong>) التي يطبقها صاحب العمل شهرياً على راتبك فتقل الضريبة.</p>'
+T([['algemene heffingskorting 2026','حتى <strong>3,115 يورو</strong> سنوياً؛ يتناقص فوق دخل <strong>29,736 يورو</strong> ويصل إلى الصفر عند دخل يقارب 78,400 يورو.'],
    ['arbeidskorting 2026','خصم لمن يعمل؛ حده الأقصى <strong>5,685 يورو</strong> سنوياً، ويتناقص مع الدخل المرتفع.'],
    ['من 1 يناير 2027','لن تُطبق arbeidskorting على <strong>الإعانات</strong> التي تُدفع عبر صاحب العمل (مثل بعض إعانات UWV)، بحسب UWV.']],
   ['الخصم','المبلغ والقاعدة'])
+'<p><strong>القاعدة الذهبية:</strong> طبّق loonheffingskorting <strong>عند جهة واحدة فقط</strong> (صاحب العمل الأعلى راتباً عادة). إن كان لك عملان، أو عمل وإعانة، وطبقتها عند الاثنين، تحصل خلال السنة على خصم أكثر مما تستحق، و<strong>تدفع الفرق لاحقاً</strong> في الإقرار الضريبي، وأحياناً مبلغاً كبيراً دفعة واحدة. يمكنك تجنب ذلك بطلب <strong>voorlopige aanslag</strong> (تقدير ضريبي مؤقت) من Mijn Belastingdienst.</p><p><strong>كيف تغيّرها؟</strong> عبر صاحب العمل أو جهة الإعانة: نموذجهم الخاص، أو نموذج Belastingdienst «Model opgaaf gegevens voor de loonheffingen» (السؤال 2a: تطبيق أو إيقاف).</p>'
'<h2 id="example">مثال توضيحي مبسط (ليس حساباً رسمياً)</h2><p>الأرقام التالية <strong>توضيحية فقط</strong> لتفهم التسلسل؛ نسب الضريبة الفعلية تعتمد على جداول Belastingdienst وCAO وتقاعدك:</p>'
+T([['الأجر الإجمالي','2,600'],['− حصة التقاعد (مثال)','− 120'],['= الأجر الخاضع للضريبة','2,480'],['− loonheffing بعد تطبيق الخصومات (مثال)','− 330'],['= الصافي المدفوع','2,150'],['+ مدّخر بدل العطلة 8% (لا يُدفع الآن)','208 تُضاف للرصيد']],['البند (يورو شهرياً)','المبلغ'])
+'<p>لاحظ أن بدل العطلة المدّخر لا يصل حسابك شهرياً، بل يُدفع مرة واحدة (غالباً في مايو أو يونيو)، وتُخصم منه ضريبة بنسبة أعلى ظاهرياً لأنه «دفعة خاصة» (bijzondere beloning). تُصحح الفروق في الإقرار السنوي (<a href="/articles/annual-tax-return-2026.html">دليل الإقرار الضريبي</a>).</p>'
'<h2 id="different">لماذا صافيك مختلف عن صافي زميلك؟</h2><ul><li>أحدكما لا يطبق loonheffingskorting (لديه عمل آخر).</li><li>اختلاف التقاعد (صناديق مختلفة أو لا تقاعد في أول فترة).</li><li>علاوات مختلفة: عمل ليلي، عطلة نهاية الأسبوع، إضافي.</li><li>خصومات خاصة: سكن، تأمين صحي جماعي، دراجة، نادٍ رياضي.</li><li>الشهر الذي يُدفع فيه بدل العطلة أو الشهر الثالث عشر.</li><li>دخل أعلى يعني خصومات أقل (تتناقص مع الدخل).</li><li>فترة مرض: راجع <a href="/articles/sick-pay-ziektewet-wia.html">دليل الأجر أثناء المرض (Ziektewet وWIA)</a> لتفهم ما يُدفع لك.</li></ul>'
'<h2 id="vakantiegeld">بدل العطلة والإجازات في القسيمة</h2><ul><li><strong>vakantiegeld:</strong> 8% على الأقل من الأجر الإجمالي (أو ما ينص عليه الـCAO، بشرط ألا يقل عن 8% من الحد الأدنى للأجر).</li><li>في عقد الاستدعاء أو الوكالة قد تُدفع الإجازة وبدل العطلة كنسبة مع كل راتب. يجب أن يكون ذلك واضحاً في القسيمة.</li><li>تحقق من <strong>رصيد ساعات الإجازة</strong>: الحد القانوني 4 أضعاف ساعاتك الأسبوعية سنوياً.</li></ul>'
'<h2 id="check">قائمة الفحص الشهرية (5 دقائق)</h2><ol><li>هل الساعات صحيحة؟ قارنها بسجلك أو جدولك.</li><li>هل الأجر بالساعة لا يقل عن <a href="/articles/minimum-wage-netherlands.html">الحد الأدنى</a>؟ (اقسم الإجمالي على الساعات).</li><li>هل العلاوات (ليل، عطلة، إضافي) موجودة حسب الـCAO؟</li><li>هل loonheffingskorting «ja» عند جهة واحدة فقط؟</li><li>هل بدل العطلة يُدَّخر أو يُدفع؟</li><li>هل كل خصم (سكن، تأمين) متفق عليه كتابياً؟</li><li>هل رصيد الإجازة يزيد؟</li><li>احفظ القسيمة (PDF) — ستحتاجها للبدلات، والإيجار، والإقامة، والقروض.</li></ol>'
'<h2 id="errors">وجدت خطأ؟ ماذا تفعل</h2><ol><li>اكتب لقسم الرواتب بالبريد: الشهر، السطر، ما تتوقعه ولماذا، مع صورة القسيمة وسجل الساعات.</li><li>اطلب التصحيح في الراتب التالي كتابياً.</li><li>إن رُفض طلبك وكان الأجر أقل من الحد الأدنى: يمكنك الإبلاغ لدى Nederlandse Arbeidsinspectie.</li><li>للنزاعات الأخرى: Juridisch Loket أو النقابة، وراجع حقوقك في <a href="/articles/employment-contracts-labor-law-2026.html">دليل عقد العمل</a>.</li></ol>'
'<h2 id="toeslagen">القسيمة والبدلات الحكومية</h2><p>لا تستخدم الصافي عند التقدير لدى Toeslagen. المطلوب هو <strong>الدخل الخاضع للتقييم</strong> (toetsingsinkomen)، وهو قريب من «الأجر الخاضع للضريبة» السنوي. استخدم سطر «cumulatief» واضربه في بقية السنة (<a href="/articles/toeslagen-income-update.html">كيف تحدّث دخلك</a>).</p>'),
faq=[('هل صاحب العمل ملزم بإعطائي قسيمة راتب؟','نعم، عند أول دفعة، وكلما تغير المبلغ. ويجب أن تذكر الإجمالي ومكوناته، الخصومات، الحد الأدنى المطبق، الفترة، الساعات، ونوع العقد.'),
('ما هي loonheffingskorting؟','الخصومات الضريبية (الخصم العام وخصم العمل) التي يطبقها صاحب العمل شهرياً فتقل ضريبتك. طبقها عند جهة واحدة فقط.'),
('عندي عملان، أين أطبق loonheffingskorting؟','عند جهة واحدة فقط، عادة صاحب الراتب الأعلى. التطبيق المزدوج يعني دفع ضريبة إضافية لاحقاً.'),
('كم الخصم العام في 2026؟','حتى 3,115 يورو سنوياً، ويتناقص فوق دخل 29,736 يورو.'),
('لماذا لا يظهر بدل العطلة في صافي الراتب؟','لأنه غالباً يُدَّخر (reservering) ويُدفع مرة واحدة في مايو أو يونيو.'),
('ماذا يتغير في 2027؟','حسب UWV لن تُطبق arbeidskorting على الإعانات المدفوعة عبر صاحب العمل اعتباراً من 1 يناير 2027.')],
src_note='راجعنا البنود الإلزامية في Rijksoverheid ومبالغ 2026 في Belastingdienst وUWV في 4 أكتوبر 2026. المثال الحسابي توضيحي وليس حساباً ضريبياً رسمياً.')

NL=dict(title='Je loonstrook regel voor regel (2026): van bruto naar netto, loonheffingskorting, vakantiegeld en fouten ontdekken',
crumb='Loonstrook',
seo_title='Loonstrook uitgelegd: van bruto naar netto 2026',
desc='Je loonstrook regel voor regel: van bruto naar netto, loonheffingskorting bij maar één werkgever, minimaal 8% vakantiegeld en een checklist voor fouten.',
summary='<ol><li><strong>Een loonstrook is verplicht</strong> bij de eerste betaling en als er iets verandert.</li><li><strong>Bruto</strong> min loonheffing en pensioenpremie is ongeveer je <strong>netto</strong>.</li><li><strong>Loonheffingskorting</strong> verlaagt je maandelijkse belasting. Pas die bij <strong>maar één</strong> werkgever of uitkeringsinstantie toe.</li><li>De algemene heffingskorting is in 2026 maximaal <strong>€3.115</strong> en neemt af boven <strong>€29.736</strong>.</li><li><strong>Vakantiegeld minimaal 8%</strong>: gereserveerd (meestal mei of juni) of per periode uitbetaald.</li><li><strong>Controleer je loonstrook elke maand.</strong></li></ol>',
body=(
'<h2 id="must">Wat moet er op je loonstrook staan?</h2><p>Volgens de Rijksoverheid krijg je een loonstrook <strong>bij de eerste betaling</strong> en daarna <strong>als het bedrag verandert</strong>. Erop staan minimaal:</p>'
+T([['Brutoloon en opbouw','Basisloon, overwerk, toeslagen, vergoedingen, waaronder minimaal vakantiegeld'],['Inhoudingen','Loonheffing, premies, pensioen, overige inhoudingen'],['Toepasselijk minimumloon','Zodat je zelf kunt vergelijken'],['Naam werknemer en werkgever',''],['Periode','Maand of 4 weken'],['Aantal uren','Overeengekomen of gewerkt'],['Contractgegevens','Schriftelijk contract ja/nee, onbepaalde tijd ja/nee, oproepcontract ja/nee']],['Onderdeel','Toelichting'])
+'<h2 id="lines">Regel voor regel</h2>'
+T([['Bruto loon / Salaris','Loon vóór inhoudingen.'],['Gewerkte uren','Vergelijk met je eigen registratie.'],['Uurloon','Minimaal het minimumloon voor je leeftijd (<a href="/nl/articles/minimum-wage-netherlands.html">bedragen 2026</a>).'],['Toeslagen (onregelmatigheid, overwerk)','Cao-toeslagen, niet de toeslagen van de overheid.'],['Pensioenpremie werknemersdeel','Jouw deel van de pensioenpremie.'],['Loon voor de loonheffing','De grondslag voor de belasting.'],['Loonheffing','Loonbelasting plus premies volksverzekeringen.'],['Loonheffingskorting ja/nee','Of de werkgever de heffingskortingen toepast.'],['Bijdrage Zvw','Inkomensafhankelijke bijdrage Zvw; meestal door de werkgever betaald.'],['Reservering vakantiegeld','Opgebouwd vakantiegeld (8%), later uitbetaald.'],['Verlofsaldo','Je resterende vakantie-uren.'],['Netto / Uit te betalen','Wat op je rekening komt.'],['Cumulatief','Totalen tot en met deze periode.']],['Regel','Betekenis'])
+'<h2 id="loonbegrip">Uniform loonbegrip</h2><p>Over hetzelfde loon worden drie soorten bedragen berekend: <strong>loonbelasting/premie volksverzekeringen</strong> (ingehouden op jouw loon, zichtbaar als loonheffing), <strong>werknemersverzekeringen</strong> (WW en WIA, meestal door de werkgever betaald) en de <strong>inkomensafhankelijke bijdrage Zvw</strong> (meestal werkgever). Voor jou is vooral de regel <strong>loonheffing</strong> van belang.</p>'
'<h2 id="korting">Loonheffingskorting</h2>'
+T([['Algemene heffingskorting 2026','Maximaal <strong>€3.115</strong>; neemt af boven <strong>€29.736</strong> en is rond €78.400 nul.'],['Arbeidskorting 2026','Maximaal <strong>€5.685</strong>; neemt af bij hogere inkomens.'],['Vanaf 1 januari 2027','Volgens UWV geen arbeidskorting meer over <strong>uitkeringen</strong> die via de werkgever worden betaald.']],['Korting','Bedrag en regel'])
+'<p><strong>Gouden regel:</strong> pas loonheffingskorting toe op <strong>maximaal 1 inkomen</strong>. Doe je het bij twee, dan krijg je te veel korting en betaal je het verschil later bij in je aangifte. Voorkom een hoge aanslag ineens met een <strong>voorlopige aanslag</strong> via Mijn Belastingdienst. Wijzigen doe je via je werkgever of uitkeringsinstantie, bijvoorbeeld met het formulier «Model opgaaf gegevens voor de loonheffingen» (vraag 2a).</p>'
'<h2 id="example">Rekenvoorbeeld (illustratief)</h2><p>De bedragen hieronder zijn <strong>alleen ter illustratie</strong> van de volgorde; echte inhoudingen hangen af van de tabellen van de Belastingdienst, je cao en je pensioen.</p>'
+T([['Brutoloon','2.600'],['− pensioenpremie (voorbeeld)','− 120'],['= loon voor de loonheffing','2.480'],['− loonheffing na kortingen (voorbeeld)','− 330'],['= netto uitbetaald','2.150'],['+ reservering vakantiegeld 8%','208 opgebouwd']],['Onderdeel (€ per maand)','Bedrag'])
+'<p>Vakantiegeld wordt meestal in mei of juni uitbetaald, met een hoger tarief op de loonstrook (bijzondere beloning). Verschillen worden verrekend in je aangifte (<a href="/nl/articles/annual-tax-return-2026.html">aangifte inkomstenbelasting</a>).</p>'
'<h2 id="different">Waarom is je netto anders dan dat van een collega?</h2><ul><li>Een van jullie past geen loonheffingskorting toe.</li><li>Ander pensioen of nog geen pensioen.</li><li>Andere toeslagen (nacht, weekend, overwerk).</li><li>Andere inhoudingen (huisvesting, collectieve zorgverzekering, fiets).</li><li>De maand waarin vakantiegeld of 13e maand wordt betaald.</li><li>Hoger inkomen betekent minder korting.</li><li>Ben je ziek geweest? Zie onze <a href="/nl/articles/sick-pay-ziektewet-wia.html">gids over loondoorbetaling, Ziektewet en WIA</a>.</li></ul>'
'<h2 id="vakantiegeld">Vakantiegeld en verlof</h2><ul><li><strong>Vakantiegeld:</strong> minimaal 8% van het brutoloon (of volgens cao, minimaal 8% van het minimumloon).</li><li>Bij oproep- of uitzendwerk kan vakantie(geld) per periode als percentage worden betaald; dat moet duidelijk op de strook staan.</li><li>Controleer je verlofsaldo: wettelijk 4 keer je wekelijkse arbeidsduur per jaar.</li></ul>'
'<h2 id="check">Maandelijkse checklist (5 minuten)</h2><ol><li>Kloppen de uren?</li><li>Is je uurloon minimaal het <a href="/nl/articles/minimum-wage-netherlands.html">minimumloon</a>?</li><li>Staan cao-toeslagen erop?</li><li>Loonheffingskorting «ja» bij maar één werkgever?</li><li>Vakantiegeld gereserveerd of uitbetaald?</li><li>Zijn alle inhoudingen schriftelijk afgesproken?</li><li>Groeit je verlofsaldo?</li><li>Bewaar de pdf: nodig voor toeslagen, huur, verblijf en leningen.</li></ol>'
'<h2 id="errors">Fout gevonden?</h2><ol><li>Mail de salarisadministratie: maand, regel, wat je verwacht en waarom, met kopie van strook en urenlijst.</li><li>Vraag schriftelijk om correctie bij de volgende betaling.</li><li>Krijg je minder dan het minimumloon: meld het bij de Nederlandse Arbeidsinspectie.</li><li>Andere conflicten: Juridisch Loket of vakbond; zie ook onze <a href="/nl/articles/employment-contracts-labor-law-2026.html">gids over het arbeidscontract</a>.</li></ol>'
'<h2 id="toeslagen">Loonstrook en toeslagen</h2><p>Geef bij Toeslagen nooit je netto loon door, maar je <strong>toetsingsinkomen</strong>, dat dicht bij je jaarlijkse loon voor de loonheffing ligt. Gebruik de cumulatieve regel en reken door naar een heel jaar (<a href="/nl/articles/toeslagen-income-update.html">inkomen doorgeven</a>).</p>'),
faq=[('Is mijn werkgever verplicht een loonstrook te geven?','Ja, bij de eerste betaling en als het bedrag verandert, met onder meer bruto, inhoudingen, minimumloon, periode, uren en contractgegevens.'),
('Wat is loonheffingskorting?','De heffingskortingen (algemene heffingskorting en arbeidskorting) die je werkgever elke maand verrekent. Pas die bij maar één inkomen toe.'),
('Ik heb twee banen. Waar pas ik loonheffingskorting toe?','Bij één werkgever, meestal die met het hoogste loon. Dubbel toepassen betekent later bijbetalen.'),
('Hoe hoog is de algemene heffingskorting in 2026?','Maximaal €3.115; die neemt af boven €29.736.'),
('Waarom zie ik mijn vakantiegeld niet in mijn netto loon?','Meestal wordt het gereserveerd en in mei of juni in één keer uitbetaald.'),
('Wat verandert er in 2027?','Volgens UWV vervalt per 1 januari 2027 de arbeidskorting over uitkeringen die via de werkgever worden betaald.')],
src_note='Verplichte onderdelen gecontroleerd bij de Rijksoverheid en bedragen 2026 bij Belastingdienst en UWV op 4 oktober 2026. Het rekenvoorbeeld is illustratief en geen officiële berekening.')
