from a_student_finance import T
SLUG='pregnancy-newborn-care'
Z='https://www.zorginstituutnederland.nl/verzekerde-zorg/'
R='https://www.rijksoverheid.nl/vraag-en-antwoord/'
P='https://www.pns.nl/'
SRC=[('Zorginstituut Nederland · Verloskundige zorg (Zvw)',Z+'v/verloskundige-zorg-zvw'),
('Zorginstituut Nederland · Kraamzorg (Zvw)',Z+'k/kraamzorg-zvw'),
('Zorginstituut Nederland · Eigen bijdrage (Zvw), overzicht 2026',Z+'e/eigen-bijdrage-zvw'),
('Rijksoverheid · Wanneer betaal ik een eigen bijdrage voor zorg? (2026)',R+'zorgverzekering/wanneer-eigen-bijdrage-zorgverzekering'),
('Rijksoverheid · Is een zorgverzekering verplicht? (basisverzekering kinderen)',R+'zorgverzekering/ben-ik-verplicht-een-zorgverzekering-af-te-sluiten'),
('Rijksoverheid · Hoe doe ik aangifte van een geboorte?',R+'aangifte-geboorte-en-naamskeuze-kind/aangifte-geboorte'),
('Rijksoverheid · Wanneer en waar kan ik mijn kind erkennen?',R+'ouderlijk-gezag/kind-erkennen-waneer-waar'),
('Rijksoverheid · Wat zijn de gevolgen als ik mijn kind erken?',R+'ouderlijk-gezag/kind-erkennen-gevolgen'),
('PNS.nl (RIVM) · Tijdlijn onderzoeken tijdens zwangerschap en na geboorte',P+'tijdlijn-onderzoeken-tijdens-zwangerschap-en-na-geboorte'),
('PNS.nl (RIVM) · Kosten NIPT',P+'nipt/kosten'),
('PNS.nl (RIVM) · De NIPT',P+'prenatale-screeningen/nipt'),
('PNS.nl (RIVM) · 13 wekenecho (IMITAS-studie)',P+'13-wekenecho'),
('PNS.nl (RIVM) · Kosten 20 wekenecho',P+'20-wekenecho/kosten'),
('PNS.nl (RIVM) · Hielprik',P+'neonatale-screeningen/hielprik'),
('PNS.nl (RIVM) · Gehoortest (Nederlands, meertalige pagina)',P+'en/multiple-languages/dutch/hearing-test'),
('PNS.nl (RIVM) · Informatie in het Arabisch',P+'en/multiple-languages/arabic'),
('RIVM Rijksvaccinatieprogramma · Kinkhoestprik voor zwangeren (22 wekenprik)','https://rijksvaccinatieprogramma.nl/vaccinaties/kinkhoestprik'),
('De Verloskundige (KNOV) · Afspraken bij de verloskundige','https://deverloskundige.nl/themas/begeleiding-en-controles/afspraken-bij-de-verloskundige'),
('De Verloskundige (KNOV) · Belinstructies: wanneer bel je de verloskundige?','https://deverloskundige.nl/themas/begeleiding-en-controles/belinstructies-wanneer-bel-je-de-verloskundige')]
AR=dict(title='الحمل والولادة في هولندا 2026: القابلة (verloskundige)، الفحوصات المجانية، رعاية ما بعد الولادة (kraamzorg) بـ5.70 يورو للساعة، وتسجيل المولود خلال 3 أيام — مع جدول زمني',
crumb='الحمل والولادة',
desc='دليل عملي للحامل القادمة حديثاً إلى هولندا: متى تتصلين بالقابلة، أي فحوصات مجانية (NIPT، إيكو الأسبوع 20)، وضع إيكو الأسبوع 13 في 2026، الولادة في البيت أو المستشفى ومساهمة 22.50 يورو يومياً، الكرامزورخ (24–80 ساعة، 5.70 يورو للساعة)، تسجيل المولود خلال 3 أيام، الاعتراف بالطفل قبل الولادة، التأمين خلال 4 أشهر، فحص الكعب والسمع والتطعيمات، مع أمثلة وأسئلة شائعة.',
summary='<ol><li><strong>اتصلي بالقابلة (verloskundige) فور ظهور اختبار حمل إيجابي.</strong> الموعد الأول عادة <strong>حول الأسبوع 8</strong>. تختارين العيادة بنفسك.</li><li><strong>الفحوصات:</strong> فحص تحديد عمر الحمل (termijnecho) ضمن التأمين الأساسي. <strong>NIPT</strong> من الأسبوع 10 <strong>مجاني</strong>. <strong>إيكو الأسبوع 20</strong> (بين 18 و21) <strong>مجاني</strong>. <strong>إيكو الأسبوع 13</strong> في 2026 متاح <strong>فقط</strong> بالمشاركة في دراسة IMITAS.</li><li><strong>سجّلي رعاية ما بعد الولادة (kraamzorg) من الأسبوع 12.</strong> تحصلين على <strong>24 إلى 80 ساعة</strong>، والمساهمة في البيت <strong>5.70 يورو للساعة</strong> في 2026. رعاية القابلة والكرامزورخ <strong>لا تدخل في الخصم الذاتي (eigen risico)</strong>.</li><li><strong>الولادة في البيت</strong>، أو في المستشفى <strong>لسبب طبي</strong>: بلا مساهمة. الولادة في المستشفى <strong>دون سبب طبي</strong> (poliklinisch): <strong>22.50 يورو يومياً للأم و22.50 لكل طفل</strong> على الأقل.</li><li><strong>بعد الولادة:</strong> سجّلوا المولود في البلدية خلال <strong>3 أيام</strong> (يوم الولادة لا يُحسب)، وأمّنوا عليه خلال <strong>4 أشهر</strong> (بلا قسط حتى 18 سنة). فحص الكعب في الأسبوع الأول وفحص السمع في الشهر الأول <strong>مجانيان</strong>.</li><li><strong>غير متزوجين؟</strong> اعترف بالطفل قبل الولادة (erkenning van de ongeboren vrucht) في <strong>أي بلدية</strong>، و<strong>مجاناً</strong>.</li></ol>',
body=(
'<h2 id="system">كيف تعمل رعاية الحمل في هولندا؟</h2><p>في هولندا، الحمل الطبيعي يتابعه <strong>القابلة (verloskundige)</strong>، لا طبيب النساء. القابلة هي نقطة الاتصال الأولى: تتابع الحمل، تجري الفحوصات الدورية، تشرح الفحوصات الاختيارية، وتولّد في البيت أو في المستشفى. إن ظهر خطر طبي تحوّلك إلى <strong>طبيب النساء (gynaecoloog)</strong> في المستشفى. في بعض المناطق يتابع طبيب العائلة الحمل أيضاً.</p><ul><li>تختارين <strong>عيادة القابلة بنفسك</strong> وتسجلين مباشرة. ابحثي عن عيادة قريبة من بيتك.</li><li>القابلة متاحة <strong>24 ساعة في اليوم و7 أيام في الأسبوع</strong> للحالات العاجلة. إن شككتِ أن الأمر عاجل، اتصلي.</li><li>بعد الولادة ترافقك القابلة في <strong>الأيام العشرة الأولى</strong>. بعدها يتولى طبيب العائلة ومركز رعاية الطفل (consultatiebureau) المتابعة. يمكنك الاتصال بالقابلة بخصوص صحتك حتى <strong>6 أسابيع</strong> بعد الولادة، وفيها موعد الفحص الختامي.</li></ul>'
+'<h2 id="timeline">الجدول الزمني أسبوعاً بأسبوع</h2>'
+T([['اختبار حمل إيجابي','اتصلي بعيادة قابلة وسجّلي','—'],['حول الأسبوع 8','الموعد الأول (intake): الأسئلة الطبية، الضغط، شرح الفحوصات','التأمين الأساسي'],['بين 8 و13','فحص دم للحامل: الأمراض المعدية (HIV، الزهري، التهاب الكبد B) وفصيلة الدم والأجسام المضادة','—'],['بين 10 و14','إيكو تحديد عمر الحمل (termijnecho)','التأمين الأساسي'],['من الأسبوع 10','NIPT (اختياري؛ ناقشيه مع القابلة قبل الأسبوع 10)','مجاني'],['من الأسبوع 12','سجّلي لدى منظمة كرامزورخ (kraamzorgorganisatie)','—'],['12+3 إلى 14+3','إيكو الأسبوع 13: فقط ضمن دراسة IMITAS','مجاني للمشاركات'],['من 12 إلى 24','موعد كل 4–6 أسابيع','—'],['بين 18 و21','إيكو الأسبوع 20 (اختياري)','مجاني'],['من الأسبوع 22','تطعيم السعال الديكي (22-wekenprik)، والإنفلونزا في موسمها','مجاني'],['من 24 إلى 32','موعد كل 3 أسابيع','—'],['الأسبوع 27 و30','فحص دم إضافي وحقنة Anti-D فقط لمن فصيلتها سالبة Rhesus عند الحاجة','—'],['قبل الولادة','الاعتراف بالطفل إن لم تكونا متزوجَين (erkenning)','مجاني'],['حوالي شهرين قبل الموعد','زيارة تعارف (intake) من منظمة الكرامزورخ','—'],['من 32 إلى 37 ثم كل أسبوع','موعد كل أسبوعين، ثم أسبوعياً من الأسبوع 37','—']],['الأسبوع','ماذا يحدث','التكلفة'])
+'<p>المجموع <strong>13 موعداً على الأقل</strong> أثناء الحمل، حسب موقع القابلات (KNOV). الفحوصات الاختيارية (NIPT، إيكو 13 و20) قرارك أنت؛ القابلة تشرح ولا تفرض.</p>'
+'<h2 id="screening">الإيكو والفحوصات: ماذا يغطي التأمين في 2026؟</h2>'
+T([['إيكو تحديد عمر الحمل (10–14 أسبوعاً)','التأمين الأساسي'],['إيكو إضافي لسبب طبي','التأمين الأساسي'],['جلسة الشرح (counseling) عن الفحوصات','برنامج الفحص الوطني (مجاني)'],['NIPT دون سبب طبي','برنامج الفحص الوطني: مجاني'],['NIPT لسبب طبي','التأمين الأساسي'],['إيكو الأسبوع 13','مجاني، ولكن فقط ضمن دراسة IMITAS'],['إيكو الأسبوع 20','مجاني إن كان مُجري الإيكو متعاقداً مع مركز إقليمي للفحص (Regionaal Centrum)'],['فحوصات المتابعة بعد نتيجة غير طبيعية (مثل بزل السائل الأمنيوسي)','التأمين الأساسي، وقد تدفعين جزءاً من الخصم الذاتي'],['إيكو «للذكرى» ثلاثي أو رباعي الأبعاد (pretecho)','غير مغطى: تدفعينه بنفسك']],['الفحص','من يدفع'])
+'<ul><li><strong>NIPT</strong>: فحص دم يبحث عن تشوهات الكروموسومات، ممكن من <strong>الأسبوع 10</strong>، والنتيجة خلال نحو <strong>10 أيام</strong>.</li><li><strong>إيكو الأسبوع 13</strong>: حسب PNS.nl «في هولندا لا يمكنك اختيار إيكو الأسبوع 13 إلا إذا شاركتِ في دراسة IMITAS العلمية»، ويُجرى بين 12+3 و14+3 أسبوعاً. اسألي قابلتك إن كانت تشارك.</li><li><strong>إيكو الأسبوع 20</strong>: يبحث عن تشوهات جسدية بتفاصيل أوضح من إيكو الأسبوع 13. قد يظهر جنس الجنين أحياناً، لكنه ليس هدف الفحص.</li><li>معلومات رسمية <strong>بالعربية</strong> عن كل هذه الفحوصات على موقع <strong>PNS.nl</strong> (قسم Information in multiple languages).</li></ul>'
+'<h2 id="birth">أين تلدين؟ البيت، المستشفى، أو مركز الولادة</h2>'
+T([['في البيت (thuisbevalling) مع القابلة','لا مساهمة'],['في المستشفى لسبب طبي (مع طبيب النساء)','لا مساهمة'],['في المستشفى أو مركز ولادة مع القابلة دون سبب طبي (poliklinische bevalling)','22.50 يورو يومياً للأم + 22.50 لكل طفل على الأقل، وقد يُضاف مبلغ حسب المؤسسة'],['مساعدة الكرامزورخ أثناء الولادة (partusassistentie) حتى ساعتين بعد خروج المشيمة','لا مساهمة']],['مكان الولادة','المساهمة الذاتية 2026'])
+'<p>في الولادة poliklinisch دون سبب طبي، يسمح للمؤسسة أن تطالب التأمين بحد أقصى <strong>323 يورو يومياً</strong> (161.50 للأم و161.50 للطفل)، تُخصم منها المساهمة، فيدفع التأمين <strong>278 يورو كحد أقصى</strong>. إن كان سعر المؤسسة أعلى تدفعين الفرق أيضاً. <strong>اسألي المستشفى أو مركز الولادة عن سعره اليومي قبل الولادة</strong>، وراجعي إن كان تأمينك الإضافي يغطي جزءاً.</p><p>كثير من النساء يلدن في البيت في هولندا؛ هذا طبيعي هنا وليس دليلاً على نقص الرعاية. إن تغيّر الوضع أثناء الولادة تنقلك القابلة إلى المستشفى، وتصبح الولادة حينها «لسبب طبي».</p>'
+'<h2 id="kraamzorg">رعاية ما بعد الولادة (kraamzorg)</h2><p>«الكرامفيرزورخنده» (kraamverzorgende) ممرضة تأتي إلى بيتك بعد الولادة: تفحصك وتفحص الطفل، تساعد في الرضاعة، تعلّمك العناية بالمولود، وتبلّغ القابلة إن لاحظت مشكلة.</p><ol><li><strong>سجّلي من الأسبوع 12</strong> لدى منظمة كرامزورخ (اسألي شركة التأمين عن المنظمات المتعاقدة معها). التسجيل المبكر يضمن مكاناً.</li><li><strong>زيارة تعارف (intake)</strong> تقريباً قبل الموعد بشهرين: يتفقون معك على الترتيبات في البيت.</li><li><strong>عدد الساعات:</strong> بين <strong>24 و80 ساعة</strong> حسب البروتوكول الوطني (Landelijk Indicatieprotocol Kraamzorg). تحدد الكرامفيرزورخنده والقابلة العدد النهائي بعد الولادة، حسب الرضاعة والمضاعفات والإقامة في المستشفى.</li><li><strong>المدة:</strong> عادة حتى <strong>اليوم الثامن</strong> بعد الولادة، وأحياناً حتى <strong>اليوم العاشر</strong> أو أطول لسبب طبي. الحق القانوني ممتد حتى 6 أسابيع بعد الولادة.</li><li><strong>المساهمة:</strong> <strong>5.70 يورو لكل ساعة</strong> كرامزورخ في البيت (2026). <strong>لا مساهمة</strong> عن الكرامزورخ داخل المستشفى. وتكاليف الكرامزورخ <strong>لا تدخل في الخصم الذاتي (eigen risico)</strong>.</li><li><strong>حقيبة الولادة (kraampakket):</strong> اسألي شركة التأمين إن كانت ترسل حقيبة مستلزمات الولادة. هذا يختلف بين البوالص.</li></ol>'
+'<h2 id="costs">التكاليف: من يدفع ماذا؟</h2>'
+T([['متابعة القابلة والولادة','التأمين الأساسي','لا يدخل في الخصم الذاتي'],['الفحوصات الوطنية (NIPT، إيكو 20، فحص الكعب، فحص السمع)','الدولة','مجانية'],['الكرامزورخ في البيت','التأمين الأساسي','5.70 يورو/ساعة'],['الولادة poliklinisch دون سبب طبي','التأمين الأساسي حتى حد معين','22.50 يورو/يوم للأم و22.50 لكل طفل على الأقل + الفرق إن كان السعر أعلى'],['الأدوية، النقل، وبعض فحوصات المختبر المرتبطة','التأمين الأساسي','قد يدخل في الخصم الذاتي'],['تطعيم السعال الديكي والإنفلونزا للحامل','برنامج التطعيم الوطني','مجاني'],['إيكو الذكرى (pretecho)','أنتِ','غير مغطى'],['تأمين الطفل حتى 18 سنة','التأمين الأساسي','بلا قسط وبلا خصم ذاتي']],['البند','من يدفع','ما تدفعينه أنتِ'])
+'<h2 id="examples">أمثلة محسوبة</h2>'
+T([['كرامزورخ في البيت 24 ساعة (الحد الأدنى)','24 × 5.70 = <strong>136.80 يورو</strong>'],['كرامزورخ 32 ساعة (مثال Zorginstituut)','32 × 5.70 = <strong>182.40 يورو</strong>'],['كرامزورخ 80 ساعة (الحد الأقصى)','80 × 5.70 = <strong>456 يورو</strong>'],['ولادة في البيت مع القابلة ثم 32 ساعة كرامزورخ','الولادة 0 + الكرامزورخ <strong>182.40 يورو</strong>'],['ولادة poliklinisch دون سبب طبي، يوم واحد، طفل واحد','22.50 + 22.50 = <strong>45 يورو على الأقل</strong> + الفرق إن كان سعر المؤسسة أعلى'],['نفس الحالة مع توأم، يوم واحد','22.50 + 22.50 × 2 = <strong>67.50 يورو على الأقل</strong>'],['ولادة في المستشفى لسبب طبي، والكرامزورخ في المستشفى','الولادة 0 + الكرامزورخ في المستشفى 0؛ تدفعين فقط ساعات الكرامزورخ في البيت بعد العودة']],['الحالة','الحساب'])
+'<p>أمثلة توضيحية وليست حالات أشخاص حقيقيين. مثال 32 ساعة مأخوذ من صفحة Zorginstituut. لم نحسب مبلغاً لسعر مؤسسة معينة لأنه يختلف؛ اسألي المؤسسة.</p>'
+'<h2 id="aangifte">تسجيل المولود في البلدية (aangifte geboorte)</h2><ul><li><strong>المهلة: 3 أيام بعد الولادة</strong>، ويوم الولادة لا يُحسب. إن انتهت المهلة يوم سبت أو أحد أو عطلة رسمية يُضاف يوم عمل. ولكم دائماً <strong>يوما عمل على الأقل</strong>.</li><li><strong>أين؟</strong> في البلدية <strong>التي وُلد فيها الطفل</strong> (قد تختلف عن بلدية سكنكم إن وُلد في مستشفى مدينة أخرى). بعض البلديات تسمح بالتسجيل <strong>عبر الإنترنت</strong>، للأب أو الأم فقط.</li><li><strong>من؟</strong> <strong>الأب أو الأم الثانية (duomoeder) ملزم</strong> بالتسجيل. الأم التي ولدت يجوز لها ولا يُلزمها. إن لم يستطع أحد منهم: شخص حضر الولادة، أو مالك البيت، أو موظف المستشفى.</li><li><strong>ماذا تحمل؟</strong> وثيقة هوية سارية، ووثيقة الاعتراف أو اختيار الاسم إن وُجدت. لا تحتاج إحضار الطفل.</li><li><strong>متأخر؟</strong> يبلّغ موظف الأحوال المدنية النيابة العامة، وقد تحصل على غرامة.</li><li>بعد التسجيل تُصدر <strong>شهادة الميلاد</strong> ويُسجَّل الطفل في سجل السكان (BRP) ويحصل على <strong>رقم BSN</strong> الذي تحتاجه للتأمين الصحي والإعانات. التسجيل السريع مهم أيضاً لأن فريق فحص الكعب يعرف من خلاله بولادة الطفل.</li></ul>'
+T([['الإثنين','الخميس'],['الثلاثاء','الجمعة'],['الأربعاء','الإثنين'],['الخميس','الإثنين'],['الجمعة','الثلاثاء'],['الجمعة (والإثنين عطلة رسمية)','الأربعاء'],['السبت','الثلاثاء'],['الأحد','الأربعاء']],['وُلد الطفل يوم','آخر يوم للتسجيل'])
+'<h2 id="erkenning">غير متزوجَين؟ الاعتراف بالطفل (erkenning)</h2><p>إن كان الوالدان <strong>متزوجَين أو بشراكة مسجلة</strong>، يصبح الزوج أباً قانونياً تلقائياً (للأم الثانية شروط خاصة). <strong>إن لم تكونا متزوجَين</strong>، لا تنشأ علاقة قانونية بين الأب والطفل إلا بالاعتراف.</p><ol><li><strong>أفضل وقت: أثناء الحمل</strong> (erkenning van de ongeboren vrucht)، في <strong>أي بلدية</strong> في هولندا. هكذا يكون الأب أباً قانونياً منذ لحظة الولادة.</li><li>إن لم تحضر الأم، تحتاج <strong>موافقتها الكتابية</strong>.</li><li>وثيقة الاعتراف <strong>مجانية</strong>؛ النسخ الإضافية بمقابل.</li><li>يمكن أيضاً الاعتراف عند تسجيل الولادة، أو لاحقاً (من 12 سنة تلزم موافقة الطفل والأم، ومن 16 موافقة الطفل فقط).</li><li><strong>إن كنتما من جنسية أجنبية</strong>، اسألا البلدية مبكراً عن الوثائق المطلوبة، فقد تحتاج وقتاً.</li></ol><p><strong>نتائج الاعتراف:</strong> علاقة قانونية بين الأب والطفل؛ منذ 2023 يحصل المعترِف تلقائياً على <strong>الولاية المشتركة (gezamenlijk gezag)</strong> مع الأم (مع استثناءات)؛ واجب النفقة حتى <strong>21 سنة</strong>؛ الإرث المتبادل؛ واختيار <strong>اسم العائلة</strong> عند الاعتراف.</p>'
+'<h2 id="newborn">الطفل بعد الولادة: الفحوصات والتأمين والتطعيمات</h2><ul><li><strong>فحص الكعب (hielprik)</strong>: في <strong>الأسبوع الأول</strong>، يأتي موظف من الرعاية الصحية للشباب (JGZ) إلى البيت ويأخذ قطرات دم من كعب الطفل للكشف عن أمراض نادرة خطيرة. <strong>مجاني</strong> واختياري، والنتيجة خلال <strong>5 أسابيع</strong>.</li><li><strong>فحص السمع (gehoortest)</strong>: في <strong>الشهر الأول</strong>، يجريه موظف مختص من مركز رعاية الطفل. لا يؤلم، و<strong>مجاني</strong>؛ والمتابعة إن لزمت يغطيها التأمين.</li><li><strong>التأمين الصحي</strong>: سجّلي الطفل لدى شركة التأمين <strong>خلال 4 أشهر</strong> من الولادة. لا قسط ولا خصم ذاتي حتى 18 سنة. انظري <a href="/articles/health-insurance-newcomers.html">التأمين الصحي للقادمين الجدد</a>.</li><li><strong>مركز رعاية الطفل (consultatiebureau / JGZ)</strong>: يتابع نمو الطفل وتطوره ويعطي تطعيمات <strong>برنامج التطعيم الوطني (Rijksvaccinatieprogramma)</strong> مجاناً.</li><li><strong>التطعيمات</strong>: إن أخذتِ تطعيم السعال الديكي في الحمل (من الأسبوع 22)، يكون الطفل محمياً من اليوم الأول، ويأخذ أول حقنة DKTP-Hib-HepB في <strong>عمر 3 أشهر</strong> بدل <strong>شهرين</strong>. التطعيم يُحجز لدى JGZ ويمكن أخذه في مركز رعاية الطفل.</li></ul>'
+'<h2 id="money">الإجازة والمال</h2><ul><li><strong>إجازة الحمل والولادة وإجازة الشريك</strong>: كل التفاصيل في <a href="/articles/birth-parental-leave.html">إجازة الولادة والأمومة والأبوة</a>.</li><li><strong>إعانة الأطفال (kinderbijslag)</strong> من SVB: <a href="/articles/kinderbijslag-guide.html">دليل kinderbijslag</a>.</li><li><strong>ميزانية الطفل (kindgebonden budget)</strong>: <a href="/articles/kindgebonden-budget-guide.html">الدليل</a>.</li><li><strong>عندك إعانات (toeslagen)؟</strong> أبلغ عن الطفل الجديد وعن تغيّر دخلك: <a href="/articles/toeslagen-income-update.html">تحديث الدخل في الإعانات</a>.</li><li><strong>حضانة الأطفال لاحقاً</strong>: <a href="/articles/childcare-allowance-kinderopvangtoeslag.html">إعانة الحضانة</a>.</li></ul>'
+'<h2 id="steps">خطوة بخطوة: ماذا تفعلين ومتى</h2><ol><li><strong>اختبار إيجابي</strong>: سجّلي لدى عيادة قابلة، وتأكدي أن تأمينك الصحي ساري وأن لديك طبيب عائلة (<a href="/articles/huisarts-registration.html">التسجيل لدى طبيب العائلة</a>).</li><li><strong>قبل الأسبوع 10</strong>: قرّري مع القابلة إن كنتِ تريدين NIPT.</li><li><strong>من الأسبوع 12</strong>: سجّلي الكرامزورخ.</li><li><strong>غير متزوجَين</strong>: حدّدا موعداً في البلدية للاعتراف بالطفل قبل الولادة.</li><li><strong>إن كنتِ تعملين</strong>: خططي لإجازة الحمل وأبلغي صاحب العمل في الوقت.</li><li><strong>قبل الولادة</strong>: جهّزي حقيبة المستشفى، ارفعي السرير إن طلبت الكرامزورخ ذلك، واحفظي رقم القابلة.</li><li><strong>خلال 3 أيام بعد الولادة</strong>: تسجيل المولود في البلدية.</li><li><strong>خلال 4 أشهر</strong>: تأمين الطفل الصحي.</li><li><strong>بعد ذلك</strong>: إعانة الأطفال، وتحديث الإعانات، ومواعيد مركز رعاية الطفل.</li></ol>'
+'<h2 id="mistakes">أخطاء شائعة</h2><ol><li><strong>تأخير التسجيل لدى الكرامزورخ</strong> حتى الشهر الأخير؛ سجّلي من الأسبوع 12.</li><li><strong>الظن أن إيكو الأسبوع 13 متاح للجميع</strong>؛ في 2026 فقط ضمن دراسة IMITAS.</li><li><strong>اختيار المستشفى دون سبب طبي</strong> دون السؤال عن السعر اليومي والمساهمة.</li><li><strong>نسيان الاعتراف بالطفل</strong> عندما يكون الوالدان غير متزوجَين قانونياً في هولندا (زواج ديني فقط أو زواج غير مسجل). اسألا البلدية إن كان زواجكما الأجنبي مسجلاً.</li><li><strong>التأخر في تسجيل المولود</strong> أكثر من 3 أيام، فقد تأتي غرامة ويتأخر فحص الكعب.</li><li><strong>نسيان تأمين الطفل</strong> خلال 4 أشهر.</li><li><strong>الاعتماد على الأقارب للترجمة</strong> في المواعيد الطبية المهمة؛ اسألي عن مترجم محترف.</li><li><strong>دفع ثمن إيكو «تجاري»</strong> والظن أنه بديل عن الإيكو الطبي؛ ليس كذلك.</li></ol>'
+'<h2 id="help">أين تجدين مساعدة مجانية؟</h2><ul><li><strong>قابلتك</strong>: أول عنوان لكل سؤال، ومتاحة على مدار الساعة للحالات العاجلة.</li><li><strong>PNS.nl</strong> (RIVM): شرح الفحوصات قبل الولادة وبعدها <strong>بالعربية</strong>.</li><li><strong>مركز رعاية الطفل (JGZ)</strong>: أسئلة عن الرضاعة والنمو والتطعيم، مجاناً.</li><li><strong>شركة التأمين</strong>: قائمة منظمات الكرامزورخ المتعاقدة، وحقيبة الولادة، وتغطية التأمين الإضافي.</li><li><strong>البلدية</strong>: تسجيل المولود والاعتراف بالطفل.</li><li><strong>اللغة</strong>: اطلبي من القابلة أو المستشفى ترتيب <strong>مترجم محترف</strong> للمواعيد المهمة. هل هو مجاني أم لا؟ يختلف حسب الجهة، فاسألي مسبقاً.</li></ul>'
+'<h2 id="related">أدلة مرتبطة</h2><ul><li><a href="/articles/birth-parental-leave.html">إجازة الولادة والأمومة والأبوة</a></li><li><a href="/articles/kinderbijslag-guide.html">إعانة الأطفال kinderbijslag</a></li><li><a href="/articles/kindgebonden-budget-guide.html">ميزانية الطفل kindgebonden budget</a></li><li><a href="/articles/health-insurance-newcomers.html">التأمين الصحي للقادمين الجدد</a></li><li><a href="/articles/huisarts-registration.html">التسجيل لدى طبيب العائلة</a></li><li><a href="/articles/bsn-municipality-registration.html">BSN والتسجيل في البلدية</a></li></ul>'),
faq=[('متى أتصل بالقابلة؟','فور ظهور اختبار حمل إيجابي. الموعد الأول عادة حول الأسبوع 8، وتختارين العيادة بنفسك.'),
('هل NIPT مجاني في 2026؟','نعم، الفحص وجلسة الشرح مجانيان، ويمكن إجراؤه من الأسبوع 10. فحوصات المتابعة بعد نتيجة غير طبيعية يغطيها التأمين الأساسي وقد يدخل جزء منها في الخصم الذاتي.'),
('هل يوجد إيكو الأسبوع 13؟','في 2026 فقط إن شاركتِ في دراسة IMITAS العلمية، ويكون حينها مجانياً.'),
('هل إيكو الأسبوع 20 مجاني؟','نعم، تدفعه الدولة إن كان مُجري الإيكو متعاقداً مع مركز إقليمي للفحص قبل الولادة.'),
('كم أدفع للكرامزورخ؟','5.70 يورو لكل ساعة في البيت في 2026، لعدد بين 24 و80 ساعة. لا مساهمة في المستشفى، ولا يدخل في الخصم الذاتي.'),
('هل تدخل متابعة الحمل في الخصم الذاتي (eigen risico)؟','لا، رعاية القابلة والكرامزورخ والفحوصات الوطنية خارج الخصم الذاتي. لكن الأدوية والنقل وبعض فحوصات المختبر قد تدخل فيه.'),
('أريد الولادة في المستشفى دون سبب طبي، كم أدفع؟','22.50 يورو يومياً للأم و22.50 لكل طفل على الأقل، وقد يُضاف فرق إن كان سعر المؤسسة أعلى من حد التأمين.'),
('متى أسجل المولود؟','خلال 3 أيام بعد الولادة في بلدية مكان الولادة، ويوم الولادة لا يُحسب. الأب أو الأم الثانية ملزم بذلك.'),
('لسنا متزوجَين، ماذا نفعل؟','اعترف بالطفل أثناء الحمل في أي بلدية، مجاناً. إن لم تحضر الأم تلزم موافقتها الكتابية.'),
('متى أؤمّن على الطفل؟','خلال 4 أشهر من الولادة لدى شركة تأمين. لا قسط ولا خصم ذاتي حتى 18 سنة.')],
src_note='راجعنا Zorginstituut Nederland وRijksoverheid وPNS.nl (RIVM) وموقع التطعيم الوطني وموقع القابلات (KNOV) في 7 أكتوبر 2026. المبالغ لعام 2026. لم نذكر مدد إجازة الحمل ومبالغ الإعانات هنا؛ انظري الأدلة المرتبطة. لم نذكر مبلغ سعر مؤسسة ولادة بعينه لأنه يختلف. الأمثلة توضيحية.')
NL=dict(title='Zwanger en bevallen in Nederland 2026: verloskundige, gratis screening, kraamzorg € 5,70 per uur en aangifte binnen 3 dagen — met tijdlijn',
crumb='Zwangerschap en geboorte',
desc='Praktische gids voor nieuwkomers die zwanger zijn: wanneer je de verloskundige belt, welke onderzoeken gratis zijn (NIPT, 20 wekenecho), de status van de 13 wekenecho in 2026, thuis of in het ziekenhuis bevallen en de eigen bijdrage van € 22,50 per dag, kraamzorg (24–80 uur, € 5,70 per uur), aangifte binnen 3 dagen, erkenning vóór de geboorte, verzekeren binnen 4 maanden, hielprik, gehoortest en vaccinaties, met rekenvoorbeelden en FAQ.',
summary='<ol><li><strong>Bel een verloskundige zodra je zwangerschapstest positief is.</strong> De eerste afspraak is meestal <strong>rond 8 weken</strong>. Je kiest zelf een praktijk.</li><li><strong>Onderzoeken:</strong> de termijnecho valt onder de basisverzekering. De <strong>NIPT</strong> vanaf 10 weken is <strong>gratis</strong>. De <strong>20 wekenecho</strong> (tussen 18 en 21 weken) is <strong>gratis</strong>. De <strong>13 wekenecho</strong> kan in 2026 <strong>alleen</strong> via de IMITAS-studie.</li><li><strong>Meld je vanaf week 12 aan voor kraamzorg.</strong> Je krijgt <strong>24 tot 80 uur</strong>; de eigen bijdrage thuis is <strong>€ 5,70 per uur</strong> in 2026. Verloskundige zorg en kraamzorg vallen <strong>niet onder het eigen risico</strong>.</li><li><strong>Thuis bevallen</strong> of in het ziekenhuis <strong>op medische indicatie</strong>: geen eigen bijdrage. <strong>Poliklinisch zonder medische indicatie</strong>: minimaal <strong>€ 22,50 per dag voor de moeder en € 22,50 per baby</strong>.</li><li><strong>Na de geboorte:</strong> aangifte binnen <strong>3 dagen</strong> (geboortedag telt niet mee), baby verzekeren binnen <strong>4 maanden</strong> (geen premie tot 18). Hielprik in de eerste week en gehoortest in de eerste maand zijn <strong>gratis</strong>.</li><li><strong>Niet getrouwd?</strong> Erken het kind vóór de geboorte (erkenning ongeboren vrucht) in <strong>elke gemeente</strong>, <strong>gratis</strong>.</li></ol>',
body=(
'<h2 id="system">Hoe werkt de zorg tijdens de zwangerschap?</h2><p>In Nederland begeleidt de <strong>verloskundige</strong> een gezonde zwangerschap, niet de gynaecoloog. De verloskundige is je eerste aanspreekpunt: zij doet de controles, legt de keuzeonderzoeken uit en begeleidt de bevalling thuis of in het ziekenhuis. Bij een medisch risico verwijst zij je naar de <strong>gynaecoloog</strong> in het ziekenhuis. In sommige regio’s begeleidt ook de huisarts zwangerschappen.</p><ul><li>Je <strong>kiest zelf een verloskundigenpraktijk</strong> en meldt je daar direct aan. Kijk welke praktijken bij jou in de buurt zitten.</li><li>Verloskundigen zijn <strong>24 uur per dag, 7 dagen per week</strong> bereikbaar voor spoed. Twijfel je of het spoed is? Bel.</li><li>Na de bevalling begeleidt de verloskundige je de <strong>eerste tien dagen</strong>. Daarna nemen de huisarts en het consultatiebureau het over. Voor je eigen gezondheid kun je tot <strong>6 weken</strong> na de bevalling de verloskundige bellen; dan is ook de nacontrole.</li></ul>'
+'<h2 id="timeline">Tijdlijn week voor week</h2>'
+T([['Positieve test','Bel een verloskundigenpraktijk en meld je aan','—'],['Rond week 8','Eerste afspraak (intake): medische vragen, bloeddruk, uitleg onderzoeken','Basisverzekering'],['Week 8–13','Bloedonderzoek zwangeren: infectieziekten (hiv, syfilis, hepatitis B), bloedgroep en antistoffen','—'],['Week 10–14','Termijnecho','Basisverzekering'],['Vanaf week 10','NIPT (keuze; bespreek dit vóór week 10)','Gratis'],['Vanaf week 12','Aanmelden bij een kraamzorgorganisatie','—'],['12+3 tot 14+3','13 wekenecho: alleen binnen de IMITAS-studie','Gratis voor deelnemers'],['Week 12–24','Controle elke 4–6 weken','—'],['Week 18–21','20 wekenecho (keuze)','Gratis'],['Vanaf week 22','Kinkhoestprik (22 wekenprik), griepprik in het griepseizoen','Gratis'],['Week 24–32','Controle elke 3 weken','—'],['Week 27 en 30','Extra bloedonderzoek en anti-D-injectie, alleen bij resus-negatieve moeders als dat nodig is','—'],['Vóór de geboorte','Erkenning als jullie niet getrouwd zijn','Gratis'],['Ca. 2 maanden vóór de datum','Intakegesprek van de kraamzorgorganisatie','—'],['Week 32–37, daarna wekelijks','Controle elke 2 weken, vanaf week 37 elke week','—']],['Week','Wat gebeurt er','Kosten'])
+'<p>In totaal heb je <strong>minimaal 13 afspraken</strong> tijdens de zwangerschap, volgens de site van de verloskundigen (KNOV). De keuzeonderzoeken (NIPT, 13 en 20 wekenecho) zijn jouw beslissing: de verloskundige legt uit, maar beslist niet voor je.</p>'
+'<h2 id="screening">Echo’s en screening: wat wordt vergoed in 2026?</h2>'
+T([['Termijnecho (10–14 weken)','Basisverzekering'],['Extra echo’s op medische indicatie','Basisverzekering'],['Counselinggesprek over screening','Bevolkingsonderzoek (gratis)'],['NIPT zonder medische indicatie','Bevolkingsonderzoek: gratis'],['NIPT met medische indicatie','Basisverzekering'],['13 wekenecho','Gratis, maar alleen binnen de IMITAS-studie'],['20 wekenecho','Gratis als je echoscopist een overeenkomst heeft met een Regionaal Centrum voor prenatale screening'],['Vervolgonderzoek na een afwijkende uitslag (bijv. vruchtwaterpunctie)','Basisverzekering; je betaalt mogelijk (een deel van) je eigen risico'],['Pretecho (3D/4D, zonder medisch doel)','Niet vergoed: zelf betalen']],['Onderzoek','Wie betaalt'])
+'<ul><li><strong>NIPT</strong>: een bloedtest op chromosoomafwijkingen, mogelijk vanaf <strong>10 weken</strong>; de uitslag komt binnen <strong>10 dagen</strong>.</li><li><strong>13 wekenecho</strong>: volgens PNS.nl kun je hier in Nederland “alleen kiezen voor de 13 wekenecho als je meedoet aan de wetenschappelijke IMITAS studie”. De echo is tussen 12+3 en 14+3 weken. Vraag je verloskundige of zij meedoet.</li><li><strong>20 wekenecho</strong>: onderzoekt lichamelijke afwijkingen, met meer detail dan bij 13 weken. Soms is het geslacht te zien, maar dat is niet het doel.</li><li>Officiële informatie over al deze onderzoeken staat <strong>ook in het Arabisch</strong> op <strong>PNS.nl</strong> (Information in multiple languages).</li></ul>'
+'<h2 id="birth">Waar bevallen: thuis, ziekenhuis of geboortecentrum</h2>'
+T([['Thuis (thuisbevalling) met de verloskundige','Geen eigen bijdrage'],['Ziekenhuis op medische indicatie (gynaecoloog)','Geen eigen bijdrage'],['Poliklinisch in ziekenhuis of geboortecentrum zonder medische indicatie','Minimaal € 22,50 per dag voor de moeder + € 22,50 per baby; afhankelijk van de instelling kan er een bedrag bij komen'],['Partusassistentie door de kraamverzorgende (tot 2 uur na de geboorte van de placenta)','Geen eigen bijdrage']],['Plaats','Eigen bijdrage 2026'])
+'<p>Bij een poliklinische bevalling zonder medische indicatie mag de instelling maximaal <strong>€ 323 per dag</strong> declareren (€ 161,50 voor de moeder en € 161,50 voor de baby). Daar gaat de eigen bijdrage nog af, dus de zorgverzekeraar vergoedt maximaal <strong>€ 278</strong>. Is het tarief hoger, dan betaal je ook het verschil. <strong>Vraag het dagtarief vooraf</strong> aan het ziekenhuis of geboortecentrum en kijk of je aanvullende verzekering iets vergoedt.</p><p>Veel vrouwen bevallen in Nederland thuis; dat is hier normaal en geen teken van minder zorg. Verandert de situatie tijdens de bevalling, dan stuurt de verloskundige je door naar het ziekenhuis en is er alsnog een medische indicatie.</p>'
+'<h2 id="kraamzorg">Kraamzorg</h2><p>De <strong>kraamverzorgende</strong> komt na de bevalling bij je thuis: zij controleert jou en de baby, helpt met (borst)voeding, leert je de baby verzorgen en meldt problemen aan de verloskundige.</p><ol><li><strong>Meld je aan vanaf week 12</strong> bij een kraamzorgorganisatie (vraag je zorgverzekeraar welke organisaties gecontracteerd zijn). Vroeg aanmelden geeft zekerheid over een plek.</li><li><strong>Intakegesprek</strong> ongeveer 2 maanden vóór de uitgerekende datum: afspraken over de situatie thuis.</li><li><strong>Aantal uren:</strong> minimaal <strong>24</strong> en maximaal <strong>80 uur</strong>, volgens het Landelijk Indicatieprotocol Kraamzorg. De kraamverzorgende en de verloskundige bepalen na de bevalling het definitieve aantal, afhankelijk van onder meer voeding, complicaties en ziekenhuisopname.</li><li><strong>Duur:</strong> meestal tot en met <strong>dag 8</strong> na de bevalling, soms tot <strong>dag 10</strong> of langer op medische indicatie. Wettelijk heb je recht tot 6 weken na de bevalling.</li><li><strong>Eigen bijdrage:</strong> <strong>€ 5,70 per uur</strong> kraamzorg thuis (2026). Voor kraamzorg in het ziekenhuis betaal je <strong>geen</strong> eigen bijdrage. Kraamzorg valt <strong>niet onder het verplichte eigen risico</strong>.</li><li><strong>Kraampakket:</strong> vraag je zorgverzekeraar of je een kraampakket krijgt; dat verschilt per polis.</li></ol>'
+'<h2 id="costs">Kosten: wie betaalt wat?</h2>'
+T([['Verloskundige zorg en bevalling','Basisverzekering','Valt niet onder eigen risico'],['Bevolkingsonderzoeken (NIPT, 20 wekenecho, hielprik, gehoortest)','Overheid','Gratis'],['Kraamzorg thuis','Basisverzekering','€ 5,70 per uur'],['Poliklinisch zonder medische indicatie','Basisverzekering tot een maximum','Min. € 22,50/dag moeder en € 22,50 per baby + verschil bij hoger tarief'],['Medicijnen, vervoer, sommige laboratoriumonderzoeken','Basisverzekering','Kan onder eigen risico vallen'],['Kinkhoest- en griepprik voor zwangeren','Rijksvaccinatieprogramma','Gratis'],['Pretecho','Jijzelf','Niet vergoed'],['Basisverzekering kind tot 18','Basisverzekering','Geen premie en geen eigen risico']],['Onderdeel','Wie betaalt','Wat betaal jij'])
+'<h2 id="examples">Rekenvoorbeelden</h2>'
+T([['Kraamzorg thuis 24 uur (minimum)','24 × € 5,70 = <strong>€ 136,80</strong>'],['Kraamzorg 32 uur (voorbeeld Zorginstituut)','32 × € 5,70 = <strong>€ 182,40</strong>'],['Kraamzorg 80 uur (maximum)','80 × € 5,70 = <strong>€ 456</strong>'],['Thuisbevalling en daarna 32 uur kraamzorg','Bevalling € 0 + kraamzorg <strong>€ 182,40</strong>'],['Poliklinisch zonder indicatie, 1 dag, 1 baby','€ 22,50 + € 22,50 = <strong>minimaal € 45</strong> + verschil bij hoger tarief'],['Idem met een tweeling, 1 dag','€ 22,50 + 2 × € 22,50 = <strong>minimaal € 67,50</strong>'],['Ziekenhuisbevalling op indicatie, kraamzorg in het ziekenhuis','Bevalling € 0 + kraamzorg in ziekenhuis € 0; je betaalt alleen de kraamzorguren thuis daarna']],['Situatie','Berekening'])
+'<p>Illustratief, geen echte personen. Het voorbeeld van 32 uur komt van de site van Zorginstituut Nederland. We rekenen geen bedrag uit voor het tarief van een specifieke instelling, omdat dat verschilt; vraag het na.</p>'
+'<h2 id="aangifte">Aangifte van de geboorte</h2><ul><li><strong>Termijn: binnen 3 dagen na de geboorte</strong>; de geboortedag telt niet mee. Eindigt de termijn op een zaterdag, zondag of officiële feestdag, dan krijg je 1 werkdag extra. Je hebt altijd <strong>minimaal 2 werkdagen</strong>.</li><li><strong>Waar?</strong> In de gemeente <strong>waar het kind is geboren</strong> (dat kan een andere gemeente zijn dan waar je woont, bijvoorbeeld bij een ziekenhuis in een andere stad). In sommige gemeenten kan het <strong>online</strong>, alleen door de vader of moeder.</li><li><strong>Wie?</strong> De <strong>vader of duomoeder is verplicht</strong> aangifte te doen. De moeder uit wie het kind is geboren mag het doen, maar hoeft niet. Kan geen van hen, dan doet iemand die bij de geboorte was, de eigenaar van het huis of een medewerker van het ziekenhuis het.</li><li><strong>Meenemen:</strong> een geldig identiteitsbewijs, en de akte van erkenning of naamskeuze als je die hebt. De baby hoeft niet mee.</li><li><strong>Te laat?</strong> De ambtenaar van de burgerlijke stand meldt dit aan het Openbaar Ministerie; je kunt een boete krijgen.</li><li>Na de aangifte volgt de <strong>geboorteakte</strong>, wordt je kind ingeschreven in de BRP en krijgt het een <strong>BSN</strong>, nodig voor de zorgverzekering en toeslagen. Snel aangifte doen is ook belangrijk omdat de hielprik zo op gang komt.</li></ul>'
+T([['maandag','donderdag'],['dinsdag','vrijdag'],['woensdag','maandag'],['donderdag','maandag'],['vrijdag','dinsdag'],['vrijdag (en maandag is een feestdag)','woensdag'],['zaterdag','dinsdag'],['zondag','woensdag']],['Kind geboren op','Uiterlijk aangifte doen op'])
+'<h2 id="erkenning">Niet getrouwd? Erkenning van het kind</h2><p>Zijn de ouders <strong>getrouwd of geregistreerd partners</strong>, dan is de echtgenoot automatisch juridisch vader (voor een duomoeder gelden aparte regels). <strong>Zijn jullie niet getrouwd</strong>, dan ontstaat er pas een juridische band tussen vader en kind door erkenning.</p><ol><li><strong>Het beste moment: tijdens de zwangerschap</strong> (erkenning van de ongeboren vrucht), in <strong>elke gemeente</strong> van Nederland. Dan is de vader vanaf de geboorte juridisch ouder.</li><li>Is de moeder er niet bij, dan is haar <strong>schriftelijke toestemming</strong> nodig.</li><li>De akte van erkenning is <strong>gratis</strong>; afschriften kosten geld.</li><li>Erkennen kan ook bij de geboorteaangifte of later (vanaf 12 jaar is toestemming van kind en moeder nodig, vanaf 16 alleen van het kind).</li><li><strong>Heb je een buitenlandse nationaliteit</strong>, vraag de gemeente dan ruim op tijd welke documenten nodig zijn; dat kan tijd kosten.</li></ol><p><strong>Gevolgen van erkenning:</strong> een juridische band tussen vader en kind; sinds 2023 krijg je bij erkenning automatisch <strong>gezamenlijk gezag</strong> met de moeder (met uitzonderingen); onderhoudsplicht tot <strong>21 jaar</strong>; wederzijds erfrecht; en bij de erkenning kies je samen de <strong>achternaam</strong>.</p>'
+'<h2 id="newborn">Na de geboorte: screening, verzekering en vaccinaties</h2><ul><li><strong>Hielprik</strong>: in de <strong>eerste week</strong> komt een medewerker van de jeugdgezondheidszorg (JGZ) bij je thuis om een paar druppels bloed uit de hiel te nemen, om zeldzame ernstige ziekten op te sporen. <strong>Gratis</strong> en vrijwillig; de uitslag is binnen <strong>5 weken</strong> bekend.</li><li><strong>Gehoortest</strong>: in de <strong>eerste maand</strong>, door een deskundige medewerker van het consultatiebureau. Doet geen pijn en is <strong>gratis</strong>; vervolgonderzoek vergoedt de zorgverzekeraar.</li><li><strong>Zorgverzekering</strong>: schrijf je kind <strong>binnen 4 maanden</strong> na de geboorte in bij een zorgverzekeraar. Tot 18 jaar geen premie en geen eigen risico. Zie <a href="/nl/articles/health-insurance-newcomers.html">Zorgverzekering voor nieuwkomers</a>.</li><li><strong>Consultatiebureau / JGZ</strong>: volgt de groei en ontwikkeling van je kind en geeft gratis de vaccinaties van het <strong>Rijksvaccinatieprogramma</strong>.</li><li><strong>Vaccinaties</strong>: heb je tijdens de zwangerschap de kinkhoestprik gehad (vanaf week 22), dan is je baby vanaf dag 1 beschermd en krijgt hij de eerste DKTP-Hib-HepB-prik op <strong>3 maanden</strong> in plaats van op <strong>2 maanden</strong>. Een afspraak voor de prik maak je bij de JGZ; je kunt hem halen op het consultatiebureau.</li></ul>'
+'<h2 id="money">Verlof en geld</h2><ul><li><strong>Zwangerschaps- en bevallingsverlof en geboorteverlof</strong>: alles in <a href="/nl/articles/birth-parental-leave.html">Zwangerschaps-, geboorte- en ouderschapsverlof</a>.</li><li><strong>Kinderbijslag</strong> van de SVB: <a href="/nl/articles/kinderbijslag-guide.html">Kinderbijslag-gids</a>.</li><li><strong>Kindgebonden budget</strong>: <a href="/nl/articles/kindgebonden-budget-guide.html">de gids</a>.</li><li><strong>Heb je toeslagen?</strong> Geef de geboorte en inkomenswijzigingen door: <a href="/nl/articles/toeslagen-income-update.html">Inkomen doorgeven bij toeslagen</a>.</li><li><strong>Later kinderopvang</strong>: <a href="/nl/articles/childcare-allowance-kinderopvangtoeslag.html">Kinderopvangtoeslag</a>.</li></ul>'
+'<h2 id="steps">Stap voor stap: wat doe je wanneer</h2><ol><li><strong>Positieve test</strong>: meld je aan bij een verloskundigenpraktijk en controleer of je zorgverzekering loopt en je een huisarts hebt (<a href="/nl/articles/huisarts-registration.html">Inschrijven bij de huisarts</a>).</li><li><strong>Vóór week 10</strong>: beslis met de verloskundige of je de NIPT wilt.</li><li><strong>Vanaf week 12</strong>: kraamzorg regelen.</li><li><strong>Niet getrouwd</strong>: maak een afspraak bij de gemeente voor erkenning vóór de geboorte.</li><li><strong>Werk je</strong>: plan je zwangerschapsverlof en meld het op tijd bij je werkgever.</li><li><strong>Vóór de bevalling</strong>: ziekenhuistas klaarzetten, het bed op klossen als de kraamzorg dat vraagt, het nummer van de verloskundige opslaan.</li><li><strong>Binnen 3 dagen na de geboorte</strong>: aangifte bij de gemeente.</li><li><strong>Binnen 4 maanden</strong>: baby verzekeren.</li><li><strong>Daarna</strong>: kinderbijslag, toeslagen bijwerken en afspraken op het consultatiebureau.</li></ol>'
+'<h2 id="mistakes">Veelgemaakte fouten</h2><ol><li><strong>Kraamzorg te laat regelen</strong>, pas in de laatste maand; meld je aan vanaf week 12.</li><li><strong>Denken dat de 13 wekenecho voor iedereen is</strong>; in 2026 alleen binnen de IMITAS-studie.</li><li><strong>Zonder indicatie in het ziekenhuis bevallen</strong> zonder het dagtarief en de eigen bijdrage na te vragen.</li><li><strong>Geen erkenning regelen</strong> als je in Nederland juridisch niet getrouwd bent (alleen religieus getrouwd of een niet-geregistreerd huwelijk). Vraag de gemeente of je buitenlandse huwelijk is ingeschreven.</li><li><strong>Te laat aangifte doen</strong> (meer dan 3 dagen): kans op een boete en vertraging van de hielprik.</li><li><strong>Vergeten de baby te verzekeren</strong> binnen 4 maanden.</li><li><strong>Familie laten tolken</strong> bij belangrijke medische gesprekken; vraag naar een professionele tolk.</li><li><strong>Een commerciële pretecho</strong> zien als vervanging van de medische echo; dat is het niet.</li></ol>'
+'<h2 id="help">Waar vind je gratis hulp?</h2><ul><li><strong>Je verloskundige</strong>: eerste aanspreekpunt, 24/7 bereikbaar bij spoed.</li><li><strong>PNS.nl</strong> (RIVM): uitleg over screening tijdens de zwangerschap en na de geboorte, <strong>ook in het Arabisch</strong>.</li><li><strong>Consultatiebureau (JGZ)</strong>: vragen over voeding, groei en vaccinaties, gratis.</li><li><strong>Je zorgverzekeraar</strong>: gecontracteerde kraamzorgorganisaties, kraampakket en aanvullende dekking.</li><li><strong>De gemeente</strong>: aangifte en erkenning.</li><li><strong>Taal</strong>: vraag de verloskundige of het ziekenhuis om een <strong>professionele tolk</strong> bij belangrijke gesprekken. Of dat gratis is, verschilt per zorgverlener; vraag het vooraf.</li></ul>'
+'<h2 id="related">Gerelateerde gidsen</h2><ul><li><a href="/nl/articles/birth-parental-leave.html">Zwangerschaps-, geboorte- en ouderschapsverlof</a></li><li><a href="/nl/articles/kinderbijslag-guide.html">Kinderbijslag</a></li><li><a href="/nl/articles/kindgebonden-budget-guide.html">Kindgebonden budget</a></li><li><a href="/nl/articles/health-insurance-newcomers.html">Zorgverzekering voor nieuwkomers</a></li><li><a href="/nl/articles/huisarts-registration.html">Inschrijven bij de huisarts</a></li><li><a href="/nl/articles/bsn-municipality-registration.html">BSN en inschrijving bij de gemeente</a></li></ul>'),
faq=[('Wanneer bel ik de verloskundige?','Zodra je zwangerschapstest positief is. De eerste afspraak is meestal rond 8 weken; je kiest zelf een praktijk.'),
('Is de NIPT gratis in 2026?','Ja, de NIPT en het counselinggesprek zijn gratis. De test kan vanaf 10 weken. Vervolgonderzoek na een afwijkende uitslag valt onder de basisverzekering; daarvoor kun je eigen risico betalen.'),
('Bestaat de 13 wekenecho nog?','In 2026 alleen als je meedoet aan de wetenschappelijke IMITAS-studie; dan is hij gratis.'),
('Is de 20 wekenecho gratis?','Ja, de overheid betaalt als je echoscopist een overeenkomst heeft met een Regionaal Centrum voor prenatale screening.'),
('Wat kost kraamzorg?','€ 5,70 per uur thuis in 2026, voor 24 tot 80 uur. In het ziekenhuis geen eigen bijdrage, en kraamzorg valt niet onder het eigen risico.'),
('Valt zwangerschapszorg onder het eigen risico?','Nee, verloskundige zorg, kraamzorg en de bevolkingsonderzoeken niet. Medicijnen, vervoer en sommige laboratoriumonderzoeken kunnen er wel onder vallen.'),
('Wat betaal ik bij een poliklinische bevalling zonder indicatie?','Minimaal € 22,50 per dag voor de moeder en € 22,50 per baby, plus het verschil als het tarief van de instelling boven het maximum ligt.'),
('Wanneer moet ik aangifte doen?','Binnen 3 dagen na de geboorte in de gemeente waar het kind is geboren; de geboortedag telt niet mee. De vader of duomoeder is verplicht.'),
('We zijn niet getrouwd. Wat moeten we doen?','Erken het kind tijdens de zwangerschap in een willekeurige gemeente, gratis. Is de moeder er niet bij, dan is haar schriftelijke toestemming nodig.'),
('Wanneer moet ik mijn baby verzekeren?','Binnen 4 maanden na de geboorte. Tot 18 jaar betaal je geen premie en geldt geen eigen risico.')],
src_note='Gecontroleerd bij Zorginstituut Nederland, Rijksoverheid, PNS.nl (RIVM), Rijksvaccinatieprogramma en De Verloskundige (KNOV) op 7 oktober 2026. Bedragen gelden voor 2026. De duur van het zwangerschapsverlof en de bedragen van toeslagen staan in de gerelateerde gidsen. Geen bedrag genoemd voor het tarief van een specifieke instelling, omdat dat verschilt. Voorbeelden illustratief.')
