from a_student_finance import T
SLUG='prinsjesdag-2026-changes'
R='https://www.rijksoverheid.nl/'
SRC=[('Rijksoverheid · Prinsjesdag','https://www.rijksoverheid.nl/themas/overheid-en-democratie/prinsjesdag'),
('Rijksoverheid · Koopkracht (Prinsjesdag 2026)',R+'themas/overheid-en-democratie/prinsjesdag/koopkracht'),
('Rijksoverheid · Prinsjesdag 2026: maatregelen op het gebied van SZW',R+'actueel/nieuws/2026/09/15/prinsjesdag-2026-maatregelen-op-het-gebied-van-szw'),
('Rijksoverheid · Kabinet zet in op gezondheid en zorg (15-9-2026)',R+'actueel/nieuws/2026/09/15/kabinet-zet-in-op-gezondheid-en-op-zorg-die-klaar-is-voor-de-toekomst'),
('Rijksoverheid · Fiscale sleuteltabel 2027',R+'documenten/2026/09/15/fiscale-sleuteltabel-2027'),
('Eerste Kamer · Gecorrigeerde fiscale sleuteltabel 2027 (18-9-2026)','https://www.eerstekamer.nl/overig/20260918/fiscale_sleuteltabel_2027/document'),
('Rijksoverheid · Factsheetbundel Belastingplan 2027',R+'documenten/2026/09/15/factsheetbundel'),
('Rijksoverheid · Belastingplan',R+'themas/belastingen-uitkeringen-en-toeslagen/belastingplan'),
('Eerste Kamer · Wetsvoorstel 37 022 Belastingplan 2027','https://www.eerstekamer.nl/wetsvoorstel/37022_belastingplan_2027'),
('Rijksoverheid · Salderingsregeling',R+'themas/klimaat-milieu-en-natuur/energie-thuis/salderingsregeling'),
('Rijksoverheid · Noodfonds Energie gaat open (29-9-2026)',R+'actueel/nieuws/2026/09/29/noodfonds-energie-gaat-open')]

AR=dict(title='Prinsjesdag 2026: ما الذي يتغير لك في 2027؟ الضرائب، البدلات، التأمين الصحي، الطاقة — مع حالة كل قرار',
crumb='Prinsjesdag 2026',
desc='شرح عميق لخطط ميزانية 2027 التي قُدّمت في Prinsjesdag (15 سبتمبر 2026): القدرة الشرائية، شرائح الضريبة والخصومات، بدل الرعاية وبدل الأطفال وبدل الحضانة، المخاطرة الذاتية 400 يورو، ضريبة الطاقة ونهاية المقاصة، وما الذي لا يزال مقترحاً ينتظر البرلمان.',
summary='<ol><li><strong>Prinsjesdag كان في 15 سبتمبر 2026</strong>، وقدّمت حكومة Jetten (D66 وVVD وCDA) ميزانية 2027 وخطة الضرائب 2027.</li><li><strong>معظم ما ستقرأه «مقترح»</strong> (voorstel): يصبح قانوناً فقط بعد موافقة مجلسي البرلمان، عادةً قبل نهاية ديسمبر. لا تبنِ قرارات مالية كبيرة على رقم مقترح.</li><li><strong>القدرة الشرائية 2027 (توقع):</strong> −0.1% للأسرة المتوسطة، +0.2% للدخل المنخفض، +0.3% للمتقاعدين.</li><li><strong>الضريبة:</strong> نسب الشريحتين الأولى والثانية ترتفع قليلاً، وخصم العمل يرتفع 173 يورو.</li><li><strong>الصحة:</strong> المخاطرة الذاتية من 385 إلى <strong>400 يورو</strong> (مقترح)، والقسط المتوقع نحو 169 يورو شهرياً.</li><li><strong>الطاقة:</strong> المقاصة للألواح الشمسية تنتهي <strong>1 يناير 2027</strong> (قانون نافذ)، وصندوق طوارئ الطاقة يفتح للطلبات من 4 يناير 2027.</li></ol>',
body=(
'<h2 id="what">ما هو Prinsjesdag ولماذا يهمك؟</h2><p>في ثالث ثلاثاء من سبتمبر يقدّم وزير المالية «ميزانية الدولة» (Miljoenennota) و«خطة الضرائب» (Belastingplan) للسنة التالية. في 2026 كان ذلك يوم <strong>15 سبتمبر</strong>، وقدّمها الوزير Heinen باسم حكومة <strong>Jetten</strong> التي أدت اليمين في 23 فبراير 2026. ما يُعلن في هذا اليوم يحدد كثيراً من راتبك الصافي وبدلاتك وفواتيرك في السنة التالية.</p><p><strong>أهم قاعدة لقراءة الأخبار:</strong> فرّق بين ثلاث حالات:</p>'
+T([['نافذ (definitief)','قانون أو قرار مقرر مسبقاً. مثال: نهاية المقاصة للألواح الشمسية في 1 يناير 2027.'],
    ['مقترح (voorstel)','خطة الحكومة التي يناقشها البرلمان. قد تتغير الأرقام. مثال: شرائح الضريبة 2027.'],
    ['توقع (verwachting)','تقدير حكومي أو من CPB. مثال: القسط الصحي المتوسط أو القدرة الشرائية.']],
   ['الحالة','ماذا تعني'])
+'<h2 id="koopkracht">القدرة الشرائية في 2027 (توقع)</h2>'
+T([['الأسرة المتوسطة','<strong>−0.1%</strong>'],['الدخل المنخفض','<strong>+0.2%</strong>'],['كبار السن','<strong>+0.3%</strong>']],['الفئة','التغير المتوقع'])
+'<p>تقول الحكومة إن الانخفاض الطفيف يعود لإجراءات الاتفاق الائتلافي (منها ما تسميه «مساهمة الحرية» vrijheidsbijdrage)، والحرب في الشرق الأوسط، وارتفاع الأسعار. ووصفت حزمة القدرة الشرائية بأنها «تعبئة تقنية» ستُناقش مع البرلمان، أي أن تفاصيلها قد تتغير. هذه أرقام متوسطة؛ وضعك الشخصي قد يختلف كثيراً.</p>'
'<h2 id="tax">الضريبة على الدخل 2027 (مقترح)</h2><p>حسب «جدول المفاتيح الضريبي 2027» المنشور يوم Prinsjesdag (نسخة مصححة في 18 سبتمبر):</p>'
+T([['الشريحة 1 (حتى حد الاشتراكات الوطنية 39,247 يورو تقريباً)','35.75%','<strong>36.23%</strong>'],
    ['الشريحة 2 (حتى 78,426 يورو)','37.56%','<strong>38.16%</strong>'],
    ['الشريحة 3 (فوق 78,426 يورو)','49.50%','49.50%'],
    ['الخصم العام (حد أقصى)','3,115 يورو','<strong>3,154 يورو</strong> (يبدأ التناقص من 30,910)'],
    ['خصم العمل (حد أقصى)','5,685 يورو','<strong>5,929 يورو</strong> (+173 يورو)']],
   ['البند','2026','2027 (مقترح)'])
+'<ul><li><strong>حد الشريحة العليا مجمّد</strong> عند 78,426 يورو (لا يُرفع مع التضخم)، وتعديل الجداول مع التضخم يُطبق جزئياً فقط (48%) كجزء من «مساهمة الحرية». النتيجة: جزء من زيادة راتبك قد يذهب لضريبة أعلى.</li><li><strong>بدل السفر المعفى من الضريبة</strong> يرتفع من 0.23 إلى <strong>0.25 يورو لكل كم</strong>، بأثر رجعي من 1 يناير 2026 (مقترح).</li><li><strong>خصم المصاريف الطبية الخاصة</strong> (aftrek specifieke zorgkosten) يُلغى من <strong>1 يناير 2028</strong>، مع تخصيص 350 مليون يورو سنوياً للمرضى المزمنين (مقترح).</li><li>خصم كبار السن (ouderenkorting) ينخفض 100 يورو إلى 1,993 يورو (مقترح).</li></ul><p>اقرأ كيف تظهر هذه الخصومات في راتبك في <a href="/articles/dutch-payslip-explained.html">دليل قسيمة الراتب</a>.</p>'
'<h2 id="toeslagen">البدلات (Toeslagen) 2027</h2>'
+T([['بدل الرعاية الصحية (zorgtoeslag)','الحد الأقصى للشخص الوحيد يُتوقع أن يرتفع إلى <strong>140 يورو شهرياً</strong> (2026: 129 يورو).','توقع'],
    ['بدل الحضانة (kinderopvangtoeslag)','يرتفع مقارنة بـ2026 لكن أقل مما خطط الاتفاق الائتلافي. مثال حكومي: أسرة بطفلين ودخل ضعف المتوسط و2 يوم حضانة تحصل على نحو <strong>700 يورو أكثر</strong> في السنة.','مقترح'],
    ['ميزانية الأطفال (kindgebonden budget)','تخفيف «نقطة الانكسار الثانية» المخططة: نسبة التناقص 9.95% في 2027 و12.8% من 2028 (قانون قيد النقاش).','مقترح'],
    ['بدل الإيجار (huurtoeslag)','لم نجد تغييرات في القواعد لعام 2027، فقط الميزانية (6.7 مليار يورو).','—']],
   ['البدل','ما أُعلن','الحالة'])
+'<p>المبالغ النهائية لكل بدل تنشرها Belastingdienst عادةً في نهاية السنة. وتذكّر: البدل يُحسب على دخلك السنوي، فحدّث تقديرك عند أي تغيير (<a href="/articles/toeslagen-income-update.html">كيف تحدّث دخلك</a>).</p>'
'<h2 id="zorg">الصحة والتأمين الصحي</h2><ul><li><strong>المخاطرة الذاتية الإلزامية (eigen risico):</strong> من 385 إلى <strong>400 يورو</strong> في 2027 «مع التضخم» (مقترح). الزيادة الأكبر (60 يورو إضافية) أُجّلت إلى 2028.</li><li><strong>القسط الشهري:</strong> تتوقع وزارة الصحة زيادة 12.50 يورو إلى متوسط <strong>169 يورو شهرياً</strong>. شركات التأمين تعلن أقساطها حتى <strong>12 نوفمبر</strong>.</li><li><strong>المساهمة الذاتية في الأدوية</strong> تبقى بحد أقصى 250 يورو سنوياً.</li></ul><p>التفاصيل وكيف تختار وتبدّل قبل 31 ديسمبر في <a href="/articles/health-insurance-2027.html">دليل التأمين الصحي 2027</a>.</p>'
'<h2 id="energy">الطاقة والماء والوقود</h2>'
+T([['نهاية المقاصة (salderingsregeling)','من <strong>1 يناير 2027</strong> لم تعد الكهرباء التي تردّها ألواحك تُخصم من استهلاكك، بل تحصل على تعويض (لا يقل حتى 2030 عن 50% من سعر التوريد الصافي).','نافذ بقانون'],
    ['ضريبة الطاقة 2027','كهرباء: 8.80 سنت/كيلوواط ساعة (2026: 9.161)؛ غاز: 61.63 سنت/م³ (2026: 60.066)؛ الخصم السنوي لكل اتصال 519.58 يورو. (كلها بدون ضريبة القيمة المضافة)','مقترح'],
    ['ضريبة ماء الصنبور','من 0.437 إلى <strong>0.537 يورو/م³</strong>، نحو 15 يورو سنوياً للأسرة المتوسطة.','مقترح'],
    ['تخفيض ضريبة الوقود','يُمدد خلال 2027 ثم يُلغى تدريجياً بشكل أبطأ.','مقترح'],
    ['صندوق طوارئ الطاقة (Noodfonds Energie)','193 مليون يورو لهذا الشتاء. التحضير والتواصل من 1 ديسمبر 2026، والطلبات من <strong>4 يناير حتى 7 مايو 2027</strong>، دون مبدأ «من يسبق».','مقرر']],
   ['الإجراء','التفاصيل','الحالة'])
+'<p>للتوفير واختيار العقد المناسب: <a href="/articles/energy-contracts-saving-2026.html">دليل عقود الطاقة</a>.</p>'
'<h2 id="work">العمل والإعانات والتقاعد</h2><ul><li><strong>أُلغي</strong> الربط الكامل (1 مقابل 1) بين سن التقاعد AOW ومتوسط العمر.</li><li><strong>أُلغي</strong> مقترح خفض الحد الأقصى لأجر الإعانة اليومي بنسبة 20%.</li><li>تقصير إعانة البطالة WW (من 24 إلى 12 شهراً) <strong>أُجّل</strong>؛ تذكر وزارة الشؤون الاجتماعية 1 يناير 2029.</li><li>الحد الأدنى للأجر والإعانات والـkinderbijslag لعام 2027: تُعلن مبالغها عادة في نوفمبر–ديسمبر، ولم تُنشر بعد (<a href="/articles/minimum-wage-netherlands.html">الحد الأدنى للأجر</a>).</li></ul>'
'<h2 id="other">إجراءات أخرى</h2><ul><li><strong>ضريبة المدخرات (box 3):</strong> قانون «العائد الحقيقي» كان مخططاً لـ1 يناير 2028، لكن الحكومة طلبت من مجلس الشيوخ في 15 سبتمبر تأجيل التصويت، وستقترح إجراءات جديدة لاحقاً. نسبة box 3 في 2027: 36%.</li><li><strong>ضريبة نقل الملكية</strong> للمنازل التي لا يسكنها مالكها (المستثمرون): من 8% إلى 7%؛ وللسكن الشخصي تبقى 2% (مقترح).</li><li><strong>ضريبة القيمة المضافة:</strong> لا تغيير في 21% و9%.</li><li><strong>منحة الطلاب</strong> للساكنين خارج بيت الأهل: +50 يورو شهرياً، لكن من السنة الدراسية <strong>2028–2029</strong> وليس 2027 (<a href="/articles/student-finance.html">دليل منحة الدراسة</a>).</li></ul>'
'<h2 id="status">متى تصبح هذه الخطط قانوناً؟</h2><ol><li>15 سبتمبر 2026: تقديم Belastingplan 2027 (رقم 37 022) مع ثلاثة قوانين ضريبية أخرى.</li><li>الآن (أكتوبر): المناقشة المكتوبة في مجلس النواب (Tweede Kamer).</li><li>عادةً في نوفمبر: تصويت مجلس النواب، ثم مجلس الشيوخ (Eerste Kamer) في ديسمبر.</li><li>1 يناير 2027: بدء التطبيق، وبعض الأجزاء بأثر رجعي إلى 2026.</li></ol><p>سنحدّث هذا الدليل بعد التصويت النهائي. حتى ذلك الحين اعتبر كل رقم «مقترح» قابلاً للتغيير.</p>'
'<h2 id="todo">ماذا تفعل الآن؟ قائمة عملية</h2><ol><li><strong>نوفمبر:</strong> قارن أقساط التأمين الصحي بعد 12 نوفمبر، وبدّل قبل 31 ديسمبر إن وجدت الأفضل.</li><li><strong>إن كانت لديك ألواح شمسية:</strong> افحص عقد الطاقة لما بعد 1 يناير 2027 (تكاليف الإرجاع والتعويض).</li><li><strong>إن كانت فاتورة الطاقة عالية ودخلك منخفض:</strong> جهّز مستنداتك لصندوق الطوارئ من ديسمبر.</li><li><strong>يناير 2027:</strong> افحص أول قسيمة راتب، وحدّث تقدير دخلك في Toeslagen.</li><li><strong>إن كنت تخصم مصاريف طبية:</strong> ما زال الخصم ممكناً عن 2026 و2027؛ الإلغاء المقترح من 2028.</li></ol>'),
faq=[('هل هذه التغييرات نهائية؟','معظمها مقترحات تحتاج موافقة مجلسي البرلمان، عادة قبل نهاية ديسمبر. نهاية المقاصة للألواح الشمسية في 1 يناير 2027 قانون نافذ.'),
('كم ستكون المخاطرة الذاتية في 2027؟','اقترحت الحكومة 400 يورو (من 385). الزيادة الإضافية 60 يورو أُجّلت إلى 2028.'),
('هل سيزيد راتبي الصافي في 2027؟','يعتمد على وضعك. التوقع للأسرة المتوسطة −0.1% في القدرة الشرائية، وللدخل المنخفض +0.2%. خصم العمل يرتفع، لكن نسب الشريحتين الأولى والثانية ترتفع قليلاً أيضاً.'),
('هل يرتفع بدل الرعاية الصحية؟','يُتوقع أن يصل الحد الأقصى للشخص الوحيد إلى نحو 140 يورو شهرياً في 2027 (129 يورو في 2026).'),
('متى أطلب دعم صندوق الطاقة؟','الطلبات من 4 يناير حتى 7 مايو 2027، ويمكن التحضير من 1 ديسمبر 2026.'),
('هل ستُلغى ضريبة المدخرات الحالية؟','قانون العائد الحقيقي كان مخططاً لـ2028، لكن الحكومة طلبت تأجيل تصويت مجلس الشيوخ وستقترح إجراءات جديدة.')],
src_note='راجعنا كل الأرقام في صفحات Rijksoverheid ووثائق Belastingplan 2027 وملف مجلس الشيوخ في 4 أكتوبر 2026. الأرقام المذكورة «مقترح» قد تتغير بعد تصويت البرلمان؛ سنحدّث الدليل حينها.')

NL=dict(title='Prinsjesdag 2026: wat verandert er voor jou in 2027? Belasting, toeslagen, zorg en energie — met de status van elke maatregel',
crumb='Prinsjesdag 2026',
desc='Uitgebreide uitleg van de plannen voor 2027 van Prinsjesdag (15 september 2026): koopkracht, schijven en heffingskortingen, zorgtoeslag, kinderopvangtoeslag en kindgebonden budget, eigen risico € 400, energiebelasting en einde salderen, en wat nog door het parlement moet.',
summary='<ol><li><strong>Prinsjesdag was op 15 september 2026</strong>; het kabinet-Jetten (D66, VVD, CDA) presenteerde de Miljoenennota en het Belastingplan 2027.</li><li><strong>Het meeste is een voorstel</strong>: het wordt pas wet na instemming van Tweede en Eerste Kamer, meestal vóór eind december.</li><li><strong>Koopkracht 2027 (verwachting):</strong> −0,1% voor een doorsnee huishouden, +0,2% voor lage inkomens, +0,3% voor ouderen.</li><li><strong>Belasting:</strong> eerste en tweede schijf iets hoger, arbeidskorting +€ 173.</li><li><strong>Zorg:</strong> eigen risico van € 385 naar <strong>€ 400</strong> (voorstel); premie naar verwachting gemiddeld € 169 per maand.</li><li><strong>Energie:</strong> salderen stopt op <strong>1 januari 2027</strong> (wet); Noodfonds Energie open voor aanvragen vanaf 4 januari 2027.</li></ol>',
body=(
'<h2 id="what">Wat is Prinsjesdag en waarom is het belangrijk?</h2><p>Op de derde dinsdag van september presenteert de minister van Financiën de Miljoenennota en het Belastingplan voor het jaar erna. In 2026 was dat op <strong>15 september</strong>, door minister Heinen namens het kabinet-<strong>Jetten</strong> (beëdigd op 23 februari 2026).</p><p><strong>Lees nieuws altijd met deze drie labels:</strong></p>'
+T([['Definitief','Wet of eerder genomen besluit, bijv. einde salderen op 1 januari 2027.'],['Voorstel','Plan van het kabinet dat het parlement nog behandelt, bijv. schijven 2027.'],['Verwachting','Raming van kabinet of CPB, bijv. gemiddelde zorgpremie of koopkracht.']],['Status','Betekenis'])
+'<h2 id="koopkracht">Koopkracht 2027 (verwachting)</h2>'
+T([['Doorsnee huishouden','<strong>−0,1%</strong>'],['Lage inkomens','<strong>+0,2%</strong>'],['Ouderen','<strong>+0,3%</strong>']],['Groep','Verwachte verandering'])
+'<p>Het kabinet noemt als oorzaken onder meer de «vrijheidsbijdrage» uit het coalitieakkoord, de oorlog in het Midden-Oosten en hogere prijzen. Het koopkrachtpakket is volgens het kabinet een «technische invulling» die met de Kamer wordt besproken. Het zijn gemiddelden; jouw situatie kan flink afwijken.</p>'
'<h2 id="tax">Inkomstenbelasting 2027 (voorstel)</h2><p>Volgens de fiscale sleuteltabel 2027 (gecorrigeerde versie 18 september):</p>'
+T([['Schijf 1 (tot circa € 39.247)','35,75%','<strong>36,23%</strong>'],['Schijf 2 (tot € 78.426)','37,56%','<strong>38,16%</strong>'],['Schijf 3 (boven € 78.426)','49,50%','49,50%'],['Algemene heffingskorting (max.)','€ 3.115','<strong>€ 3.154</strong> (afbouw vanaf € 30.910)'],['Arbeidskorting (max.)','€ 5.685','<strong>€ 5.929</strong> (+€ 173)']],['Onderdeel','2026','2027 (voorstel)'])
+'<ul><li>De grens van het toptarief blijft <strong>bevroren</strong> op € 78.426 en de inflatiecorrectie wordt maar voor 48% toegepast (onderdeel van de vrijheidsbijdrage).</li><li><strong>Onbelaste reiskostenvergoeding</strong> van € 0,23 naar <strong>€ 0,25 per km</strong>, met terugwerkende kracht tot 1 januari 2026 (voorstel).</li><li><strong>Aftrek specifieke zorgkosten</strong> vervalt per <strong>1 januari 2028</strong>; vanaf 2028 € 350 miljoen per jaar voor chronisch zieken (voorstel).</li><li>Ouderenkorting daalt met € 100 naar € 1.993 (voorstel).</li></ul><p>Zie ook <a href="/nl/articles/dutch-payslip-explained.html">je loonstrook uitgelegd</a>.</p>'
'<h2 id="toeslagen">Toeslagen 2027</h2>'
+T([['Zorgtoeslag','Maximum voor alleenstaanden naar verwachting <strong>€ 140 per maand</strong> (2026: € 129).','Verwachting'],['Kinderopvangtoeslag','Hoger dan in 2026, maar minder dan het coalitieakkoord plande. Voorbeeld: gezin met 2 kinderen, 2× modaal, 2 dagen opvang: circa <strong>€ 700 meer</strong> per jaar.','Voorstel'],['Kindgebonden budget','Tweede knikpunt verzacht: afbouw 9,95% in 2027 en 12,8% vanaf 2028 (wetsvoorstel in behandeling).','Voorstel'],['Huurtoeslag','Geen regelwijzigingen voor 2027 gevonden, alleen het budget (€ 6,7 miljard).','—']],['Toeslag','Wat is aangekondigd','Status'])
+'<p>De definitieve bedragen publiceert de Belastingdienst meestal aan het eind van het jaar. Pas je inkomensschatting aan bij elke wijziging (<a href="/nl/articles/toeslagen-income-update.html">inkomen doorgeven</a>).</p>'
'<h2 id="zorg">Zorg en zorgverzekering</h2><ul><li><strong>Verplicht eigen risico:</strong> van € 385 naar <strong>€ 400</strong> in 2027, «mee met de inflatie» (voorstel). De extra verhoging van € 60 is uitgesteld naar 2028.</li><li><strong>Premie:</strong> VWS verwacht +€ 12,50 per maand naar gemiddeld <strong>€ 169 per maand</strong>. Verzekeraars maken hun premies uiterlijk <strong>12 november</strong> bekend.</li><li>De eigen bijdrage voor geneesmiddelen blijft maximaal € 250.</li></ul><p>Meer in de <a href="/nl/articles/health-insurance-2027.html">gids zorgverzekering 2027</a>.</p>'
'<h2 id="energy">Energie, water en brandstof</h2>'
+T([['Einde salderingsregeling','Vanaf <strong>1 januari 2027</strong> geen saldering meer; je krijgt een terugleververgoeding (tot 2030 minimaal 50% van het kale leveringstarief).','Definitief (wet)'],['Energiebelasting 2027','Stroom 8,80 ct/kWh (2026: 9,161); gas 61,63 ct/m³ (2026: 60,066); vermindering € 519,58 per aansluiting (excl. btw).','Voorstel'],['Belasting op leidingwater','Van € 0,437 naar <strong>€ 0,537 per m³</strong>, circa € 15 per jaar voor een gemiddeld gezin.','Voorstel'],['Accijnskorting brandstof','Verlengd in 2027 en daarna langzamer afgebouwd.','Voorstel'],['Noodfonds Energie','€ 193 miljoen deze winter; voorbereiden vanaf 1 december 2026, aanvragen van <strong>4 januari tot en met 7 mei 2027</strong>, geen «op is op».','Besloten']],['Maatregel','Details','Status'])
+'<p>Besparen en kiezen: <a href="/nl/articles/energy-contracts-saving-2026.html">gids energiecontract</a>.</p>'
'<h2 id="work">Werk, uitkeringen en pensioen</h2><ul><li>De één-op-één koppeling van de AOW-leeftijd aan de levensverwachting <strong>vervalt</strong>.</li><li>Het plan om het maximumdagloon met 20% te verlagen <strong>vervalt</strong>.</li><li>De WW-duurverkorting (24 naar 12 maanden) wordt <strong>uitgesteld</strong>; SZW noemt 1 januari 2029.</li><li>Minimumloon, uitkeringen en kinderbijslag per 1 januari 2027 worden meestal in november–december bekendgemaakt (<a href="/nl/articles/minimum-wage-netherlands.html">minimumloon</a>).</li></ul>'
'<h2 id="other">Overige maatregelen</h2><ul><li><strong>Box 3:</strong> de Wet werkelijk rendement was gepland per 1 januari 2028, maar het kabinet vroeg de Eerste Kamer op 15 september de stemming aan te houden. Box 3-tarief 2027: 36%.</li><li><strong>Overdrachtsbelasting</strong> voor niet-eigenaar-bewoners van 8% naar 7%; eigen woning blijft 2% (voorstel).</li><li><strong>Btw:</strong> 21% en 9% blijven gelijk.</li><li><strong>Basisbeurs</strong> uitwonenden +€ 50 per maand, maar pas vanaf studiejaar <strong>2028-2029</strong> (<a href="/nl/articles/student-finance.html">studiefinanciering</a>).</li></ul>'
'<h2 id="status">Wanneer wordt het wet?</h2><ol><li>15 september 2026: Belastingplan 2027 (37 022) ingediend, met drie andere fiscale wetsvoorstellen.</li><li>Nu (oktober): schriftelijke behandeling in de Tweede Kamer.</li><li>Meestal november: stemming Tweede Kamer; december: Eerste Kamer.</li><li>1 januari 2027: inwerkingtreding, deels met terugwerkende kracht tot 2026.</li></ol>'
'<h2 id="todo">Wat kun je nu doen?</h2><ol><li><strong>November:</strong> vergelijk zorgpremies na 12 november en stap vóór 31 december over als dat loont.</li><li><strong>Zonnepanelen:</strong> controleer je energiecontract voor na 1 januari 2027 (terugleverkosten en -vergoeding).</li><li><strong>Hoge energierekening en laag inkomen:</strong> bereid vanaf december je aanvraag voor het Noodfonds voor.</li><li><strong>Januari 2027:</strong> controleer je eerste loonstrook en je inkomensschatting bij Toeslagen.</li><li><strong>Zorgkostenaftrek:</strong> nog mogelijk over 2026 en 2027; vervalt volgens het voorstel per 2028.</li></ol>'),
faq=[('Zijn deze wijzigingen definitief?','Meestal niet: het zijn voorstellen die Tweede en Eerste Kamer nog moeten aannemen, meestal vóór eind december. Het einde van salderen op 1 januari 2027 is al wet.'),
('Hoe hoog wordt het eigen risico in 2027?','Het kabinet stelt € 400 voor (van € 385). De extra € 60 is uitgesteld naar 2028.'),
('Ga ik er netto op vooruit in 2027?','Dat hangt af van je situatie. Verwachting: −0,1% voor een doorsnee huishouden, +0,2% voor lage inkomens.'),
('Gaat de zorgtoeslag omhoog?','Het maximum voor alleenstaanden gaat naar verwachting naar circa € 140 per maand (2026: € 129).'),
('Wanneer kan ik het Noodfonds Energie aanvragen?','Van 4 januari tot en met 7 mei 2027; voorbereiden kan vanaf 1 december 2026.'),
('Verdwijnt het huidige box 3-stelsel?','De Wet werkelijk rendement was gepland voor 2028, maar het kabinet vroeg de Eerste Kamer de stemming aan te houden en komt met nieuwe maatregelen.')],
src_note='Alle bedragen gecontroleerd op Rijksoverheid, in de stukken van het Belastingplan 2027 en het dossier van de Eerste Kamer op 4 oktober 2026. Bedragen met het label «voorstel» kunnen na de stemming veranderen; we werken deze gids dan bij.')
