from a_student_finance import T
SLUG='debt-help-schuldhulp'
SRC=[('Wetten.overheid.nl · Wet gemeentelijke schuldhulpverlening','https://wetten.overheid.nl/BWBR0031331/'),
('Juridisch Loket · Schuldhulpverlening via de gemeente','https://www.juridischloket.nl/schulden-en-incasso/schulden-oplossen/schuldhulpverlening-gemeente/'),
('Juridisch Loket · Wsnp-traject','https://www.juridischloket.nl/schulden-en-incasso/schulden-oplossen/wsnp-traject/'),
('Rijksoverheid · Gemeenten sneller signaleren van schulden','https://www.rijksoverheid.nl/onderwerpen/schulden/gemeenten-sneller-signaleren-van-schulden'),
('Rijksoverheid · Beslagvrije voet controleren','https://www.rijksoverheid.nl/onderwerpen/schulden/vraag-en-antwoord/beslagvrijevoet-controleren'),
('Rijksoverheid · Hoogte incassokosten','https://www.rijksoverheid.nl/vraag-en-antwoord/schulden/hoogte-incassokosten'),
('Belastingdienst · Betalingsregeling','https://www.belastingdienst.nl/wps/wcm/connect/nl/betalenenontvangen/content/betalingsregeling'),
('Dienst Toeslagen · Betalingsregeling','https://www.belastingdienst.nl/wps/wcm/connect/nl/toeslag-terugbetalen/content/kan-ik-een-betalingsregeling-krijgen')]

AR=dict(title='مساعدة الديون المجانية في هولندا 2026: موعد البلدية خلال 4 أسابيع (3 أيام عمل عند الخطر)، المهلة، الحد المحمي من الحجز، التسوية القانونية 18 شهراً، وحدود تكاليف التحصيل',
crumb='مساعدة الديون',
seo_title='مساعدة الديون schuldhulp 2026',
desc='مساعدة الديون (schuldhulp) من البلدية مجانية: موعد خلال 4 أسابيع، أو 3 أيام عمل عند خطر الطرد، مع فترة تنفس 6 أشهر والحد المحمي من الحجز.',
summary='<ol><li><strong>مساعدة الديون من البلدية مجانية</strong> وحق قانوني: موعد أول خلال <strong>4 أسابيع</strong> من طلبك، وخلال <strong>3 أيام عمل</strong> إن كان هناك خطر طرد أو قطع طاقة، وقرار خلال <strong>8 أسابيع</strong> كحد أقصى.</li><li>عند الخطر يمكن طلب <strong>«فترة تنفس» 6 أشهر</strong> لا يستطيع فيها الدائنون اتخاذ إجراءات.</li><li><strong>الحد المحمي من الحجز (beslagvrije voet)</strong> يحمي جزءاً من دخلك للعيش؛ افحصه بالحاسبة الرسمية واعترض خلال 4 أسابيع إن كان خاطئاً.</li><li><strong>التسوية القانونية (Wsnp)</strong> تستغرق <strong>18 شهراً</strong> للتسويات التي بدأت منذ 1 يوليو 2023.</li><li><strong>تكاليف التحصيل لها حد قانوني</strong>: 15% من أول 2,500 يورو، وحد أدنى 40 يورو، ولا رسوم منفصلة للتذكيرات.</li></ol>',
body=(
'<h2 id="first">ابدأ هنا: الخطوات الأولى خلال أسبوع</h2><ol><li><strong>لا تتجاهل الرسائل.</strong> افتح كل الرسائل واجمعها في ملف واحد، واحذر من الرسائل المزيفة التي تطلب الدفع فوراً (<a href="/articles/scams-phishing-netherlands.html">الاحتيال والتصيد</a>).</li><li><strong>اكتب قائمة</strong>: لمن تدين، كم، ومنذ متى، وهل وصلت لمكتب تحصيل أو محضر.</li><li><strong>ادفع الأولويات أولاً</strong>: الإيجار، الطاقة، الماء، التأمين الصحي. هذه تحمي سكنك وصحتك.</li><li><strong>اتصل ببلديتك</strong> واطلب «schuldhulpverlening» (مساعدة الديون)؛ إن كان هناك خطر طرد أو قطع فقل ذلك صراحة.</li><li><strong>لا تأخذ قرضاً جديداً</strong> لسداد قرض قديم.</li></ol>'
'<h2 id="gemeente">حقك في مساعدة البلدية</h2>'
+T([['الموعد الأول','خلال <strong>4 أسابيع</strong> من طلبك'],['خطر الطرد أو قطع الغاز أو الماء أو الكهرباء','خلال <strong>3 أيام عمل</strong>'],['قرار المساعدة','خلال مدة تحددها البلدية، <strong>8 أسابيع كحد أقصى</strong>'],['التكلفة','<strong>مجانية</strong>'],['فترة التنفس (adempauze)','حتى <strong>6 أشهر</strong> عند الخطر، يتوقف فيها الدائنون']],['البند','القانون'])
+'<p>ما قد تقدمه البلدية: ترتيب مع الدائنين (schuldbemiddeling)، «قرض تسوية» يسدد الدائنين دفعة واحدة، أو طلب من المحكمة لإلزام دائن رافض (dwangakkoord). <strong>التسوية الودية</strong> تستغرق عادة سنة ونصف.</p>'
'<h2 id="early">الإنذار المبكر</h2><p>منذ <strong>1 يناير 2021</strong> يبلغ مالكو السكن وشركات الماء والطاقة والتأمين الصحي البلدية عن التأخر في الدفع إن لم تنجح جهودهم. قد تتصل بك البلدية أو تزورك لعرض المساعدة. <strong>هذا ليس عقاباً</strong>؛ اقبل المساعدة مبكراً قبل أن تكبر الديون.</p>'
'<h2 id="beslag">الحد المحمي من الحجز (beslagvrije voet)</h2><ul><li>عند الحجز على راتبك أو إعانتك يجب أن يبقى لك مبلغ للعيش.</li><li>افحص المبلغ بالحاسبة الرسمية <strong>uwbeslagvrijevoet.nl</strong>.</li><li>إن كان خاطئاً: تواصل مع الجهة الحاجزة (العنوان في الرسالة) <strong>خلال 4 أسابيع</strong> إن أمكن.</li><li>لا يُرفع المبلغ تلقائياً عند تغير وضعك (إلا في Bijstand)؛ أبلغ أنت.</li><li>قواعد الحساب تتغير في 2026 بسبب تغييرات بدل الإيجار.</li></ul>'
'<h2 id="wsnp">التسوية القانونية (Wsnp)</h2>'
+T([['متى','عندما تفشل التسوية الودية، بطلب للمحكمة'],['المدة','<strong>18 شهراً</strong> لمن بدأت تسويته منذ 1 يوليو 2023 (3 سنوات لمن قبلها)؛ يمكن للقاضي التقصير أو التمديد حتى 5 سنوات'],['الحياة أثناءها','تعيش بمبلغ محدد، ومدير يدير مالك'],['النهاية','الديون المتبقية تُمسح عادة إن التزمت بالقواعد']],['البند','التفاصيل'])
+'<h2 id="collection">تكاليف التحصيل: ما الحد القانوني؟</h2>'
+T([['أول 2,500 يورو','15%'],['الـ2,500 التالية','10%'],['الـ5,000 التالية','5%'],['الـ190,000 التالية','1%'],['فوق 200,000','0.5%'],['الحد الأدنى','40 يورو']],['من مبلغ الدين','الحد الأقصى للتكاليف'])
+'<p>لا يجوز احتساب تكاليف منفصلة لكل تذكير أو إنذار أو «رسوم إدارية». إن طُلب منك أكثر فاعترض كتابياً واطلب حساباً مفصلاً، واستشر Juridisch Loket.</p>'
'<h2 id="government">ديون للحكومة: خطط الدفع</h2>'
+T([['ضرائب Belastingdienst','خطة عادية حتى <strong>12 شهراً</strong>، 20 يورو شهرياً على الأقل، لدين حتى 100,000 يورو؛ أطول في ظروف خاصة؛ القرار خلال 8 أسابيع؛ تُحسب فائدة التحصيل'],['استرداد البدلات (Toeslagen)','حتى <strong>24 شهراً</strong> تلقائياً بدفع أول قسط في موعده، بفائدة 4.3% منذ 1 يناير 2026؛ أو خطة شخصية إن لم تستطع (<a href="/articles/toeslagen-income-update.html">التفاصيل</a>)'],['غرامات CJIB','اسأل CJIB عن الدفع بالأقساط']],['الجهة','الترتيب'])
+'<h2 id="help">مساعدة مجانية أخرى</h2><ul><li><strong>Juridisch Loket</strong>: نصائح قانونية مجانية (0800 8020)، ومحامٍ بتكلفة مخفّضة عبر <a href="/articles/legal-aid-lawyer-toevoeging.html">الـtoevoeging</a>.</li><li><strong>المستشارون الاجتماعيون</strong> (sociaal raadslieden) في كثير من البلديات.</li><li>متطوعو المساعدة الإدارية في البيت.</li><li>ميزانيتك: افحص أيضاً ما يحق لك من دعم لم تطلبه: <a href="/articles/social-assistance-bijstand.html">Bijstand</a>، <a href="/articles/special-assistance-bijzondere-bijstand.html">المساعدة الخاصة</a>، <a href="/articles/municipal-taxes-exemption-kwijtschelding.html">إعفاء الضرائب البلدية</a>، و<a href="/articles/energy-emergency-fund-2027.html">صندوق طوارئ الطاقة 2027</a>، و<a href="/articles/energy-contracts-saving-2026.html">توفير الطاقة</a>.</li></ul>'
'<h2 id="mistakes">أخطاء شائعة</h2><ol><li>إخفاء الديون عن الشريك أو المساعد؛ الحل يحتاج الصورة كاملة.</li><li>دفع الدائن الأكثر إزعاجاً بدل الأهم (الإيجار والطاقة).</li><li>قبول خطة دفع لا تستطيع الالتزام بها.</li><li>القروض السريعة وشراء «اشترِ الآن وادفع لاحقاً».</li><li>عدم فحص الحد المحمي من الحجز.</li></ol>'),
faq=[('هل مساعدة الديون من البلدية مجانية؟','نعم، مجانية وهي حق قانوني.'),
('متى يجب أن تستقبلني البلدية؟','خلال 4 أسابيع من طلبك، وخلال 3 أيام عمل إن كان هناك خطر طرد أو قطع.'),
('ما هي «فترة التنفس»؟','مهلة حتى 6 أشهر عند الخطر يتوقف فيها الدائنون عن الإجراءات.'),
('كم تستغرق التسوية القانونية؟','18 شهراً لمن بدأت تسويته منذ 1 يوليو 2023.'),
('كم يحق لمكتب التحصيل أن يطلب؟','حسب جدول قانوني: 15% من أول 2,500 يورو، بحد أدنى 40 يورو، ودون رسوم للتذكيرات.'),
('كيف أعرف أن الحجز على راتبي صحيح؟','افحص الحد المحمي من الحجز في uwbeslagvrijevoet.nl واعترض خلال 4 أسابيع إن كان خاطئاً.')],
src_note='راجعنا قانون مساعدة الديون البلدية وJuridisch Loket وRijksoverheid وBelastingdienst في 5 أكتوبر 2026. لم نجد رقماً رسمياً لعدد أشهر التأخير قبل الإنذار المبكر.')

NL=dict(title='Gratis schuldhulp in 2026: gesprek binnen 4 weken (3 werkdagen bij dreiging), adempauze, beslagvrije voet, Wsnp in 18 maanden en maximale incassokosten',
crumb='Schuldhulp',
seo_title='Schuldhulp 2026: gratis hulp van de gemeente',
desc='Gratis schuldhulp van de gemeente: gesprek binnen 4 weken, bij dreigende uitzetting binnen 3 werkdagen. Plus adempauze, beslagvrije voet en Wsnp.',
summary='<ol><li><strong>Schuldhulp van de gemeente is gratis</strong> en een wettelijk recht: eerste gesprek binnen <strong>4 weken</strong>, bij dreigende uitzetting of afsluiting binnen <strong>3 werkdagen</strong>, besluit binnen max. <strong>8 weken</strong>.</li><li>Bij dreiging: <strong>adempauze tot 6 maanden</strong>.</li><li>De <strong>beslagvrije voet</strong> beschermt een deel van je inkomen; controleer en reageer binnen 4 weken.</li><li><strong>Wsnp</strong> duurt <strong>18 maanden</strong> bij start vanaf 1 juli 2023.</li><li><strong>Incassokosten zijn wettelijk gemaximeerd</strong>: 15% over de eerste € 2.500, minimaal € 40, geen aparte kosten voor aanmaningen.</li></ol>',
body=(
'<h2 id="first">Begin hier</h2><ol><li><strong>Negeer geen post</strong>; verzamel alles, maar let op nepberichten die direct betaling eisen (<a href="/nl/articles/scams-phishing-netherlands.html">oplichting en phishing</a>).</li><li><strong>Maak een lijst</strong>: schuldeiser, bedrag, sinds wanneer, incassobureau of deurwaarder?</li><li><strong>Vaste lasten eerst</strong>: huur, energie, water, zorgverzekering.</li><li><strong>Bel de gemeente</strong> voor schuldhulpverlening; noem een dreigende uitzetting of afsluiting.</li><li><strong>Geen nieuwe lening</strong> om oude schulden af te lossen.</li></ol>'
'<h2 id="gemeente">Je recht op schuldhulp</h2>'
+T([['Eerste gesprek','Binnen <strong>4 weken</strong> na je melding'],['Dreigende uitzetting of afsluiting','Binnen <strong>3 werkdagen</strong>'],['Besluit','Binnen een termijn uit de verordening, <strong>max. 8 weken</strong>'],['Kosten','<strong>Gratis</strong>'],['Adempauze','Tot <strong>6 maanden</strong> bij dreiging']],['Onderdeel','Wet'])
+'<p>Mogelijk: schuldbemiddeling, een saneringskrediet of een dwangakkoord via de rechter. Het <strong>minnelijk traject</strong> duurt meestal 1,5 jaar.</p>'
'<h2 id="early">Vroegsignalering</h2><p>Sinds <strong>1 januari 2021</strong> melden verhuurders, drinkwaterbedrijven, energieleveranciers en zorgverzekeraars betalingsachterstanden aan de gemeente als hun eigen inspanningen niet werken. De gemeente kan je benaderen. Dat is hulp, geen straf.</p>'
'<h2 id="beslag">Beslagvrije voet</h2><ul><li>Bij beslag moet je genoeg overhouden om van te leven.</li><li>Controleer met de rekentool op <strong>uwbeslagvrijevoet.nl</strong>.</li><li>Klopt het niet: neem bij voorkeur <strong>binnen 4 weken</strong> contact op met de beslaglegger.</li><li>Bij gewijzigde omstandigheden geen automatische aanpassing (behalve in de bijstand).</li><li>De rekenregels veranderen in 2026 door wijzigingen in de huurtoeslag.</li></ul>'
'<h2 id="wsnp">Wsnp</h2>'
+T([['Wanneer','Als het minnelijk traject mislukt, via de rechter'],['Duur','<strong>18 maanden</strong> bij start vanaf 1 juli 2023 (daarvoor 3 jaar); rechter kan inkorten of verlengen tot max. 5 jaar'],['Tijdens','Leefgeld en een bewindvoerder'],['Einde','Restschulden meestal kwijtgescholden als je je aan de regels houdt']],['Onderdeel','Toelichting'])
+'<h2 id="collection">Maximale incassokosten</h2>'
+T([['Eerste € 2.500','15%'],['Volgende € 2.500','10%'],['Volgende € 5.000','5%'],['Volgende € 190.000','1%'],['Boven € 200.000','0,5%'],['Minimum','€ 40']],['Over het bedrag','Maximum'])
+'<p>Geen aparte kosten voor aanmaningen, herinneringen of administratie. Wordt er meer gevraagd: schriftelijk bezwaar en specificatie vragen; Juridisch Loket helpt.</p>'
'<h2 id="government">Schulden bij de overheid</h2>'
+T([['Belastingdienst','Standaard max. <strong>12 maanden</strong>, min. € 20 per maand, schuld tot € 100.000; langer bij bijzondere omstandigheden; besluit binnen 8 weken; invorderingsrente'],['Toeslagen terugbetalen','Tot <strong>24 maanden</strong> door de eerste termijn op tijd te betalen; rente 4,3% sinds 1 januari 2026; anders persoonlijke regeling (<a href="/nl/articles/toeslagen-income-update.html">toeslagen</a>)'],['CJIB-boetes','Vraag het CJIB naar betalen in termijnen']],['Schuldeiser','Regeling'])
+'<h2 id="help">Meer gratis hulp</h2><ul><li><strong>Juridisch Loket</strong> (0800 8020); een advocaat met korting via een <a href="/nl/articles/legal-aid-lawyer-toevoeging.html">toevoeging</a>.</li><li><strong>Sociaal raadslieden</strong>.</li><li>Vrijwilligers thuisadministratie.</li><li>Check je rechten: <a href="/nl/articles/social-assistance-bijstand.html">bijstand</a>, <a href="/nl/articles/special-assistance-bijzondere-bijstand.html">bijzondere bijstand</a>, <a href="/nl/articles/municipal-taxes-exemption-kwijtschelding.html">kwijtschelding</a>, <a href="/nl/articles/energy-emergency-fund-2027.html">Noodfonds Energie 2027</a>, <a href="/nl/articles/energy-contracts-saving-2026.html">energie besparen</a>.</li></ul>'
'<h2 id="mistakes">Veelgemaakte fouten</h2><ol><li>Schulden verzwijgen voor partner of hulpverlener.</li><li>De luidste schuldeiser eerst betalen in plaats van huur en energie.</li><li>Een regeling afspreken die je niet volhoudt.</li><li>Flitskredieten en achteraf betalen.</li><li>De beslagvrije voet niet controleren.</li></ol>'),
faq=[('Is schuldhulp van de gemeente gratis?','Ja, en het is een wettelijk recht.'),
('Hoe snel moet de gemeente reageren?','Binnen 4 weken; bij dreigende uitzetting of afsluiting binnen 3 werkdagen.'),
('Wat is een adempauze?','Tot 6 maanden waarin schuldeisers bij dreiging geen actie ondernemen.'),
('Hoe lang duurt de Wsnp?','18 maanden bij start vanaf 1 juli 2023.'),
('Hoeveel incassokosten mogen er worden gerekend?','Volgens de wettelijke staffel: 15% over de eerste € 2.500, minimaal € 40, geen kosten voor aanmaningen.'),
('Klopt het beslag op mijn loon?','Controleer de beslagvrije voet op uwbeslagvrijevoet.nl en reageer binnen 4 weken.')],
src_note='Gecontroleerd in de Wet gemeentelijke schuldhulpverlening, bij Juridisch Loket, Rijksoverheid en Belastingdienst op 5 oktober 2026. Het aantal maanden achterstand vóór vroegsignalering vonden we niet officieel.')
