from a_student_finance import T
SLUG='dutch-school-system-basisschool'
R='https://www.rijksoverheid.nl/'
SRC=[('Rijksoverheid · Leerplicht',R+'onderwerpen/leerplicht'),
('Rijksoverheid · Kosten basisschool en vrijwillige ouderbijdrage',R+'onderwerpen/basisonderwijs/vraag-en-antwoord/kosten-basisschool-kind'),
('Rijksoverheid · Leerplicht en schoolvakanties (verlof)',R+'vraag-en-antwoord/leerplicht/leerplicht-schoolvakanties'),
('Rijksoverheid · Verplichte doorstroomtoets basisonderwijs',R+'themas/onderwijs/schooladvies-en-doorstroomtoets-basisschool/verplichte-doorstroomtoets-basisonderwijs'),
('Rijksoverheid · Adviezen in groep 8',R+'vraag-en-antwoord/schooladvies-en-doorstroomtoets-basisschool/adviezen-in-groep-8'),
('Rijksoverheid · Tijdlijn schooladvies 2027',R+'themas/onderwijs/schooladvies-en-doorstroomtoets-basisschool/tijdlijn-schooladvies-2027'),
('Rijksoverheid · Onderwijs voor nieuwkomers',R+'onderwerpen/basisonderwijs/onderwijs-voor-nieuwkomers')]

AR=dict(title='المدرسة الابتدائية في هولندا 2026: التعليم الإلزامي من 5 سنوات، المجموعات 1–8، تبرع الأهل الطوعي، الإجازات والغرامات، واختبار التوجيه والنصيحة الدراسية',
crumb='المدرسة الابتدائية',
seo_title='المدرسة الابتدائية basisschool 2026',
desc='المدرسة الابتدائية basisschool: الدخول من 4 سنوات والتعليم إلزامي من 5 حتى 16. التبرع الطوعي، الإجازة خارج العطلة (حتى 10 أيام)، واختبار المجموعة 8.',
summary='<ol><li><strong>يمكن لطفلك دخول المدرسة من 4 سنوات</strong>، و<strong>التعليم إلزامي من 5 حتى 16</strong>، ثم «الالتزام بالتأهيل» حتى 18 أو حتى الحصول على شهادة أساسية.</li><li>الابتدائية 8 «مجموعات» (groep 1–8)، من 4 إلى نحو 12 سنة.</li><li><strong>«التبرع الطوعي للأهل» طوعي فعلاً</strong>: لا يجوز حرمان طفلك من رحلة أو نشاط لأنك لم تدفع.</li><li><strong>الإجازة خارج العطلة</strong> فقط بإذن المدير ولأسباب محددة؛ دونه غرامة ممكنة.</li><li><strong>في المجموعة 8</strong> يُجري كل الأطفال «اختبار التوجيه» (doorstroomtoets)، ومعه نصيحة المدرسة تحدد المسار الثانوي. في 2027: الاختبار 25 يناير–12 فبراير، والنصيحة النهائية حتى 24 مارس.</li></ol>',
body=(
'<h2 id="ages">الأعمار والمراحل</h2>'
+T([['من 4 سنوات','يمكن الدخول للمجموعة 1 (غير إلزامي بعد)'],['من 5 حتى 16 سنة','<strong>التعليم الإلزامي</strong> (leerplicht)'],['من 16 حتى 18','<strong>الالتزام بالتأهيل</strong> (kwalificatieplicht) حتى شهادة أساسية (مثل havo أو vwo أو MBO 2؛ راجع <a href="/articles/mbo-hbo-wo-comparison.html">مقارنة mbo وhbo وwo</a>)'],['المجموعات 1–2','مرحلة الروضة: لعب ولغة وأساسيات'],['المجموعات 3–8','القراءة والكتابة والحساب والمواد'],['بعد المجموعة 8','الثانوي: vmbo أو havo أو vwo (أو praktijkonderwijs)']],['المرحلة','ماذا تعني'])
+'<h2 id="choose">اختيار المدرسة والتسجيل</h2><ul><li>في هولندا مدارس عامة ومدارس ذات طابع ديني أو تربوي خاص، وكلها ممولة من الدولة.</li><li>كثير من البلديات والمدارس تطلب التسجيل المبكر (أحياناً من سن 3). اسأل مدرسة الحي والبلدية مبكراً.</li><li>زر المدرسة، واسأل عن: دعم اللغة الهولندية، الرعاية بعد المدرسة (BSO)، حجم الصفوف، والتواصل مع الأهل.</li><li>الرعاية بعد المدرسة قد تحصل لها على بدل الحضانة (<a href="/articles/childcare-allowance-kinderopvangtoeslag.html">بدل الحضانة</a>).</li></ul>'
'<h2 id="costs">التكاليف و«التبرع الطوعي»</h2><ul><li>التعليم الابتدائي العام مجاني، ويساعد <a href="/articles/kinderbijslag-guide.html">بدل الأطفال (kinderbijslag)</a> في تغطية مصاريف الطفل.</li><li><strong>التبرع الطوعي للأهل (vrijwillige ouderbijdrage) طوعي دائماً.</strong> إن لم تدفع، لا يجوز للمدرسة استبعاد طفلك من الأنشطة الإضافية مثل الرحلة المدرسية.</li><li>يجب أن يوافق مجلس المشاركة على المبلغ وطريقة صرفه، ويُذكر في دليل المدرسة.</li><li>لا يجوز للمدرسة إلزامك بشراء جهاز لوحي أو حاسوب. وللتكاليف التي لا تستطيع تحملها راجع <a href="/articles/special-assistance-bijzondere-bijstand.html">دليل المساعدة الخاصة</a>.</li><li>للعائلات ذات الدخل المنخفض: اسأل البلدية عن مساعدات الأطفال (حزمة الأطفال، ونوادي الرياضة) (<a href="/articles/kindgebonden-budget-guide.html">ميزانية الأطفال</a>).</li></ul>'
'<h2 id="leave">الإجازة خارج العطلات (verlof)</h2>'
+T([['من يقرر','مدير المدرسة'],['متى تطلب','قبل <strong>8 أسابيع</strong> على الأقل'],['الحد','<strong>10 أيام دراسية</strong> كحد أقصى في السنة، مرة واحدة، وليس في أول أسبوعين بعد العطلة الصيفية'],['السبب المقبول','فقط إن كان عملك يمنعك من السفر في أي عطلة مدرسية (عمل موسمي، موظف لا غنى عنه في وقت الذروة، عامل حر مع خسارة دخل كبيرة)؛ مع إفادة من صاحب العمل'],['ظروف مهمة (مثل جنازة)','المدير يمنح حتى 10 أيام؛ وأكثر من ذلك يقرره موظف التعليم الإلزامي بالبلدية'],['السفر دون إذن','قد يؤدي إلى <strong>غرامة</strong>']],['البند','القاعدة'])
+'<p><strong>نصيحة للعائلات العربية:</strong> السفر لزيارة الأهل في بلد آخر ليس سبباً مقبولاً بحد ذاته. خطّط للسفر في العطل الرسمية، وأرسل الطلب كتابياً مبكراً إن كانت لديك ظروف عمل حقيقية.</p>'
'<h2 id="advice">المجموعة 8: اختبار التوجيه والنصيحة الدراسية</h2><ul><li>في المجموعتين 7 و8 تعطي المدرسة <strong>نصيحة مؤقتة</strong>.</li><li>كل أطفال المجموعة 8 يجرون <strong>اختبار التوجيه (doorstroomtoets)</strong> الذي يقيس مستوى اللغة والحساب.</li><li>النصيحة المؤقتة ونتيجة الاختبار معاً تصنعان <strong>النصيحة النهائية</strong>. إن جاءت نتيجة الاختبار أعلى، تعيد المدرسة النظر في النصيحة وترفعها مبدئياً، إلا إن لم يكن ذلك في مصلحة الطفل مع شرح السبب.</li><li>النصيحة قد تذكر نوعاً أو نوعين من التعليم الثانوي، من التعليم العملي حتى vwo.</li></ul>'
+T([['اختبار التوجيه','25 يناير – 12 فبراير 2027'],['النصيحة النهائية','حتى 24 مارس 2027'],['أسبوع التسجيل المركزي في الثانوي','25 – 31 مارس 2027'],['قرار القبول في الثانوي','حتى 12 مايو 2027']],['المرحلة (لأطفال المجموعة 8 الآن)','التاريخ'])
+'<h2 id="newcomers">الأطفال القادمون حديثاً</h2><ul><li>تتوفر في كثير من البلديات <strong>صفوف للقادمين الجدد</strong> أو «صفوف انتقالية» لتعلم الهولندية قبل الانضمام لصف عادي أو بالتوازي معه.</li><li>للأعمار 12 فما فوق: صفوف انتقالية دولية (ISK) في الثانوي عادة.</li><li>اسأل البلدية ومدرسة الحي عن المتاح لعمر طفلك؛ التنظيم يختلف بين المدن.</li><li>تحدث مع طفلك بلغتك الأم في البيت أيضاً؛ اللغة الأم القوية تساعد تعلم الهولندية.</li></ul>'
'<h2 id="parents">دورك كولي أمر</h2><ol><li>احضر «لقاءات الأهل» (oudergesprekken) ولو بمترجم.</li><li>اقرأ رسائل المدرسة وتطبيقها (مثل Parro أو غيره).</li><li>أبلغ عن الغياب قبل بدء اليوم الدراسي.</li><li>اسأل عن نصيحة طفلك مبكراً في المجموعة 7.</li><li>اطلب دعماً إضافياً إن احتاج طفلك (التعليم المناسب: passend onderwijs).</li></ol>'
'<h2 id="mistakes">أخطاء شائعة</h2><ol><li>السفر قبل العطلة بأيام دون إذن.</li><li>الظن أن التبرع الطوعي إلزامي.</li><li>التسجيل المتأخر في المدرسة المرغوبة.</li><li>تجاهل النصيحة المؤقتة حتى فوات الأوان.</li></ol>'),
faq=[('من أي عمر يدخل طفلي المدرسة؟','يمكنه الدخول من 4 سنوات، والتعليم إلزامي من 5 حتى 16.'),
('هل يجب أن أدفع التبرع الطوعي؟','لا، هو طوعي دائماً، ولا يجوز استبعاد طفلك من الأنشطة إن لم تدفع.'),
('هل يمكنني أخذ طفلي في إجازة قبل العطلة؟','فقط بإذن المدير ولأسباب عمل محددة، حتى 10 أيام مرة في السنة وبطلب قبل 8 أسابيع؛ وإلا قد تُغرَّم.'),
('ما هو doorstroomtoets؟','اختبار يجريه كل أطفال المجموعة 8 للغة والحساب، ويُكمل مع نصيحة المدرسة النصيحة النهائية للثانوي.'),
('متى النصيحة النهائية في 2027؟','حتى 24 مارس 2027، بعد الاختبار بين 25 يناير و12 فبراير.')],
src_note='راجعنا صفحات Rijksoverheid عن التعليم الإلزامي والتكاليف والإجازات والنصيحة الدراسية في 5 أكتوبر 2026. تنظيم صفوف القادمين الجدد يختلف بين البلديات.')

NL=dict(title='De basisschool in Nederland 2026: leerplicht vanaf 5, groep 1–8, vrijwillige ouderbijdrage, verlof en boetes, doorstroomtoets en schooladvies',
crumb='Basisschool',
seo_title='Basisschool in Nederland 2026: leerplicht',
desc='De basisschool uitgelegd: naar school vanaf 4, leerplicht van 5 tot 16. Vrijwillige ouderbijdrage, verlof (max. 10 dagen per jaar) en de doorstroomtoets.',
summary='<ol><li><strong>Naar school vanaf 4</strong>, <strong>leerplicht van 5 tot 16</strong>, daarna kwalificatieplicht tot 18 of een startkwalificatie.</li><li>Basisschool: groep 1–8.</li><li>De <strong>vrijwillige ouderbijdrage is echt vrijwillig</strong>: je kind mag niet worden uitgesloten van activiteiten.</li><li><strong>Verlof buiten de vakantie</strong> alleen met toestemming en om specifieke redenen; anders boete mogelijk.</li><li><strong>Groep 8:</strong> doorstroomtoets en schooladvies; in 2027 toets 25 januari–12 februari, definitief advies uiterlijk 24 maart.</li></ol>',
body=(
'<h2 id="ages">Leeftijden en fasen</h2>'
+T([['Vanaf 4','Naar groep 1 (nog niet verplicht)'],['5 tot 16','<strong>Leerplicht</strong>'],['16 tot 18','<strong>Kwalificatieplicht</strong> tot startkwalificatie (havo, vwo of mbo 2; zie <a href="/nl/articles/mbo-hbo-wo-comparison.html">mbo, hbo en wo vergeleken</a>)'],['Groep 1–2','Kleuters: spel, taal, basis'],['Groep 3–8','Lezen, schrijven, rekenen en vakken'],['Na groep 8','Vmbo, havo, vwo of praktijkonderwijs']],['Fase','Betekenis'])
+'<h2 id="choose">School kiezen en aanmelden</h2><ul><li>Openbare en bijzondere scholen (bijv. religieus of met eigen onderwijsvisie) worden allemaal door de overheid bekostigd.</li><li>Veel gemeenten en scholen vragen vroeg aanmelden (soms vanaf 3 jaar).</li><li>Vraag naar taalondersteuning, bso, groepsgrootte en contact met ouders.</li><li>Voor bso kun je kinderopvangtoeslag krijgen (<a href="/nl/articles/childcare-allowance-kinderopvangtoeslag.html">kinderopvangtoeslag</a>).</li></ul>'
'<h2 id="costs">Kosten en ouderbijdrage</h2><ul><li>Openbaar basisonderwijs is gratis; voor de kosten van je kind is er <a href="/nl/articles/kinderbijslag-guide.html">kinderbijslag</a>.</li><li>De <strong>vrijwillige ouderbijdrage is altijd vrijwillig</strong>; niet betalen mag niet leiden tot uitsluiting van extra activiteiten zoals het schoolreisje.</li><li>De medezeggenschapsraad stemt in met hoogte en besteding; dit staat in de schoolgids.</li><li>Scholen mogen geen tablet of laptop verplichten. Kosten die je niet kunt betalen? Zie onze <a href="/nl/articles/special-assistance-bijzondere-bijstand.html">gids over bijzondere bijstand</a>.</li><li>Laag inkomen: vraag de gemeente naar kindregelingen (<a href="/nl/articles/kindgebonden-budget-guide.html">kindgebonden budget</a>).</li></ul>'
'<h2 id="leave">Verlof buiten de schoolvakantie</h2>'
+T([['Wie beslist','De directeur'],['Wanneer aanvragen','Minimaal <strong>8 weken</strong> vooraf'],['Maximum','<strong>10 schooldagen</strong> per schooljaar, één keer, niet in de eerste 2 weken na de zomervakantie'],['Geldige reden','Alleen als je door je werk in geen enkele schoolvakantie weg kunt (seizoenswerk, onmisbaar in piekperiode, zelfstandige met aanzienlijk inkomstenverlies), met werkgeversverklaring'],['Gewichtige omstandigheden (bijv. begrafenis)','Directeur tot 10 dagen; meer via de leerplichtambtenaar'],['Zonder toestemming','<strong>Boete</strong> mogelijk']],['Onderdeel','Regel'])
+'<p>Familiebezoek in het buitenland is op zichzelf geen geldige reden; plan reizen in de schoolvakanties.</p>'
'<h2 id="advice">Groep 8: doorstroomtoets en schooladvies</h2><ul><li>In groep 7/8 een <strong>voorlopig advies</strong>.</li><li>Alle leerlingen in groep 8 maken de <strong>doorstroomtoets</strong> (taal en rekenen).</li><li>Voorlopig advies en toetsadvies vormen samen het <strong>definitieve advies</strong>; valt de toets hoger uit, dan stelt de school in principe bij, tenzij dat niet in het belang van het kind is (met uitleg).</li><li>Het advies kan één of twee schoolsoorten noemen, van praktijkonderwijs tot vwo.</li></ul>'
+T([['Doorstroomtoets','25 januari – 12 februari 2027'],['Definitief advies','Uiterlijk 24 maart 2027'],['Centrale aanmeldweek vo','25 – 31 maart 2027'],['Toelating vo','Uiterlijk 12 mei 2027']],['Stap (huidige groep 8)','Datum'])
+'<h2 id="newcomers">Nieuwkomers</h2><ul><li>Veel gemeenten hebben <strong>nieuwkomersklassen</strong> of schakelklassen om Nederlands te leren.</li><li>Vanaf 12 jaar meestal een internationale schakelklas (ISK) in het voortgezet onderwijs.</li><li>Vraag gemeente en school wat er voor de leeftijd van je kind is.</li><li>Blijf thuis ook je moedertaal spreken; dat helpt bij Nederlands.</li></ul>'
'<h2 id="parents">Jouw rol als ouder</h2><ol><li>Ga naar oudergesprekken, eventueel met tolk.</li><li>Lees berichten en de school-app.</li><li>Meld ziekte vóór schooltijd.</li><li>Vraag in groep 7 al naar het advies.</li><li>Vraag extra ondersteuning (passend onderwijs) als dat nodig is.</li></ol>'
'<h2 id="mistakes">Veelgemaakte fouten</h2><ol><li>Zonder toestemming eerder op vakantie.</li><li>Denken dat de ouderbijdrage verplicht is.</li><li>Te laat aanmelden.</li><li>Het voorlopig advies negeren.</li></ol>'),
faq=[('Vanaf welke leeftijd gaat mijn kind naar school?','Vanaf 4 mag het, vanaf 5 tot 16 is het leerplichtig.'),
('Moet ik de ouderbijdrage betalen?','Nee, die is altijd vrijwillig.'),
('Mag ik mijn kind eerder meenemen op vakantie?','Alleen met toestemming van de directeur om werkredenen, max. 10 dagen per jaar, 8 weken vooraf aangevraagd; anders boete mogelijk.'),
('Wat is de doorstroomtoets?','Een verplichte toets taal en rekenen in groep 8 die samen met het voorlopig advies het definitieve advies bepaalt.'),
('Wanneer komt het definitieve advies in 2027?','Uiterlijk 24 maart 2027.')],
src_note='Gecontroleerd op Rijksoverheid-pagina’s over leerplicht, kosten, verlof en schooladvies op 5 oktober 2026. Nieuwkomersonderwijs verschilt per gemeente.')
