from a_student_finance import T
SLUG='scams-phishing-netherlands'
VB='https://www.veiligbankieren.nl/'
P='https://www.politie.nl/'
SRC=[('Belastingdienst · Valse WhatsApp-berichten, sms-berichten, mails, apps, brieven of telefoontjes','https://www.belastingdienst.nl/wps/wcm/connect/nl/contact/content/valse-whatsapp-berichten-sms-berichten-mails-apps-brieven-of-telefoontjes'),
('DigiD · Recognise a fake message','https://www.digid.nl/en/security/recognise-fake-message'),
('Veilig Bankieren (Betaalvereniging/NVB) · Bankhelpdeskfraude',VB+'fraude/bankhelpdeskfraude/'),
('Veilig Bankieren · Geldezels',VB+'fraude/geldezels/'),
('Veilig Bankieren · Fraude melden (pas blokkeren, aangifte, Fraudehelpdesk)',VB+'meld-fraude/'),
('Veilig Bankieren · Uniforme veiligheidsregels',VB+'uniforme-veiligheidsregels/'),
('Veilig Bankieren · Betaalverzoek',VB+'veiligheid-betaalproducten/betaalverzoek/'),
('Politie · Ik wil aangifte doen van hulpvraagfraude (vriend-in-noodfraude)',P+'aangifte-of-melding-doen/aangifte-van-vriend-in-noodfraude.html'),
('Politie · Slachtoffer van internetoplichting? Doe aangifte!',P+'informatie/slachtoffer-van-internetoplichting-doe-aangifte.html'),
('Politie · Ik ben slachtoffer van phishing',P+'informatie/ik-ben-slachtoffer-van-phishing.html'),
('Rijksoverheid · Wat doe ik bij mogelijke identiteitsfraude?','https://www.rijksoverheid.nl/onderwerpen/identiteitsfraude/vraag-en-antwoord/wat-doe-ik-bij-mogelijke-identiteitsfraude'),
('RvIG · Centraal Meldpunt Identiteitsfraude (CMI)','https://www.rvig.nl/centraal-meldpunt-identiteitsfraude'),
('Rijksoverheid · Contactgids Fraudehelpdesk','https://www.rijksoverheid.nl/contact/contactgids/fraudehelpdesk'),
('KVK · Geld kwijt en niets ontvangen. Zo herken je een nepwebshop','https://www.kvk.nl/veilig-zakendoen/geld-kwijt-en-niets-ontvangen-zo-herken-je-een-nepwebshop/'),
('Openbaar Ministerie · Online campagne waarschuwt voor huurfraude','https://www.om.nl/actueel/nieuws/2021/10/01/online-campagne-waarschuwt-voor-huurfraude'),
('Veilig Internetten · Wat is quishing?','https://veiliginternetten.nl/wat-is-quishing/')]
AR=dict(title='الاحتيال والتصيّد في هولندا 2026: رسائل Belastingdienst وDigiD المزيفة، «هاي ماما» على واتساب، احتيال «موظف البنك»، Marktplaats وTikkie، الإيجار الوهمي وgeldezel — وماذا تفعل فوراً',
crumb='الاحتيال والتصيّد',
seo_title='الاحتيال والتصيّد phishing في هولندا',
desc='الاحتيال والتصيّد (phishing) في هولندا: رسائل Belastingdienst وDigiD المزيفة و«هاي ماما». وقعت في الفخ؟ اتصل ببنكك ثم Fraudehelpdesk على 088 786 73 72.',
summary='<ol><li><strong>Belastingdienst لا يرسل طلبات دفع مباشرة</strong> ولا يطالبك بمتأخرات عبر واتساب أو البريد الإلكتروني. تحقق دائماً بالدخول بنفسك إلى Mijn Belastingdienst أو Mijn Toeslagen.</li><li><strong>البنك لا يطلب أبداً</strong> رمزك السري أو بطاقتك أو جهاز الدخول، ولا يرسل أحداً لأخذها، ولا يطلب منك تحويل المال إلى «حساب آمن».</li><li>رسالة من «ابنك» برقم جديد يطلب مالاً عاجلاً؟ <strong>اتصل به على رقمه القديم</strong> قبل أي تحويل.</li><li>وقعت في الفخ؟ <strong>اتصل ببنكك فوراً</strong> (أو 0800 0313 لبنوك أخرى)، ثم <strong>بلاغ لدى الشرطة</strong> (aangifte) و<strong>Fraudehelpdesk</strong> على 088 786 73 72.</li><li>إقراض حسابك أو بطاقتك مقابل المال = <strong>geldezel</strong>: ملاحقة جنائية، سداد المبالغ، و<strong>8 سنوات</strong> في نظام إنذار المؤسسات المالية.</li></ol>',
body=(
'<h2 id="why">لماذا يستهدف المحتالون القادمين الجدد؟</h2><p>القادم الجديد يتلقى رسائل كثيرة من جهات لا يعرفها جيداً: الضرائب (Belastingdienst)، البدلات (Toeslagen)، DigiD، البنك، البلدية، CJIB. المحتال يستغل الخوف من الغرامة، والاستعجال، وضعف اللغة الهولندية. القاعدة الذهبية في هذا الدليل كله: <strong>لا تتصرف من داخل الرسالة نفسها</strong>. لا تضغط الرابط، ولا تتصل بالرقم المكتوب فيها، ولا تمسح رمز QR مجهولاً. افتح التطبيق أو الموقع الرسمي بنفسك، أو اتصل بالرقم الموجود على بطاقتك البنكية أو في الموقع الرسمي.</p>'
+'<h2 id="types">أشهر أنواع الاحتيال: العلامات وما تفعله</h2>'
+T([['رسالة باسم Belastingdienst أو Toeslagen','«دَين مفتوح» أو «استرداد» مع رابط دفع أو طلب تأكيد حسابك عبر iDEAL/Wero؛ رسالة واتساب أو بريد عن متأخرات','لا تضغط. ادخل بنفسك إلى Mijn Belastingdienst / Mijn Toeslagen. أرسل الرسالة إلى valse-email@belastingdienst.nl'],['رسالة باسم DigiD','«حسابك سينتهي»، «أكمل التحقق»، طلب اسم المستخدم وكلمة المرور','موظفو DigiD لا يطلبون بيانات دخولك أبداً. أرسلها إلى valse-email@digid.nl واحذفها'],['«هاي ماما/بابا» (hulpvraagfraude)','رقم جديد، «هاتفي تعطل»، فاتورة عاجلة، «لا أستطيع الاتصال الآن»، حساب باسم شخص آخر','اتصل بالشخص على رقمه القديم أو اسأله سؤالاً لا يعرفه غيره'],['احتيال مكتب البنك (bankhelpdeskfraude)','اتصال يظهر فيه رقم البنك الحقيقي، «حسابك مخترق»، «حوّل مالك إلى حساب خزنة آمن»، ساعٍ يأتي لأخذ بطاقتك، تثبيت AnyDesk أو TeamViewer','أغلق الخط. اتصل ببنكك بنفسك على الرقم الرسمي'],['طلب دفع مزيف (Tikkie/betaalverzoek)','رابط لا يبدأ بعنوان البنك الرسمي، صفحة تطلب الدخول إلى حسابك «لتستلم» المال','الدفع الحقيقي يتم دائماً عبر iDEAL؛ لاستلام المال لا تحتاج للدخول إلى حسابك'],['إيجار وهمي','دفع الإيجار أو الكفالة قبل رؤية البيت، صور وإعلان فقط، «المالك في الخارج»','لا تدفع قبل المعاينة والتحقق من المالك وتوقيع العقد'],['تجنيد geldezel','«عمل سهل» أو «مال سريع» مقابل استعارة حسابك أو بطاقتك','ارفض فوراً وأبلغ الشرطة أو بنكك'],['متجر إلكتروني وهمي','أسعار رخيصة جداً، لا رقم KVK أو عنوان غير مطابق، تحويل مسبق إلى حساب أجنبي','افحص السجل التجاري لدى KVK وعلامات الثقة قبل الدفع'],['QR مزيف (quishing)','QR على عدّاد موقف، أو في رسالة «من البنك» تطلب مسحه','امسح فقط ما كنت تتوقعه؛ ادفع عبر التطبيق الرسمي']],['النوع','العلامات الحمراء','ماذا تفعل'])
+'<h2 id="tax">رسائل الضرائب والبدلات (Belastingdienst/Toeslagen) المزيفة</h2><p>بحسب صفحة Belastingdienst الرسمية:</p><ul><li><strong>لا يرسل طلبات دفع مباشرة</strong>، ولا يستخدم واتساب أو البريد الإلكتروني لإبلاغك بمتأخرات.</li><li>لا يطلب بياناتك الشخصية عبر واتساب أو SMS أو البريد الإلكتروني، ولا يطلب منك تأكيد حسابك البنكي عبر iDEAL أو Wero.</li><li>رمز QR في رسالة ورقية حقيقية يقودك إلى صفحة «Overzicht betalen en ontvangen»، <strong>لا إلى صفحة دفع مباشرة</strong>.</li><li>الرسائل الرسمية تصلك كرسالة أو قرار ضريبي (aanslag)، وتجدها في Mijn Belastingdienst أو Mijn Toeslagen.</li><li>قبل أي تحويل: قارن رقم الحساب مع <strong>قائمة الحسابات الرسمية</strong> المنشورة على صفحة الاحتيال لدى Belastingdienst (القائمة الحالية سارية من 1 مايو 2026).</li></ul><p><strong>للإبلاغ:</strong> أرسل الرسالة المزيفة إلى <strong>valse-email@belastingdienst.nl</strong> (هذا العنوان للبلاغات فقط)، مع رقم الهاتف أو الحساب أو الموقع ولقطة شاشة. إن حوّلت مالاً: <strong>اتصل ببنكك فوراً</strong>. نفس المنطق ينطبق على رسائل باسم CJIB: تحقق دائماً عبر الموقع الرسمي بالدخول بنفسك (انظر <a href="/articles/traffic-fines-cjib.html">دليل المخالفات وCJIB</a>).</p>'
+'<h2 id="digid">تصيّد DigiD</h2><p>DigiD يرسل رسالة آلية بالبريد أو SMS عندما يتغير شيء في حسابك (طلب DigiD، تفعيل التطبيق، تغيير البيانات، انتهاء الصلاحية). لكن <strong>موظفي DigiD لا يطلبون منك بيانات الدخول أبداً</strong>. من يملك اسم مستخدمك وكلمة مرورك أو رمز التفعيل يستطيع الدخول باسمك إلى الضرائب والبدلات والتأمين. أرسل الرسائل المشبوهة إلى <strong>valse-email@digid.nl</strong> ثم احذفها. إن أعطيت بياناتك، اتبع صفحة «DigiD login credentials stolen» على digid.nl واتصل بمكتب المساعدة. انظر أيضاً <a href="/articles/digid-registration-guide.html">دليل DigiD</a>.</p>'
+'<h2 id="whatsapp">احتيال «هاي ماما/بابا» على واتساب</h2><p>تسميه الشرطة <strong>hulpvraagfraude</strong> أو vriend-in-noodfraude: شخص يتظاهر عبر واتساب أو البريد بأنه قريبك أو صديقك ويطلب مالاً. الحيلة المعتادة: رقم جديد، ثم «فاتورة يجب دفعها اليوم». <strong>اتصل دائماً بالرقم القديم</strong>، أو بصوت، أو اسأل سؤالاً شخصياً. إن دفعت: بنكك فوراً، ثم بلاغ لدى الشرطة. يمكن تقديم البلاغ إلكترونياً بـDigiD، <strong>إلا</strong> إذا استُخدمت هويتك أو حساب واتساب الخاص بك لخداع آخرين؛ عندها اتصل بـ<strong>0900-8844</strong> لحجز موعد.</p>'
+'<h2 id="bank">احتيال «موظف البنك» والحساب الآمن</h2><p>المحتال يتصل وقد يظهر على شاشتك <strong>رقم بنكك الحقيقي</strong> (spoofing). يقول إن حسابك مخترق وإن عليك تحويل مالك مؤقتاً إلى «حساب خزنة آمن»، أو إن بطاقتك غير آمنة وسيأتي ساعٍ لأخذها، أو يطلب تثبيت AnyDesk أو TeamViewer. أحياناً يتظاهر بأنه من الضرائب أو جهة رسمية أخرى. بحسب Veilig Bankieren، البنك <strong>لا</strong>:</p><ul><li>يطلب تحويل المال عبر الهاتف أو الرسائل؛</li><li>يرسل موظفاً لأخذ بطاقتك أو جهاز الدخول؛</li><li>يطلب رمزك السري أو كلمات المرور أو رموز الأمان؛</li><li>يطلب الوصول إلى حاسوبك أو هاتفك أو تثبيت برنامج مراقبة.</li></ul><p><strong>ما العمل:</strong> أغلق الخط، اتصل ببنكك بنفسك، واتبع تعليمات الموظف، ثم قدّم بلاغاً للشرطة.</p>'
+'<h2 id="marktplaats">Marktplaats وطلبات الدفع (Tikkie)</h2><ul><li>طلب الدفع الحقيقي من ABN AMRO (Tikkie) يبدأ بـ<strong>https://www.tikkie.me/pay/</strong>، ومن Rabobank بـ<strong style="overflow-wrap:anywhere">https://betaalverzoek.rabobank.nl/betaalverzoek</strong>، والدفع يتم <strong>دائماً عبر iDEAL</strong>.</li><li><strong>كبائع لا تحتاج أبداً</strong> أن تدفع أو تدخل إلى حسابك البنكي لكي تستلم المال. أي «رابط استلام» أو «تحقق بسنت واحد» يطلب ذلك علامة خطر.</li><li>انتقال المحادثة بسرعة من المنصة إلى واتساب، أو رابط «شحن» غريب، علامات تستدعي التوقف.</li><li>اشتريت ولم يصلك شيء، أو بعت ولم يُدفع لك، أو وصلك منتج مقلّد؟ يمكنك تقديم <strong>بلاغ إلكتروني</strong> لدى politie.nl. بعد <strong>10 أسابيع</strong> تصلك رسالة بريد إلكتروني تقول هل بدأ تحقيق، وإن لم يبدأ تصلك رسالة إغلاق خلال <strong>6 أشهر</strong>.</li></ul>'
+'<h2 id="rent">الإيجار الوهمي والكفالة</h2><p>بحسب النيابة العامة (OM): المحتال يتظاهر بأنه مالك بيت ليس له أو لا ينوي تأجيره، والضحية تدفع الإيجار مسبقاً بناءً على وصف وصور على الإنترنت فقط، والحساب البنكي المستلم لا يعود لـ«المالك». القواعد: لا تدفع شيئاً قبل <strong>رؤية البيت</strong> و<strong>التحقق من هوية المالك أو الوكيل</strong> و<strong>عقد مكتوب</strong>؛ ولا ترسل صورة جواز سفرك أو إقامتك لشخص لم تتحقق منه. حقوقك في الكفالة (حدها الأقصى وموعد إعادتها) في <a href="/articles/tenant-rights-netherlands.html">دليل حقوق المستأجر</a>.</p>'
+'<h2 id="mule">geldezel: «عمل سهل» قد يدمّر مستقبلك المالي</h2><p>الـgeldezel شخص يُستخدم حسابه البنكي لغسل أموال المجرمين. يُجنَّد عبر الإنترنت والدردشة والهاتف وأحياناً عند المدارس، بقصة «عمل مربح بساعات قليلة». إما يحوّل المال الذي يصله إلى حسابات أجنبية مقابل نسبة، أو يعير بطاقته ليسحب المجرم المال. العواقب بحسب Veilig Bankieren «جسيمة»:</p>'
+T([['ملاحقة جنائية','تُتهم بالمشاركة في الاحتيال، وقد تحصل على سجل جنائي'],['سداد المبالغ','عليك إعادة كل الأموال المفقودة، فتتراكم عليك ديون كبيرة'],['نظام إنذار المؤسسات المالية','تسجيل في incidentenwaarschuwingssysteem لمدة <strong>8 سنوات</strong>: صعوبة الحصول على قرض أو رهن أو خدمات بنكية'],['فقدان الحساب البنكي','قد لا تستطيع فتح حساب جديد، فيصعب استلام راتبك']],['العاقبة','التفاصيل'])
+'<p>عُرض عليك ذلك أو تورطت؟ اتصل بالشرطة <strong>0900-8844</strong> (112 في الطوارئ)، أو أبلغ دون ذكر اسمك عبر <strong>Meld Misdaad Anoniem 0800-7000</strong>، وأبلغ بنكك.</p>'
+'<h2 id="shops">المتاجر الوهمية وQR المزيف</h2><p>تنصح غرفة التجارة <strong>KVK</strong> بخمسة فحوص: (1) هل نشاط الشركة في السجل التجاري (Handelsregister) يطابق ما تبيعه؟ (2) هل العنوان في الموقع يطابق السجل؟ (3) هل يظهر في الموقع العنوان والبريد ورقم KVK؟ ويمكن استخدام أداة ScamCheck من KVK؛ (4) ادفع بطريقة آمنة: بطاقة ائتمان أو iDEAL/Wero أو PayPal أو الدفع لاحقاً، وتجنب التحويل المسبق إلى حساب أجنبي أو وسيط؛ (5) ابحث عن علامات مستقلة مثل <strong>Thuiswinkel Waarborg</strong> أو Webshop Keurmerk وعن تقييمات حقيقية. وعن <strong>quishing</strong> (التصيّد عبر QR): رموز مزيفة تظهر على عدّادات المواقف، وفي الرسائل الورقية والإعلانات والبريد، وفي «رسائل بنك» مزيفة. اسأل نفسك: هل كنت أتوقع هذا الرمز؟</p>'
+'<h2 id="examples">رسائل نموذجية للتدريب</h2><p><strong>أمثلة توضيحية وليست حالات أشخاص حقيقيين</strong>. كتبناها نحن لتتعلم العلامات، وليست منسوخة من رسائل ضحايا:</p>'
+T([['SMS: «Belastingdienst: لديك دين مفتوح 87 يورو. ادفع اليوم عبر الرابط لتجنب الحجز»','Belastingdienst لا يرسل طلبات دفع مباشرة ولا روابط دفع؛ الاستعجال والتهديد','احذف، أبلغ valse-email@belastingdienst.nl، وتحقق في Mijn Belastingdienst'],['واتساب: «ماما هذا رقمي الجديد، هاتفي وقع. أحتاج 650 يورو لفاتورة اليوم»','رقم جديد + طلب مال عاجل + حساب باسم آخر','اتصلي بالرقم القديم قبل أي شيء'],['مكالمة: «أنا من قسم الأمن في بنكك، حسابك مخترق، حوّل رصيدك إلى حساب آمن»','البنك لا يطلب تحويلاً هاتفياً أبداً','أغلق الخط واتصل ببنكك بنفسك'],['Marktplaats: «اضغط هنا لتستلم مبلغ البيع، ادخل إلى بنكك وادفع 0.01 للتحقق»','لاستلام المال لا تحتاج للدخول ولا للدفع','لا تضغط؛ أعطِ رقم حسابك فقط إن أردت'],['إعلان: «شقة 2 غرف 650 يورو، أنا في الخارج، حوّل الكفالة وأرسل لك المفتاح»','دفع قبل المعاينة، المالك غائب، سعر مغرٍ','لا تدفع؛ أبلغ المنصة وFraudehelpdesk']],['الرسالة (مثال مختلَق)','لماذا هي مزيفة','ماذا تفعل'])
+'<h2 id="steps">وقعت في الفخ؟ افعل هذا الآن بالترتيب</h2><ol><li><strong>اتصل ببنكك فوراً</strong> واطلب حجب البطاقة أو الحساب (blokkeren) وإيقاف التحويلات. يمكنك غالباً حجب البطاقة بنفسك في تطبيق البنك.</li><li><strong>غيّر كلمات المرور</strong> (البريد، DigiD، البنك). إن فتحت مرفقاً أو ثبّت برنامجاً، افحص جهازك ولا تستخدم البنك الإلكتروني حتى تتأكد من نظافته.</li><li><strong>احتفظ بالأدلة</strong>: الرسالة، لقطات الشاشة، رقم الهاتف، رقم الحساب المستلم، كشف الحساب.</li><li><strong>قدّم بلاغاً للشرطة (aangifte)</strong> عبر politie.nl (غالباً بـDigiD) أو على 0900-8844.</li><li><strong>أبلغ Fraudehelpdesk</strong> عبر fraudehelpdesk.nl أو 088 786 73 72.</li><li><strong>أرسل الرسالة المزيفة</strong> للجهة المنتحَلة: valse-email@belastingdienst.nl أو valse-email@digid.nl أو عنوان التصيّد لدى بنكك.</li><li><strong>إن استُخدمت هويتك</strong> (حساب أو قرض أو اشتراك باسمك): أبلغ <strong>CMI</strong> عبر نموذج rvig.nl، وأبلغ الشرطة.</li></ol>'
+'<h2 id="contacts">من تتصل به؟</h2>'
+T([['حجب البطاقة: ABN AMRO','0900 00 24 (من خارج هولندا: ‎+31 10 241 17 20)'],['حجب البطاقة: ING','‎+31 (0)20 22 888 00'],['حجب البطاقة: Rabobank','‎+31 (0)88 722 67 67'],['حجب البطاقة: ASN Bank','‎+31 (0)70 356 93 35'],['حجب البطاقة: بنوك أخرى','0800 03 13 (مجاني)'],['الشرطة (غير طارئ / بلاغ)','0900-8844 أو politie.nl؛ الطوارئ 112'],['Fraudehelpdesk','088 786 73 72 أو fraudehelpdesk.nl/fraude-melden'],['بلاغ مجهول','Meld Misdaad Anoniem 0800-7000'],['انتحال هويتك','CMI لدى RvIG: نموذج البلاغ على rvig.nl'],['رسائل ضرائب/بدلات مزيفة','valse-email@belastingdienst.nl'],['رسائل DigiD مزيفة','valse-email@digid.nl']],['الحالة','الجهة والرقم'])
+'<h2 id="refund">هل أستعيد مالي؟</h2><p>لا توجد ضمانة عامة، والقرار عند بنكك. ما تقوله المصادر الرسمية:</p><ul><li><strong>احتيال مكتب البنك</strong>: البنوك تعوّض الضحايا عادة «من باب حسن النية» (uit coulance) بشروط، منها: تقديم بلاغ للشرطة، وأن يكون الحساب شخصياً، وأن تكون المرة الأولى. هناك شروط إضافية لدى جمعية البنوك (NVB).</li><li><strong>القواعد الموحدة للأمان</strong> (uniforme veiligheidsregels) تطلب منك: سرية الرموز، عدم إعارة البطاقة، تأمين أجهزتك، مراجعة حسابك (كل أسبوعين)، و<strong>الإبلاغ الفوري</strong>. البنك ينظر إلى التزامك بها.</li><li>كلما اتصلت أسرع، زادت فرصة إيقاف التحويل.</li><li>إن رفض البنك شكواك، يمكنك التوجه إلى <strong>Kifid</strong> (هيئة شكاوى الخدمات المالية).</li></ul><p>فقدت مالاً وصارت عندك ديون؟ انظر <a href="/articles/debt-help-schuldhulp.html">مساعدة الديون المجانية</a>.</p>'
+'<h2 id="mistakes">أخطاء شائعة</h2><ol><li><strong>الاتصال بالرقم الموجود في الرسالة</strong> بدل رقم البنك الرسمي.</li><li><strong>الثقة برقم الهاتف الظاهر</strong>: يمكن تزويره ليظهر كرقم البنك.</li><li><strong>إعطاء رمز SMS أو كود DigiD</strong> لأي شخص «للتحقق».</li><li><strong>إعارة الحساب أو البطاقة</strong> لصديق أو «صاحب عمل» مقابل المال.</li><li><strong>دفع كفالة بيت</strong> قبل المعاينة والعقد.</li><li><strong>الخجل وتأخير البلاغ</strong>: الوقت حاسم لإيقاف المال.</li><li><strong>عدم البلاغ لأن المبلغ صغير</strong>: البلاغ يساعد الشرطة على ربط الحالات.</li></ol>'
+'<h2 id="help">مساعدة مجانية</h2><ul><li><strong>Fraudehelpdesk</strong>: نصيحة وتوجيه للضحايا (088 786 73 72).</li><li><strong>الشرطة</strong>: 0900-8844، أو البلاغ عبر الإنترنت.</li><li><strong>CMI</strong>: دعم ضحايا انتحال الهوية والوساطة مع الجهات المعنية.</li><li><strong>Veilig Bankieren</strong> و<strong>Veilig Internetten</strong>: شرح أحدث الحيل.</li><li><strong>Juridisch Loket</strong>: نصيحة قانونية مجانية إن احتجت لاسترداد المال من محتال معروف.</li></ul>'
+'<h2 id="related">أدلة مرتبطة</h2><ul><li><a href="/articles/digid-registration-guide.html">DigiD</a></li><li><a href="/articles/traffic-fines-cjib.html">المخالفات المرورية وCJIB</a></li><li><a href="/articles/tenant-rights-netherlands.html">حقوق المستأجر</a></li><li><a href="/articles/toeslagen-income-update.html">تحديث الدخل لدى Toeslagen</a></li><li><a href="/articles/debt-help-schuldhulp.html">مساعدة الديون</a></li></ul>'),
faq=[('هل يرسل Belastingdienst رسالة SMS أو واتساب فيها رابط دفع؟','لا. Belastingdienst لا يرسل طلبات دفع مباشرة ولا يطالب بمتأخرات عبر واتساب أو البريد الإلكتروني. تحقق في Mijn Belastingdienst أو Mijn Toeslagen.'),
('أين أبلغ عن رسالة مزيفة باسم الضرائب؟','أرسلها إلى valse-email@belastingdienst.nl مع لقطة شاشة وأي رقم هاتف أو حساب فيها.'),
('اتصل بي «البنك» من رقمه الحقيقي، فهل هو صادق؟','ليس بالضرورة؛ المحتالون يزوّرون الرقم الظاهر. أغلق الخط واتصل ببنكك بنفسك. البنك لا يطلب تحويل المال إلى «حساب آمن» أبداً.'),
('وصلتني رسالة من ابني برقم جديد يطلب مالاً، ماذا أفعل؟','اتصل به على رقمه القديم أو اسأله سؤالاً شخصياً قبل أي تحويل. هذا احتيال hulpvraagfraude المعروف.'),
('حوّلت المال لمحتال، ما أول خطوة؟','اتصل ببنكك فوراً، ثم قدّم بلاغاً لدى الشرطة وأبلغ Fraudehelpdesk على 088 786 73 72.'),
('هل سيعيد البنك مالي؟','لا ضمان عام. في احتيال مكتب البنك تعوّض البنوك عادة من باب حسن النية بشروط، منها بلاغ الشرطة وحساب شخصي وأن تكون أول مرة.'),
('عرض عليّ شخص مالاً مقابل استخدام حسابي، هل هذا مشكلة؟','نعم، هذا geldezel: ملاحقة جنائية، سداد المبالغ، وتسجيل 8 سنوات في نظام إنذار المؤسسات المالية.'),
('هل أستطيع تقديم البلاغ عبر الإنترنت؟','نعم لكثير من الحالات بـDigiD، مثل احتيال البيع والشراء وhulpvraagfraude. إن استُخدمت هويتك أو حساب واتساب الخاص بك، اتصل بـ0900-8844.'),
('كيف أعرف أن المتجر الإلكتروني حقيقي؟','افحص رقم KVK والعنوان في السجل التجاري، وعلامات مثل Thuiswinkel Waarborg، وادفع بطريقة آمنة لا بتحويل مسبق لحساب أجنبي.'),
('سرقوا بيانات هويتي، لمن ألجأ؟','قدّم بلاغاً للشرطة، أبلغ بنكك، واملأ نموذج Centraal Meldpunt Identiteitsfraude (CMI) على rvig.nl.')],
src_note='راجعنا Belastingdienst وDigiD وVeilig Bankieren والشرطة وRijksoverheid وRvIG وKVK والنيابة العامة وVeilig Internetten في 7 أكتوبر 2026. أرقام البنوك من صفحة Veilig Bankieren وقد تتغير؛ تحقق منها على بطاقتك أو موقع بنكك. لم نذكر رقم هاتف CMI ولا أوقات عمل Fraudehelpdesk لأننا لم نتحقق منها بدقة. الرسائل النموذجية مختلَقة للتوضيح.')
NL=dict(title='Oplichting en phishing in Nederland 2026: valse berichten van Belastingdienst en DigiD, ‘hoi mam’-fraude, bankhelpdeskfraude, Marktplaats en Tikkie, nephuur en geldezels — en wat je meteen doet',
crumb='Oplichting en phishing',
seo_title='Phishing en oplichting herkennen en melden',
desc='Phishing en oplichting: valse berichten van Belastingdienst en DigiD, ‘hoi mam’- en bankhelpdeskfraude. Erin getuind? Bel je bank en de Fraudehelpdesk.',
summary='<ol><li><strong>De Belastingdienst stuurt nooit directe betaalverzoeken</strong> en meldt achterstanden niet via WhatsApp of e-mail. Controleer altijd zelf in Mijn Belastingdienst of Mijn Toeslagen.</li><li><strong>Je bank vraagt nooit</strong> om je pincode, betaalpas of inlogapparaat, haalt die nooit op en laat je nooit geld naar een ‘veilige rekening’ overmaken.</li><li>‘Je kind’ met een nieuw nummer vraagt om spoedgeld? <strong>Bel het oude nummer</strong> vóór je iets overmaakt.</li><li>Toch erin getuind? <strong>Bel direct je bank</strong> (andere banken: 0800 03 13), doe <strong>aangifte</strong> en meld het bij de <strong>Fraudehelpdesk</strong> (088 786 73 72).</li><li>Je rekening of pas uitlenen voor geld = <strong>geldezel</strong>: strafvervolging, terugbetalen en <strong>8 jaar</strong> in het waarschuwingssysteem van financiële instellingen.</li></ol>',
body=(
'<h2 id="why">Waarom nieuwkomers vaak doelwit zijn</h2><p>Wie net in Nederland woont, krijgt post en berichten van veel onbekende instanties: Belastingdienst, Toeslagen, DigiD, de bank, de gemeente, het CJIB. Oplichters spelen in op angst voor boetes, haast en taalbarrières. De gouden regel van deze gids: <strong>handel nooit vanuit het bericht zelf</strong>. Klik niet op de link, bel niet het nummer uit het bericht en scan geen onverwachte QR-code. Open zelf de officiële app of website, of bel het nummer op je bankpas of de officiële site.</p>'
+'<h2 id="types">Veelvoorkomende oplichting: signalen en aanpak</h2>'
+T([['Bericht namens Belastingdienst of Toeslagen','‘Openstaande schuld’ of ‘teruggave’ met betaallink of verzoek je rekening te bevestigen via iDEAL/Wero; WhatsApp of mail over achterstand','Niet klikken. Log zelf in op Mijn Belastingdienst / Mijn Toeslagen. Stuur door naar valse-email@belastingdienst.nl'],['Bericht namens DigiD','‘Account verloopt’, ‘voltooi verificatie’, vraag om gebruikersnaam en wachtwoord','DigiD-medewerkers vragen nooit om je inloggegevens. Doorsturen naar valse-email@digid.nl en verwijderen'],['‘Hoi mam/pap’ (hulpvraagfraude)','Nieuw nummer, ‘telefoon kapot’, spoedrekening, ‘kan nu niet bellen’, rekening op andermans naam','Bel het oude nummer of stel een vraag die alleen die persoon weet'],['Bankhelpdeskfraude','Beller toont het echte banknummer, ‘rekening gehackt’, ‘maak geld over naar een veilige kluisrekening’, koerier haalt pas op, AnyDesk/TeamViewer installeren','Ophangen. Bel zelf je bank via het officiële nummer'],['Vals betaalverzoek (Tikkie)','Link die niet begint met het officiële bankadres; pagina vraagt in te loggen ‘om geld te ontvangen’','Echte betaalverzoeken lopen altijd via iDEAL; om geld te ontvangen hoef je nooit in te loggen'],['Nephuurwoning','Huur of borg betalen vóór bezichtiging, alleen foto’s, ‘verhuurder in het buitenland’','Niet betalen vóór bezichtiging, controle van verhuurder en getekend contract'],['Geldezel-werving','‘Makkelijk bijverdienen’ door je rekening of pas uit te lenen','Direct weigeren en melden bij politie of bank'],['Nepwebshop','Extreem lage prijzen, geen KVK-nummer of afwijkend adres, vooruitbetalen naar buitenlandse rekening','Check het Handelsregister van KVK en keurmerken vóór betalen'],['Valse QR-code (quishing)','QR-sticker op parkeerautomaat, ‘bankbrief’ die vraagt een code te scannen','Scan alleen wat je verwacht; betaal via de officiële app']],['Soort','Rode vlaggen','Wat doe je'])
+'<h2 id="tax">Valse berichten van Belastingdienst en Toeslagen</h2><p>Volgens de officiële pagina van de Belastingdienst:</p><ul><li><strong>Geen directe betaalverzoeken</strong>, en geen meldingen van betalingsachterstanden via WhatsApp of e-mail.</li><li>Geen verzoeken om persoonsgegevens via WhatsApp, sms of e-mail, en nooit de vraag je bankrekening te bevestigen via iDEAL of Wero.</li><li>Een QR-code in een echte brief leidt naar ‘Overzicht betalen en ontvangen’, <strong>nooit direct naar een betaalomgeving</strong>.</li><li>Echte post komt als brief of aanslag en is terug te vinden in Mijn Belastingdienst of Mijn Toeslagen.</li><li>Vóór je betaalt: vergelijk het rekeningnummer met de <strong>lijst officiële rekeningnummers</strong> op de phishingpagina van de Belastingdienst (huidige lijst geldig vanaf 1 mei 2026).</li></ul><p><strong>Melden:</strong> stuur het valse bericht naar <strong>valse-email@belastingdienst.nl</strong> (alleen voor meldingen), met telefoonnummers, rekeningnummers, websites en een screenshot. Geld overgemaakt? <strong>Neem meteen contact op met je bank</strong>. Hetzelfde geldt voor berichten namens het CJIB: controleer altijd zelf via de officiële site (zie <a href="/nl/articles/traffic-fines-cjib.html">Verkeersboetes en CJIB</a>).</p>'
+'<h2 id="digid">DigiD-phishing</h2><p>DigiD stuurt automatisch een e-mail of sms als er iets verandert in je account (aanvraag, activatie van de app, gewijzigde gegevens, verlopen DigiD). Maar <strong>DigiD-medewerkers vragen nooit om je inloggegevens</strong>. Wie je gebruikersnaam, wachtwoord of activeringscode heeft, kan namens jou inloggen bij Belastingdienst, Toeslagen en zorgverzekeraar. Stuur verdachte berichten door naar <strong>valse-email@digid.nl</strong> en verwijder ze. Gegevens afgegeven? Volg op digid.nl de stappen bij ‘inloggegevens gestolen’ en neem contact op met de helpdesk. Zie ook <a href="/nl/articles/digid-registration-guide.html">DigiD aanvragen</a>.</p>'
+'<h2 id="whatsapp">‘Hoi mam/pap’-fraude via WhatsApp</h2><p>De politie noemt dit <strong>hulpvraagfraude</strong> of vriend-in-noodfraude: iemand doet zich via WhatsApp of e-mail voor als familielid of bekende en vraagt om geld. Meestal: eerst een ‘nieuw nummer’, daarna ‘een rekening die vandaag betaald moet worden’. <strong>Bel altijd het oude nummer</strong>, vraag om een spraakbericht of stel een persoonlijke vraag. Betaald? Direct je bank, daarna aangifte. Online aangifte kan met DigiD, <strong>behalve</strong> als jouw identiteit of jouw WhatsApp-account is misbruikt om anderen op te lichten; bel dan <strong>0900-8844</strong> voor een afspraak.</p>'
+'<h2 id="bank">Bankhelpdeskfraude en de ‘veilige rekening’</h2><p>Oplichters bellen soms met het <strong>echte telefoonnummer van je eigen bank</strong> in beeld (spoofing). Ze zeggen dat je rekening niet veilig is en dat je geld tijdelijk naar een ‘veilige kluisrekening’ moet, of dat een koerier je pas komt ophalen, of vragen je AnyDesk of TeamViewer te installeren. Soms doen ze zich voor als Belastingdienst of een andere instantie. Volgens Veilig Bankieren doet je bank <strong>nooit</strong>:</p><ul><li>vragen om geld over te maken via telefoon of sms;</li><li>een medewerker sturen om je pas of inlogapparaat op te halen;</li><li>vragen om pincode, wachtwoorden of beveiligingscodes;</li><li>toegang vragen tot je computer of smartphone of je meekijksoftware laten installeren.</li></ul><p><strong>Wat doe je:</strong> ophangen, zelf je bank bellen, de aanwijzingen van de bankmedewerker volgen en aangifte doen.</p>'
+'<h2 id="marktplaats">Marktplaats en betaalverzoeken (Tikkie)</h2><ul><li>Een echt Tikkie-verzoek (ABN AMRO) begint met <strong>https://www.tikkie.me/pay/</strong>, een Rabobank-verzoek met <strong style="overflow-wrap:anywhere">https://betaalverzoek.rabobank.nl/betaalverzoek</strong>; betalen gaat <strong>altijd via iDEAL</strong>.</li><li><strong>Als verkoper hoef je nooit</strong> te betalen of in te loggen bij je bank om geld te ontvangen. Een ‘ontvangstlink’ of ‘verificatie met 1 cent’ die dat vraagt, is een rode vlag.</li><li>Snel van het platform naar WhatsApp willen, of een vreemde ‘verzendlink’: stop.</li><li>Iets gekocht en niets ontvangen, iets verkocht en niet betaald, of een namaakproduct gekregen? Doe <strong>online aangifte</strong> via politie.nl. Na <strong>tien weken</strong> krijg je een e-mail of er een onderzoek is gestart; zonder onderzoek volgt binnen <strong>zes maanden</strong> een afsluitbericht.</li></ul>'
+'<h2 id="rent">Nephuurwoningen en borg</h2><p>Volgens het Openbaar Ministerie doen oplichters zich voor als verhuurder van een woning die niet van hen is of die ze nooit willen verhuren. Slachtoffers maken vooraf huur over op basis van een beschrijving en foto’s op internet, naar een rekening die niet van de ‘verhuurder’ is. Regels: betaal niets vóór je de woning <strong>hebt gezien</strong>, de <strong>verhuurder of makelaar hebt gecontroleerd</strong> en een <strong>schriftelijk contract</strong> hebt; stuur geen kopie van je paspoort of verblijfsvergunning naar iemand die je niet hebt gecontroleerd. Je rechten rond de borg (maximum en terugbetaaltermijn) staan in <a href="/nl/articles/tenant-rights-netherlands.html">Rechten van huurders</a>.</p>'
+'<h2 id="mule">Geldezel: ‘makkelijk geld’ met grote gevolgen</h2><p>Een geldezel is iemand van wie de bankrekening door criminelen wordt gebruikt om geld wit te wassen. Werving gaat via internet, chat, telefoon en soms bij scholen, met het verhaal van ‘een lucratieve bijbaan van een paar uur’. De geldezel maakt ontvangen geld door naar buitenlandse rekeningen tegen een percentage, of leent zijn pas uit zodat de crimineel het geld opneemt. De gevolgen zijn volgens Veilig Bankieren ‘ingrijpend’:</p>'
+T([['Strafvervolging','Je wordt vervolgd voor betrokkenheid bij fraude en kunt een strafblad krijgen'],['Terugbetalen','Je moet al het verdwenen geld terugbetalen; dat leidt tot hoge schulden'],['Waarschuwingssysteem','Registratie in het incidentenwaarschuwingssysteem van financiële instellingen voor <strong>8 jaar</strong>: moeilijk een lening, hypotheek of bankdiensten krijgen'],['Geen bankrekening','Mogelijk kun je geen nieuwe rekening openen, lastig voor je salaris']],['Gevolg','Uitleg'])
+'<p>Benaderd of al betrokken? Bel de politie op <strong>0900-8844</strong> (spoed: 112), meld anoniem via <strong>Meld Misdaad Anoniem 0800-7000</strong>, en informeer je bank.</p>'
+'<h2 id="shops">Nepwebshops en quishing</h2><p><strong>KVK</strong> adviseert vijf checks: (1) past de activiteit in het Handelsregister bij wat de shop verkoopt? (2) klopt het adres op de site met het Handelsregister? (3) staan adres, e-mail en KVK-nummer op de site? Gebruik eventueel de ScamCheck van KVK; (4) betaal veilig: creditcard, iDEAL/Wero, PayPal of achteraf betalen, en vermijd vooruitbetalen naar buitenlandse rekeningen of tussenpersonen; (5) zoek onafhankelijke keurmerken zoals <strong>Thuiswinkel Waarborg</strong> of Webshop Keurmerk en echte reviews. Bij <strong>quishing</strong> (phishing met QR-codes) zitten valse codes op parkeerautomaten, in brieven, reclame, e-mails en valse ‘bankbrieven’. Vraag jezelf af: verwachtte ik deze QR-code?</p>'
+'<h2 id="examples">Oefenberichten</h2><p><strong>Illustratief, geen echte personen</strong>. Wij schreven deze voorbeelden zelf om de signalen te leren; ze zijn niet overgenomen van berichten van slachtoffers:</p>'
+T([['Sms: ‘Belastingdienst: u heeft een openstaande schuld van € 87. Betaal vandaag via de link om beslag te voorkomen’','De Belastingdienst stuurt geen directe betaalverzoeken of betaallinks; haast en dreiging','Verwijderen, melden bij valse-email@belastingdienst.nl, zelf checken in Mijn Belastingdienst'],['WhatsApp: ‘Mam, dit is mijn nieuwe nummer, telefoon is gevallen. Kun je vandaag € 650 voor een rekening voorschieten?’','Nieuw nummer + spoedgeld + rekening op andere naam','Eerst het oude nummer bellen'],['Telefoon: ‘Ik bel van de veiligheidsafdeling van uw bank, uw rekening is gehackt, zet uw saldo op een veilige rekening’','Een bank vraagt nooit telefonisch om geld over te maken','Ophangen en zelf je bank bellen'],['Marktplaats: ‘Klik hier om je verkoopbedrag te ontvangen, log in bij je bank en betaal € 0,01 ter verificatie’','Voor ontvangen hoef je niet in te loggen of te betalen','Niet klikken; geef alleen je rekeningnummer als je wilt'],['Advertentie: ‘2-kamerappartement € 650, ik zit in het buitenland, maak de borg over en ik stuur de sleutel’','Betalen vóór bezichtiging, verhuurder afwezig, te mooi prijsje','Niet betalen; meld bij het platform en de Fraudehelpdesk']],['Bericht (verzonnen voorbeeld)','Waarom vals','Wat doe je'])
+'<h2 id="steps">Erin getuind? Doe dit nu, in deze volgorde</h2><ol><li><strong>Bel direct je bank</strong> en laat pas of rekening blokkeren en betalingen stoppen. Vaak kun je je pas zelf blokkeren in de bankapp.</li><li><strong>Wijzig wachtwoorden</strong> (e-mail, DigiD, bank). Bijlage geopend of software geïnstalleerd? Laat je apparaat controleren en bankier niet online tot het schoon is.</li><li><strong>Bewaar bewijs</strong>: bericht, screenshots, telefoonnummer, ontvangende rekening, afschriften.</li><li><strong>Doe aangifte</strong> via politie.nl (vaak met DigiD) of via 0900-8844.</li><li><strong>Meld het bij de Fraudehelpdesk</strong> via fraudehelpdesk.nl of 088 786 73 72.</li><li><strong>Stuur het valse bericht door</strong> naar de nagebootste organisatie: valse-email@belastingdienst.nl, valse-email@digid.nl of het phishingadres van je bank.</li><li><strong>Identiteit misbruikt</strong> (rekening, lening of abonnement op jouw naam)? Meld het bij het <strong>CMI</strong> via het meldformulier op rvig.nl en doe aangifte.</li></ol>'
+'<h2 id="contacts">Wie bel je?</h2>'
+T([['Pas blokkeren: ABN AMRO','0900 00 24 (buitenland: +31 10 241 17 20)'],['Pas blokkeren: ING','+31 (0)20 22 888 00'],['Pas blokkeren: Rabobank','+31 (0)88 722 67 67'],['Pas blokkeren: ASN Bank','+31 (0)70 356 93 35'],['Pas blokkeren: overige banken','0800 03 13 (gratis)'],['Politie (geen spoed / aangifte)','0900-8844 of politie.nl; spoed 112'],['Fraudehelpdesk','088 786 73 72 of fraudehelpdesk.nl/fraude-melden'],['Anoniem melden','Meld Misdaad Anoniem 0800-7000'],['Identiteitsfraude','CMI van RvIG: meldformulier op rvig.nl'],['Valse berichten Belastingdienst/Toeslagen','valse-email@belastingdienst.nl'],['Valse berichten DigiD','valse-email@digid.nl']],['Situatie','Instantie en nummer'])
+'<h2 id="refund">Krijg ik mijn geld terug?</h2><p>Er is geen algemene garantie; je bank beslist. Wat officiële bronnen zeggen:</p><ul><li><strong>Bankhelpdeskfraude</strong>: banken vergoeden slachtoffers meestal ‘uit coulance’, onder voorwaarden, waaronder: aangifte gedaan, het gaat om een particuliere rekening en het is de eerste keer. Aanvullende voorwaarden staan bij de NVB.</li><li>De <strong>uniforme veiligheidsregels</strong> vragen: codes geheimhouden, pas niet uitlenen, apparaten beveiligen, je rekening controleren (elke twee weken) en <strong>incidenten direct melden</strong>. De bank kijkt of je je hieraan hebt gehouden.</li><li>Hoe sneller je belt, hoe groter de kans dat een betaling nog te stoppen is.</li><li>Wijst de bank je klacht af, dan kun je naar het <strong>Kifid</strong> (Klachteninstituut Financiële Dienstverlening).</li></ul><p>Door het verlies in de schulden geraakt? Zie <a href="/nl/articles/debt-help-schuldhulp.html">Gratis schuldhulp</a>.</p>'
+'<h2 id="mistakes">Veelgemaakte fouten</h2><ol><li><strong>Het nummer uit het bericht bellen</strong> in plaats van het officiële nummer van de bank.</li><li><strong>Vertrouwen op het nummer in beeld</strong>: dat kan vervalst zijn.</li><li><strong>Een sms-code of DigiD-code doorgeven</strong> ‘ter verificatie’.</li><li><strong>Je rekening of pas uitlenen</strong> aan een vriend of ‘werkgever’ voor geld.</li><li><strong>Borg betalen</strong> vóór bezichtiging en contract.</li><li><strong>Uit schaamte te laat melden</strong>: tijd is cruciaal om geld tegen te houden.</li><li><strong>Geen aangifte bij een klein bedrag</strong>: aangiftes helpen de politie zaken te koppelen.</li></ol>'
+'<h2 id="help">Gratis hulp</h2><ul><li><strong>Fraudehelpdesk</strong>: advies en doorverwijzing voor slachtoffers (088 786 73 72).</li><li><strong>Politie</strong>: 0900-8844 of online aangifte.</li><li><strong>CMI</strong>: ondersteuning bij de gevolgen van identiteitsfraude en bemiddeling met betrokken organisaties.</li><li><strong>Veilig Bankieren</strong> en <strong>Veilig Internetten</strong>: uitleg over de nieuwste trucs.</li><li><strong>Juridisch Loket</strong>: gratis juridisch advies als je geld wilt terughalen van een bekende oplichter.</li></ul>'
+'<h2 id="related">Gerelateerde gidsen</h2><ul><li><a href="/nl/articles/digid-registration-guide.html">DigiD aanvragen</a></li><li><a href="/nl/articles/traffic-fines-cjib.html">Verkeersboetes en CJIB</a></li><li><a href="/nl/articles/tenant-rights-netherlands.html">Rechten van huurders</a></li><li><a href="/nl/articles/toeslagen-income-update.html">Inkomen doorgeven aan Toeslagen</a></li><li><a href="/nl/articles/debt-help-schuldhulp.html">Gratis schuldhulp</a></li></ul>'),
faq=[('Stuurt de Belastingdienst een sms of WhatsApp met een betaallink?','Nee. De Belastingdienst stuurt geen directe betaalverzoeken en meldt achterstanden niet via WhatsApp of e-mail. Controleer in Mijn Belastingdienst of Mijn Toeslagen.'),
('Waar meld ik een vals bericht namens de Belastingdienst?','Stuur het naar valse-email@belastingdienst.nl, met screenshot en eventuele telefoon- of rekeningnummers.'),
('De ‘bank’ belde met het echte nummer. Is het dan echt?','Niet per se: oplichters vervalsen het nummer in beeld. Hang op en bel zelf je bank. Een bank vraagt nooit om geld naar een ‘veilige rekening’ over te maken.'),
('Mijn ‘zoon’ appt vanaf een nieuw nummer om geld. Wat nu?','Bel eerst het oude nummer of stel een persoonlijke vraag. Dit is de bekende hulpvraagfraude.'),
('Ik heb geld overgemaakt aan een oplichter. Wat eerst?','Bel direct je bank, doe daarna aangifte en meld het bij de Fraudehelpdesk (088 786 73 72).'),
('Krijg ik mijn geld terug van de bank?','Geen algemene garantie. Bij bankhelpdeskfraude vergoeden banken meestal uit coulance, onder voorwaarden zoals aangifte, een particuliere rekening en de eerste keer.'),
('Iemand biedt geld om mijn rekening te gebruiken. Is dat erg?','Ja, dan ben je een geldezel: strafvervolging, terugbetalen en 8 jaar registratie in het waarschuwingssysteem van financiële instellingen.'),
('Kan ik online aangifte doen?','Vaak wel, met DigiD, bijvoorbeeld bij koop-/verkoopfraude en hulpvraagfraude. Is jouw identiteit of WhatsApp-account misbruikt, bel dan 0900-8844.'),
('Hoe weet ik of een webshop betrouwbaar is?','Controleer KVK-nummer en adres in het Handelsregister, kijk naar keurmerken zoals Thuiswinkel Waarborg en betaal veilig, niet vooraf naar een buitenlandse rekening.'),
('Mijn identiteitsgegevens zijn misbruikt. Waar kan ik terecht?','Doe aangifte, informeer je bank en vul het meldformulier van het Centraal Meldpunt Identiteitsfraude (CMI) in op rvig.nl.')],
src_note='Gecontroleerd bij Belastingdienst, DigiD, Veilig Bankieren, politie, Rijksoverheid, RvIG, KVK, Openbaar Ministerie en Veilig Internetten op 7 oktober 2026. Banknummers komen van Veilig Bankieren en kunnen wijzigen; check je pas of de site van je bank. Telefoonnummer CMI en openingstijden Fraudehelpdesk niet vermeld omdat we die niet exact konden verifiëren. Oefenberichten zijn verzonnen ter illustratie.')
