from a_student_finance import T
SLUG='single-parent-support'
B='https://www.belastingdienst.nl/wps/wcm/connect/'
SRC=[('Dienst Toeslagen · Veranderingen toeslagen 2026',B+'nl/toeslagen-2026/topics/veranderingen-toeslagen-2026'),
('Rijksoverheid · Wat verandert er op 1 januari 2026','https://www.rijksoverheid.nl/actueel/nieuws/2025/12/16/wat-verandert-er-op-1-januari-2026'),
('Dienst Toeslagen · Maximaal vermogen kindgebonden budget',B+'nl/kindgebonden-budget/content/maximaal-vermogen-kindgebonden-budget'),
('Belastingdienst · Inkomensafhankelijke combinatiekorting 2026',B+'bldcontentnl/belastingdienst/prive/inkomstenbelasting/heffingskortingen_boxen_tarieven/heffingskortingen/inkomensafhankelijke_combikorting/inkomensafhankelijke-combinatiekorting-2026'),
('Belastingdienst · Voorwaarden inkomensafhankelijke combinatiekorting',B+'nl/aftrek-en-kortingen/content/voorwaarden-inkomensafhankelijke-combinatiekorting'),
('Rijksoverheid · Nieuwe regels bijstand 2026 en 2027','https://www.rijksoverheid.nl/themas/belastingen-uitkeringen-en-toeslagen/bijstand/nieuwe-regels-bijstand-2026-en-2027'),
('Dienst Toeslagen · Proefberekening toeslagen',B+'nl/toeslagen/content/hulpmiddel-proefberekening-toeslagen')]

AR=dict(title='دعم الوالد الوحيد في هولندا 2026: ميزانية الأطفال وإضافة الوالد الوحيد، خصم الجمع بين العمل ورعاية الأطفال، بدل الحضانة 96%، والمساعدة الاجتماعية الأعلى — مع أمثلة محسوبة',
crumb='الوالد الوحيد',
seo_title='دعم الوالد الوحيد alleenstaande ouder 2026',
desc='دعم الوالد الوحيد في هولندا 2026: إضافة الوالد الوحيد في ميزانية الأطفال، خصم IACK حتى 3,032 يورو، بدل حضانة حتى 96%، ومساعدة اجتماعية أعلى.',
summary='<ol><li><strong>ميزانية الأطفال</strong> فيها <strong>إضافة للوالد الوحيد</strong> (ALO-kop)، وارتفعت في 2026 للوالد الوحيد بدخل حتى <strong>29,736 يورو</strong>.</li><li><strong>خصم الجمع (IACK)</strong> إن كنت تعمل ولديك طفل تحت 12: حتى <strong>3,032 يورو</strong> سنوياً من ضريبتك.</li><li><strong>بدل الحضانة</strong>: حتى <strong>96%</strong> من السعر الأقصى بالساعة لدخل حتى نحو 56,413 يورو.</li><li><strong>المساعدة الاجتماعية:</strong> منذ 2026 يمكن للوالد الوحيد الذي لا يكفيه دخله الحصول على مبلغ أعلى، يقارب إضافة الوالد الوحيد.</li><li>حد المدخرات لميزانية الأطفال: <strong>146,011 يورو</strong> دون شريك بدلات (1 يناير).</li></ol>',
body=(
'<h2 id="overview">كل الدعم في جدول واحد</h2>'
+T([['ميزانية الأطفال + إضافة الوالد الوحيد','شهرياً من Dienst Toeslagen','حسب الدخل وعدد الأطفال وأعمارهم','<a href="/articles/kindgebonden-budget-guide.html">الدليل</a>'],
    ['إعانة الأطفال (kinderbijslag)','كل 3 أشهر من SVB','لكل الأطفال تحت 18 بغض النظر عن الدخل','<a href="/articles/kinderbijslag-guide.html">الدليل</a>'],
    ['خصم الجمع IACK','يقلل ضريبتك','إن كنت تعمل ولديك طفل تحت 12','أدناه'],
    ['بدل الحضانة','شهرياً','إن كنت تعمل أو تدرس وطفلك في حضانة مسجلة','<a href="/articles/childcare-allowance-kinderopvangtoeslag.html">الدليل</a>'],
    ['بدل الإيجار وبدل الرعاية','شهرياً','حسب الدخل','<a href="/articles/housing-rent-allowance-2026.html">الإيجار</a>، <a href="/articles/zorgtoeslag-guide.html">الرعاية</a>'],
    ['المساعدة الاجتماعية (أعلى للوالد الوحيد منذ 2026)','شهرياً من البلدية','إن كان دخلك لا يكفي','<a href="/articles/social-assistance-bijstand.html">الدليل</a>'],
    ['دعم البلدية للأطفال','حسب البلدية','دخل منخفض','<a href="/articles/special-assistance-bijzondere-bijstand.html">الدليل</a>']],
   ['الدعم','كيف يُدفع','لمن','اقرأ'])
+'<h2 id="kgb">ميزانية الأطفال وإضافة الوالد الوحيد</h2><ul><li>كوالد وحيد تحصل على ميزانية الأطفال العادية <strong>زائد إضافة الوالد الوحيد</strong> (alleenstaande-ouderkop).</li><li>في 2026 ارتفعت ميزانية الأطفال للوالد الوحيد بدخل حتى <strong>29,736 يورو</strong> (وللأزواج حتى 39,141 يورو)؛ أصحاب الدخل الأعلى يحصلون على أقل قليلاً.</li><li>حد المدخرات في 1 يناير: <strong>146,011 يورو</strong> دون شريك بدلات (184,633 معه)؛ إن تجاوزته فلا حق طوال السنة.</li><li>المبالغ الدقيقة لكل طفل تعتمد على دخلك؛ احسبها بـ«الحسبة التجريبية» الرسمية (رابط في المصادر). لم نتمكن من قراءة جدول المبالغ الرسمي لـ2026 مباشرة، لذلك لا ننشر أرقاماً غير مؤكدة.</li><li><strong>مهم:</strong> إن سكن معك شريك جديد قد يصبح «شريك بدلات» وتفقد إضافة الوالد الوحيد (<a href="/articles/toeslagpartner-guide.html">من هو شريك البدلات</a>).</li></ul>'
'<h2 id="iack">خصم الجمع بين العمل والأطفال (IACK)</h2>'
+T([['دخل العمل حتى 6,239 يورو','لا خصم'],['من 6,239 حتى 32,710 يورو','11.45% من الدخل فوق 6,239'],['32,711 يورو فأكثر','<strong>3,032 يورو</strong> (الحد الأقصى)']],['دخلك من العمل (2026)','الخصم السنوي'])
+'<p><strong>الشروط:</strong> طفل وُلد بعد 31 ديسمبر 2013 (أصغر من 12 في 1 يناير 2026)، دخل عمل فوق 6,239 يورو، الطفل في بيتك 6 أشهر على الأقل (للوالدين المنفصلين 156 يوماً على الأقل عند كل منهما)، ولا شريك ضريبي (أو أقل من 6 أشهر، أو دخلك أقل منه). يُحسب تلقائياً في الإقرار الضريبي (<a href="/articles/annual-tax-return-2026.html">الإقرار</a>).</p>'
'<h2 id="examples">أمثلة محسوبة (توضيحية)</h2>'
+T([['سارة، تعمل جزئياً، دخل عمل 20,000 يورو، طفل عمره 5','IACK = (20,000 − 6,239) × 11.45% = <strong>1,575.63 يورو</strong> خصم ضريبي في السنة'],
    ['أحمد، يعمل بدوام كامل، دخل عمل 36,000 يورو، طفلان 3 و9 سنوات','فوق 32,711 ← IACK = <strong>3,032 يورو</strong> (الحد الأقصى)'],
    ['مريم، دخل عمل 5,500 يورو، طفل عمره 2','تحت 6,239 ← <strong>لا IACK</strong>؛ لكنها غالباً تستحق ميزانية الأطفال وإضافة الوالد الوحيد كاملة، وقد تستحق المساعدة الاجتماعية'],
    ['خالد، طفله عمره 13','لا IACK لأن الطفل فوق 12؛ تبقى ميزانية الأطفال وإعانة الأطفال']],
   ['الحالة','النتيجة'])
+'<p>الأسماء والأرقام أمثلة توضيحية مبنية على القواعد الرسمية لـ2026، وليست حالات أشخاص حقيقيين. احسب وضعك بنفسك بالأدوات الرسمية.</p>'
'<h2 id="childcare">بدل الحضانة للوالد الوحيد العامل</h2><ul><li>إن كان دخلك حتى نحو <strong>56,413 يورو</strong> تحصل على <strong>96%</strong> من السعر الأقصى بالساعة (المصدران الرسميان يختلفان بيورو واحد).</li><li>السعر الأقصى بالساعة 2026: حضانة نهارية <strong>11.23</strong> يورو، رعاية بعد المدرسة <strong>9.98</strong> يورو، مربية منزلية <strong>8.49</strong> يورو.</li><li><strong>مثال:</strong> حضانة نهارية 100 ساعة شهرياً بسعر 11.23 = 1,123 يورو؛ 96% = <strong>1,078.08 يورو</strong> بدل، وتدفع أنت نحو 44.92 يورو، إن كان سعر الحضانة لا يتجاوز الحد.</li></ul>'
'<h2 id="bijstand">المساعدة الاجتماعية للوالد الوحيد</h2><p>منذ 2026 يمكن للوالد الوحيد الذي لا يكفيه دخله الحصول على <strong>مساعدة أعلى</strong>، والزيادة تقارب إضافة الوالد الوحيد في ميزانية الأطفال. لا تنطبق إن كان لديك شريك بدلات. التفاصيل في <a href="/articles/social-assistance-bijstand.html">دليل المساعدة الاجتماعية</a>.</p>'
'<h2 id="steps">خطة عملية للوالد الوحيد الجديد (بعد الانفصال)</h2><ol><li>سجّل عنوانك الجديد في البلدية.</li><li>أبلغ Toeslagen بالانفصال خلال 4 أسابيع، واحذف الشريك.</li><li>اطلب أو حدّث ميزانية الأطفال (تُضاف إضافة الوالد الوحيد تلقائياً عند الاستحقاق).</li><li>تأكد أن إعانة الأطفال من SVB تُدفع لك.</li><li>اتفق على النفقة وترتيبات الأطفال كتابياً (Juridisch Loket).</li><li>إن كنت تعمل: اطلب بدل الحضانة (يشمل أيضاً رعاية ما بعد <a href="/articles/dutch-school-system-basisschool.html">المدرسة الابتدائية</a>).</li><li>إن لم يكفِ الدخل: اطلب المساعدة الاجتماعية وإعفاء ضرائب البلدية.</li></ol>'
'<h2 id="mistakes">أخطاء شائعة</h2><ol><li>بقاء الشريك السابق مسجلاً على العنوان.</li><li>شريك جديد على العنوان دون فهم أثره على البدلات.</li><li>عدم تحديث الدخل بعد بدء عمل.</li><li>نسيان خصم IACK في الإقرار حين يعمل الوالد عبر وكالات أو بعقود قصيرة.</li></ol>'),
faq=[('هل يحصل الوالد الوحيد على مبلغ إضافي؟','نعم، إضافة الوالد الوحيد في ميزانية الأطفال، وارتفعت في 2026 للدخل حتى 29,736 يورو.'),
('ما هو IACK وكم قيمته؟','خصم ضريبي للوالد العامل بطفل تحت 12: 11.45% من الدخل فوق 6,239 يورو، حتى 3,032 يورو سنوياً.'),
('كم بدل الحضانة؟','حتى 96% من السعر الأقصى بالساعة لدخل حتى نحو 56,413 يورو.'),
('هل المساعدة الاجتماعية أعلى للوالد الوحيد؟','منذ 2026 يمكن الحصول على مساعدة أعلى تقارب إضافة الوالد الوحيد، إن لم يكن لديك شريك بدلات.'),
('هل أفقد الإضافة إن سكن معي شريك جديد؟','غالباً نعم إن أصبح شريك بدلات.')],
src_note='راجعنا Belastingdienst وDienst Toeslagen وRijksoverheid في 5 أكتوبر 2026. لم نتمكن من قراءة جداول مبالغ ميزانية الأطفال وإعانة الأطفال لعام 2026 مباشرة؛ استخدم الحسبة التجريبية الرسمية. الأمثلة توضيحية.')

NL=dict(title='Steun voor alleenstaande ouders in 2026: kindgebonden budget met alleenstaande-ouderkop, IACK, kinderopvangtoeslag tot 96% en hogere bijstand — met rekenvoorbeelden',
crumb='Alleenstaande ouder',
seo_title='Alleenstaande ouder 2026: alle steun op een rij',
desc='Steun voor alleenstaande ouders 2026: ALO-kop in het kindgebonden budget, IACK tot € 3.032, kinderopvangtoeslag tot 96% en hogere bijstand.',
summary='<ol><li>Het <strong>kindgebonden budget</strong> heeft een <strong>alleenstaande-ouderkop</strong>; in 2026 hoger voor alleenstaande ouders met een inkomen tot <strong>€ 29.736</strong>.</li><li><strong>IACK</strong> als je werkt en een kind onder 12 hebt: tot <strong>€ 3.032</strong> per jaar.</li><li><strong>Kinderopvangtoeslag</strong>: tot <strong>96%</strong> van de maximale uurprijs bij inkomen tot circa € 56.413.</li><li><strong>Bijstand:</strong> sinds 2026 kan een alleenstaande ouder die te weinig overhoudt een hogere uitkering krijgen, ongeveer gelijk aan de ALO-kop.</li><li>Vermogensgrens kindgebonden budget: <strong>€ 146.011</strong> zonder toeslagpartner (1 januari).</li></ol>',
body=(
'<h2 id="overview">Alle steun op een rij</h2>'
+T([['Kindgebonden budget + ALO-kop','Maandelijks, Dienst Toeslagen','Afhankelijk van inkomen, aantal en leeftijd kinderen','<a href="/nl/articles/kindgebonden-budget-guide.html">gids</a>'],['Kinderbijslag','Per kwartaal, SVB','Alle kinderen onder 18','<a href="/nl/articles/kinderbijslag-guide.html">gids</a>'],['IACK','Lagere belasting','Werkende ouder met kind onder 12','Hieronder'],['Kinderopvangtoeslag','Maandelijks','Werken of studeren, geregistreerde opvang','<a href="/nl/articles/childcare-allowance-kinderopvangtoeslag.html">gids</a>'],['Huur- en zorgtoeslag','Maandelijks','Inkomensafhankelijk','<a href="/nl/articles/housing-rent-allowance-2026.html">huur</a>, <a href="/nl/articles/zorgtoeslag-guide.html">zorg</a>'],['Bijstand (hoger voor alleenstaande ouders)','Maandelijks, gemeente','Als het inkomen tekortschiet','<a href="/nl/articles/social-assistance-bijstand.html">gids</a>'],['Gemeentelijke kindregelingen','Per gemeente','Laag inkomen','<a href="/nl/articles/special-assistance-bijzondere-bijstand.html">gids</a>']],['Regeling','Uitbetaling','Voor wie','Lees'])
+'<h2 id="kgb">Kindgebonden budget en ALO-kop</h2><ul><li>Als alleenstaande ouder krijg je het gewone kindgebonden budget <strong>plus de alleenstaande-ouderkop</strong>.</li><li>In 2026 steeg het voor alleenstaande ouders met inkomen tot <strong>€ 29.736</strong> (stellen tot € 39.141); hogere inkomens krijgen iets minder.</li><li>Vermogensgrens op 1 januari: <strong>€ 146.011</strong> zonder toeslagpartner (€ 184.633 met); daarboven geen recht voor het hele jaar.</li><li>De exacte bedragen hangen af van je inkomen; gebruik de officiële proefberekening. De tabel 2026 konden we niet rechtstreeks lezen, dus noemen we geen onbevestigde bedragen.</li><li><strong>Let op:</strong> een nieuwe huisgenoot kan toeslagpartner worden en dan vervalt de ALO-kop (<a href="/nl/articles/toeslagpartner-guide.html">toeslagpartner</a>).</li></ul>'
'<h2 id="iack">Inkomensafhankelijke combinatiekorting (IACK)</h2>'
+T([['Tot € 6.239','Geen korting'],['€ 6.239 – € 32.710','11,45% van het inkomen boven € 6.239'],['Vanaf € 32.711','<strong>€ 3.032</strong> (maximum)']],['Arbeidsinkomen 2026','Korting per jaar'])
+'<p><strong>Voorwaarden:</strong> kind geboren na 31 december 2013, arbeidsinkomen boven € 6.239, kind minstens 6 maanden in je huishouden (co-ouders minimaal 156 dagen per jaar bij elk), geen fiscale partner (of korter dan 6 maanden, of je verdient minder). Wordt automatisch berekend in je aangifte (<a href="/nl/articles/annual-tax-return-2026.html">aangifte</a>).</p>'
'<h2 id="examples">Rekenvoorbeelden (illustratief)</h2>'
+T([['Sara, parttime, arbeidsinkomen € 20.000, kind van 5','IACK = (20.000 − 6.239) × 11,45% = <strong>€ 1.575,63</strong> per jaar'],['Ahmed, fulltime, € 36.000, kinderen van 3 en 9','Boven € 32.711 → <strong>€ 3.032</strong>'],['Maryam, € 5.500, kind van 2','Onder € 6.239 → <strong>geen IACK</strong>; wel waarschijnlijk volledig kindgebonden budget met ALO-kop en mogelijk bijstand'],['Khaled, kind van 13','Geen IACK (kind ouder dan 12); kindgebonden budget en kinderbijslag blijven']],['Situatie','Uitkomst'])
+'<p>Namen en bedragen zijn illustratieve voorbeelden op basis van de officiële regels 2026, geen echte personen.</p>'
'<h2 id="childcare">Kinderopvangtoeslag als werkende alleenstaande ouder</h2><ul><li>Bij inkomen tot circa <strong>€ 56.413</strong>: <strong>96%</strong> van de maximale uurprijs (de twee officiële bronnen verschillen € 1).</li><li>Maximale uurprijs 2026: dagopvang <strong>€ 11,23</strong>, bso <strong>€ 9,98</strong>, gastouder <strong>€ 8,49</strong>.</li><li><strong>Voorbeeld:</strong> 100 uur dagopvang per maand × € 11,23 = € 1.123; 96% = <strong>€ 1.078,08</strong> toeslag, eigen deel circa € 44,92 (als de opvang niet duurder is dan het maximum).</li></ul>'
'<h2 id="bijstand">Bijstand voor alleenstaande ouders</h2><p>Sinds 2026 kan een alleenstaande ouder die te weinig overhoudt een <strong>hogere bijstand</strong> krijgen, ongeveer zo hoog als de ALO-kop; niet met een toeslagpartner. Zie <a href="/nl/articles/social-assistance-bijstand.html">bijstand</a>.</p>'
'<h2 id="steps">Stappenplan na een scheiding</h2><ol><li>Nieuw adres bij de gemeente.</li><li>Scheiding binnen 4 weken doorgeven aan Toeslagen; partner verwijderen.</li><li>Kindgebonden budget aanvragen of aanpassen.</li><li>Kinderbijslag op jouw naam bij de SVB.</li><li>Alimentatie en zorgregeling op papier (Juridisch Loket).</li><li>Werk je: kinderopvangtoeslag (ook voor bso naast de <a href="/nl/articles/dutch-school-system-basisschool.html">basisschool</a>).</li><li>Te weinig inkomen: bijstand en kwijtschelding.</li></ol>'
'<h2 id="mistakes">Veelgemaakte fouten</h2><ol><li>Ex-partner blijft op het adres ingeschreven.</li><li>Nieuwe partner op het adres zonder het effect te kennen.</li><li>Inkomen niet bijwerken na nieuw werk.</li><li>IACK vergeten bij flexwerk.</li></ol>'),
faq=[('Krijgt een alleenstaande ouder extra?','Ja, de alleenstaande-ouderkop in het kindgebonden budget; in 2026 hoger bij inkomen tot € 29.736.'),
('Wat is de IACK?','Een belastingkorting voor werkende ouders met een kind onder 12: 11,45% boven € 6.239, maximaal € 3.032.'),
('Hoeveel kinderopvangtoeslag?','Tot 96% van de maximale uurprijs bij inkomen tot circa € 56.413.'),
('Is de bijstand hoger voor alleenstaande ouders?','Sinds 2026 mogelijk, ongeveer zo hoog als de ALO-kop, zonder toeslagpartner.'),
('Verlies ik de ALO-kop met een nieuwe partner?','Meestal wel als die toeslagpartner wordt.')],
src_note='Gecontroleerd bij Belastingdienst, Dienst Toeslagen en Rijksoverheid op 5 oktober 2026. Bedragentabellen kindgebonden budget en kinderbijslag 2026 konden we niet direct lezen; gebruik de proefberekening. Voorbeelden zijn illustratief.')
