from a_student_finance import T
SLUG='social-housing-sociale-huurwoning'
V='https://www.volkshuisvestingnederland.nl/'
R='https://www.rijksoverheid.nl/'
SRC=[('Volkshuisvesting Nederland · Inkomensgrenzen woningtoewijzing 2026',V+'onderwerpen/huren-en-wonen/inkomensgrenzen-huurprijsgrenzen-en-huurtoeslagparameters/woningtoewijzing'),
('Rijksoverheid · Indexering inkomensgrenzen en huurprijsgrenzen 2026',R+'actueel/nieuws/2025/11/25/indexering-inkomensgrenzen-woningcorporaties-maximale-huurprijsgrenzen-en-huurtoeslagparameters-2026'),
('Rijksoverheid · Wanneer krijg ik een urgentieverklaring?',R+'onderwerpen/huurwoning-zoeken/vraag-en-antwoord/wanneer-krijg-ik-een-urgentieverklaring-voor-een-huurwoning'),
('Aedes · Wie krijgt voorrang op een sociale huurwoning','https://aedes.nl/aandachtsgroepen/wie-krijgt-voorrang-op-een-sociale-huurwoning'),
('Rijksoverheid · Wet versterking regie volkshuisvesting van kracht vanaf 1 juli 2026',R+'actueel/nieuws/2026/06/23/wet-versterking-regie-volkshuisvesting-van-kracht-vanaf-1-juli'),
('Ymere/PWNR · Jaarrapportage woonruimteverdeling 2024','https://www.ymere.nl/media/2xge5fxb/pwnr-jaarrapportage-woonruimteverdeling-2024-def.pdf'),
('Domijn · FAQ woonruimteverdeling Twente','https://www.domijn.nl/media/4158/faq-woonruimteverdeling.pdf'),
('WoningHuren (Twente)','https://www.woninghuren.nl'),
('Volkshuisvesting Nederland · Wet betaalbare huur',V+'wat-betekent-de-wet-betaalbare-huur-voor-mij/info/over-de-wet-betaalbare-huur'),
('Rijksoverheid · Woningruil',R+'onderwerpen/woning-huren/vraag-en-antwoord/kan-ik-mijn-huurwoning-ruilen-met-de-huurwoning-van-iemand-anders'),
('Rijksoverheid · Onderverhuren',R+'vraag-en-antwoord/woning-verhuren/wat-moet-ik-weten-als-ik-mijn-huis-of-kamer-wil-onderverhuren')]
AR=dict(title='السكن الاجتماعي في هولندا 2026: كيف تسجّل، حدود الدخل، مدة الانتظار، والأولوية (urgentie) — مع أمثلة',
seo_title='السكن الاجتماعي sociale huurwoning 2026',
crumb='السكن الاجتماعي',
desc='السكن الاجتماعي sociale huurwoning: حد الدخل 2026 هو 51,537 يورو لشخص و56,910 لأسرة، كيف تسجّل، مدة الانتظار الحقيقية، والأولوية العاجلة.',
summary='<ol><li>سجّل <strong>اليوم</strong> في بوابة منطقتك؛ الأقدمية هي أهم شيء.</li><li>حد الدخل 2026: <strong>51,537 يورو</strong> لشخص وحيد و<strong>56,910</strong> لأسرة.</li><li>بدخل منخفض (حتى 29,400 وحيد / 39,925 أسرة) يُعرض عليك غالباً بيت إيجاره حتى <strong>713.02</strong> (1–2 شخص) أو <strong>764.14</strong> (3+).</li><li>الانتظار طويل: في منطقة أمستردام كان المعدل <strong>8.8 سنة</strong> في 2024.</li><li>الأولوية العاجلة (urgentie) تقررها البلدية لحالات طارئة فقط.</li></ol>',
body=(
'<h2 id="what">ما هو البيت الاجتماعي؟</h2><p>بيت تؤجره غالباً شركة إسكان (woningcorporatie) بإيجار حتى <strong>932.93 يورو</strong> شهرياً في 2026 (143 نقطة في نظام النقاط)، ومعه يمكنك عادة الحصول على <a href="/articles/housing-rent-allowance-2026.html">بدل الإيجار</a>. الطلب أكبر بكثير من العرض، لذلك يوزَّع حسب قواعد.</p>'
'<h2 id="limits">حدود الدخل 2026</h2>'
+T([['شخص وحيد','حتى 51,537 يورو','حتى 29,400 (فوق سن AOW: 28,775)'],['أسرة (2+)','حتى 56,910 يورو','حتى 39,925 (فوق سن AOW: 38,650)']],['الأسرة','حد الدخل للبيت الاجتماعي','حد «الإيجار المناسب» (passend toewijzen)'])
+'<p>من دخله تحت حد «الإيجار المناسب» يحصل عادة على بيت إيجاره حتى <strong>713.02</strong> يورو (1–2 شخص) أو <strong>764.14</strong> يورو (3 أشخاص فأكثر)، حتى يبقى الإيجار مناسباً لبدل الإيجار.</p>'
'<h2 id="register">التسجيل: خطوة بخطوة</h2><ol><li>اعرف بوابة منطقتك. مثال مؤكد: في <strong>Twente (إنسخيده وما حولها)</strong> البوابة <strong>WoningHuren.nl</strong> برسوم تسجيل لمرة واحدة <strong>25 يورو</strong>. في أوترخت البوابة Mijn Dak. في المدن الكبرى الأخرى ابحث عن بوابة المنطقة عبر موقع البلدية (الرسوم تختلف).</li><li>سجّل نفسك فوراً، حتى لو لا تحتاج البيت الآن — مدة التسجيل (inschrijfduur) هي ما يعطيك الأولوية.</li><li>أدخل الدخل وعدد أفراد الأسرة في ملفك، وإلا لن ترى البيوت المناسبة لك.</li><li>قدّم (reageer) على البيوت المعروضة أسبوعياً، وعلى القرعة (loting) أيضاً.</li><li>جدّد التسجيل سنوياً إن طلبت البوابة ذلك، وإلا تخسر أقدميتك.</li></ol>'
'<h2 id="wait">كم الانتظار؟</h2>'
+T([['منطقة أمستردام 2024','متوسط مدة تسجيل الفائزين <strong>8.8 سنة</strong> (9.6 في 2023)، والقرعة 3% فقط من العروض'],['Twente منذ 2 يونيو 2025','<strong>62.5%</strong> من البيوت بالقرعة و<strong>37.5%</strong> لأقدم تسجيل'],['هنخلو 2026','البلدية تقول إن بيانات الانتظار ناقصة ولا رقم دقيق']],['المنطقة','ما تقوله المصادر'])
+'<h2 id="examples">أمثلة (توضيحية)</h2>'
+T([['ريم، وحيدة، دخل 28,000 يورو','تحت حد الإيجار المناسب ← تُعرض عليها بيوت حتى 713.02 يورو، وتستحق بدل الإيجار غالباً'],['فادي وزوجته وطفلان، دخل 45,000','تحت 56,910 ← يحق لهم البيت الاجتماعي؛ فوق 39,925 فلا تقييد بـ764.14'],['ناصر، وحيد، دخل 55,000','فوق 51,537 ← غالباً لا يحق له بيت اجتماعي؛ يبحث في الإيجار المتوسط (middenhuur) حتى 1,228.07'],['عائلة في Twente سجلت قبل 5 سنوات','تقدّم على القرعة (62.5%) وعلى بيوت الأقدمية معاً لتزيد فرصها']],['الحالة','النتيجة'])
+'<p>الأسماء أمثلة توضيحية وليست أشخاصاً حقيقيين.</p>'
'<h2 id="urgent">الأولوية العاجلة (urgentieverklaring)</h2><ul><li>تقررها <strong>البلدية</strong> حسب نظام السكن المحلي (huisvestingsverordening)؛ القواعد تختلف بين البلديات.</li><li>حالات ممكنة حسب Rijksoverheid: انتقال اضطراري لسبب صحي، بيت سيُهدم، وغيرها. حسب Aedes: إن وُجدت الأولوية في البلدية فهي إلزامية لمقدمي الرعاية (mantelzorg) ولخارجين من ملاجئ النساء.</li><li>الأولوية لحالة <strong>طارئة</strong> لا تستطيع حلها بنفسك، وليست لكل تغيير في الحياة.</li><li><strong>حاملو الإقامة (statushouders)</strong>: البلدية ملزمة بإسكانهم ضمن حصتها (taakstelling)، وتتواصل معهم عبر COA.</li><li><strong>قانون جديد منذ 1 يوليو 2026</strong> (Wet versterking regie volkshuisvesting): مجموعات وطنية للباحثين العاجلين، وكل البلديات يجب أن تشارك. التفاصيل العملية ستظهر في أنظمة البلديات حتى 2028، فاسأل بلديتك.</li></ul>'
'<h2 id="tips">نصائح لزيادة فرصك</h2><ol><li>سجّل أفراد العائلة البالغين بشكل منفصل إن سمحت البوابة.</li><li>قدّم على كل البيوت المناسبة، ولا ترفض العروض كثيراً (قد تفقد أقدميتك في بعض المناطق).</li><li>جرّب مناطق أقل طلباً.</li><li><strong>تبادل البيوت (woningruil)</strong> ممكن بموافقة المالك.</li><li>تأجير غرفة من الباطن مسموح فقط بموافقة المالك وإن لم يمنعه العقد؛ تأجير البيت كله من الباطن ممنوع.</li><li>قبل التوقيع في السوق الخاصة: تحقق من <a href="/articles/tenant-rights-netherlands.html">حقوقك كمستأجر</a>.</li><li>عند الانتقال إلى البيت الجديد أبلغ البلدية بعنوانك (<a href="/articles/change-address-netherlands.html">دليل تغيير العنوان</a>).</li></ol>'),
faq=[('ما حد الدخل للبيت الاجتماعي 2026؟','51,537 يورو لشخص وحيد و56,910 لأسرة.'),('كم أنتظر؟','يختلف كثيراً؛ في منطقة أمستردام كان المعدل 8.8 سنة في 2024. سجّل فوراً.'),('كم يكلف التسجيل؟','يختلف؛ في Twente عبر WoningHuren.nl رسم لمرة واحدة 25 يورو.'),('من يحصل على أولوية عاجلة؟','من تقرر بلديته ذلك لحالة طارئة؛ القواعد تختلف حسب البلدية.'),('هل يحصل حامل الإقامة على بيت؟','البلدية ملزمة بإسكان حاملي الإقامة ضمن حصتها.'),('ما أقصى إيجار للبيت الاجتماعي؟','932.93 يورو شهرياً في 2026.')],
src_note='راجعنا Volkshuisvesting Nederland وRijksoverheid وAedes وشركات إسكان في 5 أكتوبر 2026. رسوم التسجيل في المدن الكبرى لم نتحقق منها. الأمثلة توضيحية.')
NL=dict(title='Sociale huurwoning in 2026: inschrijven, inkomensgrenzen, wachttijd en urgentie — met voorbeelden',
seo_title='Sociale huurwoning 2026: inkomensgrens, urgentie',
crumb='Sociale huurwoning',
desc='Sociale huurwoning 2026: inkomensgrens € 51.537 alleenstaand en € 56.910 meerpersoons, inschrijven per regio, echte wachttijden en urgentie.',
summary='<ol><li>Schrijf je <strong>vandaag</strong> in bij je regionale portal; inschrijfduur telt.</li><li>Inkomensgrens 2026: <strong>€ 51.537</strong> alleenstaand, <strong>€ 56.910</strong> meerpersoons.</li><li>Laag inkomen (tot € 29.400 / € 39.925): huur meestal tot <strong>€ 713,02</strong> (1–2 pers.) of <strong>€ 764,14</strong> (3+).</li><li>Regio Amsterdam: gemiddeld <strong>8,8 jaar</strong> inschrijfduur in 2024.</li><li>Urgentie bepaalt de gemeente, alleen bij acute nood.</li></ol>',
body=(
'<h2 id="what">Wat is een sociale huurwoning?</h2><p>Meestal een woning van een corporatie met huur tot <strong>€ 932,93</strong> per maand in 2026 (143 punten), vaak met <a href="/nl/articles/housing-rent-allowance-2026.html">huurtoeslag</a>.</p>'
'<h2 id="limits">Inkomensgrenzen 2026</h2>'
+T([['Alleenstaand','Tot € 51.537','Tot € 29.400 (AOW-leeftijd € 28.775)'],['Meerpersoons','Tot € 56.910','Tot € 39.925 (AOW-leeftijd € 38.650)']],['Huishouden','Grens sociale huur','Grens passend toewijzen'])
+'<p>Onder de passend-toewijzengrens krijg je meestal een woning tot <strong>€ 713,02</strong> (1–2 personen) of <strong>€ 764,14</strong> (3+).</p>'
'<h2 id="register">Inschrijven</h2><ol><li>Zoek je regionale portal. Bevestigd: <strong>Twente</strong> via <strong>WoningHuren.nl</strong>, eenmalig <strong>€ 25</strong>; Utrecht via Mijn Dak. Andere regio’s: zie je gemeente.</li><li>Schrijf direct in, ook als je nog niet zoekt.</li><li>Vul inkomen en huishouden in.</li><li>Reageer wekelijks en doe mee aan loting.</li><li>Verleng je inschrijving als dat nodig is.</li></ol>'
'<h2 id="wait">Wachttijd</h2>'
+T([['Regio Amsterdam 2024','Gemiddeld <strong>8,8 jaar</strong> inschrijfduur (9,6 in 2023); loting 3%'],['Twente sinds 2 juni 2025','<strong>62,5%</strong> loting, <strong>37,5%</strong> langste inschrijving'],['Hengelo 2026','Gemeente: wachttijddata onvolledig']],['Regio','Bron zegt'])
+'<h2 id="examples">Voorbeelden (illustratief)</h2>'
+T([['Reem, alleenstaand, € 28.000','Passend toewijzen: woningen tot € 713,02, meestal huurtoeslag'],['Fadi, gezin met 2 kinderen, € 45.000','Onder € 56.910: recht op sociale huur; boven € 39.925 dus geen grens van € 764,14'],['Nasser, alleenstaand, € 55.000','Boven € 51.537: meestal geen sociale huur; middenhuur tot € 1.228,07'],['Gezin in Twente, 5 jaar ingeschreven','Reageer op loting én inschrijfduurwoningen']],['Situatie','Uitkomst'])
+'<p>Illustratieve voorbeelden, geen echte personen.</p>'
'<h2 id="urgent">Urgentie</h2><ul><li>Bepaald door de <strong>gemeente</strong> via de huisvestingsverordening.</li><li>Bijvoorbeeld medische noodzaak of sloop (Rijksoverheid); volgens Aedes verplicht voor mantelzorgers en uitstromers uit de vrouwenopvang als de gemeente urgentie kent.</li><li>Alleen bij acute nood.</li><li><strong>Statushouders</strong>: gemeente huisvest via de taakstelling.</li><li><strong>Wet versterking regie volkshuisvesting</strong> sinds 1 juli 2026: landelijke groepen urgent woningzoekenden; uitwerking in verordeningen tot 2028.</li></ul>'
'<h2 id="tips">Tips</h2><ol><li>Reageer breed en weiger niet te vaak.</li><li>Kijk in minder populaire gemeenten.</li><li><strong>Woningruil</strong> met toestemming van de verhuurder.</li><li>Kamer onderverhuren alleen met toestemming; hele woning onderverhuren mag niet.</li><li>Ken je <a href="/nl/articles/tenant-rights-netherlands.html">huurrechten</a>.</li><li>Verhuis je naar je nieuwe woning, geef je adres door aan de gemeente (<a href="/nl/articles/change-address-netherlands.html">verhuizen en adres wijzigen</a>).</li></ol>'),
faq=[('Inkomensgrens 2026?','€ 51.537 alleenstaand, € 56.910 meerpersoons.'),('Hoe lang wachten?','Sterk wisselend; regio Amsterdam gemiddeld 8,8 jaar in 2024.'),('Wat kost inschrijven?','Verschilt; Twente (WoningHuren.nl) eenmalig € 25.'),('Wie krijgt urgentie?','Wie de gemeente urgentie geeft bij acute nood; regels per gemeente.'),('Krijgen statushouders een woning?','De gemeente huisvest hen via de taakstelling.'),('Maximale sociale huur?','€ 932,93 per maand in 2026.')],
src_note='Gecontroleerd bij Volkshuisvesting Nederland, Rijksoverheid, Aedes en corporaties op 5 oktober 2026. Inschrijfkosten grote steden niet geverifieerd. Voorbeelden illustratief.')
