SLUG='student-finance'
SRC=[('DUO · Voorwaarden studiefinanciering','https://duo.nl/particulier/studiefinanciering/voorwaarden.jsp'),
('DUO · Bedragen studiefinanciering','https://duo.nl/particulier/studiefinanciering/bedragen.jsp'),
('DUO · Voorwaarden EU/EER, Zwitserland of VK','https://duo.nl/particulier/studiefinanciering-burgers-eu-eer-zwitserland-of-vk/voorwaarden.jsp')]
def T(rows,head):
    h=''.join(f'<th>{c}</th>' for c in head)
    r=''.join('<tr>'+''.join(f'<td>{c}</td>' for c in row)+'</tr>' for row in rows)
    return f'<div class="table-scroll"><table><thead><tr>{h}</tr></thead><tbody>{r}</tbody></table></div>'
AR=dict(
title='تمويل الدراسة من DUO في 2026: الشروط والمبالغ وكيف تحسب ما ستحصل عليه',
crumb='تمويل الدراسة DUO',
desc='دليل عملي لـ studiefinanciering من DUO: من يستحقها، مبالغ MBO وHBO لعام 2026، الفرق بين المنحة والقرض، قاعدة الـ10 سنوات، وأمثلة محسوبة خطوة بخطوة.',
summary='<ol><li>التمويل (studiefinanciering) أجزاء مختلفة: بعضها <strong>هبة مشروطة</strong> وبعضها <strong>دين بفائدة</strong>. لا تجمعها في رقم واحد وتعتبره دخلاً.</li><li>الشروط الأساسية: العمر ونوع الدراسة والجنسية أو نوع الإقامة. القبول في المعهد لا يعني تلقائياً أنك مستحق.</li><li>في MBO مستوى 3 و4 وفي HBO والجامعة تتحول المنحة إلى هبة فقط إذا حصلت على الدبلوم <strong>خلال 10 سنوات</strong>.</li><li>الحد الأقصى الشهري لطالب MBO خارج بيت أهله حالياً نحو 1,054 يورو، منها 820.85 يورو فقط قابلة لأن تصبح هبة.</li><li>إن لم تتأكد من حقك، اسأل DUO قبل أن تدفع رسوماً اعتماداً على تمويل متوقع.</li></ol>',
body=(
'<h2 id="who">من يستحق التمويل؟</h2><p>تفحص DUO ثلاثة أشياء قبل أي مبلغ: عمرك، ونوع دراستك، وجنسيتك أو نوع إقامتك.</p>'
+T([['العمر','في MBO يجب أن تكون 18 سنة على الأقل للحصول على منحة أو قرض، ويبدأ التمويل من الربع الذي يلي عيد ميلادك الـ18. ويجب أن تكون <strong>أقل من 30 سنة</strong> عند بدء التمويل. من بلغ 30 وهو يتلقاه يستمر، لكن إن أوقفه بعد الـ30 فلا يمكنه إعادة تشغيله.'],
['الدراسة','دراسة بدوام كامل أو duaal في مؤسسة معترف بها. دراسة BBL والدراسة الجزئية لا تعطي studiefinanciering وفق هذا النظام.'],
['الجنسية والإقامة','هولندي، أو إقامة من النوع <strong>II أو III أو IV أو V</strong>. صاحب النوع I قد يستحق حسب غرض إقامته، وتوجد لذلك أداة فحص على موقع DUO.'],
['مواطنو EU/EEA وسويسرا','شروط مستقلة: إقامة 5 سنوات متواصلة في هولندا، أو وضع «عامل مهاجر» بعمل مدفوع لا يقل عن 32 ساعة شهرياً، أو أن يكون أحد والديك أو شريكك كذلك. راجع صفحة DUO الخاصة بهم.']],['الشرط','ما تنص عليه DUO'])
+'<aside class="notice"><strong>إقامة من النوع I؟</strong> تنصح DUO بتقديم الطلب في كل الأحوال. ستحصل على رفض بسبب شرط الجنسية، ثم تتواصل معهم <strong>خلال 6 أسابيع</strong> من استلام الإقامة الجديدة. إن كنت حينها مستوفياً للشروط فقد يُمنح التمويل بأثر رجعي. لا تنتظر ثم تتأخر.</aside>'
'<p>إن لم تعرف نوع إقامتك فلا تخمّن. راجع قرار IND الذي وصلك أو اسأل DUO مباشرة، لأن الخطأ هنا يغيّر الحكم كله.</p>'
'<h2 id="parts">أجزاء التمويل: ما الهبة وما الدين؟</h2><p>كلمة «تمويل» توحي بمبلغ واحد، لكن النظام الهولندي مقسّم إلى أجزاء بقواعد مختلفة:</p>'
+T([['<strong>Basisbeurs</strong>','منحة أساسية، مبلغها يختلف بين من يسكن مع أهله (thuiswonend) ومن يسكن خارجهم (uitwonend).','هبة بشرط الدبلوم خلال 10 سنوات (MBO 3–4 وHBO وجامعة). في MBO مستوى 1 و2 هبة دائماً.'],
['<strong>Aanvullende beurs</strong>','منحة إضافية تتوقف على دخل والديك، لا دخلك.','مثل basisbeurs.'],
['<strong>Rentedragende lening</strong>','قرض اختياري تطلبه أنت.','دين بفائدة دائماً.'],
['<strong>Studentenreisproduct</strong>','بطاقة مواصلات مجانية أو مخفّضة.','هبة بشرط الدبلوم خلال 10 سنوات.'],
['<strong>Collegegeldkrediet</strong>','قرض لدفع الرسوم الدراسية في HBO والجامعة فقط.','دين.']],['الجزء','ما هو','هبة أم دين؟'])
+'<p>طالب MBO دون 18 سنة لا يحصل على منحة ولا قرض، بل على بطاقة المواصلات فقط.</p>'
'<h2 id="amounts">مبالغ 2026 الشهرية القصوى</h2><p>المبالغ التالية من صفحة «Bedragen» الرسمية لدى DUO، وهي <strong>حدود قصوى</strong> وليست ما يناله كل طالب. الجزء الأقصى من aanvullende beurs لا يناله إلا من كان دخل والديه منخفضاً.</p>'
'<h3>MBO: أغسطس إلى ديسمبر 2026 (يورو/شهر)</h3>'
+T([['Basisbeurs','107.26','350.03'],['Aanvullende beurs (الأقصى)','442.50','470.82'],['Rentedragende lening (الأقصى)','233.65','233.65'],['<strong>المجموع الأقصى</strong>','<strong>783.41</strong>','<strong>1,054.50</strong>']],['الجزء','يسكن مع أهله','يسكن خارجهم'])
+'<p>من يناير إلى يوليو 2026 كانت aanvullende beurs أقل قليلاً (438.08 و466.40)، فالمجموع 778.99 و1,050.08.</p>'
'<h3>HBO والجامعة: سبتمبر إلى ديسمبر 2026 (يورو/شهر)</h3>'
+T([['Basisbeurs','130.21','324.52'],['Aanvullende beurs (الأقصى)','491.08','491.08'],['Rentedragende lening (الأقصى)','315.17','315.17'],['<strong>المجموع الأقصى مع collegegeldkrediet</strong>','<strong>1,160.96</strong>','<strong>1,355.27</strong>']],['الجزء','يسكن مع أهله','يسكن خارجهم'])
+'<p>تتغير الأرقام كل عام وأحياناً داخل العام نفسه. راجع <a href="https://duo.nl/particulier/studiefinanciering/bedragen.jsp" rel="noopener noreferrer">صفحة المبالغ الرسمية</a> قبل أن تبني ميزانيتك.</p>'
'<h2 id="examples">مثالان محسوبان</h2><h3>مثال 1: طالب MBO مستوى 4، خارج بيت أهله، دخل والديه منخفض</h3><p>كل الأجزاء بالحد الأقصى (أغسطس–ديسمبر 2026):</p><ul><li>الجزء القابل لأن يصبح هبة: 350.03 + 470.82 = <strong>820.85 يورو شهرياً</strong></li><li>القرض (دين دائماً): <strong>233.65 يورو شهرياً</strong></li><li>المجموع: 1,054.50 يورو شهرياً</li></ul>'
'<p>إذا كانت الدراسة 3 سنوات (36 شهراً) وطُلب القرض كاملاً فالدين من القرض وحده 233.65 × 36 = <strong>8,411.40 يورو</strong> قبل الفائدة. أما 820.85 × 36 = 29,550.60 يورو فهي هبة فقط إذا أُنهي الدبلوم في الوقت. هذا الفرق يغيب عن كثيرين عندما يرون رقم «1,054».</p>'
'<p><strong>درس عملي:</strong> لا يلزمك طلب القرض كاملاً. اطلب ما تحتاجه فعلاً، فكل يورو تقترضه يعود بفائدة.</p>'
'<h3>مثال 2: طالب HBO، يسكن مع أهله، دخل والديه منخفض</h3><p>(سبتمبر–ديسمبر 2026): basisbeurs 130.21 + aanvullende beurs 491.08 = <strong>621.29 يورو</strong> قابلة لأن تصبح هبة. والباقي من المجموع الأقصى 1,160.96 أي <strong>539.67 يورو شهرياً</strong> دين (قرض + collegegeldkrediet) إذا طُلبت كاملة، أي أكثر من 46% من المبلغ الأقصى.</p>'
'<h2 id="ten">قاعدة الـ10 سنوات (prestatiebeurs)</h2><p>هذه أهم قاعدة في النظام، ومعظم المحتوى العربي المتداول لا يشرحها:</p><ul><li>تبدأ المدة من <strong>أول شهر</strong> تتلقى فيه التمويل، لا من أول يوم دراسة.</li><li>إن حصلت على دبلوم مناسب خلال 10 سنوات تتحول basisbeurs وaanvullende beurs وبطاقة المواصلات إلى هبة.</li><li>إن لم تحصل عليه تتحول إلى <strong>دين</strong> يجب سداده.</li><li>المدة لا تتوقف عند تغيير الدراسة أو التوقف المؤقت. فكّر في المدة الواقعية قبل أن تبدأ، خصوصاً إن كنت ستعمل أثناء الدراسة أو تتعلم الهولندية أولاً.</li></ul>'
'<h2 id="steps">خطوات الطلب</h2><ol><li>اكتب اسم دراستك الدقيق ونوع التسجيل (دوام كامل، duaal، BOL أو BBL).</li><li>تأكد من نوع إقامتك أو جنسيتك؛ إن كانت من النوع I فاستخدم أداة الفحص لدى DUO.</li><li>سجّل الدخول إلى «Mijn DUO» عبر DigiD. تحتاج DigiD وBSN قبل أي طلب.</li><li>اختر الأجزاء التي تريدها، وتذكر أن القرض وcollegegeldkrediet دين.</li><li>أدخل بيانات سكنك بدقة: نوع السكن (مع الأهل أو خارجهم) يحدد مبلغ basisbeurs.</li><li>قدّم الطلب قبل بداية الدراسة بوقت كافٍ واحفظ كل رسالة من DUO.</li><li>إن توقفت عن الدراسة أو غيّرتها أو غيّرت سكنك فأبلغ DUO فوراً.</li></ol>'
'<h2 id="mistakes">أخطاء شائعة</h2><ul><li><strong>اعتبار المجموع الأقصى دخلاً مضموناً.</strong> فيه قروض وجزء يعتمد على دخل والديك.</li><li><strong>دفع رسوم الدراسة قبل صدور القرار.</strong> القبول في المعهد لا يضمن التمويل.</li><li><strong>تسجيل عنوان لا يطابق الواقع.</strong> قد يعني إعادة مبالغ استُلمت زيادة.</li><li><strong>بناء الميزانية على «الأقصى».</strong> ابنها على المبلغ الذي ذكرته DUO في قرارها.</li><li><strong>إهمال رسائل DUO.</strong> القرارات تصلك في «Mijn DUO» وللاعتراض مهلة مكتوبة في القرار نفسه.</li></ul>'
'<h2 id="story">قصة من الواقع: ماذا يحدث إذا توقفت عن الدراسة؟</h2><p>أحد أصدقائي درس مجال التعليم سنتين ثم قرر إيقاف دراسته. كان قد أخذ قرضاً لشراء الكتب، ولم يتوقع ما جاء بعده: بعد توقفه طُلب منه إعادة هذا القرض. (هذه القصة كما رواها لنا صاحبها ولا نعرض وثائقه، فالتفاصيل الدقيقة تختلف من حالة إلى أخرى.)</p>'
'<p>الدرس أن التمويل لا ينتهي بمجرد مغادرة الدراسة. فور توقفك يتغير وضعك لدى DUO، وما أخذته قرضاً هو دين منذ البداية يجب سداده. وتذكر أن المنحة نفسها قد تتحول إلى دين إن لم تُكمل الدبلوم ضمن قاعدة الـ10 سنوات أعلاه.</p>'
'<p><strong>كيف تتجنب مفاجأة مماثلة؟</strong></p><ul><li>قبل أن تقرر التوقف اسأل DUO عن وضعك: ما الذي ستدين به، ومتى يبدأ السداد، وكم سيكون القسط. (تذكر DUO عادة فترة سماح بعد انتهاء الدراسة قبل بدء السداد؛ تحقق من مدتها الحالية في حالتك.)</li><li>احتفظ بكل رسائل DUO وقراراتها في «Mijn DUO».</li><li>إن كنت تفكر في التوقف لأن الدراسة لا تناسبك، فكّر أولاً في تغيير التخصص بدل التوقف التام، واسأل DUO كيف يؤثر ذلك.</li></ul>'
'<!-- فيديو القناة: ضع iframe من youtube-nocookie.com هنا عند توفر فيديو -->'
'<h2 id="alt">إذا لم تنطبق الشروط</h2><ul><li><strong>Tegemoetkoming scholieren:</strong> لمن يدرس vmbo أو havo أو vwo أو vavo بدوام كامل وعمره 18 سنة فأكثر مع شروط الجنسية والعمر الخاصة بها.</li><li><strong>Tuition fee loan:</strong> لمواطني EU/EEA وسويسرا ولبعض البريطانيين.</li><li><strong>Levenlanglerenkrediet:</strong> قرض بشروط ميسرة نسبياً لدراسة معترف بها لمن لا ينطبق عليه التمويل العادي.</li><li>اسأل DUO عن البدائل لحالتك <strong>قبل</strong> دفع أي رسوم.</li></ul>'
'<h2 id="glossary">مسرد المصطلحات</h2><ul><li><strong>Studiefinanciering:</strong> مجموع أجزاء التمويل الحكومي للطالب.</li><li><strong>Basisbeurs / Aanvullende beurs:</strong> المنحة الأساسية والمنحة الإضافية (حسب دخل الوالدين).</li><li><strong>Prestatiebeurs:</strong> منحة تتحول إلى هبة بشرط الدبلوم خلال 10 سنوات.</li><li><strong>Rentedragende lening:</strong> قرض بفائدة.</li><li><strong>Collegegeldkrediet:</strong> قرض لدفع الرسوم في HBO والجامعة.</li><li><strong>Thuiswonend / Uitwonend:</strong> تسكن مع أهلك / خارج بيتهم.</li><li><strong>BOL / BBL:</strong> مسار دراسة مع تدريب / مسار عمل مع دراسة؛ BBL لا يعطي studiefinanciering.</li></ul>'),
faq=[('هل كل طالب يحمل إقامة يستحق التمويل؟','لا. يجب أن تكون أقل من 30 سنة عند البدء، وتدرس دراسة معترفاً بها، وتكون إقامتك من النوع II أو III أو IV أو V (أو النوع I بشروطه).'),
('هل القرض منحة؟','لا. القرض دين دائماً. المنحة وحدها (basisbeurs وaanvullende beurs) قد تتحول إلى هبة بشرط الدبلوم خلال 10 سنوات.'),
('ماذا لو لم أنهِ الدراسة خلال 10 سنوات؟','تتحول المنحة التي استلمتها إلى دين. احسب مدة دراستك الواقعية قبل البدء.'),
('هل يمكنني الحصول على أقل من الحد الأقصى؟','نعم. aanvullende beurs تتوقف على دخل والديك، والقرض اختياري وتحدد أنت مقداره.')],
src_note='راجعنا هذه الصفحات في 4 أكتوبر 2026. الشروط والمبالغ قد تتغير، فاستخدم دائماً الصفحة الحالية.')
NLT=lambda r,h:T(r,h)
NL=dict(
title='Studiefinanciering van DUO in 2026: voorwaarden, bedragen en hoe je je bedrag berekent',
crumb='DUO-studiefinanciering',
desc='Praktische gids over studiefinanciering van DUO: wie recht heeft, bedragen voor mbo en hbo in 2026, het verschil tussen beurs en lening, de 10-jaarsregel en uitgewerkte voorbeelden.',
summary='<ol><li>Studiefinanciering bestaat uit onderdelen: sommige zijn een <strong>voorwaardelijke gift</strong>, andere een <strong>lening met rente</strong>. Tel ze niet op tot één bedrag aan inkomen.</li><li>Basisvoorwaarden: leeftijd, soort opleiding en nationaliteit of verblijfsvergunning. Toelating tot een opleiding betekent niet automatisch recht op financiering.</li><li>In mbo niveau 3 en 4, hbo en wo wordt de beurs alleen een gift als je binnen <strong>10 jaar</strong> je diploma haalt.</li><li>Het maximum voor een uitwonende mbo-student is nu ongeveer € 1.054 per maand; daarvan kan alleen € 820,85 een gift worden.</li><li>Weet je niet zeker of je recht hebt? Vraag het DUO vóór je collegegeld betaalt op basis van verwachte financiering.</li></ol>',
body=(
'<h2 id="who">Wie heeft recht?</h2><p>DUO kijkt eerst naar drie dingen: je leeftijd, je opleiding en je nationaliteit of verblijfsvergunning.</p>'
+T([['Leeftijd','In het mbo moet je minimaal 18 zijn voor beurs of lening; de financiering start in het kwartaal na je 18e verjaardag. Je moet <strong>jonger dan 30</strong> zijn als de financiering begint. Heb je hem al en word je 30, dan loopt hij door; stop je na je 30e, dan kun je hem niet opnieuw starten.'],
['Opleiding','Voltijd of duaal onderwijs bij een erkende instelling. Bbl en deeltijd geven volgens dit stelsel geen studiefinanciering.'],
['Nationaliteit en verblijf','Nederlander, of verblijfsvergunning type <strong>II, III, IV of V</strong>. Bij type I kan het afhangen van het verblijfsdoel; DUO heeft daarvoor een toetsingstool.'],
['EU/EER, Zwitserland','Aparte voorwaarden: 5 jaar ononderbroken verblijf in Nederland, of status migrerend werknemer met minimaal 32 uur betaald werk per maand, of een ouder of partner die dat is. Zie de aparte DUO-pagina.']],['Voorwaarde','Wat DUO zegt'])
+'<aside class="notice"><strong>Verblijfsvergunning type I?</strong> DUO adviseert in elk geval aan te vragen. Je krijgt dan een afwijzing vanwege de nationaliteitseis, en neemt <strong>binnen 6 weken</strong> na ontvangst van je nieuwe vergunning contact op. Voldoe je dan aan de voorwaarden, dan kan de financiering met terugwerkende kracht worden toegekend.</aside>'
'<p>Weet je niet welk type je hebt? Raad niet: kijk in het IND-besluit of vraag het DUO.</p>'
'<h2 id="parts">De onderdelen: wat is gift, wat is schuld?</h2>'
+T([['<strong>Basisbeurs</strong>','Basisbedrag, verschilt tussen thuiswonend en uitwonend.','Gift als je binnen 10 jaar een diploma haalt (mbo 3–4, hbo, wo). In mbo niveau 1 en 2 altijd een gift.'],
['<strong>Aanvullende beurs</strong>','Extra beurs afhankelijk van het inkomen van je ouders.','Zoals basisbeurs.'],
['<strong>Rentedragende lening</strong>','Vrijwillige lening die je zelf aanvraagt.','Altijd schuld, met rente.'],
['<strong>Studentenreisproduct</strong>','Gratis of met korting reizen.','Gift als je binnen 10 jaar een diploma haalt.'],
['<strong>Collegegeldkrediet</strong>','Lening voor collegegeld, alleen hbo en wo.','Schuld.']],['Onderdeel','Wat is het','Gift of schuld?'])
+'<p>Een mbo-student jonger dan 18 krijgt geen beurs of lening, alleen het reisproduct.</p>'
'<h2 id="amounts">Maximale maandbedragen 2026</h2><p>Onderstaande bedragen komen van de officiële DUO-pagina “Bedragen”. Het zijn <strong>maxima</strong>, niet wat iedere student krijgt. Het maximum van de aanvullende beurs is er alleen bij een laag ouderinkomen.</p>'
'<h3>Mbo: augustus tot en met december 2026 (€/maand)</h3>'
+T([['Basisbeurs','107,26','350,03'],['Aanvullende beurs (max.)','442,50','470,82'],['Rentedragende lening (max.)','233,65','233,65'],['<strong>Totaal maximum</strong>','<strong>783,41</strong>','<strong>1.054,50</strong>']],['Onderdeel','Thuiswonend','Uitwonend'])
+'<p>Van januari tot en met juli 2026 was de aanvullende beurs iets lager (438,08 en 466,40), met totalen van 778,99 en 1.050,08.</p>'
'<h3>Hbo en wo: september tot en met december 2026 (€/maand)</h3>'
+T([['Basisbeurs','130,21','324,52'],['Aanvullende beurs (max.)','491,08','491,08'],['Rentedragende lening (max.)','315,17','315,17'],['<strong>Totaal maximum incl. collegegeldkrediet</strong>','<strong>1.160,96</strong>','<strong>1.355,27</strong>']],['Onderdeel','Thuiswonend','Uitwonend'])
+'<p>Bedragen wijzigen jaarlijks en soms binnen een jaar. Controleer de <a href="https://duo.nl/particulier/studiefinanciering/bedragen.jsp" rel="noopener noreferrer">officiële bedragenpagina</a> voordat je een begroting maakt.</p>'
'<h2 id="examples">Twee uitgewerkte voorbeelden</h2><h3>Voorbeeld 1: mbo niveau 4, uitwonend, laag ouderinkomen</h3><p>Alle onderdelen op het maximum (aug–dec 2026):</p><ul><li>Mogelijk gift: 350,03 + 470,82 = <strong>€ 820,85 per maand</strong></li><li>Lening (altijd schuld): <strong>€ 233,65 per maand</strong></li><li>Totaal: € 1.054,50 per maand</li></ul>'
'<p>Bij een opleiding van 3 jaar (36 maanden) met de volledige lening is de schuld alleen daaruit 233,65 × 36 = <strong>€ 8.411,40</strong> vóór rente. De 820,85 × 36 = € 29.550,60 is alleen een gift als het diploma op tijd wordt gehaald. Dit verschil zien veel studenten over het hoofd bij het getal “1.054”.</p>'
'<p><strong>Praktisch:</strong> je hoeft de lening niet volledig op te nemen. Leen alleen wat je echt nodig hebt; elke euro kost rente.</p>'
'<h3>Voorbeeld 2: hbo, thuiswonend, laag ouderinkomen</h3><p>(sept–dec 2026): basisbeurs 130,21 + aanvullende beurs 491,08 = <strong>€ 621,29</strong> mogelijke gift. Het restant van het maximum 1.160,96, dus <strong>€ 539,67 per maand</strong>, is schuld (lening + collegegeldkrediet) als alles wordt opgenomen: ruim 46% van het maximum.</p>'
'<h2 id="ten">De 10-jaarsregel (prestatiebeurs)</h2><p>Dit is de belangrijkste regel van het stelsel en wordt in veel Arabischtalige content niet uitgelegd:</p><ul><li>De termijn start in de <strong>eerste maand</strong> waarin je financiering ontvangt, niet op je eerste lesdag.</li><li>Haal je binnen 10 jaar een passend diploma, dan worden basisbeurs, aanvullende beurs en reisproduct een gift.</li><li>Haal je het niet, dan worden ze een <strong>schuld</strong> die je moet terugbetalen.</li><li>De termijn stopt niet als je van opleiding wisselt of tijdelijk stopt. Reken vooraf realistisch, zeker als je gaat werken of eerst Nederlands leert.</li></ul>'
'<h2 id="steps">Aanvragen in stappen</h2><ol><li>Noteer je exacte opleiding en inschrijvingsvorm (voltijd, duaal, bol of bbl).</li><li>Controleer je verblijfstype of nationaliteit; bij type I gebruik je de toetsingstool van DUO.</li><li>Log in op “Mijn DUO” met DigiD. Je hebt DigiD en BSN nodig.</li><li>Kies de onderdelen die je wilt; onthoud dat lening en collegegeldkrediet schuld zijn.</li><li>Vul je woonsituatie juist in: thuiswonend of uitwonend bepaalt de basisbeurs.</li><li>Vraag ruim vóór de start van je opleiding aan en bewaar alle berichten van DUO.</li><li>Stop je, wissel je van opleiding of verhuis je? Meld het direct aan DUO.</li></ol>'
'<h2 id="mistakes">Veelgemaakte fouten</h2><ul><li><strong>Het maximum zien als gegarandeerd inkomen.</strong> Er zit lening in en een deel hangt af van het ouderinkomen.</li><li><strong>Collegegeld betalen vóór het besluit.</strong> Toelating garandeert geen financiering.</li><li><strong>Een adres opgeven dat niet klopt.</strong> Dat kan betekenen dat je te veel ontvangen bedragen moet terugbetalen.</li><li><strong>Begroten op het maximum.</strong> Gebruik het bedrag in het besluit van DUO.</li><li><strong>DUO-berichten negeren.</strong> Besluiten staan in “Mijn DUO”; de bezwaartermijn staat in het besluit zelf.</li></ul>'
'<h2 id="story">Uit de praktijk: wat gebeurt er als je stopt?</h2><p>Een vriend van mij studeerde twee jaar in het onderwijs en besloot toen te stoppen. Hij had een lening opgenomen voor studieboeken en verwachtte niet wat daarna kwam: na zijn stop werd van hem gevraagd die lening terug te betalen. (Dit is zijn verhaal zoals hij het vertelde; we hebben zijn stukken niet ingezien, en details verschillen per situatie.)</p>'
'<p>De les: de financiering stopt niet zodra je de opleiding verlaat. Zodra je stopt verandert je situatie bij DUO, en wat je als lening opnam is vanaf het begin schuld. Ook de beurs kan schuld worden als je niet binnen de 10-jaarsregel een diploma haalt.</p>'
'<p><strong>Hoe voorkom je zo’n verrassing?</strong></p><ul><li>Vraag DUO vóór je besluit te stoppen wat je schuldig bent, wanneer terugbetalen begint en hoe hoog de maandtermijn is. (DUO kent doorgaans een aanloopperiode na afloop van de studie; controleer de huidige duur voor jouw situatie.)</li><li>Bewaar alle berichten en besluiten uit “Mijn DUO”.</li><li>Stop je omdat de opleiding niet past? Overweeg eerst een andere opleiding en vraag DUO wat dat betekent.</li></ul>'
'<h2 id="alt">Als je niet aan de voorwaarden voldoet</h2><ul><li><strong>Tegemoetkoming scholieren:</strong> voor wie voltijd vmbo, havo, vwo of vavo volgt, 18 jaar of ouder is en aan de eisen voldoet.</li><li><strong>Tuition fee loan:</strong> voor EU/EER-burgers, Zwitsers en bepaalde Britten.</li><li><strong>Levenlanglerenkrediet:</strong> lening onder relatief gunstige voorwaarden voor een erkende opleiding.</li><li>Vraag DUO naar alternatieven <strong>voordat</strong> je kosten maakt.</li></ul>'
'<h2 id="glossary">Begrippen</h2><ul><li><strong>Studiefinanciering:</strong> alle onderdelen van de studiefinanciering samen.</li><li><strong>Basisbeurs / aanvullende beurs:</strong> basisbeurs en extra beurs (afhankelijk van ouderinkomen).</li><li><strong>Prestatiebeurs:</strong> beurs die gift wordt bij diploma binnen 10 jaar.</li><li><strong>Rentedragende lening:</strong> lening met rente.</li><li><strong>Collegegeldkrediet:</strong> lening voor collegegeld in hbo en wo.</li><li><strong>Bol / bbl:</strong> opleiding met stage / werken en leren; bbl geeft geen studiefinanciering.</li></ul>'),
faq=[('Heeft elke student met een verblijfsvergunning recht op financiering?','Nee. Je moet jonger zijn dan 30 bij de start, een erkende opleiding volgen en verblijfstype II, III, IV of V hebben (of type I onder voorwaarden).'),
('Is een lening een beurs?','Nee. Een lening is altijd schuld. Alleen de beurs (basis en aanvullend) kan een gift worden bij een diploma binnen 10 jaar.'),
('Wat als ik niet binnen 10 jaar afstudeer?','De ontvangen beurs wordt een schuld. Reken vooraf je realistische studieduur uit.'),
('Kan ik minder krijgen dan het maximum?','Ja. De aanvullende beurs hangt af van het ouderinkomen en de lening is vrijwillig; jij bepaalt het bedrag.')],
src_note='Bronnen geraadpleegd op 4 oktober 2026. Voorwaarden en bedragen kunnen wijzigen; gebruik altijd de actuele pagina.')
