from a_student_finance import T
SLUG='syrian-documents-legalisation-translation'
SRC=[('Nederland Wereldwijd · Legaliseren van documenten uit Syrië voor gebruik in Nederland','https://www.nederlandwereldwijd.nl/legaliseren/buitenlandse-documenten/syrie'),
('IND · Legaliseren en vertalen documenten (bijgewerkt 24 februari 2025)','https://ind.nl/nl/legaliseren-en-vertalen-documenten'),
('IND · Gezinshereniging asiel (documenten verzamelen)','https://ind.nl/nl/verblijfsvergunningen/asiel/gezinshereniging-asiel'),
('Nederland Wereldwijd · Buitenlandse akten omzetten naar Nederlandse akten (gemeente Den Haag)','https://www.nederlandwereldwijd.nl/buitenlandse-akte-omzetten'),
('Raad voor Rechtsbijstand Wbtv · Tolk of vertaler zoeken (Register beëdigde tolken en vertalers)','https://www.bureauwbtv.nl/tolk-vertaler-zoeken/'),
('RvIG · Als je in Nederland wilt komen wonen (inschrijven BRP binnen 5 dagen)','https://www.rvig.nl/als-je-nederland-wilt-komen-wonen')]
AR=dict(title='الوثائق السورية في هولندا 2026: التصديق (legalisatie) والترجمة المحلفة وتسجيلها في البلدية وBRP — خطوة بخطوة',
crumb='الوثائق السورية: التصديق والترجمة',
desc='دليل لاستخدام الوثائق السورية (شهادة الميلاد، عقد الزواج، دفتر العائلة…) في هولندا: التصديق من وزارة الخارجية السورية لأن السفارة الهولندية في دمشق مغلقة، الترجمة المحلفة وطريقتا الترتيب، سجل المترجمين المحلفين، تحويل الوثيقة الأجنبية إلى وثيقة هولندية عبر لاهاي، وثائق IND وBRP والبلدية، وأخطاء شائعة، مع أمثلة توضيحية وأسئلة شائعة.',
summary='<ol><li>لاستخدام وثيقة سورية في هولندا تحتاج <strong>تصديقاً (legalisatie) من وزارة الخارجية السورية</strong>. <strong>السفارة الهولندية في دمشق مغلقة</strong> حسب Nederland Wereldwijd.</li><li>الوثيقة العربية تحتاج <strong>ترجمة بمترجم محلّف</strong> إلى الهولندية أو الإنجليزية أو الفرنسية أو الألمانية.</li><li>طريقان: <strong>(أ)</strong> الترجمة في سوريا ثم تصديق الأصل والترجمة معاً، أو <strong>(ب)</strong> تصديق الأصل في سوريا ثم الترجمة في هولندا عند مترجم محلّف أمام محكمة هولندية، دون الحاجة لتصديق الترجمة.</li><li>التصديق <strong>لا يثبت صحة المحتوى</strong>: البلدية أو IND قد تتحقق منه.</li><li>التسجيل في BRP لدى البلدية خلال <strong>5 أيام</strong> من الوصول (RvIG). دفتر العائلة السوري تقبله <strong>بعض</strong> البلديات فقط: اسأل بلديتك.</li></ol>',
body=(
'<h2 id="why">لماذا نحتاج التصديق والترجمة؟</h2><p>حسب IND، التصديق (legalisatie) يجعل وثيقة رسمية صالحة للاستخدام في بلد آخر. يُنظر فيه إلى أن الجهة الصحيحة هي التي أصدرتها، ويكون عادةً بختم أو ملصق. بعده تصبح الوثيقة جاهزة للاستخدام في هولندا. <strong>IND لا تصدّق ولا تترجم بنفسها.</strong> وتنصح بالبدء مبكراً لأن التصديق قد يستغرق وقتاً طويلاً.</p>'
'<p><strong>مهم:</strong> هذا الدليل لمن يستطيع الاتصال بسلطات سوريا. إن كنت لاجئاً أو تخشى على سلامتك أو سلامة أهلك من الاتصال بسلطات بلدك أو سفارتها، <strong>استشر VluchtelingenWerk أو محامياً قبل أي خطوة</strong>. لم نجد على الصفحات الرسمية التي راجعناها قاعدة تحسم هذه المسألة، ولذلك لا نعطي حكماً فيها. وإن لم تتوفر وثائق، فقد يعتمد IND وسائل أخرى مثل فحص DNA أو مقابلة (انظر <a href="/articles/asylum-family-reunification.html">لمّ شمل عائلة اللاجئ</a>).</p>'
'<h2 id="steps">الخطوات حسب Nederland Wereldwijd (وثائق من سوريا)</h2>'
+T([['الوثيقة بالعربية','تحتاج ترجمة لاستخدامها في هولندا، بمترجم محلّف إلى الهولندية أو الإنجليزية أو الفرنسية أو الألمانية.'],['الوثيقة أصلية وكاملة','إن أحالت الوثيقة إلى وثائق أو ملحقات أخرى فيجب أن تكون معها.'],['السفارة','السفارة الهولندية في <strong>دمشق مغلقة</strong>. التصديق يتم لدى <strong>وزارة الخارجية السورية</strong>.'],['الطريق أ: الترجمة في سوريا','1) مترجم محلّف يترجم الوثيقة. 2) تصدّق <strong>الوثيقة والترجمة معاً</strong> لدى وزارة الخارجية السورية.'],['الطريق ب: الترجمة في هولندا','1) تصدّق <strong>الوثيقة الأصلية</strong> في سوريا. 2) تُترجم في هولندا عند مترجم محلّف. <strong>لا حاجة لتصديق الترجمة.</strong>'],['بعد التصديق','تصبح جاهزة للاستخدام في هولندا (وكذلك في أروبا وكوراساو وسينت مارتن وبونير وسابا وسينت أوستاتيوس).']],['البند','ما يقوله المصدر الرسمي'])
+'<h2 id="translator">كيف أجد مترجماً محلفاً في هولندا؟</h2><p>في هولندا يجب أن يكون المترجم <strong>محلّفاً أمام محكمة هولندية</strong> حسب IND. تجده في <strong>Register beëdigde tolken en vertalers (Rbtv)</strong> لدى Bureau Wbtv التابع لمجلس المساعدة القانونية: <a href="https://www.bureauwbtv.nl/tolk-vertaler-zoeken/" rel="noopener">bureauwbtv.nl/tolk-vertaler-zoeken</a>. يمكن البحث بالاسم أو برقم Wbtv أو بتركيبة اللغات أو الرمز البريدي. لم نجد مصدراً رسمياً لأسعار الترجمة المحلفة، فاسأل أكثر من مترجم عن السعر والمدة قبل البدء.</p>'
'<h2 id="get">وثائق لا أملكها بعد</h2>'
+T([['شهادة الميلاد، عقد الزواج، وثيقة الطلاق، شهادة الوفاة','تطلبها من مكتب الأحوال المدنية في وزارة الداخلية السورية (حسب Nederland Wereldwijd).'],['شهادة عدم زواج (ongehuwdverklaring)','من الجهة نفسها. <strong>IND تقبلها فقط إن لم تتجاوز 6 أشهر.</strong>'],['دفتر العائلة السوري','تقبله <strong>بعض</strong> البلديات الهولندية دليلاً على الأحوال المدنية. اسأل بلدية سكنك. لا تفترض أنه كافٍ.'],['وثائق أخرى','اسأل الجهات المحلية أين تطلبها (حسب Nederland Wereldwijd).']],['الوثيقة','أين وكيف'])
+'<h2 id="validity">الصلاحية وإعادة التصديق</h2><ul><li>التصديق <strong>لا يعني أن المحتوى صحيح</strong> أو أن الوثيقة حقيقية. الختم فقط يؤكد أن التوقيع المناسب موجود. البلدية أو IND أو جهة أخرى قد تتحقق لاحقاً.</li><li>مدة صلاحية الوثيقة أو الختم <strong>تختلف حسب الجهة</strong>. لشهادتي الميلاد والزواج لا يهم تاريخ الحصول عليهما ولا تاريخ التصديق (Nederland Wereldwijd). ولا تنظر IND عادةً إلى تاريخ الإصدار والتصديق للوثائق ذات البيانات النهائية مثل الميلاد والزواج والوفاة.</li><li><strong>لا يمكن تصديق وثيقة مصدّقة مرة ثانية.</strong> إن احتجت وثيقة أحدث فاطلبها من جديد وصدّقها.</li></ul>'
'<h2 id="convert">تحويل الوثيقة الأجنبية إلى وثيقة هولندية</h2><p>يمكنك أن تطلب من <strong>بلدية لاهاي</strong> (قسم Landelijke Taken) تحويل شهادة ميلاد أو زواج أو شراكة مسجلة أو وفاة من الخارج إلى <strong>وثيقة هولندية</strong>، حتى لو كنت تقيم خارج هولندا. تبقى الوثيقة الأصلية محفوظة ويمكنك طلب نسخة. تقول IND في حالة الزواج إن النسخة تُستخدم في الطلب دون إعادة وثيقة مصدّقة من الخارج. الطلب عبر <a href="https://www.nederlandwereldwijd.nl/buitenlandse-akte-omzetten" rel="noopener">Nederland Wereldwijd</a>. لم نتحقق من الرسوم ولا من المدة، فراجع صفحة لاهاي.</p>'
'<h2 id="gemeente">التسجيل في البلدية وBRP</h2><ul><li>من يقيم في هولندا فعلياً يسجل في <strong>BRP</strong> لدى البلدية خلال <strong>5 أيام</strong> من الوصول (RvIG). التفاصيل في <a href="/articles/bsn-municipality-registration.html">التسجيل في البلدية والحصول على BSN</a>.</li><li>قد تطلب البلدية وثائق مدنية أجنبية (ميلاد، زواج، طلاق). ما تطلبه بالضبط من تصديق أو ترجمة <strong>يختلف حسب البلدية والبلد</strong>، ولم نجد في صفحة RvIG التي راجعناها تفصيلاً بذلك. اسأل بلديتك قبل دفع ثمن ترجمة.</li><li>لاجئو الاستقبال: التسجيل والـBSN يتمان عادةً عبر إجراءات الاستقبال، كما شرحنا في دليل BSN.</li><li>بياناتك المسجلة (الاسم بالحروف اللاتينية، تاريخ الميلاد) تنتقل إلى جهات كثيرة. صحّح الخطأ مبكراً بإثبات رسمي.</li></ul>'
'<h2 id="ind">للمّ الشمل لدى IND</h2><ul><li>أرسل <strong>نسخاً</strong> من الوثائق مع الطلب. وثائق الصلة العائلية (ميلاد، زواج) يفحصها IND أحياناً، فمن المهم أن تكون الأصول <strong>في هولندا</strong> عند التقديم.</li><li>بعد استلام الطلب تصلك رسالة وملحق لإرسال الأصول. <strong>لا ترسل جواز السفر الأصلي أو بطاقة الهوية الأصلية</strong> لقريبك.</li><li>الترجمة: بمترجم محلّف إلى الهولندية أو الإنجليزية أو الفرنسية أو الألمانية.</li><li>إن غابت الوثائق، قد يجري IND فحص DNA أو مقابلة.</li></ul><p>راجع <a href="/articles/asylum-two-status-system-2026.html">نظام الحالتين</a> و<a href="/articles/family-reunification-mvv-ind.html">لمّ الشمل وMVV</a>.</p>'
'<h2 id="diploma">الشهادات الدراسية</h2><p>لتقييم شهادة جامعية أو مهنية تتطلب الجهات المعنية غالباً نسخاً مترجمة ومصدّقة، وتختلف الشروط حسب الجهة. اقرأ <a href="/articles/diploma-evaluation-sbb.html">تقييم الشهادات والمعادلة</a> ولا تبدأ بالترجمة قبل أن تعرف ما تطلبه الجهة بالضبط.</p>'
'<h2 id="examples">أمثلة توضيحية (أمثلة توضيحية وليست حالات أشخاص حقيقيين)</h2>'
+T([['شخص بحوزته شهادة ميلاد سورية بالعربية ويريد استخدامها لدى IND','الطريق ب: تصدّق في سوريا ثم تُترجم عند مترجم محلّف في هولندا. لا حاجة لتصديق الترجمة.'],['شخص ترجم الوثيقة عند مترجم في سوريا','عليه أن يصدّق <strong>الوثيقة والترجمة معاً</strong> لدى وزارة الخارجية السورية.'],['شهادة عدم زواج صدرت قبل 8 أشهر','لا تقبلها IND (أقدم من 6 أشهر). تطلب وثيقة جديدة وتصدّقها.'],['وثيقة صدّقت مرة واحدة وتحتاج نسخة حديثة','لا تصدّق مجدداً؛ تطلب وثيقة جديدة وتصدّقها.'],['عقد زواج سوري ومقيم يريد وثيقة هولندية','قد يطلب تحويلها من بلدية لاهاي، وتبقى الأصلية محفوظة.'],['البلدية لا تقبل دفتر العائلة','اسأل البلدية عن البدائل (ميلاد أو زواج مصدّقان مترجمان).']],['الحالة (افتراضية)','الإجراء'])
+'<p>هذه أمثلة توضيحية وليست حالات أشخاص حقيقيين.</p>'
'<h2 id="mistakes">أخطاء شائعة</h2><ol><li><strong>الترجمة قبل معرفة ما تطلبه الجهة</strong>: اسأل البلدية أو IND أولاً.</li><li><strong>مترجم غير محلّف أمام محكمة هولندية</strong> لوثيقة ستُقدَّم في هولندا.</li><li><strong>وثيقة ناقصة</strong> دون ملحقاتها.</li><li><strong>إرسال الأصول</strong> بلا نسخ احتياطية، أو إرسال جواز السفر الأصلي لـIND.</li><li><strong>الوثيقة المزورة أو المشتراة من وسيط</strong>: مخاطرة جدية على إقامتك. انظر <a href="/articles/scams-phishing-netherlands.html">الاحتيال في هولندا</a>.</li><li><strong>اعتبار الختم ضماناً للقبول</strong>: الجهة المستقبِلة قد تتحقق.</li></ol>'
'<h2 id="help">هل تحتاج مساعدة؟</h2><p>اطلب المساعدة من VluchtelingenWerk أو Juridisch Loket أو المستشارين الاجتماعيين في بلديتك. الروابط الرسمية في <a href="/articles/asylum-residence-hub.html">مركز أدلة اللجوء والإقامة</a>.</p>'
'<h2 id="related">أدلة مرتبطة</h2><ul><li><a href="/articles/bsn-municipality-registration.html">التسجيل في البلدية والحصول على BSN</a></li><li><a href="/articles/diploma-evaluation-sbb.html">تقييم الشهادات والمعادلة</a></li><li><a href="/articles/asylum-family-reunification.html">لمّ شمل عائلة اللاجئ (Nareis)</a></li><li><a href="/articles/family-reunification-mvv-ind.html">لمّ الشمل وMVV</a></li><li><a href="/articles/asylum-two-status-system-2026.html">نظام الحالتين للجوء 2026</a></li><li><a href="/articles/asylum-residence-hub.html">مركز أدلة اللجوء والإقامة</a></li></ul>'),
faq=[('ما هو التصديق (legalisatie)؟','إجراء رسمي يجعل وثيقة صادرة في بلد صالحة للاستخدام في بلد آخر، عادةً بختم أو ملصق. لا يثبت صحة محتواها.'),
('من يصدّق الوثائق السورية لهولندا؟','وزارة الخارجية السورية، لأن السفارة الهولندية في دمشق مغلقة (Nederland Wereldwijd).'),
('هل أترجم في سوريا أم في هولندا؟','الاثنان ممكنان. في سوريا: مترجم محلّف وتصديق الوثيقة والترجمة معاً. في هولندا: تصديق الأصل في سوريا ثم ترجمة عند مترجم محلّف أمام محكمة هولندية دون تصديق الترجمة.'),
('كيف أجد مترجماً محلفاً؟','في سجل Rbtv على موقع Bureau Wbtv (bureauwbtv.nl)، بالبحث بالاسم أو رقم Wbtv أو اللغات أو الرمز البريدي.'),
('هل تنتهي صلاحية شهادة الميلاد المصدّقة؟','لا يهم تاريخ إصدار شهادتي الميلاد والزواج أو تصديقهما (Nederland Wereldwijd). أما شهادة عدم الزواج فتقبلها IND إن لم تتجاوز 6 أشهر.'),
('هل يُقبل دفتر العائلة السوري؟','تقبله بعض البلديات الهولندية دليلاً على الأحوال المدنية. اسأل بلديتك.'),
('هل يمكن تحويل عقد زواج أجنبي إلى عقد هولندي؟','نعم، تطلب ذلك من بلدية لاهاي (Landelijke Taken). تبقى الأصلية محفوظة وتحصل على نسخة.'),
('هل أرسل الأصول إلى IND؟','ترسل نسخاً مع الطلب، ثم الأصول حسب ملحق رسالة الاستلام. لا ترسل جواز السفر أو الهوية الأصلية لقريبك.'),
('كم يكلف التصديق والترجمة؟','لم نجد مصدراً رسمياً للأسعار. اسأل أكثر من مترجم وابدأ مبكراً.'),
('ماذا لو لم تتوفر الوثائق؟','قد يجري IND فحص DNA أو مقابلة. استشر VluchtelingenWerk قبل الاتصال بسلطات بلدك.')],
src_note='راجعنا Nederland Wereldwijd (صفحة سوريا عُدّلت في يوليو 2022، وصفحة تحويل الوثائق في يناير 2026)، وIND (صفحة التصديق والترجمة عُدّلت في فبراير 2025) وBureau Wbtv وRvIG في 8 أكتوبر 2026. الأوضاع في سوريا والإجراءات هناك قد تتغير، فتحقق قبل السفر أو الدفع. لم نتحقق من أسعار الترجمة ولا من رسوم تحويل الوثائق في لاهاي ولا من قواعد كل بلدية بخصوص التصديق عند BRP. الأمثلة توضيحية.')
NL=dict(title='Syrische documenten in Nederland 2026: legaliseren, beëdigde vertaling, inschrijven bij de gemeente en BRP — stap voor stap',
crumb='Syrische documenten: legaliseren en vertalen',
desc='Gids voor het gebruik van Syrische documenten (geboorteakte, huwelijksakte, familieboekje) in Nederland: legalisatie door het Syrische ministerie van Buitenlandse Zaken omdat de Nederlandse ambassade in Damascus gesloten is, beëdigde vertaling en twee routes, het register van beëdigde vertalers, buitenlandse akten omzetten via Den Haag, documenten voor IND, BRP en gemeente, veelgemaakte fouten, met illustratieve voorbeelden en FAQ.',
summary='<ol><li>Voor een Syrisch document in Nederland is <strong>legalisatie door het Syrische ministerie van Buitenlandse Zaken</strong> nodig. <strong>De Nederlandse ambassade in Damascus is gesloten</strong> (Nederland Wereldwijd).</li><li>Een Arabisch document moet <strong>beëdigd vertaald</strong> worden naar Nederlands, Engels, Frans of Duits.</li><li>Twee routes: <strong>(a)</strong> vertalen in Syrië en <strong>document én vertaling</strong> legaliseren, of <strong>(b)</strong> het origineel in Syrië legaliseren en in Nederland vertalen door een vertaler die door een Nederlandse rechtbank is beëdigd; de vertaling hoeft dan niet gelegaliseerd.</li><li>Legalisatie bewijst <strong>niet dat de inhoud klopt</strong>: gemeente of IND mag het nog controleren.</li><li>Inschrijven in de BRP kan en moet binnen <strong>5 dagen</strong> na aankomst (RvIG). Het Syrische familieboekje wordt door <strong>sommige</strong> gemeenten geaccepteerd: vraag het uw gemeente.</li></ol>',
body=(
'<h2 id="why">Waarom legaliseren en vertalen?</h2><p>Volgens de IND maakt legalisatie een officieel document geschikt voor gebruik in een ander land. Er wordt gekeken of het door de juiste organisatie is afgegeven, meestal met een stempel of sticker. Daarna is het document klaar voor gebruik in Nederland. <strong>De IND legaliseert en vertaalt zelf niet.</strong> Het kan veel tijd kosten, dus begin op tijd.</p>'
'<p><strong>Belangrijk:</strong> deze gids gaat ervan uit dat u contact kunt opnemen met Syrische autoriteiten. Bent u vluchteling of vreest u voor uw veiligheid of die van familie als u contact zoekt met de autoriteiten van uw land of de ambassade? <strong>Vraag dan eerst advies aan VluchtelingenWerk of een advocaat.</strong> De officiële pagina’s die wij bekeken, regelen dit niet duidelijk, dus wij geven hier geen oordeel over. Ontbreken documenten, dan kan de IND ook een DNA-onderzoek of interview doen (zie <a href="/nl/articles/asylum-family-reunification.html">Gezinshereniging asiel</a>).</p>'
'<h2 id="steps">Stappen volgens Nederland Wereldwijd (documenten uit Syrië)</h2>'
+T([['Document in het Arabisch','Vertaling nodig voor gebruik in Nederland, door een beëdigd vertaler naar Nederlands, Engels, Frans of Duits.'],['Origineel en compleet','Verwijst het document naar andere documenten of bijlagen, dan moeten die erbij zitten.'],['Ambassade','De Nederlandse ambassade in <strong>Damascus is gesloten</strong>. Legalisatie gebeurt door het <strong>Syrische ministerie van Buitenlandse Zaken</strong>.'],['Route a: vertaling in Syrië','1) Beëdigd vertaler vertaalt. 2) <strong>Document én vertaling</strong> laten legaliseren door het Syrische ministerie van Buitenlandse Zaken.'],['Route b: vertaling in Nederland','1) <strong>Origineel</strong> in Syrië laten legaliseren. 2) In Nederland laten vertalen door een beëdigd vertaler. <strong>De vertaling hoeft niet gelegaliseerd.</strong>'],['Na legalisatie','Klaar voor gebruik in Nederland (ook in Aruba, Curaçao, Sint Maarten, Bonaire, Saba en Sint Eustatius).']],['Onderdeel','Wat de officiële bron zegt'])
+'<h2 id="translator">Een beëdigd vertaler vinden</h2><p>In Nederland moet de vertaler volgens de IND door een Nederlandse rechtbank zijn beëdigd. U vindt hem of haar in het <strong>Register beëdigde tolken en vertalers (Rbtv)</strong> van Bureau Wbtv (Raad voor Rechtsbijstand): <a href="https://www.bureauwbtv.nl/tolk-vertaler-zoeken/" rel="noopener">bureauwbtv.nl/tolk-vertaler-zoeken</a>. Zoeken kan op naam, Wbtv-nummer, talencombinatie en postcode. Een officiële prijslijst vonden wij niet; vraag meerdere vertalers naar prijs en doorlooptijd voordat u begint.</p>'
'<h2 id="get">Documenten die u nog niet hebt</h2>'
+T([['Geboorte-, huwelijks-, echtscheidings- en overlijdensakte','Aanvragen bij het bureau Burgerzaken van het Syrische ministerie van Binnenlandse Zaken (Nederland Wereldwijd).'],['Verklaring van ongehuwd zijn','Zelfde instantie. <strong>De IND accepteert die alleen als zij niet ouder is dan 6 maanden.</strong>'],['Syrisch familieboekje','Wordt in <strong>sommige</strong> gemeenten als bewijs voor aktes van de burgerlijke stand geaccepteerd. Vraag het uw gemeente; ga er niet van uit dat het voldoende is.'],['Overige documenten','Vraag de lokale autoriteiten waar u ze kunt opvragen (Nederland Wereldwijd).']],['Document','Waar en hoe'])
+'<h2 id="validity">Geldigheid en opnieuw legaliseren</h2><ul><li>Legalisatie betekent <strong>niet dat de inhoud klopt</strong> of dat het document echt is. Het stempel zegt alleen dat de juiste handtekening erop staat. Een gemeente, de IND of een andere organisatie kan dit nog controleren.</li><li>Hoelang een document of legalisatiestempel geldig is, verschilt per organisatie. Voor huwelijks- en geboorteaktes maakt het niet uit wanneer u ze kreeg en liet legaliseren (Nederland Wereldwijd). De IND kijkt bij documenten met definitieve gegevens, zoals geboorte-, huwelijks- en overlijdensakte, doorgaans niet naar de afgifte- en legalisatiedatum.</li><li><strong>Een gelegaliseerd document kunt u niet opnieuw laten legaliseren.</strong> Hebt u een recent document nodig, dan vraagt u het opnieuw aan en laat u het legaliseren.</li></ul>'
'<h2 id="convert">Buitenlandse akte omzetten naar een Nederlandse akte</h2><p>U kunt de <strong>gemeente Den Haag</strong> (afdeling Landelijke Taken) vragen een geboorte-, huwelijks-, partnerschaps- of overlijdensakte uit het buitenland om te zetten naar een <strong>Nederlandse akte</strong>, ook als u niet in Nederland woont. De originele akte blijft bewaard en u kunt een afschrift opvragen. Bij een huwelijk zegt de IND dat u dat afschrift voor uw aanvraag kunt gebruiken, zonder opnieuw een gelegaliseerde akte uit het buitenland in te leveren. Aanvragen via <a href="https://www.nederlandwereldwijd.nl/buitenlandse-akte-omzetten" rel="noopener">Nederland Wereldwijd</a>. Kosten en doorlooptijd hebben we niet gecontroleerd: kijk op de pagina van Den Haag.</p>'
'<h2 id="gemeente">Inschrijven bij de gemeente en BRP</h2><ul><li>Wie in Nederland komt wonen, schrijft zich binnen <strong>5 dagen</strong> na aankomst in bij de gemeente in de <strong>BRP</strong> (RvIG). Zie <a href="/nl/articles/bsn-municipality-registration.html">Inschrijven bij de gemeente en BSN</a>.</li><li>De gemeente kan buitenlandse aktes van de burgerlijke stand vragen (geboorte, huwelijk, echtscheiding). Welke legalisatie of vertaling precies nodig is, <strong>verschilt per gemeente en land</strong>; de RvIG-pagina die wij bekeken, gaat daar niet op in. Vraag het uw gemeente voordat u een vertaling bestelt.</li><li>Asielzoekers in de opvang: inschrijving en BSN lopen meestal via de opvangprocedure, zoals in onze BSN-gids staat.</li><li>Staan uw gegevens (spelling van de naam, geboortedatum) fout in de BRP? Laat ze vroeg corrigeren met een officieel bewijs: ze gaan door naar veel instanties.</li></ul>'
'<h2 id="ind">Gezinshereniging bij de IND</h2><ul><li>Stuur <strong>kopieën</strong> mee met de aanvraag. De IND onderzoekt soms documenten die de gezinsband bewijzen; het is daarom belangrijk dat de originelen al <strong>in Nederland</strong> zijn als u aanvraagt.</li><li>Na ontvangst krijgt u een brief met een bijlage voor het opsturen van originelen. <strong>Stuur geen origineel paspoort of identiteitskaart</strong> van uw gezinslid op.</li><li>Vertaling: beëdigd, naar Nederlands, Engels, Frans of Duits.</li><li>Ontbreken documenten, dan kan de IND een DNA-onderzoek of interview doen.</li></ul><p>Zie ook <a href="/nl/articles/asylum-two-status-system-2026.html">Tweestatusstelsel asiel 2026</a> en <a href="/nl/articles/family-reunification-mvv-ind.html">Gezinshereniging en mvv</a>.</p>'
'<h2 id="diploma">Diploma’s</h2><p>Voor waardering van een diploma vragen instanties meestal vertaalde en gelegaliseerde kopieën; de eisen verschillen per instantie. Lees <a href="/nl/articles/diploma-evaluation-sbb.html">Diplomawaardering en gelijkwaardigheid</a> en bestel pas een vertaling als u weet wat gevraagd wordt.</p>'
'<h2 id="examples">Illustratieve voorbeelden (illustratief, geen echte personen)</h2>'
+T([['Iemand heeft een Syrische geboorteakte in het Arabisch en wil die bij de IND gebruiken','Route b: in Syrië laten legaliseren en in Nederland door een beëdigd vertaler laten vertalen. De vertaling hoeft niet gelegaliseerd.'],['Iemand laat de akte in Syrië vertalen','<strong>Akte én vertaling</strong> laten legaliseren door het Syrische ministerie van Buitenlandse Zaken.'],['Verklaring van ongehuwd zijn van 8 maanden geleden','De IND accepteert die niet (ouder dan 6 maanden). Nieuwe verklaring aanvragen en legaliseren.'],['Document is al gelegaliseerd, maar er is een recentere nodig','Niet opnieuw legaliseren: een nieuw document aanvragen en dat laten legaliseren.'],['Syrische huwelijksakte, bewoner van Nederland wil een Nederlandse akte','Kan bij de gemeente Den Haag worden omgezet; het origineel blijft bewaard.'],['De gemeente accepteert het familieboekje niet','Vraag welke andere documenten (geboorte-, huwelijksakte gelegaliseerd en vertaald) zij willen.']],['Situatie (verzonnen)','Handeling'])
+'<p>Illustratieve voorbeelden, geen echte personen.</p>'
'<h2 id="mistakes">Veelgemaakte fouten</h2><ol><li><strong>Vertalen voordat u weet wat de instantie vraagt</strong>: vraag het eerst de gemeente of de IND.</li><li><strong>Vertaler die niet door een Nederlandse rechtbank is beëdigd</strong> voor een document dat in Nederland gebruikt wordt.</li><li><strong>Onvolledig document</strong> zonder bijlagen.</li><li><strong>Originelen sturen zonder kopieën</strong>, of het originele paspoort naar de IND sturen.</li><li><strong>Een vervalst of via een tussenpersoon gekocht document</strong>: een groot risico voor uw verblijf. Zie <a href="/nl/articles/scams-phishing-netherlands.html">Oplichting in Nederland</a>.</li><li><strong>Denken dat het stempel acceptatie garandeert</strong>: de ontvanger mag nog controleren.</li></ol>'
'<h2 id="help">Hulp nodig?</h2><p>Vraag hulp aan VluchtelingenWerk, het Juridisch Loket of sociaal raadslieden in uw gemeente. De officiële links staan in de <a href="/nl/articles/asylum-residence-hub.html">hub asiel en verblijf</a>.</p>'
'<h2 id="related">Gerelateerde gidsen</h2><ul><li><a href="/nl/articles/bsn-municipality-registration.html">Inschrijven bij de gemeente en BSN</a></li><li><a href="/nl/articles/diploma-evaluation-sbb.html">Diplomawaardering en gelijkwaardigheid</a></li><li><a href="/nl/articles/asylum-family-reunification.html">Gezinshereniging asiel (nareis)</a></li><li><a href="/nl/articles/family-reunification-mvv-ind.html">Gezinshereniging en mvv</a></li><li><a href="/nl/articles/asylum-two-status-system-2026.html">Tweestatusstelsel asiel 2026</a></li><li><a href="/nl/articles/asylum-residence-hub.html">Hub asiel en verblijf</a></li></ul>'),
faq=[('Wat is legalisatie?','Een officiële handeling waarmee een document uit het ene land geschikt wordt voor gebruik in een ander land, meestal met stempel of sticker. Het bewijst niet dat de inhoud klopt.'),
('Wie legaliseert Syrische documenten voor Nederland?','Het Syrische ministerie van Buitenlandse Zaken, omdat de Nederlandse ambassade in Damascus gesloten is (Nederland Wereldwijd).'),
('Vertalen in Syrië of in Nederland?','Beide kan. In Syrië: beëdigd vertaler en document én vertaling legaliseren. In Nederland: origineel in Syrië legaliseren en laten vertalen door een beëdigd vertaler; de vertaling hoeft niet gelegaliseerd.'),
('Hoe vind ik een beëdigd vertaler?','In het Register beëdigde tolken en vertalers (Rbtv) via bureauwbtv.nl, te doorzoeken op naam, Wbtv-nummer, talencombinatie en postcode.'),
('Verloopt een gelegaliseerde geboorteakte?','Voor geboorte- en huwelijksaktes maakt de afgifte- of legalisatiedatum niet uit (Nederland Wereldwijd). Een verklaring van ongehuwd zijn accepteert de IND alleen als zij niet ouder is dan 6 maanden.'),
('Wordt het Syrische familieboekje geaccepteerd?','Sommige Nederlandse gemeenten accepteren het als bewijs voor aktes van de burgerlijke stand. Vraag het uw gemeente.'),
('Kan een buitenlandse huwelijksakte worden omgezet naar een Nederlandse?','Ja, bij de gemeente Den Haag (afdeling Landelijke Taken). Het origineel blijft bewaard; u kunt een afschrift opvragen.'),
('Moet ik originelen naar de IND sturen?','Bij de aanvraag stuurt u kopieën; originelen volgen via de bijlage bij de ontvangstbevestiging. Stuur nooit het originele paspoort of de identiteitskaart van uw gezinslid.'),
('Wat kost legaliseren en vertalen?','Dat hebben we niet bij een officiële bron kunnen controleren. Vraag meerdere vertalers om een offerte en begin op tijd.'),
('En als ik geen documenten kan krijgen?','De IND kan een DNA-onderzoek of interview doen. Vraag eerst advies aan VluchtelingenWerk voordat u contact opneemt met autoriteiten van uw land.')],
src_note='Gecontroleerd bij Nederland Wereldwijd (pagina Syrië laatst gewijzigd in juli 2022, pagina akten omzetten januari 2026), de IND (pagina legaliseren en vertalen februari 2025), Bureau Wbtv en de RvIG op 8 oktober 2026. De situatie in Syrië en de procedures daar kunnen veranderen: controleer vóór u reist of betaalt. Niet gecontroleerd: vertaalkosten, leges voor het omzetten van akten in Den Haag en wat elke gemeente vraagt bij de BRP-inschrijving. Voorbeelden illustratief, geen echte personen.')
AR['seo_title']='الوثائق السورية في هولندا 2026: تصديق وترجمة'
AR['desc']='كيف تستخدم وثائقك السورية في هولندا: التصديق (legalisatie)، الترجمة المحلفة، وتسجيلها في البلدية. خطوات ومصادر رسمية.'
NL['seo_title']='Syrische documenten in Nederland 2026'
NL['desc']='Syrische documenten gebruiken in Nederland: legalisatie, beëdigde vertaling en inschrijving bij de gemeente. Stappen en officiële bronnen.'
#xlink
AR['body']+='<p><strong>مصطلح غير مفهوم في رسالتك؟</strong> ابحث عنه في <a href="/articles/dutch-government-terms-glossary.html">قاموس المصطلحات الحكومية الهولندية</a> (141 مصطلحاً مع النطق والمعنى).</p>'
NL['body']+='<p><strong>Een woord in uw brief niet begrepen?</strong> Zoek het op in <a href="/nl/articles/dutch-government-terms-glossary.html">Overheidstaal uitgelegd</a> (141 begrippen met het Arabische woord).</p>'
