from a_student_finance import T
SLUG='annual-tax-return-2026'
SRC=[('Belastingdienst · Moet ik aangifte inkomstenbelasting 2025 doen?','https://www.belastingdienst.nl/wps/wcm/connect/nl/belastingaangifte/content/moet_ik_aangifte_doen'),
('Belastingdienst · Aangifte inkomstenbelasting','https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/hoe_werkt_inkomstenbelasting/aangifte_doen/aangifte-doen'),
('Belastingdienst · Wat gebeurt er als ik geen aangifte doe, of te laat?','https://www.belastingdienst.nl/wps/wcm/connect/nl/belastingaangifte/content/wat-gebeurt-er-als-ik-geen-aangifte-doe-of-te-laat-of-onvolledig'),
('Belastingdienst · Hoeveel jaar terug nog aangifte doen?','https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/hoe_werkt_inkomstenbelasting/aangifte_doen/hoeveel-jaar-terug-belastingaangifte-doen'),
('Belastingdienst · Wat gebeurt er na de aangifte?','https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/hoe_werkt_inkomstenbelasting/aangifte_doen/wat_gebeurt_er_na_de_aangifte'),
('Belastingdienst · Box 1: uitleg en tarieven','https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/heffingskortingen_boxen_tarieven/boxen_en_tarieven/box_1/box_1'),
('Belastingdienst · Ik heb een foutje ontdekt in mijn aangifte','https://www.belastingdienst.nl/wps/wcm/connect/nl/belastingaangifte/content/ik-heb-een-foutje-ontdekt'),
('Belastingdienst · Eisen bezwaar','https://www.belastingdienst.nl/wps/wcm/connect/nl/bezwaar-en-beroep/content/eisen-bezwaar'),
('Belastingdienst · Definitieve aanslag','https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/hoe_werkt_inkomstenbelasting/aanslag/definitieve_aanslag'),
('Belastingdienst · Voorlopige aanslag: tarieven en heffingskortingen 2026','https://www.belastingdienst.nl/wps/wcm/connect/nl/voorlopige-aanslag/content/voorlopige-aanslag-tarieven-en-heffingskortingen'),
('Belastingdienst · Hoe kan ik mijn voorlopige aanslag wijzigen?','https://www.belastingdienst.nl/wps/wcm/connect/nl/voorlopige-aanslag/content/hoe-kan-ik-mijn-voorlopige-aanslag-wijzigen'),
('Belastingdienst · Werkelijk rendement in de belastingaangifte (box 3)','https://www.belastingdienst.nl/wps/wcm/connect/nl/box-3/content/werkelijk-rendement-belastingaangifte'),
('Rijksoverheid · Fiscale sleuteltabel 2027 (voorstel)','https://www.rijksoverheid.nl/documenten/2026/09/15/fiscale-sleuteltabel-2027'),
('Belastingdienst · Boete','https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/standaard_functies/prive/contact/rechten_en_plichten_bij_de_belastingdienst/boete')]
AR=dict(title='الإقرار الضريبي في هولندا 2026: دخل 2025، ماذا تفعل إن تأخرت، كيف تصحح أو تعترض، والاستعداد لإقرار 2026',
crumb='الإقرار الضريبي',
desc='دليل aangifte inkomstenbelasting لدخل 2025: هل أنت ملزم، المواعيد (1 مايو، 1 سبتمبر مع التأجيل، 14 يوليو)، الغرامة 469 يورو، شرائح box 1 لعام 2025، قاعدة 5 سنوات للاسترداد، وخطوات عملية إن فاتك الموعد، وتصحيح الإقرار، والاعتراض خلال 6 أسابيع، وشرائح 2026 والتقدير المؤقت 2027.',
summary='<ol><li>الإقرار الذي يُقدَّم في 2026 يخص <strong>دخل 2025</strong>. إن وصلتك رسالة من Belastingdienst فأنت ملزم به، وموعده عادةً <strong>1 مايو</strong> (أو 1 سبتمبر إن حصلت على تأجيل).</li><li>إن لم تصلك رسالة فعليك التقديم إذا كنت ستدفع <strong>58 يورو فأكثر</strong>، ويُنصح بالتقديم إن كنت ستستردّ مبلغاً فوق الحد الأدنى للاسترداد (نحو 18–19 يورو).</li><li>التأخر بعد التذكير قد يعني <strong>غرامة 469 يورو</strong>، وإن لم تقدّم أصلاً فستفرض عليك Belastingdienst تقديراً لدخلك مع غرامة.</li><li>إن لم تصلك رسالة يمكنك التقديم حتى <strong>5 سنوات للخلف</strong> (مثلاً إقرار 2025 حتى 31 ديسمبر 2030).</li><li>تاريخ اليوم (أكتوبر 2026): مواعيد 2025 العادية انتهت؛ إن لم تقدّم بعد فقدّم الآن بدل الانتظار.</li></ol>',
body=(
'<h2 id="who">هل أنا ملزم بتقديم الإقرار؟</h2><ul><li><strong>وصلتك رسالة (aangiftebrief):</strong> يجب التقديم قبل التاريخ المكتوب فيها، وهو غالباً 1 مايو.</li><li><strong>لم تصلك رسالة:</strong> سجّل الدخول إلى «Mijn Belastingdienst»، وافتح إقرار 2025، <strong>واملأه كاملاً دون إرساله</strong>، ثم انظر النتيجة: إن كان عليك دفع 58 يورو فأكثر فقدّمه فوراً (قبل 14 يوليو من السنة التالية وإلا قد تُغرَّم)، وإن كنت ستستردّ أكثر من الحد الأدنى فأرسله لتحصل على المبلغ.</li><li><strong>إن كنت تتلقى toeslagen</strong> (دعم) وكان لديك أنت أو شريكك أو أطفالك القاصرون أصول فوق <strong>37,395 يورو</strong> (74,790 مع شريك ضريبي)، فقدّم الإقرار حتى لو كانت النتيجة صغيرة.</li><li><strong>إن وصلت إلى هولندا أو غادرتها خلال السنة:</strong> لدى Belastingdienst مسار خاص لمن عاش جزءاً من السنة في هولندا (إقرار سنة الهجرة). افتح صفحته الرسمية ولا تستعمل الإقرار العادي بلا قراءة.</li></ul>'
'<p>وهكذا فإن «لم تصلني رسالة» لا تعني «لا التزام عليّ»: افحص بنفسك.</p>'
'<h2 id="dates">المواعيد والعواقب</h2>'
+T([['إقرار 2025 بعد وصول رسالة','قبل التاريخ في الرسالة، غالباً <strong>1 مايو 2026</strong>'],['مع تأجيل (uitstel)','قبل التاريخ في رسالة التأكيد، غالباً <strong>1 سبتمبر 2026</strong>'],['بدون رسالة وستدفع ≥ 58 يورو','قبل <strong>14 يوليو 2026</strong> وإلا قد تُغرَّم إن طلبت منك Belastingdienst بعده'],['بعد انتهاء الموعد','تذكير ثم تنبيه (aanmaning) بمهلة <strong>10 أيام عمل</strong>، وغرامة تأخير <strong>469 يورو</strong>'],['عدم التقديم أبداً','تقدير دخلك (ambtshalve aanslag) مع غرامة؛ والغرامة قد تصل إلى <strong>6,709 يورو</strong> عند التكرار لعدة سنوات'],['إقرار بدون رسالة','ممكن حتى 5 سنوات للخلف؛ إقرار 2025 حتى 31/12/2030 وإقرار 2021 حتى 31/12/2026']],['الحالة','الموعد/النتيجة'])
+'<aside class="notice">لأن الموعد العادي لدخل 2025 مضى، فإن لم تقدّم فلا تؤجل أكثر: كل شهر تأخير يزيد احتمال التذكير والتنبيه والغرامة. إن كان لديك تأخر وسبب وجيه فراسل Belastingdienst بالطريقة الموضحة في صفحتهم.</aside>'
'<h2 id="rates">كيف تُحسب الضريبة؟ شرائح box 1 لعام 2025</h2><p>box 1 هو الدخل من العمل والسكن. الشرائح لعام 2025 (للقادمين الذين لم يبلغوا سن AOW):</p>'
+T([['1','حتى 38,441','35.82%'],['2','أكثر من 38,441 حتى 76,817','37.48%'],['3','أكثر من 76,817','49.50%']],['الشريحة','الدخل الخاضع للضريبة (يورو)','النسبة'])
+'<p>وهذه الأرقام «قبل الخصومات»: تُخصم منها <strong>heffingskortingen</strong> مثل arbeidskorting (حتى 5,599 يورو في 2025 لمن لم يبلغ سن AOW) وalgemene heffingskorting. وغالباً يطبّقها صاحب العمل في راتبك الشهري.</p>'
'<h3>مثال حسابي (قبل heffingskortingen)</h3><p>دخل خاضع للضريبة 50,000 يورو:</p><ul><li>الشريحة 1: 38,441 × 35.82% = <strong>13,769.57</strong></li><li>الشريحة 2: (50,000 − 38,441) × 37.48% = 11,559 × 37.48% = <strong>4,332.31</strong></li><li>المجموع قبل الخصومات ≈ <strong>18,101.88 يورو</strong></li></ul><p>هذا ليس ما تدفعه فعلياً، لأن الخصومات تخفضه، وصاحب العمل قد دفع جزءاً عبر loonheffing. الإقرار يحسب الفرق: إن كان ما دُفع أكثر من المستحق فتستردّ.</p>'
'<h2 id="steps">خطوات تقديم الإقرار</h2><ol><li>سجّل الدخول إلى <strong>Mijn Belastingdienst</strong> بـ DigiD (<a href="/articles/digid-registration-guide.html">دليل DigiD</a>).</li><li>افتح الإقرار للسنة المطلوبة؛ ستجد بيانات كثيرة <strong>معبأة مسبقاً</strong> (راتب، تأمين، أحياناً رهن).</li><li>راجع كل بند مقابل <strong>jaaropgaaf</strong> (بيان الراتب السنوي من صاحب العمل) وكشوفاتك. انظر <a href="/articles/dutch-payslip-explained.html">شرح قسيمة الراتب</a>.</li><li>أضف ما لم يُعبأ: دخل آخر، حسابات في الخارج، أصول في 1 يناير (box 3).</li><li>أرسل الإقرار واحتفظ بالتأكيد.</li><li>تتلقى <strong>aanslag</strong> (القرار): إن قدّمت قبل 1 أبريل فتصلك الإجابة غالباً قبل 1 يوليو، وبعده خلال نحو 3 أشهر. الحد النهائي لإقرار 2025 هو 31 ديسمبر 2028.</li></ol>'
'<h2 id="mistakes">أخطاء شائعة</h2><ul><li><strong>الاعتماد على عدم وصول رسالة.</strong> افحص بنفسك.</li><li><strong>إرسال بيانات معبأة مسبقاً دون مراجعة.</strong> الخطأ يخصك.</li><li><strong>نسيان الدخل أو الحسابات خارج هولندا.</strong></li><li><strong>إهمال تأثير الإقرار على toeslagen.</strong> بيانات الإقرار تؤثر في الحساب النهائي للدعم (<a href="/articles/toeslagen-income-update.html">تحديث الدخل في Toeslagen</a>).</li><li><strong>الظن أن الإقرار = استرداد مضمون.</strong> قد تكون النتيجة دفعاً إضافياً.</li></ul>'
'<h2 id="late">فاتك الموعد؟ ماذا تفعل الآن</h2><ol><li><strong>قدّم فوراً</strong> عبر Mijn Belastingdienst، حتى بعد الموعد: تقول Belastingdienst «قدّم في أسرع وقت، فبذلك تتجنب الغرامة». لم يعد طلب التأجيل ممكناً لإقرار 2025 (كان حتى 1 مايو 2026).</li><li><strong>إن وصلك تذكير (herinnering)</strong> فهذا طلب صريح بالتقديم. بعده يأتي <strong>تنبيه (aanmaning)</strong> يجب أن يصل إقرارك خلاله في <strong>10 أيام عمل</strong> من تاريخ التنبيه.</li><li><strong>عواقب التأخر:</strong> غرامة تأخير <strong>469 يورو</strong> (حتى 6,709 يورو عند التكرار)، وقد تتوقف دفعات toeslagen والتقدير المؤقت، وتُحسب فائدة ضريبية (belastingrente).</li><li><strong>إن لم تقدّم أبداً</strong> تقدّر Belastingdienst دخلك وترسل لك قراراً مع غرامة، وغالباً يكون التقدير أعلى من الواقع.</li></ol><h2 id="fix">أخطأت في الإقرار أو لا توافق على القرار؟</h2>'
+T([['تصحيح خطأ في إقرارك','ادخل Mijn Belastingdienst، اختر السنة، ثم «Mijn aangifte inkomstenbelasting wijzigen»، عدّل وأرسل. ممكن حتى <strong>5 سنوات</strong> بعد السنة المعنية، وحتى بعد القرار النهائي. آخر إقرار يصلهم هو الذي يُعالَج.'],['الاعتراض على القرار (bezwaar)','خلال <strong>6 أسابيع من التاريخ المكتوب على القرار (aanslag)</strong>: عبر الإنترنت بـDigiD، أو بالنموذج، أو برسالة تذكر رقم القرار.'],['متى يصبح القرار نهائياً؟','يصلك القرار النهائي (definitieve aanslag) خلال <strong>3 سنوات</strong> كحد أقصى من 1 يناير بعد سنة الإقرار.'],['أصول ومدخرات (box 3)','في إقرار 2025 يمكنك اختيارياً ذكر العائد الحقيقي (werkelijk rendement)؛ تحسب Belastingdienst الضريبة بالطريقتين وتأخذ الأفضل لك.']],['الحالة','ما تفعله'])
 +'<h2 id="next">استعد للسنة القادمة: إقرار 2026 والتقدير المؤقت 2027</h2><p><strong>شرائح box 1 لعام 2026</strong> (قبل سن AOW)، حسب Belastingdienst:</p>'
+T([['1','حتى 38,883','35.75%'],['2','38,883 حتى 78,426','37.56%'],['3','أكثر من 78,426','49.50%']],['الشريحة','الدخل (يورو)','النسبة'])
 +'<ul><li><strong>الخصم العام 2026:</strong> حتى 3,115 يورو، يتناقص فوق 29,736 يورو. <strong>خصم العمل 2026:</strong> حتى 5,685 يورو.</li><li><strong>التقدير المؤقت (voorlopige aanslag) 2027:</strong> من طلبه يصله في بداية كل سنة (في السنوات الأخيرة بدأ الإرسال من ديسمبر). إن لم يكن صحيحاً عدّله بنموذج «Verzoek of wijziging voorlopige aanslag» في Mijn Belastingdienst؛ الرد خلال 4–5 أسابيع عادة، ويمكن التعديل حتى 1 مايو من السنة التالية.</li><li><strong>إقرار دخل 2026</strong> يُقدَّم في 2027، والموعد هو المكتوب في رسالتك (غالباً 1 مايو). المواعيد الرسمية لـ2027 لم تُنشر بعد.</li><li><strong>خطط 2027 (مقترحة، لم يقرها البرلمان):</strong> شرائح 36.23% و38.16% و49.50% حسب جدول Prinsjesdag (<a href="/articles/prinsjesdag-2026-changes.html">ما الذي يتغير في 2027</a>).</li></ul>'
'<h2 id="glossary">مسرد</h2><ul><li><strong>Aangifte:</strong> الإقرار الضريبي.</li><li><strong>Aanslag:</strong> قرار Belastingdienst بالمبلغ المطلوب أو المسترد.</li><li><strong>Jaaropgaaf:</strong> بيان الراتب السنوي.</li><li><strong>Heffingskorting:</strong> خصم ضريبي.</li><li><strong>Verzuimboete:</strong> غرامة التأخر في التقديم.</li><li><strong>Uitstel:</strong> تأجيل موعد التقديم.</li></ul>'),
faq=[('هل أقدّم الإقرار إن لم تصلني رسالة؟','افحص بنفسك: إن كنت ستدفع 58 يورو فأكثر فأنت ملزم؛ وإن كنت ستستردّ مبلغاً فوق الحد الأدنى فقدّم لتحصل عليه؛ وإن كنت تتلقى toeslagen وأصولك فوق الحد فقدّم أيضاً.'),
('ما غرامة التأخر؟','469 يورو بعد التأخر عن المهلة، وقد تصل غرامات الامتناع المتكرر إلى 6,709 يورو.'),
('هل يمكنني التقديم لسنوات سابقة؟','نعم، حتى 5 سنوات للخلف إن لم تصلك رسالة تلزمك بالتقديم (إقرار 2021 حتى 31 ديسمبر 2026).'),
('متى أعرف النتيجة؟','إن قدّمت قبل 1 أبريل فقبل 1 يوليو غالباً؛ وإن قدّمت بعده فنحو 3 أشهر، وقد تطول في حالات خاصة.'),
('كم لدي من الوقت للاعتراض على قرار الضريبة؟','6 أسابيع من التاريخ المكتوب على القرار (aanslag). أما تصحيح خطأ في إقرارك فممكن حتى 5 سنوات.'),
('هل إقرار 2026 يختلف؟','يخص دخل 2026 ويُقدَّم في 2027؛ الشرائح والخصومات تتغير، فراجع الصفحة الرسمية للسنة المعنية.')],
src_note='راجعنا صفحات Belastingdienst في 4 أكتوبر 2026. عتبات الدفع/الاسترداد تظهر بأرقام متقاربة في الصفحات الرسمية (58 يورو؛ 18–19 يورو)، فتحقق منها في Mijn Belastingdienst لحالتك.')
NL=dict(title='Aangifte inkomstenbelasting 2026: inkomen 2025, te laat, verbeteren of bezwaar, en vooruitblik op de aangifte over 2026',
crumb='Aangifte inkomstenbelasting',
desc='Gids over de aangifte inkomstenbelasting 2025: moet jij aangifte doen, deadlines (1 mei, 1 september met uitstel, 14 juli), verzuimboete € 469, box 1-tarieven 2025, 5 jaar terug aangifte doen en praktische stappen als je de deadline hebt gemist, aangifte verbeteren, bezwaar binnen 6 weken, tarieven 2026 en de voorlopige aanslag 2027.',
summary='<ol><li>De aangifte die je in 2026 doet gaat over het <strong>inkomen van 2025</strong>. Kreeg je een aangiftebrief, dan moet je aangifte doen; de datum is meestal <strong>1 mei</strong> (of 1 september met uitstel).</li><li>Geen brief? Dan moet je aangifte doen als je <strong>€ 58 of meer</strong> moet betalen; krijg je geld terug boven de teruggaafgrens (circa € 18–19), dan is aangifte verstandig.</li><li>Te laat na de herinnering kan een <strong>verzuimboete van € 469</strong> volgen; doe je helemaal geen aangifte, dan schat de Belastingdienst je inkomen en legt een boete op.</li><li>Zonder aangiftebrief kun je tot <strong>5 jaar terug</strong> aangifte doen (aangifte 2025 tot en met 31 december 2030).</li><li>Vandaag (oktober 2026) zijn de gewone deadlines voor 2025 verstreken; heb je nog niet ingediend, doe het dan nu.</li></ol>',
body=(
'<h2 id="who">Moet ik aangifte doen?</h2><ul><li><strong>Je kreeg een aangiftebrief:</strong> doe aangifte vóór de datum in de brief, meestal 1 mei.</li><li><strong>Geen brief:</strong> log in op “Mijn Belastingdienst”, open de aangifte 2025, <strong>vul alles in maar verstuur nog niet</strong> en kijk naar de uitkomst: moet je € 58 of meer betalen, doe dan zo snel mogelijk aangifte (vóór 14 juli van het jaar erna, anders kun je een boete krijgen); krijg je meer terug dan de teruggaafgrens, verstuur dan om het bedrag te ontvangen.</li><li><strong>Ontvang je toeslagen</strong> en hebben jij, je partner of je minderjarige kinderen samen meer dan <strong>€ 37.395</strong> vermogen (€ 74.790 met fiscaal partner), doe dan ook aangifte, zelfs bij een klein bedrag.</li><li><strong>Net in Nederland gekomen of vertrokken in 2025:</strong> de Belastingdienst heeft een aparte route voor wie een deel van het jaar in Nederland woonde (aangifte jaar van immigratie of emigratie). Lees die pagina.</li></ul>'
'<p>“Ik kreeg geen brief” betekent dus niet “ik hoef niets”: controleer het zelf.</p>'
'<h2 id="dates">Deadlines en gevolgen</h2>'
+T([['Aangifte 2025 na een aangiftebrief','vóór de datum in de brief, meestal <strong>1 mei 2026</strong>'],['Met uitstel','vóór de datum in de bevestiging, meestal <strong>1 september 2026</strong>'],['Geen brief en je moet ≥ € 58 betalen','vóór <strong>14 juli 2026</strong>, anders kun je een boete krijgen als de Belastingdienst je daarna vraagt aangifte te doen'],['Na de deadline','herinnering, daarna aanmaning met <strong>10 werkdagen</strong>; verzuimboete van <strong>€ 469</strong>'],['Helemaal geen aangifte','schatting van je inkomen (ambtshalve aanslag) plus boete; de verzuimboete kan oplopen tot <strong>€ 6.709</strong> bij meerdere jaren'],['Aangifte zonder brief','tot 5 jaar terug: 2025 tot 31-12-2030, 2021 tot 31-12-2026']],['Situatie','Termijn/gevolg'])
+'<aside class="notice">De gewone termijn voor 2025 is voorbij. Heb je nog niet ingediend, stel het dan niet verder uit: elke maand vergroot de kans op herinnering, aanmaning en boete. Heb je een goede reden voor de vertraging, schrijf de Belastingdienst dan zoals op hun pagina staat.</aside>'
'<h2 id="rates">Hoe wordt de belasting berekend? Box 1-tarieven 2025</h2><p>Box 1 is inkomen uit werk en woning. Tarieven 2025 (voor wie de AOW-leeftijd nog niet bereikt):</p>'
+T([['1','tot € 38.441','35,82%'],['2','meer dan € 38.441 tot € 76.817','37,48%'],['3','meer dan € 76.817','49,50%']],['Schijf','Belastbaar inkomen','Percentage'])
+'<p>Dit zijn bedragen vóór <strong>heffingskortingen</strong> zoals arbeidskorting (maximaal € 5.599 in 2025 voor wie de AOW-leeftijd nog niet bereikt) en algemene heffingskorting. Je werkgever past ze meestal al toe in je maandloon.</p>'
'<h3>Rekenvoorbeeld (vóór heffingskortingen)</h3><p>Belastbaar inkomen € 50.000:</p><ul><li>Schijf 1: 38.441 × 35,82% = <strong>€ 13.769,57</strong></li><li>Schijf 2: (50.000 − 38.441) × 37,48% = 11.559 × 37,48% = <strong>€ 4.332,31</strong></li><li>Totaal vóór kortingen ≈ <strong>€ 18.101,88</strong></li></ul><p>Dit is niet wat je uiteindelijk betaalt: de kortingen verlagen het bedrag en je werkgever hield al loonheffing in. De aangifte verrekent het verschil: is er te veel betaald, dan krijg je terug.</p>'
'<h2 id="steps">Aangifte doen in stappen</h2><ol><li>Log in op <strong>Mijn Belastingdienst</strong> met DigiD (<a href="/nl/articles/digid-registration-guide.html">gids DigiD</a>).</li><li>Open de aangifte van het juiste jaar; veel gegevens zijn <strong>vooraf ingevuld</strong>.</li><li>Controleer alles met je <strong>jaaropgaaf</strong> en bankgegevens. Zie <a href="/nl/articles/dutch-payslip-explained.html">loonstrook uitgelegd</a>.</li><li>Vul aan wat ontbreekt: ander inkomen, buitenlandse rekeningen, vermogen op 1 januari (box 3).</li><li>Verstuur en bewaar de bevestiging.</li><li>Je ontvangt de <strong>aanslag</strong>: doe je aangifte vóór 1 april, dan hoor je meestal vóór 1 juli; daarna binnen ongeveer 3 maanden. De aanslag 2025 is uiterlijk op 31 december 2028 definitief.</li></ol>'
'<h2 id="mistakes">Veelgemaakte fouten</h2><ul><li><strong>Erop vertrouwen dat er geen brief kwam.</strong> Controleer zelf.</li><li><strong>Vooraf ingevulde gegevens niet controleren.</strong> Fouten zijn jouw verantwoordelijkheid.</li><li><strong>Inkomen of rekeningen buiten Nederland vergeten.</strong></li><li><strong>De invloed op toeslagen negeren.</strong> De gegevens uit je aangifte werken door in de definitieve berekening (<a href="/nl/articles/toeslagen-income-update.html">inkomen bijwerken bij Toeslagen</a>).</li><li><strong>Denken dat aangifte altijd geld oplevert.</strong> Je kunt ook moeten bijbetalen.</li></ul>'
'<h2 id="late">Deadline gemist? Wat je nu doet</h2><ol><li><strong>Doe zo snel mogelijk aangifte</strong> via Mijn Belastingdienst, ook na de deadline: «zo voorkomt u een boete». Uitstel aanvragen voor 2025 kon tot 1 mei 2026.</li><li><strong>Herinnering ontvangen?</strong> Dan volgt een <strong>aanmaning</strong>: je aangifte moet binnen <strong>10 werkdagen</strong> na de datum op de aanmaning binnen zijn.</li><li><strong>Gevolgen:</strong> verzuimboete <strong>€ 469</strong> (tot € 6.709 bij herhaling), toeslagen en voorlopige aanslag kunnen stoppen, en je betaalt belastingrente.</li><li><strong>Helemaal geen aangifte:</strong> de Belastingdienst schat je inkomen en stuurt een aanslag met boete.</li></ol><h2 id="fix">Fout gemaakt of niet eens met de aanslag?</h2>'
+T([['Fout in je aangifte','Mijn Belastingdienst → jaar kiezen → «Mijn aangifte inkomstenbelasting wijzigen». Kan tot <strong>5 jaar</strong> na het jaar, ook na een definitieve aanslag. De laatste aangifte wordt behandeld.'],['Bezwaar tegen de aanslag','Binnen <strong>6 weken na de datum van de aanslag</strong>: online met DigiD, met het formulier of per brief met het aanslagnummer.'],['Wanneer is de aanslag definitief?','Uiterlijk binnen <strong>3 jaar</strong>, gerekend vanaf 1 januari na het aangiftejaar.'],['Vermogen (box 3)','In de aangifte 2025 kun je vrijwillig je werkelijk rendement opgeven; de Belastingdienst rekent beide manieren uit en kiest de voordeligste.']],['Situatie','Wat je doet'])
 +'<h2 id="next">Vooruitblik: aangifte over 2026 en voorlopige aanslag 2027</h2><p><strong>Box 1-tarieven 2026</strong> (onder de AOW-leeftijd) volgens de Belastingdienst:</p>'
+T([['1','tot € 38.883','35,75%'],['2','€ 38.883 tot € 78.426','37,56%'],['3','meer dan € 78.426','49,50%']],['Schijf','Inkomen','Percentage'])
 +'<ul><li><strong>Algemene heffingskorting 2026:</strong> maximaal € 3.115, afbouw boven € 29.736. <strong>Arbeidskorting 2026:</strong> maximaal € 5.685.</li><li><strong>Voorlopige aanslag 2027:</strong> wie die heeft aangevraagd, krijgt hem aan het begin van elk jaar (de laatste jaren vanaf december). Klopt hij niet, wijzig hem met «Verzoek of wijziging voorlopige aanslag»; antwoord meestal binnen 4–5 weken, wijzigen kan tot 1 mei van het jaar erna.</li><li><strong>Aangifte over 2026</strong> doe je in 2027, vóór de datum in je brief (vaak 1 mei). De officiële data voor 2027 zijn nog niet gepubliceerd.</li><li><strong>Plannen 2027 (voorstel, nog niet aangenomen):</strong> 36,23%, 38,16% en 49,50% volgens de fiscale sleuteltabel van Prinsjesdag (<a href="/nl/articles/prinsjesdag-2026-changes.html">wat verandert er in 2027</a>).</li></ul>'
'<h2 id="glossary">Begrippen</h2><ul><li><strong>Aangifte:</strong> belastingaangifte.</li><li><strong>Aanslag:</strong> besluit over te betalen of terug te krijgen bedrag.</li><li><strong>Jaaropgaaf:</strong> jaaroverzicht van je loon.</li><li><strong>Heffingskorting:</strong> belastingkorting.</li><li><strong>Verzuimboete:</strong> boete bij te late aangifte.</li><li><strong>Uitstel:</strong> verlenging van de aangiftetermijn.</li></ul>'),
faq=[('Moet ik aangifte doen als ik geen brief kreeg?','Controleer het zelf: moet je € 58 of meer betalen dan ben je verplicht; krijg je geld terug boven de teruggaafgrens dan loont aangifte; ontvang je toeslagen en is je vermogen boven de grens, dan doe je ook aangifte.'),
('Hoe hoog is de boete?','Een verzuimboete van € 469 bij te laat indienen; bij herhaald verzuim kan die oplopen tot € 6.709.'),
('Kan ik over eerdere jaren aangifte doen?','Ja, tot 5 jaar terug als je geen aangiftebrief kreeg (aangifte 2021 tot 31 december 2026).'),
('Wanneer weet ik de uitkomst?','Bij aangifte vóór 1 april meestal vóór 1 juli; daarna binnen ongeveer 3 maanden, soms langer.'),
('Hoe lang heb ik voor bezwaar?','6 weken na de datum van de aanslag. Een fout in je eigen aangifte verbeteren kan tot 5 jaar.'),
('Is de aangifte 2026 anders?','Die gaat over je inkomen van 2026 en doe je in 2027; tarieven en kortingen wijzigen, dus gebruik de officiële pagina voor dat jaar.')],
src_note='Belastingdienst-pagina’s geraadpleegd op 4 oktober 2026. De grenzen voor betalen/terugkrijgen worden op de officiële pagina’s met licht verschillende bedragen genoemd (€ 58; € 18–19); controleer ze in Mijn Belastingdienst.')
