from a_student_finance import T
SLUG='tenant-rights-netherlands'
V='https://www.volkshuisvestingnederland.nl/'
R='https://www.rijksoverheid.nl/'
SRC=[('Rijksoverheid · Maximale huurverhoging 2026',R+'onderwerpen/woning-huren/nieuws/2025/12/15/maximale-huurverhoging-2026-in-sociale-sector-41-middenhuur-61-en-vrije-sector-44'),
('Rijksoverheid · Maximale huurverhoging sociale huurwoning 2026',R+'vraag-en-antwoord/woning-huren/wat-is-de-maximale-huurverhoging-voor-een-sociale-huurwoning-in-2026'),
('Rijksoverheid · Bezwaar tegen huurverhoging',R+'onderwerpen/woning-huren/vraag-en-antwoord/hoe-maak-ik-bezwaar-tegen-de-huurverhoging-voor-mijn-sociale-huurwoning'),
('Volkshuisvesting Nederland · Waarborgsom',V+'onderwerpen/huren-en-wonen/huurbescherming-en-huurcontracten/waarborgsom'),
('Volkshuisvesting Nederland · Regels goed verhuurderschap',V+'onderwerpen/wet-goed-verhuurderschap/landelijke-regels-van-goed-verhuurderschap'),
('Volkshuisvesting Nederland · Huurcommissie',V+'onderwerpen/huren-en-wonen/huurbescherming-en-huurcontracten/huurcommissie'),
('Volkshuisvesting Nederland · Maximale huurprijsgrenzen 2026',V+'onderwerpen/huren-en-wonen/inkomensgrenzen-huurprijsgrenzen-en-huurtoeslagparameters/maximale-huurprijsgrenzen'),
('Rijksoverheid · Wet vaste huurcontracten',R+'actueel/nieuws/2024/06/07/wet-vaste-huurcontracten-vanaf-1-juli-2024-van-kracht'),
('Rijksoverheid · Kosten huurder of verhuurder',R+'onderwerpen/woning-huren/vraag-en-antwoord/welke-kosten-zijn-voor-de-huurder-en-welke-voor-de-verhuurder'),
('Rijksoverheid · Slecht onderhoud aanpakken',R+'vraag-en-antwoord/woning-huren/hoe-zorg-ik-ervoor-dat-de-verhuurder-slecht-onderhoud-aanpakt'),
('Juridisch Loket · Gebreken huurwoning','https://www.juridischloket.nl/wonen-en-buren/huurwoning/gebreken-huurwoning/'),
('Juridisch Loket · Huurachterstand en uitzetting','https://www.juridischloket.nl/schulden-en-incasso/incasso-en-betalingsachterstand/huurachterstand-uitzetting/'),
('Volkshuisvesting Nederland · Eerste Kamer: toekomstbestendige Huurcommissie (29-09-2026)',V+'actueel/nieuws/2026/09/29/eerste-kamer-stemt-in-met-wet-voor-toekomstbestendige-huurcommissie')]
AR=dict(title='حقوق المستأجر في هولندا 2026: زيادة الإيجار، التأمين (الكفالة)، الإصلاحات، لجنة الإيجار، والطرد — مع أمثلة',
crumb='حقوق المستأجر',
seo_title='حقوق المستأجر huurrechten 2026',
desc='حقوق المستأجر في هولندا 2026: أقصى زيادة إيجار 4.1% اجتماعي و6.1% متوسط و4.4% حر، الكفالة حدها شهران، ومن يصلّح ماذا ولجنة الإيجار.',
summary='<ol><li>أقصى زيادة: <strong>4.1%</strong> اجتماعي (من 1 يوليو 2026)، <strong>6.1%</strong> متوسط، <strong>4.4%</strong> حر — مرة واحدة في السنة.</li><li>الكفالة (waarborgsom) حدها <strong>شهران</strong> من الإيجار الصافي، وتُعاد خلال <strong>14 يوماً</strong> إن لم يكن هناك ضرر.</li><li>الإصلاحات الكبيرة على المالك، والصغيرة عليك.</li><li>لجنة الإيجار تحسم الخلاف برسم منخفض؛ ومن 1 يناير 2027 قانون جديد يوسّع صلاحياتها.</li><li>لا تحجب الإيجار بنفسك أبداً.</li></ol>',
body=(
'<h2 id="types">ثلاثة أنواع من الإيجار</h2>'
+T([['اجتماعي (gereguleerd)','حتى 143 نقطة، حتى 932.93 يورو','4.1% (من 1 يوليو 2026)'],['متوسط (middenhuur)','144–186 نقطة، حتى 1,228.07','6.1% في 2026'],['حر (vrije sector)','187 نقطة فأكثر','4.4% في 2026']],['النوع','الحدود 2026','أقصى زيادة'])
+'<p>المالك ملزم منذ 2025 بإعطائك <strong>حساب النقاط</strong> كتابياً، ونظام النقاط يطبق على العقود من 1 يوليو 2024 (Wet betaalbare huur). تبحث عن سكن اجتماعي؟ راجع <a href="/articles/social-housing-sociale-huurwoning.html">دليل السكن الاجتماعي</a>.</p>'
'<h2 id="increase">زيادة الإيجار في السكن الاجتماعي</h2><ul><li>الحد <strong>4.1%</strong>. إن كان إيجارك أقل من 350 يورو تُطبق مبالغ ثابتة بدل النسبة. وبعد الزيادة افحص <a href="/articles/housing-rent-allowance-2026.html">بدل الإيجار</a>.</li><li>يجب أن يصلك الإشعار قبل <strong>شهرين</strong> على الأقل.</li><li>للاعتراض: اكتب للمالك <strong>قبل</strong> بدء الزيادة. أسباب: فوق الحد، فوق أقصى إيجار لنقاط البيت، أخطاء، زيادة مبكرة، إشعار متأخر.</li><li>إن لم يتفقا: لجنة الإيجار. في القطاع المتوسط والحر: اطلب قرار اللجنة خلال <strong>4 أشهر</strong> من الإشعار إن كانت الزيادة فوق الحد.</li></ul>'
'<h2 id="examples">أمثلة محسوبة (توضيحية)</h2>'
+T([['هدى، إيجار اجتماعي 700 يورو','أقصى زيادة 4.1% = 28.70 ← <strong>728.70</strong> يورو'],['وليد، إيجار متوسط 1,100','أقصى 6.1% = 67.10 ← <strong>1,167.10</strong> (ولا يتجاوز 1,228.07 لنقاط البيت)'],['سامي، إيجار حر 1,500، طلب المالك 8%','الحد 4.4% = 66 ← <strong>1,566</strong>؛ الزيادة 120 مخالفة، اعترض'],['لينا، إيجار صافي 900، طلب المالك كفالة 2,700','الحد شهران = <strong>1,800</strong>؛ الزائد غير مسموح']],['الحالة','الحساب'])
+'<p>الأسماء والأرقام أمثلة توضيحية وليست أشخاصاً حقيقيين.</p>'
'<h2 id="deposit">الكفالة (waarborgsom)</h2><ul><li>حدها <strong>شهران</strong> من الإيجار الصافي (kale huur) منذ 1 يوليو 2023.</li><li>تُعاد خلال <strong>14 يوماً</strong> من نهاية العقد إن لا ضرر ولا ديون، أو خلال <strong>30 يوماً</strong> مع خصم مبرر.</li><li>لا خصم للاستهلاك العادي. إن لم تُعَد: طلب مكتوب، ثم المحكمة، واستشر Juridisch Loket.</li></ul>'
'<h2 id="landlord">واجبات المالك (Wet goed verhuurderschap)</h2><ul><li>عقد مكتوب ومعلومات مكتوبة عن حقوقك.</li><li>منع التمييز والترهيب.</li><li>تكاليف الخدمات (servicekosten) حسب التكلفة الفعلية مع كشف سنوي.</li><li>عمولة الوسيط لا تُدفع مرتين.</li><li>البلدية تراقب وتفرض غرامات.</li></ul>'
'<h2 id="contracts">العقود الدائمة</h2><p>منذ <strong>1 يوليو 2024</strong> العقد الدائم هو القاعدة (Wet vaste huurcontracten). العقود المؤقتة الموقعة قبل ذلك تبقى، لكن تمديدها يصبح لمدة غير محددة. استثناءات محدودة، مثل الطلاب والباحثين العاجلين (حتى سنتين).</p>'
'<h2 id="repairs">الإصلاحات</h2>'
+T([['المالك','الصيانة الكبيرة: دهان الخارج، استبدال التدفئة، المزاريب، الصراصير وآفات الخشب'],['المستأجر','الإصلاحات الصغيرة: دهان الداخل، الحنفيات، أغطية الأفياش، مقابض الأبواب، الزجاج المكسور، المصارف السهلة، النمل والبراغيث']],['على من','أمثلة'])
+'<ol><li>أبلغ كتابياً مع صور.</li><li>أعطِ مهلة معقولة (مثلاً 6 أسابيع، أسرع للطوارئ).</li><li>ثم: البلدية (Bouw- en Woningtoezicht)، أو لجنة الإيجار للإيجار الاجتماعي (قد تخفض الإيجار حتى الإصلاح)، أو المحكمة.</li><li><strong>استمر في دفع الإيجار كاملاً</strong>؛ الحجب بلا إذن قد يؤدي للطرد.</li></ol>'
'<h2 id="huurcommissie">لجنة الإيجار (Huurcommissie)</h2><ul><li>تفحص: زيادة/تخفيض الإيجار، العيوب، تكاليف الخدمات، والإيجار الابتدائي (خلال 6 أشهر من بدء العقد في السوق الخاصة).</li><li>الرسم على المستأجر (حسب نشرة اللجنة): سلفة <strong>25 يورو</strong>، تُعاد إن ربحت. تحقق من المبلغ الحالي في موقع اللجنة.</li><li><strong>من 1 يناير 2027</strong> (وافق مجلس الشيوخ في 29 سبتمبر 2026): المستأجر الاجتماعي يستطيع الطعن في الزيادات التعاقدية، ويجب الإبلاغ عن العيوب كتابياً قبل الإجراء.</li></ul>'
'<h2 id="arrears">التأخر في الدفع والطرد</h2><ul><li>المالك يذهب للمحكمة عادة عند تأخر <strong>3 أشهر</strong> أو أكثر، ويجب أن يبلّغ البلدية أولاً لتعرض المساعدة.</li><li>اطلب ترتيب دفع فوراً، واطلب <a href="/articles/debt-help-schuldhulp.html">مساعدة الديون</a> من البلدية.</li><li>إنهاء العقد من المالك يحتاج سبباً قانونياً ومهلة 3–6 أشهر، ولك حق الرفض ثم يقرر القاضي.</li><li>مساعدة قانونية مجانية: <strong>Juridisch Loket 0800-8020</strong>. بعض البلديات لديها «huurteam». وإن احتجت محامياً فراجع <a href="/articles/legal-aid-lawyer-toevoeging.html">المحامي بالـtoevoeging</a>.</li></ul>'),
faq=[('كم أقصى زيادة إيجار 2026؟','4.1% اجتماعي من 1 يوليو 2026، 6.1% متوسط، 4.4% حر.'),('كم الكفالة المسموحة؟','شهران من الإيجار الصافي كحد أقصى.'),('متى تُعاد الكفالة؟','خلال 14 يوماً، أو 30 يوماً مع خصم مبرر.'),('من يصلح السخان المعطل؟','الصيانة الكبيرة مثل التدفئة على المالك.'),('هل أوقف الدفع إن لم يُصلح المالك؟','لا؛ استمر بالدفع واذهب للبلدية أو لجنة الإيجار أو المحكمة.'),('هل العقود المؤقتة مسموحة؟','منذ 1 يوليو 2024 العقد الدائم هو القاعدة، مع استثناءات محدودة.')],
src_note='راجعنا Rijksoverheid وVolkshuisvesting Nederland وJuridisch Loket في 5 أكتوبر 2026. رسوم لجنة الإيجار من نشرتها الأخيرة المتاحة. الأمثلة توضيحية.')
NL=dict(title='Huurrechten in Nederland 2026: huurverhoging, waarborgsom, reparaties, Huurcommissie en ontruiming — met voorbeelden',
crumb='Huurrechten',
seo_title='Huurrechten 2026: huurverhoging en waarborgsom',
desc='Huurrechten 2026: maximale huurverhoging 4,1% sociaal, 6,1% midden en 4,4% vrij, waarborgsom max. 2 maanden, reparaties en de Huurcommissie.',
summary='<ol><li>Max. verhoging: <strong>4,1%</strong> sociaal (vanaf 1 juli 2026), <strong>6,1%</strong> midden, <strong>4,4%</strong> vrij — eens per jaar.</li><li>Waarborgsom max. <strong>2 maanden</strong> kale huur, terug binnen <strong>14 dagen</strong>.</li><li>Groot onderhoud verhuurder, kleine herstellingen huurder.</li><li>Huurcommissie tegen lage leges; per 1 januari 2027 nieuwe wet.</li><li>Nooit zelf huur inhouden.</li></ol>',
body=(
'<h2 id="types">Drie huursegmenten</h2>'
+T([['Sociaal','Tot 143 punten, tot € 932,93','4,1% (vanaf 1 juli 2026)'],['Middenhuur','144–186 punten, tot € 1.228,07','6,1% in 2026'],['Vrije sector','187+ punten','4,4% in 2026']],['Segment','Grenzen 2026','Max. verhoging'])
+'<p>De verhuurder moet sinds 2025 de puntentelling schriftelijk geven (Wet betaalbare huur, contracten vanaf 1 juli 2024). Een sociale huurwoning zoeken? Zie onze <a href="/nl/articles/social-housing-sociale-huurwoning.html">gids sociale huurwoning</a>.</p>'
'<h2 id="increase">Huurverhoging sociale huur</h2><ul><li>Max. <strong>4,1%</strong>; onder € 350 huur gelden vaste bedragen. Check daarna je <a href="/nl/articles/housing-rent-allowance-2026.html">huurtoeslag</a>.</li><li>Voorstel minimaal <strong>2 maanden</strong> vooraf.</li><li>Bezwaar schriftelijk vóór de ingangsdatum.</li><li>Midden/vrij: binnen <strong>4 maanden</strong> naar de Huurcommissie bij een te hoge verhoging.</li></ul>'
'<h2 id="examples">Rekenvoorbeelden (illustratief)</h2>'
+T([['Huda, sociale huur € 700','4,1% = € 28,70 → <strong>€ 728,70</strong>'],['Walid, middenhuur € 1.100','6,1% = € 67,10 → <strong>€ 1.167,10</strong> (max. puntenhuur)'],['Sami, vrije sector € 1.500, verhuurder vraagt 8%','Max. 4,4% → <strong>€ 1.566</strong>; bezwaar maken'],['Lina, kale huur € 900, borg gevraagd € 2.700','Max. 2 maanden = <strong>€ 1.800</strong>']],['Situatie','Berekening'])
+'<p>Illustratieve voorbeelden, geen echte personen.</p>'
'<h2 id="deposit">Waarborgsom</h2><ul><li>Max. <strong>2 maanden</strong> kale huur sinds 1 juli 2023.</li><li>Terug binnen <strong>14 dagen</strong>, of <strong>30 dagen</strong> bij verrekening.</li><li>Geen aftrek voor normale slijtage.</li></ul>'
'<h2 id="landlord">Goed verhuurderschap</h2><ul><li>Schriftelijk contract en informatie.</li><li>Verbod op discriminatie en intimidatie.</li><li>Servicekosten op basis van werkelijke kosten.</li><li>Bemiddelingskosten niet dubbel.</li><li>Handhaving door de gemeente.</li></ul>'
'<h2 id="contracts">Vaste huurcontracten</h2><p>Sinds <strong>1 juli 2024</strong> is vast de norm; uitzonderingen o.a. studenten en urgent woningzoekenden (max. 2 jaar).</p>'
'<h2 id="repairs">Reparaties</h2>'
+T([['Verhuurder','Groot onderhoud: buitenschilderwerk, cv vervangen, goten, kakkerlakken'],['Huurder','Kleine herstellingen: binnenschilderwerk, kraanleertjes, schakelaars, deurklinken, gebroken ruiten, mieren/vlooien']],['Wie','Voorbeelden'])
+'<ol><li>Meld schriftelijk met foto’s.</li><li>Redelijke termijn (bijv. 6 weken).</li><li>Daarna gemeente, Huurcommissie (sociaal, tijdelijke huurverlaging) of rechter.</li><li><strong>Blijf volledige huur betalen.</strong></li></ol>'
'<h2 id="huurcommissie">Huurcommissie</h2><ul><li>Huurverhoging/-verlaging, gebreken, servicekosten, aanvangshuur (binnen 6 maanden).</li><li>Leges huurder volgens legesnotitie: voorschot <strong>€ 25</strong>, terug bij gelijk. Check actuele bedragen.</li><li><strong>Per 1 januari 2027</strong> (Eerste Kamer 29 september 2026): sociale huurders kunnen contractuele verhogingen voorleggen; gebreken eerst schriftelijk melden.</li></ul>'
'<h2 id="arrears">Huurachterstand en ontruiming</h2><ul><li>Meestal bij <strong>3 maanden</strong> achterstand naar de rechter; verhuurder meldt eerst bij de gemeente.</li><li>Vraag een betalingsregeling en <a href="/nl/articles/debt-help-schuldhulp.html">schuldhulp</a>.</li><li>Opzegging door verhuurder: wettelijke grond, 3–6 maanden termijn.</li><li>Gratis hulp: <strong>Juridisch Loket 0800-8020</strong>; sommige gemeenten hebben een huurteam. Een advocaat nodig? Zie <a href="/nl/articles/legal-aid-lawyer-toevoeging.html">advocaat met toevoeging</a>.</li></ul>'),
faq=[('Max. huurverhoging 2026?','4,1% sociaal vanaf 1 juli 2026, 6,1% midden, 4,4% vrij.'),('Hoe hoog mag de borg zijn?','Max. 2 maanden kale huur.'),('Wanneer borg terug?','Binnen 14 dagen, of 30 dagen bij verrekening.'),('Wie repareert de cv?','Vervanging cv is groot onderhoud: verhuurder.'),('Mag ik huur inhouden?','Nee, zonder toestemming riskeer je ontruiming.'),('Zijn tijdelijke contracten toegestaan?','Sinds 1 juli 2024 is vast de norm, met beperkte uitzonderingen.')],
src_note='Gecontroleerd bij Rijksoverheid, Volkshuisvesting Nederland en Juridisch Loket op 5 oktober 2026. Leges volgens laatst beschikbare legesnotitie. Voorbeelden illustratief.')
