from a_student_finance import T
SLUG='asylum-two-status-system-2026'
I='https://ind.nl/nl/'
SRC=[('IND · Nieuwe wetten en regels asiel en nareis (bijgewerkt 31 juli 2026)',I+'asiel-en-nareis-het-migratiepact-en-andere-ontwikkelingen/nieuwe-wetten-en-regels-asiel-en-nareis'),
('IND · Gezinshereniging asiel (voorwaarden, procedure en kosten)',I+'verblijfsvergunningen/asiel/gezinshereniging-asiel'),
('IND · Wanneer begint de IND met mijn nareisaanvraag? (bijgewerkt 7 oktober 2026)',I+'asiel-en-nareis-het-migratiepact-en-andere-ontwikkelingen/wanneer-begint-de-ind-met-mijn-nareisaanvraag'),
('IND · Asiel aangevraagd voor 12 juni 2026',I+'asiel-en-nareis-het-migratiepact-en-andere-ontwikkelingen/asiel-aangevraagd-voor-12-juni-2026'),
('Rijksoverheid · Verminderen instroom asielzoekers (maatregelen per 12 juni 2026)','https://www.rijksoverheid.nl/themas/migratie-en-reizen/asielbeleid/verminderen-instroom-asielzoekers'),
('Staatsblad 2026, 105 · Wet invoering tweestatusstelsel (wet van 22 april 2026)','https://zoek.officielebekendmakingen.nl/stb-2026-105.html'),
('Eerste Kamer · Wetsvoorstel 36 703 Wet invoering tweestatusstelsel','https://www.eerstekamer.nl/wetsvoorstel/36703_wet_invoering')]
AR=dict(title='نظام الحالتين للجوء في هولندا 2026: ما الذي تغيّر منذ 12 يونيو لحاملي الإقامة الحاليين والجدد، وأثره على لمّ الشمل',
crumb='نظام الحالتين للجوء 2026',
desc='دليل لما يغيّره نظام الحالتين (لاجئ / حماية ثانوية) منذ 12 يونيو 2026: إقامة اللجوء لمدة 3 سنوات وإلغاء الإقامة غير المحددة، من يُعدّ من الحاملين الحاليين، شروط لمّ الشمل (nareis) لكل حالة، الأقارب المشمولون، الطلبات التي يوقف IND البت فيها مؤقتاً، ومدد الانتظار المعلنة، مع أمثلة توضيحية وأسئلة شائعة.',
summary='<ol><li><strong>منذ 12 يونيو 2026</strong> يميّز القانون بين <strong>لاجئ</strong> (اضطهاد شخصي) و<strong>حماية ثانوية</strong> (فرار من الحرب والعنف مثلاً). المصدر: IND وRijksoverheid.</li><li>إقامة اللجوء الجديدة <strong>مؤقتة لمدة 3 سنوات</strong>، ولا تُمنح <strong>إقامة لجوء غير محددة المدة</strong> بعد الآن. من كان يحملها قبل 12 يونيو <strong>يحتفظ بها</strong>.</li><li><strong>لمّ الشمل (nareis)</strong> يقتصر على الزوج/الزوجة المتزوج قانونياً والأطفال البيولوجيين أو بالتبني تحت 18، ولدى القاصر غير المصحوب: الوالدان وإخوته القاصرون.</li><li><strong>الحماية الثانوية</strong> لها 3 شروط إضافية: <strong>انتظار سنتين</strong>، <strong>دخل ذاتي ومستدام</strong>، و<strong>سكن</strong>. اللاجئ لا تنطبق عليه.</li><li>IND <strong>أوقف مؤقتاً</strong> البت في فئات من طلبات nareis بانتظار حكم المحكمة حول التطبيق على الطلبات القائمة. لا موعد معروف للحكم.</li></ol>',
body=(
'<h2 id="what">ما هو نظام الحالتين؟</h2><p>حسب IND، يمكن الحصول على إقامة اللجوء لسببين: <strong>لاجئ</strong> بموجب اتفاقية اللاجئين (خطر اضطهاد شخصي بسبب الأصل أو الدين أو الرأي السياسي مثلاً)، أو <strong>حماية ثانوية</strong> (الفرار لسبب آخر، مثل الحرب). هذه هي «حالتك» (status). القانون المسمّى <strong>Wet invoering tweestatusstelsel</strong> (قانون 22 أبريل 2026، Staatsblad 2026, 105) جعل الفرق بين الحالتين يؤثر في الحقوق، وبخاصة لمّ الشمل. بدأ العمل به في <strong>12 يونيو 2026</strong> ولم يتضمن نظاماً انتقالياً حسب ملخص Staatsblad الذي راجعناه.</p>'
'<p>وتشير Rijksoverheid إلى أن هذه الإجراءات جاءت مع <strong>الميثاق الأوروبي للهجرة واللجوء</strong> الذي بدأ في اليوم نفسه. وينص القانون على تقييمه خلال <strong>3 سنوات</strong> من بدء العمل به.</p>'
'<h2 id="check">كيف أعرف حالتي أنا؟</h2>'
+T([['قرار IND <strong>قبل 12 يونيو 2026</strong>','في أول صفحة من القرار: المادة 29 الفقرة 1 البند <strong>a</strong> = لاجئ؛ البند <strong>b</strong> = حماية ثانوية. يمكن رؤية القرار في «Mijn IND» لنحو شهر بعد منح الإقامة. إن لم تعد تراه فاتصل بخط nareis لدى IND.'],['قرار IND <strong>بعد 12 يونيو 2026</strong>','على <strong>ظهر البطاقة</strong> (pasje) مكتوب «vluchteling» أو «subsidiair beschermde».']],['متى صدر القرار؟','أين تجد الحالة'])
+'<h2 id="holders">ماذا تغيّر لحاملي الإقامة الحاليين؟</h2><p>هذا ما أكدته صفحات IND، ولم نجد فيها ما يلغي إقامة أحد:</p>'
+T([['إقامة لجوء غير محددة المدة (onbepaalde tijd)','لا يمكن طلبها منذ 12 يونيو. <strong>من كان يحملها في 12 يونيو يحتفظ بها.</strong>'],['بطاقة الإقامة الجديدة أو المجدَّدة','<strong>صالحة 3 سنوات</strong>. تاريخ البدء على البطاقة الجديدة هو <strong>12 يونيو 2026</strong>، وليس تاريخ أول إقامة لك. تحتفظ <strong>بالحقوق والواجبات نفسها</strong> حسب IND.'],['بطاقة تنتهي قريباً','اطلب تجديد «verblijfsdocument asiel» لدى IND في الوقت المناسب.'],['5 سنوات من الإقامة بعد منح إقامة اللجوء','قد تستحق إقامة <strong>مقيم طويل الأمد في الاتحاد الأوروبي</strong> (EU-langdurig ingezetene). انظر <a href="/articles/eu-permanent-residence-netherlands.html">الإقامة الدائمة ووضع المقيم طويل الأمد</a>.'],['لمّ الشمل لأسرتك','تغيّرت الشروط ولا تنطبق على الجدد فقط: حسب IND تسري أيضاً على من قدّم طلباً ولم يصله قرار بعد. التفاصيل أدناه.']],['الموضوع','ما تقوله IND'])
+'<p>ما لم نتحقق منه: أثر تغيير الحالة على الإقامة الدائمة أو الجنسية أو برنامج الاندماج لمن حصل على إقامته قبل 12 يونيو. لم نجد شرحاً رسمياً يكفي لإعطاء حكم، فاسأل VluchtelingenWerk أو IND قبل أي قرار.</p>'
'<h2 id="new">ماذا يتغير لمن يطلب اللجوء الآن؟</h2><ul><li>الإجراء الجديد: عادةً تعرف خلال <strong>6 أشهر</strong> إن كان بإمكانك البقاء، و<strong>3 أشهر</strong> في الإجراء المعجَّل (مثلاً القادم من بلد آمن).</li><li>إقامة اللجوء <strong>3 سنوات</strong>، مع بطاقة تذكر ظهرها حالتك.</li><li><strong>طلبات اللجوء قبل 12 يونيو 2026:</strong> إجراؤها مختلف. يقول IND إن المدة لن تكون 6 أشهر، وأمامه <strong>3 سنوات</strong> للبت في كل الطلبات السابقة. من لم يُجرِ المقابلة الأولى يُدعى إليها خلال 2026. وإن أُجريت المقابلة الثانية قبل 1 أكتوبر 2026 فيأمل IND قراراً قبل <strong>أبريل 2027</strong> (أمل لا التزام).</li><li><strong>تقديم طلب جديد لا يُقصّر الانتظار</strong>: تاريخ طلبك الأول هو المعتمد.</li><li>أثناء الإجراء يجب التسجيل <strong>مرة أسبوعياً</strong> لدى COA في مكان الاستقبال (meldplicht).</li><li>المحامي في الإجراء تنظمه Raad voor Rechtsbijstand وهو عادةً مجاني.</li></ul>'
'<h2 id="nareis">لمّ الشمل (nareis) بعد 12 يونيو 2026</h2>'
+T([['الأقارب المشمولون','الزوج/الزوجة <strong>المتزوج قانونياً</strong>؛ الأطفال البيولوجيون أو بالتبني <strong>تحت 18</strong>. الوالدان وإخوة تحت 18 <strong>فقط</strong> إن كنت قاصراً بلا والدين حين طلبت اللجوء (والإخوة يُقدَّم طلبهم مع الوالد).'],['خارج القائمة','الأطفال البالغون، الأبناء بالرعاية (pleegkind)، الشريك غير المتزوج: لا nareis. يمكن طلب الإقامة بموجب <strong>المادة 8 من الاتفاقية الأوروبية لحقوق الإنسان</strong> (تقدير كل حالة، لا حق عام).'],['شرط الأسرة','أن يكون القريب جزءاً من أسرتك <strong>قبل دخولك هولندا</strong>.'],['لاجئ','مهلة <strong>3 أشهر</strong> من قرار منح الإقامة. لا انتظار ولا شرط دخل أو سكن إضافي.'],['حماية ثانوية','<strong>انتظار سنتين</strong> من تاريخ قرار الإقامة حتى قرار IND، و<strong>دخل ذاتي ومستدام</strong>، و<strong>سكن خاص</strong>. إن لم تمضِ سنتان وقت القرار فقد يكون سلبياً.'],['قاصر غير مصحوب بحماية ثانوية','ينطبق <strong>شرط السنتين فقط</strong> (لا دخل ولا سكن).']],['البند','القاعدة (IND، Staatsblad)'])
+'<p>في نص القانون: السكن يشمل الإقامة في «موقع انتقالي» (doorstroomlocatie)، والدخل يُقاس حسب التفاصيل التي تضعها لائحة تنفيذية بالتوافق مع قواعد اللمّ العادي (وتشير مذكرة القانون إلى مبلغ بمستوى الحد الأدنى للأجر). تحقق من المبلغ الحالي لدى IND ولا تعتمد على رقم قديم.</p>'
'<p><strong>ملاحظة عن المهلة:</strong> صفحة IND تذكر مهلة الأشهر الثلاثة <strong>لمن له صفة لاجئ</strong>. لم تذكر الصفحة مهلة مماثلة للحماية الثانوية، فلا تفترض أنها غير موجودة: اسأل خط nareis أو VluchtelingenWerk في حالتك.</p>'
'<h2 id="pause">الطلبات التي يوقف IND البت فيها مؤقتاً</h2><p>يقول IND إن الشروط الجديدة تسري <strong>أيضاً على الطلبات القائمة</strong> التي لم يُبتّ فيها. ويريد IND وجهات لجوء أخرى أن تتحقق المحكمة من أن التطبيق <strong>بأثر رجعي</strong> مقبول قانوناً. لذلك:</p>'
+T([['حماية ثانوية (أغلب الحالات)','متوقف مؤقتاً'],['لاجئ لا يحق لأقاربه nareis وفق الشروط الجديدة (مثلاً أقارب خارج القائمة)','متوقف مؤقتاً'],['لاجئ، لزوجه المتزوج وأطفاله القاصرين','IND <strong>يواصل</strong> البت'],['حماية ثانوية، كنت قاصراً بلا والدين، مضت أكثر من سنتين، والطلب لوالديك وإخوتك دون 18 حين دخلت','IND <strong>يواصل</strong>'],['طلب بموجب المادة 8 من الاتفاقية الأوروبية (أقارب آخرون)','IND <strong>يواصل</strong>']],['الحالة','موقف IND'])
+'<p>يتوقف IND عن البت ريثما تصدر المحكمة حكمها، و<strong>لا يُعرف موعد الحكم</strong>. إن لم يتضح الأمر قبل نهاية 2026، يحدد IND الخطوة التالية. تحقق من صفحة IND، وستصلك رسالة منه إن كنت من مجموعة صغيرة يبت فيها (رسالة في يونيو أو يوليو أو أغسطس).</p>'
'<h2 id="wait">متى يبدأ IND بالنظر في طلبي؟</h2><p>بعد إيصال الاستلام يمرّ <strong>عدة أشهر</strong> قبل أن يبدأ IND بالنظر في الطلب، لكثرة الطلبات. ثم لديه <strong>9 أشهر</strong> للبت (تُمدَّد عند الحاجة). يقسّم IND الطلبات إلى مجموعتين. هذه أمثلة من جداول IND (متوسطات متوقعة تتغير، وتُعدَّل الصفحة بانتظام):</p>'
+T([['لاجئ، طلب للزوج المتزوج مع أطفاله البيولوجيين تحت 18 فقط','طلب في أكتوبر–نوفمبر 2025 ← أكتوبر 2026؛ مارس–يونيو 2026 ← ديسمبر 2026؛ سبتمبر 2026 ← مارس 2027'],['حالات أخرى (تحتاج فحصاً أطول للصلة العائلية)','طلب في أغسطس 2024 ← أكتوبر 2026؛ يونيو–أغسطس 2025 ← مارس 2027؛ يوليو–سبتمبر 2026 ← يوليو 2027']],['المجموعة (حسب IND)','أمثلة: شهر الطلب ← شهر بدء IND المتوقع'])
+'<p>من قدّم قبل الشهر المذكور في الجدول ولم تصله رسالة، فغالباً ينتمي إلى الفئة <strong>الموقوفة مؤقتاً</strong> أعلاه. الطلب الكامل (وثائق الهوية والصلة العائلية) أسرع، وقد يطلب IND فحص DNA أو مقابلة عند نقص الوثائق. الحالات الاستعجالية الاستثنائية (مثل مرض خطير لدى القريب) تُعالج أبكر بشكل استثنائي.</p>'
'<h2 id="steps">الخطوات والتكاليف</h2><ol><li><strong>تحقق من الشروط</strong> (الأقارب، الصلة قبل دخولك، حالتك).</li><li><strong>اجمع الوثائق</strong> قبل التقديم: يجب أن تكون في هولندا لأن IND يفحص أحياناً أصولها. ترجمة الوثائق الأجنبية إلى الهولندية أو الإنجليزية أو الفرنسية أو الألمانية بمترجم محلّف أمام محكمة هولندية. انظر <a href="/articles/syrian-documents-legalisation-translation.html">تصديق الوثائق السورية وترجمتها</a>.</li><li><strong>قدّم الطلب</strong> إلكترونياً أو بالبريد، وتطلب الـMVV والإقامة معاً. يوصي IND بأن تقدمه أنت لا القريب.</li><li><strong>الرسوم:</strong> إن كنتَ بالغاً حين طلبت اللجوء وطلبت لزوجك المتزوج أو لطفلك البيولوجي أو بالتبني فالطلب <strong>مجاني</strong>. لغيرهم <strong>254 يورو</strong>. القاصر غير المصحوب الذي يطلب لوالديه وإخوته: مجاني.</li><li><strong>القرار</strong>: إن كان إيجابياً يحصل القريب على MVV من السفارة (موعد خلال <strong>3 أشهر</strong> من القرار، تُمدَّد إلى 6)، وجواز يصلح 6 أشهر على الأقل، ثم يسجل خلال <strong>90 يوماً</strong> في هولندا.</li><li>قرار سلبي: يمكن <strong>الاعتراض (bezwaar)</strong>. انظر <a href="/articles/bezwaar-objection-letter.html">الاعتراض على قرار حكومي</a>.</li></ol>'
'<h2 id="regular">وإن لم تنطبق شروط nareis؟</h2><p>يبقى مسار لمّ الشمل العادي بشروطه (دخل، سكن، رسوم، وأحياناً امتحان اندماج في الخارج)، وهو مختلف. اقرأ <a href="/articles/family-reunification-mvv-ind.html">لمّ الشمل وMVV لدى IND</a> و<a href="/articles/asylum-family-reunification.html">لمّ شمل عائلة اللاجئ (Nareis)</a>. هل يستفيد أحد من مسار عادي بعد فوات المهلة؟ يتوقف ذلك على حالتك، فاستشر جهة مختصة.</p>'
'<h2 id="examples">أمثلة توضيحية (أمثلة توضيحية وليست حالات أشخاص حقيقيين)</h2>'
+T([['صاحب إقامة بصفة <strong>لاجئ</strong> ويريد لمّ شمل زوجته المتزوجة وطفلين تحت 18','يحق لهم nareis بلا انتظار ولا شرط دخل أو سكن إضافي، بشرط الطلب خلال 3 أشهر من قرار الإقامة. الطلب مجاني. IND يواصل البت في هذه الفئة.'],['صاحب <strong>حماية ثانوية</strong> قرار إقامته بتاريخ 15 أكتوبر 2026 ويطلب لزوجته','سنتان من 15 أكتوبر 2026 تعني 15 أكتوبر 2028 كأبكر تاريخ، مع دخل ذاتي ومستدام وسكن. قبل ذلك قد يكون القرار سلبياً.'],['شاب بحماية ثانوية كان <strong>قاصراً بلا والدين</strong> عند طلب اللجوء ويطلب لأمه وأبيه وأخت عمرها 12 عند دخوله','يخضع لشرط السنتين فقط، ولا يُشترط دخل أو سكن. الأخت تُطلب مع الوالد.'],['صاحب إقامة يريد لمّ شمل ابنه عمره 20 سنة','لا يدخل ضمن nareis. يمكن طلب الإقامة بموجب المادة 8 من الاتفاقية الأوروبية، ويقدّر IND كل حالة.'],['صاحب بطاقة إقامة لجوء <strong>غير محددة</strong> صادرة قبل 12 يونيو 2026','يحتفظ بها حسب IND.']],['الحالة (افتراضية)','النتيجة حسب القواعد أعلاه'])
+'<p>هذه أمثلة توضيحية وليست حالات أشخاص حقيقيين. التواريخ والأسماء افتراضية لتوضيح الحساب فقط.</p>'
'<h2 id="mistakes">أخطاء شائعة</h2><ol><li><strong>الاعتماد على أخبار قديمة</strong>: ما كان مقترحاً قبل إقرار القانون ليس كله نافذاً. راجع IND وStaatsblad.</li><li><strong>عدم معرفة حالتك</strong>: اطلع على قرارك أو ظهر بطاقتك قبل أي طلب.</li><li><strong>تفويت مهلة الأشهر الثلاثة</strong> للاجئ بانتظار اكتمال الوثائق: قدّم ثم أكمل ما يطلبه IND.</li><li><strong>سحب طلب اللجوء السابق لتقديم جديد</strong>: لن يُقصّر الانتظار.</li><li><strong>تفويت رسالة IND</strong> أو عدم تحديث العنوان.</li><li><strong>دفع مبالغ لوسطاء</strong> يعدون بتسريع القرار. طلبات nareis لا تُسرَّع بالمال. انظر <a href="/articles/scams-phishing-netherlands.html">الاحتيال في هولندا</a>.</li></ol>'
'<h2 id="help">أين أجد مساعدة بشرية؟</h2><p>الوضع القانوني يتغير بسرعة وقد يخص حالتك وحدها. الجهات المجانية موضحة في <a href="/articles/asylum-residence-hub.html">مركز أدلة اللجوء والإقامة</a>: VluchtelingenWerk وJuridisch Loket والمستشارون الاجتماعيون (sociaal raadslieden) والمحقق الوطني (Nationale ombudsman).</p>'
'<h2 id="related">أدلة مرتبطة</h2><ul><li><a href="/articles/asylum-family-reunification.html">لمّ شمل عائلة اللاجئ (Nareis)</a></li><li><a href="/articles/family-reunification-mvv-ind.html">لمّ الشمل مع الشريك: MVV والإقامة العادية</a></li><li><a href="/articles/eu-permanent-residence-netherlands.html">الإقامة الدائمة ووضع المقيم طويل الأمد</a></li><li><a href="/articles/inburgering-integration-law-2026.html">الاندماج (Inburgering) 2026</a></li><li><a href="/articles/bsn-municipality-registration.html">التسجيل في البلدية وBSN</a></li><li><a href="/articles/asylum-residence-hub.html">مركز أدلة اللجوء والإقامة</a></li></ul>'),
faq=[('ما الفرق بين اللاجئ وصاحب الحماية الثانوية؟','اللاجئ معرّض لاضطهاد شخصي (أصل، دين، رأي سياسي…) بموجب اتفاقية اللاجئين. صاحب الحماية الثانوية فرّ لسبب آخر مثل الحرب. منذ 12 يونيو 2026 تختلف شروط لمّ الشمل بينهما.'),
('هل ألغيت إقامتي غير المحددة المدة؟','لا. حسب IND من كان يحمل إقامة لجوء غير محددة المدة في 12 يونيو 2026 يحتفظ بها. لكن لا يمكن طلبها بعد هذا التاريخ.'),
('كم مدة إقامة اللجوء الجديدة؟','3 سنوات، وكذلك بطاقة الإقامة الجديدة. تاريخ البدء المكتوب عليها 12 يونيو 2026 لمن جدّد بعد هذا التاريخ.'),
('أين أرى حالتي (لاجئ أم حماية ثانوية)؟','في أول صفحة من قرار IND (المادة 29، 1، a لاجئ، b حماية ثانوية)، أو على ظهر البطاقة للقرارات بعد 12 يونيو 2026.'),
('من يمكن أن يأتي عبر nareis الآن؟','الزوج/الزوجة المتزوج قانونياً، والأطفال البيولوجيون أو بالتبني تحت 18. وللقاصر غير المصحوب: والداه وإخوته تحت 18 (يُقدَّم طلب الإخوة مع الوالد). الأقارب الآخرون عبر المادة 8 من الاتفاقية الأوروبية.'),
('ما شروط الحماية الثانوية للمّ الشمل؟','انتظار سنتين من قرار الإقامة، ودخل ذاتي ومستدام، وسكن. القاصر غير المصحوب يخضع لشرط السنتين فقط.'),
('لماذا لم يبتّ IND في طلبي؟','قد تكون من الفئات التي أوقف IND البت فيها مؤقتاً بانتظار حكم المحكمة حول تطبيق الشروط الجديدة بأثر رجعي. لا موعد معروفاً للحكم؛ راجع صفحة IND أو اتصل بخط nareis.'),
('هل لمّ الشمل مجاني؟','للبالغ الذي يطلب لزوجه المتزوج أو لأطفاله البيولوجيين أو بالتبني: مجاني حسب IND. لغيرهم 254 يورو. تحقق من صفحة الرسوم قبل الدفع.'),
('هل سحب طلب اللجوء القديم وتقديم جديد يسرّع القرار؟','لا. يقول IND إن تاريخ الطلب السابق هو الذي يحدد دورك.'),
('أين أجد مساعدة مجانية؟','VluchtelingenWerk Nederland وJuridisch Loket والمستشارون الاجتماعيون في بلديتك. الروابط في مركز أدلة اللجوء والإقامة.')],
src_note='راجعنا IND وRijksoverheid وStaatsblad 2026, 105 في 8 أكتوبر 2026؛ صفحات IND عن مدد الانتظار حُدّثت في 7 أكتوبر 2026 وتتغير باستمرار. لم نتحقق من أثر القانون على الإقامة الدائمة أو الجنسية أو الاندماج لمن حصل على إقامته قبل 12 يونيو، ولا من مهلة nareis للحماية الثانوية، ولا من مبلغ الدخل الحالي المطلوب. الأمثلة توضيحية وليست حالات أشخاص حقيقيين.')
NL=dict(title='Tweestatusstelsel asiel 2026: wat verandert er sinds 12 juni voor huidige en nieuwe statushouders en voor nareis',
crumb='Tweestatusstelsel asiel 2026',
desc='Gids over wat het tweestatusstelsel (vluchteling / subsidiair beschermde) sinds 12 juni 2026 verandert: verblijfsvergunning asiel van 3 jaar, geen vergunning voor onbepaalde tijd meer, wat er geldt voor huidige statushouders, nareisvoorwaarden per status, welke gezinsleden meetellen, welke aanvragen de IND tijdelijk niet beslist en de verwachte wachttijden, met illustratieve voorbeelden en FAQ.',
summary='<ol><li><strong>Sinds 12 juni 2026</strong> maakt de wet onderscheid tussen <strong>vluchteling</strong> (persoonlijke vervolging) en <strong>subsidiair beschermde</strong> (bijvoorbeeld gevlucht voor oorlog en geweld). Bron: IND en Rijksoverheid.</li><li>Een nieuwe verblijfsvergunning asiel is <strong>tijdelijk, 3 jaar</strong>. Een <strong>verblijfsvergunning asiel voor onbepaalde tijd</strong> kan niet meer worden aangevraagd. Wie die op 12 juni al had, <strong>houdt</strong> haar.</li><li><strong>Nareis</strong> geldt alleen nog voor de wettelijk gehuwde partner en biologische of geadopteerde kinderen jonger dan 18; bij een alleenstaande minderjarige ook ouders en minderjarige broers/zussen.</li><li><strong>Subsidiair beschermden</strong> hebben 3 extra voorwaarden: <strong>2 jaar wachttijd</strong>, <strong>zelfstandig en duurzaam inkomen</strong> en <strong>huisvesting</strong>. Vluchtelingen niet.</li><li>De IND <strong>beslist tijdelijk niet</strong> op bepaalde nareisaanvragen, in afwachting van een rechterlijke uitspraak over toepassing op lopende aanvragen. Het is niet bekend wanneer die komt.</li></ol>',
body=(
'<h2 id="what">Wat is het tweestatusstelsel?</h2><p>Volgens de IND kunt u een verblijfsvergunning asiel om twee redenen krijgen: als <strong>vluchteling</strong> volgens het Vluchtelingenverdrag (persoonlijk risico op vervolging, bijvoorbeeld door afkomst, geloof of politieke voorkeur) of met <strong>subsidiaire bescherming</strong> (u bent om een andere reden gevlucht, bijvoorbeeld door oorlog). Dat is uw <strong>status</strong>. De <strong>Wet invoering tweestatusstelsel</strong> (wet van 22 april 2026, Staatsblad 2026, 105) laat dat verschil nu meetellen voor uw rechten, vooral bij nareis. De wet is ingegaan op <strong>12 juni 2026</strong>; volgens de samenvatting van het Staatsblad die wij raadpleegden is er geen overgangsrecht.</p>'
'<p>Rijksoverheid benoemt de maatregelen als onderdeel van het <strong>Europese Asiel- en Migratiepact</strong>, dat op dezelfde dag inging. In de wet is een evaluatie binnen <strong>3 jaar</strong> na inwerkingtreding opgenomen.</p>'
'<h2 id="check">Welke status heb ik?</h2>'
+T([['IND-besluit <strong>vóór 12 juni 2026</strong>','Eerste pagina van het besluit: artikel 29, eerste lid, aanhef en onder <strong>a</strong> = vluchteling; onder <strong>b</strong> = subsidiaire bescherming. In Mijn IND is het besluit ongeveer een maand zichtbaar. Niet meer zichtbaar? Bel de nareislijn van de IND.'],['IND-besluit <strong>na 12 juni 2026</strong>','Op de <strong>achterkant van het pasje</strong> staat ‘vluchteling’ of ‘subsidiair beschermde’.']],['Wanneer was het besluit?','Waar ziet u de status'])
+'<h2 id="holders">Wat verandert er voor huidige statushouders?</h2><p>Dit staat op de IND-pagina’s; we vonden daar niets waarmee bestaande vergunningen worden ingetrokken.</p>'
+T([['Verblijfsvergunning asiel voor onbepaalde tijd','Vanaf 12 juni niet meer aan te vragen. <strong>Had u die op 12 juni al? Dan houdt u haar.</strong>'],['Nieuw of vernieuwd pasje','<strong>3 jaar geldig</strong>. Als ingangsdatum staat <strong>12 juni 2026</strong>, niet de datum waarop u voor het eerst een vergunning kreeg. U houdt <strong>dezelfde rechten en plichten</strong>, volgens de IND.'],['Pasje bijna verlopen','Vraag tijdig vernieuwing van het verblijfsdocument asiel aan bij de IND.'],['5 jaar in Nederland gewoond na de asielvergunning','Mogelijk recht op een <strong>verblijfsvergunning EU-langdurig ingezetene</strong>. Zie <a href="/nl/articles/eu-permanent-residence-netherlands.html">Permanent verblijf en EU-langdurig ingezetene</a>.'],['Nareis voor uw gezin','Voorwaarden zijn veranderd en gelden niet alleen voor nieuwe aanvragen: volgens de IND ook voor wie al nareis aanvroeg en nog geen besluit kreeg. Zie hieronder.']],['Onderwerp','Wat de IND zegt'])
+'<p>Wat wij niet hebben kunnen vaststellen: wat de statusverandering betekent voor permanent verblijf, naturalisatie of inburgering van wie vóór 12 juni een vergunning kreeg. Er was geen officiële uitleg die een stellig antwoord toelaat. Vraag het VluchtelingenWerk of de IND voordat u iets besluit.</p>'
'<h2 id="new">Wat verandert er voor nieuwe asielaanvragers?</h2><ul><li>Nieuwe procedure: standaard hoort u <strong>binnen 6 maanden</strong> of u mag blijven; in de versnelde procedure (bijvoorbeeld uit een veilig land) <strong>3 maanden</strong>.</li><li>De verblijfsvergunning asiel is <strong>3 jaar</strong> geldig; op het pasje staat uw status.</li><li><strong>Asiel aangevraagd vóór 12 juni 2026:</strong> andere procedure. De IND beslist niet binnen 6 maanden en heeft <strong>3 jaar</strong> de tijd voor alle oude aanvragen. Nog geen eerste gehoor? Dan volgt een uitnodiging nog in 2026. Tweede gehoor vóór 1 oktober 2026? Dan hoopt de IND vóór <strong>april 2027</strong> te beslissen (een verwachting, geen garantie).</li><li><strong>Een nieuwe aanvraag verkort de wachttijd niet</strong>: de datum van uw eerdere aanvraag bepaalt uw beurt.</li><li>Tijdens de procedure geldt een <strong>wekelijkse meldplicht</strong> bij het COA op uw opvanglocatie.</li><li>Een advocaat via de Raad voor Rechtsbijstand is meestal gratis.</li></ul>'
'<h2 id="nareis">Nareis na 12 juni 2026</h2>'
+T([['Welke gezinsleden','Wettelijk <strong>gehuwde partner</strong>; biologische of geadopteerde kinderen <strong>jonger dan 18</strong>. Ouders en minderjarige broers/zussen <strong>alleen</strong> als u als alleenstaande minderjarige asiel aanvroeg (broers/zussen samen met een ouder).'],['Niet meer via nareis','Meerderjarige kinderen, pleegkinderen, ongehuwde partners. Verblijf kan nog via <strong>artikel 8 EVRM</strong> (individuele afweging, geen algemeen recht).'],['Gezinsband','Het gezinslid hoorde al bij uw gezin <strong>voordat u Nederland binnenkwam</strong>.'],['Vluchteling','Aanvragen binnen <strong>3 maanden</strong> na de asielvergunning. Geen wachttijd, geen extra inkomens- of huisvestingseis.'],['Subsidiair beschermd','<strong>2 jaar wachttijd</strong> vanaf de beslissing over de vergunning tot het besluit van de IND; <strong>zelfstandig en duurzaam inkomen</strong>; <strong>eigen huis</strong>. Is bij het besluit nog geen 2 jaar verstreken, dan kan het besluit negatief zijn.'],['Alleenstaande minderjarige met subsidiaire bescherming','Alleen de <strong>wachttijd van 2 jaar</strong> (geen inkomens- of huisvestingseis).']],['Onderdeel','Regel (IND, Staatsblad)'])
+'<p>In de wettekst valt een verblijf op een doorstroomlocatie ook onder huisvesting. Het inkomen wordt nader bij algemene maatregel van bestuur ingevuld; de toelichting verwijst naar de regels voor regulier verblijf (een bedrag ten hoogte van het minimumloon). Controleer het actuele bedrag bij de IND en ga niet af op een oud cijfer.</p>'
'<p><strong>Let op de termijn:</strong> de IND-pagina noemt de nareistermijn van 3 maanden bij de status <strong>vluchteling</strong>. Voor subsidiair beschermden staat daar geen vergelijkbare termijn. Neem dus niet aan dat er geen termijn is: vraag het de nareislijn of VluchtelingenWerk voor uw situatie.</p>'
'<h2 id="pause">Aanvragen waarop de IND tijdelijk niet beslist</h2><p>De IND zegt dat de nieuwe voorwaarden ook gelden voor <strong>lopende aanvragen</strong>. De IND en andere asielorganisaties willen laten toetsen of toepassing met <strong>terugwerkende kracht</strong> juridisch houdbaar is. Daarom:</p>'
+T([['Subsidiaire bescherming (de meeste gevallen)','Tijdelijk <strong>geen besluit</strong>'],['Vluchteling, maar gezinsleden hebben volgens de nieuwe voorwaarden geen recht op nareis','Tijdelijk <strong>geen besluit</strong>'],['Vluchteling, voor gehuwde partner en kinderen jonger dan 18','IND <strong>beslist wel</strong>'],['Subsidiair beschermd, als alleenstaande minderjarige gevlucht, meer dan 2 jaar geleden vergunning, aanvraag voor ouders en broers/zussen jonger dan 18 bij binnenkomst','IND <strong>beslist wel</strong>'],['Aanvraag op grond van artikel 8 EVRM (andere familieleden)','IND <strong>beslist wel</strong>']],['Situatie','Standpunt IND'])
+'<p>De IND beslist niet voordat de rechtbank uitspraak heeft gedaan; <strong>het is niet bekend wanneer dat is</strong>. Is er voor eind 2026 geen duidelijkheid, dan bepaalt de IND wat de vervolgstappen zijn. Een klein aantal aanvragen is wel beslist; wie daarbij hoort, kreeg in juni, juli of augustus een brief.</p>'
'<h2 id="wait">Wanneer begint de IND met mijn aanvraag?</h2><p>Na de ontvangstbevestiging duurt het <strong>enkele maanden</strong> voordat de IND begint, omdat er veel aanvragen zijn. Daarna heeft de IND <strong>9 maanden</strong> om te beslissen (te verlengen). De IND deelt aanvragen in twee groepen in. Voorbeelden uit de tabellen van de IND (gemiddelden en verwachtingen die veranderen):</p>'
+T([['Vluchteling; alleen gehuwde partner met biologische kinderen jonger dan 18','Aanvraag okt–nov 2025 → okt 2026; mrt–jun 2026 → dec 2026; sep 2026 → mrt 2027'],['Andere aanvragen (meer onderzoek naar de gezinsband)','Aanvraag aug 2024 → okt 2026; jun–aug 2025 → mrt 2027; jul–sep 2026 → jul 2027']],['Groep (volgens IND)','Voorbeelden: maand aanvraag → verwachte start IND'])
+'<p>Heeft u eerder aangevraagd dan de tabel noemt en geen brief gehad? Dan valt u waarschijnlijk onder de groep waarop de IND <strong>tijdelijk niet beslist</strong>. Een compleet dossier gaat sneller; bij ontbrekende documenten kan de IND een DNA-onderzoek of interview doen. Bij een bijzondere spoedsituatie, zoals ernstige medische problemen van een gezinslid, wordt bij hoge uitzondering eerder behandeld.</p>'
'<h2 id="steps">Stappen en kosten</h2><ol><li><strong>Controleer de voorwaarden</strong> (gezinsleden, gezinsband van vóór uw komst, uw status).</li><li><strong>Verzamel documenten</strong> vóór de aanvraag: ze moeten al in Nederland zijn, want de IND onderzoekt soms de echtheid. Buitenlandse documenten laat u vertalen naar Nederlands, Engels, Frans of Duits door een vertaler die door een Nederlandse rechtbank is beëdigd. Zie <a href="/nl/articles/syrian-documents-legalisation-translation.html">Syrische documenten legaliseren en vertalen</a>.</li><li><strong>Doe de aanvraag</strong> online of per post; mvv en verblijfsvergunning vraagt u tegelijk aan. De IND raadt aan dat u zelf de aanvraag doet.</li><li><strong>Kosten:</strong> was u 18 of ouder bij uw asielaanvraag en vraagt u voor uw gehuwde partner of uw biologische of geadopteerde kind? Dan is de aanvraag <strong>gratis</strong>. Voor andere gezinsleden <strong>€ 254</strong>. Als alleenstaande minderjarige voor ouders en broers/zussen: gratis.</li><li><strong>Besluit:</strong> bij een positief besluit haalt uw gezinslid de mvv-sticker op bij de Nederlandse vertegenwoordiging binnen <strong>3 maanden</strong> (te verlengen tot 6); paspoort minimaal 6 maanden geldig; aanmelding in Nederland binnen <strong>90 dagen</strong>.</li><li>Negatief besluit: u kunt <strong>bezwaar</strong> maken. Zie <a href="/nl/articles/bezwaar-objection-letter.html">Bezwaar maken tegen een besluit</a>.</li></ol>'
'<h2 id="regular">Wat als nareis niet kan?</h2><p>Er blijft reguliere gezinshereniging met eigen voorwaarden (inkomen, woning, leges, soms inburgeringsexamen in het buitenland). Lees <a href="/nl/articles/family-reunification-mvv-ind.html">Gezinshereniging en mvv bij de IND</a> en <a href="/nl/articles/asylum-family-reunification.html">Gezinshereniging asiel (nareis)</a>. Of dat voor u een reële route is na het verstrijken van de termijn, hangt van uw situatie af: vraag een deskundige.</p>'
'<h2 id="examples">Illustratieve voorbeelden (illustratief, geen echte personen)</h2>'
+T([['Statushouder met status <strong>vluchteling</strong>, wil gehuwde partner en twee kinderen jonger dan 18 laten komen','Geen wachttijd en geen extra inkomens- of huisvestingseis; aanvragen binnen 3 maanden na de vergunning. Gratis. De IND beslist op deze groep wel.'],['Subsidiair beschermd, besluit op 15 oktober 2026, vraagt nareis voor de partner','2 jaar na 15 oktober 2026 is 15 oktober 2028 op zijn vroegst, plus zelfstandig en duurzaam inkomen en huisvesting. Eerder kan het besluit negatief zijn.'],['Jongere met subsidiaire bescherming, als alleenstaande minderjarige gevlucht, vraagt nareis voor ouders en zusje van 12 bij binnenkomst','Alleen wachttijd van 2 jaar; geen inkomens- of huisvestingseis. Zusje wordt samen met een ouder aangevraagd.'],['Statushouder wil zoon van 20 laten komen','Valt niet onder nareis. Mogelijk verblijf via artikel 8 EVRM; de IND maakt een individuele afweging.'],['Pasje met vergunning voor <strong>onbepaalde tijd</strong> van vóór 12 juni 2026','Blijft geldig, volgens de IND.']],['Situatie (verzonnen)','Uitkomst volgens bovenstaande regels'])
+'<p>Illustratieve voorbeelden, geen echte personen. De data en situaties zijn verzonnen om de rekenregels te laten zien.</p>'
'<h2 id="mistakes">Veelgemaakte fouten</h2><ol><li><strong>Afgaan op oud nieuws</strong>: niet alles wat voorgesteld werd, is wet geworden. Controleer de IND en het Staatsblad.</li><li><strong>Uw eigen status niet kennen</strong>: kijk in uw besluit of op de achterkant van het pasje.</li><li><strong>De termijn van 3 maanden missen</strong> als vluchteling omdat documenten nog ontbreken: dien in en vul aan.</li><li><strong>Een oude asielaanvraag intrekken</strong> om opnieuw aan te vragen: dat verkort de wachttijd niet.</li><li><strong>Post van de IND missen</strong> of een adreswijziging niet doorgeven.</li><li><strong>Betalen aan tussenpersonen</strong> die beloven dat het sneller gaat: nareis is niet te versnellen met geld. Zie <a href="/nl/articles/scams-phishing-netherlands.html">Oplichting in Nederland</a>.</li></ol>'
'<h2 id="help">Waar vind ik menselijke hulp?</h2><p>De regels veranderen snel en kunnen voor uw situatie anders uitpakken. Gratis hulp staat in de <a href="/nl/articles/asylum-residence-hub.html">hub asiel en verblijf</a>: VluchtelingenWerk Nederland, het Juridisch Loket, sociaal raadslieden en de Nationale ombudsman.</p>'
'<h2 id="related">Gerelateerde gidsen</h2><ul><li><a href="/nl/articles/asylum-family-reunification.html">Gezinshereniging asiel (nareis)</a></li><li><a href="/nl/articles/family-reunification-mvv-ind.html">Gezinshereniging met partner: mvv en regulier verblijf</a></li><li><a href="/nl/articles/eu-permanent-residence-netherlands.html">Permanent verblijf en EU-langdurig ingezetene</a></li><li><a href="/nl/articles/inburgering-integration-law-2026.html">Inburgeren in 2026</a></li><li><a href="/nl/articles/bsn-municipality-registration.html">Inschrijven bij de gemeente en BSN</a></li><li><a href="/nl/articles/asylum-residence-hub.html">Hub asiel en verblijf</a></li></ul>'),
faq=[('Wat is het verschil tussen vluchteling en subsidiair beschermde?','Een vluchteling loopt persoonlijk risico op vervolging (afkomst, geloof, politieke voorkeur). Wie subsidiaire bescherming heeft, is om een andere reden gevlucht, bijvoorbeeld door oorlog. Sinds 12 juni 2026 gelden verschillende nareisvoorwaarden.'),
('Is mijn vergunning voor onbepaalde tijd ingetrokken?','Nee. Volgens de IND houdt u die als u haar op 12 juni 2026 al had. Aanvragen kan niet meer.'),
('Hoelang is de nieuwe verblijfsvergunning asiel geldig?','3 jaar. Ook het nieuwe pasje is 3 jaar geldig; de ingangsdatum is 12 juni 2026.'),
('Waar zie ik mijn status?','Op de eerste pagina van uw IND-besluit (artikel 29, eerste lid, onder a = vluchteling, onder b = subsidiaire bescherming) of op de achterkant van het pasje bij besluiten na 12 juni 2026.'),
('Welke gezinsleden mogen nog via nareis komen?','Wettelijk gehuwde partner en biologische of geadopteerde kinderen jonger dan 18; bij een alleenstaande minderjarige ook ouders en minderjarige broers/zussen. Andere familieleden via artikel 8 EVRM.'),
('Welke extra voorwaarden gelden bij subsidiaire bescherming?','2 jaar wachttijd vanaf het besluit, zelfstandig en duurzaam inkomen en huisvesting. Een alleenstaande minderjarige hoeft alleen aan de wachttijd te voldoen.'),
('Waarom beslist de IND niet op mijn aanvraag?','Mogelijk valt u in de groep waarop de IND tijdelijk niet beslist, in afwachting van een uitspraak van de rechtbank over toepassing met terugwerkende kracht. Wanneer die komt, is niet bekend; bekijk de IND-pagina of bel de nareislijn.'),
('Kost nareis geld?','Voor een volwassen aanvrager met gehuwde partner of biologische of geadopteerde kinderen: gratis volgens de IND. Voor andere gezinsleden € 254. Controleer de actuele leges.'),
('Helpt het om mijn oude asielaanvraag in te trekken en opnieuw aan te vragen?','Nee. De datum van uw eerdere aanvraag bepaalt uw beurt, aldus de IND.'),
('Waar kan ik gratis hulp krijgen?','Bij VluchtelingenWerk Nederland, het Juridisch Loket en sociaal raadslieden in uw gemeente. Zie de hub asiel en verblijf.')],
src_note='Gecontroleerd bij de IND, Rijksoverheid en Staatsblad 2026, 105 op 8 oktober 2026; IND-wachttijdpagina bijgewerkt op 7 oktober 2026 en wijzigt vaak. Niet vastgesteld: gevolgen voor permanent verblijf, naturalisatie of inburgering van wie vóór 12 juni een vergunning kreeg, een termijn voor nareis bij subsidiaire bescherming en het actuele inkomensbedrag. Voorbeelden zijn illustratief, geen echte personen.')
