from a_student_finance import T
SLUG='temporary-agency-work-rights'
SRC=[('Rijksoverheid · Welke arbeidsvoorwaarden heb ik als uitzendkracht?','https://www.rijksoverheid.nl/vraag-en-antwoord/arbeidsovereenkomst-en-cao/welke-arbeidsvoorwaarden-heb-ik-als-uitzendkracht'),
('Rijksoverheid · Wordt mijn loon doorbetaald als ik als uitzendkracht ziek ben?','https://www.rijksoverheid.nl/vraag-en-antwoord/ziekteverzuim-van-het-werk/wordt-mijn-loon-doorbetaald-als-ik-als-uitzendkracht-ziek-ben'),
('Rijksoverheid · Wanneer gaat mijn tijdelijke contract over in een vast contract?','https://www.rijksoverheid.nl/vraag-en-antwoord/arbeidsovereenkomst-en-cao/wanneer-verandert-mijn-tijdelijke-arbeidscontract-in-een-vast-contract'),
('Rijksoverheid · Vanaf 2027 strengere regels uitzendbureaus','https://www.rijksoverheid.nl/actueel/nieuws/2025/04/24/vanaf-2027-strengere-regels-uitzendbureaus'),
('Rijksoverheid · Welke arbeidsvoorwaarden heb ik als payrollkracht?','https://www.rijksoverheid.nl/vraag-en-antwoord/arbeidsovereenkomst-en-cao/welke-arbeidsvoorwaarden-heb-ik-als-payrollkracht'),
('Rijksoverheid · Meer zekerheid voor mensen met een flexcontract (7-7-2026)','https://www.rijksoverheid.nl/actueel/nieuws/2026/07/08/meer-zekerheid-voor-mensen-met-een-flexcontract'),
('Nederlandse Arbeidsinspectie · Melden','https://www.nlarbeidsinspectie.nl/onderwerpen/melden')]

AR=dict(title='العمل عبر وكالات التوظيف (Uitzendbureau) في هولندا 2026: حقوقك في الأجر والمرض والسكن، وقانون ترخيص الوكالات من 2027',
crumb='العمل عبر وكالة توظيف',
desc='دليل عميق للعاملين عبر Uitzendbureau: من هو صاحب عملك، المساواة في الأجر مع موظفي الشركة، ما لا يحق للوكالة أخذه منك، المرض وبند الوكالة (uitzendbeding)، سلسلة العقود، كيف تكشف الوكالة غير النظامية، والترخيص الإلزامي للوكالات (Wtta) من 1 يناير 2027.',
summary='<ol><li><strong>صاحب عملك القانوني هو الوكالة</strong>، وليس الشركة التي تعمل فيها (inlener). عقدك وراتبك وقسيمة راتبك من الوكالة.</li><li><strong>المساواة:</strong> يجب أن تُعامل مثل موظفي الشركة في الوظيفة نفسها: الأجر والبدلات (مثل بدل السفر)، ساعات العمل والراحة، الاستراحات، العمل الإضافي، العطل الرسمية، المناوبات الليلية، ومدة الإجازة.</li><li><strong>الوكالة لا يحق لها أن تأخذ منك مالاً</strong> مقابل إيجاد العمل، ويجب أن تبلغك كتابياً بظروف العمل مسبقاً، وأن تكون مسجلة في KvK.</li><li><strong>في المرض:</strong> بلّغ الوكالة <strong>والشركة</strong> معاً. إن كانت الوكالة تطبق CAO الوكالات (ABU أو NBBU) فلا تنهي عقدك بسبب المرض.</li><li><strong>من 1 يناير 2027</strong> يبدأ قانون الترخيص الإلزامي للوكالات (Wtta)؛ ومن <strong>1 يناير 2028</strong> تُغرَّم الوكالة غير المرخصة والشركة التي تستخدمها.</li></ol>',
body=(
'<h2 id="how">كيف يعمل العمل عبر الوكالة؟ ثلاثة أطراف</h2>'
+T([['الوكالة (uitzendbureau / uitlener)','صاحب العمل القانوني: توقع معك العقد، تدفع الراتب، تقتطع الضرائب، تصدر قسيمة الراتب، وتتعامل مع مرضك وإجازتك.'],
    ['الشركة المستفيدة (inlener)','المكان الذي تعمل فيه فعلياً، ويوجّه عملك اليومي. ملزمة بإبلاغ الوكالة بشروط عملها مسبقاً.'],
    ['أنت (uitzendkracht)','تعمل لدى الشركة، لكن حقوقك تُطالَب بها من الوكالة أولاً.']],
   ['الطرف','الدور'])
+'<p><strong>لماذا يهمك هذا؟</strong> لأن أي خطأ في الأجر، أو الساعات، أو الإجازة، تراجعه مع <strong>الوكالة</strong>. والشركة المستفيدة أيضاً تتحمل مسؤولية في بعض الحالات (مثل سلامة مكان العمل).</p>'
'<h2 id="phases">مراحل العقود في CAO الوكالات (الفكرة العامة)</h2><p>معظم الوكالات في هولندا تطبق CAO خاصاً بالوكالات (من اتحادَي <strong>ABU</strong> أو <strong>NBBU</strong>). هذه الـCAO تقسم عملك إلى مراحل: في البداية حماية أقل (مثل «بند الوكالة» الذي ينهي العقد عند انتهاء المهمة)، ثم عقود مؤقتة بشروط أفضل، ثم عقد دائم مع الوكالة. تفاصيل كل مرحلة (مدتها وعدد العقود) تختلف بين ABU وNBBU وتتغير مع كل CAO جديد، لذلك:</p><ul><li>اسأل الوكالة كتابياً: «أي CAO تطبقون؟ وفي أي مرحلة أنا الآن؟».</li><li>اطلب نسخة من الـCAO واحتفظ بكل عقودك وتواريخها.</li><li>قانون 2028 الجديد سيقصّر المراحل الأقل أماناً (تفاصيل في آخر الدليل).</li></ul>'
'<h2 id="equal">المساواة في الأجر وشروط العمل</h2><p>حسب Rijksoverheid يجب أن تعاملك الوكالة <strong>كما يُعامَل موظفو الشركة</strong> في وظائف مماثلة أو مكافئة، في:</p>'
+T([['الأجر والتعويضات','الأجر نفسه للوظيفة نفسها، وبدلات مثل تعويض السفر.'],
    ['ساعات العمل والراحة','الحدود القانونية والأنظمة المطبقة في الشركة.'],
    ['الاستراحات','نفس قواعد الاستراحة.'],
    ['العمل الإضافي','نفس التعويض عن الساعات الإضافية.'],
    ['العطل الرسمية','نفس قواعد العمل أو التعويض في العطل.'],
    ['المناوبات الليلية','نفس الحماية والتعويض.'],
    ['مدة الإجازة','نفس عدد أيام الإجازة.'],
    ['قواعد الحماية','حماية الشباب، والحوامل، والمرضعات.']],
   ['المجال','ما يعنيه'])
+'<p><strong>كيف تتحقق؟</strong> قارن ما يظهر في <a href="/articles/dutch-payslip-explained.html">قسيمة راتبك</a> مع زميل دائم في الوظيفة نفسها، أو اسأل الوكالة: «ما الدرجة الوظيفية (schaal) والأجر المطبق لدى الشركة؟». تذكر أن الـCAO قد يحتوي ترتيبات مختلفة؛ اسأل عنها.</p>'
'<h2 id="forbidden">ما لا يحق للوكالة فعله</h2><ul><li><strong>أخذ مال منك</strong> أو أي مقابل لقاء إيجاد العمل أو «تسجيلك».</li><li><strong>إرسالك إلى شركة فيها إضراب</strong> أو احتلال.</li><li>العمل دون <strong>تسجيل في سجل KvK التجاري</strong>.</li><li>إرسالك دون أن تخبرك <strong>كتابياً ومسبقاً</strong> بظروف العمل في المكان (السلامة، معدات الحماية، المخاطر).</li><li>دفع أقل من <a href="/articles/minimum-wage-netherlands.html">الحد الأدنى للأجر</a> بعد الخصومات المسموحة.</li></ul><p>إن شككت في أن الوكالة تخالف القواعد: قدّم بلاغاً لدى <strong>Nederlandse Arbeidsinspectie</strong> (رابط في المصادر). يمكنك أيضاً الاتصال بـJuridisch Loket أو نقابة (FNV، CNV).</p>'
'<h2 id="housing">السكن والخصومات: انتبه بشكل خاص</h2><p>كثير من العمال القادمين من الخارج يحصلون على السكن والنقل عبر الوكالة. هذا شائع وقانوني من حيث المبدأ، لكنه مصدر أغلب المشاكل:</p><ul><li>اطلب <strong>عقد سكن منفصلاً</strong> عن عقد العمل، ونسخة مكتوبة من كل خصم (إيجار، تأمين صحي، نقل، غرامات).</li><li>تحقق أن كل خصم ظاهر على قسيمة الراتب، وأن صافي ما يبقى منطقي.</li><li>التأمين الصحي الأساسي إلزامي لمن يعمل في هولندا؛ تأكد هل تدفعه الوكالة وتخصمه، أم أنت مسؤول عنه (<a href="/articles/health-insurance-newcomers.html">دليل التأمين الصحي للقادمين الجدد</a>).</li><li>لا تسلّم جواز سفرك أو بطاقتك البنكية للوكالة.</li><li>إن انتهى عملك فاسأل كتابياً عن مهلة إخلاء السكن.</li></ul>'
'<h2 id="sick">المرض أثناء العمل عبر الوكالة</h2><p><strong>الخطوة الأولى دائماً:</strong> أبلغ عن مرضك لدى <strong>الوكالة</strong> و<strong>الشركة المستفيدة</strong> كليهما، وحسب قواعد الإبلاغ المكتوبة.</p>'
+T([['الوكالة عضو في ABU أو NBBU (تطبق CAO الوكالات)','لا يُنهى عقدك بسبب المرض. يُدفع لك الأجر في المرض حسب الـCAO.'],
    ['وكالة بلا CAO، وعقدك فيه بند الوكالة (uitzendbeding)','قد ينتهي العقد من أول يوم مرض إن طلبت الشركة ذلك. بعدها تحصل على إعانة <strong>Ziektewet</strong> من UWV، ويجب على الوكالة إبلاغ UWV عن مرضك في موعد أقصاه اليوم الرابع.'],
    ['وكالة بلا CAO، وعقدك بلا بند الوكالة','تدفع الوكالة أجرك في المرض حتى نهاية العقد.']],
   ['حالتك','ما يحدث'])
+'<ul><li><strong>أيام الانتظار:</strong> قد لا يُدفع اليوم الأول أو اليومان الأولان من المرض، إن نص العقد أو الـCAO على ذلك.</li><li>إن لم تصلك أي رسالة من UWV بعد انتهاء العقد وأنت مريض، اتصل بـUWV بنفسك.</li></ul>'
'<h2 id="chain">هل يمكن أن تتحول إلى موظف دائم؟</h2><ul><li>بعد مراحل الـCAO قد تحصل على <strong>عقد دائم مع الوكالة</strong>.</li><li>إذا انتقلت من الوكالة إلى العمل <strong>مباشرة لدى الشركة نفسها</strong> في العمل نفسه، فإن فترات الوكالة قد <strong>تُحسب في سلسلة العقود</strong> (ما يسمى opvolgend werkgeverschap). بعد أكثر من 3 عقود أو أكثر من 3 سنوات قد يصبح عقدك دائماً تلقائياً (<a href="/articles/employment-contracts-labor-law-2026.html">قواعد سلسلة العقود</a>).</li><li>إن شككت في أنك ضمن «صاحب عمل متتابع» استشر Juridisch Loket.</li></ul>'
'<h2 id="payroll">الفرق بين uitzend وpayroll</h2><p>في <strong>payroll</strong> لا تبحث الوكالة عن عمل لك، بل تتولى «إدارة الرواتب» فقط لشركة اختارتك بنفسها. القانون يمنحك في payroll <strong>نفس شروط عمل وموقع موظفي الشركة القانوني</strong> (مثل الشهر الثالث عشر، الإجازة، التدريب، سلسلة عقود الشركة، ودفع الأجر في المرض كزملائك)، ولا ينطبق عليك CAO الوكالات ومراحله. تحقق من نوع عقدك.</p>'
'<h2 id="wtta">ترخيص الوكالات الإلزامي (Wtta): ما الذي يتغير؟</h2><p>أعلنت الحكومة نظام <strong>ترخيص إلزامي</strong> لكل من يعير عمالاً (Wet toelating terbeschikkingstelling van arbeidskrachten):</p>'
+T([['1 نوفمبر 2026 – 1 يناير 2027','الوكالات التي تريد الاستفادة من الفترة الانتقالية تسجل نفسها لدى وزارة SZW.'],
    ['1 يناير 2027','يدخل القانون حيز التنفيذ، وتبدأ إجراءات الترخيص.'],
    ['قبل 1 يوليو 2027','يجب أن تقدم الوكالات طلب الترخيص.'],
    ['1 يناير 2028','تبدأ هيئة التفتيش (Arbeidsinspectie) بالتطبيق: غرامة على الوكالة غير المرخصة، <strong>وعلى الشركة المستفيدة التي تستخدمها</strong>.']],
   ['التاريخ','ماذا يحدث'])
+'<p>للحصول على الترخيص يجب على الوكالة تقديم <strong>شهادة حسن سلوك (VOG)</strong> و<strong>كفالة 100,000 يورو</strong>، وإثبات التزامها بالقوانين مثل الحد الأدنى للأجر. ويمكن تعليق الترخيص أو سحبه عند مخالفات خطيرة.</p><p><strong>ماذا يعني لك؟</strong> بعد بدء التطبيق، اسأل كل وكالة: «هل أنتم مرخصون؟» وتحقق من السجل العام عندما يصبح متاحاً.</p>'
'<h2 id="red-flags">علامات الوكالة غير النظامية</h2><ul><li>تطلب منك رسوم تسجيل أو «عمولة».</li><li>لا تعطيك عقداً مكتوباً أو قسيمة راتب.</li><li>تدفع نقداً أو بأجر ساعة أقل من الحد الأدنى.</li><li>تحتفظ بوثائقك الشخصية.</li><li>تهددك بالطرد من السكن إن مرضت أو اعترضت.</li><li>لا تجد اسمها في سجل KvK.</li></ul>'
'<h2 id="checklist">قائمة أسئلة قبل البدء مع وكالة</h2><ol><li>ما اسم الوكالة ورقم KvK؟ وهل هي عضو في ABU أو NBBU؟</li><li>أي CAO ينطبق؟ وفي أي مرحلة أبدأ؟</li><li>هل في عقدي بند الوكالة (uitzendbeding)؟</li><li>ما أجري بالساعة الإجمالي؟ وهل يساوي أجر موظفي الشركة؟</li><li>كيف تُحسب الإجازة وبدل العطلة؟ هل تُدفع مع الراتب أم تُدَّخر؟</li><li>ما الخصومات (سكن، تأمين، نقل)؟ أريدها مكتوبة.</li><li>من أبلغ عند المرض، وكيف؟</li><li>كيف أحصل على قسيمة الراتب؟</li></ol>'
'<h2 id="2028">قانون 2028 للعاملين بعقود مرنة</h2><p>بحسب الحكومة، القانون الذي أُقر في <strong>7 يوليو 2026</strong> ويبدأ <strong>1 يناير 2028</strong> يعطي عمال الوكالات <strong>شروط عمل مساوية على الأقل</strong> لشروط الموظفين في الشركة، ويقصّر المراحل الأقل أماناً من <strong>سنة ونصف إلى سنة</strong>. حتى ذلك التاريخ تبقى القواعد الحالية.</p>'),
faq=[('من هو صاحب عملي إذا عملت عبر وكالة؟','الوكالة نفسها. هي التي توقع العقد وتدفع الراتب وتصدر القسيمة، أما الشركة فهي مكان العمل فقط.'),
('هل يحق لي نفس أجر موظفي الشركة؟','نعم، يجب معاملتك مثل الموظفين في وظيفة مماثلة في الأجر والبدلات والساعات والإجازة وغيرها، مع مراعاة ما ينص عليه الـCAO.'),
('الوكالة طلبت مني رسوم تسجيل، هل هذا قانوني؟','لا. لا يحق للوكالة أن تطلب منك مالاً أو مقابلاً لإرسالك للعمل. يمكنك الإبلاغ لدى Nederlandse Arbeidsinspectie.'),
('مرضت، هل يمكن للوكالة إنهاء عقدي؟','إن كانت الوكالة تطبق CAO ABU أو NBBU فلا. إن كانت بلا CAO وعقدك فيه بند الوكالة، قد ينتهي العقد وتحصل على Ziektewet من UWV.'),
('هل تُحسب فترة الوكالة إذا وظفتني الشركة مباشرة؟','قد تُحسب في سلسلة العقود إن كان العمل نفسه، ما قد يجعل عقدك دائماً أسرع.'),
('متى يصبح ترخيص الوكالات إلزامياً؟','يبدأ القانون 1 يناير 2027، وتبدأ الغرامات على الوكالات غير المرخصة والشركات التي تستخدمها من 1 يناير 2028.')],
src_note='راجعنا القواعد والتواريخ في صفحات Rijksoverheid في 4 أكتوبر 2026. تفاصيل المراحل والأجر في المرض تعتمد على CAO الوكالة (ABU أو NBBU). هذا دليل توعوي وليس استشارة قانونية.')

NL=dict(title='Werken via een uitzendbureau in 2026: je rechten bij loon, ziekte en huisvesting, en de toelatingsplicht voor uitleners vanaf 2027',
crumb='Uitzendwerk',
desc='Uitgebreide gids voor uitzendkrachten: wie je werkgever is, gelijke behandeling met personeel van de inlener, wat een uitzendbureau niet mag, ziekte en het uitzendbeding, de ketenregeling, signalen van malafide bureaus en de toelatingsplicht (Wtta) vanaf 1 januari 2027.',
summary='<ol><li><strong>Je juridische werkgever is het uitzendbureau</strong>, niet het bedrijf waar je werkt (de inlener).</li><li><strong>Gelijke behandeling:</strong> loon en vergoedingen (zoals reiskosten), arbeids- en rusttijden, pauzes, overwerk, feestdagen, nachtdiensten, vakantieduur en beschermende regels zoals bij werknemers in gelijke functies bij de inlener.</li><li><strong>Het bureau mag je geen geld vragen</strong> voor het uitzenden, moet je vooraf schriftelijk informeren over de arbeidsomstandigheden en moet ingeschreven zijn bij de KvK.</li><li><strong>Ziek?</strong> Meld je bij het uitzendbureau <strong>én</strong> de inlener. Valt het bureau onder de ABU- of NBBU-cao, dan eindigt je contract niet door ziekte.</li><li><strong>Vanaf 1 januari 2027</strong> geldt de toelatingsplicht (Wtta); vanaf <strong>1 januari 2028</strong> volgen boetes voor uitleners zonder toelating én voor inleners die hen inschakelen.</li></ol>',
body=(
'<h2 id="how">Hoe werkt uitzendwerk? Drie partijen</h2>'
+T([['Uitzendbureau (uitlener)','Juridische werkgever: contract, loon, loonheffing, loonstrook, ziekte en vakantie.'],
    ['Inlener','Waar je feitelijk werkt en dagelijkse leiding krijgt. Moet zijn arbeidsvoorwaarden vooraf aan het bureau doorgeven.'],
    ['Jij (uitzendkracht)','Je werkt bij de inlener, maar je rechten haal je eerst bij het bureau.']],['Partij','Rol'])
+'<h2 id="phases">Fases in de uitzend-cao (in grote lijnen)</h2><p>De meeste bureaus vallen onder de cao van <strong>ABU</strong> of <strong>NBBU</strong>. Die werken met fases: eerst minder zekerheid (zoals het uitzendbeding), daarna tijdelijke contracten met betere voorwaarden, en uiteindelijk een vast contract bij het bureau. Duur en aantal contracten verschillen per cao en per cao-periode. Vraag dus schriftelijk welke cao geldt en in welke fase je zit, en bewaar al je contracten.</p>'
'<h2 id="equal">Gelijke behandeling</h2><p>Volgens de Rijksoverheid moet het bureau je hetzelfde behandelen als werknemers in gelijke of gelijkwaardige functies bij de inlener, voor:</p>'
+T([['Loon en vergoedingen','Zelfde loon, en vergoedingen zoals reiskosten.'],['Arbeids- en rusttijden','Zelfde regels.'],['Pauzes','Zelfde regels.'],['Overwerk','Zelfde vergoeding.'],['Feestdagen','Zelfde regels.'],['Nachtdienst','Zelfde bescherming en vergoeding.'],['Vakantieduur','Zelfde aantal dagen.'],['Beschermende regels','Voor jongeren, zwangeren en vrouwen die borstvoeding geven.']],['Onderwerp','Betekenis'])
+'<p>Vergelijk je <a href="/nl/articles/dutch-payslip-explained.html">loonstrook</a> met een vaste collega in dezelfde functie, of vraag welke loonschaal van de inlener op jou wordt toegepast. In de cao kunnen afwijkende afspraken staan.</p>'
'<h2 id="forbidden">Wat een uitzendbureau niet mag</h2><ul><li>Je <strong>geld of een tegenprestatie vragen</strong> voor het uitzenden.</li><li>Je laten werken bij bedrijven waar <strong>gestaakt</strong> wordt of die bezet zijn.</li><li>Werken zonder inschrijving in het <strong>Handelsregister</strong> van de KvK.</li><li>Je uitzenden zonder je <strong>vooraf schriftelijk</strong> te informeren over de arbeidsomstandigheden.</li><li>Minder betalen dan het <a href="/nl/articles/minimum-wage-netherlands.html">minimumloon</a>.</li></ul><p>Vermoed je dat het bureau zich niet aan de regels houdt? Dien een melding in bij de <strong>Nederlandse Arbeidsinspectie</strong> (zie bronnen), of vraag hulp bij het Juridisch Loket of een vakbond.</p>'
'<h2 id="housing">Huisvesting en inhoudingen</h2><ul><li>Vraag om een <strong>apart huurcontract</strong> en een schriftelijk overzicht van elke inhouding (huur, zorgverzekering, vervoer).</li><li>Controleer of alle inhoudingen op je loonstrook staan.</li><li>De basiszorgverzekering is verplicht voor wie in Nederland werkt; vraag wie die regelt (<a href="/nl/articles/health-insurance-newcomers.html">zorgverzekering voor nieuwkomers</a>).</li><li>Geef nooit je paspoort of bankpas af.</li><li>Vraag schriftelijk welke termijn geldt voor het verlaten van de woning als je werk stopt.</li></ul>'
'<h2 id="sick">Ziek als uitzendkracht</h2><p>Meld je altijd ziek bij het <strong>uitzendbureau én de inlener</strong>, volgens de verzuimregels.</p>'
+T([['Bureau is lid van ABU of NBBU (uitzend-cao)','Je uitzendcontract eindigt niet door ziekte; loondoorbetaling volgens de cao.'],
    ['Bureau zonder cao, contract met uitzendbeding','Het contract kan op de eerste ziektedag eindigen als de inlener dat vraagt. Je krijgt dan Ziektewet van UWV; het bureau moet je uiterlijk op de 4e dag ziekmelden bij UWV.'],
    ['Bureau zonder cao, contract zonder uitzendbeding','Het bureau betaalt loon door tot het einde van je contract.']],['Situatie','Gevolg'])
+'<ul><li><strong>Wachtdagen:</strong> de eerste 1 of 2 ziektedagen kunnen onbetaald zijn als dat in contract of cao staat.</li><li>Hoor je na het einde van je contract niets van UWV terwijl je ziek bent, neem dan zelf contact op.</li></ul>'
'<h2 id="chain">Kun je vast worden?</h2><ul><li>Na de cao-fases kun je een <strong>vast contract bij het bureau</strong> krijgen.</li><li>Ga je daarna <strong>direct bij de inlener</strong> in dienst voor hetzelfde werk, dan tellen de uitzendcontracten mogelijk mee in de <strong>ketenregeling</strong> (opvolgend werkgeverschap): meer dan 3 contracten of meer dan 3 jaar kan een vast contract opleveren (<a href="/nl/articles/employment-contracts-labor-law-2026.html">ketenregeling</a>).</li></ul>'
'<h2 id="payroll">Uitzend of payroll?</h2><p>Bij <strong>payroll</strong> zoekt het bureau geen werk voor je; het verzorgt alleen het werkgeverschap voor een bedrijf dat jou zelf heeft geworven. Een payrollkracht heeft <strong>minimaal dezelfde arbeidsvoorwaarden en rechtspositie</strong> als werknemers van de inlener (zoals 13e maand, vakantiedagen, scholing, de ketenregeling van het bedrijf en loondoorbetaling bij ziekte). De uitzend-cao met fases geldt dan niet.</p>'
'<h2 id="wtta">Toelatingsplicht voor uitleners (Wtta)</h2>'
+T([['1 november 2026 – 1 januari 2027','Uitleners die gebruik willen maken van het overgangsrecht melden zich bij het ministerie van SZW.'],
    ['1 januari 2027','De wet treedt in werking; het toelatingsproces start.'],
    ['Vóór 1 juli 2027','Uitleners moeten hun aanvraag indienen.'],
    ['1 januari 2028','De Nederlandse Arbeidsinspectie gaat handhaven: boete voor uitleners zonder toelating <strong>én voor inleners</strong> die hen inschakelen.']],['Datum','Wat er gebeurt'])
+'<p>Voor toelating moeten uitleners een <strong>VOG</strong> indienen, een <strong>waarborgsom van €100.000</strong> storten en aantonen dat ze wet- en regelgeving naleven, zoals het minimumloon. Bij ernstige misstanden kan de toelating worden geschorst of ingetrokken.</p>'
'<h2 id="red-flags">Signalen van een malafide bureau</h2><ul><li>Inschrijfgeld of «bemiddelingskosten».</li><li>Geen schriftelijk contract of loonstrook.</li><li>Contante betaling of uurloon onder het minimumloon.</li><li>Het bureau houdt je documenten in.</li><li>Dreigen met uitzetting uit de woning bij ziekte of klachten.</li><li>Niet te vinden in het KvK-register.</li></ul>'
'<h2 id="checklist">Checklist vóór je begint</h2><ol><li>Naam en KvK-nummer van het bureau? Lid van ABU of NBBU?</li><li>Welke cao, en in welke fase begin ik?</li><li>Staat er een uitzendbeding in mijn contract?</li><li>Wat is mijn bruto uurloon, en is dat gelijk aan dat van de inlener?</li><li>Hoe worden vakantie en vakantiegeld opgebouwd of uitbetaald?</li><li>Welke inhoudingen (huisvesting, zorgverzekering, vervoer)? Op papier.</li><li>Bij wie en hoe meld ik me ziek?</li><li>Hoe krijg ik mijn loonstrook?</li></ol>'
'<h2 id="2028">Wet meer zekerheid flexwerkers (2028)</h2><p>Volgens de overheid krijgen uitzendkrachten met deze wet (aangenomen <strong>7 juli 2026</strong>, invoering <strong>1 januari 2028</strong>) minimaal gelijkwaardige arbeidsvoorwaarden als werknemers van de inlener, en worden de meest onzekere fases verkort van <strong>anderhalf jaar naar 1 jaar</strong>. Tot die datum gelden de huidige regels.</p>'),
faq=[('Wie is mijn werkgever als uitzendkracht?','Het uitzendbureau: dat sluit het contract, betaalt het loon en geeft de loonstrook. De inlener is de plek waar je werkt.'),
('Heb ik recht op hetzelfde loon als vaste collega’s?','Ja, je moet hetzelfde worden behandeld als werknemers in gelijke of gelijkwaardige functies bij de inlener, met inachtneming van de cao.'),
('Het bureau vraagt inschrijfgeld. Mag dat?','Nee. Een uitzendbureau mag je geen geld of tegenprestatie vragen. Je kunt dit melden bij de Nederlandse Arbeidsinspectie.'),
('Kan mijn contract eindigen als ik ziek word?','Niet als het bureau onder de ABU- of NBBU-cao valt. Bij een bureau zonder cao met uitzendbeding wel; dan krijg je Ziektewet van UWV.'),
('Telt mijn uitzendtijd mee als de inlener me zelf aanneemt?','Mogelijk wel, via opvolgend werkgeverschap in de ketenregeling.'),
('Wanneer is toelating voor uitzendbureaus verplicht?','De wet geldt vanaf 1 januari 2027; vanaf 1 januari 2028 krijgen uitleners zonder toelating en hun inleners een boete.')],
src_note='Regels en data gecontroleerd op Rijksoverheid op 4 oktober 2026. Fases en loondoorbetaling bij ziekte hangen af van de uitzend-cao (ABU of NBBU). Dit is algemene informatie, geen juridisch advies.')
