from a_student_finance import T
SLUG='wmo-home-support'
R='https://www.rijksoverheid.nl/onderwerpen/zorg-en-ondersteuning-thuis/vraag-en-antwoord/'
SRC=[('Rijksoverheid · Ondersteuning van de gemeente (Wmo 2015)',R+'ondersteuning-gemeente-wmo-2015'),
('Rijksoverheid · Ondersteuning Wmo 2015 aanvragen',R+'ondersteuning-gemeente-wmo-2015-aanvragen'),
('Rijksoverheid · Eigen bijdrage Wmo 2015',R+'eigen-bijdrage-wmo-2015'),
('Rijksoverheid · Bezwaar tegen een beslissing Wmo 2015',R+'bezwaar-beslissing-wmo-2015')]

AR=dict(title='دعم البلدية في البيت (Wmo) 2026: المساعدة المنزلية، الكرسي المتحرك، تعديل البيت، المرافقة؛ كيف تطلب، البحث خلال 6 أسابيع، المساهمة 21.80 يورو شهرياً، والاعتراض',
crumb='دعم Wmo',
seo_title='دعم Wmo من البلدية في البيت 2026',
desc='دعم Wmo من البلدية 2026: مساعدة منزلية وكرسي متحرك وتعديل البيت، بحث خلال 6 أسابيع، مساهمة 21.80 يورو شهرياً، واعتراض خلال 6 أسابيع.',
summary='<ol><li><strong>Wmo</strong> يعني أن <strong>البلدية</strong> تساعدك لتبقى تعيش في بيتك وتشارك في المجتمع إن كان المرض أو العمر أو الإعاقة يصعّب ذلك.</li><li>يشمل: <strong>المساعدة المنزلية</strong>، <strong>الكرسي المتحرك</strong> والأجهزة، <strong>تعديل البيت</strong> (مثل مصعد الدرج)، <strong>المرافقة</strong>، <strong>الرعاية النهارية</strong>، واستراحة لمقدمي الرعاية.</li><li><strong>الطلب:</strong> تبلغ البلدية (مكتب Wmo أو فريق الحي)، فتجري <strong>بحثاً خلال 6 أسابيع</strong> كحد أقصى. لك <strong>دعم مستقل مجاني</strong> أثناء ذلك.</li><li><strong>المساهمة 2026:</strong> <strong>21.80 يورو شهرياً</strong> لمعظم الدعم (لمن عمره 18+)، عبر CAK. ومن 2027 مقترح مساهمة حسب الدخل والمال (يحتاج موافقة البرلمان).</li><li>لا توافق على القرار؟ <strong>اعتراض خلال 6 أسابيع</strong>.</li></ol>',
body=(
'<h2 id="what">ما الذي يوفره Wmo؟</h2>'
+T([['مساعدة منزلية (huishoudelijke hulp)','تنظيف البيت وأعمال منزلية لا تستطيعها'],['أجهزة (hulpmiddelen)','كرسي متحرك، دراجة كهربائية للتنقل، أجهزة مساعدة'],['تعديل البيت (woningaanpassing)','مصعد درج، تعديل الحمام…'],['المرافقة (begeleiding)','مساعدة في تنظيم اليوم والإدارة والتواصل'],['الرعاية النهارية (dagbesteding)','أنشطة نهارية منظمة'],['استراحة ودعم مقدم الرعاية (respijtzorg، mantelzorgondersteuning)','لمن يرعى قريباً'],['الإيواء الاجتماعي','لمن فقد بيته أو في أزمة']],['نوع الدعم','أمثلة'])
+'<p><strong>خدمات عامة دون تقييم:</strong> كثير من البلديات تقدم خدمات بلا إجراءات، مثل خدمة التسوق، وجبات جاهزة، أماكن لقاء. اسأل عنها أولاً.</p>'
'<h2 id="who">من يستحق؟</h2><p>كل ساكن في البلدية يحتاج دعماً ليعيش مستقلاً أو يشارك في المجتمع ولا يستطيع حل ذلك بنفسه أو بمساعدة محيطه أو عبر جهة أخرى (مثل التأمين الصحي أو قانون الرعاية طويلة الأمد Wlz). البلدية تنظر لحالتك الخاصة؛ لا توجد قائمة ثابتة لمن «يستحق».</p>'
'<h2 id="process">الطلب خطوة بخطوة</h2><ol><li><strong>البلاغ:</strong> تواصل مع مكتب Wmo أو فريق الحي في بلديتك (هاتفياً أو عبر الموقع).</li><li><strong>الدعم المستقل المجاني:</strong> اطلب «cliëntondersteuner» يرافقك ويساعدك في التعبير عن احتياجاتك.</li><li><strong>البحث (المقابلة):</strong> تجريه البلدية بأسرع ما يمكن، <strong>خلال 6 أسابيع كحد أقصى</strong> من البلاغ. يُنظر إلى: احتياجاتك، قدراتك، شبكتك الاجتماعية، وهل يغطي قانون آخر حاجتك. غالباً تتم المقابلة في بيتك.</li><li><strong>تقرير البحث:</strong> تحصل عليه؛ صحّح ما هو خاطئ.</li><li><strong>الطلب الرسمي ثم القرار</strong>.</li></ol><p><strong>نصيحة:</strong> قبل المقابلة اكتب ما لا تستطيعه في يوم عادي (الاستحمام، التنظيف، الدرج، التسوق)، ومن يساعدك الآن وكم يتعب.</p>'
'<h2 id="pgb">الخدمة المباشرة أم الميزانية الشخصية؟</h2>'
+T([['الخدمة المباشرة (zorg in natura)','البلدية تتعاقد مع مقدم الخدمة وتنظم كل شيء','أسهل إدارياً'],['الميزانية الشخصية (pgb)','تحصل على ميزانية وتختار من يقدم الدعم بنفسك','حرية أكبر لكن عليك مسؤولية إدارية ومحاسبة']],['الخيار','كيف يعمل','ملاحظة'])
+'<h2 id="contribution">المساهمة الذاتية</h2><ul><li>في 2026: <strong>21.80 يورو شهرياً</strong> لمعظم دعم Wmo، لمن عمره 18 سنة فأكثر، تجمعها هيئة <strong>CAK</strong>.</li><li><strong>من 1 يناير 2027 (مقترح):</strong> مساهمة حسب الدخل والمال؛ تحتاج موافقة البرلمان.</li><li>إن كان دخلك منخفضاً فاسأل عن <a href="/articles/special-assistance-bijzondere-bijstand.html">المساعدة الخاصة</a>؛ وإن كانت AOW غير كاملة فراجع <a href="/articles/aow-aio-pension.html">AOW وإضافة AIO</a>.</li></ul>'
'<h2 id="appeal">لا توافق على القرار؟</h2>'
+T([['الاعتراض لدى البلدية','كتابياً خلال <strong>6 أسابيع</strong> من القرار'],['قرار البلدية على الاعتراض','خلال 6 أسابيع (قابلة للتمديد 6 أخرى)'],['الاستئناف لدى المحكمة','خلال 6 أسابيع من قرار الاعتراض'],['الاستئناف الأعلى (Centrale Raad van Beroep)','خلال 6 أسابيع']],['المرحلة','المهلة'])
+'<p>كيف تكتب الاعتراض: راجع <a href="/articles/bezwaar-objection-letter.html">دليل رسالة الاعتراض</a>.</p><h2 id="other-laws">Wmo أم قانون آخر؟</h2><ul><li><strong>Wmo (البلدية):</strong> الدعم للعيش المستقل والمشاركة.</li><li><strong>التأمين الصحي:</strong> التمريض المنزلي والعلاج (<a href="/articles/health-insurance-2027.html">التأمين الصحي</a>).</li><li><strong>Wlz:</strong> رعاية دائمة على مدار الساعة (مثلاً دار رعاية).</li><li><strong>قانون الشباب (Jeugdwet):</strong> الدعم للأطفال تحت 18 عبر البلدية أيضاً.</li></ul>'
'<h2 id="mistakes">أخطاء شائعة</h2><ol><li>انتظار الانهيار قبل طلب المساعدة؛ ابلغ مبكراً.</li><li>الذهاب للمقابلة وحدك دون دعم مستقل.</li><li>التقليل من المشكلة في المقابلة خجلاً.</li><li>عدم قراءة تقرير البحث وتصحيحه.</li><li>تفويت مهلة الاعتراض.</li></ol>'),
faq=[('ما هو Wmo؟','قانون تساعدك بموجبه البلدية لتعيش مستقلاً وتشارك في المجتمع: مساعدة منزلية، أجهزة، تعديل البيت، مرافقة، رعاية نهارية.'),
('كيف أطلب؟','أبلغ مكتب Wmo أو فريق الحي؛ تجري البلدية بحثاً خلال 6 أسابيع.'),
('كم أدفع؟','21.80 يورو شهرياً لمعظم الدعم في 2026، عبر CAK.'),
('هل يمكنني اختيار مقدم الخدمة بنفسي؟','نعم عبر الميزانية الشخصية (pgb)، أو تختار الخدمة المباشرة من البلدية.'),
('رفضت البلدية طلبي، ماذا أفعل؟','اعترض كتابياً خلال 6 أسابيع من القرار.')],
src_note='راجعنا صفحات Rijksoverheid عن Wmo 2015 في 5 أكتوبر 2026. البلديات تنفذ القانون وتختلف في التفاصيل؛ اسأل مكتب Wmo في بلديتك.')

NL=dict(title='Wmo: hulp van de gemeente thuis in 2026 — huishoudelijke hulp, rolstoel, woningaanpassing en begeleiding; melden, onderzoek binnen 6 weken, eigen bijdrage € 21,80 per maand en bezwaar',
crumb='Wmo',
seo_title='Wmo 2026: hulp van de gemeente thuis',
desc='Wmo 2026: huishoudelijke hulp, rolstoel en woningaanpassing via de gemeente. Onderzoek binnen 6 weken, eigen bijdrage € 21,80 per maand en bezwaar.',
summary='<ol><li><strong>Wmo</strong>: de <strong>gemeente</strong> helpt je zelfstandig te wonen en mee te doen als ziekte, ouderdom of beperking dat moeilijk maakt.</li><li>Onder meer <strong>huishoudelijke hulp</strong>, <strong>rolstoel</strong> en hulpmiddelen, <strong>woningaanpassing</strong>, <strong>begeleiding</strong>, <strong>dagbesteding</strong> en respijtzorg.</li><li><strong>Melden</strong> bij het Wmo-loket of wijkteam; <strong>onderzoek binnen 6 weken</strong>. Gratis onafhankelijke cliëntondersteuning.</li><li><strong>Eigen bijdrage 2026:</strong> <strong>€ 21,80 per maand</strong> (18+), via het CAK; voor 2027 is een inkomens- en vermogensafhankelijke bijdrage voorgesteld.</li><li>Niet eens? <strong>Bezwaar binnen 6 weken</strong>.</li></ol>',
body=(
'<h2 id="what">Wat biedt de Wmo?</h2>'
+T([['Huishoudelijke hulp','Schoonmaken en huishoudelijke taken'],['Hulpmiddelen','Rolstoel, scootmobiel, andere hulpmiddelen'],['Woningaanpassing','Traplift, badkameraanpassing'],['Begeleiding','Hulp bij dagstructuur, administratie, contacten'],['Dagbesteding','Georganiseerde dagactiviteiten'],['Respijtzorg en mantelzorgondersteuning','Voor wie voor een naaste zorgt'],['Maatschappelijke opvang','Bij dakloosheid of crisis']],['Ondersteuning','Voorbeelden'])
+'<p><strong>Algemene voorzieningen</strong> zonder indicatie, zoals boodschappendienst, maaltijdservice of ontmoetingsplekken: vraag daar eerst naar.</p>'
'<h2 id="who">Wie komt in aanmerking?</h2><p>Inwoners die ondersteuning nodig hebben om zelfstandig te wonen of mee te doen en dat niet zelf, met hun netwerk of via een andere wet (zoals de Zvw of de Wlz) kunnen oplossen. De gemeente kijkt naar jouw situatie.</p>'
'<h2 id="process">Aanvragen in stappen</h2><ol><li><strong>Melding</strong> bij het Wmo-loket of wijkteam.</li><li><strong>Gratis cliëntondersteuning</strong>: vraag een onafhankelijke cliëntondersteuner.</li><li><strong>Onderzoek</strong> zo snel mogelijk, <strong>uiterlijk binnen 6 weken</strong> na de melding: behoeften, eigen mogelijkheden, netwerk en andere wetten. Vaak thuis (keukentafelgesprek).</li><li><strong>Verslag</strong>: controleer en corrigeer.</li><li><strong>Aanvraag en besluit</strong>.</li></ol><p><strong>Tip:</strong> schrijf vooraf op wat je op een gewone dag niet lukt en wie je nu helpt.</p>'
'<h2 id="pgb">Zorg in natura of pgb?</h2>'
+T([['Zorg in natura','Gemeente regelt de aanbieder','Administratief eenvoudig'],['Persoonsgebonden budget (pgb)','Je krijgt budget en kiest zelf','Meer vrijheid, meer administratie en verantwoording']],['Vorm','Werking','Let op'])
+'<h2 id="contribution">Eigen bijdrage</h2><ul><li>2026: <strong>€ 21,80 per maand</strong> voor de meeste Wmo-ondersteuning, voor 18+, via het <strong>CAK</strong>.</li><li><strong>Per 1 januari 2027 (voornemen):</strong> inkomens- en vermogensafhankelijke bijdrage; parlementaire goedkeuring nodig.</li><li>Laag inkomen: vraag naar <a href="/nl/articles/special-assistance-bijzondere-bijstand.html">bijzondere bijstand</a>; met een onvolledige AOW zie ook <a href="/nl/articles/aow-aio-pension.html">AOW en AIO-aanvulling</a>.</li></ul>'
'<h2 id="appeal">Bezwaar en beroep</h2>'
+T([['Bezwaar bij de gemeente','Schriftelijk binnen <strong>6 weken</strong> na het besluit'],['Beslissing op bezwaar','Binnen 6 weken (verlengbaar met 6)'],['Beroep bij de rechtbank','Binnen 6 weken'],['Hoger beroep (Centrale Raad van Beroep)','Binnen 6 weken']],['Stap','Termijn'])
+'<p>Hoe je een bezwaarschrift schrijft: zie onze <a href="/nl/articles/bezwaar-objection-letter.html">gids bezwaar maken</a>.</p><h2 id="other-laws">Wmo of een andere wet?</h2><ul><li><strong>Wmo (gemeente):</strong> zelfstandig wonen en meedoen.</li><li><strong>Zorgverzekering:</strong> wijkverpleging en behandeling (<a href="/nl/articles/health-insurance-2027.html">zorgverzekering</a>).</li><li><strong>Wlz:</strong> blijvende 24-uurszorg.</li><li><strong>Jeugdwet:</strong> ondersteuning voor kinderen onder 18, ook via de gemeente.</li></ul>'
'<h2 id="mistakes">Veelgemaakte fouten</h2><ol><li>Te lang wachten met melden.</li><li>Zonder cliëntondersteuner naar het gesprek.</li><li>Problemen kleiner maken uit schaamte.</li><li>Het verslag niet controleren.</li><li>De bezwaartermijn missen.</li></ol>'),
faq=[('Wat is de Wmo?','Een wet waarmee de gemeente je helpt zelfstandig te wonen en mee te doen: huishoudelijke hulp, hulpmiddelen, woningaanpassing, begeleiding en dagbesteding.'),
('Hoe vraag ik het aan?','Melding bij het Wmo-loket of wijkteam; de gemeente onderzoekt binnen 6 weken.'),
('Wat kost het?','€ 21,80 per maand voor de meeste ondersteuning in 2026, via het CAK.'),
('Kan ik zelf een aanbieder kiezen?','Ja, met een pgb; of je kiest zorg in natura via de gemeente.'),
('Mijn aanvraag is afgewezen.','Maak schriftelijk bezwaar binnen 6 weken na het besluit.')],
src_note='Gecontroleerd op Rijksoverheid-pagina’s over de Wmo 2015 op 5 oktober 2026. Gemeenten voeren uit en verschillen in details; vraag het Wmo-loket van je gemeente.')
