from a_student_finance import T
SLUG='year-end-checklist-2026'
R='https://www.rijksoverheid.nl/'
SRC=[('Rijksoverheid · Overstappen zorgverzekeraar',R+'onderwerpen/zorgverzekering/vraag-en-antwoord/overstappen-zorgverzekeraar'),
('Rijksoverheid · Prinsjesdag 2026 in begrijpelijke taal',R+'actueel/nieuws/2026/09/15/prinsjesdag-2026-in-begrijpelijke-taal'),
('Rijksoverheid · Belastingplan 2027',R+'actueel/nieuws/2026/09/15/belastingplan-2027-voorstellen-voor-beter-werkend-belastingstelsel-en-gezonde-overheidsfinancien'),
('Rijksoverheid · Voorlopige aanslag',R+'onderwerpen/inkomstenbelasting/vraag-en-antwoord/wat-is-de-voorlopige-aanslag-van-de-belastingdienst'),
('Rijksoverheid · Noodfonds Energie gaat open',R+'actueel/nieuws/2026/09/29/noodfonds-energie-gaat-open'),
('Volkshuisvesting Nederland · Wet toekomstbestendige Huurcommissie','https://www.volkshuisvestingnederland.nl/actueel/nieuws/2026/09/29/eerste-kamer-stemt-in-met-wet-voor-toekomstbestendige-huurcommissie'),
('Dienst Toeslagen · Proefberekening','https://www.belastingdienst.nl/wps/wcm/connect/nl/toeslagen/content/hulpmiddel-proefberekening-toeslagen')]
AR=dict(title='قائمة نهاية السنة 2026: ماذا تفعل قبل 31 ديسمبر وفي يناير 2027 (التأمين الصحي، البدلات، الضرائب، الطاقة)',
crumb='قائمة نهاية السنة',
desc='قائمة عملية مرتبة بالتواريخ لكل أسرة في هولندا: تغيير التأمين الصحي قبل 31 ديسمبر، تحديث دخل 2027 في البدلات، الدفعة المؤقتة للضرائب، صندوق الطاقة من 1 ديسمبر، وما تغيّر في ميزانية 2027 — مع أمثلة وأسئلة شائعة.',
summary='<ol><li><strong>12 نوفمبر</strong>: شركات التأمين تنشر أسعار 2027 — قارن.</li><li><strong>قبل 31 ديسمبر</strong>: غيّر التأمين الصحي إن أردت (والشركة الجديدة تلغي القديم).</li><li><strong>ديسمبر</strong>: حدّث دخلك المتوقع لـ2027 في حساب البدلات.</li><li><strong>من 1 ديسمبر</strong>: حضّر لصندوق الطاقة؛ التقديم <strong>4 يناير – 7 مايو 2027</strong>.</li><li>إجراءات الميزانية 2027 مقترحات حتى يقرها البرلمان.</li></ol>',
body=(
'<h2 id="calendar">التقويم</h2>'
+T([['12 نوفمبر 2026','نشر أقساط التأمين الأساسي 2027 (والتكميلي بعده بأسبوع تقريباً) — حسب مصادر القطاع'],['1 ديسمبر 2026','بدء التواصل والتحضير لصندوق الطاقة'],['31 ديسمبر 2026','آخر يوم لعقد تأمين صحي جديد يبدأ 1 يناير'],['4 يناير 2027','فتح صندوق الطاقة'],['يناير 2027','تصل الدفعة المؤقتة للضرائب (voorlopige aanslag) لمن طلبها'],['7 مايو 2027','آخر يوم لصندوق الطاقة']],['التاريخ','ماذا تفعل'])
+'<h2 id="zorg">1. التأمين الصحي</h2><ul><li>قارن بعد نشر الأسعار؛ الحكومة تقدّر متوسط القسط 2027 بنحو 169 يورو شهرياً (تقدير، يختلف حسب الشركة).</li><li>إن عقدت تأميناً جديداً قبل 31 ديسمبر، الشركة الجديدة تلغي القديم تلقائياً.</li><li><strong>المساهمة الذاتية (eigen risico) 2027</strong>: اقترحت الحكومة رفعها من 385 إلى 400 يورو، لكن ذلك يحتاج موافقة البرلمان — تابع <a href="/articles/prinsjesdag-2026-changes.html">مقالة تغييرات الميزانية</a>.</li><li>إن كانت مصاريفك الصحية كثيرة، فكّر في تأمين تكميلي مناسب. التفاصيل في <a href="/articles/health-insurance-2027.html">دليل التأمين الصحي 2027</a>.</li></ul>'
'<h2 id="toeslagen">2. البدلات</h2><ul><li>أدخل دخلك المتوقع لـ2027 (وليس 2026) في Mijn toeslagen، وكذلك تغييرات الشريك أو السكن أو الأطفال.</li><li>استخدم <a href="https://www.belastingdienst.nl/wps/wcm/connect/nl/toeslagen/content/hulpmiddel-proefberekening-toeslagen" target="_blank" rel="noopener">الحسبة التجريبية</a>.</li><li>المصادر الإعلامية تتوقع ارتفاع الحد الأقصى لبدل الرعاية في 2027، والأرقام الرسمية تُنشر لاحقاً.</li><li>انتبه: الحكومة أجّلت بعض التغييرات في البدلات والإعانات سنة واحدة.</li><li>تفاصيل: <a href="/articles/toeslagen-income-update.html">تحديث الدخل في البدلات</a>.</li></ul>'
'<h2 id="tax">3. الضرائب</h2><ul><li>الدفعة المؤقتة (voorlopige aanslag) تطلبها مرة وتتكرر سنوياً؛ يمكنك تعديلها أو إيقافها في أي وقت — عدّلها إن تغيّر دخلك حتى لا تُطالَب بمبلغ كبير لاحقاً.</li><li>مقترحات خطة الضرائب 2027: خصم العمل (arbeidskorting) يرتفع 173 يورو، والشريحتان الأولى والثانية تنخفضان 0.06 نقطة.</li><li>من 2028 يُلغى خصم المصاريف الصحية الخاصة (مقترح).</li><li>إقرار 2026 يُقدَّم من مارس 2027: <a href="/articles/annual-tax-return-2026.html">الدليل</a>.</li></ul>'
'<h2 id="energy">4. الطاقة</h2><ul><li>صندوق الطاقة: <a href="/articles/energy-emergency-fund-2027.html">الشروط والحساب</a>.</li><li>إن انتهى عقدك قريباً: <a href="/articles/energy-contracts-saving-2026.html">قارن العقود</a>.</li></ul>'
'<h2 id="housing">5. السكن</h2><ul><li>من 1 يناير 2027 قانون جديد يوسّع صلاحيات لجنة الإيجار. راجع <a href="/articles/tenant-rights-netherlands.html">حقوق المستأجر</a>.</li><li>ضرائب البلدية لـ2027 تصل في أوائل السنة؛ إن كان دخلك منخفضاً اطلب <a href="/articles/municipal-taxes-exemption-kwijtschelding.html">الإعفاء</a> حسب مواعيد بلديتك.</li></ul>'
'<h2 id="examples">أمثلة (توضيحية)</h2>'
+T([['أسرة سمير، دخلها سيرتفع 2027 بعمل جديد','تحدّث الدخل المتوقع في البدلات في ديسمبر لتجنب استرداد كبير في 2028'],['منى، تدفع تأميناً تكميلياً لا تستخدمه','تقارن في نوفمبر وتلغيه أو تغيّره قبل 31 ديسمبر'],['خالد، دخل منخفض وفاتورة طاقة عالية','يجمع أوراقه في ديسمبر ويقدّم لصندوق الطاقة في يناير']],['الحالة','الإجراء'])
+'<p>أمثلة توضيحية وليست أشخاصاً حقيقيين.</p>'
'<h2 id="checklist">القائمة النهائية</h2><ol><li>☐ قارنت التأمين الصحي.</li><li>☐ حدّثت دخل 2027 في البدلات.</li><li>☐ راجعت الدفعة المؤقتة للضرائب.</li><li>☐ جهّزت أوراق صندوق الطاقة.</li><li>☐ راجعت عقد الطاقة والإيجار.</li><li>☐ سجّلت في بوابة السكن الاجتماعي إن لم تفعل: <a href="/articles/social-housing-sociale-huurwoning.html">الدليل</a>.</li></ol>'),
faq=[('متى آخر موعد لتغيير التأمين الصحي؟','31 ديسمبر 2026 لعقد يبدأ 1 يناير 2027.'),('كم المساهمة الذاتية 2027؟','مقترح الحكومة 400 يورو (حالياً 385)، بانتظار موافقة البرلمان.'),('هل أحدّث دخلي في البدلات؟','نعم، أدخل دخل 2027 المتوقع لتجنب الاسترداد.'),('متى صندوق الطاقة؟','التقديم من 4 يناير حتى 7 مايو 2027.'),('هل الحد الأدنى للأجور 2027 معروف؟','عند كتابة المقال لم يُنشر الرقم الرسمي بعد.')],
src_note='راجعنا Rijksoverheid في 5 أكتوبر 2026. أرقام الميزانية 2027 مقترحات قد تتغير، وبعض التقديرات من مصادر إعلامية وقطاعية. الأمثلة توضيحية.')
NL=dict(title='Checklist jaareinde 2026: wat regel je vóór 31 december en in januari 2027 (zorgverzekering, toeslagen, belasting, energie)',
crumb='Checklist jaareinde',
desc='Praktische checklist op datum voor huishoudens: zorgverzekering overstappen vóór 31 december, inkomen 2027 doorgeven bij Toeslagen, voorlopige aanslag, Noodfonds Energie vanaf 1 december en de plannen voor 2027 — met voorbeelden en FAQ.',
summary='<ol><li><strong>12 november</strong>: premies 2027 bekend — vergelijk.</li><li><strong>Vóór 31 december</strong>: overstappen zorgverzekering (nieuwe verzekeraar zegt op).</li><li><strong>December</strong>: inkomen 2027 doorgeven bij Toeslagen.</li><li><strong>Vanaf 1 december</strong>: voorbereiden Noodfonds; aanvragen <strong>4 januari – 7 mei 2027</strong>.</li><li>Begrotingsmaatregelen 2027 zijn voorstellen tot het parlement beslist.</li></ol>',
body=(
'<h2 id="calendar">Kalender</h2>'
+T([['12 november 2026','Basispremies 2027 bekend (aanvullend ca. een week later) — volgens sectorbronnen'],['1 december 2026','Noodfonds: voorbereiden en contact'],['31 december 2026','Laatste dag nieuwe zorgverzekering per 1 januari'],['4 januari 2027','Noodfonds open'],['Januari 2027','Voorlopige aanslag (als aangevraagd)'],['7 mei 2027','Noodfonds sluit']],['Datum','Actie'])
+'<h2 id="zorg">1. Zorgverzekering</h2><ul><li>Kabinet schat de gemiddelde premie 2027 op ca. € 169 per maand (indicatief).</li><li>Sluit je vóór 31 december af, dan zegt de nieuwe verzekeraar de oude op.</li><li><strong>Eigen risico 2027</strong>: kabinet stelt € 400 voor (nu € 385); parlement moet nog instemmen — zie <a href="/nl/articles/prinsjesdag-2026-changes.html">Prinsjesdag-artikel</a>.</li><li>Meer: <a href="/nl/articles/health-insurance-2027.html">zorgverzekering 2027</a>.</li></ul>'
'<h2 id="toeslagen">2. Toeslagen</h2><ul><li>Geef je verwachte inkomen 2027 door in Mijn toeslagen, plus wijzigingen partner, wonen, kinderen.</li><li>Gebruik de <a href="https://www.belastingdienst.nl/wps/wcm/connect/nl/toeslagen/content/hulpmiddel-proefberekening-toeslagen" target="_blank" rel="noopener">proefberekening</a>.</li><li>Media verwachten een hogere maximale zorgtoeslag in 2027; officiële bedragen volgen.</li><li>Het kabinet stelt sommige wijzigingen in uitkeringen en toeslagen een jaar uit.</li><li><a href="/nl/articles/toeslagen-income-update.html">Inkomen wijzigen</a>.</li></ul>'
'<h2 id="tax">3. Belasting</h2><ul><li>Voorlopige aanslag: één keer aanvragen, jaarlijks opnieuw; altijd te wijzigen of stoppen.</li><li>Belastingplan 2027 (voorstel): arbeidskorting +€ 173, schijven 1 en 2 −0,06 procentpunt.</li><li>Vanaf 2028 vervalt de aftrek specifieke zorgkosten (voorstel).</li><li><a href="/nl/articles/annual-tax-return-2026.html">Aangifte 2026</a>.</li></ul>'
'<h2 id="energy">4. Energie</h2><ul><li><a href="/nl/articles/energy-emergency-fund-2027.html">Noodfonds Energie</a>.</li><li><a href="/nl/articles/energy-contracts-saving-2026.html">Energiecontract vergelijken</a>.</li></ul>'
'<h2 id="housing">5. Wonen</h2><ul><li>Per 1 januari 2027 nieuwe wet Huurcommissie: zie <a href="/nl/articles/tenant-rights-netherlands.html">huurrechten</a>.</li><li>Gemeentelijke belastingen 2027: <a href="/nl/articles/municipal-taxes-exemption-kwijtschelding.html">kwijtschelding</a> volgens termijnen van je gemeente.</li></ul>'
'<h2 id="examples">Voorbeelden (illustratief)</h2>'
+T([['Gezin Samir, hoger inkomen in 2027','Inkomen in december aanpassen om grote terugvordering te voorkomen'],['Mona, ongebruikte aanvullende verzekering','In november vergelijken, vóór 31 december wijzigen'],['Khalid, laag inkomen, hoge energierekening','Papieren in december klaarzetten, in januari aanvragen']],['Situatie','Actie'])
+'<p>Illustratieve voorbeelden, geen echte personen.</p>'
'<h2 id="checklist">Checklist</h2><ol><li>☐ Zorgverzekering vergeleken.</li><li>☐ Inkomen 2027 bij Toeslagen.</li><li>☐ Voorlopige aanslag gecontroleerd.</li><li>☐ Noodfonds-papieren klaar.</li><li>☐ Energie- en huurcontract gecheckt.</li><li>☐ Ingeschreven voor <a href="/nl/articles/social-housing-sociale-huurwoning.html">sociale huur</a>.</li></ol>'),
faq=[('Uiterste datum overstappen?','31 december 2026 voor een polis per 1 januari 2027.'),('Eigen risico 2027?','Voorstel € 400 (nu € 385), parlement moet nog beslissen.'),('Inkomen doorgeven bij Toeslagen?','Ja, je verwachte inkomen 2027.'),('Wanneer Noodfonds?','4 januari t/m 7 mei 2027.'),('Minimumloon 2027 bekend?','Bij schrijven nog niet officieel gepubliceerd.')],
src_note='Gecontroleerd bij Rijksoverheid op 5 oktober 2026. Begrotingscijfers 2027 zijn voorstellen; sommige schattingen uit media/sectorbronnen. Voorbeelden illustratief.')
