from a_student_finance import T
SLUG='zero-hours-contract'
SRC=[('Rijksoverheid · Welke contracten zijn er voor oproepkrachten?','https://www.rijksoverheid.nl/vraag-en-antwoord/arbeidsovereenkomst-en-cao/welke-contracten-zijn-er-voor-oproepkrachten'),
('Rijksoverheid · Zijn nulurencontracten verboden?','https://www.rijksoverheid.nl/vraag-en-antwoord/arbeidsovereenkomst-en-cao/worden-nulurencontracten-verboden'),
('Rijksoverheid · Wanneer krijg ik recht op een vast aantal arbeidsuren per week?','https://www.rijksoverheid.nl/vraag-en-antwoord/arbeidsovereenkomst-en-cao/wanneer-verandert-mijn-oproepcontract-in-een-vast-dienstverband'),
('Rijksoverheid · Krijg ik als oproepkracht ook loon als ik ziek ben?','https://www.rijksoverheid.nl/vraag-en-antwoord/ziekteverzuim-van-het-werk/krijg-ik-als-oproepkracht-ook-loon-als-ik-ziek-ben'),
('Rijksoverheid · Wet arbeidsmarkt in balans (WAB): wat is er veranderd','https://www.rijksoverheid.nl/themas/werk/arbeidsovereenkomst-en-cao/plannen-kabinet-voor-meer-balans-tussen-vast-werk-en-flexwerk'),
('Rijksoverheid · Hoe hoog is mijn vakantiegeld?','https://www.rijksoverheid.nl/vraag-en-antwoord/vakantiedagen-en-vakantiegeld/hoe-hoog-is-mijn-vakantiegeld'),
('Rijksoverheid · Wat staat er in een arbeidsovereenkomst?','https://www.rijksoverheid.nl/vraag-en-antwoord/arbeidsovereenkomst-en-cao/wat-staat-er-in-een-arbeidsovereenkomst'),
('Rijksoverheid · Meer zekerheid voor mensen met een flexcontract (7-7-2026)','https://www.rijksoverheid.nl/actueel/nieuws/2026/07/08/meer-zekerheid-voor-mensen-met-een-flexcontract')]

AR=dict(title='عقد الاستدعاء وعقد صفر ساعات في هولندا 2026: مهلة الـ4 أيام، 3 ساعات أجر لكل استدعاء، وحقك في ساعات ثابتة بعد 12 شهراً',
crumb='عقد الاستدعاء (0 ساعات)',
desc='دليل عميق لعقود الاستدعاء (oproepcontract) في هولندا: الأنواع الثلاثة، متى يجوز عقد صفر ساعات، مهلة الاستدعاء 4 أيام، الحد الأدنى 3 ساعات أجر، عرض الساعات الثابتة بعد 12 شهراً، قاعدة متوسط 3 أشهر، المرض والإجازة، وما يتغير في 2028.',
summary='<ol><li><strong>عقد الاستدعاء</strong> يعني أنك تعمل «عند الطلب» بلا ساعات ثابتة أو بحد أدنى صغير. له 3 أشكال: عقد إطاري، صفر ساعات، وmin-max.</li><li><strong>مهلة الاستدعاء 4 أيام على الأقل.</strong> إن استدعاك صاحب العمل بمهلة أقصر فلك أن ترفض دون عقوبة. وإن ألغى الاستدعاء أو غيّر وقته قبل أقل من 4 أيام يدفع لك أجر الساعات المخطط لها.</li><li><strong>كل استدعاء = 3 ساعات أجر على الأقل</strong> إن كانت ساعاتك غير ثابتة أو أقل من 15 ساعة أسبوعياً وأوقاتها غير محددة، حتى لو عملت أقل.</li><li><strong>بعد 12 شهراً</strong> يجب على صاحب العمل أن يعرض عليك عقداً بعدد ساعات ثابت يساوي على الأقل متوسط ما عملته في آخر 12 شهراً، ويكرر العرض كل 12 شهراً.</li><li><strong>قاعدة متوسط 3 أشهر:</strong> إن استمر عقدك 3 أشهر على الأقل يُفترض قانوناً أن ساعات عقدك تساوي متوسط تلك الأشهر، وعلى صاحب العمل إثبات العكس.</li><li><strong>عقد صفر ساعات</strong> مسموح في أول 26 أسبوعاً؛ بعدها فقط إذا سمح الـCAO وللعمل العرضي.</li></ol>',
body=(
'<h2 id="what">ما هو عقد الاستدعاء ولمن يناسب؟</h2><p>عقد الاستدعاء (oproepcontract) هو عقد عمل لا يحدد عدد ساعات ثابتاً، أو يحدد حداً أدنى صغيراً، ويطلبك صاحب العمل «عند الحاجة». ينتشر في المطاعم، والتوزيع، والمستودعات، والتنظيف، والرعاية، والتجزئة، وغالباً مع الطلاب والقادمين الجدد. ليس عقداً «من الدرجة الثانية»: هو عقد عمل كامل، لك فيه الحد الأدنى للأجر، والإجازة، وبدل العطلة، والحماية في المرض، لكن بقواعد إضافية خاصة لأن دخلك غير مستقر.</p>'
+T([['عقد إطاري (voorovereenkomst)','اتفاق مسبق بأن صاحب العمل قد يستدعيك. لا تلتزم بالحضور، ولا يلتزم هو بالاستدعاء. كل مرة تقبل فيها يُنشأ عقد عمل قصير منفصل.','الأكثر مرونة والأقل حماية. انتبه: كل استدعاء قد يُعد عقداً مؤقتاً يُحسب في سلسلة العقود.'],
    ['عقد صفر ساعات (nulurencontract)','عقد عمل حقيقي بلا ساعات مضمونة. يجب أن تحضر إن استُدعيت بشكل صحيح، ويُدفع لك فقط عن الساعات التي تعملها.','مسموح فقط أول 26 أسبوعاً، إلا إذا سمح الـCAO بأكثر لعمل عرضي.'],
    ['عقد min-max','عقد بحد أدنى مضمون (مثلاً 12 ساعة أسبوعياً) وحد أقصى (مثلاً 32). تُدفع الساعات المضمونة دائماً، والإضافية عند الاستدعاء.','أكثر أماناً: الساعات الدنيا مدفوعة حتى لو لم تُستدعَ.']],
   ['النوع','كيف يعمل','ما يجب أن تعرفه'])
+'<p><strong>كيف تعرف نوع عقدك؟</strong> ابحث في العقد عن كلمات: «oproep»، «nul uren»، «minimaal … uur»، «maximaal … uur»، «voorovereenkomst». إن لم يُذكر عدد ساعات أو ذُكرت ساعات غير محددة فأنت غالباً «oproepkracht». يجب أن يخبرك صاحب العمل كتابياً خلال أسبوع من البدء بعدد الساعات، ومتى يمكن استدعاؤك (الأيام والساعات المرجعية).</p>'
'<h2 id="nulturen">هل عقد صفر ساعات ممنوع؟</h2><p>لا. لكنه مقيد:</p><ul><li>في <strong>أول 26 أسبوعاً</strong> من العقد يجوز.</li><li>بعد 26 أسبوعاً يجوز فقط إذا نص <strong>الـCAO</strong> على ذلك، وللعمل <strong>العرضي (incidenteel)</strong> الذي لا يمكن تحديد حجمه مسبقاً.</li><li>إن لم يتوفر ذلك فلا يجوز أن تبقى بلا ساعات: اسأل صاحب العمل عن تحويل العقد إلى min-max أو ساعات ثابتة، واستخدم قاعدة متوسط 3 أشهر (أدناه).</li></ul>'
'<h2 id="4days">قاعدة الـ4 أيام: الاستدعاء والإلغاء</h2><p>هذه أهم قاعدة لعامل الاستدعاء، أُدخلت بقانون WAB منذ 2020:</p>'
+T([['صاحب العمل يستدعيك بمهلة 4 أيام أو أكثر','يجب أن تحضر (في عقد صفر ساعات وmin-max)، ضمن الأيام والأوقات المرجعية المكتوبة.'],
    ['يستدعيك بمهلة أقل من 4 أيام','<strong>لا تلتزم بالحضور.</strong> يمكنك الرفض دون أي عقوبة أو أثر على عقدك.'],
    ['يلغي الاستدعاء أو يغير الوقت قبل أقل من 4 أيام','<strong>يدفع لك أجر الساعات التي كانت مخططة</strong> كأنك عملتها.'],
    ['الـCAO ينص على مهلة أقصر','قد تُخفّض المهلة إلى <strong>يوم واحد</strong> على الأقل إن نص الـCAO على ذلك. تحقق من الـCAO.']],
   ['الحالة','النتيجة'])
+'<p><strong>نصيحة عملية:</strong> احتفظ بكل رسائل الاستدعاء والإلغاء (واتساب، تطبيق الجدولة، البريد) مع تاريخ ووقت الإرسال. هي دليلك إن طالبت بأجر الإلغاء.</p>'
'<h2 id="3hours">الحد الأدنى 3 ساعات أجر لكل استدعاء</h2><p>إذا كان عقدك <strong>أقل من 15 ساعة أسبوعياً وأوقات العمل غير محددة</strong>، أو بلا ساعات ثابتة، فلك عن كل استدعاء أجر <strong>3 ساعات على الأقل</strong>، حتى لو أرسلك صاحب العمل إلى البيت بعد ساعة.</p>'
+T([['استُدعيت وعملت ساعة واحدة','تُدفع 3 ساعات'],
    ['استُدعيت وعملت 2.5 ساعة','تُدفع 3 ساعات'],
    ['عملت 5 ساعات','تُدفع 5 ساعات'],
    ['استُدعيت مرتين في اليوم نفسه بفاصل','كل استدعاء له حد أدنى 3 ساعات']],
   ['المثال','ما يُدفع'])
+'<p>استثناء: إن كان العقد يحدد عدد الساعات ومواعيدها بدقة فلا تنطبق هذه القاعدة بالطريقة نفسها.</p>'
'<h2 id="12months">بعد 12 شهراً: عرض إلزامي بساعات ثابتة</h2><p>إن بقيت عامل استدعاء <strong>12 شهراً</strong>، يجب على صاحب العمل <strong>خلال الشهر التالي</strong> أن يعرض عليك عقداً بعدد ساعات ثابت يساوي على الأقل <strong>متوسط ساعاتك الشهرية في آخر 12 شهراً</strong>.</p><ul><li>أنت حر في القبول أو الرفض. إن رفضت تبقى بعقد الاستدعاء.</li><li>يجب أن يكرر صاحب العمل العرض <strong>كل 12 شهراً</strong>.</li><li>إن لم يقدم العرض في وقته: لك المطالبة <strong>بأجر الساعات التي كان يجب عرضها</strong> عن الفترة التي تأخر فيها.</li><li>في الإجازة والمرض: الساعات الثابتة الجديدة هي أساس أجرك.</li></ul>'
+T([['شهر 1–3','40 ساعة/شهر'],['شهر 4–6','60 ساعة/شهر'],['شهر 7–9','80 ساعة/شهر'],['شهر 10–12','60 ساعة/شهر'],['المتوسط','(120+180+240+180) ÷ 12 = <strong>60 ساعة شهرياً</strong> ← هذا الحد الأدنى للعرض']],
   ['الفترة (مثال)','ساعات العمل'])
+'<h2 id="3months">قاعدة متوسط 3 أشهر (rechtsvermoeden arbeidsomvang)</h2><p>هذه قاعدة مستقلة عن عرض الـ12 شهراً، وتفيدك إن كان عملك منتظماً:</p><ul><li>إن كان عقدك قائماً <strong>3 أشهر على الأقل</strong>، يُفترض قانوناً أن ساعات عقدك تساوي <strong>متوسط ساعاتك في آخر 3 أشهر</strong>.</li><li>يمكنك المطالبة بهذا كتابياً من صاحب العمل، وعليه هو أن يثبت أن الافتراض غير صحيح (مثلاً: كان ذلك موسم ذروة استثنائياً).</li><li>إن رفض، يمكنك اللجوء للقاضي (kantonrechter). استشر Juridisch Loket أو نقابتك قبل ذلك.</li></ul>'
'<h2 id="pay">الأجر والإجازة وبدل العطلة</h2><ul><li><strong>الحد الأدنى للأجر بالساعة</strong> ينطبق عليك كاملاً، حسب عمرك (<a href="/articles/minimum-wage-netherlands.html">جدول الحد الأدنى</a>).</li><li><strong>الإجازة:</strong> 4 أضعاف ساعاتك الأسبوعية سنوياً. بما أن ساعاتك متغيرة، تُبنى الإجازة على الساعات التي تعملها فعلاً. كثير من أصحاب العمل يدفعون «إجازة» كنسبة مئوية مع كل راتب؛ اسأل كيف تُحسب وتأكد أنها ظاهرة على <a href="/articles/dutch-payslip-explained.html">قسيمة الراتب</a>.</li><li><strong>بدل العطلة:</strong> 8% على الأقل من أجرك الإجمالي.</li><li><strong>العطل الرسمية والعمل الإضافي:</strong> حسب الـCAO أو العقد؛ القانون لا يفرض زيادة عامة.</li></ul>'
'<h2 id="sick">المرض في عقد الاستدعاء</h2>'
+T([['صفر ساعات: مرضت خلال فترة استدعاء متفق عليها','أجر 70% على الأقل عن تلك الفترة (والحد الأدنى للأجر في السنة الأولى).'],
    ['صفر ساعات: مرضت ولم يكن هناك استدعاء','لا يلتزم صاحب العمل تلقائياً بالدفع؛ لكن إن عملت 3 أشهر أو أكثر بانتظام، اطلب الأجر على أساس متوسط ساعاتك (قاعدة الـ3 أشهر).'],
    ['min-max','70% على الأقل عن <strong>الساعات المضمونة</strong> دائماً، ومع حد أدنى للأجر في السنة الأولى. وقد تطالب بأكثر إن كنت تعمل عادة فوق الحد الأدنى.'],
    ['عقد إطاري','لا يوجد عقد بين الاستدعاءات؛ قد تحتاج إعانة Ziektewet من UWV.']],
   ['الحالة','ما الذي تحصل عليه'])
+'<p>أبلغ عن المرض فوراً بالطريقة المكتوبة في نظام الشركة، واحتفظ بإثبات. إن انتهى عقدك وأنت مريض: يُبلغ صاحب العمل UWV وقد تستحق Ziektewet.</p>'
'<h2 id="end">إنهاء عقد الاستدعاء</h2><ul><li>في عقد <strong>صفر ساعات</strong>: مهلة إنذار صاحب العمل <strong>4 أيام</strong> على الأقل. إن أنهى دون ذلك بلا سبب، اطلب أجر الأيام.</li><li>في min-max أو عقد مؤقت: تنطبق المهل العامة (<a href="/articles/employment-contracts-labor-law-2026.html">دليل عقد العمل</a>).</li><li>إن لم يُجدد العقد بمبادرة صاحب العمل فقد تستحق <strong>transitievergoeding</strong> (ثلث راتب شهري عن كل سنة، يُحسب بمتوسط أجرك).</li><li>عقود الاستدعاء المتتالية تدخل في <strong>سلسلة العقود</strong>: أكثر من 3 عقود أو أكثر من 3 سنوات = عقد دائم (غالباً بساعات المتوسط).</li></ul>'
'<h2 id="toeslagen">الدخل المتغير والبدلات</h2><p>الدخل غير الثابت يسبب أكبر مشكلة لعمال الاستدعاء: استرداد البدلات. اجمع رواتب الأشهر الماضية، قدّر دخلك السنوي <strong>بشكل أعلى قليلاً</strong> وليس أقل، وحدّث التقدير كلما تغير عملك (<a href="/articles/toeslagen-income-update.html">كيف تحدّث دخلك في Toeslagen</a>). إن كان لك عملان، طبّق loonheffingskorting عند صاحب عمل واحد فقط.</p>'
'<h2 id="checklist">قائمة تحقق لعامل الاستدعاء</h2><ol><li>ما نوع عقدي: إطاري، صفر ساعات، أم min-max؟</li><li>ما الأيام والساعات المرجعية التي يمكن استدعائي فيها (مكتوبة)؟</li><li>هل ينص الـCAO على مهلة استدعاء أقصر من 4 أيام؟</li><li>هل أحصل على 3 ساعات على الأقل لكل استدعاء؟</li><li>كم ساعة متوسطي في آخر 3 أشهر و12 شهراً؟ (احفظ جدولاً)</li><li>هل حصلت على العرض الإلزامي بعد 12 شهراً؟</li><li>هل الإجازة وبدل العطلة 8% ظاهران في القسيمة؟</li><li>هل تجاوزت 26 أسبوعاً بعقد صفر ساعات بلا CAO يسمح بذلك؟</li></ol>'
'<h2 id="mistakes">أخطاء شائعة</h2><ul><li><strong>قبول الحضور بمهلة يوم واحد خوفاً من خسارة العمل</strong> دون أن تعرف أن الرفض حقك (ما لم ينص الـCAO على غير ذلك).</li><li><strong>عدم المطالبة بأجر الإلغاء المتأخر.</strong></li><li><strong>عدم حفظ سجل الساعات</strong>؛ بدونه يصعب إثبات المتوسط.</li><li><strong>نسيان أن الإجازة حق</strong> حتى في عقد صفر ساعات.</li><li><strong>تقدير الدخل السنوي أقل من الواقع</strong> في البدلات ثم مفاجأة الاسترداد.</li></ul>'
'<h2 id="2028">ماذا يتغير في 2028؟</h2><p>أقر مجلس الشيوخ في <strong>7 يوليو 2026</strong> قانون Wet meer zekerheid flexwerkers، ويبدأ <strong>1 يناير 2028</strong>. أعلنت الحكومة أن <strong>عقود صفر ساعات ستُستبدل بعقد «النطاق» (bandbreedtecontract)</strong>: عقد بحد أدنى وحد أقصى للساعات، بهدف إعطاء العامل دخلاً أكثر قابلية للتوقع. التفاصيل التطبيقية تصدر لاحقاً، وحتى ذلك التاريخ تبقى القواعد الحالية في هذا الدليل سارية. سنحدّث الصفحة عند صدورها.</p>'),
faq=[('هل يجب أن أحضر إذا اتصلوا بي اليوم للعمل غداً؟','لا، إن كانت المهلة أقل من 4 أيام فلك الرفض دون عقوبة، ما لم ينص الـCAO على مهلة أقصر (يوم واحد على الأقل).'),
('ألغوا مناوبتي قبل يومين، هل أستحق أجراً؟','نعم. الإلغاء أو تغيير الوقت قبل أقل من 4 أيام يعني أن يُدفع لك أجر الساعات المخططة.'),
('عملت ساعة واحدة فقط ثم أرسلوني للبيت، كم يُدفع لي؟','3 ساعات على الأقل، إن كانت ساعات عقدك غير ثابتة أو أقل من 15 ساعة أسبوعياً بلا أوقات محددة.'),
('متى أحصل على عقد بساعات ثابتة؟','بعد 12 شهراً يجب أن يعرض عليك صاحب العمل ساعات ثابتة تساوي متوسط آخر 12 شهراً على الأقل، ويكرر العرض كل سنة. ويمكنك أيضاً الاستناد إلى متوسط آخر 3 أشهر إن كان عملك منتظماً.'),
('هل لي إجازة وبدل عطلة في عقد صفر ساعات؟','نعم: إجازة بقدر 4 أضعاف ساعاتك الأسبوعية سنوياً، وبدل عطلة 8% على الأقل.'),
('هل ستُلغى عقود صفر ساعات؟','حسب القانون الذي أُقر في يوليو 2026 تُستبدل بعقد النطاق (bandbreedtecontract) من 1 يناير 2028. حتى ذلك الحين تبقى القواعد الحالية.')],
src_note='راجعنا كل القواعد في صفحات Rijksoverheid في 4 أكتوبر 2026. الـCAO قد يغيّر بعض القواعد (مثل مهلة الاستدعاء). هذا دليل توعوي وليس استشارة قانونية؛ في النزاع اتصل بـJuridisch Loket أو نقابتك.')

NL=dict(title='Oproepcontract en nulurencontract 2026: 4 dagen oproeptermijn, minimaal 3 uur loon per oproep en vaste uren na 12 maanden',
crumb='Oproepcontract (0 uren)',
desc='Uitgebreide gids voor oproepkrachten: de drie soorten oproepcontracten, wanneer een nulurencontract mag, 4 dagen oproeptermijn, minimaal 3 uur loon per oproep, aanbod vaste uren na 12 maanden, het rechtsvermoeden van 3 maanden, ziekte en vakantie, en wat er in 2028 verandert.',
summary='<ol><li><strong>Oproepcontract:</strong> je werkt op afroep, zonder vaste uren of met een klein minimum. Drie vormen: voorovereenkomst, nulurencontract en min-maxcontract.</li><li><strong>Oproeptermijn minimaal 4 dagen.</strong> Word je korter van tevoren opgeroepen, dan hoef je niet te komen. Trekt de werkgever een oproep binnen 4 dagen in of verschuift hij de tijd, dan krijg je het loon voor de geplande uren.</li><li><strong>Minimaal 3 uur loon per oproep</strong> bij minder dan 15 uur per week zonder vaste tijden, of zonder vaste uren.</li><li><strong>Na 12 maanden</strong> moet de werkgever je een contract aanbieden met minimaal het gemiddelde aantal uren van de afgelopen 12 maanden, en dat elk jaar herhalen.</li><li><strong>Rechtsvermoeden:</strong> duurt je contract minimaal 3 maanden, dan wordt vermoed dat je arbeidsomvang gelijk is aan het gemiddelde van die 3 maanden.</li><li><strong>Nulurencontract</strong> mag de eerste 26 weken; daarna alleen als de cao het toestaat bij incidenteel werk.</li></ol>',
body=(
'<h2 id="what">Wat is een oproepcontract?</h2><p>Bij een oproepcontract staat er geen vast aantal uren in je contract, of alleen een klein minimum, en roept de werkgever je op als er werk is. Het komt veel voor in horeca, logistiek, schoonmaak, zorg en retail, vaak bij studenten en nieuwkomers. Het is een volwaardig arbeidscontract: je hebt recht op minimumloon, vakantie, vakantiegeld en loon bij ziekte, met extra regels omdat je inkomen onzeker is.</p>'
+T([['Voorovereenkomst','Afspraak dat de werkgever je kan oproepen. Je bent niet verplicht te komen en hij niet om op te roepen. Elke keer dat je ja zegt, ontstaat een kort arbeidscontract.','Meest flexibel, minste bescherming. Elke oproep kan meetellen in de ketenregeling.'],
    ['Nulurencontract','Echt arbeidscontract zonder gegarandeerde uren. Bij een juiste oproep moet je komen; je krijgt alleen betaald voor gewerkte uren.','Alleen de eerste 26 weken, tenzij de cao langer toestaat bij incidenteel werk.'],
    ['Min-maxcontract','Contract met gegarandeerd minimum (bijv. 12 uur) en maximum (bijv. 32 uur). Het minimum wordt altijd betaald.','Zekerder: de minimumuren krijg je ook als je niet wordt opgeroepen.']],
   ['Soort','Hoe het werkt','Let op'])
+'<p><strong>Welk contract heb jij?</strong> Zoek in je contract naar «oproep», «nul uren», «minimaal … uur», «maximaal … uur» of «voorovereenkomst». De werkgever moet je binnen een week na indiensttreding schriftelijk laten weten hoeveel uren je werkt en op welke dagen en uren je kunt worden opgeroepen (referentiedagen en -uren).</p>'
'<h2 id="nulturen">Zijn nulurencontracten verboden?</h2><ul><li>Nee. De <strong>eerste 26 weken</strong> mag een nulurencontract.</li><li>Na 26 weken alleen als de <strong>cao</strong> dat toestaat, voor <strong>incidenteel</strong> werk waarvan de omvang niet vooraf vast te stellen is.</li><li>Zo niet: vraag om een min-max- of vasteurencontract en beroep je op het rechtsvermoeden (hieronder).</li></ul>'
'<h2 id="4days">De 4-dagenregel: oproepen en afzeggen</h2>'
+T([['Oproep 4 dagen of meer van tevoren','Je moet komen (bij nuluren en min-max), binnen de schriftelijke referentiedagen en -uren.'],
    ['Oproep minder dan 4 dagen van tevoren','<strong>Je hoeft niet te komen.</strong> Weigeren mag zonder gevolgen.'],
    ['Afzeggen of tijd wijzigen binnen 4 dagen','<strong>Je krijgt het loon voor de geplande uren.</strong>'],
    ['Cao met kortere termijn','De termijn kan bij cao worden verkort tot minimaal <strong>1 dag</strong>.']],
   ['Situatie','Gevolg'])
+'<p><strong>Tip:</strong> bewaar alle oproepen en afzeggingen (WhatsApp, rooster-app, e-mail) met datum en tijd. Dat is je bewijs.</p>'
'<h2 id="3hours">Minimaal 3 uur loon per oproep</h2><p>Werk je <strong>minder dan 15 uur per week zonder vastgelegde werktijden</strong>, of heb je geen vaste uren, dan krijg je per oproep minimaal <strong>3 uur loon</strong>, ook als je eerder naar huis wordt gestuurd.</p>'
+T([['Opgeroepen, 1 uur gewerkt','3 uur betaald'],['Opgeroepen, 2,5 uur gewerkt','3 uur betaald'],['5 uur gewerkt','5 uur betaald'],['Twee aparte oproepen op één dag','Per oproep minimaal 3 uur']],['Voorbeeld','Betaling'])
+'<h2 id="12months">Na 12 maanden: verplicht aanbod voor vaste uren</h2><p>Ben je <strong>12 maanden</strong> oproepkracht, dan moet de werkgever <strong>binnen een maand</strong> een vaste arbeidsomvang aanbieden van minimaal het <strong>gemiddelde aantal uren per maand over de afgelopen 12 maanden</strong>.</p><ul><li>Je mag het aanbod aannemen of weigeren.</li><li>De werkgever moet <strong>elke 12 maanden</strong> opnieuw een aanbod doen.</li><li>Doet hij dat niet op tijd, dan kun je <strong>loon over de uren die hij had moeten aanbieden</strong> claimen.</li></ul>'
+T([['Maand 1–3','40 uur/maand'],['Maand 4–6','60 uur/maand'],['Maand 7–9','80 uur/maand'],['Maand 10–12','60 uur/maand'],['Gemiddelde','(120+180+240+180) ÷ 12 = <strong>60 uur per maand</strong> = minimaal aanbod']],['Periode (voorbeeld)','Gewerkte uren'])
+'<h2 id="3months">Rechtsvermoeden arbeidsomvang (3 maanden)</h2><ul><li>Duurt je contract <strong>minimaal 3 maanden</strong>, dan wordt vermoed dat je arbeidsomvang gelijk is aan het <strong>gemiddelde van de afgelopen 3 maanden</strong>.</li><li>Je kunt dit schriftelijk claimen; de werkgever moet bewijzen dat het vermoeden niet klopt (bijvoorbeeld een uitzonderlijke piek).</li><li>Komt u er niet uit: kantonrechter. Vraag eerst advies aan het Juridisch Loket of je vakbond.</li></ul>'
'<h2 id="pay">Loon, vakantie en vakantiegeld</h2><ul><li>Het <strong>minimumuurloon</strong> geldt volledig (<a href="/nl/articles/minimum-wage-netherlands.html">bedragen minimumloon</a>).</li><li><strong>Vakantie:</strong> 4 keer je wekelijkse arbeidsduur per jaar, berekend over je gewerkte uren. Wordt vakantie als percentage uitbetaald, controleer dat op je <a href="/nl/articles/dutch-payslip-explained.html">loonstrook</a>.</li><li><strong>Vakantiegeld:</strong> minimaal 8% van je brutoloon.</li><li><strong>Feestdagen en overwerk:</strong> volgens cao of contract.</li></ul>'
'<h2 id="sick">Ziek als oproepkracht</h2>'
+T([['Nuluren, ziek tijdens afgesproken oproepperiode','Minimaal 70% over die periode (1e jaar minimaal minimumloon).'],
    ['Nuluren, ziek zonder oproep','Geen automatische verplichting; werk je 3 maanden of langer met een vast patroon, vraag loon over je gemiddelde uren.'],
    ['Min-max','Altijd minimaal 70% over je <strong>garantie-uren</strong>, in het 1e jaar minimaal het minimumloon.'],
    ['Voorovereenkomst','Tussen oproepen geen contract; mogelijk Ziektewet via UWV.']],['Situatie','Wat je krijgt'])
+'<h2 id="end">Einde van het oproepcontract</h2><ul><li><strong>Nulurencontract:</strong> opzegtermijn werkgever minimaal <strong>4 dagen</strong>.</li><li>Min-max en tijdelijk: de gewone regels (<a href="/nl/articles/employment-contracts-labor-law-2026.html">gids arbeidscontract</a>).</li><li>Bij niet-verlengen door de werkgever: mogelijk <strong>transitievergoeding</strong>.</li><li>Opeenvolgende oproepcontracten tellen mee in de <strong>ketenregeling</strong>.</li></ul>'
'<h2 id="toeslagen">Wisselend inkomen en toeslagen</h2><p>Schat je jaarinkomen liever iets te hoog dan te laag en pas de schatting aan zodra je werk verandert (<a href="/nl/articles/toeslagen-income-update.html">inkomen doorgeven bij Toeslagen</a>). Heb je twee banen: loonheffingskorting bij maar één werkgever.</p>'
'<h2 id="checklist">Checklist voor oproepkrachten</h2><ol><li>Welk soort contract heb ik?</li><li>Welke referentiedagen en -uren staan op papier?</li><li>Staat in de cao een kortere oproeptermijn?</li><li>Krijg ik minimaal 3 uur per oproep?</li><li>Wat is mijn gemiddelde over 3 en 12 maanden? (houd een urenlijst bij)</li><li>Heb ik na 12 maanden een aanbod gekregen?</li><li>Staan vakantie-uren en 8% vakantiegeld op mijn loonstrook?</li><li>Werk ik langer dan 26 weken op nuluren zonder cao-grondslag?</li></ol>'
'<h2 id="mistakes">Veelgemaakte fouten</h2><ul><li>Toch komen bij een oproep van vandaag op morgen uit angst, terwijl je mag weigeren.</li><li>Geen loon claimen bij late afzegging.</li><li>Geen urenregistratie bijhouden.</li><li>Denken dat je op nuluren geen vakantie hebt.</li><li>Je inkomen voor toeslagen te laag schatten.</li></ul>'
'<h2 id="2028">Wat verandert er in 2028?</h2><p>De Eerste Kamer stemde op <strong>7 juli 2026</strong> in met de Wet meer zekerheid flexwerkers, invoering per <strong>1 januari 2028</strong>. Volgens de overheid worden <strong>nulurencontracten vervangen door een bandbreedtecontract</strong> met een minimum en maximum aantal uren. Tot die datum gelden de huidige regels uit deze gids.</p>'),
faq=[('Moet ik komen als ik vandaag word opgeroepen voor morgen?','Nee, bij een oproep van minder dan 4 dagen mag je weigeren, tenzij je cao een kortere termijn (minimaal 1 dag) heeft.'),
('Mijn dienst werd 2 dagen van tevoren afgezegd. Krijg ik loon?','Ja, bij afzeggen of wijzigen binnen 4 dagen krijg je het loon voor de geplande uren.'),
('Ik werkte 1 uur en moest naar huis. Hoeveel krijg ik?','Minimaal 3 uur, als je minder dan 15 uur per week zonder vaste tijden of zonder vaste uren werkt.'),
('Wanneer krijg ik vaste uren?','Na 12 maanden moet de werkgever een vaste omvang aanbieden van minimaal het gemiddelde van de afgelopen 12 maanden, en dat elk jaar herhalen. Ook kun je je na 3 maanden beroepen op het rechtsvermoeden.'),
('Heb ik op een nulurencontract recht op vakantie?','Ja: 4 keer je wekelijkse arbeidsduur per jaar en minimaal 8% vakantiegeld.'),
('Verdwijnen nulurencontracten?','Volgens de wet van juli 2026 worden ze per 1 januari 2028 vervangen door een bandbreedtecontract.')],
src_note='Alle regels gecontroleerd op Rijksoverheid op 4 oktober 2026. Je cao kan afwijken (bijvoorbeeld de oproeptermijn). Dit is algemene informatie, geen juridisch advies; neem bij een conflict contact op met het Juridisch Loket of je vakbond.')
