from a_student_finance import T
SLUG='sick-pay-ziektewet-wia'
U='https://www.uwv.nl/nl/'
R='https://www.rijksoverheid.nl/'
SRC=[('UWV · Hoogte Ziektewet-uitkering',U+'ziek/ziektewet-uitkering/hoogte-zw'),('UWV · Ziek binnen 4 weken na einde dienstverband',U+'ziek/ziek-uit-dienst/4-weken'),('UWV · Ziek tijdens WW',U+'ww/ziek-tijdens-ww'),('UWV · Uitzendkracht ziek',U+'ziek/uitzend-oproep-flexibel-contract/uitzendkracht-ziek'),('UWV · Wachtdagen',U+'ziek/wachtdagen'),('UWV · Wat kunt u verwachten (Ziektewet)',U+'ziek/ziektewet-uitkering/verwachting-zw'),('UWV · Plan van aanpak',U+'ziek/loondoorbetaling/plan-van-aanpak'),('UWV · Maximum dagloon',U+'premies-bedragen/maximum-dagloon'),('Rijksoverheid · Recht op WIA',R+'vraag-en-antwoord/wia/wia-recht-op-uitkering'),('Rijksoverheid · Hoogte WIA',R+'onderwerpen/wia/vraag-en-antwoord/wia-hoogte-uitkering'),('UWV · WGA loongerelateerde uitkering',U+'wia/wga/loongerelateerde-uitkering'),('UWV · WIA aanvragen',U+'wia/wia-aanvragen'),('UWV · Vervroegde WIA',U+'wia/vervroegde-wia'),('UWV · Beslistermijn WIA 16 weken',U+'magazines-nieuwsbrieven/nieuwsbrief-werkgevers/beslistermijn-wia-verlengd-naar-16-weken'),('Rijksoverheid · Langer wachten op arbeidsongeschiktheidsuitkering (23-06-2026)',R+'actueel/nieuws/2026/06/23/meer-mensen-moeten-langer-wachten-op-arbeidsongeschiktheidsuitkering'),('UWV · Hoogte Wajong',U+'wajong/hoogte-wajong')]
AR=dict(title='المرض والعجز عن العمل في هولندا 2026: راتب المرض، قانون المرض (Ziektewet) و WIA خطوة بخطوة — مع أمثلة محسوبة',
crumb='المرض وWIA',
desc='دليل عميق: من يدفع لك عند المرض (صاحب العمل حتى سنتين بنسبة 70% على الأقل أو UWV عبر Ziektewet)، كيف تبلّغ، حساب 70% من الأجر اليومي بحد أقصى 309.91 يورو، الجدول الزمني حتى الأسبوع 104، ثم WIA (WGA وIVA)، مع أمثلة محسوبة وأسئلة شائعة.',
summary='<ol><li><strong>موظف بعقد:</strong> صاحب العمل يدفع حتى <strong>104 أسابيع</strong> بنسبة <strong>70% على الأقل</strong>.</li><li><strong>بدون صاحب عمل</strong> (انتهى العقد، WW، عامل مؤقت): <strong>Ziektewet</strong> من UWV = <strong>70%</strong> من الأجر اليومي (100% للحمل أو التبرع بعضو)، والحد الأقصى للأجر اليومي <strong>309.91 يورو</strong>.</li><li>بعد سنتين تقريباً: <strong>WIA</strong> — قدّم قبل الأسبوع 93؛ القرار حالياً قد يستغرق <strong>16 أسبوعاً</strong>.</li><li>WGA عند عجز 35–80%، وIVA عند 80% فأكثر بشكل دائم (75%).</li></ol>',
body=(
'<h2 id="who">من يدفع لك عند المرض؟</h2>'
+T([['موظف بعقد عمل','صاحب العمل (loondoorbetaling)','حتى 104 أسابيع، 70% على الأقل (غالباً 100% في السنة الأولى حسب CAO)'],['انتهى عقدك وأنت مريض أو خلال 4 أسابيع من انتهائه','UWV · Ziektewet','اتصل بـUWV بحلول اليوم الثاني للمرض'],['على إعانة البطالة WW','UWV','تستمر WW أول 13 أسبوعاً، ثم Ziektewet؛ بلّغ عبر Mijn UWV'],['عامل عبر وكالة مع uitzendbeding','UWV · Ziektewet','الوكالة تبلّغ بحلول اليوم الرابع'],['حامل/ولادة أو تبرع بعضو بلا صاحب عمل','UWV','100% من الأجر اليومي']],['وضعك','من يدفع','ملاحظات'])
+'<h2 id="amount">كم تحصل في Ziektewet؟</h2><ul><li><strong>70%</strong> من الأجر اليومي (dagloon)؛ المبلغ الأسبوعي = اليومي × 5، والشهري التقريبي × 21.75.</li><li>الحد الأقصى للأجر اليومي <strong>309.91 يورو</strong> ⇒ أقصى إعانة يومية نحو <strong>216.94 يورو</strong>.</li><li>أيام الانتظار (wachtdagen) 1–2 تُطبَّق فقط في حالات محددة يذكرها UWV.</li><li>أقصى مدة <strong>104 أسابيع</strong>.</li></ul>'
'<h2 id="examples">أمثلة محسوبة (توضيحية)</h2>'
+T([['ياسر، انتهى عقده المؤقت وهو مريض، أجر يومي 120 يورو','120 × 70% = 84 يورو/يوم ⇒ × 21.75 ≈ <strong>1,827 يورو إجمالي شهرياً</strong>'],['دينا، عاملة عبر وكالة، أجر يومي 95 يورو','95 × 70% = 66.50/يوم ⇒ ≈ <strong>1,446 يورو</strong> شهرياً'],['كريم، مهندس، أجر يومي 350 يورو','يُقيَّد بـ309.91 ⇒ 216.94/يوم ⇒ ≈ <strong>4,718 يورو</strong> شهرياً'],['سلمى، حامل، بلا صاحب عمل، أجر يومي 100','100% ⇒ 100 × 21.75 ≈ <strong>2,175 يورو</strong> شهرياً'],['عمر، موظف بعقد دائم، راتب 3,000','صاحب العمل يدفع على الأقل 70% = 2,100 (وفي الواقع غالباً 100% في السنة الأولى حسب CAO)، لا Ziektewet']],['الحالة','النتيجة'])
+'<p>الأسماء والأرقام أمثلة توضيحية، وليست حالات أشخاص حقيقيين. المبالغ إجمالية قبل الضريبة.</p>'
'<h2 id="timeline">الجدول الزمني لسنتي المرض</h2>'
+T([['اليوم 1–2','التبليغ عن المرض (لصاحب العمل أو لـUWV)'],['الأسبوع 6','طبيب الشركة يجري تحليل المشكلة (probleemanalyse) — للموظفين'],['الأسبوع 8','خطة العمل (plan van aanpak) خلال أسبوعين من التحليل؛ متابعة كل 6 أسابيع'],['الأسبوع 13','لدى Ziektewet: تحليل المشكلة من UWV خلال 13 أسبوعاً'],['الأسبوعان 26 و52 ونحو 78','تقييمات؛ بعد الأسبوع 44 قد يجري UWV فحص السنة الأولى (EZWb)'],['الأسبوع 88','رسالة WIA من UWV'],['قبل الأسبوع 93','قدّم طلب WIA'],['الأسبوع 104','تنتهي فترة المرض؛ يبدأ WIA إن قُبلت']],['التوقيت','ماذا يحدث'])
+'<h2 id="wia">WIA: بعد سنتين</h2>'
+T([['WGA','عجز 35–80%، أو 80%+ مع احتمال تحسن','loongerelateerd: 75% أول شهرين ثم 70%، لمدة 3 أشهر حتى سنتين حسب سجل العمل، ثم حسب ما تكسبه'],['IVA','80%+ ودائم','75% على الأقل من أجر WIA الشهري حتى سن التقاعد'],['أقل من 35%','لا إعانة WIA','تبقى عند صاحب العمل أو تبحث عن عمل/WW']],['النوع','لمن','المبلغ'])
+'<ul><li><strong>IVA مبكرة:</strong> إن كان واضحاً أنك لن تتعافى يمكن الطلب بين الأسبوع 3 والأسبوع 68.</li><li><strong>تأخير:</strong> مدة القرار مؤقتاً 16 أسبوعاً، والحكومة (23 يونيو 2026) تتوقع تراكم 100–150 ألف ملف حتى 2030. قدّم في الوقت وتابع.</li><li><strong>Wajong</strong> لمن أصبح عاجزاً قبل 18 أو أثناء الدراسة: حتى 70% أو 75% من الحد الأدنى (للشباب).</li></ul>'
'<h2 id="tips">نصائح عملية</h2><ol><li>احتفظ بنسخ من كل المراسلات وخطة العمل.</li><li>شارك في إعادة الإدماج؛ عدم التعاون قد يوقف الأجر أو الإعانة.</li><li>غير موافق على قرار؟ اعتراض (bezwaar) خلال 6 أسابيع.</li><li>بعد انتهاء العقد بلا صاحب عمل: راجع أيضاً <a href="/articles/unemployment-benefit-ww.html">WW</a> و<a href="/articles/social-assistance-bijstand.html">المساعدة الاجتماعية</a>.</li><li>حقوقك العامة في <a href="/articles/employment-contracts-labor-law-2026.html">دليل عقود العمل</a>.</li></ol>'),
faq=[('كم يدفع صاحب العمل عند مرضي؟','70% على الأقل لمدة حتى سنتين؛ كثير من عقود CAO تدفع 100% في السنة الأولى.'),
('كم Ziektewet؟','70% من الأجر اليومي، بحد أقصى أجر يومي 309.91 يورو؛ 100% في الحمل أو التبرع بعضو.'),
('مرضت بعد انتهاء عقدي، ماذا أفعل؟','إن كان خلال 4 أسابيع اتصل بـUWV بحلول اليوم الثاني.'),
('مرضت وأنا على WW؟','بلّغ عبر Mijn UWV؛ WW تستمر 13 أسبوعاً ثم Ziektewet.'),
('متى أقدّم WIA؟','تصلك رسالة في الأسبوع 88؛ قدّم قبل الأسبوع 93.'),
('ما الفرق بين WGA وIVA؟','WGA لعجز جزئي أو مؤقت (35–80%)، IVA لعجز كامل دائم (80%+).')],
src_note='راجعنا UWV وRijksoverheid في 5 أكتوبر 2026. الحد الأقصى للأجر اليومي يتغير كل يناير ويوليو. الأمثلة توضيحية.')
NL=dict(title='Ziek en arbeidsongeschikt in 2026: loondoorbetaling, Ziektewet en WIA stap voor stap — met rekenvoorbeelden',
crumb='Ziektewet en WIA',
desc='Uitgebreide gids: wie betaalt bij ziekte (werkgever tot 2 jaar minimaal 70% of UWV via de Ziektewet), ziekmelden, 70% van het dagloon met maximum € 309,91, de tijdlijn tot week 104 en daarna WIA (WGA en IVA), met rekenvoorbeelden en FAQ.',
summary='<ol><li><strong>In dienst:</strong> werkgever betaalt tot <strong>104 weken</strong> minimaal <strong>70%</strong>.</li><li><strong>Zonder werkgever</strong> (einde contract, WW, uitzendkracht): <strong>Ziektewet</strong> = <strong>70%</strong> van het dagloon (100% bij zwangerschap/orgaandonatie), maximum dagloon <strong>€ 309,91</strong>.</li><li>Na ca. 2 jaar: <strong>WIA</strong> — aanvragen vóór week 93; beslistermijn tijdelijk <strong>16 weken</strong>.</li><li>WGA bij 35–80%, IVA bij 80%+ duurzaam (75%).</li></ol>',
body=(
'<h2 id="who">Wie betaalt bij ziekte?</h2>'
+T([['Werknemer in dienst','Werkgever (loondoorbetaling)','Tot 104 weken, min. 70% (vaak 100% in jaar 1 via cao)'],['Ziek bij of binnen 4 weken na einde dienstverband','UWV · Ziektewet','Bel UWV uiterlijk op de 2e ziektedag'],['In de WW','UWV','WW loopt eerste 13 weken door, dan Ziektewet; meld via Mijn UWV'],['Uitzendkracht met uitzendbeding','UWV · Ziektewet','Bureau meldt uiterlijk dag 4'],['Zwanger of orgaandonor zonder werkgever','UWV','100% dagloon']],['Situatie','Wie betaalt','Let op'])
+'<h2 id="amount">Hoogte Ziektewet</h2><ul><li><strong>70%</strong> van het dagloon; week = × 5, maand ≈ × 21,75.</li><li>Maximum dagloon <strong>€ 309,91</strong> ⇒ max. ca. <strong>€ 216,94</strong> per dag.</li><li>Wachtdagen (1–2) alleen in specifieke gevallen.</li><li>Maximaal <strong>104 weken</strong>.</li></ul>'
'<h2 id="examples">Rekenvoorbeelden (illustratief)</h2>'
+T([['Yasser, tijdelijk contract afgelopen terwijl ziek, dagloon € 120','€ 84/dag ⇒ ≈ <strong>€ 1.827 bruto/maand</strong>'],['Dina, uitzendkracht, dagloon € 95','€ 66,50/dag ⇒ ≈ <strong>€ 1.446</strong>'],['Karim, dagloon € 350','Begrensd op € 309,91 ⇒ € 216,94/dag ⇒ ≈ <strong>€ 4.718</strong>'],['Salma, zwanger, geen werkgever, dagloon € 100','100% ⇒ ≈ <strong>€ 2.175</strong>'],['Omar, vast contract, salaris € 3.000','Werkgever betaalt min. 70% = € 2.100 (vaak 100% via cao); geen Ziektewet']],['Situatie','Uitkomst'])
+'<p>Namen en bedragen zijn illustratief, geen echte personen. Bruto bedragen.</p>'
'<h2 id="timeline">Tijdlijn twee ziektejaren</h2>'
+T([['Dag 1–2','Ziekmelding'],['Week 6','Probleemanalyse bedrijfsarts (werknemers)'],['Week 8','Plan van aanpak binnen 2 weken; elke 6 weken evaluatie'],['Week 13','Ziektewet: probleemanalyse UWV binnen 13 weken'],['Week 26, 52, ca. 78','Evaluaties; na week 44 mogelijk EZWb'],['Week 88','WIA-brief UWV'],['Vóór week 93','WIA aanvragen'],['Week 104','Einde wachttijd']],['Moment','Wat'])
+'<h2 id="wia">WIA na twee jaar</h2>'
+T([['WGA','35–80%, of 80%+ met kans op herstel','Loongerelateerd: 75% eerste 2 maanden, daarna 70%; 3 maanden tot 2 jaar'],['IVA','80%+ en duurzaam','Min. 75% van het WIA-maandloon tot AOW'],['Onder 35%','Geen WIA','Werkgever of werk/WW']],['Soort','Voor wie','Hoogte'])
+'<ul><li><strong>Vervroegde IVA</strong>: aanvragen tussen week 3 en week 68 bij geen kans op herstel.</li><li><strong>Wachttijd</strong>: beslistermijn tijdelijk 16 weken; Rijksoverheid (23 juni 2026) verwacht 100–150 duizend wachtenden tot 2030.</li><li><strong>Wajong</strong>: max. 70% of 75% van het (jeugd)minimumloon.</li></ul>'
'<h2 id="tips">Praktische tips</h2><ol><li>Bewaar alle correspondentie en het plan van aanpak.</li><li>Werk mee aan re-integratie.</li><li>Bezwaar binnen 6 weken.</li><li>Zie ook <a href="/nl/articles/unemployment-benefit-ww.html">WW</a> en <a href="/nl/articles/social-assistance-bijstand.html">bijstand</a>.</li><li><a href="/nl/articles/employment-contracts-labor-law-2026.html">Arbeidscontracten</a>.</li></ol>'),
faq=[('Hoeveel betaalt mijn werkgever bij ziekte?','Minimaal 70% tot 2 jaar; vaak 100% in jaar 1 via cao.'),
('Hoe hoog is de Ziektewet?','70% van het dagloon, max. dagloon € 309,91; 100% bij zwangerschap of orgaandonatie.'),
('Ziek na einde contract?','Binnen 4 weken: bel UWV uiterlijk op de 2e ziektedag.'),
('Ziek in de WW?','Meld via Mijn UWV; WW loopt 13 weken door, dan Ziektewet.'),
('Wanneer WIA aanvragen?','Brief in week 88; aanvragen vóór week 93.'),
('Verschil WGA en IVA?','WGA bij gedeeltelijk/tijdelijk (35–80%), IVA bij volledig duurzaam (80%+).')],
src_note='Gecontroleerd bij UWV en Rijksoverheid op 5 oktober 2026. Maximum dagloon wijzigt per januari en juli. Voorbeelden illustratief.')
