from a_student_finance import T
SLUG='zorgtoeslag-guide'
SRC=[('Dienst Toeslagen · Kan ik zorgtoeslag krijgen?','https://www.belastingdienst.nl/wps/wcm/connect/nl/zorgtoeslag/content/kan-ik-zorgtoeslag-krijgen'),
('Dienst Toeslagen · Hoeveel zorgtoeslag krijg ik? (tabel 2026)','https://www.belastingdienst.nl/wps/wcm/connect/nl/zorgtoeslag/content/hoeveel-zorgtoeslag'),
('Dienst Toeslagen · Maximaal inkomen zorgtoeslag','https://www.belastingdienst.nl/wps/wcm/connect/nl/zorgtoeslag/content/maximaal-inkomen-voor-zorgtoeslag'),
('Dienst Toeslagen · Maximaal vermogen zorgtoeslag','https://www.belastingdienst.nl/wps/wcm/connect/nl/zorgtoeslag/content/maximaal-vermogen-zorgtoeslag')]
single=[['29,500','129'],['30,500','120'],['31,500','109'],['32,500','97'],['33,500','86'],['34,500','74'],['35,500','63'],['36,500','51'],['37,500','40'],['38,500','28'],['39,500','17'],['40,500','6'],['41,000+','0']]
couple=[['29,500','246'],['32,000','221'],['35,000','186'],['38,000','152'],['40,000','129'],['43,000','95'],['45,000','72'],['48,000','37'],['50,000','15'],['51,000','3'],['51,500+','0']]
def tbl(rows,h,nl=False):
    if nl: rows=[[r[0].replace(',','.'),r[1]] for r in rows]
    return T(rows,h)
AR=dict(title='Zorgtoeslag 2026: هل تستحقها؟ حدود الدخل والأصول والمبالغ الفعلية بالجدول',
crumb='Zorgtoeslag',
desc='دليل zorgtoeslag لعام 2026: شروط الاستحقاق، حد الدخل (40,857 يورو للأعزب و51,142 مع الشريك)، حد الأصول، جدول المبلغ الشهري الرسمي، أمثلة محسوبة، وأخطاء تؤدي إلى استرداد المبلغ.',
summary='<ol><li>Zorgtoeslag مساهمة حكومية في تكلفة التأمين الصحي. شروطها: تأمين صحي هولندي، عمر 18 فأكثر، دخل غير مرتفع، وأصول غير مرتفعة.</li><li>في 2026 يجب ألا يتجاوز دخلك <strong>40,857 يورو سنوياً</strong> (51,142 مع شريك البدلات)، وألا تتجاوز أصولك في 1 يناير <strong>146,011</strong> يورو (184,633 مع الشريك).</li><li>أعلى مبلغ شهري في الجدول الرسمي <strong>129 يورو</strong> للفرد و<strong>246</strong> للشريكين، وينخفض كلما ارتفع الدخل.</li><li>المبلغ الذي تتلقاه شهرياً <strong>دفعة مقدّمة</strong>؛ بعد نهاية السنة يُحسب المبلغ النهائي وقد تُطالَب بإعادة جزء.</li><li>قسط تأمينك لا يحدد قيمة البدل؛ دخلك هو الذي يحدده.</li></ol>',
body=(
'<h2 id="who">من يستحق Zorgtoeslag؟</h2><p>تذكر Dienst Toeslagen أربعة شروط أساسية: أن يكون لديك <strong>تأمين صحي هولندي</strong>، وألا يكون دخلك مرتفعاً، وألا تكون أصولك مرتفعة، وأن يكون عمرك <strong>18 سنة فأكثر</strong>. لا تستطيع طلب البدل إلا بعد أن تكون قد أبرمت التأمين فعلاً. بعد بلوغ 18 تصبح ملزماً بتأمين خاص بك وقد تستحق البدل.</p>'
'<aside class="notice">القاعدة التي يخطئ فيها كثيرون: البدل لا يتوقف على <em>قسط</em> تأمينك. تقول Dienst Toeslagen إنه لا يعتمد على القسط الذي تدفعه. الذي يحدده هو دخلك (ودخل شريك البدلات) ووضعك.</aside>'
'<h2 id="limits">حدود الدخل والأصول لعام 2026</h2>'
+T([['الدخل السنوي (toetsingsinkomen)','<strong>40,857</strong> يورو','<strong>51,142</strong> يورو (معاً)'],['الأصول (vermogen) في 1 يناير 2026','<strong>146,011</strong> يورو','<strong>184,633</strong> يورو (معاً)']],['المعيار','بدون شريك بدلات','مع شريك بدلات'])
+'<ul><li><strong>Toetsingsinkomen</strong> تقريباً دخلك الإجمالي السنوي (يكون عادةً أعلى قليلاً منه). التمويل الدراسي (studiefinanciering) لا يحتسب فيه.</li><li><strong>الأصول</strong> يُنظر فيها فقط إلى وضعك في <strong>1 يناير</strong>. إن ارتفعت أصولك بعد ذلك فلا يؤثر هذا في السنة نفسها، لكنه يؤثر في السنة التالية.</li><li><strong>شريك البدلات</strong> (toeslagpartner): قد يكون زوجك أو شريكاً مسجلاً أو من يسكن معك بشروط معينة. عندها يُجمع الدخل والأصول. اقرأ <a href="/articles/toeslagpartner-guide.html">دليل شريك البدلات</a> قبل أن تقرر من هو شريكك لدى Toeslagen.</li></ul>'
'<h2 id="table">كم ستحصل شهرياً؟ الجدول الرسمي 2026</h2><p>الجدول التالي مقتطف من جدول Dienst Toeslagen لعام 2026؛ القيمة المذكورة تنطبق على من يكون دخله حتى الرقم المذكور في العمود الأول (الجدول الكامل بخطوات 500 يورو على الموقع الرسمي).</p>'
'<h3>بدون شريك بدلات (يورو/شهر)</h3>'+tbl(single,['الدخل حتى (يورو/سنة)','البدل الشهري'])
+'<h3>مع شريك بدلات: الدخل المشترك (يورو/شهر)</h3>'+tbl(couple,['الدخل المشترك حتى','البدل الشهري للاثنين'])
+'<p>لاحظ أن الجدول يتناقص تدريجياً وليس فجأة: كل 500 يورو إضافية في الدخل تخفض البدل بنحو 6 يورو شهرياً.</p>'
'<h2 id="examples">أمثلة محسوبة</h2><ul><li><strong>موظف بدون شريك، دخله 32,000 يورو:</strong> البدل 103 يورو شهرياً، أي <strong>1,236 يورو سنوياً</strong> (103 × 12).</li><li><strong>نفس الموظف بعد زيادة تجعل دخله 38,500:</strong> البدل 28 يورو شهرياً = 336 يورو سنوياً. زيادة الدخل 6,500 يورو خفّضت البدل 900 يورو سنوياً (1,236 − 336)، فالبدل ليس خسارة بل تعويض يتقلص تدريجياً.</li><li><strong>زوجان دخلهما المشترك 45,000:</strong> 72 يورو شهرياً للاثنين = 864 سنوياً. ولو كان دخل أحدهما وحده فوق 41,000 لما استحق وحده شيئاً، لكن الحساب المشترك يعطيهما بدلاً، لأن حدّ الشريكين أعلى (51,142).</li><li><strong>دخل 41,000 للفرد:</strong> لا بدل.</li></ul>'
'<h2 id="apply">كيف تطلب Zorgtoeslag؟</h2><ol><li>أبرم تأميناً صحياً هولندياً أولاً (انظر <a href="/articles/health-insurance-newcomers.html">التأمين الصحي للقادمين الجدد</a>).</li><li>جهّز DigiD ثم افتح «Mijn toeslagen».</li><li>جرّب «proefberekening» الرسمية لتعرف مبلغك التقريبي قبل الطلب.</li><li>أدخل <strong>تقدير دخلك للسنة كلها</strong>، لا راتب شهر واحد. إن بدأت عملاً في منتصف السنة فاحسب دخل السنة بأكملها.</li><li>احفظ تأكيد الطلب والقرار.</li></ol>'
'<h2 id="advance">دفعة مقدّمة وحساب نهائي</h2><p>تدفع Dienst Toeslagen نحو <strong>اليوم 20 من كل شهر</strong>، والمبلغ المدفوع <strong>دفعة مقدّمة</strong>. بعد انتهاء السنة تُحسب القيمة النهائية بناءً على دخلك الفعلي. إن كان دخلك الفعلي أعلى مما قدّرته فقد يكون عليك إعادة جزء، وإن كان أقل قد تحصل على الفرق. لذلك:</p><ul><li>حدّث «Mijn toeslagen» عند أي تغيير في الدخل أو العمل أو الأسرة أو السكن.</li><li>إذا تغيّر وضعك مثل زواج أو انتقال شخص للسكن معك، اقرأ دليل <a href="/articles/toeslagen-income-update.html">تحديث الدخل في Toeslagen</a>.</li><li>إن اضطُررت لمغادرة هولندا فعادةً لا يبقى لك حق في البدلات؛ أبلغ Toeslagen.</li></ul>'
'<h2 id="mistakes">أخطاء شائعة</h2><ul><li><strong>تقدير الدخل بأقل من الواقع</strong> للحصول على مبلغ شهري أعلى؛ النتيجة غالباً استرداد في نهاية السنة.</li><li><strong>الاعتماد على أرقام سنة سابقة.</strong> حدود الدخل والأصول تتغير كل عام.</li><li><strong>نسيان الأصول في 1 يناير.</strong> مدخراتك في ذلك التاريخ هي التي تُحتسب، حتى لو أنفقتها بعد أيام.</li><li><strong>تجاهل شريك البدلات.</strong> عدم إدخاله لا يغيّر القواعد، لكنه قد يسبب تصحيحاً وطلب استرداد لاحقاً.</li><li><strong>الظن أن التأمين الأغلى يعني بدلاً أكبر.</strong> غير صحيح.</li></ul>'
'<h2 id="glossary">مسرد</h2><ul><li><strong>Zorgtoeslag:</strong> بدل التأمين الصحي.</li><li><strong>Toetsingsinkomen:</strong> الدخل الذي تعتمد عليه Toeslagen في الحساب.</li><li><strong>Vermogen:</strong> مجموع الأصول ناقص الديون، في 1 يناير.</li><li><strong>Toeslagpartner:</strong> شريك البدلات الذي يُحسب دخله وأصوله معك.</li><li><strong>Voorschot:</strong> الدفعة المقدّمة الشهرية.</li></ul>'),
faq=[('هل أستطيع الحصول على Zorgtoeslag قبل بلوغ 18؟','لا. تبدأ إمكانية الاستحقاق من بلوغ 18، حين تصبح ملزماً بتأمين خاص بك، ولا يمكن طلب البدل قبل إبرام التأمين.'),
('هل يعتمد المبلغ على قسط التأمين؟','لا. المبلغ يعتمد على دخلك (ودخل شريك البدلات) ضمن جدول رسمي، لا على القسط الذي تدفعه.'),
('ما هو أعلى مبلغ في 2026؟','حسب الجدول الرسمي: 129 يورو شهرياً للفرد و246 يورو شهرياً للشريكين في أدنى شريحة دخل.'),
('هل تُحتسب مدخراتي في كل شهر؟','لا. يُنظر في الأصول إلى وضعك في 1 يناير فقط.'),
('ماذا لو تغيّر دخلي خلال السنة؟','حدّث Mijn toeslagen في أقرب وقت؛ لأن المبلغ الشهري دفعة مقدّمة والحساب النهائي يُجرى بعد انتهاء السنة.')],
src_note='راجعنا هذه الصفحات الرسمية في 4 أكتوبر 2026 (أرقام 2026). الحدود تتغير سنوياً؛ استخدم الصفحة الحالية وأداة proefberekening.')
NL=dict(title='Zorgtoeslag 2026: heb je recht? Inkomens- en vermogensgrenzen en de officiële bedragen',
crumb='Zorgtoeslag',
desc='Gids over zorgtoeslag 2026: voorwaarden, inkomensgrens (€ 40.857 alleenstaand, € 51.142 met toeslagpartner), vermogensgrens, de officiële maandtabel, uitgewerkte voorbeelden en fouten die tot terugbetalen leiden.',
summary='<ol><li>Zorgtoeslag is een bijdrage van de overheid aan je zorgverzekering. Voorwaarden: Nederlandse zorgverzekering, 18 jaar of ouder, geen te hoog inkomen en geen te hoog vermogen.</li><li>In 2026 mag je inkomen niet hoger zijn dan <strong>€ 40.857 per jaar</strong> (€ 51.142 met toeslagpartner) en je vermogen op 1 januari niet hoger dan <strong>€ 146.011</strong> (€ 184.633 samen).</li><li>Het hoogste maandbedrag in de officiële tabel is <strong>€ 129</strong> alleenstaand en <strong>€ 246</strong> samen, en daalt naarmate je inkomen stijgt.</li><li>Wat je maandelijks krijgt is een <strong>voorschot</strong>; na afloop van het jaar volgt de definitieve berekening en moet je soms iets terugbetalen.</li><li>De hoogte van je premie bepaalt de zorgtoeslag niet; je inkomen wel.</li></ol>',
body=(
'<h2 id="who">Wie heeft recht op zorgtoeslag?</h2><p>Dienst Toeslagen noemt vier basisvoorwaarden: een <strong>Nederlandse zorgverzekering</strong>, geen te hoog inkomen, geen te hoog vermogen en een leeftijd van <strong>18 jaar of ouder</strong>. Je kunt pas aanvragen als je de verzekering hebt afgesloten. Vanaf je 18e moet je een eigen verzekering hebben en kun je mogelijk zorgtoeslag krijgen.</p>'
'<aside class="notice">Een veelgemaakte denkfout: de zorgtoeslag hangt niet af van de <em>premie</em> die je betaalt. Dienst Toeslagen zegt dat het bedrag niet afhankelijk is van de premie. Je inkomen (en dat van je toeslagpartner) en je situatie bepalen het bedrag.</aside>'
'<h2 id="limits">Inkomens- en vermogensgrenzen 2026</h2>'
+T([['Jaarinkomen (toetsingsinkomen)','<strong>€ 40.857</strong>','<strong>€ 51.142</strong> (samen)'],['Vermogen op 1 januari 2026','<strong>€ 146.011</strong>','<strong>€ 184.633</strong> (samen)']],['Grens','Zonder toeslagpartner','Met toeslagpartner'])
+'<ul><li><strong>Toetsingsinkomen</strong> is ongeveer je bruto jaarinkomen (meestal iets hoger). Studiefinanciering telt niet mee.</li><li><strong>Vermogen</strong>: alleen je situatie op <strong>1 januari</strong> telt. Wordt je vermogen daarna hoger, dan heeft dat pas het jaar erop gevolgen.</li><li><strong>Toeslagpartner</strong>: gehuwd, geregistreerd partner of iemand met wie je samenwoont onder bepaalde voorwaarden. Inkomen en vermogen tellen dan samen. Lees de <a href="/nl/articles/toeslagpartner-guide.html">gids over de toeslagpartner</a>.</li></ul>'
'<h2 id="table">Hoeveel krijg je per maand? De officiële tabel 2026</h2><p>Onderstaande tabel is een uittreksel uit de tabel van Dienst Toeslagen voor 2026; het bedrag geldt voor een toetsingsinkomen tot het genoemde bedrag. De volledige tabel in stappen van € 500 staat op de officiële site.</p>'
'<h3>Zonder toeslagpartner (€/maand)</h3>'+tbl(single,['Inkomen tot (€/jaar)','Bedrag per maand'],True)
+'<h3>Met toeslagpartner: gezamenlijk inkomen (€/maand)</h3>'+tbl(couple,['Gezamenlijk inkomen tot','Bedrag per maand samen'],True)
+'<p>De tabel loopt geleidelijk af: elke € 500 extra inkomen verlaagt de toeslag met ongeveer € 6 per maand.</p>'
'<h2 id="examples">Uitgewerkte voorbeelden</h2><ul><li><strong>Alleenstaande met € 32.000 inkomen:</strong> € 103 per maand = <strong>€ 1.236 per jaar</strong> (103 × 12).</li><li><strong>Dezelfde persoon na een loonsverhoging naar € 38.500:</strong> € 28 per maand = € 336 per jaar. Een stijging van € 6.500 kost € 900 aan toeslag per jaar (1.236 − 336): de toeslag loopt geleidelijk af en is geen valkuil.</li><li><strong>Stel met samen € 45.000:</strong> € 72 per maand samen = € 864 per jaar. Zou één van hen alleen meer dan € 41.000 verdienen, dan had die persoon alleen geen recht; samen geldt de hogere grens (€ 51.142).</li><li><strong>Alleenstaande met € 41.000:</strong> geen zorgtoeslag.</li></ul>'
'<h2 id="apply">Zorgtoeslag aanvragen</h2><ol><li>Sluit eerst een Nederlandse zorgverzekering af (zie <a href="/nl/articles/health-insurance-newcomers.html">zorgverzekering voor nieuwkomers</a>).</li><li>Zorg voor DigiD en open “Mijn toeslagen”.</li><li>Doe de officiële proefberekening voor een indicatie.</li><li>Vul je <strong>verwachte inkomen voor het hele jaar</strong> in, niet het loon van één maand. Begin je halverwege het jaar met werken, reken dan het volledige jaar.</li><li>Bewaar de bevestiging en het besluit.</li></ol>'
'<h2 id="advance">Voorschot en definitieve berekening</h2><p>Dienst Toeslagen betaalt rond de <strong>20e van elke maand</strong>; het bedrag is een <strong>voorschot</strong>. Na afloop van het jaar volgt de definitieve berekening op basis van je werkelijke inkomen. Was je inkomen hoger dan geschat, dan moet je mogelijk iets terugbetalen; was het lager, dan kun je bijbetaald krijgen. Daarom:</p><ul><li>Geef wijzigingen in inkomen, werk, gezin of woonsituatie direct door via Mijn toeslagen.</li><li>Zie ook <a href="/nl/articles/toeslagen-income-update.html">inkomen bijwerken bij Toeslagen</a>.</li><li>Verlaat je Nederland, dan heb je meestal geen recht meer op toeslagen; meld dit.</li></ul>'
'<h2 id="mistakes">Veelgemaakte fouten</h2><ul><li><strong>Inkomen te laag inschatten</strong> voor een hoger maandbedrag; vaak volgt dan terugbetaling.</li><li><strong>Cijfers van vorig jaar gebruiken.</strong> Grenzen veranderen jaarlijks.</li><li><strong>Vermogen op 1 januari vergeten.</strong> Dat moment telt, ook als je spaargeld kort daarna uitgeeft.</li><li><strong>Een toeslagpartner negeren.</strong> Dat leidt later vaak tot correcties en terugvorderingen.</li><li><strong>Denken dat een duurdere verzekering meer toeslag geeft.</strong> Dat klopt niet.</li></ul>'
'<h2 id="glossary">Begrippen</h2><ul><li><strong>Zorgtoeslag:</strong> bijdrage in de zorgverzekering.</li><li><strong>Toetsingsinkomen:</strong> inkomen waarop Toeslagen rekent.</li><li><strong>Vermogen:</strong> bezittingen min schulden op 1 januari.</li><li><strong>Toeslagpartner:</strong> partner wiens inkomen en vermogen meetellen.</li><li><strong>Voorschot:</strong> maandelijkse betaling vooraf.</li></ul>'),
faq=[('Kan ik zorgtoeslag krijgen vóór mijn 18e?','Nee. Je kunt vanaf je 18e recht hebben, als je een eigen verzekering moet hebben; aanvragen kan pas nadat je verzekerd bent.'),
('Hangt het bedrag af van mijn premie?','Nee. Het bedrag volgt uit je inkomen (en dat van je toeslagpartner) in een officiële tabel, niet uit de premie.'),
('Wat is het maximum in 2026?','Volgens de officiële tabel € 129 per maand alleenstaand en € 246 per maand samen in de laagste inkomensklasse.'),
('Telt mijn spaargeld elke maand mee?','Nee. Alleen je vermogen op 1 januari telt.'),
('Wat als mijn inkomen verandert?','Pas Mijn toeslagen zo snel mogelijk aan; het maandbedrag is een voorschot en na het jaar volgt de definitieve berekening.')],
src_note='Bronnen geraadpleegd op 4 oktober 2026 (cijfers 2026). Grenzen wijzigen jaarlijks; gebruik de actuele pagina en de proefberekening.')
